### ISSUE TITLE
Вернуть небольшой обзор будучи в крите.

### ISSUE THREAD

**Issue by hekko4** [ChaoticOnyx/OnyxBay#10]
Точно самое и с анестезией, нужно вернуть небольшой обзор вокруг себя. 
Также можно было бы выдать небольшой обзор Киборгам когда у тех закончилась батарейка, или же тех подстрелили ионкой.

**Comment by Epicus7** [comment]
Я против этого. Как по мне, так игрок, чей персонаж без сознания, не должен знать, что происходит с ним.

Как минимум, тут появляются всякие геймплейные возможности с похищениями.

**Comment by SukaYaEbalPridumivatImya** [comment]
> Я против этого. Как по мне, так игрок, чей персонаж без сознания, не должен знать, что происходит с ним.
> 
> Как минимум, тут появляются всякие геймплейные возможности с похищениями.

Тогда надо и убирать обзор, когда глаза завязаны или закрыты рукой.
