### ISSUE TITLE
Подписочная система в лодаут

### ISSUE THREAD

**Issue by Bulatm12** [ChaoticOnyx/OnyxBay#10015]
### Улучшение
Представляет собой внедрение подписочной системы в лодаут. Существующую систему с возможностью единоразовой покупки предмета навсегда за опиксы - подписочная система при этом **не отменяет**. Является решением Сената Оникса от 26.01.2023.

### Решение
В общем, надо сделать так, чтобы **донатеры**, в соответствии со своим **тиром подписки** - имели **временный доступ** (пока действует подписка) к предметам разных ценовых категорий в **лодауте**. То есть, им не надо их покупать, они для них доступны к использованию, но только, пока активна подписка.

Здесь расписано, к предметам какой категории - должны иметь доступ подписчики с тирами от **ученого** до **ассистента**:

**Ученый** - доступ к предметам за <=5 опиксов
**ХоС** - доступ к предметам за <=9 опиксов
**Капитан** - доступ к предметам за <=10 опиксов
**Волшебник** - доступ к предметам за <=15 опиксов
**Культист** - доступ к предметам за <=20 опиксов
**Ассистент** - доступ к предметам за <=100 опиксов

---

**_За закрытие этой задачи выставлена награда размером в 500 рублей!_**

_Чтобы получить награду необходимо открыть пуллреквест с улучшениями описанными в задаче, который пройдет ревью двух разработчиков билда. После того как пуллреквест будет принят, а данная задача будет закрыта, пишите Epicus#1570 (Discord) для получения вознаграждения._

* _Если вы хотите заняться данной задачей, то вы можете её забронировать на какое-то время, но в случае отсутствия активности, бронь будет сниматься._
* _Обратите внимания на комментарии к задаче. Там могут быть пояснения и уточнения о том как её следует выполнять._

**Comment by grvz200** [comment]
нам кассеты и бумбокса не хватает?

**Comment by Epicus7** [comment]
**За закрытие данной задачи выставлена награда размером в 500 рублей!**

Подробности в ОП-посте.

**Comment by kreeperHLC** [comment]
Открываю пока не выдана награда
