### ISSUE TITLE
Пускаю рантаймы в чарактер сетапе на постоянной основе

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1002]
### Описание бага
Чарактер сетап не сохраняется, load грузится через раз, и вообще каждое действие сопровождается рантаймом. У меня. Только. Почему-то.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Захожу на сервер.
2. Уже рантайм в чейнжлохах.

### Ожидаемое поведение
почините я не могу сейвить чаров жизнь боль

### Рантаймы
https://pastebin.com/6Bs4H6PJ

### Дополнительная информация
Повторю, работает онли у меня, у остальных людей вроде норм всё.

**Comment by TapKo4eB** [comment]
А ещё когда я на все кнопки тыкаю, сервер лагать начинает.

**Comment by Epicus7** [comment]
Сейвы - это боль, потому что у нас нет к ним доступа и не совсем понятно как дебажить.

На вскидку, чтобы решить подобные проблемы, надо удалять свои сохранения (особенно последние), если это возможно. Попробуй сам поудалять, пожалуйста. Если не получится - добавим способ очистки сохранений педалями.

Это чтобы решить для тебя лично. С конкретным руткозом надо разбираться еще.

**Comment by TapKo4eB** [comment]
Собираюсь удалить чара чтобы исправить баг.
@
Жму ресет/пишу имя
@
[14:27:04] Runtime in preferences_savefile.dm, line 46: bad output
usr: TapKo4eB (/mob/new_player) ([0x300016d]) (NULL) (0,0,0) (NULL) (tapko4eb)
usr.loc: *null*

-______-

@Epicus7

**Comment by PlinHost** [comment]
> не совсем понятно как дебажить

Дать +DEBUG редактировать сейвфайлы через client/Export и client/Import.

**Comment by TapKo4eB** [comment]
Ауе, пофикшено после обновления сервака до 512.1488
