### ISSUE TITLE
Абдукторы не могут дышать через баллон

### ISSUE THREAD

**Issue by Terydd** [ChaoticOnyx/OnyxBay#10049]
### Описание бага
Абдукторы не могут использовать баллоны для дыхания.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Заходим за абдуктора.
2. Снаряжаемся баллоном, маской, скафандром, чем угодно
3. Нажимаем internal кнопку интерфейса (ну та самая, с баллоном)
4. Видим сообщение в чате, что баллона нет. Даже если он есть. Умираем от ближайшей разгермы.

**Comment by Zert0X** [comment]
а им надо дышать?

**Comment by Terydd** [comment]
Надо, иначе лёгкие рвутся, в глазах темнеет и всё такое

**Comment by Zert0X** [comment]
Абдукторы выпилены #11479
