### ISSUE TITLE
Уникальные итемы для патронов

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1006]
https://www.patreon.com/chaoticonyx

Для каждого таера нужно придумать новый уникальный итем, который будут получать игроки в каждом раунде по желанию, если купили подписку.

На первых уровнях чисто что-то косметическое и не очень яркое, но с повышением уровня можно добавить геймплея, яркости, анимированности.

Итемы было бы неплохо привязать к типу таера, но сами типы еще обсуждаемы и могут измениться.

Решить это нужно до конца года.

**Comment by Cinericius** [comment]
Пока что активно обсуждается в дискорде.

**Comment by sweden-moose** [comment]
> Решить это нужно до конца года.

))

**Comment by HonkyDonky** [comment]
Не сказано до конца какого года. Так что всё ок.

**Comment by Epicus7** [comment]
Потеряло актуальность, т.к. появился платный лоадаут + предметы по подписке.
