### ISSUE TITLE
Цветные сообщения OOC для патронов

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1007]
https://www.patreon.com/chaoticonyx

Добавить патронам цветные сообщения OOC. Любой патрон может отключить эту функцию или выбрать цвет из таеров меньших, чем его.

Возможно, стоит придумать новый способ выделения админов в OOC.

_Нужно решить до конца года._

**Comment by Epicus7** [comment]
> Возможно, стоит придумать новый способ выделения админов в OOC.

1. Кастомизировать иконку OOC.
2. Раскрашивать донатерам не все сообщение, а только никнейм. У педалей подсвечивается все сообщение.

**Comment by Cinericius** [comment]
Если нормально выделить админов - можно, да.
В принципе можно даже кастомные цвета впилить, а не тиры.

**Comment by Epicus7** [comment]
В общем давайте запилим никнейм в цвет тира патрона (или меньшего тира). Сообщение остается синим. Так будем различать педалей и патронов.

Кастомный выбор цвета можно запилить как фичу для какого-то высокого уровня патрона.

**Comment by Cinericius** [comment]
В дискорде вроде решили за этот момент.
