### ISSUE TITLE
Откатить новую радиацию

### ISSUE THREAD

**Issue by Zert0X** [ChaoticOnyx/OnyxBay#10076]
Согласно опросам игроков и древним жалобам откатить радиацию:
https://github.com/ChaoticOnyx/OnyxBay/pull/9301
https://github.com/ChaoticOnyx/OnyxBay/pull/7686
https://github.com/ChaoticOnyx/OnyxBay/pull/9279
И что-то ещё если проебали

**Comment by TimErmolt** [comment]
А чё тут, одобрено или как? Вроде фича перед созданием этого иссуя через голосование в баги-и-идеи прошла, судя по истории сообщений в конфе. Давайте уже избавим билд от этого недоразумения.

**Comment by intercepti0n** [comment]
Ну избавь.

**Comment by FloweYStyle** [comment]
научи ревертать и избавлю

**Comment by TimErmolt** [comment]
Чуть позже сегодня попробую сделать.

**Comment by igorsaux** [comment]
Устарело + непонятно что конкретно относится к геймдизу
