### ISSUE TITLE
Смайлы в ООС для патронов

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1008]
Добавить в ООС возможность использовать смайлы и ограничить ее только для патронов.

Начиная с какого-то таера можно разрешить добавить свой смайлик или даже несколько.

_Нужно решить до конца года_

**Comment by Cinericius** [comment]
Возможность добавлять свои смайлы пахнет всякими гачами.
А вообще смайлы можно сделать, но надо тогда их оформить соответствующие, а в идеале сделать их на основе спрайтов известных объектов типа клованов и лимиток. Левые улыбочки и сердечки не нужны, дискасс

**Comment by Epicus7** [comment]
Я думаю для начала можно сделать левые улыбочки и сердечки из, например, гугловского набора эмодж юникодовских. Как это сделано здесь, на гитхабе - минимальный набор. В будущем при наличии людей, которые нарисуют, можно кастомизировать под станцию.

Свои смайлы, конечно, надо модерировать. Либо премодерация, либо опять же, как и с бумбосом - предупреждать, что фича мб отрублена при нарушении правил сообщества (спам, нсфв, запрещенная в РФ символика, в том числе свастика и т.д.).

**Comment by kreeperHLC** [comment]
Привет, на ТГ уже всё для гунчата сделано. Просто скопировать - вставить.

**Comment by Epicus7** [comment]
Полностью реализовано в после #1635
