### ISSUE TITLE
Убрать ивент аппендицита при отсутствии медиков/на тебя когда ты единственный медик

### ISSUE THREAD

**Issue by kreeperHLC** [ChaoticOnyx/OnyxBay#10086]
### Улучшение
Буквально бесполезное говно, которое заставляет тебя бежать проводить операцию.

### Решение
Сделать проверочки на количество онлайна и медиков.

**Comment by Bulatm12** [comment]
Скажите, кто такой NoneOfYourBsns и я отправлю ему 50 опиксов.
