### ISSUE TITLE
Порезать количество генокрадов

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#101]
Когда будет принят пулл и пушнуто все будет в релиз - крайне рекомендую руками поменять число генокрадов в раунде. До одного.
Одного такого генокрада вполне хватит.

**Comment by Fourest** [comment]
Не, хуйня, это вообще уберёт из режима весь смысл

**Comment by ZerlGray** [comment]
генокрад может создавать с новыми абилками новых генокрадов

**Comment by Epicus7** [comment]
Сейчас бы играть с одной ролью при онлайне в 50 человек. Может лучше не надо овербаффать чейнджей и добавить им больше взаимодействия друг с другом, а не уменьшать их количество?

**Comment by ZerlGray** [comment]
Идея была превратить чейнджей в аналог нечто. Концепт нечто подразумевал из себя наличие одного антага который может создавать новых. Короче с вопросами к панчу.

**Comment by ZerlGray** [comment]
Снизьте тогда хотя бы до двух.

**Comment by Fourest** [comment]
О, вот это годно, но это скорее для отдельного антага подойдёт, а не для обычный лингов

**Comment by Epicus7** [comment]
Количество генокрадов и трейторов должно определяться онлайном. Сейчас не определяется и это баг.

Не вижу смысла обсуждать количество генокрадов в абсолютных значениях без привязки к онлайну.

С моей точки зрения, на 50 человек должно быть 3-4 спецроли уровня трейтора/генокрада.

**Comment by ZerlGray** [comment]
Уровень генокрадов сместился в сторону эквивалентности оных нинже по силе.
Хотя справедливости ради, самое имбалансное пока было - это не дедстинг, а малая форма + армблейд. Малая форма удалена и замещена другой абилкой, менее... поломанной.

**Comment by ZerlGray** [comment]
Малой формы не будет. Ее заменит более интересная вещь.

**Comment by Fourest** [comment]
Какая именно?

**Comment by Cinericius** [comment]
ВНЕЗАПНАЯ
