### ISSUE TITLE
Кнопка для возвращения камеры абдукторов в начальную точку

### ISSUE THREAD

**Issue by Terydd** [ChaoticOnyx/OnyxBay#10106]
На данный момент есть ситуации, в которых камера абдукторов улетает со станции (со слов игроков).

Вероятно, можно было бы сделать кнопку, которая телепортировала бы камеру на начальную точку (сейчас они спавнятся на шаттле прибытия).

В качестве альтернативы можно запретить вормхолам и порталам переносить камеру.

Вероятнее всего проблема связана с порталами, вормхолами и всем прочим, что успешно тпшит глаз между уровнями. У ИИ тоже бывает подобная проблема, но у ИИ есть кнопка возвращения глаза к ядру.

**Comment by TomYoungers** [comment]
Да, у меня был такой баг, после этого невозможно вернутся на станцию.

**Comment by Zert0X** [comment]
Кнопку для ресета добавили
