### ISSUE TITLE
При старте за мима уменьшается игра

### ISSUE THREAD

**Issue by GoldFlame** [ChaoticOnyx/OnyxBay#1012]
### Описание бага
Зайдя под начало раунда за мима графическая часть игры дико уменьшается и уходит куда-то вправо. Помогает перезапуск игры.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Ставим мима в Setup Character -> Occupation.
2. Нажимаем "Ready", ждём начала раунда.
3. Если появляемся за мима - видим баг с очень уменьшенной графической частью игры.

### Ожидаемое поведение
Графическая часть игры уменьшается и уходит куда-то вправо.

**Comment by kreeperHLC** [comment]
Скрины?

**Comment by Epicus7** [comment]
Баг единичный или так каждый раз случается? За другие профы точно такого не происходит?

Оч странно, профессия не должна быть никак связана с отрисовкой.

**Comment by Epicus7** [comment]
Нет воспроизведения.

@HonkyDonky, в таких случаях надо бы плашку вешать, а еще лучше явно писать, что воспроизведения нет.
