### ISSUE TITLE
станы при кидании дубинки в людей

### ISSUE THREAD

**Issue by Srankl1n** [ChaoticOnyx/OnyxBay#1019]
### Улучшение
В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.
субджект. и это как минимум прикольная фича, да и будет чем убивать людей с энергощитами, если их баффнут

### Решение
Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы.
сабжект
### (Опционально) Альтернативы
Опишите альтернативы, о которых вы думали. Почему именно ваше решение является лучшим?
субьект

### [GameDisUPD:]
Добавляем с шансом 50% при ударе.

**Comment by Epicus7** [comment]
Осталось только попасть правильным концом.

Можно добавить с шансом в 50%.

**Comment by Cinericius** [comment]
Да, раньше (в том числе вроде на Голубее) было с шансом 50%. Почему нет.

**Comment by Cinericius** [comment]
Оп-пост дополнен
