### ISSUE TITLE
Разнерфить мокрые полы

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1023]
![image](https://user-images.githubusercontent.com/5204667/70763844-9e6c7880-1d66-11ea-8a82-a97b7f94b716.png)

Повышенный приоритет из-за спроса игроков.

_Дискордо-реквест от Stalker#6332_

**Comment by Cinericius** [comment]
Можно, разика в полтора.

**Comment by Epicus7** [comment]
Я думаю тут надо не в полтора... Секунд 20 мб, минимум. Если не целую минуту.

Думаю надо делать из расчета, чтобы можно было помыть тайлов 10 и они все оставались скользкими в один момент времени.

Мейк таблички грит эгейн!

**Comment by Cinericius** [comment]
В принципе соглы, можно и подольше.
