### ISSUE TITLE
Новый ивент: Прорыв труб с газом

### ISSUE THREAD

**Issue by kreeperHLC** [ChaoticOnyx/OnyxBay#10240]
#27
При старте выбирается рандомно несколько комнат (Именно комнат, а не коридоров, так он не будет слишком раздражающим), в которых прорвутся трубы газа. Труба не удаляется, надо будет просто прийти и прикрутить её обратно.
Обязательное условия: 2 инженера и хотя бы 10 онлайна.
Ивент малый.

**Comment by Tsurupeta** [comment]
Ивент: Блюбей?
