### ISSUE TITLE
Допиливание удобства после minor ghost QOL features

### ISSUE THREAD

**Issue by Kostil** [ChaoticOnyx/OnyxBay#10255]
Сейчас в гостэкзамайне из-за большого количества переключателей найти нужной в разы хуже и народ уже жаловался на это
К тому же, из-за этого нововведения пропал способ анализировать здоровье куклы в отдельное окно "ручным сканером гостов" (пкм > analyze heath)

### Улучшение
отсортировать функции через названия по функционалу, отделив тумблеры для ЛКМ от вариаций HUDов
примеры
toggleHUD GHOSTvision toggleHUD antagHUD  toggleHUD DARKvision toggleHUD MedicalHUD ToggleCheck Air Scan ToggleСheck Gas Scan ToggleСheck Health Scan
Таким образом разделив кнопки по функционалу в клиенте, от чего их станет проще искать из общего списка понимая, где они примерно могут быть.

Второе - вернуть исчезнувший гостовый analyze health. Его удобство - он открывал свой результат в отдельное окно, позволяя продолжать следить за чатом и смотреть нужную информацию, не выводя в сам чат гору текста. Да и активировался при выборе куклы на ПКМ. Опять же - меньше работы головой чтобы быстро чекнуть здоровье с гостов (а уж про то, что лкмкой попасть  сложнее чем пкм - отдельная фича, особенно если надо юзать турф)

### (Опционально) Дополнительная информация
Опционально - вернуть старые проверки одним кликом атмоса под собой, как это было до нововведения. Они просто были быстрее и удобнее с точки зрения быстрого проклика. Ты не мог их забыть выключить и нажимать на кнопку достаточно было один раз и они сразу проверяли под гостом. Новые проверки тоже хороши - позволяют чекать содержимое контейнеров, чего старая кнопка не могла

какается напрямую сюда, чтобы связаться с автором, так как по информации в дискорде он не обитает

**Comment by NoneOfYourBsns** [comment]
Интересно, спасибо за отзыв. Сегодня вечером займусь доработкой введенных мною механик.
