### ISSUE TITLE
Запросы на поставки с ЦК для карго

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1028]
![image](https://user-images.githubusercontent.com/5204667/70764389-885fb780-1d68-11ea-85cf-66f71a06927c.png)

Повышенный приоритет из-за спроса игроков
_Дискордо-реквест от vekotov#1486_

**Comment by Cinericius** [comment]
Уже делается и это хорошо:
#1046

**Comment by Epicus7** [comment]
22 лайка - такая себе поддержка по нынешним временам.

**Comment by Artemonim** [comment]
> 22 лайка - такая себе поддержка по нынешним временам.

Сейчас с фич требуют 50 лайков. Закрываем иссуй? 🙃

**Comment by DarkHunter7756** [comment]
Погоди. Два ПРа сдохли, бог любит троицу )

**Comment by kreeperHLC** [comment]
База по добавлению запросов одобрена
