### ISSUE TITLE
clickcatcher

### ISSUE THREAD

**Issue by sephirothseeker** [ChaoticOnyx/OnyxBay#10280]
@NoneOfYourBsns сломал clickcatcher, который теперь видно через пкм

**Comment by sephirothseeker** [comment]
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/107106680/d9918b17-8ce4-4add-9d0a-52a16cd26b75)

**Comment by NoneOfYourBsns** [comment]
Странно, что он сломался, сейчас изучу вопрос.
