### ISSUE TITLE
Мутация вирусов во время радиационного шторма

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1029]
![image](https://user-images.githubusercontent.com/5204667/70764587-09b74a00-1d69-11ea-8230-d0e2d35ba67d.png)

_Дискордо-реквест от FoxStein#9547_

**Comment by Cinericius** [comment]
Если только с низким шансом и вне техов, чтобы простуда и радшторм не превращали станцию в филиал Индии.
