### ISSUE TITLE
Улучшение слипера новыми деталями.

### ISSUE THREAD

**Issue by hekko4** [ChaoticOnyx/OnyxBay#103]
В общем, хочу знать, стоит ли делать следующее:

При улучшении определенной детали у слипера он начинает синтезировать в себе новые лекарства, скажем, к примеру, не Парацетамол, а Трамадол, а если ещё сильнее улучшить, то и вовсе Оксикодон. Ну и собственно там Бикардин, Келотин, Дермалин, Хиралин, Дексалин Плюс и может даже на последнем уровне Перидаксикон. 

Также при улучшение конденсатора в нём открывать новые уровни стазиса. К примеру не только X5, но и X10, X15, X20.

Лично я вижу в этом только плюсы:
- Новый смысл изучать что-то в РнД, ради того чтобы увеличить выживаемость экипажа.
- Упростит жизнь медикам. 
- Больше взаимодействий между РнД и медбеем.

Если нужно, скажите какие хотели бы вы видеть синтезы, и на каком уровне (от 2 до 4)

Если ненужно, объясните почему.

**Comment by Ruforce** [comment]
Хорошая вещь, просил ее еще со времен блюбея.

Добавляет работы РнД, а с учетом ограниченности ресурсов химдиспенсера - мастхев.

**Comment by Cinericius** [comment]
Чем больше разномастных применений у РнД - тем лучше.
