### ISSUE TITLE
Смена внешности для трейторов

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1033]
![image](https://user-images.githubusercontent.com/5204667/70764937-2738e380-1d6a-11ea-86f8-97ccb861736b.png)

_Дискордо-реквест от vekotov#1486_

**Comment by Firefroge** [comment]
Можно как костыль добавить "Шприц Муллигана", который раньше где-то был.
И если я не ошибаюсь, то на тг. Он менял твою внешность и имя.

**Comment by Cinericius** [comment]
На мой взгляд слишком казуальная хуйня. Для голоса есть войсченджер, для всего остального - неподача виду.
Плюс будут перекликания с генокрадами, а одинаковые роли - это плохо.

**Comment by Voldirs** [comment]
Лучше бы тогда запилить операцию в хирургии чем просто айтем.

**Comment by Cinericius** [comment]
Как вариант, да
