### ISSUE TITLE
Прометеи сломаны

### ISSUE THREAD

**Issue by koronoshka** [ChaoticOnyx/OnyxBay#1036]
### Описание бага
Превращение в прометея через зеленый экстракт слизней работает очень криво. По какой-то причине кто-то посчитал, что будет очень весело если существа после введения начнут медленно терять каждую конечность и мгновенно отращивать конечность прометея. И я не против если бы оно все работало, но зачастую когда голова мутировала и раса меняется на слизне-человека, туловище остается на пол пути превращения и просто удаляется из тела. Прометей может жить и функционировать без него, однако из-за этого он разрывается на куски от пары ударов и после смерти не остается экстракт ( в теории должен), бонусом это сказывается на отыгрыше персонажа. Все еще хуже когда человеку во время превращения может просто оторвать конечность и не восстановить ее.
### Воспроизведение
 1.Вкалываешь мутаген.(~30 единиц)
2. Ждем.
3. 80% существо становится прометеем без туловища
 10% становится нормальным прометеем
 10% у существа парализует ноги, его рука взрывается и оно должно продолжать свое жалкое существование как инвалид-мутант-киборг (чаще как труп)
Прямой зависимости между количеством мутагена и успешностью превращения не нашел, но скорее всего это как-то влияет.
### Ожидаемое поведение
Существо не превращается в бублик.
### Скриншоты

![image](https://user-images.githubusercontent.com/58358430/70818731-82f48280-1de5-11ea-9bec-1e4bba32eb76.png)
Мартышка отпочковывалась. Сквозь нее видно спинку стула.

### Дополнительная информация
Выпилите эту садистскую еблю с медленной заменой конечностей и багов не будет. Пусть мутаген меняет расу разом через определенное время.

**Comment by Epicus7** [comment]
Тело пропадает не из-за мутации, а из-за бодибилдов. Когда я их впиливал, я даже не знал что этих прометеев можно заспавнить как-то...

Все остальное - хехмда.

Пофиксил "пончикование" -> [почкование](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D1%87%D0%BA%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)
