### ISSUE TITLE
Добивания в грабе

### ISSUE THREAD

**Issue by PlinHost** [ChaoticOnyx/OnyxBay#1038]
### Улучшение
Проблема такая: шаблон фичреквеста очень сложный и грабы не очень смешные.

### Решение
Перенести с Блюбея добивания в грабе. Хз что делать с шаблоном.

### Альтернативы
Не переносить с Блюбея добивания в грабе. И так  неплохо кормят.

### Дополнительная информация
Реквест не мой, я тут мимо примус починял.

**Comment by Cinericius** [comment]
Можно, если в самом последнем грабе и не мгновенно, а секунд 5-7.

**Comment by Fritcher36** [comment]
Лучше сделать не добивание мгновенной СМЭРТЬЮ, а удары, наносящие много урона и имеющие эффект в зависимости от способа их нанесения. Казнь пистолетиком офкорс летальна, а вот добивающий удар холодным оружием не по голове и туловищу должен просто калечить/отрубать конечность, давая возможность пафосных добиваний, а не просто убийства.

**Comment by dnivji** [comment]
Частично решено Тоби в его боевке. Может, закрыть? @PlinHost

**Comment by TobyThorne** [comment]
Уже впилили всякие перерезания горлов, вырывания сердцев и стрельбу в роты в грабе. Кажется, иссуй уже перевыполнен.
