### ISSUE TITLE
ФИЧА: Реворк режима культа по мотивам F&H

### ISSUE THREAD

**Issue by Judge1987** [ChaoticOnyx/OnyxBay#10394]
### Улучшение
Итак: думаю, многие согласятся, что обычный каноничный Нар'Си довольно скуден, скучен и не несёт за собой какого-то интересного бэкграунд. Условная НЁХ из космоса, словно для заглушки. Это довольно примитивная и словно не несущая за собой какую-то вразумительную отсылку часть игры, да и режим Культа как-то совсем **НИКАКОЙ**.

### Решение
Что же я предлагаю? У нас же как раз год-два как вышла замечательная финская дилогия Fear & Hunger, которая:
а) Изобилует Древними Богами Мироздания (тм);
б) Прописала заранее многие способности для божественных сил;
в) Такая же пиксельная дрочильня, как SS13.

**Суть предлагаемой фичи:**
1. Скопипастить большую часть Богов из линейки игр Fear & Hunger. Уже даже спрайты есть, нужно лишь адаптировать их, пусть это и займёт некоторое время. Осквернение земли (_defile_) и черчение рун при этом никуда не уходят, меняются лишь сам Нар'Си на кого-то более знакомого, а также способности культистов;
2. Добавить возможность чертить сигилы разных Богов (о них далее), а также вырезать их сигилы на людях. Допустим, на руках — для каких-то активных способностей, вроде файрболла, а на туловище и лице — для пассивных баффов;
3. Если в раунд дропается режим культистов, то рандомным образом для местного культа выбирается некий **главный** Бог (**Гро-Горот** — бог разрушения, **Сильвиан** — богиня любви и плодородия, **Винушка** — бог природы, **Бог Страха и Голода** / **Бог Глубин** — бог эволюции и вдобавок насекомых и гниения, **Рхер** — бог-клоун, **Алл-Мер** — тупо Иисус, но жёстче и **Логика** — богиня машин). Он определяет то, какие базовые способности будут у культистов (о них далее), но остальные в теории тоже можно изучить;
4. Реворк способностей. Каждый Бог будет иметь свой ряд способностей, и то, какому Богу поклоняются культисты внутри раунда, будет иметь значение. Поклоняться сразу всем — можно, но сложно, так ещё и способности слабые будут. Для юзания способностей — нужно рисовать руны либо на руках, либо на листках, либо на полу. Использование соответствующее: если на руках, то отнимается стамина. Если на бумаге, то после использования она сгорает. Если на полу, то сколь угодно, но без возможности двигаться руну.

Итак, что может подойти для нашей любимой космодрочильни? Вот предлагаемые мной изменения.
Для начала, СПОСОБНОСТИ:
-  **Гро-Горот:**
1. **Увечья.** Наносит урон по конечностям. Требует 1-2 секунды для каста. Чем больше осквернено земли / больше культистов, тем выше шанс отсечения конечности; 
2. **Сфера тьмы.** Проджектайл, довольно сильный, наносит урон, в т.ч. по органам, может сбить с ног;
3. **Пиромантический трюк.** Пшик огнём в стиле огнемёта. Самая слабая, возможно, даже первичная способность;
4. **Некромантия.** ПОДЪЁМ! Оживляет трупы, у которых есть голова и которые не совсем уж сгнили. В них вселяются другие игрочки, причём необязательно именно тот, чей труп оживили. Действуют медленно, слабы, но зато будет чем заняться гостоте.

-  **Винушка:**
1. **Обожжённая земля.** Поджигает всё вокруг, включая кастующего. Чем выше сила культа, тем больше радиус поджога;
2. **Корни.** Откуда на станции появиться корням деревьев — загадка, однако вот они! Обвивают противника и не позволяют двигаться. При силе культа — ещё и сжимают жертву;
3. **Сожжение.** Файрбол с поджогом жертвы и стоящих вокруг людей. Просто, со вкусом;
5. **Цветок.** Суть: Берём труп жертвы культа и подселяем туда хилящее растение. Удобрение же.

-  **Сильвиан:**
1. **Шёпот любви.** Банальный хил и лёгкий анальгетик. Чем выше сила культа, тем больше он может хилить, вплоть до переломов;
2. **Лечящий глас.** Лечит всех вокруг, но не так сильно, как предыдущая способность. Также анальгетик;
3. **Феромоны.** Ролеплейная способность: кастуется на человека, отчего некоторое время всем окружающим пишется в чат что-то в стиле «Вы невольно обращаете внимание на красоту %космонавтик_нейм%!» Позволяет охмурять людей, если игрочки позволят;
4. **Призыв любви.** Самое смешное, но, думаю, внутри игры зайдёт: Промывка мозгов и сбивание оружие у противника в зелёный режим. Теперь борьба с попыткой в ERP выйдет на новый уровень.

-  **Алл-Мер:** Его способности будут доступны по-умолчанию при любом выбранном для культа Боге.
1. **Портал.** Тот же портал, что и у Нар'Си каноничного;
2. **Кровавый меч.** Конвертируем лишнюю кровь в неплохой так меч для резки космонавтов;
3. **Терновый венец.** Неснимаемый головной убор. Надеть на противника, отчего он будет вечно чувствовать боль и ужас от всех его грехов (сопровождать красными надписями в чате и орами боли космонавтика);
4. **Воду в вино.** Повод избить (или восславить?) культиста за то, что он заменил всю воду в баках на алкоголь.

-  **Рхер:**
1. **Карманное измерение.** Сабж. Довольно сильная способность, которая, по идее, должна позволить залезть в какой-нибудь сугубо культистский отнорок, где можно строить свои планы, эдакий хаб;
2. **Золотые врата.** Что-то вроде аналога **«Портала»**, но вместо руны на полу — нужно натурально вдвоём скастовать появление портала. Минус — требует хотя бы двух человек. Плюс — перемещение безболезненно;
3. **Психическая волна.** Вызывает дикую головную боль у жертвы. Или жертв, если способность будет по площади;
4. **Лунный ожог.** Кастуется на противника, находящегося в руне, нужно 2-3 культиста. Суть: Жертва превращается в полу-разумного мутанта с клешнями или ещё чем-то. А-ля жертвоприношение Рхеру.

-  **Бог Страха и Голода / Бог Глубин:**
1. **Власть над насекомыми.** Причина появления на станции пауков, жуков и прочих негодяев. Они ещё кусаются, отравляют и вообще противные;
2. **Приказ крысам.** Крысы начинают быть сильнее, крепче и больнее кусаться. Может, даже спрайт им растягивать ради такого?;
3. **Темнота глубин.** Лампочки вокруг кастующего начинают лопаться, погружая станцию во тьму насекомых и крыс;
4. **Трансформация.** Культист трансформируется понемногу в ебаку с клешнями и мышцами, но взамен перестаёт иметь возможность, скажем, носить скафандры.

- **Логика:**
1. **Красная арка.** Разряд тока, бьющий по противнику и станящий его, полагаю;
2. **EMP.** ЭМИ-выброс. Борьба против шлюзов, синтов и боргов;
3. **Рой мотыльков.** Вызов агрессивного к не-культистам моба, атакующего их. Может, использовать моба __manhack__?;
4. **Искусственная жизнь.** 3-4 культиста, руна, создание из жертвы на руне целого свободного борга с протоколом культа.

**Дополнение:** Также по каждому Богу можно добавить пассивную способность на гравировку рун на теле с помощью колюще-режущего инструментария. То бишь: на роже символ Гро-Горота — больше силы; Винушки — больше выносливости и больше болевой порог; Сильвиан — больше здоровья; Рхер — больше здоровья у мозга; Логика — сопротивление к току, токсинам, огню; Бог Глубин / Бог Страха и Голода — меньше хочешь кушать.

## КАК ЭТО ДОЛЖНО (?) ВЫГЛЯДЕТЬ В РАУНДЕ
1. **Начало раунда.** Случайным образом выбираются культисты и случайный Бог, кроме Алл-Мера, доступному всем по-умолчанию;
2. **Рядовая деятельность.** Осквернение станции, наём новых культистов среди персонала, скрытность, возможно — даже жертвоприношения, если религия позволяет. Чем больше земли осквернено и чем больше жертв принесено на рунах определённых богов, тем больше способностей доступно и сильнее они становятся;
3. **Обучение новым Богам (ОПЦИОНАЛЬНО).** Вижу два варианта для изучения иных богов: а) Выпросить книжку у библиотекаря; б) Начертить руну нужного Бога и принести жертву;
4. **Далее как обычно:** Использование способностей, война с охраной, прочее подобное. И это должно выглядеть в разы интереснее, учитывая способности культа, которые они могут развить.

Спасибо за уделённое время для чтения и извиняюсь за сумбур. Если я могу чем-то помочь в, допустим, спрайтинге, то постараюсь что-то сделать.

**Comment by Zert0X** [comment]
:feelsgood:

**Comment by Zert0X** [comment]
Вы придумали Дейти 2.0, а не культ 2.0

**Comment by Judge1987** [comment]
> Вы придумали Дейти 2.0, а не культ 2.0

Дык в Дейти 2.0 есть божество как играбельный персонаж, а тут таки нет. Тот же культ, но другой объект поклонения и способности.

**Comment by Zert0X** [comment]
таки для культа мало возможностей

**Comment by Terydd** [comment]
Культ с гибким выбором объедков поклонения и способностей.

**Comment by Zert0X** [comment]
У текущего культа: ~20 рун на одного бога и плюс приспешники, плюс айтемы
У твоего культа: 1 руна на каждого бога( итого 7), 4 способности на каждого бога(итого 28)
но с учётом того что культ поклоняется 1 богу. Итого 4 абилки и 1 руна

**Comment by Terydd** [comment]
> Если в раунд дропается режим культистов, то рандомным образом для местного культа выбирается некий главный Бог
 > Он определяет то, какие базовые способности будут у культистов (о них далее), но остальные в теории тоже можно изучить;

**Comment by Terydd** [comment]
Вероятно, имеет смысл сделать больше способностей и часть из них сделать уникальными при поклонении определённому богу. Типо, ты не можешь развить отношения со второстепенными так же сильно, как с главным, но некоторые мелкие способности поиметь можешь. Однако для такого варианта способностей и правда маловато

**Comment by Judge1987** [comment]
> Вероятно, имеет смысл сделать больше способностей и часть из них сделать уникальными при поклонении определённому богу. Типо, ты не можешь развить отношения со второстепенными так же сильно, как с главным, но некоторые мелкие способности поиметь можешь. Однако для такого варианта способностей и правда маловато

Ну вот тут согласен. Я подразумевал следующее: 
1. Основной Бог с баффом на его способности;
2. Вторичный Бог, способности слабее, но можно изучить. Например, Гро-Горотовцы могут изучить хилы Сильвиан, но они будут не такие уж сильные;
3. Третичный Бог. Первичные слабые способности, работают раз через раз.

> У текущего культа: ~20 рун на одного бога и плюс приспешники, плюс айтемы
> У твоего культа: 1 руна на каждого бога( итого 7), 4 способности на каждого бога(итого 28)
> но с учётом того что культ поклоняется 1 богу. Итого 4 абилки и 1 руна

Эй, я не говорил, что айтемы нужно отбирать. Я бы даже каждому типу культа прописал отдельный вид брони и оружия. Да и приспешником можно сделать, вызываемых из ебеней. Винушка может вызывать зверей, БСГ / Бог Глубин — разумных насекомых и крыс и так далее.

И да, хоть у Нар'Сишного культа много абилок, но они почти не используется никогда. По мне так лучше уж меньше, но эффективнее и понятнее.
