### ISSUE TITLE
Взять на руки макаку

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#1041]
### Описание бага
Если брать одну и ту же макаку на руки, то через какое-то время, при перетягивании ее на себя (интент: граб, если что) открывается окно раздевания/одевания макаки.

### Воспроизведение

1) Находим макаку
2) Берем ее в руки и дропаем, повторяем n раз
3) Если ошибку еще не видно, то садим в макаку какой-нибудь сикей, и начинаем с пункта 2
4) Вуаля, теперь можем наряжать макаку в платья даже в граб интенте

### Ожидаемое поведение
Макака в граб интенте должна браться при любых условиях, а в остальных трех интентах, соответственно, раздеваться.

**Comment by hard-res3t** [comment]
Дергал мартыху минут 5 грабом. Ничего не случилось. Вроде работает все как и должно.
А учитывая старость бага я думаю оно уже и чинено давно.
