### ISSUE TITLE
Ментальная связь с макакой

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#1042]
### Описание бага
Давайте лучше сразу к воспроизведению.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Находим макаку.
2. Грабаем ее одной рукой.
3. Второй рукой берем ее на руки.
3. Грабнутую макаку усаживаем на стул.
4. Видим ошибку N1: во второй руке остается фейковая макака.
5. Дропаем нафиг фейковую макаку, она, благо, обычно сама исчезает.
6. Крутимся персонажем вокруг своей оси.
7. Видим ошибку N2: макака начинает крутиться в ту же сторону, несмотря на то, что в пункте 3 мы ее уже отпустили и посадили на стул.
8. Повторите так еще с 10 макаками, и у вас будет целая оруппа подтанцовки. Можете не волноваться, если их убьют, ведь они будут вам подражать даже после смерти.

### Ожидаемое поведение
Я думаю, понятно, что фейковая макака должна исчезать при таких действиях, а сидящая на стуле - сидеть спокойно и не крутиться.

**Comment by Zert0X** [comment]
**Если кому интересно почему так происходит то вот ответ:**
1. По необъяснимым причинам у нас не спадает граб с моба после того как мы его взяли на руки.
2. По таким же необъяснимым причинам не убирается прок recursive_dir_set с ивента dir_set_event у макаки и та повторяет наши движения.

**Варианты решения:**
1. Убирать граб с моба насильно.
2. Разобраться почему не убирается прок.
