### ISSUE TITLE
Белый экран вместо интерфейса на устройствах, требующих прогрузки ресурсов.

### ISSUE THREAD

**Issue by GoldFlame** [ChaoticOnyx/OnyxBay#1043]
### Описание бага
При нескольких заходах в программу "Suit Sensors" появляется белый экран вместо интерфейса.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Находим компьютер/планшет. 
2. Скачиваем на него программу для мониторинга датчиков у игроков (если программа уже установлена - пропускаем пункт).
3. Запускаем эту программу с любого устройства.
4. Пару раз нажимаем на устройство с открытой программой - пропадает интерфейс и появляется иконка NT.
5. Ещё через пару нажатий на устройство с открытой программой монитор становится белым, как и дисплеи всех открываемых устройств. Помогает перезапуск.

### Ожидаемое поведение
Белый экран заместо прогруженного интерфейса на мониторах, ПДА, раздатчиках, автоматах и т.п.

### Скриншоты
![Скриншот](https://user-images.githubusercontent.com/22894602/70849953-35841e00-1e96-11ea-9662-fbcb44862a52.png)
![Скриншот](https://user-images.githubusercontent.com/22894602/70849960-3fa61c80-1e96-11ea-971d-3fc84cfc3549.png)

### (Опционально) Характеристики
 - OS: Windows 10
 - Версия клиента: 512
 - Версия сервера: c43ea5c08497527748e440d1de1ca9a00b55a27e - release/main - 2019-12-14
 - ID игры: b4H-ca22

**Comment by Doster-d** [comment]
На IE 8 встречал такое.

**Comment by TobyThorne** [comment]
Закрываю в пользу #2352, там обсуждение более информативное.

**Comment by Tsurupeta** [comment]
Эм....

**Comment by TobyThorne** [comment]
Поправил.
