### ISSUE TITLE
резист

### ISSUE THREAD

**Issue by Srankl1n** [ChaoticOnyx/OnyxBay#1047]
### Описание бага
если ты куда-либо сядешь/начнёшь развязываться/любое действие, которое срабатывает при клике на резист, то на тебя накладывается кликделей в 15!! (наверное) секунд, из-за чего, когда ты резко встаешь со стула через резист (если по стулу кликнуть, то ты встанешь без кликделея), ты вообще ничего не можешь делать.  ни взять предмет, ни кликнуть по другому человеку, либо другое действие, связанное с кликами

**Comment by PlinHost** [comment]
Вроде 2 секунды стоит, но это нужно выпилить и воткнуть в сами действия куда надо.

**Comment by Epicus7** [comment]
Ничего не понял, но очень интересно.
