### ISSUE TITLE
Шапки на ящерах выше, чем должны быть

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#105]

**Comment by ZerlGray** [comment]
Не только шапки. Даже прически у них сдвинуты. Весь спрайт сдвинут. А в положении лежа вообще все плохо.

**Comment by Fourest** [comment]
Может поставим новобеевский спрайт? Выглядит вроде прикольно, тупо жидорептилойды

**Comment by Epicus7** [comment]
Плохая идея

**Comment by Fourest** [comment]
Почему?

**Comment by Epicus7** [comment]
Потому что классические лучше

**Comment by Fourest** [comment]
Классические уже надоели, я хочу жидорептилоидов!

**Comment by Cinericius** [comment]
Мне кажется, это фиксили, но это не точно
