### ISSUE TITLE
Сторителлер: проработка основной идеи

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1050]
Перенести идею сторителлера вместо режима с Эриса.

Сторителлер - некая отдельная логика, которая в течение игры оценивает ситуацию на станции и влияет на ход игры с целью уменьшить/добавить экшена.

Оценивать ситуацию можно по таким событиям как убийства, ранения, стрельба, разгерметизации, количестве офицеров/инженеров/врачей/глав и т.д.

В зависимости от своего характера Сторителлер пытается поддерживать уровень экшена на некотором значении. Если уровень экшена ниже - добавляет ролей/спавнит ивенты. Если уровень экшена выше требуемого, то спавнит роли для ликвидации предыдущих ролей, спавнит ЕРТ, присылает специального решальщика проблем с НТ и т.д.

Сторителлер должен заменить собою понятие режима, выбираться голосованием игроков в конце каждого раунда и включать в себя все автоматические механики вмешательства в раунд, такие как раундстартовые события, мидлраундовые ивенты, режимы и автоспавн ролей после старта.

Начать стоит с самого сторителлера, простого механизма оценки обстановки на станции (например, ранения + роли + разгермы) и триггера ивентов в зависимости от обстановки.

**Comment by Cinericius** [comment]
Не уверен, что нам нужен именно эрисовский вариант, но сторителлер быть обязан.

**Comment by danxnader** [comment]
Как по мне легче динамик взять с ВГ. Короче, генерируется уровень опасности в начале раунда, который будет поддерживаться. Чем больше игроков, тем он больше. Разные антаги имею разный уровень опасности, и чем он больше разрушений он несёт, тем он соответственно и больше. Когда ролька умирает, очки убираются и рандом решает кому-бы выдать режим для восстановления.

**Comment by Cinericius** [comment]
Я честно пишу диздок, он вот почти уже готов наверное

**Comment by Epicus7** [comment]
По мотивам иссуя создан проект: https://github.com/ChaoticOnyx/OnyxBay/projects/15

Дальше работа будет идти по нему

**Comment by Shootnik01** [comment]
РИМВОРЛД!!!

**Comment by Shootnik01** [comment]
:D
