### ISSUE TITLE
СЕНАТ: Троттлинов рестрикнуть до мерчантов и станционных только за донат.

### ISSUE THREAD

**Issue by kreeperHLC** [ChaoticOnyx/OnyxBay#10500]
Решением сената свинолюди уходят под донат Грузчика.
Единственная возможность взять их без доната - взять за Торгаша.

**Comment by intercepti0n** [comment]
Кто впилит, тот гадюка.

**Comment by Doster-d** [comment]
Любой кто сделает задачу рискует получить темную

**Comment by Nod404** [comment]
тоби поступил умнее
выпилил их нахуй
