### ISSUE TITLE
Division генокрадов сломан к херам.

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1054]
### Описание бага
Способность геночек Division проебана.
Почему? Ну она смешно работает.
Как минимум я могу сказать что при её использовании на человеке, появляется второй голый хуман. Откуда? Я не ебу.
Ещё эта способность херого работает на уже мёртвых людях. Использовать можно, но тот же эффект что и раньше. Появляется второй непонятный голый человек и вообще ничего не происходит.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берём гено4ку.
2. Берём себе дивижн.
3. Используем на любом человеке.
4. Видим эффект.

### Ожидаемое поведение
Починить способность, чтобы работала нормально и безотказно.

### bonus clips
![image](https://user-images.githubusercontent.com/48761132/70911434-f6370800-2022-11ea-9dee-a9a1c489e655.png)

**Comment by Animesku** [comment]
![6c12e3b55cf933e4](https://user-images.githubusercontent.com/48406301/70911793-aefd4700-2023-11ea-87a0-7ca3c213f406.png)
Про голых хуманов-то правда..

**Comment by Cinericius** [comment]
Брух

**Comment by ZerlGray** [comment]
Красиво

**Comment by Cinericius** [comment]
А, оно уже есть, тогда #1210 можно закрыть

**Comment by ZerlGray** [comment]
Ну как, пофиксили, фиксеры? :)
