### ISSUE TITLE
Хардсьюты и способы их получения

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1055]
### Улучшение
В данный момент, для того, чтобы заиметь в своём арсенале такой предмет, как хардсьют (aka РИГ, ИКС), можно сделать всего две вещи: взять его с места, где он появляется на карте, а таких крайне немного, либо купить у торговцев. Оба эти варианта не слишком надёжны, из-за чего иногда найти хардсьют может быть затруднительно, ведь торговцев может не быть, в то время как взять его с точки появления мог кто-нибудь другой. Вырисовывается проблема: космонавтику позарез нужен вышеупомянутый костюм (например, СЕ слазить в запущенную материю, установить условные коллекторы или построить баньку в ядре реактора. Если исключить варианты с РИГом, то остаётся лишь возможность получить лютый урон от радиации или идти искать войдсьюты со свойством защиты от радиации, которых крайне мало в целом в игре, а на станции вообще нет), а получить его никак нельзя.

### Решение
Добавить возможность заказывать в карго за большое количество кредитов (например, за одну штуку в n раз большее, чем за ящик войдов аналогичной профессии) все стационарные ИКСы: EVA, улучшенный инженерный, AMI, СБ-вариант, медицинский вариант; заказа отдельных ящиков каждой спецификации с модулями, которые есть в этих костюмах на станции. Модули и сами РИГи отдельно, для удобства и баланса.

### Альтернативы
Можно добавить хардсьюты в научку: в протолат или сделать отдельную машину для распечатки костюмов, плату на которую можно изучить, но самой машины в РнД раундстартом нет. Естественно, сделав невероятный порог по научным уровням и ресурсам. Минусы этой альтернативы:
-РИГи из научного скорее всего выпилят в первые две недели, потому что 146% учёных будет использовать энергетические сетки, что не слишком красиво со стороны геймдизайна. Заказать же предмет в отделе доставки чуть сложнее, чем сделать три клика, стоя у научной консоли: тут и поговорить с завхозом нужно, и уговорить его что это так важно, а ещё решить проблему того, откуда взять лишние очки на это, попинав ксенобиологов или шахтёров.
С о ц и а л о ч к а, короче.
-Запихивать ИКСы в протолат - решение бедное на креативность, выглядеть будет криво. Запиливать отдельную машинерию под эту цель - слишком сложно для такого минорного улучшения.
-РнД, способное на создание этих костюмов, будет существовать лишь чуть чаще, чем появляются торговцы, продающие хардсьюты, а вот карго - надёжный, как швейцарские часы, вариант.

### [GameDisUPD:]
В карго за дохуиллион поинтов. В научку ненад.

**Comment by Fritcher36** [comment]
Хардсьюты имхо нужно оставить практически на таком же уровне редкости, разве что дать возможность их закупать за большией суммы, но сделать войдсьюты более играбельными. Они красиво и лампово выглядят, но емнип рвутся от плевка и слишком уж замедляют игрока. Лучше оставить харды тем, кто действительно сопряжен с риском: парамедикам медицинский, сб красненький, инженерам и атмостехам, а по станции вкинуть больше войдсьютов, начиная с скафандрового гардероба в каждом отделе и заканчивая гражданскими/синди в гетто или еще где. Я верю, что на станции, которая вполне может разгерметизироваться, должно быть больше скафандров, чем 20 экстренных из говна и палок, которые рвутся при нуле кпа.

**Comment by MrMagick2104** [comment]
> инженерам и атмостехам
>Оставить харды

У них так и так их нет, есть только один - СЕшный. О том, что надо бы пару EVA-РИГов пихнуть в ЕВА вместо войдов, и не говорится.
>практически на таком же уровне редкости, разве что дать возможность их закупать за большией суммы

Именно об этом я и пишу. Сейчас, если хардсьют, один на отдел, кто-то взял/потерял/украл/выкинул в космос/отдал учёным, заменить нельзя, иссуй об этом. То есть, даже если стоимость такового будет вычтена из жалования, а служить придётся пока не исполнится пятьсот десять лет, получить новый ИКС никак не выйдет.

**Comment by Fritcher36** [comment]
> 
> 
> > инженерам и атмостехам
> > Оставить харды
> 
> У них так и так их нет, есть только один - СЕшный. О том, что надо бы пару EVA-РИГов пихнуть в ЕВА вместо войдов, и не говорится.
> 
> > практически на таком же уровне редкости, разве что дать возможность их закупать за большией суммы
> 
> Именно об этом я и пишу. Сейчас, если хардсьют, один на отдел, кто-то взял/потерял/украл/выкинул в космос/отдал учёным, заменить нельзя, иссуй об этом. То есть, даже если стоимость такового будет вычтена из жалования, а служить придётся пока не исполнится пятьсот десять лет, получить новый ИКС никак не выйдет.

Тьфу блять, ты про РИГи. Я говорил о скафандрах с подсоединяемыми шлемом, магбутами и баллоном, лежащих в ЕВЕ на все отделы, в инженерке в количестве 6 штук, они емнип войдсьюты. РИГи как есть - так пусть и остаются максимально редкими, либо пусть полностью заменяют скафандры.  Я проебался с терминологией, поправил коммент. Всю станцию обмазать софтсьютами, войды оставить как есть, а хардсьюты и должны быть редкостью, разве что за мильён денег покупать.

**Comment by MrMagick2104** [comment]
>РИГи как есть - так пусть и остаются максимально редкими

Ещё раз говорю, проблема не в том, что они редкие, а в том, что они _незаменимые_. Если кто-то взял и, допустим, уничтожил хардсьют с концами, условно, сослав его в nullspace, то возможности просто взять и найти новый _нет_. Единственная возможность - купить у торговца, который спавнится с каким-то там шансом, бла-бла-бла, грубо говоря, вероятность того, что купить у него этот самый РИГ будет можно КРАЙНЕ МАЛА. И получается проблема такая же, как с операционными столами и стационарными анализаторами здоровья: они могут быть нужны, но построить их никак нельзя.

**Comment by Fritcher36** [comment]
Карго - вариант. Но я бы вместе с этим обратил внимание на общий баланс скафандров, хоть иссуй и не об этом.

**Comment by MrMagick2104** [comment]
>Но я бы вместе с этим обратил внимание на общий баланс скафандров, хоть иссуй и не об этом.

С балансом всё ясно, как бы. Софтсьюты - отстой, потому что неудобные, войдсьюты - отстой, но не такой сильный, потому что удобные, но замедляют и не защищают, а хардсьюты - отстой, потому что их нет. 
>Карго - вариант.

По поводу карго я как раз написал в иссуе.

**Comment by Fritcher36** [comment]
Иссуй предлагает несколько вариантов проблемы, я поддержал карго. С балансом неясно, потому что при всей своей отстойности софтсьюты редкие шописец, не считая экстренных, которых тоже дай бог полтора десятка по станции.

**Comment by Cinericius** [comment]
Можно tl;dr треда?

**Comment by MrMagick2104** [comment]
> Можно tl;dr треда?

Хардсьюты нигде нельзя найти на станции - оп пост, предлагается добавление их (РИГов) в карго или научку, в комментариях обсуждено что-то левое, связанное в целом со скафандрами и войдсьютами, но поддержан карго.

**Comment by Cinericius** [comment]
Вижу. В принципе научка тож вариант. Аппрув поставлю на оба.

**Comment by Voldirs** [comment]
Не надо в научку

**Comment by MrMagick2104** [comment]
> В принципе научка тож вариант

Вариант тоже, при том хороший, но тут с балансом проблема, повторюсь. В научке есть инвиз и сетки, которые можно использовать только с хардсьютом. Если его прямо туда и пихнуть просто в протолат, то будет кринжово как-то.

**Comment by Voldirs** [comment]
Риг это слишком мощный инструмент, чтобы получить риг с модулями должна быть сОцИаЛоЧкА или воровство

**Comment by MrMagick2104** [comment]
С другой стороны, юному учёному-манчкину придётся выбирать между тем, чтобы таскать с собой тонну лута в БоХе или только один РИГ.
Тем более, можно впилить какой-нибудь обрезанный РИГ, вроде хакерского, который не даёт защиты от вакуума, предварительно выпилив ему возможность установки той же сетки и инвиза.

**Comment by Voldirs** [comment]
Костыльно слишком звучит

**Comment by Cinericius** [comment]
Тады давайте только в карго за охуиллион поинтов

**Comment by MrMagick2104** [comment]
> Костыльно слишком звучит

Тогда можно закинуть сетку на уровень нелегала выше, чтобы просто взять и без делов с антагами её нормально сделать нельзя было, как с инвизом сейчас.
