### ISSUE TITLE
Куски какой-либо еды в ланчбоксе пропадают при попытке использования.

### ISSUE THREAD

**Issue by Traysoul** [ChaoticOnyx/OnyxBay#1056]
### Описание бага
Куски какой-либо еды в ланчбоксе пропадают при попытке использования.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Ставим в лодауте ланчбокс и выбираем там кусок(slice) чего-либо
2. Заходим в раунд
3. Пытаемся съесть кусок
4. Он пропадает и нам пишет: None of N slice left!

### Ожидаемое поведение
Жраться должно.

**Comment by Epicus7** [comment]
Он просто пустой (кусок еды), аналогичный баг с кусочками еды, которые спавнятся на карте: #631
