### ISSUE TITLE
Программа библиотеки в консоли крашит клиент

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#10572]
### Описание бага
Открываешь эту программу в консоли -- крашишься. При этом программа-то открывается, но любой, кто кликнет на консоль, пока она открыта, тоже улетает в краш.
Вестимо, сломалось либо что-то в интерфейсе программы, либо, что, как по мне, более вероятный вариант, кто-то залил туда какую-то книгу с хуёвым названием, которое и крашит дримсикер при попытке его отобразить. Надо посмотреть в БД и удалить эту херобору. Ну или починить билд.

**Comment by AnimeshkaTvar** [comment]
Он у меня крашил даже тогда, когда я ворд на библиотечной консоли открыл. Причем в начале раунда такой проблемы не было

**Comment by TimErmolt** [comment]
ИСПРАВЛЕНО удалением следующей книги:

> ADMIN LOG: TheUnknownOneBYND/(Odaycel Sombreifni) has deleted the book: [724] "Х.Яоцзы. 'Общая хирургия'. Аппендэктомия" by Хэ Яоцзы

На будущее: не заливайте в библиотеку книги с апострофами в названии. Иначе программа опять начнёт крашить клиент до удаления этой книги. Ин факт, надо бы отдельный иссуй открыть по этому поводу.
