### ISSUE TITLE
Добавить крышам уникальный спрайт

### ISSUE THREAD

**Issue by kreeperHLC** [ChaoticOnyx/OnyxBay#10590]
### Улучшение
Сейчас для крыши используются спрайты укреплённого пола, что сильно сбивает с толку (Плюсом я иногда видел что там используются плейтинги). 
Так получим и плюс к пониманию что это крыша и к красоте. 

Требования к спрайту: Спрайт должен быть не статичным, а как ковры соединяться друг с другом.

**Comment by ArmenianOnyx** [comment]
я ни разу не видел крышу
