### ISSUE TITLE
Психические заболевания и не только

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#106]
Собственно, я тут готовлю большой прожект с психболячками и не только. Мне нужны от вас идеи, какие болячки или специфические состояния психики вы хотели бы видеть. Шизу, паранойку, биполярку, посттравматику, депру и ОКР предлагать не надо, тантрум и панические атаки тоже есть, религии и бредовые культы тоже. И даже ЛОЯЛИЗМ предусмотрен.
Нужно что-то свежее и неочевидное, возможно, доселе в психиатрии невиданное.

**Comment by Fourest** [comment]
Это надо самому отыгрывать, нахуй нам надо запиливать это виде механа?

**Comment by Cinericius** [comment]
Чтобы был ФАН и работа психиатру.
Да и запилено оно будет в виде строчек текста вроде законов ИИ (ну и некоторые состояния типа панических атак будут еще какой-то физиологический эффект иметь), так что простор для отыгрыша вполне себе останется.

**Comment by Epicus7** [comment]
Ты же пропишешь в этот прожект еще нашего клоуна?

**Comment by Cinericius** [comment]
В смысле клоуна? Техтоннельного что ли?

**Comment by Epicus7** [comment]
Ну да, который в шкафу спавнится с веселыми целями.

**Comment by Cinericius** [comment]
Закрываю, прожект скоро будет, а идей вы так и не предложили, поэтому будет только всякая банальщина.
