### ISSUE TITLE
Набор кринжемаппинга проводов и труб Фоксхола

### ISSUE THREAD

**Issue by No-Tips** [ChaoticOnyx/OnyxBay#10621]
**С концептом "1 отсек - один основной вход для коммуникаций" не справились? Как ты предполагаешь на этой карте ограничивать движение газов в определенные отсеки/ограничивать передвижение ксеноморфов/ограничивать движение людей в гаччисьютах?**

злевел1
 Хуево проложенные трубы

Проложить по низу синюю трубу, сдвинуть на тайл ниже шлюз, упереть переход на З левел в угол.
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/504ff992-d899-429b-b00c-15c72a342279)

Хз, поставить нормально симметрично венты и скрабберы, а не в стиле пьяного воина?
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/c1e79b2f-a2ec-4e33-ae1a-bd6324d324fc)

Добавь еще один скраббер/убери еще один вент?
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/16f6d9b7-e6d7-4b6d-8ad8-6bc16abde9ae)

Ижектор посреди комнаты конечно смешно, но подвинь хз, на тайл НАВЕРХ?
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/852f1ee1-d399-459f-91e4-9315dd98085d)

Проебал вообще трубы в химии
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/feb2f55a-42fb-4837-ae30-4748fa306a03)

Выход в космос - нет никакой возможности перекачать воздух в шлюз
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/f7a16583-a76b-494b-8593-da0f5482b20d)

сейм хир
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/f93f7bfe-bb59-4c0b-98aa-767e9ddfe50c)

и хир
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/68dc2232-0739-4b0f-b522-f291f482c8b7)

Хуево проложенные провода:

Почему смес питается лишь от одного тэга (а стоп даже от него не питается потому что ты там провод забыл в другую сторону).
Провода под стеклами можно со спокойно душой провести на левый или правый шлюз.
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/98df597b-77c5-4b01-8f98-61b3a9388887)

Макароны можно разобрать, поменяв местами СМЕСы и стореджи
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/877f52c3-2685-4962-ae71-1fb535355467)

ааа ты как запитал АТМОС ааааа
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/a3714429-9c20-421b-8041-5f93e0e8a426)

Забыл про вент и скраббер в чекпоинте:
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/92c8eb3b-cbe4-479b-9e76-d647672e0165)

Видимо потерялся в пространстве когда думал куда тут поместить скрабберы и венты:
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/4e73e237-d9de-4ef6-8ec5-faa1e5b4d3bf)

подпункт КОММУНИКАЦИИ НЕ ПО ОДНОМУ ТАЙЛУ
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/8877b6d4-bdbc-4807-8a72-b28331cbace8)

![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/c4bc3045-dd97-43bd-a83b-e7047826333c)

![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/3e8fcba3-859a-4773-991b-d640f2019bee)

![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/8acccdc5-0197-410b-906b-6358e44652c5)

Этому Злевелу я ставлю 7 по шкале кринжовости

злевел2

Трубопроблемы:

Проебал венты вообще на всех хранилищах газа, перепутал направление у помпы для воздуха
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/b6fe85f7-9c7b-4a2c-9c35-c1f49c4a7cd2)

**Вообще почему атмос НАСТОЛЬКО пустой? Типо, в нем вообще ничего нет, я уже не говорю про то, что из-за разделения атмоса камерами на две части у тебя получились какие-то пустые ангары, которые даже приспособить как-то сложно, и такой же пустой ангар который никак не приспособить от того, что все хранилища на другом злевеле находятся.**

господи ну почему, иисус, слив газов проходит через вирусологию через СТЕНУ?
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/35a47e9c-dc9f-45eb-9948-38514b64b394)

У плазма ресерчера отсутствует вообще какой-либо способ слить газы из канистр не используя хранилище. Нужен 1) Слив в космос 2) слив в скрабберную магистраль

Проебал трубы в карго (+лишний провод у шахтеров? +отсутствие стены у шахтеров?):
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/3fea90bb-2ae1-4b59-aec8-604ddc597b37)

Забыл про трубы у ИИ
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/a1df0ed5-ae09-47a9-b079-106bffacb9c1)

мама я не хочу скрабберы и венты просто посреди комнаты мама неееет
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/f06fbe28-1ce0-41d5-aff0-4a71125500ce)
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/4d902f4a-ed5f-40f5-b0e1-a69e91da2100)
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/7a1a05f1-e46e-4a88-9cbd-7018741f5041)

Выходы в космос без вентов:

![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/048c00ff-0b22-416f-8086-9c8fd1c6f19d)

Проводкопроблемы:

Спагетти+незапитанный апц+коммуникации на разных тайлах
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/093488bc-ddcf-48c9-bc2f-9655c9ff0af7)

Ну вот с одной стороны же нгормально провел.
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/9a3e2ba9-eda2-47d8-9283-8017fab7af60)

![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/bd1665fa-295e-4fd7-8c90-38a1ea684d71)

А вот тут вообще ненормально провел:
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/f758e916-2e02-442c-9556-218ed3811ac9)

А вот тут слева нормально справа не ок
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/847bb486-67a9-4578-ab14-fd969b49610c)

Забыл запитать клоуна:
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/351e5ac6-7e08-4618-ac27-5fd41fe01804)

Сборник минорнопроблем:
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/0a44aa3f-2809-400d-9d26-1b331bd7db63)
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/d7e17225-8688-4e32-85a1-6f263dce7beb)
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/4e122d82-793a-40ec-860a-9a5725582ee3)

Этот Злевел получает всего лишь 3 по шкале кринжовости, грейт джоб!

пс:
ты на нижнем уровне двигатели делал красивыми, а тут забыл?
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/75416333/06eca948-78d2-4a7c-8e67-72558d5b497b)

**Comment by intercepti0n** [comment]
Закрываю иссуй в связи с удалением карты в #11429.
