### ISSUE TITLE
Баги связанные с ксенобио – crossbreeding

### ISSUE THREAD

**Issue by BooJ1K** [ChaoticOnyx/OnyxBay#10640]
### Скрещивание

**Burning:**

gold – созданные существа атакуют создателя, но бог сказал – effect_desc = "Creates a gank squad of monsters that are friendly to the user."
Многоразовая, но создаёт по одному существу, так и планировалось?

adamantine shield – Им нельзя бить (другими щитами можно); Он не блокирует удары в ближнем бою; Он не имеет описание статов: длины, веса и т.п.

rainbow knife – Очень странно работает: по идеи, он должен случайно менять тип урона после каждого удара, но по факту, урон ПОЧТИ всегда брут, пару раз сменялся на окси и оставался таковым.

Низкие модификаторы:

(E) (C) (M) mod_handy = 0.25
(E) (C) (M) mod_reach = 0.25
(E) (C) (M) mod_speed = 1
(E) (C) (M) mod_weight = 0.25

_Для примера, у обычного кухонного ножа они больше_

(E) (C) (M) mod_handy = 1.1
(E) (C) (M) mod_reach = 0.4
(E) (C) (M) mod_speed = 1
(E) (C) (M) mod_weight = 0.5

**Regenerative:**

Восстановление не работает у всех экстрактов.

orange – не создаёт кольцо огня; не имеет описания.

darkpurple – не даёт полный комплект одежды, даёт только перчатки и то если используешь правой рукой (по себе), если использовать на ком-то, то даёт и левой...

sepia – не даёт монохромность.

cerulean  – не удаляется после использования из рук, можно использовать бесконечно, пока не выбросишь; Создаёт экстракт без описания.

lightpink – исходя из первого пункта, не работает полностью.

**Stabilized:**

metal – Изменить описание/починить; Должен давать к случайному стаку ресурсов в сумке +1 раз в 30 секунд; По факту, даёт только если держать ресурсы в руках.

rainbow – Не срабатывает в крите.

adamantine – Исправить описание, он защищает только от брута, а не: "Owner gains a slight boost in damage resistance to all types."

**Industrial:**

orange – Создаёт metroid zippo без спрайта.

gold – Не работает.

silver – Идёт процесс создания, но ничего не появляется.

**Chilling:** 

light pink – Цветок нельзя забрать/помочь снять, только отрезать конечность; Если взял в руки, то всё – конечная. По идеи, оно не должно сниматься самостоятельно.

**Consuming:**

Все виды экстрактов отказываются кушать.

**Comment by Zert0X** [comment]
А как это всё сломалость...

**Comment by Zert0X** [comment]
Оно же точно работало...

**Comment by BooJ1K** [comment]
> Оно же точно работало...

Там ещё преколы с промитеями есть, но я решил, что и так слишком много в один пакет запихал + не до конца их проверил.

**Comment by BooJ1K** [comment]
**Recurring** 
Если довести до extract.Uses <= 0 – то экстракт нормально не может умереть и начинает прилично срать в чат.
>The light inside the used metroid extract flickers and dies out.

Проверял на экстрактах, у которых большой кулдаун.

**Comment by BooJ1K** [comment]
Stabilized: cerulean
Нет проверки на то, был ли человек ужё мёртв на момент получения ядра, что приводит к том, что можно воскрешать мёртвых.

**Comment by Zert0X** [comment]
> Stabilized: cerulean Нет проверки на то, был ли человек ужё мёртв на момент получения ядра, что приводит к том, что можно воскрешать мёртвых.

Как оказалось интендед механ.
