### ISSUE TITLE
Фоксхол Предложения Карта

### ISSUE THREAD

**Issue by kokokobold** [ChaoticOnyx/OnyxBay#10676]
1) Нужен прямой путь (не по пути стрелочки, а просто чтобы пройти можно было) от этого места до отбытия по техам, очень неудобно окольными путями добираться, в идеале вообще посвободнее сделать эти теха.
![ApplicationFrameHost_B6a1PzZJEY](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/f28e9160-108a-47dc-a673-8f4f43b4bd28)

2) Морг в медбее неюзабельный и неудобный. Его бы переместить на место текущей комнаты отдыха (или что это), а на месте морга сделать выход в общий коридор, крио и прочее. Для парамедиков минимед, в общем.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/09a5babf-c716-4544-b4b7-a3781c4b54f3)

3) Вот это недоразумение просто не нужно, никто пользоваться не будет, сюда можно переместить комнату отдыха ниже морга, а эти все вещи закинуть на общий склад ниже.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/f6182091-8f93-4a93-bdc4-1943e195025f)

4) Химику нужны стёкла в общий коридор. С возможность закрытия, как на всех картах.

5) Этот переход очень неудобный, люди будут толпиться у хирургии всегда, плюс залетать в хирургию неудобно, если брать в учёт предложение по измению морга выше, то тут можно просто избавиться от стен и сделать более свободную и просторную зону, которая только шлюзами отделяется от остального меда.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/e4dd8786-907e-413d-862d-440670ec9d06)

6) Больше окон, без окон карта всегда выглядит замкнутее.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/3274003f-996a-4b7d-818e-009d0cb5bd47)

7) Не хватает раковин в следующих отделах: медбэй (у входа где-нибудь, люди часто там моют вещи), гидропоника (где воду наливать, из бака часто уходит быстро), кухня (ну тут очевидно).

8) Бар выглядит крайне узким, там просто неудобно сидеть и находиться — бар лучше подальше всегда от главного коридора держать. Что надо сделать: поменять местами саму стойку бармена и его комнату, комнату в идеале сделать с выходом в общий коридор, чтобы бармену удобнее было вначале заходить в свою комнату, а оттуда уже на стойку. Это у нас А и Б.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/89bd6597-784f-4761-a203-4441b13adecc)

В случае с (В) надо просто растянуть бар наверх побольше и там уже расположить основную часть бара со стойками и прочим. Тогда бар будет формой Г.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/69186398-3bc1-41da-9068-a364f52f7d97)

9) Общую задумку я понял, но тут бы теха сделать, потому что иначе у РнДшников нет сразу выхода в теха, у кухни нет, из бара нет, со стороны подов нет, а так удобно можно будет передвигаться между этими частями станций ещё.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/487ccbeb-883f-4205-a34e-fb8f1437c8ee)

10) Эта стена ОЧЕНЬ сильно уменьшает радиус обзора, а смысла в ней ноль, тут просто окно надо. 
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/ff63093f-2618-4fce-a7c1-4f2b832c8290)

11) ОЧЕНЬ узкий вход в бриг, там всегда много людей туда-сюда входит, его всегда надо делать вширь. Просто убери медчасть вниз, ей не так часто пользуются для преступников, которые приходят в бриг, она нужна для тех, кто уже в бриге. И если убрать её, то сразу хороший такой вход просторный будет. И КПП для сидения офицерам туда же впихнуть можно небольшое. И одной лестницы маловато будет для поднятия наверх. 
Или просто вход сделать пониже, а тут сделать публичное пространство около входа. Но оно точно нужно, у брига толпятся люди каждый раунд по той или иной причине.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/44885330/57e3774e-cf75-426d-8fca-57bf5d686d52)

**Comment by intercepti0n** [comment]
Закрываю иссуй в связи с удалением карты в #11429.
