### ISSUE TITLE
Обжективы генокрадов

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#1069]
Переработать обжективы. Тут надо подумать, как это лучше сделать, чтобы обжективы были более-менее "генокрадскими". Абсорбы, ассимиляции/инфесты, размножение мб.

В тред приглашаются все любители подавать безумные идеи.

**Comment by Voldirs** [comment]
не хватает юмористических целей типа поменять людей Х и У внешностями, сделать Н копий человека Х и всякого такого, что не убивало бы людей, но вносило бы хаос

мэйк трапенбергер стэйше грейт агаин

**Comment by koronoshka** [comment]
Задание стереть генкой информацию о их виде. Пусть очищают консоли книжек в библиотеке, хакают научные консоли, пиздят прототипы психоскопов и анализаторы ксеножизни (ах да, они не выдают генок) Что-то такое.

**Comment by Epicus7** [comment]
> не хватает юмористических целей типа поменять людей Х и У внешностями, сделать Н копий человека Х и всякого такого, что не убивало бы людей, но вносило бы хаос

Хотелось бы какого-то ингейм обоснования зачем это нужно, а то цирк.

**Comment by Voldirs** [comment]
Очень просто, ради создания хаоса

**Comment by Epicus7** [comment]
Приехала НЕХ из далекого космоса на станцию с человеками и думает "хмм, а не создать ли мне хаос?"

**Comment by Voldirs** [comment]
Ну да, нормальная тема, потешаться над людишками.

**Comment by vekotov** [comment]
Лучше уж спиздить с ТГ, ибо все уже придумано до нас. У них есть прикольные задания по типу полной кражи личности с побегом и т.д.

**Comment by Cinericius** [comment]
Можно и украсть. У них на вики есть про это?

**Comment by TobyThorne** [comment]
В комментах порофлили и забыли. Очевидно мёртвый иссуй.
