### ISSUE TITLE
Челленджлист

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#107]
Добавить специальный челленджлист с сикеями. Сикеи вносятся добровольно, по запросу игроков. Игроки в челленджлисте получают больше заданий на одиночных рольках и сами задания более сложные (в том числе удаленные из ротации, типа кражи бэг оф холдинга). 
Зачем? Чтобы сделать игру немножко интереснее тем, кто считает себя опытным игроком.

**Comment by Epicus7** [comment]
Сначала стоит просто новые цели написать для трейторов и других ролей.

**Comment by Cinericius** [comment]
Ну да, и сами роли реворкнуть. Но на будущее пусть будет тут записано с плашкой "низкий приоритет".

**Comment by Cinericius** [comment]
Будущее пока не наступило

**Comment by Cinericius** [comment]
Лучше ИС-контракты ебанем
