### ISSUE TITLE
Хоррор-форма для генок

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#1071]
>Хоррор-форма.
Я бы сделал два-три варианта хоррор-форм с возможностью взаимопревращения (читать 2-3 моба, у которых есть абилка Reform, позволяющая сменить одного моба на другого) + один вариант, открывающийся при покупке абилки на улучшение абилок.
Название абилки че-нить типа Supreme Metamorphosis, цена покупки - 10 очков, цена применения - около 30 химикатов.
Подформы:
>1. Gutsnake. Змеехуета типа GAS'а, с венткраулом и бесшумными шагами, с грифонистыми ударами, но не сильно более крепкая, чем человек.
>2. Breeder. Жирная медленная хуета, срущая агрессивными мобами. Урон умеренный или даже низкий.
>3.
>4*.

Ну короче я даж диздок не дописал, но Тоби пилит свою хоррор-форму, так що будем считать, что эта карточка в работе

UPD: RIP Тоби. Предлагайте ваши идеи.

**Comment by Fritcher36** [comment]
Что-то вроде пикче на арте в лобби - гуманоидная ебака с когтями до пола, щупальцами аки у кровосиси из сталкера, которая по всем статам человек, но пожирнее, с коготками для робуста и прорыва артерий, возможностью сосать из жертв кровь, возможно переваривая её в химикаты или излечиваясь ей.

**Comment by vekotov** [comment]
Какая-нибудь псионная хрень, слабая по параметрам, но раздающая баффы другим генкам, а также умеющая наносить стандамаг. Этакий аналог ксеносов-праеторианов с маринов.

**Comment by TapKo4eB** [comment]
Короче чмырилу как из прея найтмер, чтобы по гетто ходила и мимопроходящих кушала.
![image](https://user-images.githubusercontent.com/48761132/71324488-34836a00-24f0-11ea-99d4-b3fb82a27dbc.png)

**Comment by ZerlGray** [comment]
Лучше для начала их полноценно и окончательно ревокнуть. Они не являются цельными как концепт, и у них нет адекватной идеи в том виде, в котором они есть. Придумайте то, что это такое, откуда оно и что должно делать. И как делать. И исходя из этого реализуйте их.

Ради простоты я бы предложил реализовать их как отдельную расу, это уберет несколько проблем с точки зрения реализации - меньше костылей пилить придется, связанных с тем что необходимо каждый раз генокраду возвращать роль генокрада при его ревайвах\других подобных штуках. Ну и вместо широкого класса способностей - дать малый набор оных, но с более широкими возможностями. Сейчас генокрады - чудовища франкенштейна.

**Comment by Cinericius** [comment]
Вообще, сделать концепт - хорошая мысль, конечно.

С расой будет проблема в виде ДНК и разных органов у разных ксеносов, да и еще что-то наверняка вылезет. Возможно, костыль с перевыдачей роли проще, хотя тут полноценным кодерам виднее. 

Насчет франкенштейна - это не так уж плохо в теории, поскольку создаёт РаЗнОоБрАзИе геймплея, главное сбалансировать так, чтобы не было одной принципиально более крутой меты.

**Comment by ZerlGray** [comment]
Не, экземайн при превращении и спрайтик менять не так сложно. Да и ДНК. Просто ранее на грине именно так реализовали их, вроде работало клево.

**Comment by Wuattt** [comment]
В варкрафте3 ещё есть карта metastasis, там вот кууча всяких форм - оттуда можно взять идеи
К примеру, гена превращается непередвигаемую НЁХ размером в 1 тайл, НО с дополнительными размерами в виде стен и пола, а также, мб других штук (ловушек мб, производителей газов)
Сам центр этой НЁХ сможет создавать существ, которых смогут посесснуть госты или сама НЁХ. 
Сами существа будут по силе примерно ходячему телу от body disjunction
А появляться существа будут либо если нет ни одного такого моба, либо если к НЁХ принесли человека

**Comment by SukaYaEbalPridumivatImya** [comment]
Из игры монструм всех трёх приделать можно, разве что с правками небольшими.
