### ISSUE TITLE
Новый ивент: Поломка термостатов

### ISSUE THREAD

**Issue by kreeperHLC** [ChaoticOnyx/OnyxBay#10729]
https://github.com/ChaoticOnyx/OnyxBay/issues/27
В каких-то комнатах уменьшается/увеличивается температура а аир алярмах.
Обяз. ус.: Инженеры.
Малый ивент.

**Comment by Filatelele** [comment]
У нас аир алярмы настолько долго охлаждают/нагревают воздух, что смысла в этом почти нет без изменения логики самих аиралярмов.
