### ISSUE TITLE
Стрельба лазерами через аварийные двери

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1078]
### Описание бага
При помощи отражений лазеров от стенок, можно стрелять через, очевидно, непрозрачные объекты - аварийные двери. Основное условие работы бага - возможность стрельбы через тайл таким отражением до закрытия аварийной двери.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем любое лазерное оружие.
2. Встаём в правильную позу.
3. Стреляем.

### Ожидаемое поведение
Лазерный луч не должен так отражаться.

### Скриншоты
![LasGunCheats](https://user-images.githubusercontent.com/58848742/71305658-5a254c00-23e8-11ea-918a-32f992929ada.gif)

**Comment by TobyThorne** [comment]
![laser](https://user-images.githubusercontent.com/45202681/106398638-3da67080-643e-11eb-909b-678eb8907510.gif)
Всё ещё актуально.

**Comment by wadangel** [comment]
Всё ещё актуально, почините пожалуйста. Но рикошеты вообще кривые до невозможности, а подобные прострелы сквозь шлюзы работают и для огнестрельных прожектайлов. С L6 SAW и разными пистолетами точно.

**Comment by TobyThorne** [comment]
https://github.com/ChaoticOnyx/OnyxBay/pull/10584
Ловла убил рикошеты. 
П  О  Ф  И  К  Ш  Е  Н  О
О
Ф
И
К
Ш
Е
Н
О
