### ISSUE TITLE
Система репутациии

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#108]
Думаю, стоит впилить систему игровой репутации, от уровня которой будет зависеть возможность получения должности, на которой ты отыграл предыдущий раунд.
Условно говоря:
Ты играешь на офицере. Ты играешь как типичный щиткурити. Бьешь хармбаттоном, насилуешь в задницу трапов в камерах.
По итогу тебе ставят крайне низкую репутацию, и все профессии типа "СБ" закрываются для тебя на раунд или больше. 
Эдакий аналог джоббана, только вместо педального вмешательства будет фактически оцениваться уровень адекватности. Это сделает осмысленным хоть как то - существование ЦК. Можно формально будет обосновать подобные запреты при плохой репутации - увольнением.
Опцианально:
Для совсем редких случаев - что то типо казни с аналогом бана на настройку персонажа, если репутация игрока совсем совсем плоха.

**Comment by Cinericius** [comment]
Мне кажется такая себе затея. Сама по себе репутация - это хорошо, дифференцированная на профессии (и мб даже на рольки) - тоже клево, но вот как ее обрабатывать - отдельный сложный вопрос.

**Comment by Epicus7** [comment]
Я бы начал с нормальной системы репутации, да. Общей. Если к ней получится прикрутить что-то такое, то да, можно.

**Comment by ZerlGray** [comment]
Ну это как то осмысленным присутствие ЦК сделает. Иначе по сути - ЦК нет, и жизни за пределами станции тоже. И можно забить хер на это. Что и делают зачастую.

**Comment by Cinericius** [comment]
Давайте не будем нервничать
