### ISSUE TITLE
xenobiology: buff

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#10807]
Сейчас ксенобиология - абсолютно скучнейшая часть космической станции тринадцать. Метроиды жрут мартышек слишком долго, чистить камеры метроидов слишком долго, растут метроиды слишком долго, разделяются на несколько частей слишком долго, долго-долго-долго.

Предлагаю такое:
1. Для разделения на части метроиду нужна только одна мартышка. Кинул - метроид съел - разделился. 
2. Сделать так, чтобы для "скрещивания" метроидов было достаточно пяти экстрактов (вместо десяти, что сейчас стоит, согласно вики).

На этом всё. УЖЕ будет интереснее играть без необходимости тратить на весёлый контент полтора часа без коммуникации и ролеплея.

**Comment by keepm4n** [comment]
В таком случае предлагаю добавить и время жизни метроидам (или любой другой способ не давать им достичь огромного числа), потому что нагрузка на сервер под конец раунда при одном хорошо поработавшем ксенобиологе уже заметна. Один раз мне выдало число под сотню, когда я вручную подчищал мобов без майнда в ксенобиологии.
