### ISSUE TITLE
ИИ при декларе заспавнился в гейтвее

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#10801]
### Описание бага
Игрок задекларился за ИИ, раунд начинается, игрок за ИИ спавнится в гейтвее вместо ядра. Притом ему даже неймпик (выбор имени) не дало.

### Скриншоты
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/60045066/79a4442c-2459-4e51-a242-e7a8ce40a1fe)

### (Опционально) Дополнительная информация
У игрока точкой спавна стоял гейтвей. Возможно, его ИИ в гейтвее появился как раз из-за этого. Но, очевидно, ИИ всегда должен спавниться в своём ядре.

Client Version: 514
Server Revision: [44983e01f4d1e43e00a5743adb4f9766457b280a](https://github.com/ChaoticOnyx/OnyxBay/commit/44983e01f4d1e43e00a5743adb4f9766457b280a) - 00a5743adb4f9766457b280a - 2023-10-27
Game ID: cqv-dah2
Current map: NSS Exodus

**Comment by Zert0X** [comment]
Спасибо батя за карту

**Comment by TimErmolt** [comment]
Исход, NSS Exodus, exodus-2.dmm

**Comment by Zert0X** [comment]
> Раунд айди где?

**Comment by TimErmolt** [comment]
Бля скажи сразу всё остальное, что надо скинуть

Client Version: 514
Server Revision: [44983e01f4d1e43e00a5743adb4f9766457b280a](https://github.com/ChaoticOnyx/OnyxBay/commit/44983e01f4d1e43e00a5743adb4f9766457b280a) - 00a5743adb4f9766457b280a - 2023-10-27
Game ID: cqv-dah2
Current map: NSS Exodus

**Comment by Zert0X** [comment]
> Бля скажи сразу всё остальное, что надо скинуть
> 
> Client Version: 514
> Server Revision: [44983e01f4d1e43e00a5743adb4f9766457b280a](https://github.com/ChaoticOnyx/OnyxBay/commit/44983e01f4d1e43e00a5743adb4f9766457b280a) - 00a5743adb4f9766457b280a - 2023-10-27
> Game ID: cqv-dah2
> Current map: NSS Exodus

У тебя в образце репорта буквально написано чё надо

**Comment by TimErmolt** [comment]
Теперь в крио заспавнился, так же при декларе, очуметь можно.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/60045066/82257129-370b-4150-a7b1-edaafcd0ab13)

Client Version: 514
Server Revision: [e3928970a8dbf293bf96f6a8abe566cd92dad218](https://github.com/ChaoticOnyx/OnyxBay/commit/e3928970a8dbf293bf96f6a8abe566cd92dad218) - bf96f6a8abe566cd92dad218 - 2023-10-30
Game ID: cqx-bYAb
Current map: NSS Exodus

**Comment by BooJ1K** [comment]
Если декларишься за ИИ, при этом убирая все возможные нестационарные рольки, оставляя при этом Rampant AI
То тебя просто не пустит в игру.
Таким образом, малфа вообще не может заспавнится, кроме как кнопками.
