### ISSUE TITLE
Вернуть генетику, но без клонирования

### ISSUE THREAD

**Issue by NyanCommissar** [ChaoticOnyx/OnyxBay#1088]
Портировать генетику с ТГ, Фернфловера или еще откуда-то. Нужно решать конкретнее откуда и что.

Без клонирования.

Старое описание игрока:
> #### Описание проблемы
> Генетика - как мне говорят, там вырезанный подчистую код. Все, что бееебанашки сделали - устроили пиздец.
> 
> #### Что делать?
> 
> Генетику просто верните. Тупо верните то, как было 7 лет назад. С разнерфленным телекинезом, термозащитой, халком и прочим. 
> 
> #### Как?
> 
> Ловите Фернфловер: https://github.com/SS13/green_old

**Comment by ZerlGray** [comment]
Ты так говоришь, будто бы это просто...

**Comment by Cinericius** [comment]
Хочется, конечно, какую-нибдь новую генетику с невиданным доселе механом, но для начала можно и старую вернуть.

**Comment by Cinericius** [comment]
Вот только без клонилки плез.

**Comment by ZerlGray** [comment]
Вспомните идею летала. Ее реально реализовать за неделю. Про то, что при мутации бы органы заменялись на мутировавший тип с особенностями.

**Comment by Epicus7** [comment]
Генетику можно будет вернуть в рамках нового РнД. Пока предлагаю отложить этот вопрос.

**Comment by MACTEP-ABATAP** [comment]
> Генетику можно будет вернуть в рамках нового РнД. Пока предлагаю отложить этот вопрос.

В рамках зари над бездной?
Make research great again?

**Comment by Epicus7** [comment]
Да, ждем #2448

**Comment by kreeperHLC** [comment]
Генетика через аппаратные машинки одно из самых скучных и тык ту вин действий, в таком виде просто будет неуместно создавать себе за пять минут раунда халка с телекинезом и иксреем чтобы...что? Весь раунд раздавать другим это или пойти грифонить? Иссуй с портом отправляется в помойку, но остальные варианты впила - велком.
