### ISSUE TITLE
Старые добрые стинги.

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#109]
Из-за кривого кода цианид спавнится через пять секунд, как раньше. 

А еще он моментально дамажит сердце, даже с учетом антитоксина.

**Comment by ZerlGray** [comment]
Поменяйте циферки в делеях, я проебался чуть чуть (но ты тоже не совсем прав - он и должен был спавнить цианид через 5 сек, просто меньшее кол-во).
`spawn(10 SECONDS)
			T.reagents.add_reagent(/datum/reagent/toxin/cyanide, 1)
		spawn(5 SECONDS)
			T.reagents.add_reagent(/datum/reagent/toxin/cyanide, 1)
		spawn(10 SECONDS)
			T.reagents.add_reagent(/datum/reagent/toxin/cyanide, 3)`
1 делей 5 сек, 2 делей - 10 сек, 3 делей - 15 сек - нужно так сделать. Ну или больше. И цену абилки поставить в 20 генов.
И добавить в код абсорба проверку на ismonkey.
Если все это сделать, то генки не будут имбой с дедстингом.

**Comment by Epicus7** [comment]
Сломал генокрадов, а как чинить - сами чините. Нормально.

**Comment by Cinericius** [comment]
Я щас просто закомменчу скучные стинги и поиграем без них

**Comment by Ruforce** [comment]
буду дома - пушну нерф

**Comment by ZerlGray** [comment]
Сломал? Ты еблан, эпикус? Делеи работают не так как я задумал, но лучше чем раньше. Я хотел сделать поэтапный спавн цианида - сейчас он и спавнится поэтапно. За первые 5 секунд - одна единица цианида.
1 тик может убить только печень (проверял много раз на локалке).
через 10 секунд - еще 4 ед. цианида - и это смертельно, если нет антитоксина.
Олсо, я говорю - при мне ткнутого мною уже детектива спас медик, который действовал оперативно. И это до поэтапного спавна. Чудо видимо.

**Comment by ZerlGray** [comment]
Если я сломал генок - откатывай их к хуям к версии бея и\или пиши сам. Do it.

**Comment by Ruforce** [comment]
вот эт детонация

**Comment by Epicus7** [comment]
Короче починили в рамках другой иссуи.
