### ISSUE TITLE
Система реквестов музыки для жукбокса

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1091]
### Улучшение
Раз мы категорично отказались от кастомной музыки в жукбоксе, можно пойти по другому пути. Конкретно, наладить систему реквестов на добавление тех или иных композиций. Вся музыка будет проходить проверку на качество и затем будет добавляться.
Вместе с этим позже можно сделать сортировку по жанрам и прочему. Хотя ещё надо будет решить проблему с размером самих музыкальных файлов, дабы ни у кого сильно не тормозило.

### Решение
1. Пилим канал реквестов.
2. Туда заливают реквесты.
3. Отбираем самое нормальное.
4. Заливаем.

### (Опционально) Альтернативы
Сделать похожую систему, но только для патронов.

**Comment by Epicus7** [comment]
Проигрыш своей музыки будет в донатном бумбоксе, который смогут получить донатеры.

Продавать постоянные слоты в джукбоксе уже, кажется, почти решили через донат-панель.

Так что скоро будет

**Comment by Epicus7** [comment]
Это вопрос канала дискорда и к билду не относится, в общем-то.

Алсо в #1590 сделали кассеты с кастомной музыкой. Думаю иссуй более не актуален.
