### ISSUE TITLE
Невозможно выбрать глав и АВД (на Эклипсе)

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#10941]
### Описание бага
В сетапе пишет [FOR NANOTRASEN EMPLOYESS ONLY], даже если в бэкграунде стоит НаноТразен. Возможно, такая хрень только на Эклипсе, на остальных картах пока не проверял.

### Характеристики
Client Version: 514
Server Revision: [3f9eed5e6d674b5e90c4e2ef165c30d6d6532140](https://github.com/ChaoticOnyx/OnyxBay/commit/3f9eed5e6d674b5e90c4e2ef165c30d6d6532140) - 90c4e2ef165c30d6d6532140 - 2023-11-10
Game ID: cqJ-aPHj
Current map: NSS Eclipse

**Comment by Zert0X** [comment]
#10939
