### ISSUE TITLE
Плазменные резаки невероятно бесполезны

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1095]
### Улучшение
В том виде, что они есть сейчас, плазменные резаки - кусок бесполезного кода, который игрокам нужен раз в тысячу раундов. Шахтёрам он не нужен вообще никак, потому что копает он медленнее, чем стандартный бур, а урона по мобам наносит около нуля, быстрее огнетушителем их запинать. При этом, никому кроме шахтёров плазменные резаки тоже не сдались: в лучшем случае ими можно прорезать обычную стальную стенку, потратив минуты три.

### Решение
Пятнадцать бёрн-урона поменять на пятнадцать брута, потому что пятнадцать бёрна вообще не ощущается, затем добавить модификатор урона по объектам, чтобы куски породы ломались не за три выстрела, а за один, стенки из стали пилились ~5 выстрелов, пласталевые - 10-20.

### Альтернативы
1) Во-первых, добавить флажок плазменного резака тулбелту, чтобы его можно было нормально носить, во-вторых, добавить возможность без использования сварочных очков плазменным резаком пилить стальные стенки, болты и создавать предметы из стальных/пластмассовых листов. Добавить инженерного функционала, короче, чтобы он не был таким бесполезным как инструмент.
2) Поделить один существующий лучик плазмы со спрайтиком трёх на три полноценных дуги, равных по характеристикам текущим, но выпускать их под углом в 15/25/30/45/60 градусов относительно "главной" дуги, которая летит прямо в цель.
3) Портировать плазменные резаки с какого-нибудь другого сервера, где они не такие бесполезные.
4) Добавить "Улучшенную" версию плазменного резака с нормальными характеристиками, по-факту представляющую из себя пробафанный плазменный недорезак, что есть сейчас, но с другим спрайтом.

**Comment by Cinericius** [comment]
Давным-давно хотели их апнуть, да, еще когда только добавили, но потом как-то замоталось.

**Comment by kreeperHLC** [comment]
Ну про смену берна на брут смешное конечно. Тут скорее ещё берна добавлять нужно.

**Comment by MrMagick2104** [comment]
> Ну про смену берна на брут смешное конечно. Тут скорее ещё берна добавлять нужно.

Имхо, не слишком и смешное. Плазменная дуга - штука под большим давлением и с высокой скоростью перемещения, что в точке прикосновения просто сделает дырку без большого количества ожогов, просто потому, что слишком быстро пройдёт через ткани тела, не успев значительно нагреть их.
Если взять то, откуда этот плазменный резак взят - Мёртвый космос - и посмотреть геймплей, то можно заметить, что плазменный резак, внезапно, _режет_ ксеноморфов, а не сжигает их.
Ещё можно бонусом вспомнить гидроабразивную резку, где принцип похожий, только плазма - не плазма, а вода с абразивом.

**Comment by Voldirs** [comment]
>Плазменная дуга - штука под большим давлением и с высокой скоростью перемещения, что в точке прикосновения просто сделает дырку без большого количества ожогов, просто потому, что слишком быстро пройдёт через ткани тела, не успев значительно нагреть их.

Путаешь с кумулятивной струёй.

**Comment by MrMagick2104** [comment]
> Путаешь с кумулятивной струёй.

Да, точно. Беру свои слова по поводу брута назад.

**Comment by MrMagick2104** [comment]
> Давным-давно хотели их апнуть, да, еще когда только добавили, но потом как-то замоталось.

Видимо, судьба к плазменным резакам непреклонна.

**Comment by Epicus7** [comment]
Апнули в ПРе выше, так что можно закрыть.
