### ISSUE TITLE
Изменить время появления голосования за карту на следующий раунд.

### ISSUE THREAD

**Issue by Bulatm12** [ChaoticOnyx/OnyxBay#10976]
### Улучшение
Сейчас голосование (Vote) за карту, которая будет в следующем раунде - появляется в момент конца раунда (Round End). За мгновение перед оглашением итогов раунда и тут же улетает за пределы чата. Поскольку у нас еще и резня после раунда на данный момент разрешена, то время для голосования супер неудобное и многие это голосование пропускают.

### Решение
Все просто, голосование за карту должно стартовать сразу после отлета шаттла отбытия от станции.

**Comment by Bulatm12** [comment]
Поправьте если что-то не так, делается я думаю достаточно просто.

**Comment by Bulatm12** [comment]
Хотя, я думаю будет проще, чтобы голосование запускалось в момент отлета шаттла от станции. Сейчас заредачу.

**Comment by Zert0X** [comment]
>и тут же улетает за пределы чата
Дядя булат у нас кнопка голосования теперь на экране...

**Comment by Bulatm12** [comment]
Видимо из-за того, что я был в гостах, я ее на экране не увидел, хз. Вот в буквально предыдущем раунде, сидел обсервил, звук услышал, на экране ничего не было, само сообщение смыло сначала инфой об раунд энде, потом логами резни. В любом случае, думать и голосовать за карту во время экшона - сложно. Куда удобнее, чтобы голосование врубалось когда ребята спокойно улетают со станции. Пока шаттл летит, можно спокойно посидеть и подумать.

**Comment by Zert0X** [comment]
ну эт можно поправить не проблема

**Comment by Bulatm12** [comment]
Это весьма старая проблема вообще, о ней много кто писал, но я васян и до иссуя руки до сего момента не добирались.

![image](https://github.com/ChaoticOnyx/OnyxBay/assets/57260577/cfc658c6-e4fc-4e17-86fc-75d3a44493bc)
