### ISSUE TITLE
Transform генокрада не меняет имя персонажа

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#10987]
### Описание бага
Вы ебанутые или чё? Как вы это вообще сломали нахуй? Вы ебанулись ломать ключевую способность антагониста?

Нажимаешь Transform, превращаешься в кого-то -- имя не меняется. Притом голос и внешность меняются как надо, имя (то, что в экзамине видно) -- нет. Пиздец нахуй.

ВОЗМОЖНО работает только если превращаться в людей, ДНК которых получил через жало ДНК, а не через высасывание. Не уверен.

**Comment by TobyThorne** [comment]
Нужно больше информации. ID раунда хотя бы. На локалке не воспроизводится:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/66e28d89-1fbb-4fd0-bc85-2bbcfd274baa)
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/fc1afe72-09c6-4786-8cc8-c79548863581)

**Comment by kreeperHLC** [comment]
> ### Описание бага
> Вы ебанутые или чё? Как вы это вообще сломали нахуй? Вы ебанулись ломать ключевую способность антагониста?

А можно вот без этого а

**Comment by TimErmolt** [comment]
> А можно вот без этого а

Извини, мне сгорело


> Нужно больше информации. ID раунда хотя бы. На локалке не воспроизводится:

`cqR-bVou` раунд, вчера (19.11) шёл где-то с 14:45 по 16:35. Я в ахелп писал по поводу этой фигни ещё, мне педально поменяли имя.

**Comment by TobyThorne** [comment]
В общем, рантаймов никаких не было, если верить логам - на момент написания в ахелп имя уже сменилось (c Odaycel Sombreifni на Kyler White):
```[15:44:26] cqR-bVou ADMIN: HELP: пшшш/(Kyler White): Блять, почему генокрадское превращение не меняет имя? - heard by 1 non-AFK admins.```

Варианта два:
- Что-то сломалось именно в обновлении аппиренса, а сам генокрадский трансформ сработал вполне надёжно.
- Божественное вмешательство.

**Comment by Primudash** [comment]
Не воспроизводится
