### ISSUE TITLE
Сменить жукбокс на кассетный магнитофон

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1098]
### зачем?
Аутентичненько. Будет навевать 90-ые или когда кассеты были в моде, я не помню.

### по чём кассеты?
Кассетный магнитофон, это не респрайт жукбокса, а реальный такой проигрыватель кассет. Сами кассеты можно будет найти во многих местах: изначальные у бармена, с песнями как у нас сейчас, какие-нибудь на задворках гетто и дереликта, где-то купить в автомате, заказать в лодауте, купить у торговца на рынке короче где угодно.

### а в чём прикол
Шоб прикольные асмр звуки были когда касету вставляешь, включаешь, выключаешь, достаёшь и т.д.

### почему именно кассеты?
Я у деда в гараже на старой магнитоле слушал любэ, и чёт проникся духом таким, да.

### [GameDisUPD:]
>MrMagick2104 commented 15 days ago
>Вообще, имхо, неплохо вписывается с идеей донатного  бумбокса, который может проигрывать любые кастомные песни, в то время  как смерды-непатреоны вынуждены искать по станции магнитофоны и кассеты с  жанровой музыкой, на которых по три-четыре случайной песни из пула  жанра, которые добавляются/обновляются через аппрувы самими игроками. А  ещё можно кассеты с выбором нужного жанра добавить в лоадаут, да.

**Comment by Epicus7** [comment]
Джукбокс - проблема, которая волнует большую часть игроков. Необходимость данного иссуя должна решаться советом, имхо.

**Comment by Cinericius** [comment]
Кассеты - охуенная тема. Можно прятать всякую пропаганду в гетто, крипоту на дереликтах, даже какие-то эффекты на персонажей от прослушивания всего этого накладывать.

**Comment by MrMagick2104** [comment]
Вообще, имхо, неплохо вписывается с идеей донатного бумбокса, который может проигрывать любые кастомные песни, в то время как смерды-непатреоны вынуждены искать по станции магнитофоны и кассеты с жанровой музыкой, на которых по три-четыре случайной песни из пула жанра, которые добавляются/обновляются через аппрувы самими игроками. А ещё можно кассеты с выбором нужного жанра добавить в лоадаут, да.

**Comment by Fritcher36** [comment]
Максимально охуенную идею внес мэджик, но это делать надо. Желающие есть? За донат я бы давал именно кассету с музычкой в лоадаут, а не кастомный бокс, дабы в случае злоупотребления кассету могли бы отобрать и в жопу затолкать.

**Comment by Cinericius** [comment]
Внес каммент Мэджика в ОП

**Comment by Epicus7** [comment]
@Cinericius, в ОП-посте помойка какая-то.

Во-первых, джукбокс и бумбокс - это разные вещи.
Во-вторых, бумбокса еще в игре нет, так что несовсем понятно как можно одобрять иссуй на его улучшение.

**Comment by Cinericius** [comment]
Так идея в том, шоб жукбокс заменить на кассетник, а бумбокс будет переносным кассетником с кастомной музыкой на кассете.

**Comment by Epicus7** [comment]
В целом спрайты уже есть за авторством Армолитского. Плашку снимаю.

**Comment by Epicus7** [comment]
Реализовано в #1590
