### ISSUE TITLE
На стулья можно вешать одежду

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11009]
Короче, джва года ждал такое обновление, по нажатию хелпом на стул (либо перетягиванием одежды из руки на стул) со спинкой на него вешается одежда по типу пиджаков, кофточек, плащей, халатов. Снимается таким же образом. Ребята, это ПЕРЕВЕРНЁТ игровой мир, все будут в шоке!

_Этот иссуй был создан автоматически по [сообщению из дискорда](https://discord.com/channels/414832443384659968/606411392811139072/1168883997565255820). Автор: **inges#0**._

**Comment by TobyThorne** [comment]
Работа для спрайтеров на ближайшие два года и миллиарды иссуев с "почему мой новый кастомный плащек ни вешаица на стул???????????" в будущем. Звучит круто.
