### ISSUE TITLE
Чаты в ПДА

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11006]
Добавить возможность создавать чаты в ПДА по аналогии с приложухой на консолях. Зачем? Потому что на консолях чатами АБСОЛЮТНО НИКТО НЕ ПОЛЬЗУЕТСЯ. А так прикольно будет. Можно будет делать чисто ассистентские чаты, хвастаться размерами своего тулбокса и говорить всем пацанам какой хос хуесос

_Этот иссуй был создан автоматически по [сообщению из дискорда](https://discord.com/channels/414832443384659968/606411392811139072/1168883997565255820). Автор: **inges#0**._

**Comment by Filatelele** [comment]
Надо вообще ПДА реворкать и делать их модульными как компы. 
А еще ПДА надо чинить, там картриджи сломаны чуть более чем полностью.

**Comment by TobyThorne** [comment]
>модульными как компы

а можно лучше модульные компы к хуям снести пожалуйста
