### ISSUE TITLE
Дать игроку возможность отказаться от роли, если его выбрал сторителлер посреди раунда

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11008]
В Спортлото⁠ хорошо подметили, что "ВНЕЗАПНО Я ГЕНОКРАД ПОСРЕДИ РАУНДА В ПЫТОЧНОЙ С ГОЛОЙ ЖОПОЙ" — хуйня, очень портящая раунды. Предлагаю сделать выдачу роли сторителлером по типу той, что уже есть сейчас с борерами, абдукторами, ПИИ и прочей нечистью посреди раунда, а именно — 
"Вы выиграли в антаголотерею, хотите стать %рольканейм%? Y/N"

_Этот иссуй был создан автоматически по [сообщению из дискорда](https://discord.com/channels/414832443384659968/606411392811139072/1168883997565255820). Автор: *gladkiyelisey#0**._

**Comment by TobyThorne** [comment]
Звучит херово. Если госту предлагают стать антагом - ему, по сути, ничего не палят. Если он откажется - он всё равно увидит антага.
Если же хуман тыкает "НИНАДА ГЕНКУ" - он знает, что кто-то другой на станции стал генкой.

**Comment by Filatelele** [comment]
Закрывайте иссуй либо в баг переводите


`	if(player.is_brigged())
		log_debug_verbose("[key_name(player)] is not eligible to become a [role_text]: They are brigged!")
		return FALSE
`

**Comment by EliseyGladkiy** [comment]
> if(player.is_brigged()) log_debug_verbose("[key_name(player)] is not eligible to become a [role_text]: They are brigged!") return FALSE

Так тут речь не только про бриг. Некоторые ситуации с выдачей ролек просто-напросто неуместны, а игрок на это повлиять никак не может, кроме как посреди раунда менять себе префы, что кринж.

**Comment by kreeperHLC** [comment]
Видимо нужен отдельный преф на выдачу роли в раунде

**Comment by EliseyGladkiy** [comment]
> Звучит херово. Если госту предлагают стать антагом - ему, по сути, ничего не палят. Если он откажется - он всё равно увидит антага. Если же хуман тыкает "НИНАДА ГЕНКУ" - он знает, что кто-то другой на станции стал генкой.

Вывод: сделать задержку в N минут перед следующим дропом рольки, рероллить тип роли, который должен выпасть. Таким образом игрок будет знать только то, что на станции когда-то будет ролька, что и так можно спалить по инфе о мёртвых антагах на число живых СБшников

**Comment by EliseyGladkiy** [comment]
> Видимо нужен отдельный преф на выдачу роли в раунде

Как вариант, кстати

**Comment by Zert0X** [comment]
> > Видимо нужен отдельный преф на выдачу роли в раунде
> 
> Как вариант, кстати

Зайти в чар сетап и выключить роли на раунд для слабаков
