### ISSUE TITLE
Новый режим/событие: the hell on station (пародия на DOOM)

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#1100]
Новый режимчик, в котором:

На станцию проникают полчища демонов, которые кушают персонал. Конечно же, среди персонала появляется DoomGuy (спрайты есть), который обладает большей живучестью и силой. И начинается бой. Персонал + думгай уничтожают демонов, либо только думгай, так как персонал лоханется.
Некоторые превращаются в одержимых/зомби.

На станции появляются демоны в N-ном количестве ИЛИ появляются врата в ад, которые нужно закрыть, ибо оттуда выскакивают твари. 

Я shitаю, что будет прикольно стать думгаем и пострелять в демонов, покрамсать их, избить всех этих тварей и т.д. и т.п. За персонал также не будет скучно.

**Comment by Cinericius** [comment]
И чо персоналу делать? Каэсик с мобами?

**Comment by Fritcher36** [comment]
Как обычно, идея хорошая - реализовать предлагаете отстойно. Если и делать вторжение ада - то без мемного думгая и толпы симплэнималов. Сделать дьяволов-антагов, возможно, привязать це к культу вместо Нар-си.

**Comment by ArmolitskiyCarpoeb** [comment]
> И чо персоналу делать? Каэсик с мобами?

Возможно, принимать препараты/ходить в церковь, чтобы не стать одержимым. Выживать.

**Comment by kreeperHLC** [comment]
Режим, который надоест после двух-трех раз

**Comment by ZerlGray** [comment]
Ну нюка же не надоела

**Comment by Cinericius** [comment]
В нюке люди стреляются с людьми, да и бывает она нечасто
