### ISSUE TITLE
Завязывать кофты на поясе/на спине

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11012]
меня НЕ ЕБЁТ кто будет это спрайтить, могу поставить баунти если залетит
Импровизированные бананки с двумя карманами на слот пояса это круто и стильно. Плащики из завязанных рукавов на шее тоже классно, но не мастхев.

_Этот иссуй был создан автоматически по [сообщению из дискорда](https://discord.com/channels/414832443384659968/606411392811139072/1146875697055404203). Автор: **incarantor#0**._

**Comment by Filatelele** [comment]
Ставь баунти. Запилю.
