### ISSUE TITLE
Хочу бронежилет под плащ 

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#1101]
### Улучшение
Теперь можно выглядеть действительно крутым, нося плащ (куртку/худи и т.д.) и бронежилет одновременно. Детективу понравится. 

### Решение
Куртки/худи/плащи/халаты становятся "аттачментами" и прикрепляются к жумпсуитам или же бронежилеты к курткам. 

### (Опционально) Альтернативы

То что сейчас и так заебись, зачем менять?

### (Опционально) Дополнительная информация

> сделать так, чтобы броню можно было одевать под плащ, типо аттачмента на жумпсуит, либо на внешнюю одежду (куртки, худи, плащи)
> 
> либо пусть внешняя одежда "аттачица" на жумпсуиты (не вся, естественно) 

Моя идея в дискорде набрала довольно много положительных стрелочек вверх.

**Comment by Fritcher36** [comment]
Идея звучит неплохо, реализация такая себе. Можно взять пример со сталкеробилда и ввести два слота внешней одежды, внешний и внутренний. Скафандры занимают оба, а вот одежду можно комбинировать. Но это уже рефакторинг системы одежды, что достаточно геморройно, и если уж в это лезть - то подумать над ней и переработать в целом. Надо ли?

**Comment by Cinericius** [comment]
Сложно и непрактично.
