### ISSUE TITLE
Добавить каморку для клоуна и мима

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1103]
### В чём проблема
Нашим клоунам и мимам тупо жить негде. Ни на коробке ни на Эклипсе нет актёрской комнаты или как она там.
А на вики там есть было да!!1111

**Comment by ArmolitskiyCarpoeb** [comment]
Полностью согласен, клоун и мим должны иметь свою комнату с кучей разных вещей для приколов.

**Comment by Tsurupeta** [comment]
Предлагаю вьіпилить мимов и клоунов как пережитки прошлого.

**Comment by Cinericius** [comment]
> Предлагаю вьіпилить мимов и клоунов как пережитки прошлого.

Ты чо блять

**Comment by Cinericius** [comment]
Деды, значит, в поте лица впиливали обратно Омерзительную Двойку, безбожно выпиленную беедаунами (как говорил Тоби, выпил клоунов бейцами - это френдлифайер), а ты теперь говоришь "пережитки прошлого"?

Ух сука аж зубы скрипят.

**Comment by Tsurupeta** [comment]
> Деды, значит, в поте лица впиливали обратно Омерзительную Двойку, безбожно выпиленную беедаунами (как говорил Тоби, выпил клоунов бейцами - это френдлифайер), а ты теперь говоришь "пережитки прошлого"?

Клоуны по большей части не смешные, а нормально на мимах без написания предложений пальцами в воздухе умеют играть единицы.

**Comment by TapKo4eB** [comment]
> умеют играть единицы.

1 > 0, so...

**Comment by Cinericius** [comment]
Фуу

**Comment by Cinericius** [comment]
Аппрув на аве, каморка на мапе

**Comment by Epicus7** [comment]
Эта "коморка" всегда раньше называлась театром. Прям театр пилить я думаю не стоит, но коморку можно добавить поближе к отсеку с голограммами, название которого я забыл.
