### ISSUE TITLE
Сломался спрайт зомби хуманов

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#11047]
Зомби хуманы теперь выглядят вот так 
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/62835631/13734cc5-b636-4e86-aa4a-6f06c01ff9c3)

Ранее должны были так 
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/62835631/69879aec-aa30-48ff-adbb-999e3a1dd169)

**Comment by Bulatm12** [comment]
Очень нужно для проведения ивента.

**Comment by k4m3rn** [comment]
Какой нахуй приоритет, какие нахуй зомби...

**Comment by ArmenianOnyx** [comment]
вот зомби

**Comment by ArmenianOnyx** [comment]
https://cdn.discordapp.com/attachments/846685890549514280/1187324856249876522/r_human.dmi?ex=65967971&is=65840471&hm=5c68f8286b10e0ee2f9fbd2e277f5ab1a234e039a1c30ae1c86134a0ebf9450d&

**Comment by kreeperHLC** [comment]
PR #11274
