### ISSUE TITLE
Откатить гниение мертвых тел. 

### ISSUE THREAD

**Issue by Aehsonneh** [ChaoticOnyx/OnyxBay#1104]
#### Разница между реальным поведением и ожидаемым
Пункт 1. Принцип гниения органов и конечностей таков, что процесс разложения начинается при расположении на "грязных" тайлах и при температуре, ниже определенной. "Стерильность" - это свойство тайла, которым по умолчанию обладает белая чистая плитка, грязь и выделения делают ее "грязной". По многократным опытам стало очевидно, что на "стерильных" тайлах ампутированная печень или рука могут лежать сравнительно долго (речь о десятках минут), оставаясь свежими, в то время как другая печень, лежащая в техтуннеле в трех клетках от первой, сгнила за две-три минуты. В условиях холодильника, к примеру, переносного в виде чемоданчика или в холодильном ящике с кухни, ампутированный орган, в том числе и мозг, остается свежим бесконечно, 
Но трупы с _одинаковой_ скоростью сгнивают и в техтуннеле, и на плитке медбея, и в криокамере (проверяла разные температуры, от 200К до 50К). Хотя опять же, их отделенные органы следуют стандартным правилам.

Пункт 2. При пересобирании синтов из киборгов в полученном торсе присутствуют все органы, а так же живот. Это старый костыль, который исправно функционировал и никак не сказывался на игре, оставляя органические органы независимыми от действий роботехника или самого синта. Сейчас же при пересборке синта все эти органы (и живот) оказываются уже гнилыми - они безнадежно сгнивают за то время, пока идет сборка, и в результате несчастный мозг в ММИ умирает за две минуты агонии, причем исправить это практически невозможно игровыми средствами.

#### Как воспроизвести проблему?
Пункт 1. Убей трех человек, первого положи в техах в лужу грязи, второго в медбее, третьего в настроенную криокамеру. Засеки время.
Пункт 2. Разбери борга. Его торс используй для сборки синта. 

#### Как долго известно о проблеме?

Проблема стала известна с той минуты, как только гниение мертвых тел было введено в игру. А борга четыре дня назад пересобирала, но по логике проблемы видно, что она тесно связана с самим разложением.

#### Дополнительная информация

- [х ] Проблему можно воспроизвести хотя бы один раз
- [х ] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [х ] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [х ] Проблема случилась в недавнем раунде (прошло меньше недели)
- [х ] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by LLIkolnik** [comment]
>Откатить

Тупая хуйня хочет, чтобы ей вернули абузы, вместо фиксов. Блядь, браво.

**Comment by koronoshka** [comment]
На откат да, не тянет, но гниющие борги вообще не смешно. Механика гниения пока топорная и возможность замедлить процесс нужна не одним только медикам.

**Comment by Aehsonneh** [comment]
> > Откатить
> 
> Тупая хуйня хочет, чтобы ей вернули абузы, вместо фиксов. Блядь, браво.

Я предлагаю сделать специальные места, где гниение происходить не будет, например специальные камеры в моргах - так можно будет сохранять тела при необходимости, и при этом они не будут заабужены вообще все. Но сейчас проблема лежит еще глубже, разложение вообще никак не связано с обычной механикой гниения, оно просто _есть_, и ничто не может этому помешать.

**Comment by Schutze88** [comment]
Так это реально хуйня. Люди за то время, которое проходит на станции, обычно не сгнивают до состояния полного разложения. Особенно учитывая, что это вообще-то космос. Особенно учитывая, что сгнивают даже кибернетические протезы вплоть до ММИ, которые гнить вообще не должны.

**Comment by TapKo4eB** [comment]
Вспоминаю сгнившие геноорганы за время стазиса.

**Comment by Aehsonneh** [comment]
> Так это реально хуйня. Люди за то время, которое проходит на станции, обычно не сгнивают до состояния полного разложения. Особенно учитывая, что это вообще-то космос. Особенно учитывая, что сгнивают даже кибернетические протезы вплоть до ММИ, которые гнить вообще не должны.

Гниение кибернетических протезов понерфили когда я в прошлый раз писала иссуй на это. Здесь проблема что гниют органические органы в синтотеле киборга.

**Comment by TapKo4eB** [comment]
Тут юмор не в том что это понёрфили... А хотя вру, в этом и юмор.
Как только Игорь залил пр с гниением, оно уже было мёртворожденным, ибо он это даже не тестил нормально судя по всему. Потому мы и имеем хотфиксы с починкой гниения гено и синто органов.

**Comment by SirStronghold1488** [comment]
Достаточно просто откатить игорегниение и всё, хотя бы на первое время. Остальное сгнивало с нормальной скоростью, в независимости от условий содержания.

> Тупая хуйня хочет

Согласен.
