### ISSUE TITLE
На Полярке у бармена нет патронов для дробовика

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#11074]
### Описание бага
Бедняга везде перерыл, нигде не нашёл.

### Скриншоты
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/60045066/da6e9024-701c-48e0-8d9a-90842d97643b)

### Характеристики
Client Version: 514
Server Revision: [82de2e075f2f6400624811d9959a344b5843b384](https://github.com/ChaoticOnyx/OnyxBay/commit/82de2e075f2f6400624811d9959a344b5843b384) - 624811d9959a344b5843b384 - 2023-11-26
Game ID: cqZ-c7sO
Current map: Pathos-I

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
