### ISSUE TITLE
Патос-1: обсчёт метели кривой?

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11077]
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/150343435/cc450ea9-bd8e-4c85-b99e-08c19bc75255)
Я сначала увидел что на турфах без снега нет метели, а потом заметил на крайних турфах со снегом отсутствие метели.

ой блядь там еще и на стены залезло жесть какая

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
