### ISSUE TITLE
Парящая лампа (129, 160, 3) на Полярке

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#11076]
### Описание бага
Лампа на тайл выше чем должна быть, из-за чего витает в воздухе.

### Скриншоты
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/60045066/1ebb90da-32f8-40c1-b5ec-955192f522c5)

### Характеристики
Client Version: 514
Server Revision: [82de2e075f2f6400624811d9959a344b5843b384](https://github.com/ChaoticOnyx/OnyxBay/commit/82de2e075f2f6400624811d9959a344b5843b384) - 624811d9959a344b5843b384 - 2023-11-26
Game ID: cqZ-c7sO
Current map: Pathos-I

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
