### ISSUE TITLE
Каркасы столов вместо столов в ксенобиологии Полярки

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#11071]
### Описание бага
сабж)

### Скриншоты
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/60045066/40d597d5-314d-4a33-99a7-b4b8f3c62570)

Client Version: 514
Server Revision: [82de2e075f2f6400624811d9959a344b5843b384](https://github.com/ChaoticOnyx/OnyxBay/commit/82de2e075f2f6400624811d9959a344b5843b384) - 624811d9959a344b5843b384 - 2023-11-26
Game ID: cqZ-c7sO
Current map: Pathos-I

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
