### ISSUE TITLE
Нет мусорки в трёх левых загонах в ксенобиологии Полярки

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#11072]
### Описание бага
А в трёх загонах снизу -- есть. Конфликт!

### Скриншоты
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/60045066/5765d173-5384-4ac7-84b1-46b277931453)

![image](https://github.com/ChaoticOnyx/OnyxBay/assets/60045066/569b16b0-c1a7-446c-8183-c94ec2cea67c)

### Характеристики
Client Version: 514
Server Revision: [82de2e075f2f6400624811d9959a344b5843b384](https://github.com/ChaoticOnyx/OnyxBay/commit/82de2e075f2f6400624811d9959a344b5843b384) - 624811d9959a344b5843b384 - 2023-11-26
Game ID: cqZ-c7sO
Current map: Pathos-I

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
