### ISSUE TITLE
Патос-1: проблемы с темнотой

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11073]
Пробежаться еще раз по Патосу и поискать тёмные места. Понятно что астероидная станция не должна быть подсвечена везде, но кое-где даже шлюзы в отдел тёмные уровня #000000 
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/150343435/7ad6fc83-e405-4d58-a319-55986a291139)
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/150343435/0c049f5d-1729-4d8e-9ae5-77e6bda8a9fb)
Скрин с одного места.

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
