### ISSUE TITLE
Полярка: Шлюз (134, 126, 3) обесточен из-за кривой зоны АПЦ

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#11075]
### Описание бага
Шлюз (который внешний, белый) технически находится в зоне улицы, а не в зоне станции, где работает АПЦ, и поэтому вечно обесточен.

### Скриншоты
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/60045066/0f6a4804-4436-4c46-a4e1-066421bd8b67)

### Характеристики
Client Version: 514
Server Revision: [82de2e075f2f6400624811d9959a344b5843b384](https://github.com/ChaoticOnyx/OnyxBay/commit/82de2e075f2f6400624811d9959a344b5843b384) - 624811d9959a344b5843b384 - 2023-11-26
Game ID: cqZ-c7sO
Current map: Pathos-I

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
