### ISSUE TITLE
Патос-1: проблема с мостиком на шаттле отбытия

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11081]
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/150343435/e6c0cc0b-5df2-4262-b8fb-11639a547d7c)

ХоП, РД и СЕ туда тупо пролезть не могут, если официально.

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
