### ISSUE TITLE
Патос-1: в вирусологии нет мусорки

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11080]
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/150343435/6f3c6de6-1df6-44f6-b787-9e47de98bc03)
Как избавиться от мартышки?

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
