### ISSUE TITLE
"You can't remember how you got here"

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11101]
Данная фраза при похищении абдуктором неясна жертве похищения; нам требуется прописать более чёткую формулировку (желательно такую, которую нельзя оспорить (лол)).
Важно учесть интенцию разработчика, цитата - "люди вообще ничего не будут помнить о похищении"

**Comment by Zert0X** [comment]
Абдукторы выпилены #11479
