### ISSUE TITLE
Ещё один иссуй про экономику

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#11105]
### Улучшение
В данный момент в нашей игре существует проблема - деньги не нужны (исключение - торговец). Лишь самые ролеплейные игроки что-то с ними делают. Поэтому нужно вводить фичи, решающие эту проблему. 

### Решение
1. Перевести карго консоль на кредиты. Сейчас все заказы производятся за снабженческие очки. Нужно будет продумать цены на вещи из ассортимента того, что можно заказать, а также стоимость предметов, которые можно "продать" на ЦентКомм + добавить новые предметы в список тех, что можно отправить и получить за это деньги. В такую карго консоль можно вводить деньги и выводить. 

2. Некоторые бесплатные предметы в вендорах (автоматах) должны стать платными. Например, инструменты в YouTool в ассистентской. Платные предметы в вендорах должны стоить в разы дороже. Например, Bread tube из Getmore Chocolate Corp вместо 10 кредитов будет стоить 300-500 кредитов.

#2874 
>В идеале инструменты и перчатки из автоматов должны быть платными, но зато чтобы там было все и сразу. Также сейчас сама еда очень дешева и любой ассистент может выкупить целый автомат еды, так что ее надо бы сделать подороже.
Ну и дать возможность карго перезаполнять эти автоматы, а прибыль с них отправлять обратно каргонии, да. (сейчас прибыль идет на какой-то Vendor Account, который нигде не юзается кроме этих самых автоматов).

3. Официально еда и напитки в баре будут платными. Цены выставляют бармен, на напитки, и повар, на еду. 

4. Кастомный вендор (автомат), где можно будет выставить предмет и цену на него. Такой есть на /vg/station и Эрисе. Пример: отдельная плата в хранилище карго (+ в консоль заказов) - автомат нужно собрать самому. После сборки вендора открываешь интерфейс, вводишь нужный электронный счёт, куда будут переводиться деньги. Вставляешь предмет, он появляется в интерфейсе вендора, устанавливаешь там же ему цену. Проводишь картой по автомату, чтобы его заблокировать (таким образом, никто, кроме тебя, не сможет достать предметы или установить другие цены).

5. Деньги у ассистентов должны быть в виде налички - спавниться в кармане. Никакого счёта.

6. Убивать количество полезного хлама, разбросанного по станциям. Во многих местах валяются бесплатные сигареты, зажигалки и еда. Такого быть не должно. 

Зарплата и премии будут выдаваться капитаном/ХоПом/главами отделов.

### (Опционально) Альтернативы
#2640 - в комментариях

### (Опционально) Дополнительная информация
-

**Comment by kreeperHLC** [comment]
Нужна декомпозиция, в таком виде - минус

**Comment by ArmolitskiyCarpoeb** [comment]
> Нужна декомпозиция, в таком виде - минус

Делить иссуйчик на иссуи? 

К слову, мне недавно захотелось какую-то часть из этого самому сделать в виде PR, а именно:
* Убавить количество полезного хлама, разбросанного по станциям (еда, зажигалки, сигареты, алкоголь). 
* Некоторые бесплатные предметы в вендорах (автоматах) должны стать платными. Платные предметы в вендорах должны стоить в разы дороже.

**Comment by vsss412** [comment]
Конечно делать иссуи на иссуи. Будет совсем жопа - добавим лейбл Экономика, у нас с ней ваще туго. @kreeperHLC прошу отпиши по текущим предложениям, по пунктам, может что-то стоит отдельно потом выносить, это не проблема. Предложение то имеется так сказать.
