### ISSUE TITLE
Улучшение голода у Ящеров

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#1117]
Есть два стула, простой и сложный. 

Простой стул - покрутить циферки:
1) Усиление голода в 1,5-2 раза вместо текущих 3
2) Нерф скорости перемещения - 0,8 вместо текущих 0,5
3) Гниение органов от голода заменить прогрессивным снижением скорости перемещения

Сложный стул - добавить видоспецифичный верб Change metabolic rate, который переключает метаболизм между двумя режимами:
1) Hibernation. Голод - 1/2 от человеческого. Скорость - 0,7 от человеческой. Регенерация как у человека, может даже чуть медленнее, без восстановления крови и органов. Никакого урона органам от голода. 
2) Hyperactive. Голод - в 3-3,5 раза выше человеческого. Скорость бега - 1,1-1,2 человеческой. Сильная регенерация с восстановлением крови и органов, отнимающая очень много нутриентов. Урон органам от голода. В общем примерно как сейчас норма, но с повышенной скоростью бега и регенерацией.
Концепт в том, что игроку на рептилии будут доступны два режима, один дико ебущий, но энергозатратный и потенциально саморазрушительный, а второй наоборот тормозной, но сберегающий. 
Может возникнуть необходимость доребалансить пост-фактум.

**Comment by MrMagick2104** [comment]
>Hyperactive. Голод - в 5 раз выше человеческого. Скорость бега - 1,2 человеческой. Сильная регенерация с восстановлением крови и органов.

Можно же голод оставить как сейчас, т.е. в 3 раза выше, но снимать много очков насыщения за регенерацию крови и органов. Если условный унатх будет просто быстро бежать секунд пятнадцать (условные, опять же), а потом умирать от голодания, в то время как такой же унатх будет во время активного боя умирать от голода за то же самое время, то это будет как-то криво выглядеть, наверное.

**Comment by ArmolitskiyCarpoeb** [comment]
### Ксеносы должны страдать

**Comment by Animesku** [comment]
А подкручивание голода, которое делали недавно, и на унатхов подействовало?

**Comment by TermService** [comment]
> А подкручивание голода, которое делали недавно, и на унатхов подействовало?

у них 3 людских голода, если заканчиваются нутрименты они получают дамаг по органам

**Comment by Animesku** [comment]
А если ящеру еще и трейт на высокий метаболизм поставить, то даже запихивание в него мяса без остановки не поможет...

**Comment by TermService** [comment]
За них сейчас играть очень сложно, ибо без еды ты умираешь, хотя я немного потерял смысл беседы

**Comment by Cinericius** [comment]
> > Hyperactive. Голод - в 5 раз выше человеческого. Скорость бега - 1,2 человеческой. Сильная регенерация с восстановлением крови и органов.
> 
> Можно же голод оставить как сейчас, т.е. в 3 раза выше, но снимать много очков насыщения за регенерацию крови и органов. Если условный унатх будет просто быстро бежать секунд пятнадцать (условные, опять же), а потом умирать от голодания, в то время как такой же унатх будет во время активного боя умирать от голода за то же самое время, то это будет как-то криво выглядеть, наверное.

Соглы, пофикшу сейчас в ОПе

**Comment by Cinericius** [comment]
Циферки потыканы

**Comment by vekotov** [comment]
Ящер должен уметь менять режим, если он находится в отключке? Если я правильно понимаю, то да.

**Comment by Cinericius** [comment]
> Ящер должен уметь менять режим, если он находится в отключке? Если я правильно понимаю, то да.

В принципе да. 

> А также нужно ли изменять голод, который добавляется при регене органов или же нужно подкрутить только тот, который при ходьбе?

Сложно. Там два параллельных голода что ли? ШУЕ БЕЕКОД.

**Comment by ZerlGray** [comment]
1. А он и умел. А потом пришли люди которые решили занерфать ксеносов. Но они не смогли это сделать и оставили в том виде, в котором оно сейчас есть. Ха!
