### ISSUE TITLE
При ресливе неправильно пишет в чат

### ISSUE THREAD

**Issue by vsss412** [ChaoticOnyx/OnyxBay#11177]
Во время реслива получаем сообщение на пике. Скорее всего пропущено "You will come to LIFE soon." или типа того
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/150343435/c3096f68-844f-41d8-b3c7-db852c2bbec2)

**Comment by Filatelele** [comment]
Closed in https://github.com/ChaoticOnyx/OnyxBay/pull/11312
