### ISSUE TITLE
Клоун умеет стрелять (если он антаг)

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#1118]
### Стреляющий клоун

Если клоун антаг (а именно тритор), то ему больше не придется попадать себе по пятке, стреляя из пушек. Клоун-тритор это уже очень странно. Зачем Синдикату агент с профессией клоуна, который не умеет стрелять? 

_А может не надо? Пусть клоуны-триторы пытаются не стрелять, а моя идея говно?_ Вполне возможно.

**Comment by Vostok-Odin** [comment]
На гринотг клоун-предатель умел нормально стрелять. Это добавляло перчинку - никогда не знаешь, выстрелит ли клоун себе в пятку из револьвера, или отстрелит им твою лысую голову.

**Comment by Cinericius** [comment]
Клоуны везде могли стрелять, будучи ролями. Было даж недвусмысленное сообщение про то, что тренировки помогли overcome your clownish nature. Видимо, мы забыли это накатить, возвращая их после беевырезок.
