### ISSUE TITLE
Боеголовка ёбнула моментально, хотя поставили таймер 120 секунд

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#11215]
### Описание бага
ээ ну сабж. нопепс поставил на терминале самоуничтожения таймер 120 секунд и запустил. бомба ебанула моментально, станция могила.

### Воспроизведение
хз, но вроде бы не первый раз такая атомная пушка

### (Опционально) Характеристики
Client Version: 515
Server Revision: [ff5646ef1ffa485adf8f19bc18693ae94655dda4](https://github.com/ChaoticOnyx/OnyxBay/commit/ff5646ef1ffa485adf8f19bc18693ae94655dda4) - df8f19bc18693ae94655dda4 - 2023-12-11
Game ID: crd-cFTy
Current map: NSS Exodus

**Comment by Filatelele** [comment]
Таймер не 120 секунд, а 120 децисекунд. Так что не удивительно почему бомба ебнула практически мгновенно. 

Notabug wontfix
