### ISSUE TITLE
Баф грабов

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1124]
![image](https://user-images.githubusercontent.com/5204667/71675641-45a16600-2d8f-11ea-8d3c-07b9bd013196.png)

_Дискордо-реквест от Dobrak#5772_

**Comment by Cinericius** [comment]
Не, старое грабоговно не нужно, это был пиздец. Надо или какой-то костыль специально для офицеров СБ (проблема-то именно в том, что наручники не надеваются без граба, как я понимаю), или оставить как есть. Можно убрать необходимость граба для наручников. Еще можно сделать игнорирование пойза для тех, на ком наручники, если еще не. Энивей, идея из поста (вернуть суперграбы) не катит.
