### ISSUE TITLE
Броня под плащем

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1125]
![image](https://user-images.githubusercontent.com/5204667/71675727-7bdee580-2d8f-11ea-8daf-31ae55dfee8e.png)

Дискордо-реквест от Armolitskiy#4866

Какой-то ппц. Вангую лютый дисбаланс и огромные проблемы, если такое начать реализовывать, но оно собрало много лайков, так что есть смысл рассмотреть.

**Comment by MrMagick2104** [comment]
Разве ещё нет иссуя по этому поводу - #1101 ?
