### ISSUE TITLE
Вещи под шапкой

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1126]
![image](https://user-images.githubusercontent.com/5204667/71675822-b8aadc80-2d8f-11ea-9dc7-6564a50090bc.png)

_Дискордо-реквест от Koronoshka#1895_

**Comment by Cinericius** [comment]
Как реализовать? Сначала класть в шапку, потом надевать? Можно шапку контейнером сделать, как некоторые сьюты. В принципе забавно, попробовать можно.

**Comment by koronoshka** [comment]
Давайте только если будете впиливать, то не коряво. А то обезьяны, мыши, ианы и дроны обзаведутся анальным слотом, так как они могут надеваться как шапки.
