### ISSUE TITLE
Рандомные наборы для трейторов

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1128]
![image](https://user-images.githubusercontent.com/5204667/71675902-f3147980-2d8f-11ea-9267-8e187465b86d.png)

_Дискордо-реквест от Firefroge#5927_

**Comment by Cinericius** [comment]
Так они же есть, random item и random items, не? Там можно один купить и много на все кристаллы. В Badassery, если не ошибаюсь.
Или не работает?

**Comment by LLIkolnik** [comment]
Тут речь идёт о специальных китах, мне кажется, как на том же, допустим, ТГ, где тебе посылается коробочка с определённым набором из одежды и приборов, вроде десворда и костюма церковника (набор а-ля джедай), а наборов таких - порядка десяти.

**Comment by Cinericius** [comment]
Накидайте примеры наборов штолле или ссылку где посмотреть.
