### ISSUE TITLE
Починить аномальные батареи

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1129]
![image](https://user-images.githubusercontent.com/5204667/71675973-1808ec80-2d90-11ea-855b-61e1656875ae.png)

Без понятия что с ними не так и что это вообще за батареи.
_Дискордо-реквест от FoxStein#9547_

**Comment by Vostok-Odin** [comment]
Тут я подробно расписывал.
#480

**Comment by Epicus7** [comment]
Название там такое себе было. Поменял там название и поставил повышенный приоритет. Я так понимаю у нас главная фича аномалистов не работает и всем похуй, мда.
