### ISSUE TITLE
Оптимизация машинерии

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#113]
Контроллер машин стабильно жрет слишком много процессорного времени и вылезает за тик. Нужно выяснить в чем дело и снизить нагрузку.

![image](https://user-images.githubusercontent.com/5204667/44680531-a3f56080-aa46-11e8-8589-afd9bb65eaca.png)

**Comment by igorsaux** [comment]
Оптимизировалось в #4900. Давно устарело.
