### ISSUE TITLE
Security Cadet

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1131]
![image](https://user-images.githubusercontent.com/5204667/71676092-59010100-2d90-11ea-85fa-c30e87703a84.png)

_Дискордо-реквест от Necrome#2527_

**Comment by Cinericius** [comment]
Есть junior officer как подпрофа щиткурити.

**Comment by ArmolitskiyCarpoeb** [comment]
С доступом, как у офицера

**Comment by MrMagick2104** [comment]
> Есть junior officer как подпрофа щиткурити.

Младший офицер по званию всё равно выше кадета будет, потому что первый уже служит, а второй - нет.

**Comment by Cinericius** [comment]
А нужны ли эти 100500 разновидностей личинок СБ с недодоступами всех сортов?
