### ISSUE TITLE
Добавить костры

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1135]
![image](https://user-images.githubusercontent.com/5204667/71676699-ebee6b00-2d91-11ea-967a-3e08575fba5c.png)

_Дискордо-реквест от DR111#8053_

Напоминаю, что у нас космическая станция. И костер в закрытом пространстве очень быстро сжигает кислород, так что при отсутствующей вентиляции эт будет очень весело.

**Comment by TermService** [comment]
нет.
