### ISSUE TITLE
Решить проблему 2+ аксессуаров

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1136]
![image](https://user-images.githubusercontent.com/5204667/71676812-38d24180-2d92-11ea-8150-24ffe2829066.png)

_Дискордо-реквест от Skitzo#1114_

Как решать - неизвестно. Надо думать.

**Comment by MrMagick2104** [comment]
> Как решать - неизвестно. Надо думать.

Можно вынести взаимодействие с аксессуарами на панель сверху, где магбутсы, шлемы, фонарики и прочее, но это прокатит, только если максимумом один предмет-хранилище + кобура надевать: кобура в панели сверху, а предмет-хранилище на одежде используется, либо вынести их неограниченно количество также в панель сверху, но неудобно будет по разгрузкам и бандольеркам лазить.

**Comment by Srankl1n** [comment]
пацан не шарит, что используется только тот аксессуар, который был одет последним
к примеру: сначала надеваешь кобуру, а дальше - разгрузку, и вауля - ствол достаешь вербом Holster, доступ к разгрузке по клику на униформе.

**Comment by MrMagick2104** [comment]
Шарит-не шарит, но если реквест набрал ~20 стрелочек вверх, то можно сказать, что это для многих неочевидно (неожиданно, на самом деле),  а это уже проблемы с геймдизайном, которые надо решать.

**Comment by Srankl1n** [comment]
ну тогда инструкцию напишите, как этим пользоваться и не срите в уши

**Comment by MrMagick2104** [comment]
Не лучше сделать как-нибудь нормально, чтобы не нужно было в мануал лезть по каждой такой мелкой причине?

**Comment by Srankl1n** [comment]
ну можно еще сделать так, чтобы при клике у тебя дополнительный слот с пушкой открывался, если у тебя разгрузка... но не знаю будет ли это удобно............. у меня честно идей нет

**Comment by Cinericius** [comment]
Разве что реально наверх вынести или в object, хотя есть у меня смутное ощущение, что ПКМ по предмету даст возможность взаимодействовать с любым аксессуаром уже сейчас, но это могут быть ложные воспоминания.

**Comment by MrMagick2104** [comment]
ПКМ даёт возможность отцепить любой аксессуар и использовать команду холстер, на этом всё.

**Comment by TapKo4eB** [comment]
Запилите просто приоритет взаимодействия для этих акссесуаров, тогда проблем не будет.

- Первым запилите веббинги и прочее что хранит вещи.
- Вторым все холстеры, т.к. на них есть хоткей.
- Всё остальное ниже, чтобы не мешалось.

**Comment by Epicus7** [comment]
Сейчас работает приоритет "что последним повесил, то первым и активируется". Если активировать нельзя, то переходит к следующему предмету.

Поэтому вешаете холстер, сверху веббинг. Получаете доступ к веббингу по клику, а к холстеру через верб. Я думаю приоритет точно не нужен больше никакой.

Самое лучшее решение что я здесь вижу - реально выносить кнопки наверх к фонарикам и баллонам.

**Comment by TapKo4eB** [comment]
Приоритет нужен для того чтобы если космонавтик и просрался с порядком надевания, то всё работало бы исправно.
А если в худ реально добавить кнопку холстера, то проблема эта не исчезнет, ибо без приоритета надетый сверху холстер на тот же поуч не даст достать из поуча предметы.
И будет у тебя целых две возможности использовать холстер, по новой кнопке и по нажатию по одежде, да вот только нахера?

**Comment by MrMagick2104** [comment]
> И будет у тебя целых две возможности использовать холстер, по новой кнопке и по нажатию по одежде, да вот только нахера?

Приоритеты - это очевидно, а кнопка всё равно нужна ведь. Не все с хоткеями играют, не у всех они нормально работают.
Да и кнопки можно на все используемые аксессуары запилить.

**Comment by TapKo4eB** [comment]
Против кнопки я не имею ничего против. Я просто говорю что если её и добавлять, то приоритет тоже.
Иначе карусель получается.

**Comment by TobyThorne** [comment]
В каком-то смысле исправлено в https://github.com/ChaoticOnyx/OnyxBay/pull/10790
