### ISSUE TITLE
Сломались бороды в редакторе персонажей

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1137]
![image](https://user-images.githubusercontent.com/5204667/71676948-82229100-2d92-11ea-989d-2bde74dac6f5.png)

_Дискордо-репорт от IlyaIII#1488_

**Comment by Vostok-Odin** [comment]
Прямо сейчас на мэйне бороды нормально меняются.

**Comment by Epicus7** [comment]
Ilyalll подтвердил, что сейчас все работает. Закрываю баг.
