### ISSUE TITLE
Вместимость желудка

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1139]
![image](https://user-images.githubusercontent.com/5204667/71677116-0248f680-2d93-11ea-8954-0c953e242a65.png)

_Дискордо-реквест от Faceless#9510_

**Comment by Cinericius** [comment]
>30u
>как у мелкой склянки или баночки
>ебучее ЖКТ

Рирж

**Comment by TobyThorne** [comment]
Уже увеличили, теперь 65.
