### ISSUE TITLE
Оптимизация мобов

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#114]
Контроллер мобов стабильно жрет больше положенного времени и вылезает за тик. Нужно разобраться в чем дело и снизить требуемое процессорное время.

![image](https://user-images.githubusercontent.com/5204667/44680663-1d8d4e80-aa47-11e8-91a3-c9997c7240c4.png)

**Comment by Epicus7** [comment]
Уменьшил потребление примерно в два раза ee0ae7598e1ae7f9fe58c2618e7662aff1fecee0.

![image](https://user-images.githubusercontent.com/5204667/44691341-f8a8d380-aa66-11e8-859b-a88e13870d29.png)

Но контроллер все равно уходит за выделенное время, судя по MC. Возможно, тут дело в подсчете. А может и нет - надо дальше смотреть.

**Comment by igorsaux** [comment]
Оптимизировалось в #5017, #4980, #4901, #3885. Устарело.
