### ISSUE TITLE
Гайд как убить просветы

### ISSUE THREAD

**Issue by Filatelele** [ChaoticOnyx/OnyxBay#11446]
### Просветы и откуда они берутся
Причина просветов - рунчат вместе с изменениями матрицы (update_transform()) вызывает незадокументированное поведение бьенда. По какой-то причине имаж рунчата начинает влиять на просчет видимости. Как результат - получаем просветы.

<details>
  <summary>Видео и размышления на тему причины просветов </summary>

https://github.com/ChaoticOnyx/OnyxBay/assets/23741266/e896efd7-3b6f-4171-bee5-47ef088ed952

Тест просветов. Изначальный body_height = 1. После варедита body_height = 1.07 и вызова update_transform() появились просветы. 

https://github.com/ChaoticOnyx/OnyxBay/assets/23741266/8ac79f25-6fd8-4b0e-a160-b7c569a153b4

Оба моба со стандартным ростом. Пока моб стоит - никаких просветов нет. Как только прожимается rest, вызывающий update_transform() появляются просветы. 
`		rotate_deg += 90
		translate_x = 1
		translate_y = -6` 

https://github.com/ChaoticOnyx/OnyxBay/assets/23741266/a672f1f3-65c9-42e3-964a-926fc2b4ab76

На видео ниже - тест с реворком рунчата на скорую руку. Loc имаджа с текстом - hud_object у моба. Как только мы убираем рунчат с игрового плейна - все просветы исчезают.

https://github.com/ChaoticOnyx/OnyxBay/assets/23741266/5b1b182c-3739-47fb-9db3-204a3e053f41

</details>

### Решение
По всей видимости, решения с ТГ не очень подходят нашему билду вследствие использования update_transform() с изменением матрицы моба - рост, сдвиг при ресте и.т.д.
Можно попробовать выводить изображения рунчата в худ моба. Пример реализации - голографические карты.

### (Опционально) Дополнительная информация

<details>
  <summary>Мобы появляются в экзамайне не того тайла </summary>

Картинка - ниже. С очень большой вероятностью связано с - https://www.byond.com/forum/post/2909701. Предположительно, имажи рунчата не пропадают, а просто убираются в нулевую альфу. Точно так же убирается выводом рунчата в худ моба.

![image (4)](https://github.com/ChaoticOnyx/OnyxBay/assets/23741266/9bf50297-7b94-496a-937c-081caa980780)

</details>

**Comment by kreeperHLC** [comment]
**За закрытие данной задачи выставлена награда размером в N рублей!**

Подробности у Фила в личке.

**Comment by Filatelele** [comment]
Если #11440 это не закроет то можно закрывать билд. 

Для потомков, на случай если #11440 не поможет. Есть другие решения. 
- Перенос рунчата в худ клиентам (А это тотальный реворк всего рунчата с ебейшими трудозатратами)
- Попробовать заменить pixel_x/pixel_y на pixel_w/pixel_z в трансформах мобов.
- Привести плейны в порядок, так чтобы BLACKNESS_PLANE накрывал невидимые турфы (то есть вынести его с неработающего -5 плейна на нулевой)
