### ISSUE TITLE
Нет кнопки закрытия у медицинских сканеров (body scanner)

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1147]
![image](https://user-images.githubusercontent.com/5204667/71706108-fccfc880-2df3-11ea-88c6-cd8e015b41de.png)

Окно посередине

**Comment by hard-res3t** [comment]
Теперь вроде есть...
![изображение_2021-04-08_153409](https://user-images.githubusercontent.com/59255670/114027270-de227200-987f-11eb-944e-baf028ad897b.png)

**Comment by MaxFreemen** [comment]
Баг починили, закрываем.
