### ISSUE TITLE
Открытие сломанных дверей руками.

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1148]
### што
Сделать второй путь открытия дверей если ты проебал лом. Руками. Больно, шумно, и долго.

### как
Закодить верб для открытия дверей руками.
И чтобы это не было слишком смешно:

- Открытие занимает дохрена времени.
- Урон по рукам при совершении/попытки открытия.
- Громкий звук на два квартала при совершении действия.

**Comment by Cinericius** [comment]
Щас бы убить целый пласт геймплея и обесценить целый инструмент из-за чьего-то РРРРЕЕЕЕЕ Я ЗАСТРЕВАЮ.

**Comment by Traysoul** [comment]
Послушайте мистер геймдизайнер, часто бывает, что люди застревают без ломов на шаттле без электричества и связи. И они вынуждены ждать рандома, который зачем-то придёт к прибытию. Или ливнуть просто.

**Comment by PlinHost** [comment]
>застревают без ломов на шаттле
1. Надеваешь из коробки в рюкзаке маску и баллон.
2. Разбиваешь стекло баллоном.
3. Прыг прыг прыг по космосу.
4. ?????
5. RIP

**Comment by Cinericius** [comment]
Эту проблему надо решать другими способами. Например, положить на шаттл ломик или пару (к слову, на олдовых билдах часто так и было, на том же Ферне).
Это:
1) Значительно проще, чем кодить.
2) Не убивает игру в спасение рядового ксенобиолога.

**Comment by Epicus7** [comment]
Мы начинаем забывать, что самое интересное в работе инженера - спасение людей. Остальное чистый механодроч.
