### ISSUE TITLE
Передёргивание затвора оружия и патронник

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1149]
### Улучшение
Перед тем, как пуля вылетает из ствола, патрон попадает в патронник путём передёргивания затвора или, если оружие автоматическое/полуавтоматическое, то после предыдущего выстрела, либо вкладыванием патрона вручную. Очевидные вещи: если патроны находятся в магазине, но ни одного в патроннике нет, а спусковой крючок нажат, то ничего не происходит. Если есть патрон в патроннике, а магазин вынут, то патрон остаётся в патроннике. Не у каждого оружия есть нужда в досылании патрона, например, её нет у револьверов, переламывающегося оружия, зипганов, а у помповых дробовиков это уже реализовано.

### Решение
Впилить патронник, как отдельный слот для патрона, и автоматическую подачу в него патронов из магазина после выстрела не так уж и сложно, я думаю. Проблемы могут возникнуть со сменой режима стрельбы на автоматическом оружии, так как сейчас действие на него переключает режим, а должно передёргивать затвор. Решить можно перенесением смены режима в вёрбы и контекстное меню.

**Comment by Cinericius** [comment]
Допустим, но зачем? Какую геймплейную задачу это решает?

**Comment by MrMagick2104** [comment]
Такую же, как, допустим, сердце, лёгкие, почки, прочие внутренние органы в механе. Они нужны просто потому что без них человек ирл жить не будет, хотя ведь можно было всех космонавтиков сделать простыми мобами с одной-единственной плашкой хп, без всяких там усложнений, ведь так и производительность выше, и кодить особо не надо, и игрокам проще: кликнул бинтиками по спрайтику и оп!, регенерация здоровья началась.
Также и тут: оружие спокойно может обходиться без вот этого всего, да и играть проще, к тому же кодить не надо, но, всё-таки, оружие работает не совсем так, как это сейчас представлено.
ССка-то всё же должна быть сложнее, потому что в этом её смысл, её особенность. Можно ведь пойти и играть в какой-нибудь ТТТ на сурсе, ведь идея, по-факту, та же самая: где-то происходят стрелялочки, общение, обманы из-за того, что кто-то злой пришёл, либо просто без причины, а не мучаться с бесконечными лагами, багами, сложной системой регуляции отношений, судами, которых бы не было, если СС была бы проще, но нужна ли тогда эта самая СС?
Если смысл всей игры в том, чтобы быть не такой уж и простой, а глубокой и завлекающей своими обширными возможностями, которые предстоит исследовать самостоятельно, при том, эти самые возможности ведут себя примерно также, как и в нашей реальности (или изо всех сил стараются), то почему бы слегка не улучшить механику стрельбы и обращения с оружием, добавив пару фич?

**TL;DR**: нужно затем, зачем и местная медицина: более глубокая проработка геймплея, приближение к реальности, aka _реализм_.

**Comment by Cinericius** [comment]
>Такую же, как, допустим, сердце, лёгкие, почки, прочие внутренние органы в механе. Они нужны просто потому что без них человек ирл жить не будет

Они так-то говоря нужны, чтобы занимать медиков работой, СБ пытками, а космонавтиков - внезапными отказами.

>хотя ведь можно было всех космонавтиков сделать простыми мобами с одной-единственной плашкой хп, без всяких там усложнений

ССка, особенно БейСтейшун - это игра-система. Тут цимес как раз во возникновении историй на фоне взаимодействия множества сложных систем типа химии, медицины и инженерки.

>и игрокам проще: кликнул бинтиками по спрайтику и оп!, регенерация здоровья началась.

Тащемта ТГ, которые отошли от системного геймплея в сторону ненапряжной 2D-каэсочки, именно так и сделали. Это не что-то плохое, это просто другое.

>оружие работает не совсем так, как это сейчас представлено.

Как таковое это не есть проблема.

>эти самые возможности ведут себя примерно также, как и в нашей реальности (или изо всех сил стараются)

Тащемта сложный геймплей не равен реализму. Это как раз проблема многих современных геймдизайнеров, особенно индюшных - люди не понимают, в чем разница между реализмом ради реализма и иллюзией реализма ради интересного игрового опыта. ССка-таки не симулятор (разве что атмосферы).

>то почему бы слегка не улучшить механику стрельбы и обращения с оружием

Так вот вопрос в том, улучшится ли она. С одной стороны, это добавит историй уровня "не успел передернуть затвор и соснул", что потешно. Кроме того, можно еще добавить шанс срыва ударника при падении оружия на пол, с последующим выстрелом в рандомном направлении или в ногу хозяина, если он упал с волыной на поясе - это создаст некую вариативность игровых стратегий (носить ли патрон в патроннике, что позволит быстрее начать стрелять в случае чего, но потенциально опасно). С другой стороны, не поломает ли это что-то, что уже хорошо работает? Баланс, например. В общем, надо плюсы и минусы с точки зрения гамеплау, а не с точки зрения "ууу больше реализма потому что реализм".

**Comment by MrMagick2104** [comment]
> Баланс, например.

То что мертво, умереть не может, как говорится. Простенький пример, как за тритора в одних портках, но с аплинком, можно перерезать вообще всех, не делая никаких особо сложных усилий:
1) Делаем бинд на блок и смену руки блока.
2) Берём световой меч и револьвер .357 в аплинке, боеприпасов делаем в автолате в гетто.
3) Берём меч в одну руку, .357 в другую, выбираем блок на вторую руку, включаем блок, идём стреляться. 
4) Всех, кто пытается подойти на близкую дистанцию, лишаем пяток из револьвера. Любые снаряды можно заблокировать мечиком, если попадать в тайминги (спамить) кнопкой блока. Когда опонентов в состоянии к сопротивлению нет, можно спокойно идти добивать их в ближнем бою.
5) ???
6) Profit!

И это только единственный из множества пример, хотя таких (псевдо)робустных лайфхаков можно найти почти у любой роли, и не по одному, я уверен.

По поводу надобности. Например, с точки зрения ролевухи, передёрнуть затвор, допустим, угрожая кому-то - неплохое действие, а то сейчас приходится полчаса набирать эмоуты, либо кричать что-то вроде "эээ, слы, у меня ствол", так как не все особенно сильное внимание придают этому, может и не заметить кто-то маленький по размерам пистолет. Или под конец пафосной, воодушевляющей речи взять и дёрнуть, так чтоб прям все вокруг видели сообщение в чатике, и ещё звук громкий.
Кстати, по поводу звуков. Если сделать его чуть громче, чем на два тайла, то это можно будет использовать для тактики: сидит террорист, бомбу заложил в комнатке, ждёт штурма. Когда подходят секурити, они, естественно, затворы начинают коллективно дёргать, потому что знают: предстоит стрельба. А ехидный террорист сразу подготовился стрелять, так как услышал лязг затворов.
А ещё обращение с оружием, тоже важная вещь.

**Comment by Vostok-Odin** [comment]
> Например, с точки зрения ролевухи, передёрнуть затвор, допустим, угрожая кому-то - неплохое действие..

У вас целая система прицеливания есть, чтобы это делать....
Но фича с пулей в патроннике мне нравится.

**Comment by MrMagick2104** [comment]
> У вас целая система прицеливания есть, чтобы это делать....

Из-за всеми любимого нёрфоцирка, пока ты прицеливаешься, тебе спокойно могут лицо сломать (aka набить ебало петушителем), ведь если ты начал прицеливание, после чего человек побежал прямо на тебя в мили, то ты сразу взять и начать стрелять не сможешь, так как тебе нужно ещё режимы переключить, до чего тянуться далеко (справа снизу в хаде - не слишком удобно, j с хоткеями - тоже, т.к. с хоткеями одна рука на мыши, а другая - на wasd), а если ты передёргиваешь затвор, то ты чётко показываешь, что жвачка у тебя закончилась и ты прямо вот сейчас готов стрелять.

P.S. Ещё по поводу режима прицеливания: впиливание автоматического переключения с режима собственно прицеливания на активную стрельбу при сбитии "наведения" сделало бы его чуть менее бесполезным говном, чем сейчас.

**Comment by Cinericius** [comment]
Вот теперь убедил.

**Comment by Voldirs** [comment]
>а если ты передёргиваешь затвор, то ты чётко показываешь, что жвачка у тебя закончилась и ты прямо вот сейчас готов стрелять

Для меня это например будет лишь способ заиметь на один патрон в пушке больше. Заранее вставляешь полный магазин, досылаешь, заряжаешь новый магазин. Никаких выебонов затвором ибо это тупо.

**Comment by MrMagick2104** [comment]
> Для меня это например будет лишь способ заиметь на один патрон в пушке больше.Заранее вставляешь полный магазин, досылаешь, заряжаешь новый магазин.

Тоже абсолютно нормально. Если поиграть во всякие тактические шутаны, аля инсёрдженси, то там делает так каждый второй и это _абсолютно_ нормально, так сделает любой здравомыслящий человек, потому что это - целый патрон, который может спасти тебе жизнь, особенно если ты косой, но так делать совершенно необязательно. При условии, что к этому добавятся какие-то недостатки (вроде случайных выстрелов с некоторым шансом, если у тебя из рук оружие выбили, застанили или просто по руке ударили), то это будет хорошей такой фичей.

**Comment by Cinericius** [comment]
Я вам больше скажу, так некоторые ИРЛ те же травматы носят, хотя патрон в патроннике без необходимости применения оружия - админка за нарушение правил безопасного обращения при проверке сотрудником полиции. Как раз потому что так стрелять начать быстрее и проще, можно делать это с одной свободной рукой и есть целый дополнительный патрон.
И-таки да, иногда (редко) оно случайно стреляет у некоторых.

**Comment by Epicus7** [comment]
@Cinericius, тут нужен диздок нормальный. Я вот пробежался глазами и сразу куча вопросов:

* Какое оружие нужно менять?
* Как вынуть патрон из патронника? Как проверить, есть ли там патрон? Пилить два верба на это?
* Как дослать первый патрон в патронник? Еще один верб пилить?

Плюс из-за обилия оружия в билде и особенностей каждого отдельного оружия, ожидаю тут кучу подводных камней и возможных багов. Так что сложность повышаю как минимум до тех пор, пока не появится нормальный диздок.

**Comment by MrMagick2104** [comment]
> Какое оружие нужно менять?

Любое, которое обладает затвором, т.е. всё, кроме лазерного, надламывающегося (дробовик бармена), револьверного, однозарядного.
> Как вынуть патрон из патронника? Как дослать первый патрон в патронник?

С передёргиванием затвора в патронник попадает первый патрон из обоймы, а текущий патрон вылетает. Если патрона в патроннике нет, то при передёргивании патрон только досылается. Для удобства переназначить обычное использование на передёргивание затвора, а смену режима стрельбы в отдельные вёрбы выкинуть.
> Как проверить, есть ли там патрон? Пилить два верба на это?

Предлагаю при экзамайне стрелкового оружия в руках сделать небольшую задержку (как при заклеивании маленьких ранок пластырем) в 0.5-1с. После того, как экзамайн происходит, показывать есть ли в патроннике патрон, а также сколько патронов в магазине. Сколько патронов в магазине оружия на полу узнать, не взяв его в руки, нельзя. При этом, во время экзамайна можно проигрывать "неполную" анимацию передёргивания затвора, такой длины, чтобы умещалось во временной промежуток действия, если такую анимацию вообще решат сделать.
Бонусом гифка (в слоумо) того, как проверка патронов выглядит в Rising Storm 2 Vietnam, для наглядности:
![RS2Vm1911ammocheck](https://user-images.githubusercontent.com/58848742/71809337-f73ae280-3080-11ea-82a3-dfa1f7e4447b.gif)

**Comment by Cinericius** [comment]
^^^

**Comment by Epicus7** [comment]
> Для удобства переназначить обычное использование на передёргивание затвора, а смену режима стрельбы в отдельные вёрбы выкинуть.

Офигенное "удобство". Все игроки привыкли к одному поведению, а мы его сейчас поменяем. Мало того, будет неконсистентность с другими билдами - игроки будут приходить с других серверов и офигевать.

Здесь же есть люди, которые тоже не понимали изменений в системе раздевания других человеков? Вот будет тоже самое.

> Предлагаю при экзамайне стрелкового оружия в руках сделать небольшую задержку (как при заклеивании маленьких ранок пластырем) в 0.5-1с.

Тогда уж задержку не при экзамайне, а после. Не сам экзамайн задерживается, а через некоторое время дописывается дополнительная инфа. Как с проверкой пульса у людей.

> сколько патронов в магазине. Сколько патронов в магазине оружия на полу узнать, не взяв его в руки, нельзя.

Магазины то тут причем. Иссуй про затворы, вот теперь мы еще и магазины меняем.

@Cinericius, диздока в ОП-посте все еще нет. Каким образом этот иссуй реализовывать и, что важне, как принимать ПРы, если ты так и не написал что КОНКРЕТНО тут надо делать. Не надо ссылаться, пожалуйста, на посты игрока, который накидывает с каждым постом все больше маняидей. Надо выбрать что мы делаем, а что - нет. И описать это в ОП-посте.
