### ISSUE TITLE
Механ затралливания жирнотриторов через ЦК

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#115]
Сделать в коммандную консольку возможность отправить на ЦК рапорт с жалобой на предательство со стороны члена персонала (указывается через Crew Records). Делать это будут АВД и, возможно, капитан. 
Тритор, попавший в рапорт, автоматом получает редтекст (надо соответственно добавить либо отдельный обжектив, либо дополнить обжектив на эскейп). Нетритор, попавший в рапорт, приводит к жопбану (возможно даже автожопбану) на капитана и АВД у отправившего рапорт.
Зачем? Чтобы триторы играли осторожнее и не палились лишний раз.

**Comment by denver1000** [comment]
Но что если кто-то подставит нетритора?

**Comment by Voldirs** [comment]
Такая себе идея потому что экипаж без ролек зачастую ведёт себя не хуже триторов, а порой даже лучше и задорнее.
И  таком случае лучше да, отдельный обджектив. 
Энивэй есть же люди, которым исключительно похуй на гринтексты, они будут играть как играли.

**Comment by LagannPM** [comment]
То что происходит в раунде должно оставаться в раунде, пускай педали джопки выдают.
И тритор не должен знать что его обнаружили, в этом весь элемент неожиданости

**Comment by Fourest** [comment]
Не, хуйня

**Comment by Epicus7** [comment]
Предлагаю добавить отдельный обжектив, да. И выдавать его отдельно с некоторым шансом.

Джоббаны и уменьшение приоритета при выборе ролек итак будет в реализации репутации когда-нибудь.

**Comment by Cinericius** [comment]
Пожалуй, сейчас в таком виде скорее не надо, чем надо.
