### ISSUE TITLE
Наборы экипировки для СБ

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#1150]
Генерирование наборов экипировки для СБ в начале раунда, чтобы в каждом раунде СБ имели немного разные вещи. Интегрируемо в сторителлер, но запиливаемо и отдельно от него. 

Суть токова: в начале раунда кидается кубик, от которого зависит, какая будет экипировка в шкафчиках и в армори.

Шкафичики (все спаунеры настраиваются синхронно, то есть содержимое всех шкафчиков идентично):
1) Униформа. У нас ее и так несколько вариантов, но все они доступны в каждом раунде, а петрушечное СБ - это такое себе. Пускай оно будет одинаковое в раунде, но разное между раундами. Вероятности униформ - равные.
2) Тазеры или .45 с резиной. Бугурты будут, но почему нет? Пускай тазеры будут в 2/3 или 3/4 случаев.
3) Гранаты. Флешбенги или перцовки. Да, в теории их все равно можно добрать из всяких раздатчиков и оружейки, но пускай в шкафах все равно будут разные в разных раундах.
4) Флешки и перцовки. Аналогично.
5) Дубинки - станбатоны и классические полицаевки. Станбатоны в 3/4 случаев. Можно еще добавить микрошанс телескопичек, но я не уверен, что это хорошая идея.

Оружейка (асинхронные спаунеры, соответственно возможны разные количества разных вещей в разных раундах):
1) Броня. Сегодня больше баллистики, завтра больше аблативок.
2) Оружие. Сегодня завезли дополнительных СМГ, завтра сплошные лазкарабины. Единственная нерандомная вещь - ионки, ибо баланс.

**Comment by LLIkolnik** [comment]
Сам написал - сам одобрил. Аве непредвзятое мнение.
Рандом это, конечно, хорошо и весело. Ан нет подождите рандомный выбор между чем-то имбалансным и чем-то перенёрфанным (тазер и .45) это ж говно и уныло. Вот про униформы хорошо задвинул, только как это реализовывать в условиях лоадаута, который возвращает петрушечное СБ - другой вопрос. Рандомная броня это тоже странно, а с рандомным оружием согласен почти полностью за исключением ионок - их тоже можно всунуть в ротацию. Короче, нужно обсуждать, делать голосования, пилить мемократию, но никак не сувать в продакшн.

**Comment by Cinericius** [comment]
>Сам написал - сам одобрил. Аве непредвзятое мнение.

Мне можно

>рандомный выбор между чем-то имбалансным и чем-то перенёрфанным (тазер и .45) это ж говно и уныло

Будут жалобы - будет повод отбалансить. Но вероятности, если ты обратил внимание, неравные.

>в условиях лоадаута, который возвращает петрушечное СБ

Вот кстати спасибо, что напомнил, лоадаут можно будет порезать.

>Рандомная броня это тоже странно

Броня в оружейке не так много решает на самом деле, обычно все бегают как бегали при любой тревоге и пиздятся засчет скилла и пяток.

>ионок - их тоже можно всунуть в ротацию

Они там в таких количествах лежат из-за охуевающих синтетов, так что лучше не вскрывать эту тему.

**Comment by koronoshka** [comment]
Если появляется ретро оружие, то это лишь нагрузка на карго в начале игры как по мне. Просто закажут что-то получше.

**Comment by LLIkolnik** [comment]
>Будут жалобы - будет повод отбалансить. Но вероятности, если ты обратил внимание, неравные.

Это породит ещё больше жалоб и нытья, когда .45 таки выпадет.

>Броня в оружейке не так много решает

Тогда зачем её трогать?

>Они там в таких количествах лежат из-за охуевающих синтетов

Ни разу не юзал ионки для чего-либо, кроме выключения АПЦ. Что можно сделать и лазерной указкой, пусть и радикальнее и с большими последствиями. 

>ретро оружие

Вот рандом между ретролазерами и тазерами был бы смешным.

**Comment by Cinericius** [comment]
>.45

Вообще говоря, тут про резину говорят, что ее очень сложно сделать великой снова в силу особенностей кода. Можно сделать тазеры и дисейблеры (которые мочелучевые), например, хотя там тож свои подводные камни.

>зачем её трогать

Для вариативности раундов. Пригодится, особенно со сторителлером.

>ионки

Повторюсь, до них был абуз синтетов. Синтетонерфы и ионки держат ситуацию в норме, так что пускай так и будет впредь. Просто не надо вскрывать эту тему. 

>ретролазерами

Они летальные. Тут цимес во взаимозаменяемости снаряги, поэтому гранаты варьируют с гранатами, дубинки с дубинками, а тазеры - с другим нелеталом.

**Comment by Traysoul** [comment]
Зачем ограничивать людей? Если они берут одинаковое вооружение - то значит сами так хотят. Ваши обязательные ЧЕЛЛЕНДЖИ и РОЗНООБРАЗИЕ нахуй никому не всрались. И вообще всё предложение - инвалид, потому что как сказали есть карго. Просто появится лишняя трата времени на заказ всего этого.

**Comment by Cinericius** [comment]
>Зачем ограничивать людей?

Потому что интерес вырастает не только из возможностей, но и из ограничений. Людям свойственно хотеть ВОЗМОЖНОСТЕЙ и не хотеть ограничения, потому что это адаптивно ИРЛ, но игра должна быть интересной, а казуалка без трудностей интересной не бывает по определению. В этом, вообще говоря, заключается одна из трагедий бытия современных людей из мегаполисов, всякой золотой молодежи, у которой все есть, но которой нихуя не надо. Жить становится не интересно, когда нет вызова, так устроены люди, пушо эволюционировали мы в среде с вызовами и превозмогание вызовов давало плюшки (а иногда было необходимо для выживания). 
Вообще, кто-то из известных геймдизайнеров (вроде нинтендовских) однажды сказал про читы, мол, если дать игрокам полную свободу, то они убьют интерес игры для себя. Собсно это актуально не только для читов, поэтому хороший геймдизайнер должен мочь в издевательства над игроками. Главное не перегнуть и не подать виду.

>инвалид, потому что как сказали есть карго. Просто появится лишняя трата времени на заказ всего этого.

Это не лишняя трата времени. Лишняя трата времени - это, скажем, удалить все инструменты, чтобы их надо было печатать в автолатах каждый раунд.
В данном же случае мы имеем усиление межотделовых взаимодействий (и межигроковых как следствие), что уже неплохо, плюс мы поднагружаем карго, которое часто пинает хуи (а сейчас как раз подъехали обновы про торговлю с ЦК, так что будет СиНеРгИя). Ну и будет это не каждый раунд, да.

**Comment by Voldirs** [comment]
> .45 с резиной

летал и только летал, чтоб по-мужски, гондономётами даже ирл не пользуются в таких калибрах

**Comment by Cinericius** [comment]
>гондономётами даже ирл не пользуются в таких калибрах

Ты что, не слышал о легендарном калашниковском макарыче в .45 калибре, любимом друге каждого гордого горца, вышибающем из тапок первым же выстрелом?
Гениальная же поделка для отжима денег у долбоебов.

**Comment by Voldirs** [comment]
Я имею ввиду людей с доступом к человеческому короткостволу. Гондономёты, переделанные из пистолетов, расчитанных под нормальные скорости и энергии, по дефолту не могут быть хорошим выбором потому что для останавливающей силы нужен нормальный импульс, а в малых калибрах хорошего импульса, но при этом чтобы была низкая энергия, добиться тяжело/нецелесообразно.

**Comment by Cinericius** [comment]
Бля, может ОСУ для СБ завезти.

**Comment by Traysoul** [comment]
Вся станция - это челлендж для сб, и всякая хрень вроде "Ой вам тазеров не довезли))" Ахуеть какого экспириенса не прибавит. Это как делать сложность в увеличении хп и урона противников.

**Comment by Cinericius** [comment]
Причем тут "не довезли"?

Перечитай иссуй.

**Comment by TobyThorne** [comment]
Панч погиб, отправляю на повторное рассмотрение.

**Comment by kreeperHLC** [comment]
По сути уже реализовано, так как на разных картах СБ различается, плюс есть возможность выбрать оружие.
