### ISSUE TITLE
Серийные (инвентарные) номера для огнестрела.

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1151]
### Улучшение
Ввод серийного номера для огнестрела.
### Зачем?
Аутичное развлечение для любителей бюрократии и варденов с завхозами. Приведу пример ситуации, в которой это может найти практическое применение:
1) Варден выдал пистолет сорок пятого калибра офицеру СБ, с серийным номером.
2) Офицера СБ кто-то избил до потери памяти, попутно раздев догола.
3) Чуть позже арестовывают ассистента с пистолетом, серийный номер которого совпадает с тем, что был у офицера.
4) Варден с детективом используют свои три общие клетки мозга для того, чтобы понять, откуда у ассистента пистолет, успешно делая вывод, что именно этот ассистент избил офицера, а не какие-нибудь торговцы его подогнали за двести межгалактических рублей.
5) Вершится правосудие и ассистент получает дополнительное наказание - две смертной казни вместо одной.

Ещё можно будет точно сказать, когда какой-то предмет украли, и то, что это действительно он.
_Б ю р о к р а т и я_

### Решение
1. Всему раундстартовому огнестрелу выдается случайный серийный номер
2. Нелегальное оружие(то которое не было распечатано на станции) или прислано в карго не имеет серийного номера.
2. У смотрителя в коморке есть листок со всеми номерами огнестрела из брига
3. Любой огнестрел при создании в автолате получает свой номер.
4. Удалить номер можно: кислотой, отверткой (с большим шансом провала) 

В иссуе, по этой причине предлагаю сжать до этих пунктов. Лучше ограничить ее только огнестрелом, так как это летальное оружие и не переносить на всякие биты, и холодное оружие.

Базу данных со списком оружия и записях о выдачи лучше делать в другом иссуе.

**Comment by Cinericius** [comment]
Недавно играл ХоСом, в середине раунда шахтер запросил лазкарабин для защиты от мобов, а потом учёный прикатил пачку адвансед-еганов с просьбой разрешить ему оставить один себе.
Обмазался лейблером и почувствовал себя ЛРОшником. В целом смешной экспириенс, но слишком много номеров на всем подряд убьет цимес работы дефектива, который так-то говоря и должен определять, украдена вещь или нет.

**Comment by MrMagick2104** [comment]
Номера на всём подряд и сейчас могут выставлять всякие ебанутые каждый раунд лейблером, но у него такая проблема, что бирку можно оторвать голыми руками, если я не ошибаюсь. Для того, чтобы стереть маркер, нужно, раз, заметить то, что кто-то им что-то написал, так как для этого нужно заценить предмет и внимательно прочитать описание в то время как лейблер прямо на название предмета это всё вешает, два, найти такой же маркер для стирания, три, нужен кто-то, кто эти инвентарные номера проставит.
В случае же с огнестрельным оружием, серийный номер отгравировать на заводе - плёвое дело, решив множество проблем превентивно, также добавив необходимость вардену в начале  смены делать опись всего вооружения, либо проверку с уже существующей документацией.

**Comment by MrMagick2104** [comment]
К тому же, можно немало придумать немало способов свести серийные номера:
-Кислота, которую я приводил в пример в иссуе
-Бормашинка хирурга (медленнее, чем с кислотой, но с меньшим шансом повреждения)
-Отвёртка (Сведение по одной буковке, не всегда получается, не всегда отвёртка это переживает, долго, где-то минута)
-Узкоспециализированный триторский гаджет.

Приятным дополнением станет то, что это упростит выдачу разрешения на ношения оружия, которые, правда, никто не выдаёт.
Ещё придаёт некоторой конкретности в том, что у НТ есть хоть какие-то ограничения в обороте оружия, потому что сейчас это выглядит так, словно бы этим заправляет обезьяна с синдромом Дауна. Серьёзно? Человеку нельзя выписать штраф за мачете, которое он таскает с собой без веской причины или разрешения? Тазеры не попадают под единственную статью про оружие, так как она про боевое? Учёных сажают за то, что те сделали какое-то оружие и потом сразу же разобрали в деструктивном анализаторе, потому что это нелегальное производство оружия?
Тут настолько всё херово прописано, что меня (учёного) и робототехника (за компанию) хотели как-то посадить за тот факт, что в консоли были **_уровни исследования оружия_**. 
С серийными номерами этот цирк будет выглядеть хотя бы чуть-чуть более представительно.

**Comment by Fritcher36** [comment]
Думаю, что серийник должно быть видно только при экзамайне оружия в руках или максимум на соседнем тайле. Наносить можно специальным прибором, менять им же, но долго, а доступ к нему - только у вардена и триторов, возможно у ученых, на эвэйках и с очень редким шансом в гетто.

**Comment by Cinericius** [comment]
Тут еще надо подумать, а подумать я сегодня не в состоянии

**Comment by rxssxnbxrg** [comment]
**Всё что будет написано ниже - лишь моё скромное видение реализации.**

**Preface:**
Для начала, да - серийный номер должен быть виден только при _Examine_ оружия. 

**Main part:**
Введение этой механики позволяет добавить работы смотрителю или же, желающему помочь, детективу. Следует добавить в консоли СБ новую программу - Security Service Database. В ней будут записаны все _Active_ и _Inactive_ сотрудники СБ, в том числе и вышедшие из раунда через _long-therm storage_. Нажимая на имя офицера мы попадаем в меню, схожее с досье персонала. Там смотритель должен будет заполнять данные о снаряжении офицеров, а именно - выданное им снаряжение и серийный номер выданного вооружения.

Серийный номер же будет случайно генерироваться в начале раунда/при доставке груза с оружием с ЦК по схеме - XYYXXYX. Где **X** - соответственно, буква, а **Y** - цифра. 

Также ХоС, ХоП, АВД или же Капитан могут запросить у смотрителя отчёт по выданному офицерам оружию, шаблон я составлю при одобрении иссуя. 

Несомненно, способы свести серийный номер должны быть. MrMagick2104 уже привёл возможные способы:
>-Кислота, которую я приводил в пример в иссуе
-Бормашинка хирурга (медленнее, чем с кислотой, но с меньшим шансом повреждения)
-Отвёртка (Сведение по одной буковке, не всегда получается, не всегда отвёртка это переживает, долго, где-то минута)
-Узкоспециализированный триторский гаджет.

От себя могу лишь добавить что гаджет предателя должен иметь возможность не только _удаления_ серийного номера, но и _нанесения_ нового. И естественно, после удаления серийного номера тремя первыми способами при _examine_ оружие будет писаться что-то на подобии: "_Where the serial number had been there were only scuff marks._".

**Comment by NefrNerf** [comment]
Обновил иссуй, упростив идею, прошу к повторному обсуждению.

**Comment by kreeperHLC** [comment]
Иссуй - говно.
Почему? У нас по дефолту оружие практически всегда в оружейке и все кто ходят с оружием сразу вызывают подозрение. Зачем Вардену знать откуда Ассистент получил пушку, если легально он её получить нигде не может? Причём это убивают обратную ситуацию, где сейчас ты можешь соврать что купил её у Торгаша, а не своровал.
