### ISSUE TITLE
Убрать Эклипс из ротации. 

### ISSUE THREAD

**Issue by MemoryDreams** [ChaoticOnyx/OnyxBay#1154]
### Описание бага
Четкое и понятное описание сути бага.
Эклипс это до жути сырая и неудобная карта. Даже после кучи работы проделанной над картой, после игры на ней хочется помыться. 
До того как появился Эклипс, никто не жаловался на его отсутствие. Сейчас никто не хочет на нём играть кроме нескольких извращенцев, из-за которых страдает вся станция.
После трёх месяцев игры на коробочке у меня всё ещё было желание играть ещё. После одного раунда на Эклипсе, я опять забил на игру и не появлялся там уже около месяца. 
### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем Оникс.
2. Открываем список карт в коде.
3. Нажимаем на Эклипс.
4. Видим, насколько всё плохо.

### Ожидаемое поведение
Четкое и понятное описание того, что должно было произойти.
Должна запуститься до жути неудобная карта.
### Скриншоты
Если проблема может быть показана на скриншотах - прикрепите их.
Боюсь, я не готов пожертвовать ещё парой месяцев игры, чтобы сделать скриншоты.

**Comment by LLIkolnik** [comment]
> ###**Ожидаемое поведение**
Четкое и понятное описание того, что должно было произойти.
Должна запуститься до жути неудобная карта.

Ну. Она и запустилась.
А вообще, в этом пункте нужно расписывать, что именно должно было произойти вместо бага.
По теме - Эклипс говно, но там, вроде, Альфу хотят пофиксить, когда пофиксят - можно выпилить. Чтобы ротация не пропадала хоть. But who's to say what is to say and what's not to say...

**Comment by Epicus7** [comment]
Баг - это когда что-то ведет себя не так, как должно было.

Это не баг, а "улучшение". И тут нужно ревью геймдизайнера.

**Comment by ArmolitskiyCarpoeb** [comment]
на эклипсе дормы прикольные, а еще кпп нормальный

**Comment by Cinericius** [comment]
Рампо извини
