### ISSUE TITLE
Xenobio Prometheans

### ISSUE THREAD

**Issue by BooJ1K** [ChaoticOnyx/OnyxBay#11556]
### Promethean
Все подвиды промитеев не могут получать нутриты, кроме как реген лимба.

1) Нужно дождаться падения нутритов. 
Ждать пока у вас дойдёт желешка до 350~ при этом вы никак не можете узнать, сколько её у вас, потом оно сожрёт ногу.
Выпить 200+ желле сидя на стуле, потому-что наши куклы не умеют держать предметы лёжа. 
прожать реген лимб. 
2) Пилить себе конечность. Прожать реген лимб.

regenerate_limbs – если у вас не хватило желле для регенерации ноги и ступни и вы восстановили ногу, то отрастить _только_ ступню, будет невозможно.

- [ ] Сделать regenerate_limbs восстановление не всех конечностей сразу, а выборочно.

Т.к. если у вас нет рук и ног, восстановив их сразу, у вас может не хватить желешки и вы обратно всосёте какие-то конечности.

Cannibalize_Body – поглощает только руки и ноги, игнорируя ступни и кисти, что приводит к тому, что после поглощения руки у вас отрывается кисть.

- [ ] Сделать, чтоб ступни и кисти тоже поглощались.

- [ ] Сделать отдельную кнопу, для поглощения конечности, которую выбираешь сам.

Выбирание конечностей, может привести к тому, что надеть наручники или связать такого игрока будет невозможно, но эй, просто оторвите ему ноги!

### Slimeperson

У нас в билде метроиды, а не слаймы, нормально ли оставлять такое название? 

После создания клона, оригинал получает непонятное замедление, фиксится регеном лимбов и то не с первого раза.

### Luminescent: Metroid activate minor and major 

**grey**
Minor – превращает в человека без спрайта. 
Major – превращает в человека без спрайта, должен давать выбор на превращения в другой подвид промитев.

**metal**
Major – спавнит железные слитки, вместо стальных листов – не адаптировали под наш билд?

**purple**
Minor – даёт нутриты и кровь. Кровь невозможно потерять её всегда 600. Предлагаю заменить кровь на metroidjelly

**yellow**
Minor – загорается, но сразу гаснет, нет кд, должна переключаться?

**red**
Minor – даёт inaprovaline при этом пишет: "You start feeling fast" Заменить на гиперзин или другой вид спидов?

**blue**
/obj/item/metroid_extract/blue/obj/item/metroid_extract/blue 
Major – всё ещё нужно сделать.

**green**
Major – спавнит серого метроида. Заменить на зелёного.

**black**
Major – не указать не могу. Нашему ролиплейному билду срочно требуется шадоулинги.

**adamantine**
Major – превращает в человека без спрайта. Должно в голема адамантитового.

**pyrite**
Minor – не работает.

**cerulean**
Minor – даёт inaprovaline, но имеет описание: ""You feel like you don't need to breathe!"" – Очень смешно, особенно если учесть что, у всех промитеев oxy_mod = 0
Тематика этого экстракта связана с атмосферой и воздухом, можно добавить, чтоб минор реакция заправляла балон, который ты держишь в руках?
Или как вариант отказаться от этой тематики в пользу чего-то другого.

### Stargazer 
/datum/component/mind_linker, network_name = "Slime Link" – Менять на Metroid Link/ Stargazer Link?

**Comment by Filatelele** [comment]
А БЛЯТЬ

**Comment by Zert0X** [comment]
> А БЛЯТЬ

Лох.

**Comment by BooJ1K** [comment]
> А БЛЯТЬ

Вы совершили непростительную ошибку, дон
