### ISSUE TITLE
Отдельная кнопка для холстера

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#1156]
Перенести дополнительную кнопку для холстера с Инфинити (возможно это Бейская фича).

Старое пользовательское описание:
> У меня не работают хоткеи/я ими не пользуюсь, кнопка для холстера удобнее для меня.
> 
> Многим понравится, эта кнопка не будет лишней. И да, на гейфинитях она уже есть.
> 
> Кнопку нарисовать делов на 5 минут.
>

**Comment by Epicus7** [comment]
Какая кнопка, где она должна быть? Скрин с Инфинити можно? Я вот там не играю и не видел..

**Comment by Epicus7** [comment]
И я правильно понимаю, что это решение проблему из #1136, но конкретно для холстера? Так то если у тебя прицеплен только холстер, то оружие можно доставать кликом по униформе.

**Comment by ArmolitskiyCarpoeb** [comment]
> Какая кнопка, где она должна быть? Скрин с Инфинити можно? Я вот там не играю и не видел..

Кнопка находится чуть выше смены режима движения (бег-ходьба). Размером с кнопку intent'a

**Comment by Epicus7** [comment]
Тогда тем более нужен скриншот.

**Comment by ArmolitskiyCarpoeb** [comment]
> И я правильно понимаю, что это решение проблемы из #1136, но конкретно для холстера? Так то если у тебя прицеплен только холстер, то оружие можно доставать кликом по униформе.

Да, но я отдельно написал. Если разгруз висит с холстером, то эта кнопка полезна будет.

**Comment by ArmolitskiyCarpoeb** [comment]
> Тогда тем более нужен скриншот.

![765](https://user-images.githubusercontent.com/59237874/71866851-74cf2300-3153-11ea-9906-800f83107860.png)

**Comment by Epicus7** [comment]
Порт с инфинити (или новых сборок Бея?).

**Comment by Epicus7** [comment]
Изменил описание иссуя.

**Comment by Voldirs** [comment]
Есть ещё вариант как это можно попытаться реализовать, на бэйцах есть пояса с кобурами, это обычный сторэдж, в который можно пихнуть один пистолет и всякие там магазины, и всё остальное, присущее обычному охранному поясу. При клике на любом интенте кроме хелпа достаётся пистолет, на хелпе открывается сторедж.
По сути тут тоже можно сделать похожую схему с атачами:
1)Вариант сложный. Сделать так чтобы при нацеплении двух атачей, их стореджи "складывались". С этим могут возникнуть проблемы потому что дропаучи не имеют ограниченные слоты, они имеют ограниченный объём, разгрузки - наоборот, поэтому "сложить" два разнотиповых атача, то есть дропаучи (по объёму) и кобуру (в которой один фиксированный слот) скорее всего не выйдет без особых танцев с бубном
2)Вариант попроще. Оставить всё как есть сейчас, но добавить возможность "переключать режим на кобуре", добавив два режима, а) всегда доставать пистолет из кобуры при грабе/дизарме/харме, б) всегда открывать сторедж, вне зависимости от интента (для тех кто пользуется хоткеями)
3)Ну иконочки на худе, в конце концов, как выше предложили

**Comment by MemoryDreams** [comment]
А зачем нам отдельная кнопка для кобуры, если она (кобура) в самом деле используется по клику на одежду? 
Давайте лучше попытаемся реализовать то что Волдирс предложил выше, интересней будет.

**Comment by ArmolitskiyCarpoeb** [comment]
> А зачем нам отдельная кнопка для кобуры, если она (кобура) в самом деле используется по клику на одежду?

Если разгруз и кобура уже на одежде, то использовать можно только одно

**Comment by Epicus7** [comment]
@Cinericius одобрил без комментариев, так что как я понимаю реализуем просто кнопочку как сейчас описано в ОП-посте.

Сложную схему Волдирса можно вынести в отдельный иссуй.

**Comment by Cinericius** [comment]
Кнопки есть для всего подряд собсно, не вижу проблемы сделать кнопку и для холстера, по крайней мере пока не разберёмся с веббинго-кобурной путаницей. Можно кстати и для веббинга кнопку запилить.

**Comment by No-Tips** [comment]
Ну короче забираю, ожидайте.

**Comment by TobyThorne** [comment]
Если делать - то через экшн буттонс, как сворачивание шлема на войдах и переключение фонариков. Перманентное присутствие на интерфейсе нахер не нужно - вдруг завтра кобуры удалим? :kek:

**Comment by Oubi256** [comment]
> Если делать - то через экшн буттонс, как сворачивание шлема на войдах и переключение фонариков. Перманентное присутствие на интерфейсе нахер не нужно - вдруг завтра кобуры удалим? :kek:

Ля, верните одобрено. Мой идеальный вариант, так это кобура на экшен буттонс, а инвентарь разгрузок по клику на одежду, ибо так реализован весь инвентарь (рюкзаки, куртки), это логично млять.

**Comment by Sudar0770** [comment]
Слот кобуры в одежде будет приемлемым вариантом? Мне тоже кажется, что применение либо разгрузки либо кобуры сломано.

**Comment by kreeperHLC** [comment]
Реализовано
