### ISSUE TITLE
Кошкодевочки и кошкомальчики, предлагаю вашему вниманию...

### ISSUE THREAD

**Issue by ChristianAnderssen** [ChaoticOnyx/OnyxBay#1159]
Есть у меня одна идея - ввести новую расу "Неко", те же самые хуманы, только с ушками и хвостом, как если нацепить котоушки на слот головы, только без них. Никакого отличия от людей, кроме визуального, либо добавить в речь Неко-людей автодополнение предложений словами "мяу" и "ня", типа "Я пойду на шаттл с дробовиком в руках, мяу!", "Тебе свернуть шею, ня?". Изначально планировал как мутацию в генетике, но так как генетика отсутствует, предлагаю ввести эту расу как мутацию в результате облучения во время радшторма. То есть, из лобби эту расу выбрать изначально нельзя, чтобы лохи не абузили, чтобы эта раса была редкой, чисто наградой за выживание во время радшторма. Этакий эксклюзив. Как вам идея? 

### Улучшение
В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.

   Моя идея сос мыслом. Эстетическим смыслом. Я подумал, что было бы неплохо добавить такую расу, так ее наличие не идет в разрез с лором и не портит атмосферу станции, а тот, кто видит в этом какой-то мем или еще что-то - просто поехавший шизик. Не знаю, что еще сказать.

### Решение
Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы.

   У меня нет никаких проблем. Я просто предлагаю свою идею народным умельцам, которые могут вдруг захотеть заняться этим на чистом энтузиазме, 

### (Опционально) Альтернативы
Опишите альтернативы, о которых вы думали. Почему именно ваше решение является лучшим?

   Я не считаю свою идею лучшей, но Далек предлагал портировать котодевочек с ТГ. Я, честно, не знаю, в чем разница между нашими идеями.

### (Опционально) Дополнительная информация
Добавьте любую дополнительную информацию о вашей идее. Если у вас есть какие-то ресурсы - примеры внутриигрового текста, спрайты, картинки, звуки - обязательно прикрепите. Тогда шансов, что вашу идею реализуют, будет гораздо больше.

   Тут могу лишь попросить вас отнестись к идее серьезно, потому, что, блядь, я аж залез на гитхаб, чтобы это запостить. Какие ресурсы нужны? Спрайты с котоушек можно перенести, звуки вроде тоже где-то должны быть. 
[Neko.zip](https://github.com/ChaoticOnyx/OnyxBay/files/4030002/Neko.zip)

Могу еще картинку скинуть с кошкодевочками, хули.

![image](https://user-images.githubusercontent.com/24549043/71886764-cf658080-314d-11ea-88cc-29f259cf033d.png)

**Comment by Epicus7** [comment]
Сегодня кошкодевочек, а завтра ЕРП вам разрешить?

**Comment by Voldirs** [comment]
![ъ1](https://user-images.githubusercontent.com/4889771/71887186-a4c7f780-314e-11ea-80e0-1043df6e1119.gif)

**Comment by ChristianAnderssen** [comment]
ЕРП - это плохо. Кошкодевочки - хорошо.

**Comment by Iotwo** [comment]
https://wiki.ss13.ru/index.php?title=%D0%A2%D0%B0%D1%8F%D1%80%D0%B0%D0%BD

Недостаточно?

**Comment by ChristianAnderssen** [comment]
> https://wiki.ss13.ru/index.php?title=%D0%A2%D0%B0%D1%8F%D1%80%D0%B0%D0%BD
> Недостаточно?

Да ты охуел ссаных ксеносов путать с кошколюдьми. Сам играй за это отродье, еще ящеров и медуз с собой захватить не забудь.

**Comment by Traysoul** [comment]
Легальные цели для грифона

**Comment by ArmolitskiyCarpoeb** [comment]
если эту хуйню потом можно убивать и в бан не попадать, то я за
