### ISSUE TITLE
Лестницы убиты вражеским агентом

### ISSUE THREAD

**Issue by TobyThorne** [ChaoticOnyx/OnyxBay#11833]
тл др ревертните нахуй https://github.com/ChaoticOnyx/OnyxBay/pull/11482 а то я инсульт выхватил

позиция 0:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/1eb4764d-0f7c-4b89-9071-f492884d7506)
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/767888f9-64bd-449a-9bc8-4800ec725eb6)

позиция 1:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/1492a0f3-5012-4d7b-9e2f-2c59dfb06c73)
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/e8582079-e8c6-41e2-9eb4-b1858f175dac)

позиция 2:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/0e54431c-cfad-482c-8ff4-3e4c5f8b3918)
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/957b2f03-476f-4bb5-8b08-ed580e64ea42)

позиция 3:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/526e0724-614c-40da-9e2c-136864f58efa)

дальше - смешнее
если чел А будет стоять здесь
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/f6613903-0b40-46c8-bde7-c39b6d7599e3)
а чел Б - здесь 
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/7806401a-a022-4bc5-a2bc-598ee4104bf1)
и чел Б в этот момент поднимется - челы А и Б свапаются местами появляется смешное сообщение:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/9f3aa614-0699-4f4f-89b6-019f0fc43c9e)
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/1fc12265-98f3-486b-ab61-469554d98add)

**Comment by Filatelele** [comment]
Лестницы были спасены.
