### ISSUE TITLE
Добавить способ получить Voice Analyser

### ISSUE THREAD

**Issue by koronoshka** [ChaoticOnyx/OnyxBay#1189]
Добавить Voice Analyser в хакнутый вендомат и автолат.

Старое описание:
> ### Улучшение
> Поговорив с одним уважаемым человеком, я узнал что несмотря на то что у нас в билде есть Voice Analyser, его честным путем не достать. В итоге бедные ассистенты не могут сделать двери с кодовым словом и бомбы, подрывающиеся от n-слова.
> 
> ### Решение
> В других билдах этот предмет достается в хакнутом вендомате, что находится в складе инструментов ассистентов. Поместите туда.
> 
> ### (Опционально) Альтернативы
> Предмет можно поместить в автолат
> 
> ### (Опционально) Дополнительная информация
> Возможно, в билде так же есть Health sensor. Активирует сигналлер от состояния здоровья. Если такой есть, то поместите его вместе с анализатором голоса.
>

**Comment by Cinericius** [comment]
А в РнД нет? Раньше был.

**Comment by Voldirs** [comment]
В рнд есть интегралки, там тоже есть анализатор голоса, но ещё есть обычный анализатор голоса, не интегральный, его бы в автолат и добавить, в коде он уже есть.

**Comment by koronoshka** [comment]
Волдирс сообщил что нет на данный момент способов получения. Да и лучше ему быть со всеми остальными предметами для сигналлеров, в вендомате.

**Comment by Cinericius** [comment]
>в коде он уже есть.
>нет на данный момент способов получения.

Вас понял

**Comment by Epicus7** [comment]
@Cinericius, куда пихать то? Ты бы решил

**Comment by Cinericius** [comment]
Да можно и туда, и туда.

**Comment by Epicus7** [comment]
Обновил описание.
