### ISSUE TITLE
Создать какнить-лат и принтер плат для инженеров 

### ISSUE THREAD

**Issue by LagannPM** [ChaoticOnyx/OnyxBay#119]
- Сделать что-то типо протолата для инженеров и поставить в их отделе и еще один в научном.
- Будет печатать строительные компоненты и расходуемые предметы которые доступны через рнд.
Проблема в том что зачастую нужны детали для чего либо и отвлекать ученого он изучения это очень тупо, так как зачастую тебе нужно много деталей и ты можешь прийти не один раз.
Это нихуя не взаимодействие и ты только злишь ученого который из за тебя должен останавливать свой процесс.
Ты идешь к ученому все равно за нерасходуемыми предметами типо инструментов, девайсами, модулями для рига и тд.
Тоже самое с принтером плат.
Для того чтобы уметь печатать платы или детали не нужно быть ученым

**Comment by Ruforce** [comment]
Уберите доступ у протолата и все будет чики-пуки.

Одна переменная же.

**Comment by hekko4** [comment]
Дать доступ инжам к полному протолату? Не смешно

**Comment by Cinericius** [comment]
На каком-то билде были урезанные протолаты с конкретными доступными технологиями, раскиданные по отделам. Надо было просто синхронизировать их с базой и можно было пользоваться. Точно помню, что в бриге там был протолат, печатающий оружку всякую.

**Comment by Epicus7** [comment]
Очень плохая идея. Между отделами должно быть как можно больше взаимодействия, а вы превращаете игру в дроч механики.

Ученые, которые дрочат науку ради науки, пусть идут учить философию и какую-нибудь топологию, а не играть с приличными людьми в компьютерную онлайн игру.

**Comment by Cinericius** [comment]
Заметьте, не я это сказал...

**Comment by LagannPM** [comment]
Это не взаимодействие, это тупо проблема.
Протолат один на всю станцию, и использовать его для производства деталей для строительства тоже тупо.
В нем как задумано делаются прототипы вот пускай и делаются всякие инструменты,девайсы и тд.
На станции вообще нету способа достать капаситоры/манипуляторы и тд кроме как 5 штук в автомате у инженеров на столе парочка.

**Comment by Epicus7** [comment]
Голиаф же сделал возможность производить эти штуки стаками

**Comment by LagannPM** [comment]
С взаимодействия не убудет а ученые не будут гореть по этому поводу. И инженерам добавиться геймплея.

**Comment by Epicus7** [comment]
Цапаситоры и манипуляторы инженерам нужны не так часто. А платы тем более пусть у ученых берут. Короче плохая идея.

Пусть учатся в общение.

**Comment by LagannPM** [comment]
давай тогда поставим второй протолат в сторонке у РНД. Тоже решение проблемы и ты доволнен

**Comment by YaridaTheDragon** [comment]
Херовая идея. Протолат должен быть лишь один. Пускай инженеры поднимают свои жопы и идут в РнД.

**Comment by Cinericius** [comment]
Тоже не нужно
