### ISSUE TITLE
Сделать так, чтобы ПДА с карточкой работало не только на груди

### ISSUE THREAD

**Issue by MemoryDreams** [ChaoticOnyx/OnyxBay#1198]
### Улучшение
В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.

В чем вообще прикол носить пда на груди? Я понимаю, что они, вроде, маленькие, но вы пробовали класть телефон в грудной карман рубашки? Очень неприятный опыт. Но станция не оставляет других способов носить пда с карточкой, ибо СБшные худы вдруг перестают опознавать карточку где-либо кроме груди. 
Я предлагаю дать возможность носить пда с карточкой на поясе. С этим может возникнуть проблема, что если игрок будет иметь одну карту на груди, вторую на поясе. Если такое происходит, можно показывать на худах либо ошибку, либо обе должности сразу. Как вариант, можно сделать так, чтобы если худ зарегистрировал карту на груди, он не пойдёт проверять наличие карты в слоте на поясе.
Я считаю, что это сильно расширит возможности для персонализации персонажей.

**Comment by MrMagick2104** [comment]
А в чём проблема носить КПК отдельно от карты?

**Comment by MemoryDreams** [comment]
А я не хочу носить КПК отдельно от карты, это неприятно. Хочу носить карту в КПК.

**Comment by MemoryDreams** [comment]
А я не хочу носить КПК отдельно от карты, это неприятно. Хочу носить карту в КПК.

**Comment by Fritcher36** [comment]
> 
> 
> А я не хочу носить КПК отдельно от карты, это неприятно. Хочу носить карту в КПК.

зря-зря. Ну да ладно, напомню, что id слот - это специальный кармашек, а не как в современных рубашках, так что как айди, так и кпк там вполне себе удобно лежит. Но сама фича хорошая, я за.

**Comment by MemoryDreams** [comment]
Тут проблема не в том, как он лежит, а в том, что он неудобно одежду вниз тянет.

**Comment by MemoryDreams** [comment]
А оно одобрено или отклонено? Уже почти три недели прошло.

**Comment by MrMagick2104** [comment]
Если бы отклонили, то закрыли бы. Если бы одобрили, то дали бы плашку.
Некоторые иссуи могут лежать открытыми тысячелетиями. Когда-нибудь его решат. Когда-нибудь.

**Comment by Cinericius** [comment]
Решено. Закрыто.

**Comment by MemoryDreams** [comment]
А почему закрыто?
