### ISSUE TITLE
Портировать этого моба с торча

### ISSUE THREAD

**Issue by LagannPM** [ChaoticOnyx/OnyxBay#120]
![default](https://user-images.githubusercontent.com/6437377/44721389-f6408b00-aaf3-11e8-9247-7e82e07175c7.png)
Описание:
Adds Sarashen (Now Vagrants), for use on away missions to provide a more active threat to the away team. Currently used on the bearcat, and can randomly be used on the derelict.

Sarashen are fragile, but are able to cloak when not in combat, making them difficult to see, especially in the dark. When they spot an enemy, they move to them and attack, pinning the target down and starting to suck their blood. While attacking, they decloak and glow brightly, so the victim can be more easily helped. Once they've sucked enough blood, they will split in two. Sarashen have a random chance of carrying an infection, which is passed onto their victims. Once there's nobody left to attack, they cloak again.

Вкратце:
Почти невидыми пока не атакуют, сосут кровь из жертвы, могут передать вирус и делятся на 2 когда накушаются

**Comment by Cinericius** [comment]
Эти модифицированные метроиды у нас есть, я их спавнил на ЦеКа.

**Comment by LagannPM** [comment]
у них нету вроде такого механа, они просто бьют тебя

**Comment by ZerlGray** [comment]
Не, именно так работают вообще.

**Comment by Cinericius** [comment]
Короче раз они уже есть и работают как надо, я закрою иссуй.
