### ISSUE TITLE
Спиздить спрайты со стульями с Тау или торча

### ISSUE THREAD

**Issue by LagannPM** [ChaoticOnyx/OnyxBay#122]
Примеры с торча
![](https://user-images.githubusercontent.com/17550641/42545749-c62dac94-84b1-11e8-9e2f-de7f84a1a30b.png)

![](https://user-images.githubusercontent.com/17550641/42545787-f50fbc96-84b1-11e8-8c38-f441e5078f36.png)

![](https://user-images.githubusercontent.com/17550641/42545779-eb66ddd2-84b1-11e8-9329-f8cb99356fff.png)

![](https://user-images.githubusercontent.com/17550641/42545824-17cdec8a-84b2-11e8-8e64-51d6daa48800.png)

![](https://user-images.githubusercontent.com/17550641/42545861-3cf452a6-84b2-11e8-8a54-65f083495695.png)

**Comment by Cinericius** [comment]
Ну хз, у нас персонажи все четко сбоку прорисованы, а эти стулья в 3/4.

**Comment by LagannPM** [comment]
давайте стены сделаем тогда тоже сбоку ? и все вещи
и вообще превратив ССку в платформер
ССка ближе всего по дизайну к 3/4 и я не знаю почему вы так коллективного этого боитесь

**Comment by Cinericius** [comment]
Потому что ССка - это рогалик.

**Comment by Cinericius** [comment]
https://waltorious.files.wordpress.com/2015/08/crawl-tiles-2014-06-09-20-21-48-18.png

**Comment by Cinericius** [comment]
Клозаю
