### ISSUE TITLE
Переработать синтов, добавив им каких-нибудь витальных органов

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1220]
### Улучшение
Название говорит само за себя, синтам нужны какие-то органы для того, чтобы они не могли, допустим, танковать тыщщи урона в торс и нижнюю часть тела без каких-либо серьёзных повреждений, попутно накидывая им дополнительные фичи и возможности, которых нет сейчас.

### Зачем?
Потому что синты из говна и палок (в данном случае - из глаз и батарейки) выглядят как-то слишком упрощённо и дизбалансно. 

### Решение
Натыкать синтам всяких органов, чтобы жизнь маслом не казалась, которые раскиданы по различным частям тела, а ля:
**Гироскоп:** без него синтетик не может нормально стоять, при повреждении его шатает, словно бы он пьяный.
**ЦП:** аналог мозга у человека, которого у синтов нет. При поломке синтетик падает в крит до ремонта.
**Трансформатор** или как это назвать(?): идея в том, что при неисправности синтетик получает потребление тока раз в десять больше.
**Биогенератор:** получаем из этанола и прочих органических веществ немного энергии: 
За юнит от одного до пяти. При этом, переход не моментальный, вещества как бы усваиваются. У генератора есть вместимость.
**Хладагент:** жидкость, которая выступает "кровью" синта, отвечает за охлаждение. Без неё синтетик греется. При "кровотечении" синт может потерять много хладагента и соснуть. Восстанавливает специальными пакетами крови.
**Компрессор:** сердце синтетика, качает хладагент.
**Радиаторы** + активное охлаждение: лёгкие синтетика, отвечают за отвод температуры в окружающую среду.
Ну и всё в таком духе, вы поняли.
Бонусом можно добавлять вариации этих органов с какими-то преимуществами или недостатками, возможность разгона, но с получением дамага на органы из-за него, а соответственно какие-нибудь мини-игры, вроде перетаскивания ползунков для регуляции напряжения и скорости охлаждения.
Естественно, надо как-то бафнуть нанопасту, так как в текущем состоянии она - бесполезный кусок кода. Любые органы можно починить отвёрткой, а повреждения конечностей проще отремонтировать сваркой/проводами, так как для применения нанопасты нужно в любом случае вскрывать конечность. Предлагаю сделать её веществом, которое как бикаридин/дермалин будет медленно восстанавливать хп органов и конечностей на всём участке, применять можно без вскрытия, просто намазывая пасту, как мазик в салат.

**Comment by Epicus7** [comment]
Гироскоп, ЦП, Трансформатор, Биогенератор, Компрессор, Радиаторы - нужны спрайты.

Вообще довольно сложная механика, это не будет выглядеть вычурно на фоне киборгов? В киборгах довольно простой механ, а в синтах, которые почти тоже самое, будет такое разнообразие.

**Comment by Cinericius** [comment]
ЦП в сундук

**Comment by Cinericius** [comment]
Можно еще пойти рудиментарным путем и накатить им киберорганы, которые уже есть. Там все те же печени и почки, только кибер.

**Comment by ularesen** [comment]
В чем проблема добавить синтам киборговских модулей, исключая пластины и бинарного ключа. Дамаг сначала будет по телу, а потом по батарее. Можно им добавить как у мехов, при получении домага они будут дезориентироваться

**Comment by Cinericius** [comment]
В общем вешаю сразу "нужны идеи" и одобрено. Можно пилить как в посте или в комментариях, можно что-то свое придумать.

**Comment by Epicus7** [comment]
@Cinericius, классно ты придумал. Мы сейчас награду повесим, причем по сложности довольно большую, видимо. Кто-то запилит и как нам принимать/не принимать это? И соответственно платить/не платить?

**Comment by MACTEP-ABATAP** [comment]
:kek:  вы поверили в награду?
А так очень крутая фича была бы, жаль не реализована сейчас.
