### ISSUE TITLE
Железки не нужны 

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#1228]
Предлагается выпилить ФБП, а так же протезы головы и сундука из настроек персонажа, роботехники, РнД, короче из доступа игроков.

В билде можно оставить на случай ивентов или запила режима про киберлюдей. UPGRADING IS COMPULSORY.

**Comment by Cinericius** [comment]
Ура срач

**Comment by TapKo4eB** [comment]
чё?
Ты хочешь сказать что надо тупо всех синтетов?

**Comment by Cinericius** [comment]
DA

Только боргов и протезы рук-ног оставить, как в старые добрые.

**Comment by TapKo4eB** [comment]
безризонно, инвалидно, вставьте слово сюда, я против
выпилить - полная хуйня
занёрфать - хуйня но уже не такая
запилить им определённые органы там со слабостями и т.д - заебись

**Comment by Srankl1n** [comment]
выпилить фбп

им просто срать на станы, будь то дубинка, тазер или что-либо. раньше станило из-за боли, но щас оно станит из-за спазма мускул, которые после последних обнов пропали у фбп (а так как боли нету, то их даже вогнать в пейнкрит нельзя, только убивать)

концептуально - говно. представьте себе - вы вставляете мозг человека в тело, которое он ВООБЩЕ НЕ ЧУВСТВУЕТ (а ведь это не вей-медовские протезы, которые по лору имеют чувства), при этом он бегает как человек, жрет тонны патрон и живет бесконечность, пока ему не оторвут батарейку или не взорвут бошку. 

его можно ревайвнуть после отрыва головы, просто приклеив другую голову

нет, серьёзно, это еще одни борги, только эти еще могут брать руки в предметы и не имеют законы.

ну и важный плюс, как по мне, игроки еще сильнее будут боятся за свою жизнь, потому-что им не дадут тело, которое лучше биологического во всем, лол.

**Comment by ularesen** [comment]
Можно сделать что:
Дезориентация при получении некоторого урона, как в мехе
Взрыв батарейки при критическом дамаге
Со взрывом можно запилить любую конечность, аналог гиба, что-ли

**Comment by Iotwo** [comment]
В некоторых старых билдах попадание станлуча\сферы, разрада тока либо облучение откуда угодно с высокой вероятностью приводили к тому, что протез если не взрывался, унося с собой ещё какие-нибудь части тела, то очень надолго переставал функционировать: либо до нормального ремонта от профессионалов, либо до замены. 
И совсем необязательно нужно было попасть именно в протез. В связи с чем любители I never asked for this гораздо реже пытались играть в боевичок, так как знали, что даже мимобипски имеет шансы сделать из них героев посмертно.

**Comment by Cinericius** [comment]
Было такое, помню Дустин сбегал из брига, стоя у окна и трогая горячую лампочку протезом до победы.
Можно вернуть, в принципе-то.

**Comment by Epicus7** [comment]
Любой выпил фичи находит любителей этой фичи, которые огорчаются не получив ничего взамен.

Можно реально по-тихонечку это перепиливать в киберлюдей, но прям выпилить - это будет слишком резко.

Можно запилить режим с киберлюдьми, переделать их немного и залить сразу с выпилом ФБП в виде обычной расы - так будет правильнее и понятнее для игроков.

**Comment by Cinericius** [comment]
Прост проблема ФБП в том, что их или надо реворкать в что-то человекообразное с органами и прочей требухой, чтобы соблюсти баланс, или оставлять как есть, чтобы у них оставалась изюминка. Или придумать им новую изюминку.

**Comment by HonkyDonky** [comment]
Возможное > [решение](https://github.com/Baystation12/Baystation12/pull/26724) <

**Comment by Cinericius** [comment]
В целом неплохо, но там еще какая-то параша типа выпила веймедов.

**Comment by MACTEP-ABATAP** [comment]
Опять про нёрф синтов?
Серьёзно?
Просто сделайте полную переработку им, серьёзно.
