### ISSUE TITLE
Переделать ползанье как обычное движение чтобы не приходилось тыкать

### ISSUE THREAD

**Issue by LagannPM** [ChaoticOnyx/OnyxBay#123]

**Comment by ZerlGray** [comment]
Было бы не плохо описание...

**Comment by Cinericius** [comment]
Можно, а заодно убрать автоматический дроп предметов при падении.

**Comment by LagannPM** [comment]
Описание не требуется и так понятно.
А дроп бы я оставил а вот возможность подобрать предмет пока лежишь сделал

**Comment by Ruforce** [comment]
Как-то я кодил кравл на блюбей.

Это была плохая идея.

**Comment by Cinericius** [comment]
Вообще да, оставить дроп при самом падении, но дать возможность лежачим брать и использовать вещи, причем только с пола (либо наоборот, только со стола, если лежишь на столе).

**Comment by Epicus7** [comment]
Не лезьте - убьет.

SS13 не рассчитана на то, чтобы лежащие могли брать предметы. Там очень много подводных камней.

А ползать - чисто физически сложно. Механические трудности тут логичны, я бы оставил как есть.

**Comment by Cinericius** [comment]
Но... как же... Луф... Интербей...

**Comment by ZerlGray** [comment]
Даже на блюбее люди не роняют вещи при падении.

**Comment by LagannPM** [comment]
@Epicus7 Не все даже знают что можно ползать

**Comment by Epicus7** [comment]
Ну и слава богу!

**Comment by LagannPM** [comment]
а надо знать, это ведь жизнь спасти может

**Comment by YaridaTheDragon** [comment]
Ползать физически сложно [2]. Не стоит лезть сюда.

**Comment by Cinericius** [comment]
Не нужно
