### ISSUE TITLE
Рандомивенты

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#124]
На билде все плохо с рандомивентами.
Нет ролей -> нет движухи. Так быть не должно. Логично будет создать множество рандомивентов новых:
1) Прорывы рандомных труб с газом.
2) Поломка проводки (чтобы перегрузка которая иногда случается - сжигала часть проводки).
3) Добавить проебанные аномалии, вроде телепортов, смещения объектов в комнатах etc.
4) Случайные взрывы взрывоопасных приборов. Например случайно взрывающиеся фуелтанки.
5) Случайная поломка системы контроля температуры, из за чего температура в комнате опускается СЛИШКОМ СИЛЬНО. Или поднимается. (Поломка термостатов)
6) Проебы в СМЕСАХ, из за чего большая часть энергии поставляемая в отдел сжирается холодным вакуумом\превращается в тепло.
7) Проебы в шлюзах, которые будут изредка открывать шлюзы в свежесть вакуума.
etc.

**Comment by LagannPM** [comment]
нужно больше ивентов !
Пишите свои предложения сюда еще
Насчет взрывопасной аппаратуры я не согласен, что то не может взрываться просто так.

**Comment by ZerlGray** [comment]
Что то может взрываться, если это "что то" плохо сделали. Никто не обещал качественное оборудование!

**Comment by Cinericius** [comment]
#27

**Comment by Cinericius** [comment]
Инженерные поломки - это хорошо, но хотелось бы еще чот.

**Comment by ZerlGray** [comment]
1) Улучшить код генерации рандомвирусов (там щас у него проблемы большие), добавить аномалии.
Весовые коэффициенты перед шансом генерации сделать адекватными.
2) Чтобы совсем смешное было - добавить оружию шанс оказаться НЕИСПРАВНЫМ. Вот заходишь в оружейку, берешь ствол - идешь воеват. А он неисправен.
3) Добавить смешную фичу с возможность спавна с расширенным\зауженным доступом (типа ошибка отдела кадров ЦК) случайным образом.
4) Поломка обычных ID карт. Типа ID карта опять же херового качества.

**Comment by ZerlGray** [comment]
Ну и чтобы совсем смешно:
Добавить шанс того, что после старта раунда какой то отдел окажется без оборудования. Тупо без вещей. Инженерка без суперматерии, пустая оружейка, РнД с нихера etc.

**Comment by Ruforce** [comment]
>Поломка обычных ID карт. Типа ID карта опять же херового качества.

ХОП К ХОПСКОЙ

**Comment by hekko4** [comment]
Идеи классные конечно и всё такое, но это дубликат #27 
Так что все туда
