### ISSUE TITLE
Мобы на астероиде не двигаются

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#125]
Просто стоят на месте.

**Comment by LagannPM** [comment]
уверен ? мб они не атакуют ?

**Comment by ZerlGray** [comment]
На астероиде они просто стоят на месте.

**Comment by ZerlGray** [comment]
Как говорится, оптимизировали.

**Comment by LagannPM** [comment]
это уже на сервере ?

**Comment by ZerlGray** [comment]
Да. Ну я щас в гостах летаю - а они стоят на месте.

**Comment by LagannPM** [comment]
я сейчас на локалке проверил они двигаются, это скорей всего потому что ты гост

**Comment by ZerlGray** [comment]
Вряд ли то, что я гост, должно влиять на движение мобов на сервере.
А ты какую версию тестил? Эпикус же недавно слегка оптимизировал мобов, чтобы они не вызывали лаги.

**Comment by LagannPM** [comment]
вместе с оптимизацией

**Comment by LagannPM** [comment]
нахуя им жрать процессор движениями на жалкого госта типо тебя ?
я думаю это так и задумано если рядом нету живых

**Comment by ZerlGray** [comment]
Не. Щас все гораздо смешнее: Они рандомно двигаются, если хоть раз увидели живого. Даже если после этого он ушел из поля зрения - они продолжают работать и случайно передвигаться. А вот если ни разу не видели человека - стоят на месте.

**Comment by Epicus7** [comment]
Это нормально. Все обычные мобы неактивны, когда их никто не видит. Когда видит цель - начинает преследовать, а потом искать ее.

Если просто разрешить им хаотично ходить, то реально будет слишком большая нагрузка на сервер.
