### ISSUE TITLE
Сертификаты клоуна

### ISSUE THREAD

**Issue by Fritcher36** [ChaoticOnyx/OnyxBay#1250]
За особо стыдную хуйню вроде эмоутов про говно, ерп или мемных приколов, заходов за Симбу Двухлимиточного педаль может повесить на юзверя сертификат клоуна. Каждый сертификат даёт накопительный шанс 10% заспавниться в раунде клоуном вне зависимости от выбранной роли и деклара клоунов, при достижении шанса в 100% человек получает бан на месяц/три/перму(Это уже к геймдизайну), сертификаты снимаются. Можно еще сделать снятие сертификатов по одному за календарную неделю/месяц, либо за донат(Надо ж чем-то за хост платить).

**Comment by ArmolitskiyCarpoeb** [comment]
я не хочу в бан сукаааа

**Comment by LLIkolnik** [comment]
Закрывайте нахуй.

**Comment by Fritcher36** [comment]
Напомню товарищам, что клован изначально создавался как роль-наказание для особо стыдных клоунов, которых вроде бы бан не исправит, а вроде бы наказать надо. А тут и дурачок официально дурачок ингейм, и серверу смешно. Возвращаем всё на круги своя.

**Comment by ArmolitskiyCarpoeb** [comment]
> Напомню товарищам, что клован изначально создавался как роль-наказание для особо стыдных клоунов, которых вроде бы бан не исправит, а вроде бы наказать надо. А тут и дурачок официально дурачок ингейм, и серверу смешно. Возвращаем всё на круги своя.

додик

**Comment by Fritcher36** [comment]
> 
> 
> > Напомню товарищам, что клован изначально создавался как роль-наказание для особо стыдных клоунов, которых вроде бы бан не исправит, а вроде бы наказать надо. А тут и дурачок официально дурачок ингейм, и серверу смешно. Возвращаем всё на круги своя.
> 
> додик

На гит по поводу кода или геймдиза пишут, срать сообщениями из одного оскорбления иди в дискорд.

**Comment by ZerlGray** [comment]
Но ведь возвращали клоунов не как наказание а как мемную дань старой сске.
Да и у них возможностей больше чем у ассистентов. Какое тут наказание?
Олсо, бог дал баны на профы. Забань все кроме клоунов.

**Comment by ZerlGray** [comment]
Как альтернатива - впилить неснимаемую одежду клоуна которая будет спавниться вместе с мутацией "кламси" на наказанном.

**Comment by Epicus7** [comment]
Сомнительная фича, непонятно чем она принципиально отличается по способу использования от Варнов.

Педали будут тупо выдавать 10 сертификатов сразу, либо не выдавать ничего. В итоге получаем тупо джобку на все профы, кроме клоуна.

**Comment by MACTEP-ABATAP** [comment]
Сделать возможность выдавать сертификат клоуна, через vote.
