### ISSUE TITLE
Боевые стулья

### ISSUE THREAD

**Issue by Fritcher36** [ChaoticOnyx/OnyxBay#1251]
### Описание бага
В текущий момент есть смешная возможность пристегивать людей к стульям в бою. 

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Жертва стоит на тайле с кроватью/стулом
2. Перетягиваем её на стул
3. Жертва пристегнута
4. Пиздим

### Ожидаемое поведение
Возможность быстро пристегнуть товарища к стулу, например, во время разгермы - это, конечно, хорошо, но в боёвке это смешной абуз. Я бы предложил убрать посадку перетаскиванием в принципе, оставив её только для себя. Других персонажей можно спокойно посадить с задержкой в секунду, взяв их в граб и кликнув по стулу грабом. Как вариант, можно оставить пристежку, если пристегиваемый лежит. Но стоячего человека мгновенно сажать на стул и пристегивать - это мем.

### Геймдизокоммент:
>Я всесторонне рассмотрел проблему (нет) и пришел к выводу, что надо просто уменьшить радиус до того же тайла.

**Comment by Voldirs** [comment]
А где баг то? И нахуя ты приоритет повесил? Эта хуйня роняет сервер или твой пердак? Мне кажется второе.

**Comment by Fritcher36** [comment]
> 
> 
> А где баг то? И нахуя ты приоритет повесил? Эта хуйня роняет сервер или твой пердак? Мне кажется второе.

Это не тот приоритет, который роняет сервер, у нас их два, этот просто повышенный. И да, это приоритетно, потому что что в суде, что в чатиках всплывает предельно регулярно. Почему это баг? Потому что логически это не должно так работать, в билде есть пристегивание через граб, которое занимает время, а это - рудимент.

**Comment by Voldirs** [comment]
На это много народу жаловалось? Я как-то вообще не видел.

**Comment by TermService** [comment]
Это ишшуй из разряда я соснул@пойду занерфаю

**Comment by Voldirs** [comment]
Странно что за хуево количество времени это стало проблемой только для тебя одного, не находишь?

**Comment by koronoshka** [comment]
Есть ли действительно причина оставлять это так как есть, кроме "так всегда было?"

**Comment by LLIkolnik** [comment]
> Есть ли действительно причина оставлять это так как есть, кроме "так всегда было?"

Да, есть. Во-первых, это удобно. Во-вторых, это имеет под собой подоплёку.
То, что дебилов сажают на стулья и из-за этого они хуй сосут - проблема от части Тоби, который сделал складывание стульев без дилэя, и от части билда, который при укладывании на кушетку выкидывает вещи куколки из рук.

**Comment by danxnader** [comment]
Ещё смешнее после этого стул убирать, и наслаждаться 15ти секундным станом

**Comment by Cinericius** [comment]
Я всесторонне рассмотрел проблему (нет) и пришел к выводу, что надо просто уменьшить радиус до того же тайла.

**Comment by Cinericius** [comment]
ОП чому-то не редачится.

**Comment by Cinericius** [comment]
А, это у меня браузеропроблемы на калькуляторе.

**Comment by Cinericius** [comment]
Обновил ОП

**Comment by ZerlGray** [comment]
> Это ишшуй из разряда я соснул@пойду занерфаю

разве у вас так не половина разработочки делается? о_О

**Comment by sweden-moose** [comment]
Выполнено в #3729
