### ISSUE TITLE
Выпилить нахуй один из дереликтов

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#1277]
### Улучшение
На одном из дереликтов, Лар-Мария вроде, охуеть как много трупов и мобов. Смысла большого в этой локации нет, но подозреваю что оно давит на сервер охуеть как.
### Решение
Выпилить нахоооой

### (Опционально) Альтернативы
Убрать из загрузки

### (Опционально) Дополнительная информация
Жопа гори-ит

### Виза геймдиза:
Дереликт оставить, мобов и особенно трупы хуманов убрать. Возможно, кинуть пару сильных нечеловеческих мобов для интересности.

**Comment by MrMagick2104** [comment]
> Лар-Мария вроде охуеть как много трупов и мобов. Смысла большого в этой локации нет, но подозреваю что оно давит на сервер охуеть как.

Там же все мобы и трупы - простые мобы, а не хуманы всякие, не должно сильно сервер нагружать.

**Comment by Voldirs** [comment]
Мобы грузят. А трупы там хуманы, ага

**Comment by MrMagick2104** [comment]
Ну, тут на практике смотреть надо. По моим личным ощущениям, на бегиннере сервер и без тюряжки загружается так, что она сильно не влияет, а на основном это как-то незаметно из-за трупующего онлайна 24/7

**Comment by Voldirs** [comment]
Хрен знает, опух очень сильно ломаться начал, мне кажется из-за дереликтов

**Comment by Cinericius** [comment]
Остпвил визу в ОПе

**Comment by MrMagick2104** [comment]
Дереликт без мобов какой-то скучный выйдет, имхо. Тупо коробка со средненьким лутом, внимания не стоит. Я бы предложил закинуть туда пару сильных ебак, типа короля козлов, но что-нибудь тематичное, для эдакого босс-баттла, да чтобы сервер не сильно загружать.

**Comment by Cinericius** [comment]
Хорошая идея

**Comment by Voldirs** [comment]
А ты этот дереликт смотрел?
Он тупо НЕИНТЕРЕСНЫЙ

**Comment by MrMagick2104** [comment]
Я думаю, смысл был в том, что когда ты залутался на всяких казино и биркэтах, можно было бы просто повторить х/ф "Рейд" с мясом, кровью, а также кучей болванчиков.

**Comment by Voldirs** [comment]
Алсо пока кто-то не сделает вот это вот, то есть не ткнётся в мапу, народ будет СТРАДАТЬ, надо убрать хоть временно эту мапу

**Comment by MrMagick2104** [comment]
А ещё можно сделать какое-нибудь гениально-костыльное решение, вроде того, что пока нет живых людей на нём, то мобконтроллер, процессор атмоса и прочая хрень отключена на обоих з-уровнях.

**Comment by Voldirs** [comment]
Ну в теории звучит неплохо

**Comment by MrMagick2104** [comment]
В теории-то да, так вообще часто во многих играх поступают, но я не уверен, что это в нашем случае вообще реализуемо.
А если "временно" удалять карту, отложив её до каких-нибудь фиксов, то увидят её снова только археологи из будущего в древних архивах гитхаба иссуев с пометкой "отложено".

**Comment by Fritcher36** [comment]
> 
> 
> А ещё можно сделать какое-нибудь гениально-костыльное решение, вроде того, что пока нет живых людей на нём, то мобконтроллер, процессор атмоса и прочая хрень отключена на обоих з-уровнях.

И оно точно так же будет повидлить сервер, но не сразу, а когда туда прилетит кто-нибудь. Тут сама идея так себе, да и карта не лучше. В ведро.

**Comment by Epicus7** [comment]
То что лагает билд - это баг. То что лагает из-за карты - неверная догадка. Лагает не из-за карты, а из-за гунчата.

Короче предпосылка неверная, "улучшение" не обосновано.

@Cinericius, вопросы оптимизации, лагов и прочих фиксов ревьювить тебе смысла нет.

Если ты хочешь выпилить карту потому что она унылая - это одно. Если ты хочешь ее выпилить потому что она лагает - это надо не тебе одному решать, а вместе с разработчиками, которые хотя бы умеют пользоваться профайлером.

Устраивать охоту на ведьм и выпиливать фичи потому что кому-то **кажется**, что 50 симпл-мобов и трупиков лагают - это бред. У нас мышей на станции больше. Лаги тут не причем.

**Comment by Cinericius** [comment]
Ну ок
