### ISSUE TITLE
Реверт генокрадов до бей12 уровня

### ISSUE THREAD

**Issue by TermService** [ChaoticOnyx/OnyxBay#1297]
### Улучшение
Текущие генокрады представляют собой сборную помойку из несбалансированных фич, принятых на условиях допила и добаланса, чего нет на данный момент.

### Решение
Портирование генокрадов бей12 текущей сборки и подготовка к опциональному применению в условиях Onyxbay сборки.

**Comment by HonkyDonky** [comment]
Согласен. Недавно проходился по коду этого ужаса и меня чуть не вывернуло наизнанку.
Спортировать текущих генокрадов с Бея и заревертить предыдущие изменения будет не так уж и сложно, I guess.

**Comment by koronoshka** [comment]
![IMG_20200122_113112](https://user-images.githubusercontent.com/58358430/72877815-c7d7d700-3d0a-11ea-81b2-3e6db5369bfe.png)
🤔

**Comment by HonkyDonky** [comment]
> картинка

К чему намёк?

**Comment by koronoshka** [comment]
Засрали текущего генокрада, вернем другого и начнем засирать фичами его?

**Comment by HonkyDonky** [comment]
> Засрали.

Насколько я понял - генокрадов изуродовал один человек, а не несколько.
К тому же под конец обсуждения в том ПР'е мы сошлись на том, что всё же эта фича - очень несбалансированная, и потому я предложил просто оставить её в сторонке.

Этих генокрадов чинить устанешь, проще будет просто взять с Бея и закончить на этом.

**Comment by LLIkolnik** [comment]
Шило на мыло.
Бэедаун перенёрфал генокрадов, дебфилософ их перебаффал. 
Duh?

**Comment by HonkyDonky** [comment]
Посмотри на все негативные иссуи связанные с "новыми" генокрадами и осознай, что всё же лучше 'мыло'.

**Comment by LLIkolnik** [comment]
Так и так говно.
На бэй12 генокрадов тоже жаловаться будут, если чё.

**Comment by HonkyDonky** [comment]
Ошибаешься.

**Comment by Cinericius** [comment]
> Посмотри на все негативные иссуи связанные с "новыми" генокрадами и осознай, что всё же лучше 'мыло'.

Потому что сейчас стоит "шило".
А нахуя? Чего эти беегенокрады умеют, тихо стингать в жопу?

**Comment by ZerlGray** [comment]
А я между прочем пуллил как то реверт, но его чот отклонили :С

Но вообще, беекрады совсем говно. В плане - они даже в жопу стингать тихо не то чтобы могут, и умирают от отрубания головы.

**Comment by Fritcher36** [comment]
> 
> 
> А я между прочем пуллил как то реверт, но его чот отклонили :С
> 
> Но вообще, беекрады совсем говно. В плане - они даже в жопу стингать тихо не то чтобы могут, и умирают от отрубания головы.
> И ровно столько же было запросов на их изменения, ибо они никому не нравились, а на бее им все больше и больше отрезали возможности.

Щас бы блять считать стинг в жопу чем-то нормальным. Одна из пососнейших генокрадных механик: вжух и ты петух.

**Comment by ZerlGray** [comment]
> > А я между прочем пуллил как то реверт, но его чот отклонили :С
> > Но вообще, беекрады совсем говно. В плане - они даже в жопу стингать тихо не то чтобы могут, и умирают от отрубания головы.
> > И ровно столько же было запросов на их изменения, ибо они никому не нравились, а на бее им все больше и больше отрезали возможности.
> 
> Щас бы блять считать стинг в жопу чем-то нормальным. Одна из пососнейших генокрадных механик: вжух и ты петух.

я имел ввиду, что беекрады из инструментов имеют только стинги, да и большую часть оных - удалили, а те что остались - довольно таки юзлес.

А, ну и да, стоит вспомнить, что если вы в тупую ревертните генок, вам либо придется ебаться опять же с переписыванием кода активации, либо опять иметь стинги которые активируются через выпадание окошечка выбора жертвы, а не по клику.
Короче, если хотите адекватных генок - напишите их, а не просто ревертайте.
Олсо, судя по кол-ву иссуев, генок у вас кто то после меня уже поломал, отломав дивижн, нопейн и найтвижн. Кря.

**Comment by TermService** [comment]
Тогда переделывать не будем
