### ISSUE TITLE
Изменить освещение во время эвакуации и дельта-коде.

### ISSUE THREAD

**Issue by HonkyDonky** [ChaoticOnyx/OnyxBay#1318]
Вырвиглазное дерьмо, которое начинается во время эвакуации, реально режет глаза.

### Геймдазайн
И добавить вместо него красное освещение на основе обычного света. Кстати давно еще хотели, да.

**Comment by ArmolitskiyCarpoeb** [comment]
это для того и сделано, чтобы глаза ебало тебе и ты хотел улететь со станции

**Comment by Epicus7** [comment]
Хрен знает, пусть геймдиз решает.

**Comment by Cinericius** [comment]
Там надо освещение красное сделать вместо обоссанного оверлея, да

**Comment by Epicus7** [comment]
Во, со светом норм, да.
