### ISSUE TITLE
Хардсьюты и здоровье

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1319]
### Улучшение
Хардсьюты, ИКСы, РИГи, чисто логически должны:
1) Позволять носителю получать информацию о своём здоровье на уровне медицинского сканера - облучение, переломы, кровопотеря и проч., желательно в виде UI.
2) Позволять окружающим получать сводную информацию в виде изменяющейся полоски хитов на спине и/или надписи при экзамайне, которая заменяет полоску хитов.

Почему?
Во-первых, о том, что ИКСы позволяют мониторить здоровье, ясно по некоторым вещам, которые есть в игре, конкретнее - недавней анимации загрузки систем костюма:
![Helth](https://user-images.githubusercontent.com/58848742/73117245-7f5f2a00-3f53-11ea-919d-255fdc1cb972.PNG)
Системы здоровья есть, но никакого игрового взаимодействия с ними механ вообще не предоставляет.
Во-вторых, эту информацию легко можно найти на вики об игре, откуда хардсьюты были взяты - на вики о дедспейсе:
![Скрин](https://user-images.githubusercontent.com/58848742/73117273-f09edd00-3f53-11ea-88ac-663d0d7e256a.PNG)
©  _fandom wiki_

Но у нас этого нет, потому я предлагаю это добавить.

**Comment by Srankl1n** [comment]
ну и к чему ты хочешь привязать полоску хепе, если у нас медицина это дроч в мозги

**Comment by MrMagick2104** [comment]
Привязать к активности мозга 1 к 1 в процентах, бонусом снимать проценты за повреждения внутренних органов и пониженное насыщение кислородом, а также за брут на конечностях при прохождении определённого порога.
Если мозг не мёртв, то ниже одного процента полоска не опускается.
Правда, нужно у адептов медицины узнавать, какие повреждения наиболее фатальные и сколько за них нужно снимать, чтобы не было EMERGENCY, USER DEATH IMMINENT при ушибе пальца ноги об тумбочку.

**Comment by Cinericius** [comment]
Мерять сложненько, да. А так можно.

**Comment by Epicus7** [comment]
Улучшение можно выполнять без полоски пока, показывая значение здоровья только в Examine. Если спрайты не появятся, то потом отдельный иссуй на допил заведем.

**Comment by MrMagick2104** [comment]
> ну и к чему ты хочешь привязать полоску хепе, если у нас медицина это дроч в мозги
> Привязать к активности мозга 1 к 1 в процентах, бла-бла-бла

Подумал, кроме того, не обязательно делать полоску на сто процентов точной, можно было бы сделать её дискретной. Шесть условных делений (далее - лампочек) - уровней повреждения.
Чем меньше лампочек горит, тем сильнее повреждения, очевидно.
Каждая лампочка потухает при выполнении определённых условий:

Все лампочки горят: 100% ХП, как и у куклы со здоровьем, ничего необычного.

Одна лампочка не горит: Мелкие повреждения без кровотечения, т.е. ушибы, а также небольшие ожоги (до 15 урона).

Две лампочки не горят: Мелкие повреждения с кровотечением, облучение (без большого урона печени и почкам, естественно), наличие токсинов в крови (до 10 юнитов?, не уверен по этому поводу), средние ожоги (до 50 урона), небольшой урон по одному органу (aka minor damage), здоровье мозга в пределах от 100% до 90%, снижение оксигенации в крови (от 100% до 80%)

Три лампочки не горят: Переломы (так как большинство ИКСов может пережимать переломы, по-моему, не слишком критично), сильные повреждения с кровотечением, но без артериального и внутреннего, есть посторонние объекты в теле (пульки), токсины в крови (выше 10 юнитов), средний урон по одному органу, либо небольшой урон по двум и более органам, здоровье мозга в пределах от 80% до 60%, пониженная оксигенация крови (от 80% до 60%), либо незначительная кровопотеря (не более, чем двадцать процентов крови).

Четыре лампочки не горят: артериальное внутреннее кровотечение, отсутствие конечности без артериального кровотечения от её отсутствия (не целой руки, а, допустим, ладони), значительная кровопотеря (потеряно до 40% крови), значительно снижена оксигенация крови (от 60% до 30%), сильный урон по одному из органов, либо средний по двум, здоровье мозга от 60% до 40%.

Пять лампочек не горит: артериальное внешнее кровотечение, отсутствие целой конечности (рука, нога, голова?, гроин?), смерть/некроз одного из органов (кроме сердца), либо сильный урон по двум органам, оксигенация в крови ниже 30%, кровопотеря выше 40%, урон мозгу до 20% здоровья мозга.

Пять лампочек не горит, последняя мигает (опционально, это можно докинуть в следующий или предыдущий уровень): остановка сердца + выполнение условий из предыдущего "уровня" повреждений.

Ни одна лампочка не горит: смерть мозга.

(Опционально): несколько лампочек горят (переливаются) фиолетовым (или каким-то другим цветом, радикально отличным от зелёного - красного, можно белым, например, но, имхо, это так себе выглядеть будет), если пациент мёртв и у него есть нейролейс, либо если пациент - синтетик.

Удобство такого подхода в том, что не нужно составлять _**универсальную сверх-формулу**_, которая будет идеально высчитывать здоровье пациента из факторов выше.

<hr>

Цвет делений зависит от количества их активных, естественно. 6 - зелёный, 5 - #a5fa00 или что-то типа такого, 4 - #c8ff00, 3 - простой жёлтый, 2 - оранжевый, 1 - красный.

Кроме того, выполнение нескольких (трёх, допустим) условий с одного уровня, я думаю, должно равняться передвижению на следующий уровень? 
Т.е. у нас есть условный Василий Петров, космонавт в РИГе, у него 45 урона ожогами, немного накоцана печень (на minor урон) от цирроза и он облучён. Получаем, что выполняются целых три условия, но все они из уровня 2, т.е. гореть чисто технически, должно 4/6 лампочек. Но, при   этом, его повреждения достаточно серьёзные, и, имхо, он достоин 3/6 лампочек, горящих на его костюме.

<hr>

Кроме того, по теме, можно было бы одолжить озвучку костюма, предупреждающую нас о каких-то повреждениях (возможно, ещё и некоторые значки, которых у нас нет, например, радиационной опасности, исключительно для хардсьютов), из [халфлайфа](https://www.youtube.com/watch?v=6oPGjA5-4AM).
Если делать это, то, конечно, сделать озвучку переключаемой в префах.
Если не делать, то можно было бы просто сообщения в чат кидать по типу урона, полученного от окружающей среды.
Обязательно, естественно, включать тихий звук прямой линии в ЭКГ-машине при остановке сердца ([e.g.](https://www.youtube.com/watch?v=y5psyfZ9OZA))

**Comment by MACTEP-ABATAP** [comment]
Фича крутая, может кто-то из спрайтеров заинтересуется, да и наверное респрайт ригов уже в нескольких иссуях есть
