### ISSUE TITLE
УЛЬТРАНАСИЛИЕ

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#132]
Суровая механная система насилия. Боль, пытки, крики, разнерф мясных крюков, в общем все, что мы любим и ценим. Что-то из этого можно покрасть, например, со старого Интербея.

**Comment by Voldirs** [comment]
Учитывая, что тут от боли у людей сердце останавливается, это будет натуральное мдааааааа.

**Comment by Cinericius** [comment]
Ну так это тоже можно пофиксить/отрегулировать в процессе.

**Comment by Epicus7** [comment]
Не уверен, что это прям ПРИОРИТЕТНО. У нас на сервере итак садомазо творится. Мне кажется надо больше геймплей разбавлять и ролевые/педальные штуки добавлять, чем подобное делать.

Ну и если уж приоритетное - то в майлстоун добавь что ли. То что не в майлстоуне - не в приоритете автоматически.

**Comment by Cinericius** [comment]
Пускай повисит с низким приоритетом

**Comment by Cinericius** [comment]
Поставлю порт, потому что основное можно покрасть с Интербея.
