### ISSUE TITLE
Добавить отдельный шкаф для одежды в офис капитана.

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#1323]
Ровно такой же, какой стоит у Агента Внутренних Дел.

**Comment by Epicus7** [comment]
@Exapster, скриншот можно конкретного шкафа у АВД? И у капитана чо, мало шкафов?

**Comment by Exapster** [comment]
@Epicus7, через день-два выдам скрин. Да, у капитана есть лишь капитанская одежды, а чего-то обычного - нет. Да и места в каюте слишком много. Почему бы и шкаф не поставить?

**Comment by Cinericius** [comment]
Брух
