### ISSUE TITLE
Визуальное искривление пианино при получении урона

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1334]
### что
при получении достаточно урона пианино будет корёжится на icon_rotation = 353

зачем?

а почему бы и нет? мы что? не прогрессивный билд? нам нужно разнообразие!

![image](https://user-images.githubusercontent.com/48761132/73203748-b8afb980-414e-11ea-8f37-45be42c5a94d.png)

**Comment by HonkyDonky** [comment]
Ревьювь ПРы для прогрессивного билда, с-суко.

**Comment by TapKo4eB** [comment]
надо ещё их протестировать
а у меня нету времени тестировать

**Comment by HonkyDonky** [comment]
Ты что, каждый ПР запускаешь на локалке и проверяешь?
Жестоко.

**Comment by TapKo4eB** [comment]
еще бы мне понять как не качать весь форк полностью с бранчем, а только к моему присобачить

**Comment by HonkyDonky** [comment]
Ты ещё и весь форк качаешь ради этого?! Ахуеть! Блять! Пиздец! Я реально в шоке.

**Comment by TapKo4eB** [comment]
![image](https://user-images.githubusercontent.com/48761132/73204169-8d799a00-414f-11ea-8429-463428b87db1.png)

**Comment by HonkyDonky** [comment]
Теперь мне всё понятно...
Какой билд - такие и разработчики...

**Comment by TapKo4eB** [comment]
Кстати наебал со скачкой всего форка.
Я нашёл способ через ремоут бранчи качать)

**Comment by Cinericius** [comment]
Можно еще звук корежить.

**Comment by Cinericius** [comment]
Не знаю зачем, но оDOBрено.

**Comment by MrMagick2104** [comment]
> Можно еще звук корежить.

Не надо, пожалуйста. Мне даже сложно представить, что будут делать всякие извлекаемые из ASS ноты будут делать с корёженьем, но это явно будет против Женёвских конвенций.

**Comment by GusevDuhast** [comment]
Пожалуйста, не издевайтесь над звуками пианино, и так с трудом в мелодии выходит, так вы его вообще убить собираетесь
