### ISSUE TITLE
Machinery&Contents

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#134]
При сборке машины в ней находятся детали те, что были вставлены самим игроком, и те, что необходимы для создания самой конструкции. 

Пример собранного Circuit Imprinter:
![image](https://user-images.githubusercontent.com/29167103/44773281-db642a00-ab78-11e8-93ce-1a17368028ac.png)

**Comment by Shirlineyn** [comment]
Это не баг так-то.

**Comment by O0oMaximo0O** [comment]
Не нравится наличие компонентов в двух местах. Стоит наверно повесить плашку рефакторинг/оптимизация? Насчёт бага - вроде на работоспособность не влияет, наверно да, не баг.

**Comment by MaxFreemen** [comment]
Это костыль, полагаю, который надо чинить.

**Comment by Doster-d** [comment]
Боже уеби того, кто писал этот кусок говна.

**Comment by Doster-d** [comment]
В результате какой-то клоун просто очищал список без удаления предметов, поэтому предметы находились в контентсах.
Поэтому, дети, если видите список, то надо использовать QDEL_LIST, а не просто очищать список, всем пока.
