### ISSUE TITLE
Сделать нормальные спрайты застёгнутым лабораторным халатам

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1344]
### Улучшение
Застёгнутый халат в анфас, как ни странно, не застёгнут до конца. 
![Халат](https://user-images.githubusercontent.com/58848742/73277872-cf601a00-41fb-11ea-93b0-7bc7ea065500.PNG)
Почему это - проблема?
1) Выглядит очень плохо, хотя это субъективно.
2) Таким образом застегнём халат, а потом прольём на себя какой-нибудь реагент => в лучшем случае получим пару испорченных брюк. Оставлять промежность открытой<s>, особенно в свете недавних событий,</s> при работе с химическими реагентами - не самая хорошая идея, что, я думаю, каждому понятно.
3) Даже на спрайтике предмета халат застёгнут нормально:
![Халат3](https://user-images.githubusercontent.com/58848742/73279399-1cdd8680-41fe-11ea-8f6c-8aaf796ebfdc.PNG)

### Решение
Нарисовать нормальные спрайтики застёгнутым лабораторным халатам, заменив существующие, либо добавив возможность между ними переключаться, путём нажатия соответствующей кнопки в контекстном меню (но можно и без последнего).
Как это примерно должно выглядеть:
![Халат2](https://user-images.githubusercontent.com/58848742/73280180-39c68980-41ff-11ea-8415-e7bbd7488d52.png)

**Comment by Voldirs** [comment]
Так ты сам же уже нарисовал))

**Comment by MrMagick2104** [comment]
Так там же тыщщи их разновидностей, начиная от халата криминалиста, заканчивая научным.
