### ISSUE TITLE
Запилить операции по смене пола и смене лица.

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#1348]
С полом нужна возможность выбрать заодно и тип тела если делаешь трапа

С лицом должен меняться и голос, чтобы можно было полностью поменять личность. На выбор даётся два списка имён, в одном все имена членов экипажа, во втором 10 рандомных имен. Может быть добавить ещё и третий вариант, это Unknown. Плюс хирург может поменять флавор тому кого оперирует.

З.Ы.: бот сломался несите нового

**Comment by MrMagick2104** [comment]
> С лицом должен меняться и голос

Мне кажется, стоит сделать манипуляции раздельными или последовательными, чтобы можно было иметь один голос и другое лицо.
> Unknown

А как должен звучать этот голос? Как синтезированный? Как самый обычный голос у самого обычного человека?
>  одном все имена членов экипажа

Мне кажется что стоит сделать некоторую вероятность фейла во время создания лица как у члена экипажа, при котором либо просто выбирается другое рандомное имя, либо несколько согласных и гласных меняются на другие соответственно, что можно исправить повторной операцией/наличием улучшенных инструментов.
Например, вместо b в имени - d, вместо B - в, вместо е - ё, (если починили уже некорректное отображение кириллицы в названиях) a - o и всё в таком духе.
> З.Ы.: бот сломался несите нового

Press F to Pay Respects

**Comment by Voldirs** [comment]
>Мне кажется, стоит сделать манипуляции раздельными или последовательными, чтобы можно было иметь один голос и другое лицо.

Как вариант, но я не могу придумать для какой ситуации такое очетание могло бы понадобиться

>А как должен звучать этот голос? Как синтезированный? Как самый обычный голос у самого обычного человека?

Да, просто как обычный голос, не распознаваемый радиосистемой

>Например, вместо b в имени - d, вместо B - в, вместо е - ё, (если починили уже некорректное отображение кириллицы в названиях) a - o и всё в таком духе.
Yes please

**Comment by MrMagick2104** [comment]
> Как вариант, но я не могу придумать для какой ситуации такое очетание могло бы понадобиться

Тритор в противогазе. Когда снимает противогаз, чтобы показать лицо СБ он - один человек, а когда говорит - другой. Удобно для быстрых перевоплощений и маскировки, к тому же может породить такие ситуации, когда хирург тебе пластику сделал, а голос-то забыл. Да и странно выглядит, если голос зависит от лица.
> распознаваемый радиосистемой

Инвалиды-космонавты все со слуховыми аппаратами ходят или что? Ведь даже при встрече тет-а-тет этот голос так и будет Unknown. 
Кстати, если это таки делать, то предлагаю запилить бонус-фичей при прерывании операции, а не отдельной опцией.

**Comment by Voldirs** [comment]
>Инвалиды-космонавты все со слуховыми аппаратами ходят или что?

Похоже что да

**Comment by Cinericius** [comment]
>нужна возможность выбрать заодно и тип тела если делаешь трапа

Хочешь убить все веселье?
