### ISSUE TITLE
Борго худ

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#135]
Если перезайти в игру через клиент>реконнект то слетает худ.Если до реконнект у тебя что-то было в модульных слотах, то ты ещё можешь этим пользоваться, но зайти в инвентарь уже не получится

**Comment by hekko4** [comment]
Только что попробовал произвести на локалке, не получилось.
Какой хотя бы модуль стоял?

**Comment by Demisov** [comment]
Медицинский ещё ресерч

**Comment by Demisov** [comment]
У меня последняя версия бульенда
