### ISSUE TITLE
Призраки могут взаимодействовать с консолями [затиранено]

### ISSUE THREAD

**Issue by Kiruxa1324** [ChaoticOnyx/OnyxBay#136]
#### Описание проблемы
Призраки или обсерверы могут менять значения в консолях [затиранено]

#### Разница между реальным поведением и ожидаемым
Очевидна, призраки не должны иметь возможность менять значения

#### Как воспроизвести проблему?
Нажать на консоль рядом с ней и менять значения

#### Как долго известно о проблеме?

Обновление было 29.08.18, узнал о баге в 22:00 на клиенте 511

#### Версия клиента, версия сервера и идентификатор игры

511 версия,ID игры bV6-cIw4, версия сервера cba73eac1f6e378f67807624be53b0bd92cffc68 

#### Дополнительная информация

- [ ] Проблему можно воспроизвести хотя бы один раз
- [x] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [x] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [x] Проблема случилась в недавнем раунде (прошло меньше недели)
- [ ] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by Epicus7** [comment]
Педальные призраки могут с любыми консолями взаимодействовать - это нормально. Здесь, видимо, Бейцы проверку потеряли.

**Comment by Kiruxa1324** [comment]
Про педальных я знаю. Здесь юзверовские призраки, кто-то даже на минуту лишил всех связи переименовав сервер)

**Comment by Epicus7** [comment]
Н-да. Тут особо не спрячешь, ну ладно, чо. Придется фиксить

**Comment by Kiruxa1324** [comment]
Нет, здесь только коммуникации

**Comment by Kiruxa1324** [comment]
Я могу изменить репорт, чтобы не палить баг

**Comment by Epicus7** [comment]
Так история сохраняется же. Пофиг, тут починить быстро можно.

**Comment by Cinericius** [comment]
А чо не закрыли-то, лол
