### ISSUE TITLE
НАРДЫ И МАНГАЛ

### ISSUE THREAD

**Issue by turbomensch** [ChaoticOnyx/OnyxBay#1380]
Начнем с того, что обычные карты уже всем давно приелись. Вряд ли, пройдя по станции, можно увидеть ассистентов, играющих в карты. Определенно, есть огромное количество карточных игр, такие как "преферанс", "рамс" или же "очко", которые и по сей день пользуются огромной популярностью среди населения. Но даже при таком большом выборе, сердце продолжает требовать нечто родное и близкое, то самое, что поможет незабываемо и с пользой провести время. А что лучше всего поможет скрасить время на станции? Конечно, всеми известная игра - нарды. Данный вид развлечение позволит людям получше раскрыть своего персонажа и погрузится в игру. Кроме того, в будущем можно будет сделать отдельный турнир по нардам, и я считаю, что он займет почетное места среди "Chaoticfest" и "Onyx Chess Tournament".
 Не зря же в эту игру играют все - от юных до старых, везде - от камер тюрем до лавочек около подъезда. И, кого не спроси, любой знает, что в нарды веселее и приятнее играть, когда рядом с тобой жарится сочный шашлык, а на столе стоит холодное пиво. В данный момент на сервере есть лишь жалкая замена шашлыку - мясной кебаб, который по всем параметрам уступает лучшему блюду всех времен, начиная от названия, заканчивая вкусом. 
  Вы спросите, почему не ввести только шашлык? А все просто, шашлык - это половина удовольствия, которое приносит данное блюдо людям. Вторая половина - его приготовление, поэтому именно добавление мангала подарит игрокам ту незабываемую радость, которую все мы испытываем во время приготовления шашлыка. 
  Так же помимо добавления мангала, сделать разные виды шашлыка. Можно хотя бы вот эти, самые известные, среди остальных:
 "Обычный" - нестареющая классика. Именно его вы чаще всего увидите, прогуливаясь майским днем.
 "С пивом" - выбор юных любителей шашлыка. Пиво делает вкус шашлыка еще более прекрасным, удивительным и незабываемым.
 И, конечно, любимый рецепт бати - "Пережаренный". Как завещали деды и отцы: "Нормальная прожарка, зато глистов не будет. Есть можно, с майонезом пойдет"

Думаю, любой из вас поддержит столь замечательную идею, которая, я надеюсь, вскоре воплотится в жизнь и каждый на сервере сможет незабываемо провести время, играя в нарды и вкушая пищу богов, именуемую шашлыком.

**Comment by TapKo4eB** [comment]
ещё нужно срочно запилить возможность розжига костра

**Comment by TermService** [comment]
костры точно нет, мы же на станции, нарды мб

**Comment by Epicus7** [comment]
@Cinericius,

> игра про космическую станцию в 25 веке

> одобряем иссуи про шашлык, лавочки и пивас

Тупа кринж.

Короче охуенные идеи, ставлю очень сложно, ибо тут надо костер реализовывать, интерфейс нардам, да и сами нарды реализовать неоч легко, а делать это нужно с нуля. Короче охуенные иссуи, найс геймдиз.

**Comment by Epicus7** [comment]
А, забыл. Тут еще спрайты нужны.

**Comment by Epicus7** [comment]
@MemoryDreams, я закрою этот кринж все-таки. Если хочешь его переоткрыть - твое дело, но мне кажется это какой-то треш.

Просто висит, а ты не пересматриваешь уже одобренные..
