### ISSUE TITLE
Подготовить билд к переезду на 513

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1384]
Нужно подготовить ПуллРеквест, который:

1. Заставит наш билд компилироваться без ошибок и варнингов на версии бьонда 513.
2. Исправит все проблемы связанные с переходом бьондом с однобайтовых кодировок на Unicode.
3. Исправит все нестабильности, которые возникают в процессе тестирования нашего билда на версии 513. Падения, зависания - все, чего не было раньше.
4. Поддержит обратный конверт из юникода в cp1251 для работы с Базой Данных. Эти конверты должны быть опциональными и включаться через конфиг, чтобы их можно было легко выключить после переезда БД на юникод.

В качестве основы можно использовать мой ПР #1383, в котором можно найти больше подробностей.

**Comment by Iotwo** [comment]
А, так вы на 512 бйонде разворачивались.. Вот так неожиданность.

**Comment by Epicus7** [comment]
Пока повешу "нужны идеи", ибо оптимальное решение недостаточно хорошо проработано, чтобы выставлять награду.
