### ISSUE TITLE
Свет от космоса

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1386]
### Улучшение
Если взглянуть на космос, можно заметить, что он, внезапно, не полностью чёрный и напоминает фон из какого-нибудь ФТЛа, яркий, цветастый. Но! но! как ни странно, космос не излучает свет.
Было бы очень красиво, если бы окна не были бесполезным куском декора/геймдизайнерским инструментом, а сквозь них бы что-нибудь светило.
Таким образом, предлагаю впилить клеткам космоса пассивное освещение, чтобы и соляры не на чистой математике работали, да чтобы и во время перебоев электричества не было темноты, как в пещерах гоблинов.
А т м о с ф е р а, опять же.

### Решение
Космос освещает 2-3 тайла (это с учётом тайлом стекла) вокруг себя, достаточно слабо, примерно на том же уровне, что и просто зрение в темноте без освещения, но не чёрные темнотайлы, как сейчас, либо сделать тайлы рядом с космосом просто видимыми для всех.

### Альтернативы
Ещё можно запилить условный источник света в космосе и так, побаловавшись с расчётом лучей от него, освещать космические клетки в соответствии с, но это заметно сложнее.

P.S. Могут ли быть проблемы с производительностью из-за этого или нет? Динамическое освещение 80% всего игрового пространства сильно есть вычислительные мощности будет?

**Comment by TermService** [comment]
свет от звезд же))

**Comment by MrMagick2104** [comment]
Звёзды - часть космоса.

**Comment by Iotwo** [comment]
С одной стороны, солнечные батареи на станции всё таки улавливают какой-то свет, поэтому изменение имеет под собой хоть какое-то осмысленное обоснование.

**Comment by MrMagick2104** [comment]
А с другой?

**Comment by Iotwo** [comment]
А с другой, если ни в одной из версий "целей существования станции N" не описано, что оная висит в какой-нибудь системе, ядром которой является функционирующая звезда, то свет, который улавливают соляры, такой же реальный, как потолок на станции.

Вариант с излучением от далёких звёзд не внушает доверия, так как рассеивание в космосе нормальное такое.

**Comment by GusevDuhast** [comment]
Так у нас же в "актуальном" лоре прописано что мы в системе "такой-то" висим, на орбите такой-то звезды.

**Comment by TermService** [comment]
Налить динамического света тоже не вариант, итак лагает

**Comment by MrMagick2104** [comment]
Можно тайлам, которые в радиусе двух-трёх клеток от космоса выдавать освещённость, а не делать клетки космоса источниками света. Так должно быть лучше, наверное.
Или только прилежащим тайлам, но делать его более сильным.

**Comment by Iotwo** [comment]
> Так у нас же в "актуальном" лоре прописано что мы в системе "такой-то" висим, на орбите такой-то звезды.

Тогда вариантов несколько и зависят они от ориентации "окон" станции относительно источника света.
1) положение станции таково, что все внешние грани равномерно освещены независимо от времени суток, и тогда только техпереходы между этажами не имеют "собственного" освещения от космоса.
2) станция крутится, попеременно "подставляя" звезде одну из своих сторон, таким образом освещёнными становятся клетки, в настоящий момент повёрнутые к звезде. Ориентацию можно как-то брать от соляр,
3) ещё какой-нибудь хитрый план, как и рыбку съесть, и на стул сесть.

**Comment by TermService** [comment]
но это не так работает, у тебя два вида темноты: абсолютная(которая за стенами) и динамическая, которая оверлей

**Comment by MrMagick2104** [comment]
> но это не так работает, у тебя два вида темноты: абсолютная(которая за стенами) и динамическая, которая оверлей

Честно, понятия не имею как это работает. 
Можно тогда динамическую темноту около космоса убирать или что?

> положение станции таково, что все внешние грани равномерно освещены независимо от времени суток, и тогда только техпереходы между этажами не имеют "собственного" освещения от космоса.

Можно предположить, что звезда висит над станцией сверху, но под углом. Объяснит и вращение панелей, и равномерную освещённость везде (с тёмной стороны отражается от местной Венеры какой-нибудь. На орбите газового гиганта ведь висим).

**Comment by Cinericius** [comment]
Было бы красиво, но я боюсь за производительность.

**Comment by Iotwo** [comment]
Где-то в конфигах вашего билда был параметр, отвечающий за свет от космоса.

**Comment by Epicus7** [comment]
Не думаю, что динамическое освещение оправдано. Насчет производительности - надо исследовать этот вопрос. Я не знаю сейчас.

**Comment by MemoryDreams** [comment]
@MrMagick2104 можешь исследовать вопрос производительности?

**Comment by MrMagick2104** [comment]
Посмотрел на локалочке, действительно, всё уже есть в конфигах, просто выключено.
Config.txt, пункт starlight.
Вот так выглядит отбытие со starlight 3:
![EscHallL](https://user-images.githubusercontent.com/58848742/75453601-343a9b80-5985-11ea-8fd3-0842015a8684.PNG)
А вот так со starlight 0, т.е. сейчас:
![EscHallNL](https://user-images.githubusercontent.com/58848742/75453640-4288b780-5985-11ea-8354-563af7bd3218.PNG)

> @MrMagick2104 можешь исследовать вопрос производительности?

Не совсем понял вопрос, но вот данные мобконтроллера при настройках 3 и 0 соответственно:
![Starlight3](https://user-images.githubusercontent.com/58848742/75453745-6a781b00-5985-11ea-88d5-59ed54fb6a1d.gif)
![Starlight0](https://user-images.githubusercontent.com/58848742/75453748-6ba94800-5985-11ea-9478-e96fc1db81e4.gif)

**Comment by MemoryDreams** [comment]
Странно, но, кажется, оно без света лагает чуть-чуть сильнее, чем с ним. Цифры, вроде, больше. Разница, вроде, не очень разительная, так что, ничего сломаться не должно. Давайте выкрутим на троечку.

**Comment by MrMagick2104** [comment]
> Странно, но, кажется, оно без света лагает чуть-чуть сильнее, чем с ним. Цифры, вроде, больше.

Называется статистическая погрешность, да.

**Comment by HonkyDonky** [comment]
Конфиг обновлён, идея принята.
