### ISSUE TITLE
Невозможность окончить раунд внутриигровыми путями на мейне

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1387]
### Улучшение
Относительно #1305, изменений конфигов и мейна. Такое бывает, что глав тупо нет (вайтлист и низкий онлайн сказываются), на станции убежала какая-нибудь синга (условно) и пожрала 60% станции, прибытие и криогеника в говно, но шаттл вызван быть не может, потому что ни воута, ни капитанской карты нет. Приходится либо слапать педалей, либо лезть за картой на 3 з-лвл особыми техниками. Ни то, ни это валидным решением не является, ведь первое — по-просту некультурно, а второе могут счесть багоюзом. Так как сторителлера у нас пока нет, то, в качестве временного решения, нужно добавить собственно что-то другое, потому что если раунд в сессионной игре, в которой со временем эта сессия может загнуться, нельзя закончить внутриигровыми способами, то это - плохой геймдизайн.

### Решения
1) Добавить возможность простым смертным делать воут на вызов ЕРТ раз в полчаса после прохождения одного часа игры через вёрб Vote.
2) Делать #1305 только на бегиннере
3) Делать #1305 на мейне, но добавить проверку на деклары глав перед киданием виртуального кубика.
4) Удалить бегиннер
5) Вернуть воут на шаттл, но сделать его реже и только после второго часа, добавив автоматом 1/3 голосов от всего онлайна на невызов.

P.S. Лично я не против ни того, ни другого изменения, но в условиях дикого мейна без глав и педалей они выглядят так себе.

**Comment by Srankl1n** [comment]
а они че мержанули отсутствие кэпкарты? аутстендинг мув.

короче, на тг при отсутствии всех консолей коммуникаций на з-уровне станции автошаттл на 25 минут, однако у нас можно скачать програмку, что очень васянство как по мне. хочу старые консоли, которые позволяют тебе открутить все платы и ждать шаттла, без возможности отзыва

**Comment by MrMagick2104** [comment]
> а они че мержанули отсутствие кэпкарты? аутстендинг мув.

Йеп:

> Еpicus7 merged commit 78a10b7 into ChaoticOnyx:dev  5 days ago

**Comment by Cinericius** [comment]
Там ревёрт паранойи подвезли

**Comment by TapKo4eB** [comment]
су+ка я же меншион пулл реквест он бы сам закрылся...
