### ISSUE TITLE
Поломаны некоторые заклинания мага

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#1395]
Спеллы мага (особенно "новые") полны багов и работают зачастую неадекватно.
Как пример: Блодшард кастуется ток на человека, но при этом он НЕ ранит этого человека, а ранит всех окружающих.
В итоге бои с ним - это суицид.
Были косяки с высасыванием крови и еще с несколькими.

**Comment by Epicus7** [comment]
Ставлю сложно, потому что нужно проверять ВСЕ заклинания и чинить их.

@ZerlGray, в таких случаях как минимум надо бы описать ВСЕ сломанные заклинания и что конкретно с ними не так. А в идеале еще и в разных иссуях.

**Comment by TobyThorne** [comment]
Блядьшарды, если мне не изменяет память, уже успели переделать. Больше ничего конкретного иссуй не описывает, как выполнять - не совсем ясно.
