### ISSUE TITLE
Сделать новую опцию для защиты от радиационного пояса в генераторе щиов.

### ISSUE THREAD

**Issue by hekko4** [ChaoticOnyx/OnyxBay#14]

**Comment by Epicus7** [comment]
Зачем? Не вижу смысла в этой фиче. Механ и с техтоннелями сейчас нормально работает.

**Comment by Ruforce** [comment]
как жаль что опухоигроки туда не ходят, а потом бегут помирать в медблок, заблевывая всю регистратуру.

**Comment by Kin51** [comment]
Советую тогда перечекать флаги на всех техах - ходит слух что экранировано не всё.
