### ISSUE TITLE
починить направление источника звука взрыва 

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1400]
### Описание бага
фар эксполжн играет в уши мобу и хуй пойми где бахает
### Воспроизведение
взорвать что нибудь вне экрана.
или внутри экрана
где угодно короче лишь бы на том же з уровне

**Comment by MrMagick2104** [comment]
С одной стороны, это - мелкая недоделка, незначительно влияющая на восприятие игры.
С другой же, он открывает множество возможностей, например, в создании интегралки, которая на протяжении 180 секунд и более мешает по единице воды с калием раз в секунду, создавая впечатление, что станция расположена в горячей точке. Я считаю, что удалять такой внутриигровой опыт было бы кощунственно. Хотя тут ещё влияет то, что громкость бума водокалия не скалируется, но всё равно.
Плюс, можно это просто списать на "особенности распространения звука в замкнутых пространствах". Множественное отражение звука и вибрации стен всё равно не дадут определить источник шума.

**Comment by TapKo4eB** [comment]
иссуй как раз для того чтобы вычислить где находится машина или хуй мешающий води4ку с калием, ибо скалирование ещё труднее делать а так хоть ебало набить можно

**Comment by MrMagick2104** [comment]
> бтв нахуй вибрации тоже имеют скорость и они не везде и сразу

Скорость звука в твёрдых телах выше, чем в газах, из-за чего в унисон будут все стены жужжать, ещё до прибытия ударной волны от воздуха. Какофония в течение секунды - двух такая будет, что что-нибудь услышать и понять будет невозможно.
К тому же, система замкнутая, считай локализованное землетрясение образуется, из-за чего всех на станции будет косоёбить от тряски туда-сюда, что несколько затруднит определение места взрыва.
Пик релейтед.
![Uaz](https://user-images.githubusercontent.com/58848742/73679568-ba87f880-46cb-11ea-8dbd-65a4e4c7f308.gif)

**Comment by MrMagick2104** [comment]
Короче, по-моему, надо пилить это только для взрывов маленького радиуса.

**Comment by TapKo4eB** [comment]
Как говорил один великий человек. Наш билд про геймплей, а не реализм.

**Comment by Epicus7** [comment]
Ставлю низкий приоритет
