### ISSUE TITLE
Дюпы и прочие приколы из-за кривого использования input в разных местах

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#1403]
Я не имею доступа к вашему элитарному дискордику, так что спрошу тут:

Как известно, в билде с древнейших времен есть баг - любое действие которое использует input можно юзать много раз, потому что input возвращает что либо только после того, как отработает полностью. Т.е. можно прокликать какую нибудь кнопочку сотню раз, и сотню раз же получить результат.

Вопрос: Нельзя ли просто написать новую input функцию которая будет чекать, делает ли УЖЕ моб что либо (бинарную переменную присвоить мобу), и если да - то посылать его нахуй?
И заменить все input функции на новую.

**Comment by TermService** [comment]
тебя разбанили, заходи

**Comment by ZerlGray** [comment]
> тебя разбанили, заходи

В дискорде? Нет.

**Comment by TermService** [comment]
![lightshot_1580768056](https://user-images.githubusercontent.com/18397924/73695769-d8fdec00-46eb-11ea-952c-7c1df59074b3.png)

**Comment by ZerlGray** [comment]
![image](https://user-images.githubusercontent.com/32713309/73698336-ec13ba80-46f1-11ea-8c66-222d9b4cdfe7.png)

**Comment by MrMagick2104** [comment]
> input можно юзать много раз, потому что input возвращает что либо только после того, как отработает полностью.

Такое есть, но сделает ли его убирание игру лучше или превратит сс в симулятор ожидания того, как ты сваришь три палки из листов стали? Баг ли это вообще?
Из того, что сразу приходит на ум: шахтёры станут в двести раз аутичнее, на добычу тех же самых ресурсов уйдет как минимум в два раза больше времени на ранних этапах, что для социальной игры как-то так себе.
Или, допустим, то же строительство. Делать условные двадцать кусков арматуры по очереди ты будешь делать ОЧЕНЬ долго, хотя этого хватит всего на одну мелкую коробку в космосе, не говоря уже о полноценном строительстве зиккуратов и прочего.

**Comment by GusevDuhast** [comment]
Эй, для шахтеров это реально будет больно, ибо с той скоростью что стандартная дрель бурит, только тыкая на множество тайлов, можно быстро накопать материалов

**Comment by TermService** [comment]
Проблема не в том что input плохой оператор, туда впихнули задержку, однако не запихнули проверку не втыкает ли кто-то ещё что-то, таким образом получалось что впихивая условное стекло несколько раз не срабатывало его убавление вовремя, а следовательно можно было напихивать по несколько раз

**Comment by ZerlGray** [comment]
Тож самое можно делать практически со всеми объектами имеющими инпуты и алерты.
Это никак не трогает шахтерку, ибо в сверлении дрелью нет ни инпутов ни алертов.
Можно навызывать окошек с объектом, и пока они висят, сделать с объектом то, что можно сделать без вызовов этих функций. Итогом будет то, что объект вероятно, дюпнется. Или телепортируется. Или и то и другое вместе. Это можно избежать впихивая везде где есть инпуты проверочки отдельные, а можно просто соорудить хитровыебнутые функции инпутов и алертов, которые будут чекать, юзается ли объект еще кем либо и юзается ли этот объект одним и тем же человеком несколько раз подряд.

**Comment by Epicus7** [comment]
@ZerlGray, странный вопрос.

Конечно можно, хорошая идея. По поводу бана в дискорде напиши мне в личку в дискорде.

**Comment by HonkyDonky** [comment]
Найдёшь где такой input - репорти.
