### ISSUE TITLE
Examine объектов на фото

### ISSUE THREAD

**Issue by IvanDonFon** [ChaoticOnyx/OnyxBay#1410]
### Улучшение
Можно делать Examine объектов на фото. Смысла в фото будет больше

### Решение
Выполнить эту просьбу

**Comment by TapKo4eB** [comment]
Смысл фото в том что это фото. Картиночка. Тем более уже на фотографии есть пометка мобов и что у них в руках.
Да и экзамайн подобный сделать будет сложно. А если и сделают, я уже чувствую что им будут класть сервер.

**Comment by Epicus7** [comment]
Поправлю: в рамках бьонда это впринципе нереализуемо.
