### ISSUE TITLE
У хирург боргов нет возможности фастом снимать одежду с пациентов.

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1446]
Сделать возможность киборгам либо через особый инструмент, либо просто баффом скорости снятия одежды быстрее раздевать хуманов для операции, ибо у нас в текущий момент снятие одежды это необходимо в хирургии.

**Comment by Srankl1n** [comment]
15 секунд на раздевание не можем потратить))00 когда для лечения мозга достаточно снять головной убор (что не так уж и долго) и дальше лечить хоть задним числом.

**Comment by TapKo4eB** [comment]
Ну борги так-то и задуманы быть машиной быстрой. Так значит надо ей это позволить. Ибо изначально хирург борг уже узкоспециализирован на хирургии, потому борг > человек по части операций.

**Comment by MrMagick2104** [comment]
> либо просто баффом скорости снятия одежды быстрее раздевать хуманов для операции

Тут, главное, не переборщить, а то будут хирургические борги прям в бою с врага портки снимать, вместе с бронежилетами и оружием.

**Comment by ZerlGray** [comment]
Ржу если реально кто то сделает баф к скорости и у нас и правда появятся армии боргов-раздевальщиков.

**Comment by TapKo4eB** [comment]
Good thinking. Инструмент или бафф будет работать только если пациент лежит.

**Comment by TapKo4eB** [comment]
А, стоп. Мы же уже придумали сделать инструментам борга обход одежды.

**Comment by ZerlGray** [comment]
> Good thinking. Инструмент или бафф будет работать только если пациент лежит.

>нюкер упал
>быстро проводишь ему операцию по вырезанию печени

**Comment by Epicus7** [comment]
Пофикшено в #1369.
