### ISSUE TITLE
Поставьте на один из серверов новотг

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#1453]
И можно допилить его до состояния серьезного билда.
На тг в разы красивее код и больше юзабилити для игроков. 
Бей представляет собой спагетти ебаное.
Допилить тг до состояния мрачности и серьезности в разы проще, чем сделать беебилд рабочим и постоянно не разваливающимся.
Ну и наверное, самое главное, тгбилд просто проще поддерживать. 
У вас регулярно умирают и оживают кодеры. Чому бы не иметь билд который кодить можно даже если ты вообще раньше особо не сталкивался с ним?
Тем более у вас есть два сервера.

**Comment by Srankl1n** [comment]
не поставим) не переносим мемное тг) ты че там мемы на каждом шагу)

**Comment by ZerlGray** [comment]
Вырезать мемы проще, чем оживить то, у чего через раунд контроллеры отваливаются.

**Comment by Srankl1n** [comment]
ну все равно не поставим

**Comment by MrMagick2104** [comment]
> на один из серверов

> Ну и наверное, самое главное, тгбилд просто проще поддерживать.

На поддержку текущего билда уходят все силы, но он, так скажем, звёзд с неба не хватает. Если ещё и параллельно надо будет со вторым билдом разбираться, то первый вообще на дно уйдет.

P.S. Хотя, я бы посмотрел, что из этого выйдет.

**Comment by ZerlGray** [comment]
> > на один из серверов
> 
> > Ну и наверное, самое главное, тгбилд просто проще поддерживать.
> 
> На поддержку текущего билда уходят все силы, но он, так скажем, звёзд с неба не хватает. Если ещё и параллельно надо будет со вторым билдом разбираться, то первый вообще на дно уйдет.
> 
> P.S. Хотя, я бы посмотрел, что из этого выйдет.

Будто бы уже не ушел :С
Там из раунда в раунд билд делает клевые кульбиты.

**Comment by MrMagick2104** [comment]
Если тг настолько лучше, то зачем нужен будет бей? Будет бесполезным аппендиксом, который только занимает место и время <s> как сейчас мейн </s>.

Менять, так уж всё, иначе выйдет полумера.

А если менять всё, то целевая аудитория поменяется слишком резко, из-за чего сервер недееспособен станет, очевидно почему.

**Comment by ZerlGray** [comment]
Ну часть людей в любом случае выберет бей.

**Comment by MrMagick2104** [comment]
> ЦА зависит не столько от билда же, сколько от атмосферы.

Большая часть текущих игроков - относительные новички, которые ни на одном другом билде, кроме бея не были _(иронично)_. Они уже чуть-чуть свыклись с местной обстановкой и механиками, но заново проходить период обучения они не захотят. Не будет этого, они пойдут на похожий беесервер, потому что ничего, кроме знания механик, их тут не держит.

Спорные решения - хорошо, конечно, потому что результат может быть приятен для атмосферы, для кодеров, но каждое такое решение - гвоздь в крышку гроба ещё свежего трупа онлайна.

**Comment by ZerlGray** [comment]
> > ЦА зависит не столько от билда же, сколько от атмосферы.
> 
> Большая часть текущих игроков - относительные новички, которые ни на одном другом билде, кроме бея не были _(иронично)_. Они уже чуть-чуть свыклись с местной обстановкой и механиками, но заново проходить период обучения они не захотят. Не будет этого, они пойдут на похожий беесервер, потому что ничего, кроме знания механик, их тут не держит.
> 
> Спорные решения - хорошо, конечно, потому что результат может быть приятен для атмосферы, для кодеров, но каждое такое решение - гвоздь в крышку гроба ещё свежего трупа онлайна.

для освоения тг проще, перейти с тг на бей действительно сложно, но с бея то на тг - основные механики в разы проще и, что наверное главное, естественнее. Много разных окошек интерфейса, интуитивно более понятное все.

**Comment by ZerlGray** [comment]
Чтобы заценили:
Вчера в раунде отвалился атмосконтроллер, а слаймы улетели в космос размножаться и отказываясь умирать. В итоге основали колонию в размере ~ 10-30 особей под ксенобиологией в космосе, и неплохо так летали по космосу.
Тем временем люди могут пол часа лежать расстреляные из каких нибудь буллапов, из за охереннейшего механа смерти мозга, который все еще работает через жопу, а могут рипнуться от одной пульки, будучи в броне.

Как вариант - вместо впила и фиксов провести месяц-два редизайна кода под то, чтобы его в принципе можно было трогать руками, ибо из за желания бейцев унифицировать код под каждую левую хуйню, они сделали такое спагетти, из за которого одной строчкой можно наебнуть в принципе пол билда. При том зачастую две разные фичи которые работают примерно по одним принципам в игре, в коде реализованы абсолютно по разному, и что там, что там - сверхусложненным способом, чтобы никто кроме тех кто оное трогал руками, переделать там ничего не смог.
Лулзов ради посмотрите код РЦД например. Или организацию кода активации абилок мага. Это нечто абсолютно прекрасное, ящитаю. Каждая фича делалась "с заделом на будущее", и не одна практически ни у одной из них дальше "задела" не пошло.

**Comment by Epicus7** [comment]
Иссуй не касается билда.
