### ISSUE TITLE
Бафф брони против огнестрельного оружия

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1455]
### Улучшение
Есть такая проблема, что практически никакая броня не защищает от огнестрела, даже от мелкокалиберного, вроде 9мм. Буквально недавно проверял, сквозь боевую броню ОБР (равноценна тактическим бронеплитам из арсенала, вроде бы) можно пробить человеку артерию из 9мм холдаут пистолета с глушителем с ОДНОГО ВЫСТРЕЛА. Нюкерская броня вообще из фольги сделана.

### Решения
1) Пороги урона. Если урон ниже определённого порога, то он пройдёт не по человеку, а полностью уйдет в саму броню, нанося ей урон. Если "здоровье" брони равно нулю, то она "ломается" (условно), после чего её резисты падают в n раз (где-то в районе от 1 до 1,5), а также поглощение урона больше невозможно.
Пороги урона и хиты появляются, только если защита >= 30% или около того.
Нужно решить, надо ли добавлять способы ремонта брони и бронеплит. Если надо, то лучше всего это реализовать через отдельную машинерию, чтобы нельзя было прямо в бою, допустим, прикладывать горелку к броне и чинить её или что-то такое.
2) Уменьшить вероятность попадания в органы/артерии через броню.
3) Значительнее снижать урон по внутренним органам.

**Comment by Srankl1n** [comment]
прикрепи сюда защиту от стаггеров еще

**Comment by MrMagick2104** [comment]
Это в отдельный иссуй надо, не?
Иначе свалка получится.

**Comment by Srankl1n** [comment]
у нас броня на билде не работает, какая свалка)

**Comment by Srankl1n** [comment]
или ты думаешь про стаггеры при переломах?
просто когда в тебя попадают, у тебя пидорасит экран, ты не можешь кликать и, вроде как, ходить

**Comment by MrMagick2104** [comment]
Что за стаггеры вообще?
Иссуи надо по проблемам разделять, даже если они связаны, чтобы, если кто-то захочет взяться за один из иссуев, ему не нужно будет решать второй автоматом.

**Comment by Cinericius** [comment]
Да

**Comment by Epicus7** [comment]
@Cinericius, что "да"?

В иссуе описано три разных варианта. Какой конкретно кодить?

**Comment by MemoryDreams** [comment]
@Epicus7 это не три разных варианта, это всё часть одного предложения. Кодить всё.

**Comment by Epicus7** [comment]
Пофикшено в #2186
