### ISSUE TITLE
Гунчат не останавливает автоскролл при выделении текста

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1457]
Ну вот хочешь ты скопипастить смешное из чатика, а он сам продолжает скроллить.
И скроллить.
И скроллить.
И вот ты уже сотый раз пытаешься одно слово выделить, но он всё равно скроллится.
Верните как на старом чатике было, ей богу.

**Comment by MrMagick2104** [comment]
Не у всех эта проблема появляется, как я понял, может какие-то проблемы с версиями или что-то такое?

**Comment by TapKo4eB** [comment]
512 ежжи

**Comment by MrMagick2104** [comment]
Точно встречал человека, который говорил, что в гунчате таких проблем нет.
Сейчас перепроверил, 512.1477:
![chat](https://user-images.githubusercontent.com/58848742/74099810-75831c80-4b38-11ea-813a-32e156aecf19.gif)
В гостчате такой проблемы нет, в чате живых - тоже.

**Comment by TapKo4eB** [comment]
Ок, перепроверил.
Дело в том что если отмотать чат самому повыше, то он останавливается.
Но при этом если не мотать и всё равно выделить что-то, то он всё равно идёт вниз.
Слишком смешно, оставим как фичу.
