### ISSUE TITLE
Вернуть лолконверт культу

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#1460]
Сабж

**Comment by ZerlGray** [comment]
Интересно, через сколько люди смогут поменять целых 4 строчки в коде?
https://github.com/ChaoticOnyx/OnyxBay/blob/dev/code/game/gamemodes/cult/runes.dm

**Comment by Epicus7** [comment]
@Cinericius, и что это значит?

Нужно сделать так, чтобы руна конвертила моментально? Сейчас нужно согласие, а за отказ дамажит. От этой механики мы отказываемся и конвертим автоматически всех?

А чо по всяким там лоялистам? Их тоже конвертим моментально? Главы?

**Comment by Fritcher36** [comment]
А давай без хуйни? Как можно без особых проблем понять, за менее чем 10 юзов руны конверта человек либо входит в ряды культа либо превращается в головешку. Это интересный геймплейный процесс, а не вжух и ты в другой команде. У нас тут не зомби режим гаррисмода или кубача.

**Comment by MemoryDreams** [comment]
Я думаю, этот процесс можно было бы сделать интересней. По сути, сейчас это мало чем отличается от конверта под дулом рельсы.
Но лолконверт точно не нужен.

**Comment by Doster-d** [comment]
Может сделать отдельной руны?
