### ISSUE TITLE
ПКМ по большой куче предметов может создать много проблем

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1477]
### Описание бага
Если ты ПКМнешь по какой-нибудь куче руды после трёхчасовой работы шахтёров или деталей из протолата, то клиенту или даже серваку наступает пиздык.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем педали
2. Открываем спавнпанель
3. Включаем автокликер и щитспавним десять мильёнов тыщщ айтемов
4. ПКМ
5. RIP

### Ожидаемое поведение
Хотя бы ошибку возвращать, если слишком много предметов на квадратный метр. Всякое говно, которое часто встречается в больших количествах в виде руды, деталей из протолата и гильз, можно было бы стакать.

**Comment by vekotov** [comment]
Единственное решение - стакать, так как лично я не видел билдов где смогли этот фокус с отключением ПКМа провернуть. Пиздык наступает только на клиентской части, просто винда охуевает от построения контекстного меню на 50+ кнопок.

**Comment by MrMagick2104** [comment]
> Пиздык наступает только на клиентской части

Возможно, серверу бывает плохо просто от большого количества отдельных предметов? Потому что на практике очень часто бывает, что после заценивания такой горы предметов, на сервере начинаются (не)продолжительные проблемы с доступом, хотя, возможно, это всего лишь совпадения.
Выдержка из ООКа вчерашнего раунда на мейне:
> OOC: SSSSAAAANNNNEEEESSSS: Кликнул правой кнопкой по огромной куче-упал сервер

Ещё существует такая вероятность, что в обычном состоянии серверу посрать на вот эти все зырканья на кучу, но, из-за кривой оптимизации в долгосрочной перспективе, на мейне это вызывает куда большие проблемы.

**Comment by Epicus7** [comment]
В 513 оптимизировали ПКМ-меню. Нужно обновить сервер и после обновы проверить актуален ли баг.

**Comment by MrMagick2104** [comment]
Действительно. Проверил на локальной версии (Client Version: 513/Server Revision: 1485f774c86d6d75e0121ede37926de63e0199ca - dev - 2020-06-06/Game ID: b8i-cvYD), от контекстного меню на 50 предметов пролагало меньше, чем на секунду.
Хотя от условной тысячи предметов вполне можно впасть в минутный пролаг, я не думаю, что это критично, так как в игре такие количества предметов встречаться всё равно не должны.
Можно закрывать иссуй, я думаю, хотя стоило бы на текущей посмотреть.
