### ISSUE TITLE
Усилить температурную пушку из научного

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1479]
### Улучшение
Она просто бесполезная. Абсолютно. Ей даже нельзя температуру в комнате понизить, не говоря уже там о каком-то вредоносном эффекте изменения температуры тела.

### Решение
Повысить эффективность охлаждения/нагревания пушки, чтобы ею можно было пожары там тушить, или материю, или переохлаждение людям накидывать.

**Comment by Fritcher36** [comment]
А ты её насколько разгонял? С полным разгоном она емнип как лазган дамажит.

**Comment by MrMagick2104** [comment]
> С полным разгоном она емнип как лазган дамажит.

Она вообще урона не наносит, а только меняет температуру тела на минус пять градусов или околого того, что довольно бесполезно.

**Comment by MemoryDreams** [comment]
Нужно проверить.
