### ISSUE TITLE
Починить заикание

### ISSUE THREAD

**Issue by WhityTaty** [ChaoticOnyx/OnyxBay#15]
Заикание на кириллице не работает, не канон, нужно починить. 
Mike Anderson stammers, "Больно."
Mike Anderson stammers, "T-t-t-h-h-a-t h-h-u-r-t-t."

Точное самое и с синтетикой, а точнее киборгами, при поломке Радио сообщение от Киборга должно выглядеть неразборчиво. Например так:
Cyborg states, "О;**р%*ы $о*;е#н,я!

**Comment by PlinHost** [comment]
https://github.com/ChaoticOnyx/OnyxBay/blob/581549500825caf20f2611a3e7720cb47b6202c0/code/modules/mob/mob_helpers.dm#L243

**Comment by LagannPM** [comment]
я могу занятся, но как тестить ? как эффект воспроизвести ?

**Comment by mihailtyutkin** [comment]
Просто пропихнуть еще один лист с кириллицей не выйдет. ckey() режет кириллицу, а без него начинает пропускать знаки препинания

**Comment by Cinericius** [comment]
Фиксед
