### ISSUE TITLE
Мерж с богомерзким беем

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#151]
Короче я открыл чейнджлог Бея и посмотрел чо там у них появилось с нашего последнего мержа (который был аж 19 марта). Чессгря, давно так не орал, делать с ними полный мерж - себя не уважать, но кое-что (и на самом деле довольно много в абсолютных значениях) попиздить черри-пиком можно. Ниже прилагаю ссылку на список того, что стоит спиздить:
https://pastebin.com/S85JBXPF

**Comment by Epicus7** [comment]
Ну это все мержить в один присест - все равно сложно. Надо бы разбить по месяцам и сделать отдельные иссуи, чтобы проще было.

**Comment by Epicus7** [comment]
Тут же помимо того, что ты нашел в чейнджлогах еще багфиксы есть (смешно конечно, но вдруг?).

**Comment by Cinericius** [comment]
Там как минимум часть фиксов есть в чейнджлоге. Вообще он странный и вызывает ощущение, что в нем некоторые вещи пропущены, но да ладно.

А так, собсно, чо там разбивать-то, все обновки помечены датами.

**Comment by Epicus7** [comment]
Смысл в том, чтобы ни одним ПРом это все заливать, а не 6-ю отдельными (или сколько там месяцев?). Плюс обсуждать проще будет, если все изменения будут прямо здесь, а не на текстбине и не такой большой пачкой

**Comment by Cinericius** [comment]
Ну можно тут обсуждать, а заливать даже не шестью, а сколькими угодно. А иссуй этот просто не закрывать после первого же ПРа.

**Comment by Cinericius** [comment]
Короче в пизду этот мерж на самом деле, пойдем своим путем, а если совсем припрет что-то спиздить, то спиздим таргетно.
