### ISSUE TITLE
Баланс астеройда

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#153]
Шахтёрам нужны таблетки которые стабилизируют температуру тела и топливный бак для починки скафандров

**Comment by Epicus7** [comment]
Какие еще таблетки? Зачем они им?

**Comment by YaridaTheDragon** [comment]
Вам, блять, не таблетки нужны, а полное оказуаливание уже нынешней шахтерки. Беемед и ссаные спектаторы - это несовместимые вещи. Сегодня у меня на руках обмороженный чел раза впал в клин. смерть от боли. Даже оксикодон\трамадол не помог. Либо сносите половину мобов, либо сносите шахтерку нахуй.

**Comment by Epicus7** [comment]
Ну он же не сдох.

Таблетки заказывайте у химиков, сложно что ли?

**Comment by YaridaTheDragon** [comment]
Ну это уже чистое охуение. Что там ещё шахтерам нужно? Если вы ломаете БЭЙСКИЙ баланс с БЭЙСКОЙ медициной, то либо чините этот баланс выпиливанием, либо закидыванием медикаментов. Серьезных.
Я повторюсь, у меня челик от пейна сдох три раза, хотя по нему просто спектатор попал (или кто там морозит)

**Comment by hekko4** [comment]
Можно спектру уменьшить охлаждение... А то оно ахуело слегка, что аж до абсолютного нуля доводит температуру тела.

**Comment by Epicus7** [comment]
Ох уж этот Бейский баланс, который мы сломали...

**Comment by Cinericius** [comment]
Спектаторы редкие, скорее всего направо-налево фризят василиски. Можно понерфить фриз, в принципе-то.

**Comment by Cinericius** [comment]
В общем надо баки с водой и топливом на шахтерку. А таблеточки можно положить в вендор.
