### ISSUE TITLE
Шляпа слетает с вас при падении

### ISSUE THREAD

**Issue by IvanDonFon** [ChaoticOnyx/OnyxBay#1530]
### Улучшение
При падение с вас слетает шляпа

### Решение
При падение - если это шляпа, которая никак не закреплена(маска для сварки и т.д) - она с вас слетает

**Comment by MemoryDreams** [comment]
Ну, почему бы и нет. Придется сделать два подкласса шапок: слетаемые и нет. Всякие шлемы и прочие важные штуки, понятное дело, слетать не должны. В некоторые шапки стиля типа широкополых гляп, цилиндров и береты, пускай падают.
@IvanDonFon пересмотри весь список шляп и напиши в закрепленном сообщении, какие из них должны слетать, а какие нет. 
Почему мы это не сделаем? Так ты фичу хочешь. Соизволь приложить усилия для неё. Лично я и, пожалуй, многие, кто так или иначе будут этим заниматься, спокойно проживут без слетающих шляп.

**Comment by koronoshka** [comment]
А обезьяна на голове слетает или нет?

**Comment by MemoryDreams** [comment]
А ты ирл когда падаешь с ребенком на плечах, он слетает или нет?

**Comment by koronoshka** [comment]
Ну это же макака
