### ISSUE TITLE
Нимфа не может дропать предметы

### ISSUE THREAD

**Issue by danxnader** [ChaoticOnyx/OnyxBay#1536]
### Описание бага
Нимфа не может класть предметы, которые сама-же и подобрала.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Спавнимся за нимфу.
2. Берём любой маленький предмет.
3. Нажимаем expel, дабы вырыгнуть итем обратно на белый свет
4. Сообщение в чате, что якобы диона выплюнула предмет, но он всё ещё в руке.

### Ожидаемое поведение
Предмет должен был выпасть.

### (Опционально) Дополнительная информация
Проверено на локалочке.

![22112](https://user-images.githubusercontent.com/55185311/74855872-4ea3c200-5352-11ea-8922-3e2fd547c317.png)
![2123](https://user-images.githubusercontent.com/55185311/74855878-506d8580-5352-11ea-886b-de4b086d07bc.png)

**Comment by TapKo4eB** [comment]
ёбаный в рот кто так хуёво портировал этих дион что у нас ни expel ни дроп хелд айтем не работает

**Comment by TobyThorne** [comment]
Исправлено во время ревертов-хуевертов.
