### ISSUE TITLE
Спрайты для бумбокса

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1540]
Нужны следующие спрайты для бумбокса:

1. Базовая иконка
2. Оверлей проигрывания (анимация вроде басов или другой красивый эффект)
3. Оверлей вскрытой крышки
4. Отдельный оверлей батарейки, который будет накладываться поверх оверлея открытой крышки.
6. Бумбокс в руке. 4 направления. Не забыть, что у тонкотрапов руки ближе к центру тайла.

**Comment by TapKo4eB** [comment]
![image](https://user-images.githubusercontent.com/48761132/74909928-5f901a00-53ca-11ea-908b-8ce5f6901a32.png)

**Comment by Epicus7** [comment]
Армолитский сделал.
