### ISSUE TITLE
Логирование координат всех действий игроков

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1542]
### Улучшение
приделайте ко всем сейлогам, комбат логам и всем действиям игроков координаты
затем налепите софт с картой станции, импортируй логи и смотри где всё общение и действия происходили по временной шкале

Да, хуета полная, может даже не реализуемая, но гипотетическое её наличие существенно бы упростило всю работку.

**Comment by HonkyDonky** [comment]
Лол-к, недавно думал о такой параше.

**Comment by Fritcher36** [comment]
Если вы хотите окончательно задушить сервер лагами - можете еще прикрутить трату стамины за каждый шаг и её реген каждый тик. Каждому мобу.

**Comment by TapKo4eB** [comment]
>Если вы хотите окончательно задушить сервер лагами - можете еще прикрутить трату стамины за каждый шаг и её реген каждый тик. Каждому мобу.

Неужто координаты в логах настолько будут грузить сервак?

**Comment by Fritcher36** [comment]
> 
> 
> > Если вы хотите окончательно задушить сервер лагами - можете еще прикрутить трату стамины за каждый шаг и её реген каждый тик. Каждому мобу.
> 
> Неужто запись координат в логах настолько будут грузить сервак?

Мы обсуждали парс слов на предмет самых банальных ошибок/запрещенных слов где-то месяц назад, сошлись на том, что это утопит сервер нахуй. Идея охуенная, но у меня есть подозрения, что будет топить сервер. Особенно учитывая тот факт, что без выпуска обновы на лайв проверить нажор не особо выйдет. Можно попробовать, но при введении нужно держать руку на пульсе плюс нужно ж тогда сделать и софт, которым это всё можно читать. Сами коорды тоже неплохо, но я уже представляю педалей, которые будут разбирать логи с открытым ДМ и бегать по карте ручками.

**Comment by TapKo4eB** [comment]
>плюс нужно ж тогда сделать и софт, которым это всё можно читать.

весь этот пост про это

**Comment by Fritcher36** [comment]
> 
> 
> > плюс нужно ж тогда сделать и софт, которым это всё можно читать.
> 
> весь этот пост про это

Сохранение координат в логах и отдельная софтина для отображения этих координат - это две разные вещи разного уровня сложности. Если вязать их в одно дело, то пока не найдется человек, который возьмется за софт - коордов мы не увидим.

**Comment by quardbreak** [comment]
https://github.com/yogstation13/Yogstation/pull/7070

**Comment by TapKo4eB** [comment]
если от этого не сломается сервер, то оно нам надо.

**Comment by Epicus7** [comment]
Не нужно без адекватного способа воспроизведения/просмотра.

А над таким способом нужно думать. ПР на Йогстейшен выглядит прикольно, но держу пари там есть проблемы с воспроизведением + логи по 50 мегабайт вызовут проблемы со стороны хоста.

**Comment by TapKo4eB** [comment]
>  но держу пари там есть проблемы с воспроизведением + логи по 50 мегабайт вызовут проблемы со стороны хоста.

Пока не проверишь - не удостоверишь

**Comment by Epicus7** [comment]
#1577 более корректный иссуй на ту же тему. Этот закрываю.
