### ISSUE TITLE
Лазерный скальпель

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#156]
Лазерный скальпель не может отделить органы от тела.Протещено на самом простом из них

**Comment by hekko4** [comment]
Я же сказал, что лазерный скальпель только вырезает орган, чтобы вытащить нужно ещё и гемостатом пройтись. Не создавай больше ложных иссуев.

![image](https://user-images.githubusercontent.com/29167103/44911146-84a05100-ad2e-11e8-9184-274ce8c99d73.png)
