### ISSUE TITLE
Лечения у магов слишком слабое.

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#1567]
### Улучшение
Сейчас ни одно заклинание мага, направленное на лечение, не может избавить его от внутренних повреждений и переломов, что делает открытую игру за магов довольно неудобной, поскольку один удар по голове и ты можешь откинуться в течении 10 минут без возможности что-либо сделать.
### Решение
Добавить лечение внутренних повреждений заклинаниями мага.
### (Опционально) Альтернативы
Добавить более сильные версии этих заклинаний, способных исцелять такой дамаг.
Или предмет...

**Comment by Voldirs** [comment]
Уже есть же
Cure Major Wounds
При прокачке, восстанавливает кровь, насыщение крови, лечит органы, моск, выводит радиацию, токсины, лечит оба вида физического урона. Это и так дохуя уже.

Очевидно есть только у хилера

**Comment by Srankl1n** [comment]
предлагаю открутить отхилл магам чтобы они аккуратнее играли

**Comment by Voldirs** [comment]
Да хилера и так никто не берёт, похеру. А обычная хилка она почти бесполезная

**Comment by Srankl1n** [comment]
о, кстати, в предметом нормальная идея. можно будет просто открутить заклинание и дать им предмет для хилла, чтобы его можно было забрать у васяна который постоянно абузит лечение при любом ранении

**Comment by MemoryDreams** [comment]
Предлагаю добавить магу артефакт, что-то типа лечебного эликсира. Это будет обычный сосуд с жидкостью, которая интенсивно лечит все виды урона, вравляет кости, насыщает кровь и выводит радиацию.
Во фляге будет 60 единиц жидкости. Одна ежиница жидкости хилит две единицы каждого вида урона, выводит столько же радиации и, если разом выпить единиц 15, то лечит кости.
Нужна проверка на уровень крови и, если крови меньше, чем 80%, то напиток восполняет кровь точно так же, как это дедает нанокровь, только прямо из желудка.

Что думаете? Кто у нас в медицине шарит, не слишком имбово будет?

**Comment by TapKo4eB** [comment]
ну хер его знает надо кодить и проверять. а затем уже докручивать.
но учитывая что вообще жижа лекает по наличию в крови ор нот
можно попытаться ей сделать хил большой, но метаболизм быстрый, или наоборот
А заживление костей/артерий можно пропихнуть через овердоз

**Comment by MemoryDreams** [comment]
> А заживление костей/артерий можно пропихнуть через овердоз

Вот это хорошая идея. А в бульонде невозможно разве сделать проверку на уровень крови, когда кушаешь?

Так-то неплохо было бы сделать это этаким овербаффнутым докторс делайтом здорового человека (пока бэевцы его не занерфали).

Мне нравится идея напитка с точки зрения геймдизайна, потому что оно мощное, но не бесконечное, в отличии от простых хилок у мага. Было бы идеально прикрутить это именно к жидкости.

**Comment by TapKo4eB** [comment]
так в том и прикол что та же жижа нутриментов в еде (а еда напомню это контейнер с жижей) каким-то чудом поднимает блоод вессел
соответственно поколдовав можно заставить это бухло поднимать уровень

**Comment by MemoryDreams** [comment]
Сможешь сделать, если что?

**Comment by TapKo4eB** [comment]
в душе не ебу если время вообще появится чтобы разобраться с этим, если я не начну с еамсом ибаться
скорее всего нет, но кто его знает
а вообще визардов бы сделать ивентом на нескольких человек чтобы кто-то брал хилера и всё было хорошо

**Comment by MemoryDreams** [comment]
Окей, я понял. Тогда, пишу диздок и аппруваю, пусть кодеры кодят.

**Comment by Voldirs** [comment]
>Что думаете? Кто у нас в медицине шарит, не слишком имбово будет?       1 hour ago

>аппруваю          44 minutes ago

Чего бляяяядь?

**Comment by Voldirs** [comment]
Да идите нахуй)))))) Сука, у шизарда 3 вида телепорта, у одного вида шизарда есть очень мощный хил, а тут ещё и артефакт предлагают, который делает по сути то же самое))))))))))))))))))))))))))) И ещё всё же бесконечным потому что можно фармить очки у шизарда))))))) Короче нахуй и в пизду такой геймдизайн, просто нахуй, один геймдиз лучше другого

**Comment by MemoryDreams** [comment]
А что ты предлагаешь?

**Comment by Voldirs** [comment]
Ну смотри, я бы предложил либо оставить всё как есть, а сейчас по хилу я считаю у визарда всё нормально, если ты не хилер, то обычная хилка лечит только обычный физический урон, если огребаешь пульку то изволь найти помощника, благо есть даже контракты и можно брать учеников. Если ты хилер, то прокачанный мажор хил и так поможет с большинством этих проблем.
Иссуй вообще некорректный, у визарда ЕСТЬ возможность исцелять внутренние органы
Если рассматривать этот эликсир, то его ни в коем случае не должно быть в книге мага потому что тогда люди просто будут брать его за счёт накопившихся очков и всё, тут уже не будет никакого ограничения по количеству этого эликсира, который визард сможет приобретать.
Как вариант можно сделать этот эликсирчик лотереей. Дамаг то он вылечит, но с возможностью интересных побочек. Например пусть он сможет накинуть рандомный вирус. Или понемногу возвращать весь урон, который вылечил. Или вызвать зависимость от этого эликсирчика. Но это сложно реализовать

**Comment by Shabat-Sholom** [comment]
Хил у магов не лечит совершенно, открою тайну. Ни органы, ни брут с бёрном. Единственный рабочий хил - сакрифайс. Прекрасный акт альтруизма, фактическое самоубийство.

**Comment by kreeperHLC** [comment]
Сам же и сделал в #4348
