### ISSUE TITLE
У рефитнутых скафандров отсутствуют уникальные спрайты на теле

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#157]
- У рефитнутых скафандров отсутствуют уникальные спрайты на теле.
- Фауна спанятся прямо возле аванпостах, лишая шахтеров спокойной жизни.

**Comment by LagannPM** [comment]
Создавай отдельные иссуи для каждого бага в следующий раз.
По крайней мере не кидай несвязанный баги в один

**Comment by Epicus7** [comment]
> Фауна спанятся прямо возле аванпостах, лишая шахтеров спокойной жизни.

Это не баг, так и было задумано. Нужно создавать отдельную иссую с предложением улучшить алгоритм спавна крипов.

> У рефитнутых скафандров отсутствуют уникальные спрайты на теле.

Какие "уникальные спрайты"?
