### ISSUE TITLE
Вы можете видеть названий тайлов когда в коме

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#1570]
### Описание бага
Вы можете видеть названий тайлов когда в коме
### Воспроизведение
Падаем в кому.
Наводимся на блок 
Смотрим в нижний левый угол
### Ожидаемое поведение
Дядя, ты в коме! Вы не должны ничего различать.
### Скриншоты
![image](https://user-images.githubusercontent.com/20579256/75119617-90f03a80-5695-11ea-8041-9de364145a8c.png)

**Comment by MemoryDreams** [comment]
Так это же фича. Нет?

**Comment by O0oMaximo0O** [comment]
Фича
