### ISSUE TITLE
Придумать как удалить авто активацию ревайва у генокрадов.

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1575]
### Улучшение
На текущий момент регенератив стазис у генок по окончанию процесса добавляет кнопку ревайва, которая казалось бы, должна давать генке выбрать момент для того чтобы встать и пойти.
Но нет, этот самый ревайв автоматом прокается через 10 секунд, по причине сломанности бьёнда и недоступности активации верба если ты находишься внутри другого объекта по типу сумки для трупов, морга, или и того и другого, я на самом деле не проверял.

### Решение
Придумать так чтобы можно было снять авто активацию и не возникало лишних проблем.

**Comment by MemoryDreams** [comment]
Ну, это скорее баг, чем улучшение. По идее, ревайв и должен работать по нажатию кнопки. Почему он делает это автоматически, если ты в чем-то?

**Comment by TapKo4eB** [comment]
Фикс фикса бага = фича.
И ты слегка не понял, оно авторевайвит ВСЕГДА. И делается оно по той причине что если моба поместить в объект, то у него могут сломаться вербы. Но это опять же надо удостоверить.

**Comment by Epicus7** [comment]
Когда генокрад умирает - мы добавляем ему верб ревайва. Проблема в том, что в бьонда баг, из-за которого верб не добавляется, если мою сидит в контейнере.

Поэтому собственно да, сделали костыль с автоматическим ревайвом.

Улучшение техническое, думаю плашка гейдизайна тут лишняя.

**Comment by Epicus7** [comment]
Идеи тоже не нужны) Надо просто убрать костыль и переписать код как-то.

**Comment by TapKo4eB** [comment]
Прогресс бар в интерфейс генки в качестве отображения процесса регенерации. С кнопочкой.

**Comment by ArmenianOnyx** [comment]
Оживите пожалуйста иссуй. Это очень нужна вещь, потому что убивается стелс. 
Когда ты пиздишься с кем то, тебя итак могут генкой обозвать, за то что ты сильнее, так и при регенирации ты тупо внезапно воскресаешь перед оравой СБ. Было бы приятно, еслиб тебя отмудохали и бросили где то, скрытно воскреснуть и убежать.

**Comment by Epicus7** [comment]
Вот ссылка на баг BYOND, кстати, чтобы не искать:
http://www.byond.com/forum/post/1833666
