### ISSUE TITLE
Портировать на Оникс Бей реплеер. 

### ISSUE THREAD

**Issue by MemoryDreams** [ChaoticOnyx/OnyxBay#1577]
### Улучшение
Сделать логирование всего на сервере, чтобы потом можно было просматривать раунды в режиме демонстрации, как это сделано в некоторых играх и что уже реализовано в ряде серверов Космостанции (но, конечно же не на Бэе).

Фича сложная, но очень нужная, так как навсегда преобразит судовые процессы и даст возможность пересматривать ужавшиеся раунды при желании.

**Comment by Zert0X** [comment]
Снимаю с себя, все пояснения и напутствие в #6010
Может быть после перерыва попробую повторно.
