### ISSUE TITLE
Пропажа интерфейса за киборгов

### ISSUE THREAD

**Issue by Shleld** [ChaoticOnyx/OnyxBay#162]
#### Описание проблемы
Пропажа интерфейса за киборга

#### Разница между реальным поведением и ожидаемым
Не должен пропадать интерфейс

#### Как воспроизвести проблему?
Перезайти в игру, если повисло изображение

#### Как долго известно о проблеме?

Больше четырех дней

#### Версия клиента, версия сервера и идентификатор игры

Client Version: 512
Server Revision: af700698d47c9686fc4e7db80cdb45c4f98a89a0 - release - 2018-08-31

#### Дополнительная информация

- [x] Проблему можно воспроизвести хотя бы один раз
- [x] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [x] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [x] Проблема случилась в недавнем раунде (прошло меньше недели)
- [x] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by Epicus7** [comment]
Ничего не понятно. Что ты сделал, чтобы зависло изображение?

**Comment by Shleld** [comment]
Ничего блять.
Я регулярно получаю такое зависание картинки, от этого помогает перезаход. Просто перестает работать.
В ахелп люди писали пару раз с таким багом за киборгов и какого-то решения этой проблемы нет.

**Comment by Shleld** [comment]
Да, использовал охранный визор.
Нет, до этого с этим я лично не встречался
