### ISSUE TITLE
Могу бить себя правой рукой по правой руке

### ISSUE THREAD

**Issue by sdwenwen** [ChaoticOnyx/OnyxBay#1623]
#### Дополнительная информация

- [ ] Проблему можно воспроизвести хотя бы один раз
- [x ] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [x ] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [ ] Проблема случилась в недавнем раунде (прошло меньше недели)
- [ ] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by TapKo4eB** [comment]
Диагноз баг.
Какой, не знаю.

**Comment by MemoryDreams** [comment]
Это очень смешной баг, чинить который никто не будет. Однажды я отрезал себе левую руку кусочком стекла в левой руке (я хотел порезать вены).

**Comment by MemoryDreams** [comment]
Думаю, можно закрывать.
