### ISSUE TITLE
Удалите уже ISSUE_TEMPLATE.md, он старый до жопы и люди умудряются его до сих пор использовать.

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1624]
### Улучшение
У нас бланковский иссуй темплейт берётся из ISSUE_TEMPLATE.md
И да, он написан ещё два года назад самим рампочем, имеет смешной чеклист, смешные комменты и в принципе в нём постоянно запутываются. Один из примеров подобного: #1623

### Решение
Стереть к чертям, у нас и так есть уже нормальные темплейты для багов и улучшений

**Comment by MemoryDreams** [comment]
Я напишу пошаговую инструкцию о том, как писать иссуи.

**Comment by TapKo4eB** [comment]
Не надо, уже и так есть.

**Comment by MemoryDreams** [comment]
Ссылочку можно?

**Comment by TapKo4eB** [comment]
*facepalm
![image](https://user-images.githubusercontent.com/48761132/75558878-8649f280-5a53-11ea-98e6-28887da4c7f4.png)
Наши иссуи темплейты УЖЕ являются инструкциями!

**Comment by MemoryDreams** [comment]
Нет, я не это имел ввиду. Я имел ввиду, как написать иссуй с продолжением или багом так, чтобы было понятно, что к чему. Меня жутко бесят иссуи по типу "добавьте что-нибудь, на ваше усмотрение".

**Comment by TapKo4eB** [comment]
> Меня жутко бесят иссуи по типу "добавьте что-нибудь, на ваше усмотрение".

Просто закрой #баги-и-предложения и оставь там лишь ссылку на гитхаб.
Поверь, поток говна сразу снизится.

**Comment by Epicus7** [comment]
> он написан ещё два года назад самим рампочем

Рампоч к репе практически не имеет никакого отношения. Этот шаблон я писал.

**Comment by TapKo4eB** [comment]
Ну удаляй, хрен ли.

**Comment by HonkyDonky** [comment]
себя удали ок
