### ISSUE TITLE
суицид с любого оружия без пуль поджигает и убивает вызывая код огнемёта!11

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1632]
### Описание бага
я инвалид сломал систему
https://github.com/ChaoticOnyx/OnyxBay/blob/b3ff4c1d9a0eb584d6574a20e1f3fb25f2283865/code/modules/projectiles/gun.dm#L393
пытался сделать из тайп инчембер, но тогда он ищет пули в огнемёте и не стреляет1

### Воспроизведение
убейся с тазера - загоришься

**Comment by HonkyDonky** [comment]
Пофикшено в https://github.com/ChaoticOnyx/OnyxBay/pull/1633
