### ISSUE TITLE
Разнерфать Bag of Holding

### ISSUE THREAD

**Issue by hekko4** [ChaoticOnyx/OnyxBay#164]
Разрешить ей поднимать более тяжёлые вещи. (Сейчас даже Egun нельзя)
Вернуть спавн сингулярности при запихивании одного boh'a в другой.

**Comment by Cinericius** [comment]
Оу йеа

**Comment by Epicus7** [comment]
Не надо спавн сингулярности.

1. Это была редкая фича, о которой никто не знал
2. Сингулярность не работает с з-уровнями нормально

**Comment by Cinericius** [comment]
Блет, точно, Z-уровни. 
Ну тогда просто ограничения на размер убрать, да.
