### ISSUE TITLE
Спрайты для оружия из археологии для отображения на персонаже

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#1652]
### Улучшение
На нынешний момент всё оружие из археологии использует спрайты обычных пушек, например,  егана, когда находиться на спрайте спейсмана. 
### Решение
Нарисуйте текстурки...
### (Опционально) Альтернативы
Нарисуйте несколько общих текстурок для пушек из археалогии.

**Comment by Epicus7** [comment]
А угнать ни откуда нельзя? На Бее, случайно, нету?
