### ISSUE TITLE
Баг с пластиной Голиафа.

### ISSUE THREAD

**Issue by Stalkeros2** [ChaoticOnyx/OnyxBay#166]
**Описание бага**
Шлем шахтёрского скафандра можно улучшить три раза одной пластиной Голиафа, при этом она даже после этого не удалится.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем пластину Голиафа.
2. Нажимаем три раза по шлему шахтёрского скафандра.
4. Получаем полностью проапгрейженный шлем.

**Ожидаемое поведение**
Нажал один раз, улучшил шлем, пластина исчезла.

**Характеристики**
 - OS: Windows 7
 - Версия клиента: 512.1442
 - Версия сервера: af700698d47c9686fc4e7db80cdb45c4f98a89a0 - release - 2018-08-31
 - ID игры: bV0-a6o8

**Comment by Epicus7** [comment]
@kreeperHLC, это баг? Или чо?

**Comment by Cinericius** [comment]
Фича
