### ISSUE TITLE
Замена хирургических инструментов ЕРТшных медиков на продвинутые.

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#168]
1. Насколько я заметил, ЕРТшных медиков редко берут, да и пользы от них не слишком много, с учётом их лекарств и так далее. Если им добавить один продвинутый хирургический наборчик для медика, они смогут хоть как-то помогать как экипажу так и членам своего же отряда, так как они, зачастую, дохнуть от _артериального_ не в силах себе помочь. Да-да, и инжекторы в костюмах не помогут, да и кости они не латают.

2. Кстати, возможно, это поднимет количество ЕРТ - медиков, но это не факт.

**Comment by Cinericius** [comment]
Можно
