### ISSUE TITLE
В декомпрессионной камере не происходит закачка воздуха

### ISSUE THREAD

**Issue by HonkyDonky** [ChaoticOnyx/OnyxBay#1684]
Тот что над хранилищем (Vault).

<details>

![image](https://user-images.githubusercontent.com/59123747/75775094-4f7d2080-5d62-11ea-9125-f466701dece3.png)

**Comment by dnivji** [comment]
Проверю на днях, скорее всего проблемы со слетевшими настройками насосов.

**Comment by Epicus7** [comment]
Еще актуально?

**Comment by hard-res3t** [comment]
Актуально. Воздух не откачивает и не закачивает.
