### ISSUE TITLE
Апдейт 1 марта сломал спрайты энерго оружек.

### ISSUE THREAD

**Issue by Lalagix** [ChaoticOnyx/OnyxBay#1686]
### Описание бага
С новым апдейтом 1 марта, с энерго оружиями случился баг, их визуал-модельки(спрайты) зависли ВСЕ на одном заряде. Хотя заряд на самом деле полный.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем бульонд.
2. Открываем его, следом Оникс.
3. Нажимаем "Играть" или наблюдать.
4. Находим любой энерго ствол, и видим что на нем визуально ОДИН заряд.

### Ожидаемое поведение
Должна быть полная визуальная шкала, при полном заряде. Но при ФИЗИЧЕСКОМ полном заряде в данный момент показывает ВИЗУАЛЬНО один заряд.

**Comment by HonkyDonky** [comment]
Пофикшено в #1646
