### ISSUE TITLE
Людей рвет от приема таблеток с большим количеством юнитов лекарства внутри

### ISSUE THREAD

**Issue by MemoryDreams** [ChaoticOnyx/OnyxBay#1689]
Знаете, когда у нас на сервере очень быстро что-то поглощать или пить, персонаж начинает блевать? Допустим, если выставить в стакане амаунт в шестьдесят и выпить, персонаж тут же начнём извергать желтые массы. Так вот.

Я предлагаю сделать исключение в этой киллер-фиче для медицинских таблеток. Какой смысл давать возможность положить в таблетку 60 единиц лекарства, если человек выплюнет содержимое через пару секунд? 

И какой тогда смысл в этих ваших таблетках, если практичней будет просто таскать с собой пачку банок нужных лекарств и по очереди, без КД вкалывать их себе прямо в вену? 

Я бы мог понять эту фичу, если бы таблетки якобы были гигантских размеров и их банально было бы сложно проглотить. Но это не так. Размер таблетки никак не меняется от её содержимого. 

К слову, неплохо бы прописать точно такое же исключение для бутылки "ничего" мима. Сейчас бы пить пустоту и блювать, потому что пьёшь слишком быстро, ага.

**Comment by Voldirs** [comment]
Исключение костыльным будет. Имхо тут надо желудок расширить ОЧЕНЬ сильно, например до 150. Либо вообще выпилить.

**Comment by MemoryDreams** [comment]
> Исключение костыльным будет.

Для таблеток - допустим, согласен. Но как быть с бутылкой воздуха у мима? Это же совсем бред какой-то.

**Comment by Voldirs** [comment]
Это не бред. Это исскуство! Кстати с ним можно коктейльчик делать

**Comment by MemoryDreams** [comment]
Какая у нас сейчас вместительность желудка?

**Comment by koronoshka** [comment]
https://www.youtube.com/watch?v=OA0asXeUgsU

**Comment by MrMagick2104** [comment]
> Какая у нас сейчас вместительность желудка?

30, если я правильно помню.

А ничего мима - не ничего (т.е. null), а напиток с названием "Ничего". Это не воздух.

**Comment by koronoshka** [comment]
![image](https://user-images.githubusercontent.com/58358430/75985129-c2220380-5efc-11ea-98bb-85f8d1c89a16.png)
 Вроде как больше. В коде желудка как органа написано что блюешь после 90

**Comment by MrMagick2104** [comment]
> Вроде как больше. В коде желудка как органа написано что блюешь после 90

Там, наверное, что-то ещё влияет. У меня как-то персонаж с одной чашки кофе блеванул, выпитой не залпом, с полным нутришном и без недавнего поедания чего-то.

Но 90 для желудка - ОЧЕНЬ мало. Даже пончик с кружкой чая не выпьешь.

**Comment by pro100Player** [comment]
Это уже совсем недавно на 90 подправили.

**Comment by MemoryDreams** [comment]
О, надо проверить. Если так, то иссуй можно закрывать.

**Comment by Epicus7** [comment]
Это, очевидно, баг. Что бы там в таблетку ни запихали, рвать от нее не должно. Та же фигня с бутылкой "ничего" мима.

**Comment by TobyThorne** [comment]
Произошли твики как желудков, так и реагентов.
