### ISSUE TITLE
Спрайты для научных шлемов скреллоты

### ISSUE THREAD

**Issue by KimihitoOld** [ChaoticOnyx/OnyxBay#1695]
### Улучшение
Скрелло-шлемы для научного скафандра в шахтёрке. Всё. Четко и просто.
### Решение
Моё решение проблемы прямо здесь. Не знаю где у вас там хранятся использующиеся файлы со спрайтами, да и в коде разбираться нету времени и желания, так что попрошу самим вставить куда надо. Если подскажете куда кидать и что править, чтобы сразу делать ПРки - буду благодарен.

![science helmet -skrell](https://user-images.githubusercontent.com/27325767/75854968-dba34c80-5e23-11ea-998b-3f6d1c33a6b8.png)
### (Опционально) Дополнительная информация

**Comment by MemoryDreams** [comment]
Прямо сюда залей спрайтики. Отдельно тут же можешь залить скриншот, как это будет выглядеть на персонаже (можно сделать посредством наложения).

**Comment by KimihitoOld** [comment]
К сожалению могу залить только фронтальный вид. Боковые спрайты скрелла не нашёл.
![image](https://user-images.githubusercontent.com/27325767/75883635-e545a800-5e55-11ea-9a5e-38a20e4ce49c.png)

**Comment by MemoryDreams** [comment]
Сойдёт.
