### ISSUE TITLE
Добавление новых имплантов.

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#170]
Чего-то роботехнике точно не хватает, и это имплантов для персонала. Я не прошу руки-лезвия из металла, или ещё чего похуже, а добавить пару новых плюшек, например: бронепластина вживляемая человеку в любую часть тела(защита как-никак), замена глаз на их подобие(иксрей глазики, термальные глазики), хотя и руку-лезвие я бы не прочь увидеть на этой сборке. Нагло, конечно, такое просить, да и долго делать, но попытка стоит того.

**Comment by Cinericius** [comment]
Можно еще трейты привязать к тем же глазам, щоб термалы, но с всратой цветопедерачей, например.

**Comment by Voldirs** [comment]
>с всратой цветопедерачей

ломаем глаза ин рил лайф, годный, хороший билд
Если делать термалы на минималках то пускай они показывают не всего моба, а тупо его силуэт беленький и чтобы экзаминить не получалось и чтобы имя не показывалось

**Comment by MrMagick2104** [comment]
Имхо, если заменять полный экзамайн моба на силуэт, то надо хотя бы ч/б фильтр поставить вместо красного, а то после сессии использования термалов глаза себе иногда вырвать хочется, цель средства оправдывать не будет.

**Comment by Voldirs** [comment]
Не спорю, эти ебаные светофильтры это что-то с чем-то

**Comment by Cinericius** [comment]
#1223

**Comment by Fritcher36** [comment]
На эрисе щас новая аугментика в процессе допила, можно будет оттуда взять.

**Comment by vsss412** [comment]
3 года ждём проработку, а её всё нет.
Любой желающий может подать иссуй с большей конкретикой, мы приветствуем это и очень ждём.
