### ISSUE TITLE
Ещё баланс астеройда

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#171]
*Временно понерфать всем мобам хп в три-четыре раза(особенно почините абилку Голиафа, она слишком быстро станит)
*Сделать скафандры прочнее в несколько раз.И я не про резисты.
*Завести в рнд бесконечный мешок для руды.
Пока всё что придумал.

**Comment by Cinericius** [comment]
От абилки вроде увернуться можно. Или в скафандре не получается?
Шахтерские скафандры укрепитт от мили-урона можно, да.
Бесконечный мешок в принципе можно, с теми же требованиями, что и Bag of Holding, но исследовать его все равно будут довольно долго.

**Comment by YaridaTheDragon** [comment]
Баг оф Холдинг достается на 10 минут при условии, что ресурсы будут заказаны сразу же.

**Comment by Stalkeros2** [comment]
1. У них и так мало хп, и ты ещё хочешь понизить? Про абилку Голиафа - не лезь на щупальца и дерись с ним в уже хорошо раскопанном месте, если он тебя застанил лучше отползать (перетаскивай свой спрайт на соседний тайл)
2. Не лезь в ближний бой, а лучше попроси огнестрел у глав или СБ.
3. Согласен, только пусть он будет не бесконечный, а на где-то двести кусков руды.

**Comment by Demisov** [comment]
Просто сделай голиафу хп меньше в два раза и сделай задержку перед абилкой секунду.И скафандр рвется слишком быстро, любой мою тебе его рвет кроме ваших саалапендр и легионов

**Comment by Cinericius** [comment]
Короче этот иссуй на самом деле скорее не нужен, чем нужен.
