### ISSUE TITLE
Реалистичная одежда.

### ISSUE THREAD

**Issue by Lalagix** [ChaoticOnyx/OnyxBay#1713]
### Улучшение
Например, на худи или подобных кофтах можно сделать не только застег. молнию, но и капюшон который будет скрывать лицо (Unknown).

### (Опционально) Дополнительная информация
Можно сделать как застег молнии, или как экип шлема на хардсьюте (РИГе).

**Comment by MrMagick2104** [comment]
Зачем?

**Comment by Lalagix** [comment]
> Зачем?

Я же сказал: для реалистичности. Мне кажется прикольно и круто.

**Comment by Lalagix** [comment]
> Зачем?

Тем более, это не мешает геймплею

**Comment by dominoCaesar** [comment]
Я уже представил половину станции в худи...

**Comment by TapKo4eB** [comment]
Уже есть, бтв на одной из худи капюшон.

**Comment by dnivji** [comment]
Уже есть.
