### ISSUE TITLE
Не работает рестарт после каскада

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1729]
### Описание бага
Тикер ты сука.
После прошедших пяти минут каскада происхид universe_has_ended = 1, но тикер не может завершить игру потому что вместо ожидаемого END_GAME_READY_TO_END стоит END_GAME_NOT_OVER.
И даже если этот реди_ту_енд проставить, и вызвать даже прок тикера, всё равно сервер не ребутнится из-за непонятно чего.
### Воспроизведение
Взорви каскад
@
пососи

**Comment by Shirlineyn** [comment]
Проверил, работает.

**Comment by Epicus7** [comment]
@TapKo4eB, говорят тут все работает, ты уверен, что баг актуальный? Возможно нужны какие-то ОСОБЕННЫЕ условия?

```
[17:46] Shirlineyn: Я затестил каскады и админский, и обычный
[17:46] Shirlineyn: И они завершают
```

**Comment by TapKo4eB** [comment]
полный шруг, может быть это завязано на стрёмной работе тикера во время лагов
но если данный иссуй самозарезовлился то его можно закрывать до наступления следующей такой же проблемы
