### ISSUE TITLE
Проблемы c wine

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#1730]
### Описание бага
Unhandled exception: page fault on read access to 0x0e4bd770 in 32-bit code (0x100b986b).
Register dump:

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берём устанавливаем линух
2. Хотим поиграть в сску, поэтому ставим wine.
3. Играем какое-то время нормально.
4. СМЭРТ

### Ожидаемое поведение
НЕ СМЭРТ

### Скриншоты
Если проблема может быть показана на скриншотах - прикрепите их.

### (Опционально) Дополнительная информация
Здесь можете описать любую дополнительную информацию, которая касается бага

### (Опционально) Характеристики
 - OS: : Linux Manjaro wine
 - Версия клиента 512.1488

**Comment by DeltaEpsilon7787** [comment]
Никакого отношения к билду это не имеет, проблемы с Бъондом -- проблемы самого Бъонда.
