### ISSUE TITLE
Нельзя вешать халаты детектива

### ISSUE THREAD

**Issue by Wuattt** [ChaoticOnyx/OnyxBay#1731]
### Описание бага
Четкое и понятное описание сути бага.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем .. красный халат
2. Тыкаем на деревянную вешалку детектива
3. 
4. Видим, что The coat rack has been hit by Kaylee Sanders with the red jacket. или The coat rack has been hit by John Marshall with the leather coat.

### Ожидаемое поведение
Должен вешаться

### Скриншоты
Если проблема может быть показана на скриншотах - прикрепите их.

### (Опционально) Дополнительная информация
Скорее всего, так со всеми халатами, кроме коричневого

**Comment by dominoCaesar** [comment]
Во первых, leather coat которым ты hit эту rack это кожаное пальто. Во вторых, оно должно было вешаться. Ты уверен что на вешалке уже ничего не висело? Туда вроде только одно повесить можно. И халаты туда вешаться вроде вообще не должны, потому что зачем.

**Comment by Wuattt** [comment]
Не вешается, было пустое. Coat - пальто

**Comment by TermService** [comment]
на деле прост нет спрайтов, там обычный дефективный вешается и халатик СМО вроде, будут спрайты будет вешаться

**Comment by Epicus7** [comment]
Почему на вешалку вообще можно повесить только детективное дефолтное пальто и халат СМО? Странная история.

Хз, что с этим делать если честно. На всю одежду спрайты задолбаешься рисовать.

**Comment by Primudash** [comment]
Пусть более свежий репорт останется
