### ISSUE TITLE
Final Countdown слишком тихий

### ISSUE THREAD

**Issue by Wuattt** [ChaoticOnyx/OnyxBay#1732]
В джукбоксе слишком тихий трек, надо сделать громче, как у мистера сендмана

**Comment by Epicus7** [comment]
Нужно тупо трек поменять на другую версию, более громкую.

**Comment by TapKo4eB** [comment]
Не, надо вообще все треки из жукбокса прогнать через прогу какую нить, дабы громкость уровнять.

**Comment by Epicus7** [comment]
Оно того не стоит, каждый раз прогонять задолбаешься. Мы меняем музыку довольно часто.

Просто именно Final Countdown тихая реально, я еще когда заливал заметил, но забил, ток тссс
