### ISSUE TITLE
Новое оружие в аплинк: камера-пушка

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#1735]
Добавляется новое оружие для трейторов в аплинк: пулялка, замаскированная под камеру. Можно сделать любой из этих вариантов: 
1) Камера-пушка (cam-gun) стреляет одной пулей определённого калибра.
2) Кам-ган стреляет 2-3 пулями определённого калибра.
3) Кам-ган стреляет дротиком/шприцом.

Цена: 20-30ТК.

Отличное оружие для библиотекаря-трейтора/журналиста-предателя.

**Comment by MrMagick2104** [comment]
Ещё нужны наручные часы с лазером, дымовые шашки, замаскированные под запонки пиджака, туфли-раскладные ролики, расчёска-нож, а также штука, которая при использовании будет оглашать: "Name`s Bond. James Bond."

**Comment by MemoryDreams** [comment]
>cum-gun

**Comment by Wuattt** [comment]
Туфлю-радио ещё можно сделать

**Comment by MrMagick2104** [comment]
Туфлю-аплинк.

**Comment by dominoCaesar** [comment]
![image](https://user-images.githubusercontent.com/52449263/76194909-3eb42b00-61f8-11ea-8fba-f22d4e67b761.png)

**Comment by koronoshka** [comment]
![image](https://user-images.githubusercontent.com/58358430/76196236-ea5e7a80-61fa-11ea-8657-83cc86fbd8d6.png)
Мне нужно срочно 130 мыл синдиката. Доставьте ASAP

**Comment by MemoryDreams** [comment]
Это, кстати, вопрос геймдизайна. Где плашечка?

**Comment by MrMagick2104** [comment]
Обычные смертные могут ставить только [БАГ] и [Улучшение].

**Comment by rxssxnbxrg** [comment]
**Всё что будет написано ниже - лишь моё скромное видение реализации.**

Камера-огнестрел? Выстрел производит слишком много шума и корпус камеры перегреется нанеся вред владельцу. Прорезиненные вставки же вызовут подозрения, ведь тогда это будет уже не _Camera_, а _Strange Camera_. 

Более реальное и близкое к идее автора - камера-пушка с дротиками/шприцами. Работает также как и шприцемёт/дротикомёт. Бесшумное и вполне практичное, а главное **скрытное** оружие для предателя. Вмещает в себя один дротик/шприц. Выходит из строя либо после первого выстрела, либо после второго.
