### ISSUE TITLE
Блобы-аутисты

### ISSUE THREAD

**Issue by Fox231** [ChaoticOnyx/OnyxBay#1736]
### Описание бага
Враждебные мобы атакуют очень не сразу.  Блобские споры после своего появления минуту стоят на одном тайтле и делают ничего. Только спустя где-то примерно минуту они очухиваются и начинают нападать на окружающих.
![image](https://user-images.githubusercontent.com/23282994/76205029-88a60c80-620a-11ea-8030-5c5c5d00e0af.png)

**Comment by NefrNerf** [comment]
Заканчиваем с иссуями по вырезанному блобу #4711

**Comment by NefrNerf** [comment]
Пнули, сказали, что блоб таки скорее жив
