### ISSUE TITLE
Переделать CPR

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1738]
### Улучшение
В текущий момент CPR это рулетка, где чёрное с красным это ничего, треть это запуск сердца а зеро это сломать рёбра.
На деле это достаточно смешно, и в случае если человеку хуёво до остановки сердца это мало чем может помочь, ибо упадёт заного.

### Решение
Сделать CPR не только поднимание сердца, а так же пополнение оксигенации крови, чем оно по сути и должно заниматься, дабы как раз не дать умереть мозгу.

**Comment by dominoCaesar** [comment]
дабафти ищо АИВЛ чтобы не надо было делать самому СЛР каждый раз...

**Comment by MrMagick2104** [comment]
Так оно уже делает:

>  if(!need_breathe())
> 						return
> 					var/obj/item/organ/internal/lungs/L = internal_organs_by_name[species.breathing_organ]
> 					if(L)
> 						var/datum/gas_mixture/breath = H.get_breath_from_environment()
> 						var/fail = L.handle_breath(breath, 1)
> 						if(!fail)
> 							to_chat(src, "<span class='notice'>You feel a breath of fresh air enter your lungs. It feels good.</span>")


>if(L)
						var/datum/gas_mixture/breath = H.get_breath_from_environment()

Конкретно вот это выше ⬆️ .
И да, СЛР на самом деле реально помогает, просто ею никто вообще не пользуется, т.к. считает, что она - юзлесс. У меня, вот, по скромному личному опыту, где-то четыре раза из пяти СЛР спокойно из крита пациента выводила, если это было в принципе возможно.

**Comment by TapKo4eB** [comment]
Я слепой.

**Comment by kcalbCube** [comment]
В жизни СЛР это важнейшая вещь. Даже если есть дефибриллятор. Но для того что бы его использовали, необходимо добавить больше состояний остановки сердца: фибрилляция желудочков, тахикардия желудочков, асистолия. При том дефибрилляция возможна только при тахикардии и с меньшим шансом при фибрилляции... Реворк асистолии кароче.

**Comment by kcalbCube** [comment]
А, бл, некроиссуй.
