### ISSUE TITLE
Спрайты питомцев

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1751]
Нужны спрайты нескольких вариантов питомцев. Сама идея питомцев описана в #1750.

Так как питомцы - донатерская фича, хочется, чтобы они выделялись на общем фоне. Поэтому для них нужны анимации ходьбы и стоячего положения.

Какие конкретно питомцы - не очень важно, тут все зависит от фантазии художника. Логика питомцам пока планируется максимально простая, но если будут интересные идеи, то можем реализовать это для конкретных питомцев.

Из того, что есть уже сейчас:
@MemoryDreams рисует черного кота. Пока work in progress.

**Comment by MemoryDreams** [comment]
Значит, анимация ходьбы таки нужна...

**Comment by Destrolaric** [comment]
Кто-нибудь нарисуйте кота из вахи, будет необычный пет донатерам
