### ISSUE TITLE
Пакет на голову

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#1752]
Идеальный головной убор, подходящий абсолютно всем, от ассистента до капитана!
![PaintDotNet_7WGBeBSCi0](https://user-images.githubusercontent.com/59237874/76368356-ad6dc180-637b-11ea-8774-0a1b4640d91a.png)

**Comment by Epicus7** [comment]
Нужно больше одинаковых иссуев (нет)

Дубликат #1146.
