### ISSUE TITLE
Убрать пакеты с нанокровью из медбея. 

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#1763]
Убрать нанокровь из медицинского отсека раундстартом. 

> Нанокровь слишком хороша, чтобы быть в шкафчиках раундстартом, есть и обычная кровь. Пусть работает химик или карго. К тому же, если убрать пакеты с нанокровью, может появится нужда в донорах.

**Comment by MemoryDreams** [comment]
Вообще-то мне нравится эта идея. Но есть одно но! Без крови люди же в самом деле будут умирать чуть что. 
Чтобы сделать такую штуку, нам как минимум нужен анализатор крови, который показывает группу крови, чтобы её можно было сливать с условных мартых.
Кроме того, на карте должно быть оборудование для приёма крови и место, где её нужно принимать. Нужна машинка по производству пакетов для крови, типа химмастера в химии, лишняя капельница. 
Также следует задаться вопросом, а кто и зачем будет сдавать кровь? Добрые самаритяне?
Нам нужна экономика, рыночек на станции, чтобы людям нужны были деньги. Тогда у них будет мотивация сдавать кровь. До того момента, мы просто лишаем отсек крови и вынуждаем их брать кровь из трупов. Что тоже довольно неплохо!

**Comment by Animesku** [comment]
Пакеты из пластика крафтятся

**Comment by MemoryDreams** [comment]
К сожалению, Оникс к этому ещё не готов. Поэтому, идею отложим до лучших времен!

**Comment by MrMagick2104** [comment]
> Чтобы сделать такую штуку, нам как минимум нужен анализатор крови, который показывает группу крови, чтобы её можно было сливать с условных мартых.

Так обычный стационарный анализатор показывает группу крови, не?
> должно быть оборудование для приёма крови

Не уверен, но, мне кажется, капельницей можно сливать кровь.

> До того момента, мы просто лишаем отсек крови и вынуждаем их брать кровь из трупов. Что тоже довольно неплохо!

Иссуй не про кровь, а про нанокровь. Обычную трогать не надо, это да, но вот нанокровь - херня чёт, зачем её раундстартом класть?

**Comment by MemoryDreams** [comment]
> нанокровь - херня чёт, зачем её раундстартом класть? 

Для ксеноты же. Что ты им без нанокрови вливать будешь?

**Comment by MrMagick2104** [comment]
А обычная кровь им не подходит?

**Comment by MemoryDreams** [comment]
Насколько я знаю, не подходит. У них, вроде, как раз таки нанокровь течёт по венам. Нужно проверить.

**Comment by koronoshka** [comment]
> Что ты им без нанокрови вливать будешь?
![image](https://user-images.githubusercontent.com/58358430/76541857-42181280-6495-11ea-8161-512057d9670a.png)

**Comment by MrMagick2104** [comment]
> У них, вроде, как раз таки нанокровь течёт по венам. Нужно проверить.

Обычная кровь у них течёт по венам. Тем более, у нанокрови начинается передоз со скольки-то юнитов.
![Cut](https://user-images.githubusercontent.com/58848742/76542503-22351e80-6496-11ea-8932-f6cee9640d10.PNG)

**Comment by MemoryDreams** [comment]
Ага. Ну тогда да, убираем нанокровь.

**Comment by Kexilex** [comment]
В первую очередь, я предлагал убрать нанокрови, чтобы стало на чайную ложку больше социалочки. Быстрее будет заказать нанокровь у химика или в карго, но можно будет и устраивать центры доноров. Пустые пакеты делаются из пластика, группа крови определяется в сканере ИЛИ спросить у персонажа, на крайний случай. Также особо ярые интегралщики смогут притащить свое устройство для переливания крови. 
И хочу обратить внимание на то, что в медбее 2 шкафчика с обычной кровью, которая там не просто так.

**Comment by Ruforce** [comment]
Господи, Господи Боже, вы опять полезли трогать медблок! Вас просили? 
На текущий момент времени наш билд всецело и полностью завязан на здоровье мозга, который, в свою очередь, завязан на оксигенации крови. При оксигенации меньше восьмидесяти процентов мозг начинает потихоньку помирать, заставляя айкью космонавта снижаться до уровня, на котором он не может ходить. Но это ладно. Это маленькая ремарка для кодеров, которые (не буду показывать пальцем, пусть оный сам выйдет из тьмы в конце второго акта, после звонка к антракту!) в игру играют раз в три года.

Для проведения одной операции по поднятию космонавта на ноги после, условного, пулевого ранения, которое задело магистральный кровоток, требуется не менее двухста юнитов крови - так уж вышло, так сложилось исторически. На сервере, в прайм-тайм, играет шестьдесят пять-семьдесят человек. Медиана раненых, из них, сорок процентов - кому влетела пуля в торс и ловким движением гравитации, полетала по всей плевральной, брюшной и зареберной полости, кто-то прикоснулся к божественному и подышал вакуумом, у кого-то случился алкогольный передоз от бутылки водки, выпитой менее чем за десять минут. Кто-то в очередной раз не смог поделить что-то с ближним своим и уебал ему баллоном до сломаного черепа. Втык в провод с мегаваттом в сети заставляет около тридцати процентов крови перейти из жидкого в парообразное состояние и покинуть организм вместе облаком табачного дыма.

Всем этим космонавтам требуется кровь. Много крови. Крайне много крови.  В медблоке, раундстартом, находится один пакет на триста шестьдесят юнитов крови каждой группы. Всё. 
Исходя из этого и моих расчетов выше - а мне можно верить, я до сих пор почётный главвраач этого уебанского отсека говна и трапов - на одного космонавта нужно полтора пакета крови.  Включим сюда человеческий фактор (ну, да, не все медики так круты как я или Шон Неггро), из-за чего кровь переливается за свой кап и, в принципе, теряется. Включим сюда то, что создание новых пакетов крови никак недоступно и, каким бы крутым ролеплеером ты не был, максимальный объем банка крови ограничен. 

Нанокровь,  в текущей итерации, вынужденное зло - как бы сильно она не ломала ролеплей, сколько интересных ситуаций она бы не губила, без неё любое повреждение, которое снижает ОЦК, просто-напросто смертельно. Без нанокрови шуссомедики, вскормленные молоком асесосеша, просто-напросто не смогут оказывать помощь на двадцатой минуте раунда.

Резюмируя. Ролеплей, Мемори, мой добрый друг - это прекрасно. Но ты выбрал не то место и не то время для того, что бы его воплощать в жизнь. Медблок - это не про "вот вам список рецептов, вот вам палата, отдыхайте", медбэй - это непрекращающийся поток раненых, каждому из которых нужна помощь. Таков уж фатум неофитов парацельсизма. Убирая нанокровь, ты, конечно, создашь пару интересных ситуаций - может быть, кто нибудь из шуссодетей, сможет сделать станцию переливания - но при этом, ты обречешь почти весь активный онлайн, который не дрочит работку в комнате три на три, а всячески взаимодействует между собой - влипать в чёрный экран, что никак не способствует продуктивному геймплею. Да, я пришёл сюда играть в симулятор космостанции, а не симулятор лечения в больнице.

Убирая нанокровь - да и вообще, всячески трогая баланс меда, в сторону _ухудшения_, ты провоцируешь игроков играть так, что они будут бояться проявить любую инициативу. Не будет больше пьяных драк, не будет больше охранного произвола. Станция превратится в убежище гемофилов.

**Comment by MemoryDreams** [comment]
> Убирая нанокровь - да и вообще, всячески трогая баланс меда, в сторону ухудшения, ты провоцируешь игроков играть так, что они будут бояться проявить любую инициативу. Не будет больше пьяных драк, не будет больше охранного произвола. Станция превратится в убежище гемофилов.

Мы оба знаем, что это не так. Пьяные драки, охранный произвол и прочее всё так же будет. Люди играют не ради того, чтобы их вылечили (хотя и очень хотят этого!).
Тем не менее, я не вижу, как отсутствие пары пакетов нанокрови, которая всегда делались химиками, ухудшит ситуацию. Всё-таки, они делаются минут за пять.
Тем более, что это пакеты даже не всегда трогают.

**Comment by MemoryDreams** [comment]
Давай, вместо того, чтобы рассказывать, какое всё хрупкое и какие игроки немочные, вместе сядем и подумаем, как сделать медицину меньшим говном, чем она есть.

**Comment by MrMagick2104** [comment]
> Много крови. Крайне много крови. В медблоке, раундстартом, находится один пакет на триста шестьдесят юнитов крови каждой группы. Всё.

Там больше есть на складе, емнип. Плюс, донорство никто не отменял. 

> Включим сюда то, что создание новых пакетов крови никак недоступно и, каким бы крутым ролеплеером ты не был, максимальный объем банка крови ограничен.

"Недоступно создание новых пакетов", - когда буквально на несколько комментов выше сказали:
"Пакеты из пластика крафтятся". 
Не хочется переходить на личности, но авторитет "почётного главврача" это несколько подрывает.

> Убирая нанокровь - да и вообще, всячески трогая баланс меда, в сторону ухудшения, ты провоцируешь игроков играть так, что они будут бояться проявить любую инициативу. Не будет больше пьяных драк, не будет больше охранного произвола. Станция превратится в убежище гемофилов.

Мы не знаем, что будет, пока не попробуем. Может быть, вместо того, что бы прекращать пьяные драки, люди пойдут сдавать кровь и проявлять инициативу, чтобы можно было безопасно пиздиться. И никто не мешает в будущем ревёртнуть пр, если всё пойдёт по пизде.

P.S. Зачем нужна кровь в пакетах, когда пациентов можно просто смесью глюкозы/нутримента, трика и железа, которые с приличным темпом восстанавливают количество этой самой крови?
P.S.S. Даже если доноров не будет, всегда можно пополнять количество запасов крови при помощи макак, так как у всех хуманов кровь взаимозаменяемая.
P.S.S.S. Оффтоп, но у нас вроде бы есть отключенные евенты оф зе раунд, в которых иногда бывают смешные приколы. Отсутствие в медбее всего, включая сканеры, аптечки, а также замена хирургических инструментов на гетто-варианты, включено в эвент с недостаточным спонсированием медбея. На локалочке видел, жаль, что отключены, хотя на это наверняка есть причины, так как некоторые из них не работали, по-моему.

**Comment by MemoryDreams** [comment]
> жаль, что отключены, хотя на это наверняка есть причины

Возможно, причина таки в том, что у нас безрукие игроки?

**Comment by Srankl1n** [comment]
я конечно понимаю нытье соляра, но добавлю, что шуссоид скорее убьет меня этой нанокровью ибо передоз там 5 юнитов, не говоря о том что она лежит в неочевидном месте. по сути удаление крови создаст лишнюю мозгоебку и все

**Comment by MrMagick2104** [comment]
> Давай, вместо того, чтобы рассказывать, какое всё хрупкое и какие игроки немочные, вместе сядем и подумаем, как сделать медицину меньшим говном, чем она есть.

Можно попробовать сделать медицину в некоторых аспектах менее "бурной", чтобы процессы происходили медленнее, а потому большая часть пациентов не требовала бы активной хирургии под капельницей с кровью и кучей химикатов, как говорит человек выше.
Ну и можно добавить несмертельные рандомные заболевания, которые были бы лишь слегка мешающими, например, боль в коленях от артрита при беге. И, естественно, трейт на повышенный шанс получения заболевания.
А ещё, имхо, стоит сделать повреждения более долгосрочными, чем сейчас, а также требующих присмотра. Если человеку, допустим, оторвало все конечности, но мозг не умер, то в меде его спокойно могут заштопать за пять минут и он выйдет как новенький, в худшем случае у него будет потеря памяти. По-моему, если кому-то оторвало хотя бы палец, не говоря уже о голове, а потом его пришили обратно, то там проблемы на всю жизнь остаются, если не повезёт.

**Comment by MrMagick2104** [comment]
> Возможно, причина таки в том, что у нас безрукие игроки?

Да не, скорее потому, что половина эвентов кривая, а другая половина вообще не работает. Допустим, эвент с отсутствием нормального вооружения в арсенале иногда прокает, но из-за недавнего ремаппинга, он ничего не делает, как я проверял на локалке.
Плюс, это очень фрустрирует, наверное, когда они выпадают каждый раунд или тогда, когда хочется просто нормально поиграть, потому что там есть вещи по разряду: "Какое удивительное совпадение, что НИКТО на станции не умеет стрелять. У каждого игрока теперь кламзи."
Если сделать воут перед раундом на разрешение этих микроэвентов, а также починить их, то было бы нормально, я думаю.

**Comment by MemoryDreams** [comment]
По вопросам медицины пиши в #1784.
