### ISSUE TITLE
База данных, или как вечно спрашивать "живой ли вы?".

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#177]
**Описание бага**
На консоли датчиков у ЧЕЛОВЕКА такие данные "Pulse: null bpm | BP 30/20 (low oxygenation) | Temp: 50.0637 C.". В базе данных по этому нечего нет, а он говорит.
К чему я это всё, если у него полностью протезированое тела почему у него есть давление вообще и почему, а также в базе данных об это ни слова не сказано, да и зачем это. Ведь так?
**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Открываем консоль датчиков, и пялим в экран. В итоге, видим, что у него низкое содержание кислорода в крови, да и температура высокая. Теперь, смотрим в базу данных, и видим что он ЧЕЛОВЕК, а говорить-то он говорит.
**Ожидаемое поведение**
Вместо человека, там должно быть человек-киборг или что-то в этом духе.
**Скриншоты**
![-](https://user-images.githubusercontent.com/10909882/45031989-b2f99580-b07a-11e8-8460-b72fa3f85db3.PNG)

**Дополнительня информация**
Да-да, я не слепой, и картинку его вижу, но всё же так не должно быть.

**Comment by Cinericius** [comment]
А, этот баг вроде бейцы недавно у себя правили, фикс есть в списке для мержа.

**Comment by YaridaTheDragon** [comment]
- ЛЯ СМО УМЕР ПОМОГИТЕ ЕМУ
>СМО просто спит у себя в кабинете и он боргохьюман

**Comment by Cinericius** [comment]
Фиксили кажись
