### ISSUE TITLE
Justice hat без спрайта

### ISSUE THREAD

**Issue by Wuattt** [ChaoticOnyx/OnyxBay#1771]
### Описание бага
Надеваешь шапку - а она тебя лысым делает. Она даже без спрайта

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем шапку

3. одеваем на голову
4. Видим, что ты лысый и без шапки

### Ожидаемое поведение
Шапка должна быть видна, а волосы не сбриваться

### Скриншоты
Если проблема может быть показана на скриншотах - прикрепите их.
![image](https://user-images.githubusercontent.com/34631419/76581467-19673b80-64dc-11ea-869a-a6faf6585f92.png)

### (Опционально) Дополнительная информация
Justice hat в гетто которая

**Comment by hard-res3t** [comment]
Поискал спрайты в билде. Для инвентаря есть, для персонажа нет.
Поискал в бее. Там тоже самое. Надо рисовать.

**Comment by TobyThorne** [comment]
Исправлено в #6900
