### ISSUE TITLE
Сделать шахтёрку и ксеноархеалогию великой снова!

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#1773]
### Улучшение
Сделать игру за шахтёров и археологов интересной, внести больше видов активностей вне станции.
###** Решение**
Добавить возможные бедствия на астеройд, заставляя быть куда более осмотрительным. Переделать артефакты для учёных, добавив им намного более явные эффекты и описания их особенностей. Добавить взрывную руду из других билдов. Увеличить кол-во дереликтов для исследований археологами и учёными. 
### (Опционально) Альтернативы
Портировать лаваленд.
Реализовать аналог дюны, добавить песчанных червей, впилить псионику(Это рофл не бейте)

**Comment by Iotwo** [comment]
То есть бродящих мобов, взрывной породы и коллег по цеху с сомнительными намерениями тебе на астероиде недостаточно?

**Comment by Traysoul** [comment]
+убрать возможность телепортироваться к дереликтам с помощью вортекса
