### ISSUE TITLE
Shower curtain в спальне

### ISSUE THREAD

**Issue by Wuattt** [ChaoticOnyx/OnyxBay#1782]
### Описание бага
Четкое и понятное описание сути бага.
Неправильное название занавески

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем занавеску в спальне брига
2. наводим мышку
3. видим shower curtain
4. Видим ошибку .. shower curtain не в shower, а в bedroom

### Ожидаемое поведение
Душевная занавеска должна стать обычной

### Скриншоты
Если проблема может быть показана на скриншотах - прикрепите их.
![image](https://user-images.githubusercontent.com/34631419/76692602-82c48700-6661-11ea-8809-664cc33887d9.png)

**Comment by MemoryDreams** [comment]
А в чем, собственно, проблема душевых зановесок в спальне? Ты не задумывался, что это не баг, а фича?

**Comment by Wuattt** [comment]
То есть, там действительно стоят полиэтиленовые шторки для душа?

**Comment by MrMagick2104** [comment]
Нет, это в душе обычные тканевые занавески.

**Comment by MemoryDreams** [comment]
> То есть, там действительно стоят полиэтиленовые шторки для душа?

Бюджет не резиновый, знаете ли.

**Comment by HonkyDonky** [comment]
Классные репорты, вкусные.
