### ISSUE TITLE
Реворк медицины. Опять. 

### ISSUE THREAD

**Issue by Fritcher36** [ChaoticOnyx/OnyxBay#1784]
Заниматься этим придется долго и упорно в несколько патчей, но надо. Итак, что от медицины требуется:
1) Добавить реакции куклы на пиздюли. Сейчас крайне сложно уронить челика в крит, но из крита он уже не выйдет без гениальных врачей. Происходит это от того, что даже при нескольких дырках в теле, переломах и общем зашкаливающем количестве брута космонавтик все ещё способен стоять и стрелять. Должна быть несколько другая ситуация: нелетально прибить космонавтика/просто вывести его из строя, не заботясь об его выживаемости, должно быть легче, чем 100% подтвердить смерть. 
2) Добавить летальности. Сейчас большая часть оружия крайне медленно опиздюляет противника, в то время как некоторые редкие образчики имеют свойство ваншотать. В связи с этим хотелось бы превратить различные ножи, бутылки, монтировки, тулбоксы и прочее оружие пролетариата в что-то более опасное, чем палка. 
3) Убрать ситуации с неизлечимыми пациентами. Сейчас если пациент после боя попал в медбей - он либо победитель, либо труп. Во втором случае он может ещё иметь немного хп на мозге, но количество дыр во всех частях тела, урона органам и потери крови делает его спасение чем-то кроме получаса таскания между крио и операционной невозможным. Лечение может быть сложным, может быть доступным только при определенных средствах, но растягиваться на полчаса дроча оно объективно не должно. Одно дело - полчаса лежания в палате медбея под капельницей с ПДА, ньюскастером, регулярными гостями и процедурами, а другое - полчаса черного экрана для пациента и интенсивного QTE для медиков. В то же время мгновенная хирургия это не круто.
4) Ввести какие-либо ещё методы лечения кроме крио и хирургии. В данный момент любые повреждения тяжелее небольших ожогов/недолгого пребывания в разгерме требуют оперативного лечения, что нагружает врачей. Медикаментозное и процедуральное лечение может разнообразить геймплей, дать химикам хоть какое-то занятие кроме варки луба, а новичкам в меде - возможность для практики. 

Кроме вышесказанного, требуются следующие фичи: 
1) Удобный интерфейс операций. Жрисовский с его хп конечностей и органов - бред сивой кобылы, а вот кукла, по которой можно кликать, не выбирая нужные конечности на панели интентов - хорошая вещь. Бонусные очки за визуальное отображение переломов и разорванных артерий после оперативного входа. 
2) tbd...

Иссуй создан больше как общий связующий, сам медицинский апдейт нужно делить на иссуи и пилить по частям, плюс требуется обсуждение с геймдизайнером и другими разработчиками.

**Comment by MemoryDreams** [comment]
1-2. То есть, ты предлагаешь облегчить кнок и при этом забаффать рукопашное оружие? Тебе не кажется, что это будут абузить вообще все? Я знаю, что это всё ещё на концепте "ах если бы", без какой-либо конкретики, но всё же. Чувствую тут лёгкую неувязочку. 
3. Ну, да. Было бы здорово, если чувакам не приходилось по полчаса наблюдать чёрный экран, а палаты хоть иногда были кем-то заняты. Но, опять таки, никакой конкретики. Нужно думать, как это всё устроить. 
4. 
> Медикаментозное и процедуральное лечение может разнообразить геймплей, дать химикам хоть какое-то занятие кроме варки луба

Ты сейчас до глубины души оскорбил химика во мне. Лекарства могут вылечить вообще всё, кроме сломанных костей и сгнивших органов. Я, зачастую, без особых проблем на химике тащил весь медбей. 
Да и эй. Вспомни все те смешные ситуации, когда хирург раундстартом выламывает окно в химию и начинает варить себе фарму, потому что, видите ли, у него лапки и без лекарств лечить он не может (хотя всему кроме антирадина в отсеке есть альтернатива). 

> Удобный интерфейс операций. Жрисовский с его хп конечностей и органов - бред сивой кобылы, а вот кукла, по которой можно кликать, не выбирая нужные конечности на панели интентов - хорошая вещь. Бонусные очки за визуальное отображение переломов и разорванных артерий после оперативного входа.

Это, конечно, хорошая вещь. Нужная? Почему бы и нет. Но уж точно не приоритетная. Операции, какие они сейчас, более чем справляются со своей задачей. Если найдётся кодер, который вкодит красивенький интерфейс, то, да, я с радостью его одобрю. Но я не вижу это как приоритет. 

Вообще-то, я полностью согласен с тобой в том, что с медициной нужно что-то делать. В текущем её виде, это тупое говно тупого говна, в которое неинтересно играть. Чтобы переработать эту медицину во что-то удобоваримое, нужно потратить колоссальные усилия. Но, в конечном итоге, оно того стоит. Так что, давай работать.

**Comment by MrMagick2104** [comment]
> В связи с этим хотелось бы превратить различные ножи, бутылки, монтировки, тулбоксы и прочее оружие пролетариата в что-то более опасное, чем палка.

Имхо, проблема в том, что большая часть оружия крайне ситуативна, но я бы не сказал, что оно безопасное. Например, можно взять пять-шесть бутылок и, разбивая их о голову оппонента, держать его в станлоке, уронив с одного удара<s>, особенно с 10/10 фичей с поджигом алкоголя на теле после разбития бутылки о голову </s>.
Ножи, например, полезны исключительно в ситуации, когда человек уже лежит и его нужно добить, так как им можно отрубить человеку голову за пятнадцать секунд, если держать его в грабе, но в остальных случаях колюще-режущие раны особо никакого вреда не наносят.
А монтировки, тулбоксы и огнетушители хорошо работают только если бить на дизарме в голову.
Учитывая всё это, оружие ближнего боя очень сильно уступает даже обычному зипгану, при этом имея заметную эффективность при правильно применении относительно боя голыми руками, но разве это плохо? <s> А ещё можно парировать удары армблейда генок. </s>
Плохо то, опять же, имхо, что огнестрел обладает никакой останавливающей силой, на уровне дизарма голой рукой. Буквально, человек может пережить длинную очередь из пулемёта в упор, отпиздить тебя мачете (кончились патроны), после чего умереть от предыдущих ран через минут десять - тридцать, при этом ни разу не упав на землю.
Итого, в перестрелках 1 на 1 с обычным пулевым оружием, у космонавта есть три стадии боеспособности:
1) Пока не словил не одной пули. Можно спокойно бегать, уворачиваться от пулек, использовать укрытия и т.д., и т.п.
2) Словил одну пульку. На следующие пару минут ты становишься инвалидом из-за боли, что, однако, не мешает тебе отстреливаться, а мешает уворачиваться и использовать укрытия. Как следствие, значительно уменьшает шансы победить в перестрелке, но не убить оппонента. Если ты получил одно попадание в торс/ноги/руки, а тебе задело органы или артерию, то без медицинской помощи в последующем ты уже не боец, а труп. 
3) Крит. 
И проблема не в целом в такой ситуации, а в том, что между 2-3 лежат как минимум пара-тройка очередей вплотную и в том, что никакой разницы между промежуточными состояниями 2-3 по-просту нет.

Что с этим делать? И ещё раз, имхо, следует добавить влияние боли на жизнь кроме замедления, в зависимости от её количества и, в конце-концов, понизить болевой порог у космонавтов, добавив им кратковременный стан (не больше десяти секунд) на определённом уровне боли, до остановки сердца от болевого шока, снять который можно активно прожимая резист на пяток секунд раньше.

<h3>TL;DR: </h3> Оружие ближнего боя полезно только в конкретных ситуациях для каждого вида оружия, но, по моему мнению, это нормально. У огнестрела есть проблема в том, что космонавтам не похуй только на первое попадание(даёт замедление) и фатальные выстрелы. Нужно решать с использованием большего количества боли и различных дебаффов из-за неё.

**Comment by MemoryDreams** [comment]
У меня тут родилась идея по поводу вертикального геймплея. 
Предлагаю дать космонавтам возможность брать и использовать прежметы из лежачего положения. При этом, если космонавт падает любым способом (кроме прожатия рест), вещи и его рук выпадают всегда и накладывается кулдаун секунды в 2-3, в которые он не может ничего подобрать или встать, чтобы как-то "наградить" опонента за удачный кнок. 
При этом, кнопку рест стоит вынести отдельной кнопкой в интерфейс, где-то возле резиста, и отвечать она должна не за абстрактное состояние "is resting", а за конкретное положение космонавта. То есть, чтобы rest автоматически активировался, когда персонаж падает, и вставать нужно было мануально, секунд через пять после того, как ты упал.

**Comment by MrMagick2104** [comment]
> > Давай, вместо того, чтобы рассказывать, какое всё хрупкое и какие игроки немочные, вместе сядем и подумаем, как сделать медицину меньшим говном, чем она есть.

> Можно попробовать сделать медицину в некоторых аспектах менее "бурной", чтобы процессы происходили медленнее, а потому большая часть пациентов не требовала бы активной хирургии под капельницей с кровью и кучей химикатов, как говорит человек выше.
Ну и можно добавить несмертельные рандомные заболевания, которые были бы лишь слегка мешающими, например, боль в коленях от артрита при беге. И, естественно, трейт на повышенный шанс получения заболевания.
А ещё, имхо, стоит сделать повреждения более долгосрочными, чем сейчас, а также требующих присмотра. Если человеку, допустим, оторвало все конечности, но мозг не умер, то в меде его спокойно могут заштопать за пять минут и он выйдет как новенький, в худшем случае у него будет потеря памяти. По-моему, если кому-то оторвало хотя бы палец, не говоря уже о голове, а потом его пришили обратно, то там проблемы на всю жизнь остаются, если не повезёт.

В другом иссуе написал, попадает под тему реворка медицины, так что копипастну сюда.

**Comment by Srankl1n** [comment]
давайте вы украдете с бея автокомпрессор и привяжете остановку сердца при достаточном количевстве урона у тела
это конечно безумная идея но хоть как то можно будет отправить пацана в крит без болезненно долгой стрельбы или избиений

**Comment by MrMagick2104** [comment]
> количевстве урона у тела

Уже есть в виде крита с остановочкой сердца от пейндамага. Правда, там порог заоблачный, скорее тебя гибнет, чем сердце остановится.

**Comment by MemoryDreams** [comment]
А у нас сейчас разве тяжело отправить человека в крит? И так же от боли вызывается шок и отключение сердца, после чего его приходится перезапускать.

**Comment by MrMagick2104** [comment]
Отправить в крит - тяжело. Остановить сердце так, чтобы его сразу можно было запустить, без всяких доливаний крови - сложная задача.
А вот убить человек при помощи дамага по органам несложно.

**Comment by Srankl1n** [comment]
лол если додику повезет то он после 15 пуль из буллпапа восстанет и убьет тебя прикладом от этого же буллапапа

**Comment by MemoryDreams** [comment]
Окей. Как вариант, можно понерфать урон по органам, чтобы они не умирали, чуть что, но понизить порог боли для остановки сердца. Только так, чтобы его можно было запустить без особой боли массажем сердца, если всё не слишком плохо. Можно это на рандом с каким-то шансом повесить вообще.

**Comment by Srankl1n** [comment]
э, нет, моя кривоватая идея подразумевала отключение космонавтика после урона, как при старой медицине, тут же тупо жахнулся оксикодоном и идешь убивать нюкеров хоть без брони

**Comment by MrMagick2104** [comment]
СЛР у нас охуенно реализован, но им никто не пользуется, потому что при любых условиях, которых останавливается сердце, оно остановится снова, если их не убирать, из-за чего СЛР кажется бесполезным (пусть это и не так, т.к. он накидывает оксигенацию).
> Можно это на рандом с каким-то шансом повесить вообще.

Пощади, с нашим генератором случайных чисел это - хрень.
> э, нет, моя кривоватая идея подразумевала отключение космонавтика после урона, как при старой медицине, тут же тупо жахнулся оксикодоном и идешь убивать нюкеров хоть без брони

У нас же люди не симплмобы, с чего бы им отключаться вообще, если урон не по голове, допустим?

**Comment by Srankl1n** [comment]
так я и не расчитывал что моя идея будет слишком хорошей, это попытка совместить старомед с брейнмедом, такая же нелогичная хуита но зато мог спокойно отправлять в крит вражину нанося ему непрямой дамаг по органам

**Comment by MrMagick2104** [comment]
> можно понерфать урон по органам, чтобы они не умирали, чуть что,

Имхо, лучше броню баффнуть, а не просто органы пуленепробиваемыми делать, потому что тогда придётся ревёртать рано или поздно.

**Comment by Srankl1n** [comment]
ну даб, слаг который с первого попадания убивает тебе глаза и мозг. броня не спасет орган если у него невероятно мало хп

**Comment by MrMagick2104** [comment]
У органа мало хп -> он маленький по размеру -> скрутить шанс попадания именно по нему, а не по всей части тела в целом. Не?

**Comment by Srankl1n** [comment]
рандом)

**Comment by MrMagick2104** [comment]
Рандом там и без нас есть, просто нужно его подкорректировать.

**Comment by Fritcher36** [comment]
Ну а кроме рандома что у нас есть? Можно органы коцать в процентном соотношении от урона в часть тела, но это не лучше.

**Comment by MrMagick2104** [comment]
Иногда рандома не избежать, но, когда его можно просто не трогать или есть более-менее нормальная возможность-альтернатива, то лучше от него поостеречься. Зачем больше рандом на массаж и остановку сердца - не совсем понятно.

**Comment by MemoryDreams** [comment]
> У органа мало хп -> он маленький по размеру -> скрутить шанс попадания именно по нему, а не по всей части тела в целом. Не?

Вот это, кстати, хорошая идея. Давай тогда уменьшим шанс попадария по маленьким незащищенным органам, а именно, по глазам. Может ещё и на мозг добавить?
Баффнем броню, чтобы урон по органам в грудной клетке шел меньше. При этом понизим порог пейн дамага, чтобы было чуть проще положить космонавта в крит. То, что он может обколоться обезболом, я считаю, не большая проблема, учитывая, что его действие не вечно и он довольно быстро овердозится. Вопрос только в том, насколько понизить этот порог.
Ну и да, нужно удостовериться, что броня хотя и защищает от пейндамага, не пропускает его полностью.

**Comment by MrMagick2104** [comment]
> Ну и да, нужно удостовериться, что броня хотя и защищает от пейндамага, не убирает его полностью.

iirc, пейндамаг идёт либо как отдельный вид дамага (пулл панчи и боксёрские перчатки), либо как производное от обычного урона. Если броня полностью не защищает от урона, то и от пейна тоже.

**Comment by Srankl1n** [comment]
трамадол держится чуть больше чем дохуя, если его взять таблеткой, а овердознутся ним нельзя
разве что медленная скорость после длительного нахождения в организме, но я бы по вопросам боевки и медицины спрашивал соляра, а не делал выводы

**Comment by MrMagick2104** [comment]
> Баффнем броню, чтобы урон по органам в грудной клетке шел меньше.

Лучше, имхо, как-то по-другому сделать, потому что урон по органам, он как радиация. Если его хотя бы чуть-чуть есть, то всё.
Плюс, не решит проблему надоедливых застревающих шрапнелек.
Я бы добавил порог урона, до которого дамаг органов сквозь броню и застревание всякого мусора в теле невозможно.

**Comment by MemoryDreams** [comment]
> Я бы добавил порог урона, до которого дамаг органов сквозь конкретную броню и застревание всякого мусора в теле невозможно.

А как ты предлагаешь это реализовать? До этого порога будут синяки или типа того?

**Comment by Fritcher36** [comment]
> синяки
А давайте систему урона и ХП как в маскараде, ага.

**Comment by MemoryDreams** [comment]
А что там в Маскараде?

**Comment by Fritcher36** [comment]
У тебя где-то 5-7 стадий хп от синяков до крита, а твоя живучесть влияет не на ХП как во всяких дындах а на то, как сложно тебе нанести урон. В тебя влетает урон и ты его танкуешь точками в телосложении и если ты живучий вомпер то Стойкостью.

**Comment by MrMagick2104** [comment]
> А как ты предлагаешь это реализовать? До этого порога будут синяки или типа того?

Первый вариант: до порога урон гарантированно проходит по телу, без урона по органам, а также без застревания в теле шрапнели и артериалочки, со снижением урона от брони. После порога - как сейчас.
Второй вариант: включает первый, но также есть минимальный порог урона, если урон ниже него, то он просто не проходит. Вместо этого, он наносится по условному ХП брони, при достижении которого нуля, броня либо разваливается на элементарные частицы, либо "ломается", после которого нужно либо сменять плиту в плитнике, либо починить бронежилет (как?), либо взять новый бронежилет. Сломанная броня получает x/2 резисты и больше не защищает ни от шрапнели, ни от дамага по органам, а даёт только просто срезание урона и то, как выше сказано, в два раза меньше. Правда, тут спрайты нужны будут, а также отдельный способ для ремонта брони/плиток, если это захочется пилить.

**Comment by Srankl1n** [comment]
>
шрапнель

ну можно как на маринах (или как во втором фар край) вытаскивать осколки острыми предметами, офк все это с болью, артери рапшрами и прочьим говном

алсо коляска от шрапнели не помагает

**Comment by MrMagick2104** [comment]
От шрапнели вообще нихуя не помогает, это отдельная проблема.
Если ты двигаешь, неважно как, пусть хоть телепортацией через порталы, пусть шагом, пусть на каталке везут, то тебя всё равно ебёт шрапнель.

**Comment by Fritcher36** [comment]
Артериалки это отдельный рак, который нужно залечивать отдельными механиками. Сейчас нет жгутов или каких-то ещё способов приостановить или замедлить артериалку без хирургии, не считая укола всякими кровоостанавливающими химикатами.

**Comment by Srankl1n** [comment]
бей лудший билд.
алсо надо сделать застревание арматуры и осколков стекла если они влетели в тебя во время взрыва или из пневматики

**Comment by MrMagick2104** [comment]
Осколки уже застряют, вроде бы.

**Comment by Srankl1n** [comment]
осколки тупо из бомбы, а не из окружения

**Comment by MrMagick2104** [comment]
Не, если в тебя кидают стекляшки, то они застряют, емнип, но взрыв не отталкивает стекляшки, чтобы они "кидались".

**Comment by MemoryDreams** [comment]
> Первый вариант: до порога урон гарантированно проходит по телу, без урона по органам, а также без застревания в теле шрапнели и артериалочки, со снижением урона от брони. После порога - как сейчас.

Вот этот вариант мне нравится. Не слишком сложный и должен выполнять цель.

**Comment by Srankl1n** [comment]
в принципе норм, но какой будет порог и если оружие наносит урона выше порога? я еще молчу про обрез который делает 2 разных выстрела по 80 дамага если это слаг

**Comment by Fritcher36** [comment]
Ну слаг и должен по органам хреначить.

**Comment by MemoryDreams** [comment]
Вот это нам и предстоит выяснить! Нужно посмотреть, сколько урона в среднем наносит оружие сейчас.

**Comment by MrMagick2104** [comment]
> я еще молчу про обрез который делает 2 разных выстрела по 80 дамага если это слаг

Запилить понижение точности при выстреле залпом, дамажить руку, в которой держится обрез, опять же, при стрельбе залпом, может ещё каких-нибудь дебафов накинуть, но только для обреза, а для полноразмерного ружья оставить как есть, чтобы был смысл носить его на спине, а не в кармане.
> в принципе норм, но какой будет порог

Сделать зависимым от резистов армора, я думаю, можно.
>  если оружие наносит урона выше порога

Просто применять резисты, как сейчас.

**Comment by Srankl1n** [comment]
лол нет) дети с удачей 10 будут тебе сердце ваншотать

**Comment by Srankl1n** [comment]
предлагаю АМР игнорить этот порог

**Comment by MrMagick2104** [comment]
Так или иначе, у АМР дохера высокий дамаг, чтобы порог проходить гарантированно. И порог не снижает урон, а только убирает дамаг по органам и прочий смех, оставив чистый брут.

**Comment by MrMagick2104** [comment]
> Вот это нам и предстоит выяснить! Нужно посмотреть, сколько урона в среднем наносит оружие сейчас.

Кстати, у нас там где-то есть стата армор пирсинга, ака пробивная способность у обычных пулек. Думаю, стоит ещё её во внимание взять.

**Comment by koronoshka** [comment]
Немного не по теме, но имеет ли смысл сделать механику на сознании мозга? А то болевой урон ты можешь впитывать но урон идет по сердцу; держишь сводящий с ума меч а эффект как будто у тебя в мозгу гвоздь. Вроде имеет смысл что ты от подобных вещей будешь терять сознание, а не накапливать буквально физические травмы на башке или сердечке. В медицине я хуй, но подумал что СБшники встающие под нашатырчиком довольно интересно.

**Comment by TobyThorne** [comment]
Что мы имеем?
- Иссуй уже достаточно древний и лежит на хрен-его-знает-какой странице, про него уже все забыли.
- С момента открытия иссуя медицину уже успели подёргать кучу раз.
- Неизлечимые пациенты в нынешних реалиях - штука ультимативно редкая. Операции проводятся очень быстро, а в условиях когда не нужны пересадки/починка костей - есть крио, которое лечит ещё быстрее.
- Летальности у оружия - хоть отбавляй. Вон ещё и дикий бафф огнестрела на подходе.

Свои проблемы есть и сейчас, но на это нужен уже отдельный иссуй с обсуждением. За сим отключаю этот от аппарата жизнеобеспечения, он слишком долго пялится в чёрный квадрат.

**Comment by kcalbCubeFork** [comment]
> Немного не по теме, но имеет ли смысл сделать механику на сознании мозга? А то болевой урон ты можешь впитывать но урон идет по сердцу; держишь сводящий с ума меч а эффект как будто у тебя в мозгу гвоздь. Вроде имеет смысл что ты от подобных вещей будешь терять сознание, а не накапливать буквально физические травмы на башке или сердечке. В медицине я хуй, но подумал что СБшники встающие под нашатырчиком довольно интересно.

Я сделал

**Comment by Doster-d** [comment]
Убийся аб стину!
