### ISSUE TITLE
Не меняется спрайт однобаллонки

### ISSUE THREAD

**Issue by Wuattt** [ChaoticOnyx/OnyxBay#1786]
### Описание бага
Четкое и понятное описание сути бага.
Если открутить от однобаллонки (баллона с проводами и девайсом) девайс(к примеру, игнайтер с таймером), то девайс отрутится, а спрайт девайса на баллоне останется. +если добавить провода к большому баллону, то иногда провода не отображаются
### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем .. однобаллонку
2. снимаем девайс кусачками
3. смотрим на выпавший девайс и однобаллонку
4. Видим ошибку .. что девайса стало два визуально

### Ожидаемое поведение
Четкое и понятное описание того, что должно было произойти.
думаю тут понятно, что должно произойти, спрайты должны правильно отображаться
### Скриншоты
Если проблема может быть показана на скриншотах - прикрепите их.
![image](https://user-images.githubusercontent.com/34631419/76728050-4296fe80-675e-11ea-8323-5af2978a2599.png)

(скрин прилепил чтобы было понятно, о какой однобаллонке идет речь)

**Comment by sweden-moose** [comment]
Фиксанул
