### ISSUE TITLE
Концептуальный UI для генок / Колесо выбора абилок

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1788]
### Улучшение
Запилить для геноцидов колесо с абилками как в прототипе.
![image](https://user-images.githubusercontent.com/48761132/76780223-b3213800-67bd-11ea-91d3-22a65968475b.png)

**Comment by MrMagick2104** [comment]
А куда его пихнуть на экране? Сделать контекстным?

**Comment by TapKo4eB** [comment]
по хоткею в центр

**Comment by MrMagick2104** [comment]
А что с бесхоткейными стрелочниками? Им, возможно, тоже захочется как-то получать доступ к колесу?

**Comment by TapKo4eB** [comment]
а можно и без хоткей мода хоткеи, кто запрещает

**Comment by kreeperHLC** [comment]
Решилось при рефорке, как и #2090
