### ISSUE TITLE
Маг-культист

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1789]
> ### Улучшение
> Убрать возможность присоединения мага к культу, потому что и так уже не самый балансный маг, да ещё и со смешными способностями культа - херня, очевидно.

Отключить магу возможность присоединения к существующему культу.

**Comment by MemoryDreams** [comment]
А разве маг сам не может запускать культ?

**Comment by koronoshka** [comment]
Маг в культе имеет потенциал быть очень веселой историей.

**Comment by koronoshka** [comment]
И разве у культа есть что-то такое особенное что не может делать маг при правильном сэтапе? Чувствую что маг нужен культу, но культ не особо полезен магу.

**Comment by MrMagick2104** [comment]
> А разве маг сам не может запускать культ?

Не уверен, но ничего такого не слышал. Обычно маг+культ идут как двойной режим.

> И разве у культа есть что-то такое особенное что не может делать маг при правильном сэтапе?

Да. У него есть союзники, которые не могут предать или что-то такое, а также могут использовать огнестрел. Сам по себе верный миньон - уже сильный союзник, а если это целая потенциальная бригада из малазийских террористов, так ещё и с командными способностями - пиздец. Допустим, маг, раскачанный на телепорт, может за тридцать секунд своровать карту кэпа, выдать всем культистам полный доступ без особых усилий, а потом начертить под столом в арсенале руну телепорта. По факту, это - чистый вин для культа.
И если побеждают культисты, то побеждает и маг, ведь они спокойно выносят главную угрозу мага - СБ и глав, т.к. murderhobо, а ещё у них есть пушечки. А уж если магу совсем повезёт, то культисты самовыпилятся об то же СБ вместе с ними, что позволит магу творить что он хочет безнаказанно.
При этом, на присоединение к культу не нужно потратить никаких сил, так как культу выгодно иметь мага, а магу не нужно тратить свои драгоценные очки на получение свитков учеников для создания союзников, не нужно убеждать кого-то к этому и так далее.
Никаких причин для мага не присоединятся к культу, кроме как чистого ролевого отыгрыша и отсутствия метагейства в нём, я не вижу.
По поводу МГ и ролевой части. Если маг, чисто в теории, достаточно могущественный, осознаёт силу своей души и прочего, знает про Нар-Си и прочих божков, про то, что все эти контракты на получение вечной жизни и прочего - наёбочка, то зачем он всё равно присоединяется к культу, погружая себя в вечное рабство при условии успеха культа? Он же не обычный космонавтик, который может жаждать золота, власти или который просто родился с желанием служить древним богам в сердце, которого можно одурманить всем этим, его наверняка учили в школе магии Федерации магов, что всё это - херня, иначе почему тогда все маги не получают дополнительные силы сделочками культистов чисто по факту своего существования в Федерации магов? /* Аргумент невалиден, если у мага есть возможность начинать культ, правда, но это проверить бы. На вики не нашёл. */

**Comment by koronoshka** [comment]
Культ и маг может кооперироваться и просто так. У меня революционеры кооперировались с культистами, а магу чернокнижнику с явно не лучшим моральным компасом это будет еще проще.
 Ну и лор у нас очень гибкий, разные маги могут и знать и не знать про Нар-Си, бесполезно просто делать догадки. На вики вообще написано что мага можно прописать хоть супергероем хоть мутантом.

**Comment by MrMagick2104** [comment]
> а магу чернокнижнику с явно не лучшим моральным компасом это будет еще проще.

Варлок чисто по определению не может контракт заключить с Нар-Си, т.к. у него уже есть один с другой или этой же сущностью, это - источник сил варлока..
> Ну и лор у нас очень гибкий, разные маги могут и знать и не знать про Нар-Си, бесполезно просто делать догадки. На вики вообще написано что мага можно прописать хоть супергероем хоть мутантом.

Ничего против создания собственной вселенной не имею, но, обычно, принимается, что маги работают на Федерацию магов, которой, очевидно, должно быть известно о всяких сущностях вроде Нар-Си, т.к. там есть варлоки. Информация про Федерацию есть на викистранице мага, оттуда это взял.
> Культ и маг может кооперироваться и просто так.

Да, но без возможности именно вступить в культ, маг не сможет давать свою стопроцентную мобильность джаунта культистам путём рун телепорта.

**Comment by MemoryDreams** [comment]
Ладно. Согласен. Одобряю.

**Comment by MrMagick2104** [comment]
> Ладно. Согласен. Одобряю.

Маг всё-таки может начать культ, как я понял по недавнему раунду.

**Comment by PlinHost** [comment]
Поглощено #1896.
