### ISSUE TITLE
Food replicator не работает

### ISSUE THREAD

**Issue by Wuattt** [ChaoticOnyx/OnyxBay#1790]
### Проблема:
У нас Food replicator очень неочевидно работает, и совершенно никогда никто не додумывается до того что у него голосовое управление.
### Решение:
Сделать так, чтобы при осмотре было сообщение о том, что у этой штуки есть микрофон. + перевести команды на русский язык, чтобы можно было произносить их на русском и всё работало. 

Старый текст:
> ### Описание бага
> В рнд делается плата food replicatora, в описании которого написано like a microwave, except better.
> 
> ### Воспроизведение
> Шаги чтобы воспроизвести баг:
> 1. Берем и строим репликатор
> 2. нажимаем лкм по нему
> 3. Видим, что ничего не происходит
> 
> ### Ожидаемое поведение
> То, что прибор управляется голосом, должно быть чётко показано в описании/при попытке взаимодействовать кликом. 
> 
> ### Скриншоты
> Если проблема может быть показана на скриншотах - прикрепите их.
> ![image](https://user-images.githubusercontent.com/34631419/76917830-44330480-68cd-11ea-93c2-5d39aa970cd0.png)
> 
> ### (Опционально) Дополнительная информация
> В него можно засунуть еду, чтобы он её на биомассу переработал, но воспользоваться автоматом, кроме как мусоркой нельзя
> 
>

**Comment by GusevDuhast** [comment]
Сколь я помню, фуд репликатор использует голосовое управление. Так что не баг, а фича

**Comment by Wuattt** [comment]
и какие команды он принимает?

**Comment by TapKo4eB** [comment]
Малогеи охренели, нет бы поэкспериментировать, нет бы у педалей или у других людей ic путём спросить - сразу багрепорт.

"menu" произнеси рядом с аппаратом и всё он тебе расскажету

**Comment by MemoryDreams** [comment]
Ни разу не пользовался этой штукой. Но вам не кажется, что управление голосом это слишком неочевидно для штуки, на спрайте которой отчётливо видны кнопочки? Там хоть в описании что-то про голос есть?

**Comment by Fritcher36** [comment]
Это не кнопки, а индикаторы, но очевидности голосовому управлению нужно прибавить.

**Comment by Wuattt** [comment]
у педалей я уже спрашивал когда-то. Не ответили толком

**Comment by GusevDuhast** [comment]
Педали сами таким не пользуются, я сам будучи ученым это открывал

**Comment by MemoryDreams** [comment]
Как насчет того, чтобы руссифицировать команды и сделать, чтобы при осмотре оно говорило, мол, там есть наклейка с микрофоном?

**Comment by Wuattt** [comment]
мне нравится ответ мемори

**Comment by TapKo4eB** [comment]
Вот согласились, согласились, да, а плашки не поменяли.

**Comment by MemoryDreams** [comment]
Поменял описание и повесил плашку.

**Comment by Doster-d** [comment]
Беру этот иссуй
