### ISSUE TITLE
paper bin невозможно достать из сумки

### ISSUE THREAD

**Issue by TheUnknownOneGH** [ChaoticOnyx/OnyxBay#1791]
### Описание бага
Его невозможно достать из сумки, даже если он пустой. Из-за чего какое-то количество места в сумке перманентно исчезает.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем paper bin в руку.
2. Кладём его в рюкзак.
3. Пытаемся его достать оттуда рукой.
4. Вы не можете это сделать, даже если он пустой.

### Ожидаемое поведение
Ну он должен доставаться-то наверное.

**Comment by Fritcher36** [comment]
Ты мне скажи, как ты его туда запихал-то нахуй?

**Comment by koronoshka** [comment]
Они на себя перетаскиваются и помещаются в руку

**Comment by MrMagick2104** [comment]
У меня как-то раз получилось вынуть одну пейпербинку из сумки, но воссоздать не удалось.
Вообще, я бы предложил сделать для всех контейнеров кнопочку быстрого опустошения. У нас очень много предметов вот с такими свойствами, проблема не в первый раз случается, иногда багуют какие-то штуки, нувыпоняли. Была такая проблема уже как минимум раз с невидимыми протезами рук в сумке.

**Comment by koronoshka** [comment]
Их можно достать перетаскиванием спрайта из сумки на себя. Закрывайте.

**Comment by TheUnknownOneGH** [comment]
> Их можно достать перетаскиванием спрайта из сумки на себя. Закрывайте.
