### ISSUE TITLE
Сломана атмосферка

### ISSUE THREAD

**Issue by Cregrant** [ChaoticOnyx/OnyxBay#1798]
### Баг
Давление в трубе подачи воздуха и в трубе откачки одинаковое. Не знаю когда точно, но похоже после февраля изменяли карту и случайно соединили **(?)** трубы

### Скриншоты
![Скриншот 20-03-2020 233716](https://user-images.githubusercontent.com/62436046/77185305-c573dc80-6b03-11ea-80c9-f9dfb5f70b24.jpg)
![Скриншот 20-03-2020 233153](https://user-images.githubusercontent.com/62436046/77185505-184d9400-6b04-11ea-895f-675859bb1620.jpg)

**Comment by MrMagick2104** [comment]
О, кстати, тоже замечал странное, когда откачиваешь много горячего воздуха, то осадочек в виде пяти тысячи градусов остаётся и в синей, и в красной трубе. Фрустрирующе.

**Comment by Srankl1n** [comment]
прикол в том что в каком-то отсеке после обнов татарина оказались где-то обрывы труб, из-за чего газ из дырявой синей трубы перетекает в дырявую красную трубу. но где именно - хз

**Comment by MrMagick2104** [comment]
Ставлю на геттомед и/или геттосб.

**Comment by Cregrant** [comment]
> оказались где-то обрывы труб

Надо когда-нибудь на локалке это дело погонять

**Comment by TapKo4eB** [comment]
уже не надо
