### ISSUE TITLE
Убирать несколько смешных моментов с рунами культяпок

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#1801]
### Улучшение
Нынче культисты повадились срать дефайлами и нарси где они хотят, пора бы это немного занёрфить.

### Решение
- Запретить дефайл песка на астероиде, дабы культяпки не фармили смешно очки на пропитание и улучшение рун.
- Запретить культу руну теар реалити а.к.а призыв Нас-Ри на всех зет уровнях кроме 1 и 2, что есть станция. Мне надеюсь не надо объяснять что бывает когда культ призывает своего бога на дереликте в заднице мира.

### (Опционально) Альтернативы
удалить культ

**Comment by MemoryDreams** [comment]
Да.
