### ISSUE TITLE
Научная консоль позволяет положить сервер

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1803]
### Описание бага
У научных консолей есть возможность печатать кастомное количество предметов в очереди.
Берём научную консоль, кладём минимум ресурсов для каких-нибудь capacitor`ов в протолат, жмём кнопку [custom] в выборе количества и дальше, используя воображение, вводим число неприемлемо больших размеров, после чего отправляем сервер в последний путь, нажав кнопку подтверждения.

**Comment by TapKo4eB** [comment]
сука я из-за тебя локалку уронил!
