### ISSUE TITLE
Корпоративные рестрикты на лоадаут

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#181]
Сделать некоторые вещи в лоадауте доступными членам только некоторых корпораций в соответствии с консенсусным списком: [Loadaut по корпорациям2.docx](https://github.com/ChaoticOnyx/OnyxBay/files/2350088/Loadaut.2.docx).

В перспективе - добавить больше корпоративного лоадаута. Но пока так.

**Comment by LagannPM** [comment]
Совершенно бесполезно и даже не стоит время на это тратить

**Comment by Cinericius** [comment]
Эх...

**Comment by TobyThorne** [comment]
Консенсусный список устарел, лодаут прочувствовал девелоперскую энтропию, корпы не нужны.
