### ISSUE TITLE
Шрапнель имеет неограниченный урон за каждый кусочек шрапнели на полу

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1810]
### Описание бага
При разрушении некоторых объектов, например, столов, остаётся шрапнель. При разрушении стёкол остаются склянки. При ходьбе по склянкам и шрапнели без обуви тебе наносит урон по ногам. Урон за каждый кусок шрапнели складывается бесконечно.
![pyatkis2](https://user-images.githubusercontent.com/58848742/77230234-e68c0a00-6ba3-11ea-9182-31ebdd4b7900.gif)
_Наступил на кусочек пола, на котором лежит пятьдесят кусков шрапнели -> оторвало обе пятки._

**Comment by Poromoks** [comment]
О, я помню, как пацанчика какого лечил, у него во всём теле была шрапнель. И вот я всё вытащил, даже специально скинул на пол, а не оставил на операционном столе, но проблема в том, что скинул я её между сканером и столом. Кладу пацана в сканер, убеждаюсь, что всё вытащил, возвращаю на стол, а он по пути на стол всем своим голым телом проезжает по шрапнели, получая ещё где-то 3 перелома. Может, сам виноват, что подальше её не убрал, но в целом у меня всё.

**Comment by ZerlGray** [comment]
Оставили бы лучше как фишку.

**Comment by MrMagick2104** [comment]
Достаточно шрапнели могут лаги вызывать в больших количествах, как показала локалка. Норм фича.
