### ISSUE TITLE
"Your previous action was ignored because you've done too many in a minute" при заходе.

### ISSUE THREAD

**Issue by MorJams** [ChaoticOnyx/OnyxBay#1818]
### Описание бага
Флуд "Your previous action was ignored because you've done too many in a minute", заодно клиент лагает. Насколько я помню, ещё и педалям срёт. Фиксится перезаходом, но вдруг это ещё и серверу грустное делает, кто знает.

### Воспроизведение
Хуй знает, появляется рандомно при заходе. В топиках вроде видно.

### Ожидаемое поведение
Не флудить и не заставлять клиент лагать.

### Скриншоты
![Скриншотик](https://puu.sh/FnVbu/3b6f6f5b64.png)

### (Опционально) Характеристики
 - OS: Win10
 - Версия клиента: 512.1479

Server Revision: eb5261c3f2cdc3af5768daaf702507c1e5421d29 - release/chaotic - 2020-03-04
Game ID: b6j-cbOh

**Comment by PlinHost** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/client/client_procs.dm#L85-L88

**Comment by Epicus7** [comment]
> Фиксится перезаходом, но вдруг это ещё и серверу грустное делает, кто знает.

Да, делает. От этого он даже упасть может. У меня локалка падала во всяком случае.
