### ISSUE TITLE
Возрастные рестрикты на профессии

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#182]
Минимальный возраст персонажа - 20 лет.
Минимальный возраст для инженера (любого, кроме стажера), медика (вирусолога, химика и т.д. кроме стажеров), СБшника (кроме кадета, да), ученого (роботиста, ксенобиолога, ну вы поняли, кроме кого), каптера - 24 года.
Минимальный возраст для СМО, СЕ или ХоПа - 27 лет.
Минимальный возраст для ХоСа, РД, кэпа или АВД - 30 лет.

**Comment by LagannPM** [comment]
Совершенно бесполезно и даже не стоит время на это тратить

**Comment by Cinericius** [comment]
Ну, во-первых, времени на это много уйти не должно, эта возможность уже есть в беебилде, оно просто не настроено.
Во-вторых, это отнюдь не бесполезно, потому что создает атмосферу, вернее, мешает ее ломать всякими 17-летними кокпетанами.

**Comment by hekko4** [comment]
Вообще, в коде есть две переменные, как я понял.

Одна из них отвечает за минимальный возраст персонажа, т.е. если у твоего персонажа возраст меньше выставленного, то он не сможет играть за определенную профессию. 
Вторая же, это идеальный возраст для персонажа. Суть её заключается в том, что чем ближе возраст персонажа у игрока к этой переменной, тем больше шансов получить эту роль. Ну например: 
Капитан: минимальный возраст - 30, идеальный возраст - 60. 
Игрок 1: возраст персонажа - 25. 
Игрок 2: возраст персонажа - 40.
Игрок 3: возраст персонажа - 56.
Игрок 1 не сможет получить роль Капитана вообще, даже если никто на неё не претендовал. 
Игрок 2 сможет получить роль Капитана, но только в случае, если Игрок 3 не претендовал на роль Капитана, если же он претендовал, то роль Капитана 100% будет выдана Игроку 3.

![image](https://user-images.githubusercontent.com/29167103/45086378-acffc500-b10b-11e8-9257-eab49ca88078.png)

**Comment by Cinericius** [comment]
Прикольно, но вот с идеальным возрастом все сложнее, потому что для некоторых профессий диапазон может быть весьма широк.
А там его обязательно для всех проф ставить или для некоторых можно ограничиться минимальным?

**Comment by hekko4** [comment]
Не, можно вообще не ставить

**Comment by Cinericius** [comment]
А, и еще, можно ли разные рестрикты ставить для разных подпроф? А то вон тот же кадет вроде как в одной профе с полноценным офицером, но минимальный возраст им бы разный воткнуть.

**Comment by hekko4** [comment]
Для подпроф нельзя, они сейчас лишь как название идут.
Можно сделать новую профессию, назвав её Junior Officer, тогда можно.

Хотя я не уверен в правдивости своих слов на все 100.

**Comment by Fourest** [comment]
Поддерживаю, заебали 17-летние капитанши
