### ISSUE TITLE
Добавить коронавирус

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#1820]
Ведь рано или поздно он должен дойти до всех.

**Comment by MemoryDreams** [comment]
Нет, не должен. У нас игра про эскейпизм.

**Comment by ZerlGray** [comment]
Не ну слыш. А куда тогда все эти костюмы защиты девать, кому приказывать не сближаться ближе чем на два тайла друг к другу, кого сжигать во имя чистоты?

**Comment by MemoryDreams** [comment]
Задизайним бубонную чуму.

**Comment by ZerlGray** [comment]
Коронавирус лучше, у него смертность меньше....

**Comment by Iotwo** [comment]
Насколько я помню и без этого шальной вирусолог или педалебоярин может потешить тебя дюже бравыми синдромами. Но только один раз.
