### ISSUE TITLE
Баг с экраном у мима (?)

### ISSUE THREAD

**Issue by MorJams** [ChaoticOnyx/OnyxBay#1825]
### Описание бага
Захожу за мима - экран становится таким как на скриншоте. При перезаходе исправляется.

### Воспроизведение
ДЕКЛАР за мима.

### Ожидаемое поведение
Экранчик должен быть нормальным.

### Скриншоты
![Скриншотик](https://puu.sh/Fo2ut/2251dad921.png)

### (Опционально) Дополнительная информация
Я, на самом деле, не уверен, что это только за мима такая хуйня. За другие профессии я последний день не играл. Но вчера ещё со всякими офицеро-ассистентами всё было нормально, а за мима такое появилось.

### (Опционально) Характеристики
 - OS: Win10
 - Версия клиента: 512.1479

Server Revision: eb5261c3f2cdc3af5768daaf702507c1e5421d29 - release/chaotic - 2020-03-04

Game ID: b6j-c70D
(на самом деле раунд прошлый, ждал пока кончится чтоб скриншот залить. Просто сейчас опять появилось)

**Comment by MorJams** [comment]
А, бля.
github.com/ChaoticOnyx/OnyxBay/issues/1012

**Comment by Epicus7** [comment]
Между логином и логаутом (во время перезахода) подозрительные рантаймы. Думаю, дело в них:

```
[19:38:30] Runtime in movable_screen_objects.dm,57: Cannot read null.client<br />
[19:38:30] Runtime in movable_screen_objects.dm,82: Cannot read null.client<br />
[19:38:30] Runtime in movable_screen_objects.dm,48: Cannot read null.client<br />
[19:38:30] Runtime in movable_screen_objects.dm,73: Cannot read null.client<br />
```

**Comment by Epicus7** [comment]
Более подробный рантайм:
```
[23:39:00] Runtime in movable_screen_objects.dm, line 57: Cannot read null.client
proc name: decode screen X (/obj/screen/movable/proc/decode_screen_X)
src: Abilities (/obj/screen/movable/ability_master)
src.loc: null
call stack:
Abilities (/obj/screen/movable/ability_master): decode screen X("EAST-1")
Abilities (/obj/screen/movable/ability_master): open ability master()
Abilities (/obj/screen/movable/ability_master): toggle open(2)
Abilities (/obj/screen/movable/ability_master): add spell(Invisible wall (/spell/aoe_turf/conjure/forcewall/mime), "grey_spell_ready")
(/mob/living/carbon/human): add spell(Invisible wall (/spell/aoe_turf/conjure/forcewall/mime), "grey_spell_ready")
/datum/job/mime (/datum/job/mime): equip( (/mob/living/carbon/human), "Mime", null, null)
/datum/controller/occupations (/datum/controller/occupations): EquipRank( (/mob/living/carbon/human), "Mime", 0)
Ticker (/datum/controller/subsystem/ticker): equip characters()
Ticker (/datum/controller/subsystem/ticker): setup tick()
Ticker (/datum/controller/subsystem/ticker): fire(0)
Ticker (/datum/controller/subsystem/ticker): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

Алсо у меня воспроизвелся локально.
