### ISSUE TITLE
Механика щитов.

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#1828]
Щиты сейчас - очень странный предмет. Работая от механики блокировок, они полностью потеряли свою полезность. Вроде нужны, выглядят мощно, а вроде и ссанина ебучая, которая абсолютно, абсолютно нахуй, не нужна, если у тебя нет макроса на useblock. Да и в том случае, щит блокирует только одну атаку, что делает их использование крайне неудобным.

Для примера: по тебе открыли огонь очередью из пистолета-пулемета. С, ну, условными гандонами, а не боевыми патронами в магазине. Щитоносец, видя это, включает блок и, успешно блокируя первую пулю, падает от второй-третий-и так далее. Почему? Не знаю. Самое смешное, что он не тратит на это свою стамину - у меня был прекрасный опыт, когда имея на руках энергощит, смог заблокировать два попадания из АМР. Четырнадцать и пять миллиметров чистой боли, вылетая из ствола, попадают в щит и делаю пукич щитоносцу, сквиртя искрами ему в лицо.

Чё делать? Либо вернуться к легаси-системе, в которой щиты с условным пробом блокировал все попадания по щитоносцу, либо менять механику использования блока и щитов в целом,добавляя им ХП и меняя режим блока.  При получении определенного уровня урона щит:
1) Разряжается - в случае с энергощитом
2) Ломается - в случае с условным полицейским щитом или баклером. 

В первом случае щит нужно закинуть на перезарядку, во втором - добавить стали и приварить её на место дыр, снижая общее количество прочности щита (было 500 - стало 400) щита, но полностью удаляя повреждения.

Как поменять механ блокировки? Автоматически включать режим блока при взятии щита в одну из рук и лочить скорость передвижения до скорости ходьбы. При получении попаданий щит должен получать повреждения, сделать потерю стамины от каждого попадания, сделать возможным попадания по ногам (с пробом в 20%, а то пяткобоевка го врумврум). 

Щитовики должны быть щитовкиами, а не барабанщиками симфонического оркестра охранного отдела РСХА НСС Екзодус.

Сори, я бухой. Если будут вопросы - меншенте тут или в дискоре.

**Comment by Epicus7** [comment]
У нас уже есть иссуй на перепил щитов, закрываю этот как дупликат. Тот уже принят, но можно чот дополнить.

**Comment by Epicus7** [comment]
Иссуй то забыл указать. Вот он: #1011

**Comment by Ruforce** [comment]
@Epicus7 Э, ну. Ты, кажется, не понял. Давай я тебе поясню.

Сранклин просит _апргейднуть_ энергощиты нюкеров.
Я прошу перепилить весь механ щитов.

**у нас боевой щит это просто респрайт полицейского щита**

И 

**Щиты сейчас - очень странный предмет. Работая от механики блокировок, они полностью потеряли свою полезность. Вроде нужны, выглядят мощно, а вроде и ссанина ебучая, которая абсолютно, абсолютно нахуй, не нужна, если у тебя нет макроса на useblock. Да и в том случае, щит блокирует только одну атаку, что делает их использование крайне неудобным.
**

**Comment by Ruforce** [comment]
Я бы ещё предложил добавить телескопические щиты с ТГ и дать их научникам, но зная любовь гениев научного ~~долбое~~атеизма коллективизировать means of production и спамить валынми на десятой минуте (хахаха, научка, которая изучается за пять-семь минут НЕ выходя из комнаты с деструктором) раунда, а на двадцатой, когда аутичные работяги-шахтеры притащили из шахт ~~Дортмунда~~ очередную порцию алмазиков, спамить вортексами, гигаксами с блюспейс целлами и иже с ним, это не очень хорошая идея.

**Comment by Ruforce** [comment]
Научка, кстати, отдельный пиздец. Не будь я бухим и не видя за окном приближающийся рассвет, пожалуй, поведал бы и про неё, но сейчас спать, сорян.
Может завтра. Кто хочет задонатить мне на портвейн три семерки - прошу вас, в директ!

**Comment by Epicus7** [comment]
> Сранклин просит апргейднуть энергощиты нюкеров.
Я прошу перепилить весь механ щитов.

Ну вообще-то нет, там иссуй в итоге более широко раскрыли. Ну да пофиг, жалко прям закрывать такую стену текста. Пусть геймдиз разбирается

**Comment by TapKo4eB** [comment]
Можно отрубить автовыкл блока при хите, хуле. Всё равно при совершении блокировки пули пойз опускается. Надо лишь посмотреть как смотреться будет.

**Comment by Rodial-Admiral** [comment]
> Щитоносец, видя это, включает блок и, успешно блокируя первую пулю, падает от второй-третий-и так далее

Да, это хохма, конечно.
Предложение с перепилом механа (с зарядкой и износом) выглядит годным.
Реквестирую тактических геймдизов в тред.

**Comment by TobyThorne** [comment]
Блоки были столько раз переработаны, что иссуй потерял актуальность.
