### ISSUE TITLE
Отсутствует сообщение о лимите игроков, когда игрока не пускает на сервер

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1833]
Выудил скрин из чата новичков:

![image](https://user-images.githubusercontent.com/5204667/77456798-cf038a00-6e0c-11ea-9dcb-80694c63279f.png)

**Comment by MrPersival** [comment]
https://github.com/ChaoticOnyx/OnyxBay/pull/3893

**Comment by MrPersival** [comment]
Починили же.
