### ISSUE TITLE
Импрувмент новых мышей.

### ISSUE THREAD

**Issue by Fox231** [ChaoticOnyx/OnyxBay#1835]
### Улучшение
Сделать два моба мышей, старые мыши без харма и заражения и новые мыши с хармом (1-5) и шансом заразить. Старые мыши разбросанны по станции и в них может вселятся кто угодно через позест. Новые мыши спавнятся только через беком маус. Кнопка беком маус становится доступна для гостоты только после мини-ивента, который спавнит в какой-нибудь отсек мышей.

**Comment by Epicus7** [comment]
Become mouse выпилена уже.

**Comment by MemoryDreams** [comment]
Это идёт вразрез с тем, как мы их дорабатывали. Да и смысла особо в этом не вижу. Эти миниивенты же регулярно случаются. Я думаю, это будет только конфузить игроков, потому что кнопка то есть, то её нет.
