### ISSUE TITLE
Кардридер в кабинетах глав больше не работает

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#1836]
### Описание бага
Если два человека проводят картой по кардридеру (ака Keycard Authentication Device) , то второму человеку выдаст сообщение о том, что карты одинаковые, независимо от карт. При этом, по всей видимости, происходит вообще ничего, что делает вышеобозначенный девайс бесполезным, как следствие, нельзя ни получить ядерные коды, ни вызвать ОБР непедальным путём.
Не первый раз столкнулись на мейне, в последний раз на версии 4244bee1ebd2c76ca0fc17d338e57035abb3a581 - release/lawful - 2020-03-25.

**Comment by Epicus7** [comment]
@HonkyDonky, похоже ты сломал здесь: https://github.com/ChaoticOnyx/OnyxBay/pull/1598

Посмотри, пожалуйста.
