### ISSUE TITLE
Добавить всякие данжи, заброшенные корабли и прочие интересности на астероид.

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#184]
Опционально: как-то связать некоторые из них с бурением. Например, сделать возможность при бурении случайно вместе с рудой вытащить активатор для телепорта/гейтвея, позволяющий попасть в некое особое место.

*Этот иссуй сделан просто чтобы проект состоял из иссуев*

**Comment by kreeperHLC** [comment]
Переработано в #11088
