### ISSUE TITLE
Сделать астероиду мульти-Z.

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#185]
Хотя бы три уровня. Добавить всяких обрывов, естественных подъемов и прочих ландшафтных радостей.

*Этот иссуй сделан просто чтобы проект состоял из иссуев*

---

**_За закрытие этой задачи выставлена награда размером в 1000 рублей!_**

_Чтобы получить награду необходимо открыть пуллреквест с улучшениями описанными в задаче, который пройдет ревью двух разработчиков билда. После того как пуллреквест будет принят, а данная задача будет закрыта, пишите Epicus#1570 (Discord) для получения вознаграждения._

* _Если вы хотите заняться данной задачей, то вы можете её забронировать на какое-то время, но в случае отсутствия активности, бронь будет сниматься._
* _Обратите внимания на комментарии к задаче. Там могут быть пояснения и уточнения о том как её следует выполнять._

**Comment by Shootnik01** [comment]
Так и стоял он в приоритетах третий год..

**Comment by OpsCoretango** [comment]
Может сварганить над аванпостом еще один астероид на который можно попасть нажав move up юзая Джет?

**Comment by OpsCoretango** [comment]
большой камень летающий над махиной

**Comment by Shootnik01** [comment]
Приоритет😼😼😼

**Comment by Epicus7** [comment]
**За закрытие данной задачи выставлена награда размером в 1000 рублей!**

Подробности в ОП-посте.

**Comment by kreeperHLC** [comment]
Сделано в https://github.com/ChaoticOnyx/OnyxBay/pull/9463

**Comment by Epicus7** [comment]
Награда выдана
