### ISSUE TITLE
Стильные декорации для данжей, раскрывающие лор.

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#187]
*Этот иссуй сделан просто чтобы проект состоял из иссуев*

**Comment by TwinIndifferent** [comment]
Хуита.

**Comment by Fourest** [comment]
>лор
> в сске
В ней лора не больше, чем в майнкрафте

**Comment by kreeperHLC** [comment]
Закрываю, так как идея хорошая, но без конкретики и спрайтов никто делать не будет. Ну и ещё у нас билд схрюкивается от количества З-лвлов, поэтому ждём рандомизации дереликтов.
