### ISSUE TITLE
Сделать шахтерам подходящее оружие от фауны.

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#188]
Добавить на шахтерку кинетические акселераторы и апгрейды для них. 
Опционально: сделать туррели, стреляющие только по мобам.

*Этот иссуй сделан просто чтобы проект состоял из иссуев*

**Comment by Cinericius** [comment]
Апгрейды в вендор, да, либо сделать возможность улучшать аксели переплавленной рудой, как это предложил @Ruforce.

**Comment by LagannPM** [comment]
Вендор надо выпиливать к хуям, и делать все через карго.
С новыми ресами появятся лишние ресурсы которые можно будет продать в карго, на эти деньги можно будет заказать подходящее оружие и возможно упгрейды
