### ISSUE TITLE
Починить количество антагов на раунд.

### ISSUE THREAD

**Issue by WhityTaty** [ChaoticOnyx/OnyxBay#19]
Три генокрада на девять человек. 
Четыре главных революционеров на четырнадцать человек.
Шесть рейдеров на шестнадцать человек.
И много других примеров которых уже не нужно приводить, чтобы объяснить всю беду с количеством антагов.

**Comment by Cinericius** [comment]
Вроде починили, по крайней мере для рабочих режимов
