### ISSUE TITLE
Опционально: завезти новый эмбиент на астероид. Дварфы это круто, но нужно что-то более атмосферное.

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#192]
*Этот иссуй сделан просто чтобы проект состоял из иссуев*

**Comment by Cinericius** [comment]
Например
https://www.youtube.com/watch?v=yWAKXyl0vQQ
https://www.youtube.com/watch?v=zrZP6Ej6Gns

**Comment by ArmolitskiyCarpoeb** [comment]
>просто

за два года так и не сделали

**Comment by Jlekar** [comment]
за очередные два года так и не сделали

**Comment by TobyThorne** [comment]
Не сделали ещё за три.
