### ISSUE TITLE
Адвансед еганы.

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#1936]
![image](https://user-images.githubusercontent.com/34314865/78385538-ac2f5d80-75e4-11ea-9f5c-3fb3210020bd.png)
Ужасно раковый вид оружия, который ссыт на баланс с высокой башни НИОКР-а.
Оружие, способное за пятнадцать секунд зарядть в себя десять лазеров, которое можно положить в сумку. Так мало того, аеган создается из говна, палок и капельку урана. По какой причине ЭКСПЕРИМЕНТАЛЬНОЕ оружие штампуется с темпами создания пистолетов-пулеметов Шпагина и не несет в себе никаких, ну ебать, никакх минусов ещё не приведено к балансу - хороший вопрос. На ТГ оно облучает радиацией стрелка и тайлы вокруг, во время зарядки, что хоть как-то нивелирует его плюсы. Почему у нас такого нет - хороший вопрос к бэекодеру. А, нет, вру. Есть. Оно облучает стрелка радиацией (только стрелка!) при ЭМ-пульсе.
https://i.imgur.com/aorQbXH.gifv

Условному блобу против него просто-напросто не выстоять, что сводит всю его опасность данного ивента к нулю, если даже не к отрицательным значениям.
https://i.imgur.com/nVUcTbG.png

**Comment by Ruforce** [comment]
advanced energy gun [5000 Steel, 1000 Glass, 500 Uranium] Queue: (Custom)

**Comment by Rodial-Admiral** [comment]
Плюсую. Фактически, сейчас можно в рекордные сроки (масштаб минут) вооружить ими АБСОЛЮТНО всю станцию - не то, что РнД. Это убивает смысл оружия, как такового, в принципе. Более эффективной пукалки НЕТ, потому что здесь мы имеем бесконечный запас аммуниции и многофункциональность - два тазерных режима и один боевой.
Можно таскать с собой несколько штук, что позволяет забить даже на мизерные задержки по перезарядке.
БОХи, под завязку заполненные адвансед еганами, начинают надоедать.

**Comment by Rodial-Admiral** [comment]
Да, сейчас fail_counter накидывается только за ЭМИ. fail_counter у аеганов отвечает, как раз, за выдачу радиации.

**Comment by Ruforce** [comment]
За раунд я удалял аеганы два раза. 
![image](https://user-images.githubusercontent.com/34314865/78387675-6d030b80-75e8-11ea-92c3-1714c32b7dd6.png)
Через десять минут после первого удаления
![image](https://user-images.githubusercontent.com/34314865/78387759-87d58000-75e8-11ea-8ff1-01957bc0a717.png)
Через двадцать минут после второго удаления.
![image](https://user-images.githubusercontent.com/34314865/78387641-5b216880-75e8-11ea-9758-35059635b769.png)

**Comment by dnivji** [comment]
Предлагаю сделать дороже крафт.
5000 Steel, 1000 Glass, 500 Plastic, 500 Uranium, 500 Diamond
Например.

**Comment by Rodial-Admiral** [comment]
Шахтеры (если они не лысые) алмазы притаскивают в количествах, сопоставимых с ураном. Не решит проблему.

**Comment by Ruforce** [comment]
>приоритет низкий
Саша, бля.

**Comment by Rodial-Admiral** [comment]
Из "простых" вариантов тут только повышение требуемой технологии випонсов до 8ки (ЕМНИП, для этого уровня надо деструктнуть буллпап, доведя предварительно до седьмого при помощи РИГовского егана). 
Но это, как по мне, костыль.

**Comment by Rodial-Admiral** [comment]
Предлагаю накидывать fail_counter при стрельбе. Конкретную величину ставить в зависимости от режима и степени разряженности. Чем более летальный режим и чем сильнее разряжен аеган - тем больше радиации.

**Comment by Ruforce** [comment]
https://cdn.discordapp.com/attachments/606411392811139072/695946101026586674/unknown.png

**Comment by Rodial-Admiral** [comment]
Забили, а зря.
Предлагаю конкретный план решения:
1) Бросать fail_counter в зависимости от режима стрельбы и заряда. Умножать на полтора при шоке, на два - при летале. 
2) Множитель fail_counter при заряде от 75% до 100% - ноль.
3) Множитель fail_counter при заряде от 50% до 75% - один.
4) Множитель fail_counter при заряде от 25% до 50% - два.
5) Множитель fail_counter при заряде от 0 до 25% - четыре.

Это побудит людей хотя бы не делать из этого _прототипа_ - энергетический миниган.
Если у них нет защиты от радиации, конечно.
По конкретным значениям - для 1 северити ЕМП там сейчас такое:
fail_counter = max(fail_counter, 30)
Для второй - то же, но 10.
Соответственно, на заряде от 50 до 75 логично подводить все к чему-то поменьше, от 25 до 50 - к чему-то примерно между 10 и 30, меньше 25 - к чему-то порядка 30 и выше.
Впилить, соответственно, видимо, в Process() ?
Тут непонятно. Кидать по таймеру или при выстрелах?
Реквестирую дополнительные мнения.

**Comment by Ruforce** [comment]
![image](https://user-images.githubusercontent.com/34314865/79563041-b2c5d680-80b4-11ea-8866-587a537af6ff.png)
Педалирую эту тему, а то её совсем без движения оставили.

**Comment by Voldirs** [comment]
Да, не чувствуется что это ПРОТОТИП, он должен калечить владельца с немаленьким шансом, вот раньше он накидывал радиацию или вообще ломался, отказываясь перезаряжаться, вдобавок можно сделать шанс взрыва этой хуйни в руках.

Но только один важный момент аеганы, которые заспавнены другим способом, например из аплинка или те что у ерт спавнятся должны работать штатно

**Comment by pro100Player** [comment]
Только предложение.
Как насчёт сделать создаваемые аеганы в протолате "экспериментальными" в качестве нового предмета, с новым спрайтиком и описанными выше свойствами? И, конечно же, значительно повысить цену этих аеганов. А то сейчас из одной пластины урана можно сделать аж ВОСЕМЬ аеганов.

**Comment by HonkyDonky** [comment]
ну че геймдизайнеры решили давайте нерфать

**Comment by Epicus7** [comment]
Понерфили в #2449, закрываю.
