### ISSUE TITLE
Бутылка молотова не разбивается об стены

### ISSUE THREAD

**Issue by PunishedHideo** [ChaoticOnyx/OnyxBay#1940]
Коктейль молотова, который можно сделать сейчас в игре...работает очень странно.

Мы наливаем в бутылку сварочное топливо, и засовываем в горлышко тряпку, смоченную тем же топливом. Поджигаем.
Сколько ни кидай бутылку об стены, она не разобьётся, а если разбить бутылку об голову, то сварочное топливо не будет загораться от подожённой тряпки.
![bandicam 2020-04-04 13-09-43-835](https://user-images.githubusercontent.com/58644835/78417477-c36a5b80-7675-11ea-9f70-4244922aec33.jpg)

**Comment by TobyThorne** [comment]
В какой-то момент было исправлено. Кидать надо на харме.
