### ISSUE TITLE
Рандомные законы для ИИ: предлагаем свои наборы

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#1944]
В начале раунда ИИ получает рандомные законы. Есть пачка различных наборов с разными вероятностями, которые ИИ может получить на старте. Корпоративные законы, азимов, переписанный для работы с сотрудниками станции, вместо "людей", идут с наибольшими приоритетами. Далее более экзотические варианты с приоритетами поменьше.

В этом иссуе нужно собрать наборы законов, которые мы потом запихаем в игру. С каждым набором нужна оценка его грифозности, чтобы понимать какой шанс ему ставить.

Идея, в общем, одобрена сенатом. Сами наборы законов требуют дополнительного одобрения геймдизом.

**Comment by PlinHost** [comment]
Вот сразу шесть, аппрувайте.
![img](https://user-images.githubusercontent.com/8840325/78452327-5cf43600-7693-11ea-8d10-d971011452e6.png)

**Comment by Ruforce** [comment]
>Идея, в общем, одобрена сенатом

хаха, опять трупы космонавтов лезут трогать игровую часть.

Но идея интересная.

**Comment by ArmenianOnyx** [comment]
Предлагаю пару интересных вариантов набора законов: 
(Мне лень англизничать)

ИИ хонкомать
- Персонал обязан носить клоунскую форму независимо от их должности и выступать перед ИИ.

ИИ трапофоб
- Весь женский персонал станции имеет низший приоритет и расценивается как биомусор.

ИИ фемолюб
- Весь мужской персонал станции имеет низший приоритет и расценивается как биомусор.

ИИ гавноед - редкий глюк заставляющий ИИ начать уничтожать персонал любой ценой.

**Comment by PlinHost** [comment]
> Предлагаю пару интересных вариантов набора законов

Эти подходят для рандом ивентов, но иссуй про адекватные раундстартовые законы, а не сбои.

**Comment by ArmenianOnyx** [comment]
> > Предлагаю пару интересных вариантов набора законов
> 
> Эти подходят для рандом ивентов, но иссуй про адекватные раундстартовые законы, а не сбои.

Смысл? Главы тогда мгновенно будут на дефолтные законы ставить

**Comment by PlinHost** [comment]
> Смысл? Главы тогда мгновенно будут на дефолтные законы ставить

Скорее предложенные тобой будут убирать, чем менять одни нормальные законы на другие.
