### ISSUE TITLE
Мыши кусают, когда наступаешь на них

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#1967]
Когда персонаж наступает на мышь, которая не контролируется игроком, с шансом в 50% она кусает его.

Описание автора:
> ### Улучшение
> Мыши, над которыми не взяли контроль игроки, совершенно безопасны. А те, что управляются космонавтиками, конечно же, больно кусаются и жрут людей.
> 
> ### Решение
> Человечек наступает на мышь. С определённым шансом мышь дает ответочку - кусает, тем самым передавая болезнь.

**Comment by Epicus7** [comment]
Проработал геймдизайн. ОП-пост обновлен.
