### ISSUE TITLE
Новые механики для ксеносов.

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#1976]
### Улучшение
Если говорить проще - игра на ксеносах будет более уникальна и интересна. Ксеносы не будут просто рескинами людей. Новые механики могут дать СОВЕРШЕННО новые и интересные ситуации. На данный момент ксеносы различаются от человека лишь по мелочам, а это не круто. Ксеносов тогда хоть вырезай, нафиг надо.

### Решение
Тут я напишу отдельно каждую расу и мои идеи по ним.

- УНАТХИ.
Ящеркам нужно сделать апгрейд боевой системы. Увеличенный урон в ближнем бою - мало. Надо дать способностей.

1. Хвост. У ящеров есть хвост. У унатхов он большой. 
Первый вариант, можно просто увеличить спрайт в четырех направлениях так, чтобы хвост заходил на второй тайл.
Второй вариант - сделать дополнительный объект "хвост", который будет следовать за ящером и застревать где-нибудь в шлюзах, не давая унатху пройти. Это более геморно, но звучит интересно.
Собственно, что там с боевкой. Унатхи используют хвост лишь для дизарма - по идее он довольно мягкий, но сбить с ног может. Выбираем намерение Disarm, ноги или пятки на кукле в левом нижнем углу, жмякаем на противника и получаем сообщение в чат, мол, происходит удар хвостом. Это даёт увеличенный шанс сбить противника с ног, положить на лопатки. Также с руками - можно сделать увеличенный шанс выбить оружие из рук противника.

2. Голова (а точнее зубки, рот). Крокодилы чем атакуют жертву? Наверное, ртом. Причем очень сильным. Предлагаю сделать фичу со ртом. Играя за унатха, вы должны иметь две пустые руки. В одну руку грабом берём противника, усиливаем захват. Второй рукой выбираем харм, целимся в рот кукле, нажимаем на противника и, хоба, "His face is horribly mangled!". Короче, укус лица.

3. Что-нибудь хамелеонское. Пусть унатхи будут менять чешую, кожу. Менять её цвет. Таким образом можно маскироваться в толпе. Правда, нужно укромное место, а оставленную чешую можно будет спутать с трупом.

- ТАЯРЕ.
Котов и кошек в ССке сейчас называют просто - фурри. Ну реально, они бесполезны. Лишь баф к бегу есть и всё. Надо исправить.

1. Скорость. Раз уж у нас таяре самые крутые легкоатлеты, то нужно им всё остальное тоже ускорить. Ускорить передвижение в режиме лёжа. Например, прожимаем Rest, но имеем возможность в таком положении передвигаться на стрелочки. Дальше - ускорить побег из наручников и кресла, кровати в два раза. На данный момент это занимает две минуты. Всем известно, что таяре были рабами, думаю, их часто заключали где-нибудь, так что они научились устраивать побеги. Плюс, кошки - жидкость. Наручники из проводов же они раздирают когтями мгновенно.

2. Шерсть. Пусть с таяр будет сыпаться шерсть, которая может вызвать загрязнение вентиляционной системы. Сыпаться она будет при ранении или голодании. Может быть это имеет что-то общее с тошнотой, кровотечением и блевотней. 

- СКРЕЛЛЫ.
Наши любимые склизкие скреллочки только склизкостью и отличаются. Уф.

1. Дыхание. Скреллы - амфибии, земноводные. Многие из них дышат кожей, как жабы, например. Собственно, что я предлагаю. Убрать скреллам легкие и добавить уязвимость к огню и ожогам. При ожогах скрелл начинает задыхаться, точнее, полностью перестает дышать, если у него нет НЕ обоженного места. Соответственно, мозг умирает,все дела.
В космосе же скреллы чувствуют себя прекрасно.  У них не лопнут легкие в случае чего, просто gasp gasp gasp, пока кислород не кончится. Токсины на скреллов реагируют ещё круче - игрок буквально загибается.

2. Общение на расстоянии. Добавим скреллам что-то вроде сообщения на всю станцию, только очень тихое и трудноуловимое другими расами. Сообщение такое поймут только сами скреллы. Типо радио на частоте 666.6, не знаю. 

3. Нужда в воде. Без воды кожа скрелла перестает дышать. Каждые 20-30 минут ему нужно будет попить хотя бы стакан воды из кулера. Единицы голода, только жажды. И начинаешь задыхаться. Класс.

4. Неуязвимость к флешу, дыму. У скреллов глаза интересные. Пусть они будут способны отражать флеши и всякие другие оглушающие и ослепляющие штуковины. Спреи, перцовые баллончики - всё бесполезно.

### Альтернативы
Альтернатива улучшения ксеносов - более проработанный лор. Но, как я уже замечал, мало кто этот лор соблюдает. Читают только самое основное по расе. Чтобы за ксеносов играли - им нужно улучшенный механ. У скреллов лор вообще очень и очень скучный, так что перелопатить нужно.

**Comment by TapKo4eB** [comment]
звучит как список идей для превращения оникса в ксенос-стейшн, ибо добавление этого приведёт к массовой миграции на ксенорасы, ибо те же хуманы порой будут страдать по отношению к другим.
Даже если какие-то некоторые вещи реализовать в виде мелкотвиков, всё равно будет подниматься вопрос баланса рас.

**Comment by ArmolitskiyCarpoeb** [comment]
С человеком выше я никак не могу не согласиться. И хочу сказать одно, fuck xenos.

**Comment by Ershovdi** [comment]
Сейчас у нас все расы в полном балансе ( ͡° ͜ʖ ͡°) .

Все можно пробалансить бэком для ксеносов. Надо лишь написать.

**Comment by Ershovdi** [comment]
Я в коде вообще не шарю. Можно какие-нибудь дебаффы сделать. Унатхи гниют от голода. Скреллы слабые (должны быть). С Таярами - хз.

**Comment by TapKo4eB** [comment]
ну в принципе что-то из этого можно ввести, с ещё большим ущемлением ксеносов. поднимем конфликт класс, пусть ассистенты пиздят баллонами котов, предупредительные выстрелы в голову, и т.д.

**Comment by Wuattt** [comment]
насчёт общения через всю станцию - можно просто добавить local skrellian и global skrellian, как у дион и радоваться жизни

**Comment by TapKo4eB** [comment]
не поверишь локал скреллан уже есть у скреллов а глобал скреллан это хрень, вам как будто дионовский хайвмайнда или геноцидского чата не хватает

**Comment by Ruforce** [comment]
что блядь.

**Comment by Epicus7** [comment]
Ну во-первых, дизбаланс. Почему люди получаются самой донной расой? Тогда людям тоже надо добавлять какие-то бонусы.

Во-вторых, слишком большой иссуй. Сойдет как обобщающий, но каждую новую способность/особенность надо в отдельный иссуй.

Но общее впечатление - это овербафф рас. Мы получим дизбаланс.

**Comment by Ershovdi** [comment]
Баланс можно исправить ограничением на ксеносов. Только 5-10 человек сможет поиграть за ксеноса в раунде. Если лимит - коннектится за другого твоего персонажа, только человека. Также, ксеносы не смогу залазить в мехи, всякие вортекс-костюмы, только воидсьюты, это сможет только человек.

**Comment by koronoshka** [comment]
Ну будет когда их в тюрягу перевезут

**Comment by Ershovdi** [comment]
А вообще кстати, все это можно сделать, если они будут в тюряге - вот и баланс.

**Comment by Wuattt** [comment]
спойлер: ограничение не сделают
либо сделают больше изьянов либо меньше фич для ксеноты (второе вероятнее)

**Comment by dnivji** [comment]
А где же предложение ксено-ерп механа?
