### ISSUE TITLE
Добавить локальные мини-ивенты, связанные с бурением.

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#198]
Например, возможность наткнуться на гнездо подземных тварей, которые начнут зерграшить бур и всех, кто стоит рядом с ним.

*Этот иссуй сделан просто чтобы проект состоял из иссуев*

**Comment by Sudar0770** [comment]
Ивент 1 - пробурено гнездо космоптеридов, и несколько штук заспаунились у бура и начали его атаковать и вообще проявлять агрессию ко всему.
Ивент 2 - пробурен артефакт находившийся под землей, что вызвало *вставьте сюда ивент* сравнимое с *вставьте сюда силу и последствия ивента*.
Ивент 3 - пробурено месторождение газа, который под огромным давлением уничтожает бур и роняет на жопу всех космонавтиков и летит в сторону вакуума.
Ивент 4 - бур бурит что-то непонятное под землей, это что-то пускает сигнал тем самым роботам на юго-западе астероида и заставляет их идти в атаку на бур (а если в них еще и игроков вселить, то в атаку на станцию и все живое)

**Comment by kreeperHLC** [comment]
Вычленил нужное, остальное ненужное
