### ISSUE TITLE
Уменьшить делей гранат при стрельбе из гранатомета РИГа

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#1980]
По какой-то странной причине, гранатомет рига метает гранаты с стандартным делеем в пять секунд, отчего весь его смысл нахуй теряется. Ручной гранатомет меняет делей на секунду.

**Comment by Ershovdi** [comment]
Так это же называется "баланс". Даже если просто подумать, как может такое мощное оружие быстро стрелять, будучи встроенным в костюм? Если в РИГе есть гранатомет, значит и другое оружие скорей всего есть, вот и пробалансили по сравнению с другими пушками.

**Comment by Ruforce** [comment]
Хуялянас. На кой чёрт мне занимать модуль для рига, если я могу взять полный пояс флешбенгов-осколочных-дымовых, а не тратить своё время для их переключения? 
Или после выстрела мне нужно брать её в руки, ждать условных три секунды и уже потом метать?

**Comment by Rodial-Admiral** [comment]
> Так это же называется "баланс"
В чем тут баланс, если гранатомет в РИГе хуже не просто обычного гранатомета, но и ручного кидания гранат?
Мне вообще казалось, что гранаты там иначе работали. Это кто-то дергал?

**Comment by dnivji** [comment]
Надо пофиксить, если ни у кого руки не дойдут, сам КД срежу.

**Comment by Epicus7** [comment]
@dnivji,

1. Ты не можешь одобрять соло иссуи. Нужно чтобы все геймдизы высказались за/против и по результатам уже можно повесить плашку "одобрено".
2. Если ты снимаешь плашку "требуется проверка", то надо повесить другие нужные плашки, как минимум "геймдиз".
3. Нельзя в принципе одобрять иссуи без "геймдиз", ибо они не требуют одобрения. Но в этой иссуи ты просто забыл плашку, тут конечно надо голосовать геймдизам и одобрять.

Вообще, подробнее это все написано здесь: https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/issues_processing.md

**Comment by Rodial-Admiral** [comment]
Отписываю в явном виде на правах геймдезигнера - оно так работать не должно, аппруваю геймдизайнерское изменение большинством голосов.
