### ISSUE TITLE
Убрать таярам и унатхам возможность залезать в мех, всякие боевые РИГи, телепортные костюмы.

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#1982]
Унатхи и таяре не могут носить перчатки и обувь людей из-за когтей. Уберем им возможность ходить в воидсьютах, в всяких РИГах, мехах и тому подобное. Ксенос есть ксенос - с хвостом и остальным.

**Comment by MrMagick2104** [comment]
> ходить в воидсьютах

Уже не могут. Нужны специальные войды.
> в всяких РИГах

Почему РИГи должны иметь ограничение на расу, если они принимают форму тела носителя, подгоняясь автоматически? Кроме расовых РИГов.
> мехах

Хвост не будет мешать ксеносу сидеть в просторной кабине меха. Если что, в одного меха спокойно может влезть 4-5 человек, там места как в маршрутке.

**Comment by Ershovdi** [comment]
У меня есть решение круче
