### ISSUE TITLE
Убрать ксеносам использование телепорта.

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#1983]
Вортекс привязывается по ДНК. ДНК человека и ксеносов очень отличается, поэтому нельзя вортексы наделать всем расам сразу, думаю. Апгрейд человека путем нёрфа ксеноса.

**Comment by Ruforce** [comment]
Что, блядь? 
У условных кисиков-хуисиков-залуписиков нет никакого генетического идентификатора, по которому можно привязать хтоническую адмиралову машину к их персонажу?

**Comment by TapKo4eB** [comment]
Что, блядь?
Это какой-то нёрф ради нёрфа или чё это вообще такое? Сейчас бы на уровне кода отрезать безвозвратно юзание плюшек.

**Comment by Ershovdi** [comment]
Окей, понял, хуйня.
