### ISSUE TITLE
Убрать/ИЗМЕНИТЬ лор, состояние, механ ксеносов.

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#1984]
Короче, просто вырезать их из кода или менять лор с ксенофобского на менее ксенофобский.
Причины:
1. Самих игроков за ксеносов унижают из-за тупых токсичных приебов уровня "хаха фуриеб".
2. На самом сервере большинству не нужны майндгеймы против тех, кто сильнее их в физическом плане. Им нужен тупо робаст.
3. Тюрьма на астероиде лишь испортит игру любителям ксеносов. Но и сама игра на ксеносах сейчас тоже неприятная.
4. Если добавлять ксеносам фичи, то люди останутся слабыми.
5. Если ксеносов нерфить, то за них точно никто не будет играть.
6. Никто не соблюдает лор ксеносов и баны за это никто не выдает.

Все шесть проблем решаются выпилом ксеносов. Для интересной игры с постоянным противостоянием ксеносов только в IC, потому что это интересно, нужно создавать отдельный проект.

Plus, можно подкрепить все правилами игры за ксеносов - за не исполнение лора ксеносов без веской причины тупо давать джоббан тупому ЕРПшеру фурриебу.

**Comment by dnivji** [comment]
Ваше мнение очень важно для нас.

**Comment by Voldirs** [comment]
Кек, а зачем так быстро закрывать то, я бы выпилил всех ксеносов кроме воксов и дион. Воксы-рэйдеры это очень клёвая тема, а дионки не так чтобы клёвая, но они рили сильно отличаются от хуманов, правда имбоваты. А вот всякие котеги, скреллочки, ящурги рили не нужны, либо нужны в каком-то другом виде, не в виде обычных членов экипажа

**Comment by Ershovdi** [comment]
Да, всех, кроме воксов и дион. Я это и имел ввиду, я дебил, да. Скреллочки, котики и ящерки реально не нужны. Их могут сделать нормально где угодно, но не здесь.

**Comment by MrMagick2104** [comment]
> А вот всякие котеги, скреллочки, ящурги рили не нужны, либо нужны в каком-то другом виде, не в виде обычных членов экипажа

Вот в виде рабов с кучей бафов было бы интересно их увидеть, как в одном иссуе предлагали.

**Comment by MemoryDreams** [comment]
> Вот в виде рабов с кучей бафов было бы интересно их увидеть, как в одном иссуе предлагали.

Это будет интересно для садистов, которые хотят смотреть на это со стороны и мазохистов, которые хотят почувствовать себя рабом. 
Нравится или нет, но у нас есть игроки, которым просто хочется играть за котиков или скреллов, чтобы их не считали рабами. И по этой причине, я согласен с ОПом. Если мы не можем дать им нормальную игру, то лучше вовсе выпилить расы.

**Comment by TermService** [comment]
Что это за предложение такое? Почему надо убрать? Чем заменить? Ксеносы это разнообразие которое ничем не компенсируется на данный момент

**Comment by koronoshka** [comment]
Я бы поиграл за раба-зека
![image](https://user-images.githubusercontent.com/58358430/78897492-f009e300-7a7a-11ea-89ec-6a97f661a33a.png)

**Comment by TapKo4eB** [comment]
А чё я захожу порой за скреллов на меня все плюют но мне то нравица, зачем выпиливать? я понимаю идея го фичи выпиливать хуле всё равно их никто не юзает но кто-то же их сделал

**Comment by MemoryDreams** [comment]
Фурриёбы сделали.

**Comment by TapKo4eB** [comment]
скреллов тоже фурриёбы шоль сделали?

**Comment by MemoryDreams** [comment]
Да.

**Comment by koronoshka** [comment]
> Нравится или нет, но у нас есть игроки, которым просто хочется играть за котиков или скреллов,

Вы как бы уже решились на то что ксеносы будут угнетаемыми гастарбайтерами на станции, с чего такая милость к ним сейчас?

**Comment by TapKo4eB** [comment]
но фурри это же от слова фур(шерсть), а у скреллов нет шерсти, как тогда фурриёбы смогли сделать скреллов??? тут то-то не так

**Comment by MemoryDreams** [comment]
> Вы как бы уже решились на то что ксеносы будут угнетаемыми гастарбайтерами на станции, с чего такая милость к ним сейчас?

Я с этим был несогласен. Мне не нравится идея рабов на станции так же, как мне не нравится идея ЕРП на станции.

**Comment by koronoshka** [comment]
Кто вообще принимал решение о введении ксенофобского лора?

**Comment by TapKo4eB** [comment]
Да и в конце концов, отдельные расы уже устоялись на сервере. Отношение у игроков как правило к ним непритязательное, даже пиздят порой, ну ок. Только выпиливать их подчистую смысл? Есть же всё же люди которым хочется поиграть на подобном.

>как мне не нравится идея ЕРП на станции.

хрен что поделаешь у нас это разрешили

>Кто вообще принимал решение о введении ксенофобского лора?

очевидно давно ещё до нас кто-то

**Comment by MrMagick2104** [comment]
> Это будет интересно для садистов, которые хотят смотреть на это со стороны и мазохистов, которые хотят почувствовать себя рабом.

Они могут не только быть рабами, но и устраивать бунты, а также просто работать и РПшить у себя там на шахтёрской микробазе.

**Comment by koronoshka** [comment]
Я сомневаюсь что сейчас люди играющие на ксеносах играют на них из-за того, что быть гастарбайтером на станции весело. Не вижу причин ксенофобскому лору оставаться на станции, единственное что я видел исходящего из этого факта в нашем каноне - еще одна поблажка на гриф. А если все же не изменять ксенофобский лор, то перетаскивание всех таяр на отдельную станцию выглядит как закономерное развитие всей этой идеи, которая до этого была игромеханически подкреплена собственно, ничем. Удаление же ксеносов это просто плохая идея. Давайте вырезать все больше и больше куски игры.

**Comment by Ershovdi** [comment]
Если не убирать ксеносов, то нужно либо делать отдельную штуку только для них (но тюряга в ВК вроде есть, зачем копия), либо изменить ксенофобский лор/законы в пользу ксеносов, рабочая сила всё-таки, а рабочую силу пиздить ни-ни.

**Comment by Ershovdi** [comment]
> А чё я захожу порой за скреллов на меня все плюют но мне то нравица, зачем выпиливать? 

С чего ты решил что это кому-то нравится. Может ты один такой фетишист, а остальные нет?

> Что это за предложение такое? Почему надо убрать? Чем заменить? Ксеносы это разнообразие которое ничем не компенсируется на данный момент

Предложение - обычное предложение. Убрать - потому что никто не улучшает. Заменить - не нужно. Разнообразие? Лишь для мазохистов.

**Comment by Ershovdi** [comment]
Кстати, иссуй по большей части был сделан на моей горящей жопе. Так что давайте лучше ксеносов менять, потому что - почему нет?

**Comment by Rodial-Admiral** [comment]
Людей и персонажей нельзя заставить не быть ксенофобами.
Тут лор достаточно пластичен, влияющие на геймплей детали вселенной генерируются больше игроками в каждом отдельном раунде, чем чьими-то талмудами где-то там на вики.

**Comment by Ershovdi** [comment]
Хуй
