### ISSUE TITLE
Ограничения для глав и АВД

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#199]
Убираем главам и АВД возможность быть не из НТ. Такой финальный штрих, который давно пора сделать, как и возрастные рестрикты.

И роли главам с АВД тоже отключаем.

Хотя, возможно, некоторым гражданским главам стоит оставить здесь небольшую вариативность, но точно стоит убрать для Капитана-ХоПа-ХоСа и для АВД.

**Comment by Fourest** [comment]
Для Хоса оставьте, а вот для АВД, Кэпа и ХоПа – оставляем.
Ещё можно сделать так, чтобы нельзя было зайти за главу, если у тебя в графе "отношение к НТ" стоит негативное

**Comment by Cinericius** [comment]
>Для Хоса оставьте, а вот для АВД, Кэпа и ХоПа – оставляем.

Сложна.

Насчет отношений - да. АВД вообще надо только Loyal оставить по большому счету, а вот главам просто отрубить два отношения, которые ниже Neutral (вроде называются Skeptical и Opposed).

**Comment by YaridaTheDragon** [comment]
>убрать ХОПу рольку
Ты зачем над каноном глумишься? 
А насчет рестриктов - ну это такое. Не бывает полностью лояльных людишек. Кто-то может находиться и на таком высоком посте, имея к НТ немного хуевенькое отношение. Если хуевое отношение, то это не значит, что они террористы и готовы в любой момент какую-нибудь хуйню-пакость натворить для НТ. Вы пытаетесь изменить то, что в принципе менять то и не нужно.

**Comment by hekko4** [comment]
Кстати смешное - чем выше лояльность, тем больше денег на счету.

**Comment by Cinericius** [comment]
Может быть что угодно, но вопрос не в том, что принципиально возможно в конкретной вселенной, а в том, что мы хотим видеть в раундах с дизайнерской точки зрения, как мы хотим канализировать процесс и какие ощущения хотим вызвать у игроков. Больше кастомизации не всегда означает более интересную игру, да.

**Comment by SFMUC** [comment]
> Вот банально, почему бы не положить в лоадаут доступное всем огнестрельное оружие с боевыми патронами? 

> 
Давай. Тогда ассистентам по типу BigRage'а не нужно будет ломать оружейку, а просто сразу бежать напролом за картой капитана, убивая всего и вся, ИбО оТыГрЫвАнИе бАнДиТа.
И смысл будет в СБ, если у каждого второго будет ствол, который спокойно пробьет бронежилет?

> Ведь кто-то мог бы классно отыграть скрывающегося под личиной уборщика бандита (не тритора-террориста, а залегшего на дно), или коварного гэбиста
> 
Возможно, но таких на Опухоли не найдешь. Нет, вернее ты найдешь одного-двух таких, которые могли бы. Но ради них litellary давать всем оружие...

**Comment by Cinericius** [comment]
Чот не пойму, сарказм в последнем абзаце слишком тонкий штолле получился?

**Comment by SFMUC** [comment]
>Чот не пойму, сарказм в последнем абзаце слишком тонкий штолле получился?

Не, там нет сарказма. 

>Еще можно для разнообразия почитать весь тред, а не только последнее сообщение, да. 

Мне было немного лень, признаюсь.

**Comment by Cinericius** [comment]
Ну про нерфоугнетение ролеплееров же жирный сарказм же, ну.

**Comment by dnivji** [comment]
Так давно пора же. ХоСу, капитану, АВД, ХоПу - только из НТ и с отношением к НТ не ниже лоялити.
