### ISSUE TITLE
T7: Добавить say log

### ISSUE THREAD

**Issue by WhityTaty** [ChaoticOnyx/OnyxBay#20]
Упростит жизнь Администраторам в кучу раз.

**Comment by Epicus7** [comment]
Очень хреновое описание тут. Я так понимаю, ты имеешь в виду отдельное окошко с сейлогами для каждого персонажа?

**Comment by hekko4** [comment]
Именно про него я и говорю.
Идеально было бы их сделать и запихать в Admin Investigation.

**Comment by Vmihey** [comment]
[Приликованная карточка](https://github.com/ChaoticOnyx/OnyxBay/projects/8#card-21696756)
