### ISSUE TITLE
Борго баги

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#200]
*В модуль рпед не лезут батарейки.
*Хирургический модуль не может в замену пакетов крови в капельницах.Не может достать пустой пакет.
*Менеджер разрезов, по крайней мере борговски аналог не оттягивает кожу.

**Comment by hekko4** [comment]
1. Это не баг, в обычный тоже не лезет. 
2. Может, нужно просто кликнуть пустым модулем. 
3. Он и не должен. 
4. На 1 баг/улучшение 1 иссуй. Это так сложно?

**Comment by Demisov** [comment]
На старом бее и батарейки лезли в рпед и менеджер разрезов оттягивал кожу

**Comment by YaridaTheDragon** [comment]
Батарейки таки должны залезать в РПЕД. В заряднике боргов есть батарейка и чтобы ее заменить, нужно полностью разбирать зарядник.

**Comment by Cinericius** [comment]
Все пофикшено вроде
