### ISSUE TITLE
Пда

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#203]
Больше половины картриджей не работает.
Либо верните нам старые картриджи, либо переходите на торчевский аналог пда

**Comment by LagannPM** [comment]
@Cinericius Слышь, надо переходить на торчевский аналог

**Comment by Cinericius** [comment]
Торчевский аналог сосатт

**Comment by Cinericius** [comment]
А действительно ли все так плохо сейчас?

**Comment by Penguineapig** [comment]
Только не торчевский аналог, умоляю
