### ISSUE TITLE
Вернуть криминалиста.

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#2035]
Не знаю, какой бейский или тутошний гений решил его выпилить и перевести в подпрофу детектива. 
Его наличие хуже не сделает, а вот отсутствие убирает немало интерсных ситуаций.

**Comment by Rodial-Admiral** [comment]
Плюсую.
"Или детектив, или криминалист" - что-то совершенно странное.
Единственное, что потребуется некий ремап. 
Из важного:
У детектива есть термалы. Термалы - уникальный предмет.
Если впиливать криминалиста простыми методами, то у него будут не только термалы, но и уникальная детективская пушка.
Тут надо детали заранее обработать.
Думаю, что выдавать криминалисту доступ, полностью идентичный доступу детектива - не самый лучший вариант.

**Comment by Rodial-Admiral** [comment]
Т-щи геймдизайнеры, думаем.
Предлагаю добавить криминалиста, как отдельную профу с отдельным от детектива доступом, что потребует, конечно, некоторого ремапа.
Можно сделать им общий отсек (тот беленький, который в кабинете детектива). 
Нужны идеи, как конкретно будет выглядеть криминалист.
Второй детектив, как подпрофа, но с двумя слотами вместо одного - слишком проблемно и неинтересно, имхо.

**Comment by Voldirs** [comment]
Ремап не надо никакой, сделать доступ в кабинет детектива req_one_access (то есть требующий хотя бы один из списка доступов) на два доступа, детектив и криминалист. Сделать шкафчик для криминалиста с таким же доступом (то есть детектив туда сможет залезть), а на шкаф детектива повесить только один доступ, детективский чистый (криминалист залезть не сможет).
Ну и шкафчик этот втыкать в правую половину комнатки.
Не забыть в супервизоров криминалиста написать детектива
???
профит

**Comment by Rodial-Admiral** [comment]
Окей, вариант Волдирса выглядит недурно по ряду причин.
Помимо того, что будут пары детектив-криминалист (что уже само по себе интересно), еще и условные неопытные нуфаги смогут забегать за криминалистов и работать под супервайзерством детективов. В идеале. Если детективы попадаться будут нормальные.
По крайней мере, в случае чего, можно будет посылать их играть на криминалистах, а не детективах.
Аппруваю в виде, описанном Волдирсом:
1) Ввести отдельную профессию "криминалист" с доступом, аналогичным текущему доступу детектива, за исключением доступа к шкафу детектива
2) Добавить детективу отдельный доступ, который будет требоваться для открытия детективского шкафа (с пушкой и термалами)
3) Добавить криминалисту свой шкаф, где будут вещи криминалистической направленности (халатики-перчаточки и криминалистические приборы) - все в целом есть в детективской на карте, но пусть в шкафу будет.
4) Профессии "криминалист" вписать, что он находится под руководством детектива

**Comment by Rodial-Admiral** [comment]
Две вещи тут не проработаны:
1) Делать ли криминалиста защищенным от некоторых ролей так же, как защищен сейчас детектив (от трейторства, например). Кажется, если криминалист сможет быть тритором, это будет довольно занятно. Но, с другой стороны - это же СБ. С третьей стороны - криминалист оттуда еще дальше, чем детектив.
2) Какие рестрикты по возрасту аккаунта (с момента подключения к серверу) вешать на криминалиста. На детективе же они есть сейчас, или сразу можно забегать? Надо проверить.
Кажется, если на детектива они есть, то на криминалиста стоит поставить пониже на несколько дней.

**Comment by Voldirs** [comment]
По поводу первого пункта ай дунно, я бы дал криминалисту возможность быть трейтором, это клёво когда трейтор-криминалист подделывает улики
По поводу второго ай дунно, но я так понимаю у криминалиста доступа к пушкам не будет так что там реально можно ооооочень маленький рестрикт сделать

**Comment by rxssxnbxrg** [comment]
Внесу свою лепту в этот иссуй. **Всё что будет написано ниже - лишь моё скромное видение реализации.**

Для начала нам стоит обратиться к терминологии: 
_Детектив_ - специалист по расследованию уголовных преступлений, в чьи обязанности входит выявление улик и предоставление оных судебным органам.
_Криминалист_ - специалист, занимающийся сбором и исследованием улик на месте преступления, которые в ходе расследования преступления помогают установить виновных, а в ходе судебного заседания доказать виновность обвиняемого.

С первого взгляда может показаться что они похожи и их объединение в билде - верное решение, но это не так. Детектив является оперативным работником, т.е. непосредственно членом службы безопасности. Криминалист же лишь предлагает свои услуги по анализу крови и других веществ и выявлению отпечатков пальцев. Говоря более понятно - детектив находится на месте преступления и **собирает** улики, а криминалист же сидит в своём офисе и по просьбе детектива **анализирует** собранные улики и предоставляет полученные данные СБ.

С терминологией мы закончили, теперь о реализации:

В нынешнем кабинете детектива всё уже сделано правильно и красиво, исходя из этого я считаю что этот кабинет должен перейти во владение криминалиста. Детектива же следует переместить в нынешний офис АВД, слегка переделав его антураж. Новый офис АВД придётся создавать с нуля немного урезав спальни в дормах, они и так редко кем используются. 

С маппингом я закончил, далее - возможности и роли:

У криминалиста в любом случае не должно быть доступа к оружию, так как его стоит причислить либо к гражданскому персоналу, либо к низшему СБ. В случае причисления криминалиста к службе безопасности - иерархия будет изменена добавлением криминалиста подвластного детективу и ХоСу, соответственно. 

Безусловно запрещать криминалисту быть трейтором - **ужасное решение**. Подделывание улик, подставы, интриги никто не отменял. К примеру, криминалист, будучи предателем, убивает члена экипажа - детектив берётся за это дело и предоставляет улики убийце и тот, дабы не быть раскрытым и убрать потенциально опасную личность, подставляет детектива и предъявляет поддельные улики вардену или же ХоСу, провоцируя арест детектива.

**Comment by MorJams** [comment]
Не знаю, какой бейский или тутошний гений решил вообще придумать такую хуйню как "криминалист"

Абсолютно бесполезная хуйня что в качестве подпрофы, что в качестве отдельной профессии
