### ISSUE TITLE
Проблемы с Балансом и Игровым Дизайном  Внестанционных Антагонистов "ВОКС"

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#2037]
Сама суть режима. Вырождение бейского кодера, то ли нюка, то ли тритор. 
У них есть инвизный модуль и снайперка, которая кладет тебя в стан - не знаю почему и как, но кладет. 
У них есть сломанные жучки, которые летают по космосу и ползают по полу со скоростью в две человеческих. 
У них какая-то супер-пупер-хуюпер броня, из-за которой шесть попаданий в туловище делают вот так
![image](https://user-images.githubusercontent.com/34314865/79163916-a279d700-7de8-11ea-9383-7f06d0ec6c14.png)

Задания воксов - отдельный пиздец, которые побуждает идти по трем возможным путям - прямо как у Данте. 
1. Воксики идут воевать и закономерно сосут.
2. Воксики идут воевать и, подрубив всю свою залупу, побеждают всех.
3. Воксики идут на астероид работать-копать-дрочить до конца раунда, где их убивает случайный голиаф.

Они  будут прекрасным дополнением к мидраунд-ивентам (как блоб), но вот считать их отдельным режимом это какой-то сюр.

**Comment by Rodial-Admiral** [comment]
Инвизный модуль (если ты про войдсуит) палится ХУДами. Да и вообще, вроде, просто альфу вниз выкручивает, но не до нуля.
Или там в каком-то из РИГов есть стелс?

**Comment by Voldirs** [comment]
Воксы в теории очень клёвый режим. Но их руинит то что их шатол всегда подлетает с оповещением. Имхо, оповещение должно быть только у нюки
Це не модуль, це скафандр, аналогичный тому что на астероиде валяется, который альфу режет
Жучков опасными вообще не назовёшь, но они рили быстрые
С хуюпер бронёй тебе тупо НЕ ПОВЕЗЛО, нюкеры тоже могут такое говно выдержать
Задания у воксов да, говно, годятся больше для мидраунда

Но для мидраунда надо сторителлера, его давно надо, но никто его ещё не спиздил

**Comment by Rodial-Admiral** [comment]
Да, я не считаю, что в текущем виде воксы могут быть отдельным режимом.
Из-за идентичного с нюковцами анонсмента, станция по умолчанию настроена к ним враждебно, и они действительно либо устраивают пиу-пиу (который априори скучнее, чем в случае с нюкой, потому что эквип более дрянной, а робастных ролей нам не завезли), либо аутизм с астероидом. 
Т.е. это некий цикорий от нюки. 
Масса проблем - странные РИГи (в них не вставить азотные баллоны, и в итоге ты тупо теряешь слот спины под РИГ и слот брони под баллон), закислороженность базы, из-за чего любое переодевание раундстартом тебя убивает.

**Comment by Rodial-Admiral** [comment]
О, Волдирс опередил про анонс.

**Comment by Voldirs** [comment]
АПД: снайперка не имбовая, на не лезет в сумки, у неё 4 выстрела, зато она инстастанит. Без стана она будет совсем помойкой.

**Comment by Ruforce** [comment]
Вопрос даже не про эквип, а про их суть. Он-то меняется даже не заходя в дримсикер, через гуи гитхаба.

**Comment by Rodial-Admiral** [comment]
А в чем сутб?
Сутб в том, что они должны устроить некий "налет" - быстро зашли, быстро взяли то, что им надо, быстро вышли. Под то, вроде, и заточены задания - взять некое приличное число всякой хрени и вернуть все тела назад. 
Как они осуществляют этот "налет" - это уже их дело, но, по идее, они должны балансировать между бомжами и хайтеком - вроде и не настолько бомжи, чтобы убиться в первые пять минут, а вроде и не могут "в лоб" прийти, всех перестрелять и с трупов стянуть нужное.
То есть - да, отстреливаются, но именно что отстреливаются в процессе налета.
Упирается эта "суть" в юзеров на воксах и в юзерах на экипаже. Первые думают, что они нюковцы со странными заданиями, вторые думают, что к ним прилетели странные нюковцы (анонс-то один и тот же).
Стоит ли винить игроков в том, что они игнорируют эту задумку?
Не думаю по двум причинам:
1) Это больше годится для ивонтов с раздачей конкретных указаний, а не "украдите столько алмазов, сколько станция будет еще два часа шахтерить и не факт, что нашахтерит"
2) Виноват механ. Механ анонса, например. Механ задач. Механ тупого эквипа и кислорода на воксобазе.

**Comment by Rodial-Admiral** [comment]
tl;dr моей мысли в том, что сама идея хорошая, но реализация (суммарно всеми, кто прикладывал к этому руку) хромает на все три ноги.
Импрувменты тут видятся - можно пофиксить анонс (почему-то при прилете мерчантов никаких анонсов нет, лол), можно не выдавать идиотские задания на ресурсы.
Скажем, задания на КИДНАП. Членов персонала, боргов или ИИ. 
Смущает задание на "все тела должны вернуться". А если гибнули/сожгли? А если какой-то дебил раундстартом улетел в космос из шлюза?

**Comment by Rodial-Admiral** [comment]
Цельки должны выполнять критерии:
1) Выполнимости (иначе людям неинтересно будет идти по этим рельсам, и неизбежно будет стремление либо к омску, либо к аутизму)
2) Рельсовости в нужном ключе. Задачи должны определять стиль антага.

**Comment by Rodial-Admiral** [comment]
Невозможность пристыковаться к станции (хотя бы даже с ожиданием аппрува от глав по механу через консоль) тоже идет в копилку минусов. Как выдавать себя за торговцев, если первое действие - это взлом стен/стекол?
Полный аналог нюки выходит. Кому-то лень было сделать нормально.

**Comment by kokokobold** [comment]
Я бы завязал воксов на получении прибыли. Например, им даются цели на получение определённых предметов, которые есть на станции, за них они могут получать кредиты там или ещё какие-то очки, а на них воксы уже покупают себе эквип, шарфики и прочее. Ну и плюс задания на убийство/кражу людей, за выполнение которых они также получают бабло. 

То есть да, просто объединить воксов и торговцев.

**Comment by Rodial-Admiral** [comment]
> Я бы завязал воксов на получении прибыли. Например, им даются цели на получение определённых предметов, которые есть на станции, за них они могут получать кредиты там или ещё какие-то очки, а на них воксы уже покупают себе эквип, шарфики и прочее. Ну и плюс задания на убийство/кражу людей, за выполнение которых они также получают бабло.

О. Можно пойти дальше и сделать одну цельку - на конец раунда иметь определенное число "кредитов". 
Кредиты - сумма выплат за выполнение "контрактов" и штрафов - например, за смЭрть кого-то из членов команды, чтобы у любителей каэсить в одиночку было чуть больше мотивации не бросать своих коллег.

Кстати, почему бы и триторам такое не сделать, вместо заданий на удержание лысых ассистентов в бриге?

**Comment by Voldirs** [comment]
>Кстати, почему бы и триторам такое не сделать, вместо заданий на удержание лысых ассистентов в бриге?

Ох мальчик, здесь мы идём снова, система контрактов уже есть на жрисе, трейтор сам выбирает какое задание он хочет сделать, по выполнению он получает кристаллы

**Comment by Rodial-Admiral** [comment]
Ох уж этот жрис.
Про трейторов можно пока забыть и смотреть отдельным иссуем, что касается воксов:

Программа-минимум:
1) Убрать анонс
2) Поменять текущие задания на киднапы, ассасинейты и кражи тех или иных важных предметов - убрав задания на кражу алмазов/металла и прочий аутизм; убрать требование на возврат всех тех, заменив на половину (иначе невыполнимо)
3) Ремапнуть базу воксов, убрав там КИСЛОРОД. 

Программа-максимум:
1) Перепилить цельки под систему "кредитов" с плюсами за выполнение выбираемых самими антагами контрактов (тоже из киднапов, ассасинейтов, краж и т.п.) и штрафами за смерти / не возвращенные на базу к моменту round end тела.
2) Дать возможность воксам пристыковываться к станции в каком-нибудь месте - но с необходимым ожиданием аппрува от глав с доступом к консоли стыковки.

**Comment by Rodial-Admiral** [comment]
В моем видении. Реквестирую остальных геймдизов.

**Comment by PlinHost** [comment]
Часть предложений реализована в ПРах выше, после #2471 можно будет переделать цели. Следует создать отдельные иссуи для остальных предложений.

**Comment by Ruforce** [comment]
Статка брони воксов, для тех, кто в танке: 
(E) (C) (M) armor = /list (7)
1: "melee" -> 80
2: "bullet" -> 80
3: "laser" -> 80
4: "energy" -> 80
5: "bomb" -> 60
6: "bio" -> 100
7: "rad" -> 60
