### ISSUE TITLE
Починить зомбификацию

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#204]
И вернуть как 4 стадия вируса

**Comment by Demisov** [comment]
Я знаю только про монкизм.Зомби режима на бее не было

**Comment by Cinericius** [comment]
Для начала можно просто портировать фиксы с Троча, потом уже поменять чо не понравится.

**Comment by Epicus7** [comment]
А у нас вообще есть в билде зомбификация? Нужно прорабатывать, у нас в билде ничего для этого нет.

Что делает зомбификация? Какие особенности у зомби? Как они умирают? Откуда берется вирус? Кто играет на зомби? И куча еще вопросов.

**Comment by Epicus7** [comment]
А вообще, у нас вон есть иссуй про зомби уже: #1834. 

Этот тогда закрываю как дубликат.
