### ISSUE TITLE
Расширение механа чертежей станции.

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#2041]
В текущей итерации их применение сводится к переименованию и созданию зон для постройки отсеков, что как-бы говно ебучее.
Предлагаю обратиться за опытом тгшников, которые дали блюпринтам возможность показывать месторасположение труб-кабелей-АПС-мусорок на момент раундстарта, что облегчит инженерам возможность чинить повреждения.
https://github.com/frosty-dev/white-dream-theta/commit/95d2f9a8488a81b6ae995c290b030aefb2a5bda9#diff-72ec57b6a6d8802463a1505b142d30fc

**Comment by TapKo4eB** [comment]
спиздить

**Comment by Rodial-Admiral** [comment]
Плюсую коммент выше, можно просто с ТГ портануть для начала.
Сейчас станция неремонтопригодна после большинства взрывов и абсолютно неремонтопригодна, если происходит взрыв трех и более двухбаллонок.
Единственное - важнее, как мне кажется, рисовать границы зон.

**Comment by Rodial-Admiral** [comment]
Предлагаю сначала портануть чисто то, что есть у ТГшников, а потом уже думать над дополнительными плюхами (вроде рисования границ зон) в отдельных иссуях/ПРах.
Итого кидаю аппрув от себя, реквестирую аппрувы от других геймдизов.

**Comment by Moscowchief** [comment]
Аппруваю.
