### ISSUE TITLE
Неверное отображение предметов в руке у тонкротрапов

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#2053]
У нас есть отдельные .dmi файлы для тонкотрапов, но, судя по всему, их реально не хватает, либо они неправильно работают, так что все выглядит примерно так
Отвертка
![image](https://user-images.githubusercontent.com/48406301/79324594-807f7200-7f18-11ea-859a-1858aec36a5b.png)
Тулбокс
![image](https://user-images.githubusercontent.com/48406301/79324155-d1429b00-7f17-11ea-886f-bf9bca395fc8.png)
Кто-то предлагал оффсет просто сделать, но это не поможет, пока есть 
Баллон 
![image](https://user-images.githubusercontent.com/48406301/79324264-0222d000-7f18-11ea-8739-f059fc46f7e9.png)
Кошка
![image](https://user-images.githubusercontent.com/48406301/79324336-2383bc00-7f18-11ea-84e9-85072971e6f1.png)
Трость
![image](https://user-images.githubusercontent.com/48406301/79324409-41e9b780-7f18-11ea-97c8-fb6456fb6f61.png)
Короче, и так понятно, что проблемы абсолютно со всем тут в этом плане и нужно как-то рештаь.

**Comment by LegatePritcher** [comment]
Рассмеялся. Окей, я посмотрю, что можно сделать.

**Comment by TobyThorne** [comment]
хули нам
