### ISSUE TITLE
Ограничить выдачу заданий, нацеленных на антагонистов

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#2056]
Трейтору может выпасть задание на бриггед **нинджи**, магу может выпасть задание на ассасинейт **чейнджлинга**, воксики, в теории, могут получить задачу на похищение **нюкера**. Это смешно, конечно, но скорее грустно.

**Comment by PlinHost** [comment]
Ассассинейт можно и оставить, а сложные вроде брига и похищения нужно спилить, да.

**Comment by PlinHost** [comment]
Нужен список конкретных задач и ролей, на которых их нельзя нацеливать.
