### ISSUE TITLE
Баланс виара.

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#2057]
ахахаха геймдизайнер не смог)
К сути. 
1. Питон стоимостью в два поинта, который ваншотает сердце с одного выстрела - слишком круто. Оно не только ломает баланс в пизду, но и превращает геймплей на виаре в простое и унылое наведение и закликивание мышкой. Для сравнения, дробовик стоит четыре, а узи - три. 
2. Доступность магазина ВЕЗДЕ. Эт, конечно, очень круто, что и на нашу станцию пришли идеи либертарианства, но точно так же ломает баланс. Сделать магазин доступным только в центральном доме или на спавнпоинтах.
2.1 Возможность срать бесконечными топориками и петушителями, закидывая ими оппонента.
3. От бросков человек не умирает. Только от ударов или попаданий пуль.
4. Ввести пропорциональную систему потери поинтов, 50% от каждой смерти. Условный робастер уважаемый член комьюнити патриот опуха 228, сделав три фрага, уже получает питон и магазин к нему, но при смерти теряет только один поинт, что как-бы не круто. Чем выше ты на пищевой цепи, тем больнее должно быть оттуда падать.
5. Сократить количество бутылок, а то весь геймплей сводится к "налутай водочку опусти водочку на темечко".
6. Флешка не станит. 
7. Сердце встает, из-за чего ты очень долго можешь умирать. Ввести кнопку "саккамб". 
8. Переломы убрали, но вот шрапнель в теле до сих пор делает тебе БОЛЬНО. 
9. После пяти минут интенсивных боев начинается сверхсильный лагач, воевать при котором невозможно. Сделать проверку на количество obj/decal/blood, если его больше условных трех сотен - удалять. Так же и с гильзами. Вызывать проверку каждые пять-семь минут.
10. Добавить логгирование ВР-пода, что бы избежать некоторых неприятных ситуаций. 

Тут я должен был обосрать всех, кто это кодил и не смог в баланс, но не буду - забанят за хейтспич. 
Мир, дружба, жвачка!

**Comment by Ruforce** [comment]
[J]  Arsenii (Royce Faust) complains, "Это. Смешное. Шизард с меткой и возвратом может лезть на станцию ВРхуманом."

**Comment by Rodial-Admiral** [comment]
1. Предлагаю стоимость питона повысить до пяти пунктов, потому как с него можно стрелять одной рукой - в отличие от дробовика, стоящего четыре пункта.
2. Согласен - пусть будет доступен в каких-то конкретных локациях. Не смотрел на карту, но выглядит приемлемо. А на спавнпоинты обратно насколько реально вернуться? Нужен ли закупочный пункт в домике?
Топорики - мем, пусть хоть чего-то стоят.
3. Каких бросков? Когда человека бросают, или в него что-то бросают?
4. 50% - вроде слишком много и фиксировано. Хотя, будет побуждать тратить очки.
Но если что-то будет стоить условных 5 поинтов - реально ли успеть сделать пять фрагов до того, как тебя убьют?
5. Согласен.
6. Мем какой-то, надо фиксить.
7. Согласен.
8. Осколки так же мешают, как и переломы. Если убрали переломы - надо убрать и эффекты от осколков, либо ввести возможность в полевых условиях легко решать вопрос с ними. Самостоятельно вытаскивая чем-нибудь, например.
9. Предлагаю гильзы тупо не выплевывать на таких з-уровнях или зонах. Зачем они нужны? Атмосферы в таких пострелушках от гильз, наверное, мало.
Кровь - да.
Либо по таймеру удалять, либо по спецкнопке какой-нибудь.
10. Логирование входа-выхода-емага-внешних операций? Ну, в принципе, резон есть.

**Comment by Ruforce** [comment]
>Каких бросков? Когда человека бросают, или в него что-то бросают?
Второе.

**Comment by Ruforce** [comment]
>А на спавнпоинты обратно насколько реально вернуться? 
>

Элементарно. Спавнпоинтов несколько штук и это просто комнаты по краям карты.

**Comment by Rodial-Admiral** [comment]
С бросками непонятно тогда. Должно, конечно, наносить урон.

Подумал на тему спавнпоинтов - с одной стороны, вроде как закуп по какой-то логике должен бы быть только там.
С другой - возвращаться на точки спавна чисто ради того, чтобы что-то купить, как-то не всегда хорошо. Плюс, на спавнах не должно быть большой концентрации людей, иначе прямо там выносить будут.

Пусть и на спавне, и в какой-нибудь зоне посередине.

**Comment by TobyThorne** [comment]
С карты уже убрали, иссуй на выпил ВРа из кода одобрен.
