### ISSUE TITLE
Робопринтеры в хирургии: ФАЙНАЛ СОЛЮШЕН

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#2060]
Преследуя Благую Цель Улучшения Качества Игры в Медблоке, ныне почивший геймдиз приказал выпилить оттуда органические принтеры.
Но, к сожалению, геймдиз был плох и, слава богам, сейчас у нас триумвират турбоежиков-трупов.

Чё предлагаю, лень мне расписывать все.
Вернуть органические принтеры в хирургию, убрав оттуда возможность печати конечностей, оставив это на откуп роботехам. Заменить сердце - пожалуйста, ставить ногу - на коляску и дрочить научников. В текущем состоянии у бедных механтроников осталась только одна задача - клепать боргов и мехов; раньше-то у них хоть монополия на протезы была, а теперь шиш с маслом.

**Comment by Voldirs** [comment]
А невидимые конечности из этого робопринтера пофикшены хоть?

**Comment by Ruforce** [comment]
Вроде как.

**Comment by Voldirs** [comment]
В прииииииинципе для врачей куда выгоднее работать с протезированными органами с текущей механикой потому что они не гниют, а это очень важный аспект, но а таком случае робототехники сосут хуи, в прочем как и обычно

**Comment by Ruforce** [comment]
Как вариант добавить для создания органа необходимость в перидаксоне.

**Comment by Voldirs** [comment]
Тогда робототехники сосут хуи ещё больше

**Comment by Ruforce** [comment]
Я про биопринтер, а не про робоговно.

**Comment by Voldirs** [comment]
Ну да, робототехникис сосут ещё больше потому что не смогут быстренько кому-то поменять органы ведь хуй им кто даст перик

**Comment by Ruforce** [comment]
Не-не. Я про то, что для создания БИОоргана нужно будет загорячиться с периком, а для создания робоговна - что-то ещё.

**Comment by Voldirs** [comment]
А, я понял. Оставить биопринтеры в меде, но сделать так чтобы он жрал мясо с периком. Хмммммммммм. Я бы не очень хотел усложнять жизнь врачей, потому что тут они без химиков реально не могут вообще нихуя сделать при отказе органов. Я привык относиться к химии как к тому что может потенциально облегчить твою жизнь как врача, но при это не расчитывать сильно дохуя на них потому что зачастую химики-еблонавты. А это изменение химиков-еблонавтов никак не поменяет. И тут у врача будет два варианта при отказе органов, первый это вздохнуть и добить умирающего, второй это ломать эбало химику и сметагеить себе перидаксон.

**Comment by Ruforce** [comment]
@Voldirs как вариант, можно положить в ящик банку с перидаксоном - юнитов двадцать-двадцать пять, по аналогии с мясом.

**Comment by Voldirs** [comment]
Ну мэйби

**Comment by Rodial-Admiral** [comment]
С перидаксоном выглядит адекватно.
Положить раундстартом достаточно, чтобы хватило на Т1-деталях (они же играют какую-то роль для принтеров, или и тут бейцы нормально не сделали?) распечатать полный комплект органов для случая с гниением всего. 
Хотят конвейером оперировать - пусть пинают химиков.
