### ISSUE TITLE
Technology trade

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#207]
Добавить возможность покупать\продавать технологии в каргонии, и тем самым получать профит(Пиздюлей от РнД), в виде денег для нужд станции, или получение технологий, что нельзя получить в РнД путём исследования.

В итоге, станет больше толку от каргонии, ну или просто мне так кажется.

К слову, если это так сложно провести через РнД, то можно за место добавления их  в каргонию, добавить товары в консоль торговцев. РнД их охотно скупит.

**Comment by LagannPM** [comment]
Если и делать это то после передела системы иследований

**Comment by YaridaTheDragon** [comment]
Одна идея ахуительнее другой просто. Сначала добавили возможность переводить денюжки в каргопоинты для заказа любых ресурсов, а теперь возможность ПОКУПАТЬ/ПРОДАВАТЬ технологии. 
Оба варианта - полная хрень, так как тут баланс полностью утерян.

**Comment by LagannPM** [comment]
Я не вижу ничего плохого в возможности покупать технологии.
А перевод денег в карго действительно нужно балансить

**Comment by YaridaTheDragon** [comment]
https://ibb.co/nRoiAK
Вчерашний скрин. Научка и без ресурсов качается достаточно высоко (если знать как), а с ресурсами качается до уровней как на скрине. Это, кстати, не максимум.
Против покупки технологий. Только после ребаланса РнД.

**Comment by Exapster** [comment]
Я не случайно же написал "что нельзя получить в РнД путём исследования". Это особые технологии, и их **НЕЛЬЗЯ** получить в РнД, путём исследования. Цена, конечно, покупки будет выше, а продажи ниже. Например: возможность создавать РИГи\скафандры; создание оружия(даже синди можно, если повезёт); возможно(слишком напряжно), какие-то новые мехи. Как по мне, цена за одну технологию(покупка) Должна быть где-то 10.000 тысяч кредитов, если это не торговец, а если не повезёт, и то выше.

**Comment by Cinericius** [comment]
#1046
