### ISSUE TITLE
Изменение анонса о прибытии нюки

### ISSUE THREAD

**Issue by kokokobold** [ChaoticOnyx/OnyxBay#2073]
Сейчас о приезде нюки сообщается огромными красными буквами, даже если они пытаются прикинуться торговцами — мало кто им верит, все сразу лезут брать пушки, чтобы начать воевать. Это сильно уменьшает простор для тактик, ни о каком стелсе не может быть и речи, все изначально враждебно настроены к приезжающим, никого не смущают крики в рацию о том, что мимо вирусологии пролетел космонавт в красном скафандре.

Как это можно исправить: дать возможность нюке через аплинк купить отключение этого анонса.
Ну или просто убрать анонс.

**Comment by Voldirs** [comment]
Покупка отключения анонса по идее должна принести некий элемент тимплея, когда команда всё же обсуждает что она будет покупать на кристаллы и с кем надо будет поделиться. Это хороший момент, несогласованность закупок должна приводить к последствиям. По цифрам, цену на такой девайс можно сделать в один полный аплинк

**Comment by koronoshka** [comment]
Аргументируй цену

**Comment by Voldirs** [comment]
Сначала свою предложи, я же из тех соображений чтобы скрытнонюка имела на четверть меньше кристаллов и чтобы была необходимо кооперация по расходам так сказать.

**Comment by Rodial-Admiral** [comment]
Предлагаю несколько вещей:

1) Если нюка запускает шатол в сторону станции в первые N (от пяти до десяти) минут, то оповещение не приходит. Пусть жертвуют планированием в обмен на большее число кристаллов.

2) За полный аплинк они все равно торговцами не прикинутся. Не то чтобы проблема только в анонсе - все равно, если нюкеров пропалят в нюкокостюмах, поднимется шум.
Половина аплинка - разумная цена, кажется. Есть же платы для телепортов
`/datum/uplink_item/item/tools/teleporter
	name = "Teleporter Circuit Board"
	item_cost = 40
	path = /obj/item/weapon/circuitboard/teleporter
	antag_roles = list(MODE_MERCENARY)`
Которые, по сути, и так дают стелс. Нахрена тратить весь аплинк, если можно за 40 кристаллов телепортнуться? Никто не будет тогда фичу брать.
Итого - думаю, 60 или 80 ТК.

**Comment by ArmolitskiyCarpoeb** [comment]
> 1. Если нюка запускает шатол в сторону станции в первые N (от пяти до десяти) минут, то оповещение не приходит. Пусть жертвуют планированием в обмен на большее число кристаллов.

а что им мешает за 5 минут собраться, улететь на шаттле к станции и там уже обсудить план?

**Comment by Rodial-Admiral** [comment]
Аутизм мешает. Ты много нюк видел?

**Comment by ArmolitskiyCarpoeb** [comment]
аааа, вспомнил, теперь понятно

**Comment by Rodial-Admiral** [comment]
5 минут - это не точно, конечно, но думаю, что за 2-3 минуты - время, которого, по идее, вполне должно хватать на то, чтобы натянуть костюмы и забрать с базы все, что надо - точно почти никто успевать не будет.

**Comment by Rodial-Admiral** [comment]
@Ruforce специалист по смешным нюкам, какие там обычно тайминги? Я редко обсервлю это дело в последнее время.

**Comment by Voldirs** [comment]
Первый вариант мне совсем не нравится, что мешает тупо кинуть всё в шаттл, полететь к телекомам и там всё спокойно обсуждать?

>Которые, по сути, и так дают стелс. Нахрена тратить весь аплинк, если можно за 40 кристаллов телепортнуться? Никто не будет тогда фичу брать.

Ооооо опять геймдезигнер не в курсе про то что телепортера больше нет)))

**Comment by Rodial-Admiral** [comment]
О, сдохший иссуй.

**Comment by Voldirs** [comment]
Но можно же закупаться после того как прилетел тогда, не?

**Comment by MrMagick2104** [comment]
> Но можно же закупаться после того как прилетел тогда, не?

Аннонс-то всё равно будет. Не обязательно делать его зависимым от того, сидят ли нюкеры на базе или нет.
Хотя, если закупаться по прилёту, нюкерам бонус будет по времени. Вообще, как бы, неплохая тактическая возможность.
