### ISSUE TITLE
Починить электрический стул.

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#21]
Не работает от слова совсем, имеет пару спрайтиков и кое-какую сборку, не без возможности применения.

**Comment by Demisov** [comment]
Сука, когда нам стул вернут.Шприцы с хлоркой так же невидимы как полгода назад.

**Comment by TermService** [comment]
о какой хлорке речь? Отпишите в дисскорд

**Comment by Cinericius** [comment]
Так это олдовый иссуй, про хлорку. Вот стул до сих пор не работает, да.

**Comment by Cinericius** [comment]
(соре не в дискорд)

**Comment by Epicus7** [comment]
Пофикшено в https://github.com/ChaoticOnyx/OnyxBay/pull/1106
