### ISSUE TITLE
Локализация языков

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#210]
Так же как с радио каналами
Сделать возможность писать ",и" вместо",b"

**Comment by Cinericius** [comment]
Хорошая тема, полезная, да.

**Comment by Penguineapig** [comment]
Как воды не хватает

**Comment by Doster-d** [comment]
#5127

**Comment by ITCups** [comment]
Пока сам не починишь никто не починит, три года прошло
