### ISSUE TITLE
Высыхание мыла

### ISSUE THREAD

**Issue by dnivji** [ChaoticOnyx/OnyxBay#2117]
На текущий момент мыло - самое мощное оружие ближнего боя, ибо одним только мылом можно убить любого человека вне зависимости от его брони, просто бесконечно катая его туда сюда-на мыльце и параллельно мудохая хоть голыми руками.
Предлагаю добавить мылу шанс, что если на нем кто-то проедется, оно исчезнет, оставив на месте себя тайл смазки. Ну или как-то по другому решить эту проблему.

**Comment by Ruforce** [comment]
Всё не так. Сейчас у мыла есть переменная wet, которая отвечает сам понимаешь за что. Сделать так, что одно катание на мыле зависит от этого и меняет переменную на ноль после того, как на бруске кто-то покатался.

**Comment by dnivji** [comment]
Так даже лучше!

**Comment by Voldirs** [comment]
Я чот не считаю это проблемой. Есть же банановая кожура, вода, причём вода имхо опаснее. На мыле всегда подскальзывались и так должно оставаться, а то пахнет бэйским нерфоцирком.

**Comment by TapKo4eB** [comment]
дело не в мыле
дело в слипах
ибо со временем понимаешь что полный кнок всего только от того что ты упал это слишком
тут надо переработать некоторые вещи кд стана/возможность совершаемых действий при падении/чё то ещё
дело короче на диздок тянет

**Comment by Rodial-Admiral** [comment]
> Epicus7 added the :godmode: просто label 29 days ago

haha oh wow

Тут надо действительно проработать все падения в принципе. И на кожурках тоже.

**Comment by PlinHost** [comment]
Можно пулл на мыло занерфить, чтобы не прокатывало. А если сам наступил - сам и виноват.

**Comment by TobyThorne** [comment]
Решено в #3072, мыло теперь и сохнет, и отлетает при поскальзывании.
