### ISSUE TITLE
Новый "голый" мех

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#212]
Прошу добавить меха, что не имеет брони, и представляет из себя голый экзоскелет, в который можно пихать различное оборудование(не тяжёлое). Мех(экзоскелет) должен будет иметь низкий запас прочности, а также невозможность вставить батарейки(если возможно) выше стандартной. Как по мне, два слота для экипировки, отсутствие брони, малый запас прочности(ниже одиссея), невозможность экипировать тяжёлое снаряжение - компенсируется его низкой стоимостью, а также мобильностью.

Давно хотел увидеть что-то подобное в СС, но и так не дождался, к сожалению.

**Comment by LagannPM** [comment]
Прежде чем трогать мехов нужно портануть код мехов с Европы или дождаться когда это сделают бейцы (они пытались, я видел)
