### ISSUE TITLE
Закинуть рикролл в жукбокс

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#2150]
### Улучшение
RICK ROLLED

### Решение
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by xmaebx** [comment]
10/10

**Comment by TapKo4eB** [comment]
мб шанс в 1/500 при включении любой песни вместо нужной будет играть рикролл

**Comment by PlinHost** [comment]
Спейс ассо, но играет невер гонна гив ю ап.
