### ISSUE TITLE
Кулдаун руны бладбойл.

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#2157]
https://i.imgur.com/OE1tjXM.png

Его нет. Руна разрывает за секунду.

**Comment by TapKo4eB** [comment]
это я гляну

**Comment by Rodial-Admiral** [comment]
@TapKo4eB глянул?

**Comment by kokokobold** [comment]
Технически, это оригинал, а #2203 дубликат, но там чуть получше обрисовывается проблема.
