### ISSUE TITLE
гетто химдиспенсер

### ISSUE THREAD

**Issue by pootis228why** [ChaoticOnyx/OnyxBay#2159]
Из 21 реагентов, в гетто хим.диспенсере только нужных 16

**Comment by Animesku** [comment]
Охуеть новость, а ты уже политринник с хлоркой там варить собирался?

**Comment by Doster-d** [comment]
Это не баг, а фича. Всего существует 3 вида раздатчика: из химии (21 реагентов), геттовский(16 реагентов), ЕРТшный (только лекарства)

**Comment by TapKo4eB** [comment]
ломись в химию/заказывай в карго, а не водокалий раундстартом
