### ISSUE TITLE
Подвинуть иконку мобов чейнджей чуть выше

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#216]
Подвинуть иконку мобов чейнджей чуть выше чтобы они могли незаметно прятаться под столами
![gif](https://user-images.githubusercontent.com/6437377/45269228-b646b400-b4b4-11e8-8d4e-5832a9cf0850.gif)

**Comment by Demisov** [comment]
Не такие они уж незаметные
