### ISSUE TITLE
Поднять с колен мышей

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#218]
Сделать поведение мышам 
- Чтобы они убегали от всех кто больше них
- Чтобы бродили и искали еду
- Если накушаются и найдут партнера - размножатся
- Сделать возможность посмертно перегрызть провод и добавить очень маленький шанс мышам без игрока это сделать

**Comment by PlinHost** [comment]
Респавнящиеся должны страдать. Либо отрезаем респавн за мышей, либо нерфим мышей.

>хайвмайнд для мышей

Это сразу в коллекцию платины.

**Comment by MalinaGirl** [comment]
Предлагаю тогда сделать отдельный режим про мышей-мутантов, где они бы зерграшом пытались расхуярить станцию в щепки ради всеобщего зла.

**Comment by hekko4** [comment]
Ты только что придумал свармеров

**Comment by LagannPM** [comment]
@Fourest 
Посмертно, значит ты сидишь опять гостом минимум 10 минут...
Ты тоже самое можешь сделать за человека и при этом не умереть
Ничто не мешает другим гостам зайти за дрона и починить это
И пускай инженеры работают (их никто не пикает потому что делать нехуй)

**Comment by LagannPM** [comment]
Это можно даже превратить в мини игру Мыши VS Дроны.
Где мыши пытаются расхуярить станцию , а дроны пытаются ее починить
Добавить мышам урон в 1-2 единицу и сделать поведение : Если в округе 5+мышей и они увидели дрона она начинают его зерграшить

**Comment by Cinericius** [comment]
Пожирание проводов и хайвмайнд нахуй, остальное можно.
Хочешь мышей с хайвмайндом - надо тогда уж пилить колдунских мозгокрыс из Planescape: Torment. Но на это щас нет ни времени, ни лишних рук.

**Comment by Cinericius** [comment]
#1031

**Comment by Epicus7** [comment]
> Если накушаются и найдут партнера - размножатся

И вот мы пилим ЕРП-билд.
