### ISSUE TITLE
Радиопеленг дереликтов 

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#2183]
### Улучшение

Я считаю, что приведенная ниже фича позволит посещать дереликты адекватным способом без ВОРТЕКСА или свободного полета. Также с полетами на дереликты можно разбавить раунд последствиями, следующими после посещения дереликтов(лаборатория? капитан сошел с ума и убил весь экипаж? корабль пиратов? и т.д.)

Значит так, добавляем консоль радиопеленга и радар, которые надо исследовать в РнД. Добавляем в научный отдел шаттл, который сможет посещать запеленгованные порты.
По легенде, на некотором расстоянии от станции уже есть спутник-пеленгатор. Вот мы включили консоль и видим данные первичного сканирования: расстояние от спутника и от станции до объекта. Далее мы напрягаем извилины и выбираем квадрат для вторичного сканирования, оно занимает 5 минут, чтобы нельзя было все квадраты прокликать быстро. 

В случае успешного пеленга мы получаем координаты дереликта на шаттл и можем отправлятся в путешествие!

### Дополнительная информация
Так же можно создать пул из нескольких кораблей/аванпостов/etc и подгружать только парочку в начале раунда. При успешном пеленге объекта можно выдавать гостоте роль выжившего. По легенде выживший пробуждается из криосна из-за сообщения о том, что приближается корабль. Получает в записи предысторию или выбор создать ее самому.

Для постройки радара потребуются машинный корпус, провода, топовый модуль сканирования и Ansible Crystal из РнД, для консоли печатаем плату и линкуем мультитулом.  Шаттл будет использовать водород в качестве топлива или нет(?), подобное видел у шаттла в казино, неплохо бы заставить это работать.

![SPOILER_unknown](https://user-images.githubusercontent.com/62109144/80311289-7f3b2880-87e7-11ea-8987-d68aaf2ebd68.png)

**Comment by MrMagick2104** [comment]
> дереликты адекватным способом без БоХа

А зачем Бег оф холдинг для этого?
> Шаттл будет использовать водород в качестве топлива или нет(?), подобное видел у шаттла в казино, неплохо бы заставить это работать.

В шаттле казино азот, емнип, но это меньшая из проблем. Дело в том, что у нас все шаттлы летают при помощи очень костыльно-велосипедной магии, без какой-либо нужды в двигателях или чего-то подобного. Собственно, содержимое обозначенных кодером или билдмодом педали клеток телепортируется в другую область, также обозначенную заранее. Никакого потребления топлива или чего-то подобного на данный момент нет. Либо, может, есть, но как огрызки кода с бея, которые сейчас не используются.
> Вот мы включили консоль и видим данные первичного сканирования: расстояние от спутника и от станции до объекта. Далее мы напрягаем извилины и выбираем квадрат для вторичного сканирования, оно занимает 5 минут, чтобы нельзя было все квадраты прокликать быстро.

Если предположить, что это будет настолько долго, по пять минут-клетка, так ещё и в половине клеток будет пустота, быстрее будет просто при помощи джетпака или чего-то ещё долететь до ближайшего дереликта за три минуты, что сейчас спокойно делается.

Имхо, вместо отдельного корабля и спутника, стоит сделать гейтавей на какие-нибудь другие локации, никак не связанные с текущим путешествием по космосу, с большим количеством опасностей, желательно не скриптованных, а рандомных, чтобы можно было собрать отряд из 4-5 человек и пойти на рейд, предварительно проведя какое-нибудь сканирование локации при помощи каких-нибудь собираемых прямо на станции или на телекоммах средств, максимум на полчаса после старта раунда, а потом благополучно помереть при штурме какой-нибудь лаборатории или базы синдиката. 
Дереликты так и так уже представляют из себя возможность для того, чтобы сбегать в космос за лутом на пять минут, ибо они, пусть и прибавили недавно в количестве, крайне однообразные. Единственным дереликтом, где сложно было заучить всё, была Лар-Мария, на которую нельзя было попасть из-за неправильного маппинга. Они невероятно безопасные, там почти нет никаких врагов дальнего боя, хотя у нас полно всяких простых мобиков, вроде русских или синдикатовцев, которые спокойно могут развалить плохо подготовленных исследователей космоса. Следует как-то сначала решить проблему разнообразия и сложности дереликтов, прежде чем перепиливать способ того, как добраться до них, ибо сейчас ты будешь просто летать к трём-четырём локациям, на которых помереть довольно сложно, а также эти локации будут приедаться, ибо игрокам видно, как их немного.

**Comment by Kexilex** [comment]
Думаю, не должно быть такого, чтобы люди могли летать по дереликтам на джетпаках и петушителях, они же не на расстоянии десяти километров друг от друга находятся. Перемещение должно быть на шаттле или бохе. 

Другая проблема в том, что дереликтах нет ничего кроме пушечек, остальное можно и без дереликтов достать. 
Что там может быть еще? 
1. База синдиката с ПУШЕЧКАМИ, может ригом, какой-нибудь документацией.
2. Медицинский центр с кишками, инструментами, мемными вирусами в холодильнике.
3. Станция одинокого ИИ? Одинокого генососа? Там есть датадиски для РнД?
4. Шахтерский аванпост с выжившим и кучей трупов за заболтированной дверью?(отсылка луна 2112)

Нужны идеи. Такие дереликты могут быть размеров с научный отдел, больше не нужно. Как вариант, на этих дереликтах можно оставить датадиски для РнД, без которых не продвинутся по исследованиям(БоХа, например?). Диск в сейфе/пк, а там пароль, а вот поройся в бумажках на дереликте, может найдешь что-нибудь. А может еще ксеноархеологию приплести к технологиям РнД, исследование должно быть, а не дроч консоли.

**Comment by MrMagick2104** [comment]
> Думаю, не должно быть такого, чтобы люди могли летать по дереликтам на джетпаках и петушителях, они же не на расстоянии десяти километров друг от друга находятся.

Можно разделить дереликты на дальние и ближние. До одних, которые есть сейчас, можно добраться пешком и только пешком (они нужны, ибо иначе космонавты, случайно улетевшие в космос, будут дико скучать, а объяснить это можно тем, что большинство из них - корабли и станции - обладают глушителями радаров/особым отражающим покрытием/etc. из-за чего пеленгатор их заметить не может), а до дальних - только на корабле.
> бохе

БоХ - рюкзак. Как на нём летать?
> Как вариант, на этих дереликтах можно оставить датадиски для РнД, без которых не продвинутся по исследованиям(БоХа, например?)

Идея хорошая.
> А может еще ксеноархеологию приплести к технологиям РнД, исследование должно быть, а не дроч консоли.

Уже есть, но у вещей с ксеноархеологии уровни исследований крайне низкие, из-за чего они бесполезны.

**Comment by Kexilex** [comment]
> БоХ - рюкзак. Как на нём летать?
 Оу, совсем чердак потек, да, вортекс.

**Comment by Voldirs** [comment]
Ого, сер, вы придумали овермап?
Ой а его спилили с опуха когда бэй откручивали. Хотя мб какой-то код и остался

**Comment by Rodial-Admiral** [comment]
О!
Возможность посещать все эти бесконечные з-уровни при помощи специального научного шаттла - это очень полезная идея.
Сейчас у шаттлов (некоторых) есть выбор точки назначения. В принципе, не думаю, что менять список точек назначения - сложно.

**Comment by Rodial-Admiral** [comment]
> По легенде, на некотором расстоянии от станции уже есть спутник-пеленгатор.

Телекоммы же.

**Comment by Rodial-Admiral** [comment]
Я бы вот как сделал:

Небольшое число дефолтных локаций находятся на плоскости XY с Z = 0, где уже "лежат" станция и спутник телекоммуникаций. Астероид, думаю, сюда включать не стоит, потому что тайлов космоса там нет. 

По умолчанию доступны станция и телекоммы, на обоих стоит оборудование для пеленга. 

За счет двух узлов получаешь инфу о каком-то еще объекте на XY0-плоскости. Узлы выдают тебе тупо список всех расстояний, которые у них есть. Задача юзера - ткнуть в квадрат и подождать энное время.

Чтобы получить доступ к условно-продвинутым локам, надо поставить еще один узел на какой-то из свежеобнаруженных локаций. Т.е. притащить оборудование, запитать его и связать со станцией. Тогда ты получаешь уже три списка расстояний до объектов и возможность сканировать квадраты с оффсетом по Z.

**Comment by Voldirs** [comment]
>Астероид, думаю, сюда включать не стоит, потому что тайлов космоса там нет.

Сер, вы опять отстали от опуха, там уже есть тайлы космоса и туда можно попасть через границу з-уровней

А не проще это запилить на базе овермапа? Все эти радиусы, оборудования? Так то звучит неплохо, но я бы сделал это в рамках плоского пространства, как на овермапе. З-уровни на абстрактной карте это перебор

**Comment by Rodial-Admiral** [comment]
На базе овермапа придется овермап возвращать.

**Comment by Rodial-Admiral** [comment]
Но от плоского пространства тоже можно играть.
Тогда нужен будет "радиус покрытия". Чтобы попасть в локацию, она должна быть в радиусе покрытия одного (или двух, если мы хотим сделать процесс чуть более хардовым) пеленгующих аппаратов. 
Думаю, все-таки одного, а станцию по умолчанию считать уникальной точкой отсчета.

**Comment by Rodial-Admiral** [comment]
Надо выбрать один из двух вариантов.

**Comment by Rodial-Admiral** [comment]
Ну или ни один из них, если нам это не надо. Но я считаю, что это оживит экспедиции по з-уровням.

**Comment by Rodial-Admiral** [comment]
Абстрагируясь от пеленга - на тему выживших.
Есть зоны, в которых их присутствие очень удобно и логично. Разбившийся корабль с НЕХами, например. Но я бы триггером сделал, в таком случае, не прибытие на з-уровень любого хумана, а прилет туда исследовательского шаттла именно что. 
Тогда у обсерверов работала бы кнопка "Join as Survivor" по аналогии с респонс тимом. И с выбором из доступных точек спавна.

**Comment by anihillator** [comment]
На тему экспедиций в космос- добавьте возможность обвязаться веревкой/кабелем а-ля покорители горных вершин, а то экспедиция разлетится по космосу и уровням.

**Comment by Rodial-Admiral** [comment]
Веревкой от исследовательского шаттла?

**Comment by Rodial-Admiral** [comment]
Но замечание резонное - нужен девайс, который бы показывал местоположение шаттла

**Comment by anihillator** [comment]
Вообще я предлагал друг с другом всех связать, как более надежный пулл.
Но и к шаттлу тоже было бы неплохо маячок иметь.

**Comment by Rodial-Admiral** [comment]
На тему астероида - там в любом случае вряд ли есть, где шаттлу пролететь.

**Comment by Rodial-Admiral** [comment]
В принципе, локаторы маячков уже есть, но ими никто не пользуется.

**Comment by Rodial-Admiral** [comment]
И это не так удобно, как аппарат по типу пинпоинтера, который тупо стрелочкой бы указывал на шатол и графически и звуком отображал расстояние.

**Comment by Voldirs** [comment]
>На базе овермапа придется овермап возвращать.
Вернуть овермап на билд, откуда его вырезали наверное будет проще чем городить абстрактную систему с нуля, котороая выльется в тот же овермап?

**Comment by Rodial-Admiral** [comment]
Не уверен. Там же другая система рандомивентов - метеоры стукают не ивентконтроллером, а по факту влета в метеорфилд на овермапе.

**Comment by Voldirs** [comment]
И так и так можно. Сам на жрисе видел рандомные метеориты даже вне поля

**Comment by Rodial-Admiral** [comment]
Но что делать с движением станции по овермапу? А если она влетит в поле метеоров и застрянет там до конца раунда? 

И не нужно ли тогда будет перепиливать механику работы шаттлов?

**Comment by Rodial-Admiral** [comment]
> А если она влетит в поле метеоров и застрянет там до конца раунда?

Хотя в этом-то как раз ничего плохого нет

**Comment by Rodial-Admiral** [comment]
Просто, как мне казалось, суть овермапа, среди прочего - в движении по овермапу. Хоть чего-то.

**Comment by Voldirs** [comment]
>И не нужно ли тогда будет перепиливать механику работы шаттлов?

>Возможность посещать все эти бесконечные з-уровни при помощи специального научного шаттла - это очень полезная идея.

bruh

**Comment by Rodial-Admiral** [comment]
Летающий мини-тор4?

Ставлю класс.

**Comment by Rodial-Admiral** [comment]
Кстати да, а почему бы и нет.

Научный корабль сделать тор4ем в плане основных механик. Станцию - просто локацией.

**Comment by Voldirs** [comment]
Ну да, надо будет шатолы переделывать. Но вообще без интересных дереликтов это всё бессмысленно. А интересных дереликтов нет. В казино летают за магнумом, На снежную штуку летают за шмотом, материалами, пушечками. Говно короче

**Comment by Rodial-Admiral** [comment]
Пусть научный корабль двигается по овермапу, ограниченный "радиусом покрытия" неких ретрансляторов и самой станции.

**Comment by Rodial-Admiral** [comment]
Это интереснее, чем прыжки шаттлом по "исследованным" локам, и можно хоть в экспедиции играть, при этом не переделывая всю станцию под тор4.

**Comment by Voldirs** [comment]
Да было бы что исследовать. Татар вон запилил дереликты, прикольненькие, функциональные местами, но смысла в них нет потому что люди и так знают что там. И я бы сказал что сначала надо как-то это фиксить, но это очень сложно фиксить потому что нужен очень качественный рандомизатор карт, с продвинутой логикой. А это гораздо сложнее того же сторителлера

**Comment by Rodial-Admiral** [comment]
Мобов досыпать, спавнящихся только в присутствии хуманов. Пусть в каэсик играют.

**Comment by Voldirs** [comment]
Ловушек надо интересных. Мобы хуйня.

**Comment by Rodial-Admiral** [comment]
Ловушка, спавнящая мобов - тоже вариант.

А какие еще? Растяжки с лимитками?

**Comment by Voldirs** [comment]
ловушка, типа капкана, из которой нельзя выбраться без помощи другого человека например, ну или можно, но потеряв ногу например

**Comment by Wuattt** [comment]
![maxresdefault](https://user-images.githubusercontent.com/34631419/82500532-33d11d00-9afc-11ea-88be-06a3d8fd883e.jpg)

**Comment by Wuattt** [comment]
![image](https://user-images.githubusercontent.com/34631419/82500596-519e8200-9afc-11ea-8d36-ea9356145f4f.png)

**Comment by Kexilex** [comment]
Выпилить Вортекс, впилить научный шаттл, when?

**Comment by MrMagick2104** [comment]
> Выпилить Вортекс

Казалось бы, при чём тут Украина?
Если судить по теме иссуя, достаточно заблокировать з-уровни дереликтов для перемещения вортексом, не?
Зачем его выпиливать?

**Comment by Kexilex** [comment]
Да, все таки Вортексу нужен реворк, а не выпил, чтобы нельзя было без остановок прыгать и перемещаться по z-лвлам не считая маяков, но это уже совсем другой иссуй.

**Comment by Kexilex** [comment]
Говно какое-то, мне не нравится.
