### ISSUE TITLE
Разнёрфать РИПЛИ из ада нёрфоцирка

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#2185]
### Улучшение
РИПЛИ - абсолютное, бесполезное говно, тратящее время и ресурсы робототехников вникуда, путающее новичков статьями на вики о своей полезности и так далее.
Почему он - говно?
Как минимум по той простой причине, что он, как бы это не было смешно, бурит медленнее обычного ручного бура, который ещё и бесплатный. Казалось бы, раньше это не было такой проблемой. Но, сейчас:
![autistic](https://user-images.githubusercontent.com/58848742/80317541-28e0e080-880d-11ea-981a-b9f1b81ff03b.PNG)
Обычный РИПЛИ, с обычным буром, стоимостью в очень много листов стали (60, что-ли?) нахуй не нужен. Его место - на помойке, учитывая этот нёрф.
Кроме того, даже до этого апдейта, он был всё равно хуже обычного копания буром или любыми другими средствами:
Во-первых, РИПЛИ невероятно медленный. Пока ты им ищешь ресурсы, пройдёт уже час-другой. Но, это можно ещё оправдать его массивность и принципом работы.
Что же нельзя оправдать массивностью и принципом работы, так это то, что он сделан не из 60 листов стали и 5 листов пластали, а из какой-то фольги от шоколадки, которую нашли на помойке. РИПЛИ спокойно ломается вообще ЛЮБОЙ живностью с астероида, даже обычными крабами или ховерхедами, которые представляют из себя самых рядовых противников. Не стоит говорить уж о том, что даже Пун-Пун с палкой-копалкой и не самым робастным игроком внутри может закликать Рипли в бою один-на-один.
Во-вторых, как уже было выше сказано, копать на РИПЛИ в промышленных масштабах какие-то залежи теперь тоже нельзя:
Обычный бур вообще не копает, а алмазный не нужен, ибо, когда у РнД уже есть алмазы, шахтёры спокойно могут себе попросить ручной алмазный бур или кирку, которые лучше его.
### Исполнение
1) Баффнуть ХП РИПЛИ, чтобы он мог хотя бы с двумя-тремя мобами справляться без починки или утечки кислорода с дезориентацией.
2) Увеличить скорость (опционально) передвижения РИПЛИ хотя бы чуть-чуть, а то инвалид на каталке его спокойно обгоняет.
3) Ревёртнуть область бурения стандартного бура в три, вместо этого повысив скорость бурения у алмазного бура.

**Comment by Rodial-Admiral** [comment]
ХП у них действительно очень мало.

По скорости - не хочется, чтобы раундстартом сразу клепались быстрые рипли. Надо продумать, как их скорость должна увеличиваться с течением времени.

Область бурения не вижу смысла ревертать, пусть все мехобуры копают 3x1, это более чем резонно.

**Comment by MrMagick2104** [comment]
> Область бурения не вижу смысла ревертать, пусть все мехобуры копают 3x1, это более чем резонно.

Это починили в #2194, тогда у нас обычный бур копал 1х1, а не 3х1.
> По скорости - не хочется, чтобы раундстартом сразу клепались быстрые рипли. Надо продумать, как их скорость должна увеличиваться с течением времени.

Может быть, впилить какой-то модуль из уровней научки, который бы повышал скорость хотя бы чуть-чуть для РИПЛИ?

**Comment by TobyThorne** [comment]
Outdated issue.
С тех пор Рипли уже потыкали, пофиксив буры, увеличив урон и дав возможность крафтить ускорители и Т3-буры.
