### ISSUE TITLE
У научного борга поломаны инструменты

### ISSUE THREAD

**Issue by Poromoks** [ChaoticOnyx/OnyxBay#2192]
Поиграл я тут за научного борга и столкнулся с рядом проблем:

1. Взяв батарею в захват (gripper), борг (не только научный, к слову, с другими та же проблема) не может вставить её в recharger, cell charger или PSU. В первых двух случаях ничего не происходит, в последнем - пишет, что нет доступных слотов для батарейки, хотя слоты есть. Человеческими руками всё спокойно вставляется.

2. Тот же научный захват не может подбирать протезы. Имеются в виду части тела и органы, которые делаются в prosthetic organ fabricator и нужны для синтетических людей. Соответственно, можно сделать тело с головой в robotic fabricator, но руки-ноги ему прицепить не получится. 

3. Научный борг не имеет среди своих инструментов мультитула, из-за чего не может вытащить батарею из синтетических людей (ведь им, в отличие от боргов, её нужно сначала отсоединить), дабы потом поставить улучшенную. И даже если бы имел, он, как было сказано во втором пункте, не смог бы её подобрать, чтобы потом поставить на место.

**Comment by Epicus7** [comment]
В идеале надо было разбить на несколько иссуев, но ладно, пусть так висит пока.

**Comment by Doster-d** [comment]
Занимаюсь этим иссуем.

**Comment by Doster-d** [comment]
Готово, скоро сделаю ПР

**Comment by Epicus7** [comment]
> Взяв батарею в захват (gripper), борг (не только научный, к слову, с другими та же проблема) не может вставить её в ... **или PSU**.

Вынес это в отдельный иссуй, так как не покрывается ПРом выше.

**Comment by Doster-d** [comment]
Recharger вроде так и хотели оставить для людей
