### ISSUE TITLE
Обновить и добавить внутриигровые мануалы

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#220]
По возможности на обоих языках

**Comment by Demisov** [comment]
Это файлы в html.Ты просишь перевести их или что?

**Comment by LagannPM** [comment]
Многие из них уже не актуальны.И не только перевести, перевод это второстепенная задача, в основном это починить старые и добавить новые для всего возможного в игре.
Начиная от работы карго и заканчивая как пользоваться оружием.
Таким образом можно помочь новым игрокам и убрать зависимость от неактуальной вики

**Comment by Demisov** [comment]
Тут нужен челик, который не пробовал на информатике как делать веб-страницы в аштимиэл

**Comment by Cinericius** [comment]
Причем тут геймдизайн кек?

**Comment by Epicus7** [comment]
Конкретики ноль. Какие мануалы, что в них обновить, какие добавить, зачем переводить?

Короче в топку
