### ISSUE TITLE
Крафтящиеся тазеры.

### ISSUE THREAD

**Issue by dnivji** [ChaoticOnyx/OnyxBay#2205]
На текущий момент, в гетто можно собрать много разного летального оружия - зипган, дробовик, арбалет, молчу о капканах, бомбах и прочих веселых и смертельных штуках. 
Но почему нельзя создать тазер? Его не могут делать даже ученные в протолате. 
Предлагаю запилить крафт тазеров из стали, пластика, парочки конденсаторов, баттареи, мультитула и микро-лазера.

**Comment by xmaebx** [comment]
Но у ученых есть станревольверы, а дать возможность каждому второму бегать с тазером = дать обезьяне в руки гранату без чеки.

**Comment by dnivji** [comment]
Так это надо будет где-то напиздить все материалы, что уже доступно не каждому второму, и знать про рецепт, который, мы, конечно, в открытый доступ выкладывать не будем - кому надо, найдет в коде или на гитхабе.

**Comment by xmaebx** [comment]
А, ну. Тогда нормально, в принципе, если рецепт на всеобщее обозрение не выкидывать.

**Comment by xmaebx** [comment]
Так у ученых станревольверы есть, те же яйца, только вид сбоку.

**Comment by ArmolitskiyCarpoeb** [comment]
> Да и спрайт другой нужен по-хорошему. 

а я спрайтер, я тутачки если че

**Comment by Voldirs** [comment]
На самопал в 12-м калибре можно сделать патроны со стансферами. Вот тебе и тазер

**Comment by Rodial-Admiral** [comment]
Есть самодельные станпроды, есть самодельные арбалеты.
Тазер видится мне чем-то, что нельзя собрать из металла и палок. 
Т.е. да - ты можешь собрать штуки, бьющие током на ближней дистанции, можешь собрать нечто, что бьет раскаленными прутами или стреляет дробью - но тазер на этом фоне явно более продвинутый.
Плюс, потеряется значительная часть смысла в таргетинге шкафов СБ ради тазеров.

**Comment by Rodial-Admiral** [comment]
Ну и на самопал можно сделать станпатроны, да.
