### ISSUE TITLE
Поднять с колен маленьких ящериц

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#221]
Добавить поведение
Может быть дать возможность мутировать если подвергаются радиации и стать ashwalker'ом (агресивным мобом)

Потому что они бесполезны, появляются при мини ивентах и никак не влияют на работу станции

**Comment by Demisov** [comment]
Просто дай гостам за их заходить и что мышам что им давать возможность залезать под одежду.

**Comment by LagannPM** [comment]
нахрена им залезать под одежду ?
такой механ есть где ?
они сами по себе бесполезны как и мыши, вот пауки например вырастают и едят персонал, их есть смысл истреблять

**Comment by Demisov** [comment]
Заставлять людей раздевается, вот ты разделся, а у тебя ящерицы/мыши всё что плохо лежит растащили и сгрызли.

**Comment by LagannPM** [comment]
ну это конечно тоже идея, и да это будет влиять на людей, но что то я не вижу логической причины зачем им залазить на того кого они должны бояться

**Comment by Demisov** [comment]
Пытается искать логические объяснения тому, что творится на станции.Загнанная в угол мышь должна кусатся, хоть и не больно.Некоторые люди за мышами по приколу гоняются.

**Comment by Demisov** [comment]
Предлагаю воспользоваться механом бореров.Игра проверяет ли есть ли на космонавте одежда, пока не снимет мышь/ящерицу нельзя согнать.Пока их не согнали, у них есть три абилку:вылезти, цапнуть и пощекотать.

**Comment by Cinericius** [comment]
Ашвалкеры жирно, да и смысла мало, это надо чтобы мини-ивенты с ящерицами и радиацией совпали, причем в конкретной последовательности, а это не так уж часто происходит, скорее даже очень редко.

Лучше самих ящериц поменять. Сделать их кусачими и ядовитыми (слабенький брут в пятки/ноги/жеппу/кисти + инъекция 5 юнитов яда), причем с рандомным веществом в качестве яда. И пущай еще размножаются, да, и чем их больше - тем они агрессивнее (скажем, при появлении человека в области зрения они делают проверку на ящериц, тоже видящих этого человека). А биохуд, скажем, пущай защищает от них (ура, работа для уборщика).

**Comment by Cinericius** [comment]
Яды - разные кислоты и токсины, от политриника и форона до спейсдрагсов и сопорифика (но вот хлорку, нейротокс и зомбипорошок не надо, слишком имбово).

**Comment by Cinericius** [comment]
А, ну и да, у всех ящериц из одной популяции (одновременно отспавненных или рожденных от одновременно отспавненных) яд одинаковый.

**Comment by Cinericius** [comment]
Тык
