### ISSUE TITLE
Runtime in timer.dm,112: Invalid timer

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#2220]
`[15:32:43] Runtime in timer.dm,112: Invalid timer: Timer: -1, TTR: 33083.3, Flags: TIMER_UNIQUE, TIMER_OVERRIDE, callBack: [0x2105ac16], callBack.object: Cargo Docking Hatch[0x200cc5a](/obj/machinery/door/airlock/external), callBack.delegate:/obj/machinery/door/airlock/close() timer.timeToRun=33083.3||QDELETED(timer)=33084.6||world.time=33085.2||head_offset=32620.2||practical_offset=747||timer.spent=1<br />`

Round ID: b6U-ckZM | 2020/04/29

**Comment by Epicus7** [comment]
Короче скорее всего сработал удаленный таймер. Чтобы понять наверняка залил PR с фиксом дебажного вывода.

Если подсистема таймеров вызывает удаленные таймеры - то это жепа, надо чинить подсистему таймеров. Тут надо будет либо поискать фиксы на Бее, либо стащить таймеры с ТГ, либо снести вообще таймеры нафиг и не мучаться.
