### ISSUE TITLE
Ограничить вызов шаттла только z-уровнями самой станции

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#2233]
Почему бейский долбоеб убрал ограничение на вызов шаттла со всяких дереликтов я не совсем знаю и не совсем понимаю. Это создает о ч Ен Ь и Нт Ер Се Ны е ситуации, в которых ребенок с вортексом уныло дрочит консоль связи на условном казино, отзывая шаттл раз за разом.

**Comment by MalinaGirl** [comment]
ВОРТЕКС СНЕЙКС РУЛЗ!

**Comment by Epicus7** [comment]
Не баг, а фича. Перевешиваю плашки

**Comment by Epicus7** [comment]
Вообще не понятна физика этого ограничения. Нерфоцирк это конечно прикольно, но можно, если и ограничивать, то как-то это обосновать ингейм?

**Comment by PlinHost** [comment]
> Вообще не понятна физика этого ограничения. Нерфоцирк это конечно прикольно, но можно, если и ограничивать, то как-то это обосновать ингейм?

На ЦК проверяют, откуда сигнал пришел.

**Comment by Epicus7** [comment]
Это как. Расстояние от ЦК до станции несравнимо больше расстояния между станцией и астероидом.

**Comment by PlinHost** [comment]
Так же, как и шаттл точно знает куда лететь.
