### ISSUE TITLE
Пассивная регенерация генокрадов криво работает

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#2234]
### Описание бага
Пассивная регенерация генокрадов в целом работает, но у неё есть довольно часто встречаемое исключение, при котором она не работает.
Если пассивная регенерация была включена ДО получения урона и на момент получения урона генокрад имел 0 любого урона, то пассивная регенерация вообще никак не работает.
Если она включена после получения урона или у генокрада уже был дамаг и работающая пассивная регенерация, то она работает правильно.
Гифка с ВВ для понимания. Если наносить урон любыми внутриигровыми методами, ситуация такая же. Регенерация не происходит даже в случае, если конечность с уроном была оторвана или ампутирована.
![crimnge](https://user-images.githubusercontent.com/58848742/80823967-35d34a80-8be6-11ea-8502-f6088b803e4a.gif)

**Comment by TobyThorne** [comment]
Исправлено в #7084
