### ISSUE TITLE
Переписать органы

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#224]
Сделать чтобы хозяином органов были mob/living/carbon вместо mob/living/carbon/human
Чтобы иметь органы могли все углеродные существа 
И убрать такой пиздец как Ксеноморфы подтип Хумана

**Comment by Cinericius** [comment]
Хорошая тема, обобряю, для планов по ксенобиологии и генетике так и вовсе необходимая.

**Comment by Rampoch** [comment]
Это круто конечно, но на сколько муторно? Или там можно все через замену сделать?

**Comment by LagannPM** [comment]
все отсылки к хозяину органа внутри папку модуля "органы" придется переписать на карбон, все проки для работы с органами перенести из хумана в карбон

**Comment by SilenceInsider** [comment]
Чтобы что?

**Comment by Cinericius** [comment]
Надо подумать насчет этого, не увеличит ли оно нагрузку на мобконтроллер до запредельных значений. Аналогично для всех прочих "хуманизаций" мобов.

**Comment by TobyThorne** [comment]
Реализуемо путём анального переписывания половины кода, но при этом особых (по крайней мере, очевидных) плюсов от этого не проглядывается. Ксеноморфы в виде расы уже вполне прижились. Пусть хеддев переоткроет, если не согласен.
