### ISSUE TITLE
Нету возможности зайти в игру или не удается отобразить эту страницу

### ISSUE THREAD

**Issue by asdasdasdasqeqwew** [ChaoticOnyx/OnyxBay#2251]
### Описание бага
После окончания раунда и его автоматического рестарта у меня вместо панеля на котором обычно Ready or No ready и сетапа Не удается отобразить страницу

### Воспроизведение
Шаги чтобы воспроизвести баг:
Не знаю как!

### Ожидаемое поведение
Четкое и понятное описание того, что должно было произойти.

### Скриншоты
Если проблема может быть показана на скриншотах - прикрепите их
![Без названия (1)](https://user-images.githubusercontent.com/40051569/80909871-48708f80-8d5e-11ea-8bce-3c4c8d1e8b10.png)
![Без названия (2)](https://user-images.githubusercontent.com/40051569/80909881-6c33d580-8d5e-11ea-8bed-02157fa3fe1c.png)

### (Опционально) Дополнительная информация
Реконнет не помог.

### (Опционально) Характеристики
 - OS: Щиндовус 7
 - Версия клиента 512
 - Версия сервера Server Revision: 49a1be8a91643f512d76d908ad8f527ffee1eac0 - release/chaotic - 2020-04-22
 - ID игры b6Y-bqHA

**Comment by dnivji** [comment]
Проблема на стороне клиента.
