### ISSUE TITLE
Добавить кнопку Deploy Hardsuit в панель сверху

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#2252]
### Улучшение
У хардсьютов (ака РИГи, ака ИКСы) есть в панели управления вёрб Deploy Hardsuit, который практически бесполезен, потому что пока ты переключаешься между кучей панелей, допустим, когда тебе нужно разложить РИГ из-за разгерметизации, тебе уже тысячу раз порвёт лёгкие/сломает руки вакуумом/откусят ноги карпы/etc.
Если добавить кнопку быстрого развёртывания РИГа в панель сверху, то это будет крайне удобно и развёртывание будет именно быстрым, а не со скоростью поиска вёрба в куче вкладок.
В качестве иконки можно использовать либо иконку самого модуля управления, как предмета, либо нагрудной части.

**Comment by Animesku** [comment]
Макрос поставь

**Comment by MrMagick2104** [comment]
О возможности ставить макросы я знаю.
Проблема в том, что большинство игроков ими всё равно не пользуется, да и по удобству интерфейс всё-таки интуитивнее и более просто, нежели макросы.
Иначе, зачем вообще делать какой-то интерфейс, кнопочки REST там в него добавлять, RESIST всякие, если можно на макросах играть?

**Comment by Rodial-Admiral** [comment]
Я бы подошел к этой проблеме иначе и сделал РИГам худ с основными кнопками

**Comment by MrMagick2104** [comment]
> Я бы подошел к этой проблеме иначе и сделал РИГам худ с основными кнопками

Переключения модулей и визоров дико не хватает, но мне лень было расписывать целый иссуй по всему этому.
Хочется, чтобы была возможность иметь колесо модулей или что-то такое, чтобы можно было переключаться не занимая много места на экране. Плюс, выключение в префах.
