### ISSUE TITLE
Новый интерфейс для Автолата

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#226]
Сделать возможность печатать сразу несколько элементов и не обновлять интерфейс после каждого напечатого
Можно спиздить с другого билда

_**[GameDisUpd:] Можно сделать очередь как в протолате.**_

**Comment by Cinericius** [comment]
#1113

**Comment by DarkHunter7756** [comment]
На текущий момент ввод в автолат нескольких команд на распечатку сделает их параллельно друг-другу, баг-не баг, хрен его знает. Фича сделалась сама-собой?

**Comment by NefrNerf** [comment]
Да, фича сама собой сложилась, если и трогать КД на печать, то это уже другой иссуй. #5478
