### ISSUE TITLE
Будучи вне состояния адекватно перемещаться - можно упасть в Disposal Unit

### ISSUE THREAD

**Issue by IvanDonFon** [ChaoticOnyx/OnyxBay#2260]
### Улучшение
Когда Ваши ноги не слушаются вас - и ходят в случайное направление(Опьянение, флеш, сильная доза обезбола) - если вы будете ходить на Run'e - можно будет свалиться в Disposal Unit
### Пример
Дурачка оглушили флешкой, а он не совладал с ногами - и упал в мусор. Если это был ассистент - по назначению. Кто-то набухался - и перепутал дверь с мусоркой. Упал.

**Comment by Moscowchief** [comment]
Вай нот, аппрув. Теперь из бара надо будет выходить аккуратней.

**Comment by Rodial-Admiral** [comment]
Аппрув.
