### ISSUE TITLE
Конфликт законов емагнутного борга.

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#2285]
![dreamseeker_71UKFqASAX](https://user-images.githubusercontent.com/63337306/81147516-e305e400-8f93-11ea-9e31-dd158ffd435f.png)

Нулевой закон пишет про masters, хотя должно быть operatives.

**Comment by TapKo4eB** [comment]
не оперативс а операторс

**Comment by TheUnknownOneGH** [comment]
> идеальным солюшеном будет изменить все упоминания влавствующих лиц на операторов "operators"

Это в смысле вообще везде в законах боргов/ИИ или только в емагнутых?

**Comment by TapKo4eB** [comment]
![image](https://user-images.githubusercontent.com/48761132/81167716-5d3b6600-8f9e-11ea-8ee5-61be21689734.png)
