### ISSUE TITLE
Понерфить суперматерию

### ISSUE THREAD

**Issue by Tsurupeta** [ChaoticOnyx/OnyxBay#2289]
### Улучшение/Баг
Основная идея: материя не пишет ничего в радиоканал, если стоит на тайле космоса. Также материя взрывается с просто неебическим радиусом, если её банально вытащить на тайл космоса и дать там перегреться. Итог: ультимативная грифмашина, которая взрывает пол станции за 5 кликов.

### Решение
Пофиксите материю, уменьшите ей кап или сделайте так, чтобы она срала в чат как ебанутая. Либо сделайте так, чтобы её было не так просто взорвать на уровень ПИЗДЕЦ. Пожалуйста. От таких взрывов (Сегодня первый же мой взрыв, который я видел, имел в себе числа 20 40 80. ЗАДУМАЙТЕСЬ) сервер зависает секунд так на 20 точно, если не больше. А потом цепной реакцией половина баков на станции так же взрывается. Ну это, блин, как-то слишком грифонисто, учитывая что ньюфаги взрывают материю и они не в курсе, что при плохих обстоятельствах эти взрывы достигнут ебанических масштабов.

**Comment by ArmenianOnyx** [comment]
В дискорде удалил предложение потому что тебя засрали и ты решил сразу на гитхаб кинуть

**Comment by ifromspaceGANG** [comment]
**ЗАДУМАЙТЕСЬ** и даже **НАЙДИТЕ** этих людей!

**Comment by Animesku** [comment]
Че думать-то. Хекоч

**Comment by TapKo4eB** [comment]
revert it

**Comment by Epicus7** [comment]
Вот PR с обновлением суперматерии: #1591.

Хз зачем нерфить, по-моему, материя и должна взрываться на полстанции. Не вижу ничего плохого.

**Comment by Voldirs** [comment]
Не надо нерфить ничего, сейчас заебца бахает, чувствуется

**Comment by Tsurupeta** [comment]
Из дискорда я удалил сообщение потому что кто-то сказал, что такие серьёзные вещи туда не нужно постить. А ещё бот сюда его не закинул автоматом, так что да-а-а.

**Comment by dnivji** [comment]
Не нужно ничего нерфать. Против аппрува.

**Comment by Moscowchief** [comment]
Щас бы нуфаги материю настраивали, пусть сначала в роли подмастерья поиграют и у знающих людей поучатся. 
>материя не пишет ничего в радиоканал, если стоит на тайле космоса.
Фиксится сообщением на общую частоту "МАТЕРИЯ ПОКИНУЛА РЕАКТОРНУЮ" при, собственно, покидании материи реакторной

**Comment by Rodial-Admiral** [comment]
> Фиксится сообщением на общую частоту "МАТЕРИЯ ПОКИНУЛА РЕАКТОРНУЮ" при, собственно, покидании материи реакторной

Идея, кстати.
