### ISSUE TITLE
Экзокостюмы кричат о помощи.

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#229]
Побегал я на гигаксе и потестил все что можно.
*Все генераторы не работают.
*Нельзя всунуть в боевой экзоскелет что-то крупнее адвансед кондера и сканнера на этапе постройки.
*Дрели не совсем корректно работают на гридерах стенок.
*Связать шприцемет и слипер у Одиссея.Чтобы в слипер можно было закачивать медицину.
*Можно сделать телепорт для экзосьютов, но он не работает.
*Добавить шаг с вставлением батарейки на этапе строительства как на тг.
Было бы неплохо если бы ещё кто протестировать протекшн бустеры

**Comment by YaridaTheDragon** [comment]
1. Неправильно их юзаешь, лол
2. Более лучшие детали используются в сборке Фазона, не более. Тут он почему то выпилен. Все в норме.
3. Мех не даёт тебе полный доступ. Он и не должен разбирать гирдеры.
4. Глупости.
5. Телепортер же есть и он даже работает.
6. Батарейка по дефолту вставлена в торс меха. :^)

**Comment by Cinericius** [comment]
Почему это не закрыли, лол?
