### ISSUE TITLE
Убрать или же починить крио.

### ISSUE THREAD

**Issue by WhityTaty** [ChaoticOnyx/OnyxBay#23]
Проблема - очень медленно лечит людей, по своей сути бесполезна. 
Но ещё в крайних случаях почему-то ломает давлением людям кости, что она не должна делать.

**Comment by Epicus7** [comment]
Вообще, крио, который с легкостью лечит любые болезни - это немного имба. Не знаю что с ним лучше сделать.

**Comment by LagannPM** [comment]
Не убирайте крио, я туда пихаю людей вместо стазис сумки.И она полезна чтобы лечить органы когда перидаксадона нету. Работает пиздет медленно правда.
В коде смотрел он должен так же лечить берн и брут дамаг не завися от метаболизма.
Но люди жалуются что он не работает

**Comment by Cinericius** [comment]
Возможно, тут та же проблема, что и с баней-убийцей, то есть проблема с теплом и давлением в бееатмосе.

**Comment by Epicus7** [comment]
Можно сделать вот так: #75. Чтобы было понятно, что за баня-убийца.

**Comment by Cinericius** [comment]
Пофикшено давным-давно
