### ISSUE TITLE
Переделать как работает урон на человека при перетаскивании

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#230]
Сделать зависимость от сломанных костей, открытых ран, серьезных ожогов
а не просто от урона
Плюс убрать возможность перетаскивать раненых в ящиках , но сделать исключения для некоторых (например ящик биоорганки)

**Comment by Demisov** [comment]
Не оч как-то

**Comment by Epicus7** [comment]
Куча проблем в одном иссуе, плюс тут требуется более подробная проработка. Т.к. иссуй 2018 года, думаю нет смысла оставлять его открытым.
