### ISSUE TITLE
Гунчат: вечная прокрутка и обрезание текста

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#2303]
Если я не прав и это все в игре исправляется, то объясните как, **НО**

- Текст в гунчате постоянно прокручивается вниз. Если захочешь что-то выделить и скопировать, то придется жопу разорвать, потому что выделение **не останавливает прокрутку**, хотя, очевидно, должно.
- Текст в гунчате, походу, обрезается. Раньше я мог в конце раунда взять и прокрутить чатик до самого начала, если по ходу дела не релогался. Сейчас дай бог 5 минут там остается, хотя я не релогаюсь и не реконекчусь. Какого хрена? А как мне тогда сохранять логи? Собирать их из обрывков что ли?

**Comment by Epicus7** [comment]
> Текст в гунчате постоянно прокручивается вниз. Если захочешь что-то выделить и скопировать, то придется жопу разорвать, потому что выделение не останавливает прокрутку, хотя, очевидно, должно.

Откручиваем чат вверх немного и профит - его перестает скроллить. Старый чат работал также.

> Текст в гунчате, походу, обрезается. Раньше я мог в конце раунда взять и прокрутить чатик до самого начала, если по ходу дела не релогался. Сейчас дай бог 5 минут там остается, хотя я не релогаюсь и не реконекчусь. Какого хрена? А как мне тогда сохранять логи? Собирать их из обрывков что ли?

Это не баг, никто никогда не гарантировал сохранность чата. То что у тебя там чот сохранялось между релогами - счастливое совпадение. Надо улучшение заводить на то, чтобы это улучшить и сохранять логи.

В любом случае лог прерывался релогом, а релоги происходили довольно часто из-за вылетов, например. Так что это все равно было неудобно. Не вижу смысла тут особо заморачиваться ради этого.
