### ISSUE TITLE
Ребаланс аплинка

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#231]
Триторов зачастую идут через пушки, так что вот пара идей как разнообразить их тактики:
*Снизить стоимость аптечки и хирургического набора.Поднять инструменты из набора тиром
*Переделать импланты.Фридом должен стоить 4 телекристалл и быть одноразовым.Увеличить мощность взрыва от взрывного.Вернуть адреналин в ротацию.
*Починить поверсинк и войсченджер.
*Снизить стоимость камера муи.
*Вернуть бомбы в каком-то виде.
*Починить шприцемет и разнообразить выпадаемые токсины из коробки за восемь.Там написано рандом, но по сути выпадает только майндбрейкер.
*Увеличить курс таллеров к каргопоинтам.Объяснять не надо почему.
*Добавить ещё шмоток, если количество людей превышает нное кол-во людей.По типу энерготопора, Синди риг, супперматтер граната, шприцы с суперсилами, двойной есворд, маячок для десанта меха.
*Добавить возможность заказать вирус.
*Добавить возможность проводить по хамелеонодежде айдикартой для быстрой смены облика на соответствующую профессию.
*В тулбокс добавить сварочные очки.
*Понизить в цене модули для Рига.Добавить больше модулей по типу гренейд лаунчера, комплекта визоров, комбат чемикал инжектор.
*Фальшивые сообщения с цк для грандиозного театра (цирка).
*Убрать штраф скорости со скафандра или уменьшить его.

**Comment by Ruforce** [comment]
>*Увеличить курс таллеров к каргопоинтам.Объяснять не надо почему.

эх, сейчас бы не быть посвященным монтетаристом

**Comment by Cinericius** [comment]
Идеи хорошие, правда маячки для мехов жирно, а обмен таллеров на каргопоинты в нынешнем виде вообще не нужен.

**Comment by Demisov** [comment]
Не знаю, если мех будет сравнится с рандомный батарейкой и эквипом, то вполне нормально

**Comment by Cinericius** [comment]
Ребаланс сделали, хотя возможно не совсем такой, как тут.
