### ISSUE TITLE
Отключение гринтекстов в конце раунда

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#2321]
### Улучшение
Это должно хотя бы частично решить проблему с гринтекстодрочерами и перевести список задач антагов именно в разряд рекомендаций для тех, кто не может придумать что-то своё. Но при этом оставить вариативность системы.

### Решение
Сделать возможность убрать через конфиг показывание задач и успешности выполнения  задач антагов в конце раунда
Варианты в конфиге:
Показывается только список антагов и их амбиции (те цели, которые антаг ставит себе сам)
Показывается список антагов, амбиции, цели, но не успешность их выполнения
Показывается и список антагов, и амбиции, и задачи, и степень их выполнения (То что имеем сейчас по факту)

**Comment by Rodial-Admiral** [comment]
Считаю, что это - первый шаг к улучшению нашей слегка удручающей ситуации с антагонистами.
Аппрув.
@dnivji @Moscowchief

**Comment by Wuattt** [comment]
YES-YES-YES-YES-YES-YES

**Comment by Moscowchief** [comment]
Аппрув

**Comment by Epicus7** [comment]
> Показывается список антагов, амбиции, цели, но не успешность их выполнения

Это будет воспринято игроками как очередной баг: "у них ДАЖЕ цели трейторов поломаны!". Особенно если это будет включаться от случая к случаю. Если чот и переделывать с гринтекстом, то нужно действовать более координально и не так топорно.

Придумайте что-то чуть более сложное, чем выпиливание фич, плиз. Особенно когда эти фичи неотъемлимо присутствовали в SS13 с самого её зарождения и никому и в голову прийти не может, что пропавший гринтекст - это не баг, а плод воспаленного воображения местных геймдизов.
