### ISSUE TITLE
Текстурка ран вылезает за спрайт тонкотрапов

### ISSUE THREAD

**Issue by hard-res3t** [ChaoticOnyx/OnyxBay#2327]
### Описание бага
У тонкотрапов вылезает текстурки повреждения за тело. В частности на ногах.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем тонкотрапа
2. Бьем его

### Ожидаемое поведение
Это конечно больше придирка (и так нормально выглядит если не всматриваться), но вправить пару пикселей в тело довольно легко и приятнее будет смотреться.
### Скриншоты
![Снимок экрана (335)](https://user-images.githubusercontent.com/59255670/81487993-27330600-926c-11ea-9c2f-a8d33b8101d9.png)

**Comment by Epicus7** [comment]
Ну тут нужны спрайты текстурок повреждений.
