### ISSUE TITLE
Бумажные самолётики и механики броска.

### ISSUE THREAD

**Issue by Hikky1412** [ChaoticOnyx/OnyxBay#2330]
Добавляем возможность складывать **бумажные самолётики** из волокнистого материала с минеральными добавками. С винрарных вариантов получаем очередной предмет фаллометрии с коллегами на досуге. Степень профита с данной фичи напрямую зависит от выбора реализации механики броска.
Механики броска:
1. Берём предмет в активную руку > выбираем бросок > кликаем на нужный тайл > PROFIT!!!
Комментарий: ужасный вариант, в таком виде смысл фичи теряется.
2. Во время создания самолётика рандомно выбирается его **предел полёта** > самолётик в активной руке > выбираем бросок > кликаем на любой тайл, который будет являться ориентиром направления полёта > (смотрим 2.1; 2.2; 2.3) > PROFIT!!!
Комментарий: **предел полёта** должен быть примерно на уровне 20-30 тайлов. Просчитывается рандомно, очевидно.
2.1 > самолётик летит до своего предела
2.2 > судьба полёта опять просчитывается рандомно
Пример: имеем 10 процентов, что самолётик пролетит не больше 10 тайлов - рандомим от 1 до 10; имеем остальные 90 процентов на вероятность полёта от 11 тайлов до предела – рандомим от 11 до предела.
Комментарий: уже почти win, также можно привинтить к сюрикенам.
2.3 > включается мини-игра по типу: шарик бегает по полоске с красной, жёлтой и зелёными зонами
Пример: красная зона – от предела полёта минусуем рандомное число от 0 до 5; жёлтая зона – к половине предела полёта прибавляем от -5 до 5; зелёная зона – рандом от 1 до 10.
Комментарий: очевидный win.
3. Удаляем иссуй, клипаем всякие ВР дальше.

**Comment by Penguineapig** [comment]
2.3 : можно уже минигольф завезти, лол

**Comment by MrMagick2104** [comment]
>  от предела полёта минусуем рандомное число от 0 до 5; жёлтая зона – к половине предела полёта прибавляем от -5 до 5

Красная зона получается выгоднее. Или имелось ввиду -5?

> минигольф

Фича, которую наш билд заслуживает.

**Comment by Hikky1412** [comment]
> можно уже минигольф завезти

Нужно. Качаем возможности для социалочки.
> Красная зона получается выгоднее. 

Красная зона самая выгодная, но и попасть по ней не должно быть легко. 
> Или имелось ввиду -5?

Мы минусуем у **предела полёта** от 0 до 5, так что по факту, да, имеется ввиду -5.

**Comment by MrMagick2104** [comment]
> Мы минусуем у предела полёта от 0 до 5, так что по факту, да, имеется ввиду -5.

А, ну да. Прибавить минус пять и вычесть пять - одно и то же.

**Comment by Rodial-Admiral** [comment]
А на дизарме они разве не клепаются, или я с блубеем путаю?

**Comment by Hikky1412** [comment]
Путаешь.

**Comment by vsss412** [comment]
Не могли написать нормальных фич? Закрыто, какой нахуй самолетик, блядь.
