### ISSUE TITLE
Удушение слишком долго убивает

### ISSUE THREAD

**Issue by kokokobold** [ChaoticOnyx/OnyxBay#2345]
Я бы сказал, что это скорее баг, нежели улучшение, но кто знает. Если не баг и так задумано™, то поменяйте, пожалуйста.

И я говорю даже не только про удушение с граба, но и удушение из-за виселицы. И там, и там душить приходится минут 7-10 до полной смерти. Разве это нормально? Вот в прошлом буквально раунде я человека душил без преувеличений ДЕСЯТЬ минут. У него не было пульса через какое-то время, конечно, но он всё ещё храпел и дёргался вплоть до последних мгновений. Когда вешаешься, то такая же беда. Висишь себе десять минут, а если твоё тело в петле кто-то найдёт, то без проблем дотащит до медбэя, где тебя откачают. 
Я не спец, но брейндамаг капает уж очень неторопливо: от силы по 0.5 дамага раз в пару секунд. Возможно, проблема связана с тем, что максимально можно получить только 100 оксидамага?

**Comment by TobyThorne** [comment]
Потестировал в лайве, полностью здоровый человек словил полный брейндамаг и успешно умер где-то за три минуты. Уж и не знаю, в какой момент успели это потрогать, но работает.
