### ISSUE TITLE
Ксеностафф

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#235]
Добавить ксеносов робастный метаболизм (не скреллам), помогающий им в их несчастной жизни.Сломаные кости, порванные артерии, и орган дэмэйдж пропадают.Но такой метаболизм сложно поддерживать если ты голодный.И мало быть сытым, надо ещё соблюдать правильную диету и создать условия по типу температуры.
*Различные реагенты оказывают на них различные эффекты.Осторожно, что могут спокойно пить и есть люди, можете отравится.
*Их метаболизм повышается или понижается в связи с температурой тела.
*Ксеносов рождаются без денег и так ходят всю жизнь.Повысит социальному между ксеносами и людьми, так как они выполнят любую работу за копеечку.
*Нутрименты из тела уходят крайне быстро и голодовка  имеет крайне пагубный эффект.

**Comment by Ruforce** [comment]
где код бы взять

**Comment by Demisov** [comment]
Тут больше по цифрам пройтись, и такой механизм уже есть на бее.

**Comment by Demisov** [comment]
Код с разными эффектами на расы точно есть на авроре

**Comment by Fourest** [comment]
У тау это неплохо реализовано
