### ISSUE TITLE
Переставить варианты "Да" и "Нет" во время приглашения в реву

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#2364]
### Улучшение
Есть такая проблема как молчаливые приглашения в реву и порой люди кидают их когда ты пишешь в чатик, а когда ты нажимаешь энтер, то вместо отправки сообщения ты вступаешь в реву. С этим люди сталкиваются довольно часто

### Решение
Сделать дефолтным ответом на конверт "Нет". Это должно быть ну ооочень просто.

### (Опционально) Альтернативы
Возможно как-то переделать механику приглашений? Идея с флешками немного говно, для бэя не подходит. Но у меня нет идей, хотя это ну реально можно как-то нормально реализовать, если у кого есть идея, поделитесь.

### (Опционально) Дополнительная информация
Молчаливые конвертеры сосут хуи

**Comment by PlinHost** [comment]
Альтернатива: выпилить роль рева. Роль нужна только для иконки над персонажем, но иконки ломают иммершен и тоже не нужны. Будет интереснее, если ревам придется обвешиваться опознавательными знаками.

**Comment by TapKo4eB** [comment]
го крафт повязочек из ragов
и чтоб перекрасить их можно было проводами с нужным цветом(лел)

**Comment by Rodial-Admiral** [comment]
Кстати, да.
Ревы не нужны. Хедревы, как катализаторы - да, пожалуйста.

Наличие рольки "рева" объяснимо, возможно, задачами и освобождением от наказания за грифоний. Но надо разъяснить игрокам, что революция против глав - это не гриф.

**Comment by Epicus7** [comment]
Просто напомню: #975

**Comment by TapKo4eB** [comment]
кстати лучше приглашение в чат рефами выкинуть как с конвертом культа а то весь корень всех проблем собсна из-за этого окна

**Comment by Voldirs** [comment]
А лучше реву выпилить, в таком виде, в каком она сейчас, она не нужна потому что этого можно добиться ралиплеем, в ходе раунда. А то мне дебилы, которые молча предлагают бунтовать всё погружение ломают. Мозговыми волными срут, не иначе

**Comment by TobyThorne** [comment]
По-хорошему, вернуть бы на Бегиннерсе конец раунда после победы ревы/выпила нюки/выпила культа. 
А ревам вернуть лолфлеш. Промывание мозгов флешкой выглядит хоть как-то удобоваримо в сравнении с молчаливым высиранием лолконвертов.

**Comment by Moscowchief** [comment]
>А лучше реву выпилить, в таком виде, в каком она сейчас, она не нужна потому что этого можно добиться ралиплеем, в ходе раунда.

This.

**Comment by Rodial-Admiral** [comment]
> This.

This.
