### ISSUE TITLE
Больше механа для капеллана. Бог.

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#2371]
перенести механ с Богом отсюда: https://wiki.taucetistation.org/Chaplain

**Comment by Rodial-Admiral** [comment]
Так предлагается прямой порт?

**Comment by PlinHost** [comment]
Не нужно.

**Comment by kokokobold** [comment]
Уже есть одобренный иссуй на тему механа священнику: #704
И там предложения лучше того, что тут.

**Comment by Primudash** [comment]
Одобрили другое #704

**Comment by Primudash** [comment]
Нет, мы не отпустим идею!!!!!!!!!!!!!!

**Comment by vsss412** [comment]
Нет, мы закрываем идею в пользу дубля. https://github.com/ChaoticOnyx/OnyxBay/issues/704
