### ISSUE TITLE
Сторителлер: базовая механика

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#2391]
Создаем новую **подсистему**, создаем объекты "характер сторителлера", "триггер" и "метрика".

**Условия работы.** Сторителлер должен включаться/отключаться педально для проверки работы метрик (и триггеров?) ингейм, независимо от наличия режима. Ингейм можно включить эксту самому, включить сторителлера и летать педально смотреть как все работает. Включается сторителлер в любой момент раунда, однако для работы стартовых ивентов необходимо включать его до старта.

**Процесс работы.**

1. Сторителлер стартует. На старте раунда создает "характер", пока один единственный. "Характер" создает себе все нужные метрики и триггеры, настраивая их под себя.

**Характер** - хранитель всех настроек сложности игры. Хранит в себе метрики и триггеры, которые может настраивать и пинать. Весь геймдизайн должен быть здесь. Метрики и триггеры - чисто технические вещи, которые настраиваются характером снаружи.

**Метрика** - тип классов, которые собирают информацию о мире и предоставляют информацию для "характера". Метрики должны возвращать информацию в обобщенных типах: шкала от 0 до 100, бул 0 или 1. При создании метрика может требовать какие-то опции от "характера". **Важно:** метрики могут быть довольно тяжелыми в плане производительности, поэтому должны вызываться как можно реже. Наброски вариантов метрик, которые потом нужно будет реализовать на базе этого класса: https://github.com/ChaoticOnyx/OnyxBay/projects/15#card-38327343.

**Триггер** - тип класса, который при вызове каким-то образом влияет на мир. Триггеры имеют постоянные (прописанные в классе определенного тригера) зависимости от метрик. Метрики могут ставить жесткие ограничения на триггер (нельзя выполнить, если метрика "боеспособность станции" ниже 10 из 100), изменять приоритет срабатывания триггера (от 0 до 100), а также использоваться внутри тригера для определения его силы (мощности?). Примеры тригеров: https://github.com/ChaoticOnyx/OnyxBay/projects/15#card-38327131.

2. Также **на старте (до начала раунда)** сторителлер пинает метрики, чтобы они посчитались. Стартовые триггеры в зависимости от метрик считают могут ли они выполниться, а также какой у них приоритет. Сторителлер случайно выбирает какое-то количество триггеров (чем больше приоритет - тем больше вероятность, что триггер сработает) и запускает их. После этого определяется случайное время 5-15 минут, когда сторителлер запустит первую волну.

3. **На старте волны** сторителлер сначала также считает метрики. Потом аналогичным образом выбирает триггеры и спавнит какое-то количество из них со случайными задержками в рамках волны.

4. **В течение волны** сторителлер обновляет метрики и определяет уровень угрозы на станции, пытаясь определить спад и окончание волны (спад уровня угрозы до какого-то уровня относительно максимального за время волны). После окончания дает случайный перерыв, откладывая запуск следующей волны на случайное время (5-10 минут).

------

**В рамках этого иссуя необходима реализация только базовой механики.** Все "случайные" места могут быть проставлены произвольно, триггеры, характеры и метрики не нужны - нужен лишь каркас, на базе которого можно будет создавать эти триггеры, характеры и метрики. Кроме каркаса нужно также реализовать этапы работы сторителлера: старт раунда, волна, конец раунда.

**Comment by PlinHost** [comment]
Рандом ивенты должны прилетать когда угодно, а не волнами. Учитывая, что рандом ивенты будут спавниться сторителлером, система сторителлера основанная на волнах не подходит.

>В зависимости от метрик, характер может решить, что пора заканчивать смену и перестать спавнить волны, вместо этого начиная форсить голосования, шаттлы и сообщения о конце смены.

Это какое-то некрасивое поведение, игроки могут сами начать голосование на рестарт или вызвать шаттл. Разве что если голосования на рестарт запрещены, можно дать характерам возможность их разрешать.

**Comment by Epicus7** [comment]
> Рандом ивенты должны прилетать когда угодно, а не волнами. Учитывая, что рандом ивенты будут спавниться сторителлером, система сторителлера основанная на волнах не подходит.

> Потом аналогичным образом выбирает триггеры и спавнит какое-то количество из них со случайными задержками в рамках волны.

Волнами лишь расчитываются метрики и тригеры. А рандом ивенты спавнятся со случайными задержками, т.е, рандомно, а не волнами.

**Comment by Epicus7** [comment]
> Это какое-то некрасивое поведение, игроки могут сами начать голосование на рестарт или вызвать шаттл. Разве что если голосования на рестарт запрещены, можно дать характерам возможность их разрешать.

Это лишь механика "окончательно этапа" сторителлера, которой характер может не пользоваться. Сама механика нужна, мне кажется, как минимум для того, чтобы проверить на игроках как такие вещи им зайдут - если им не понравится, мы отключим все финальные действия (если вообще добавим их в характер).
