### ISSUE TITLE
Апнуть емп

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#241]
Киборгам и ригам поехать на емп, а именно на эффект разрядки батареи.Киборг со стандартной батарейкой может спокойно ещё сопротивляться после двух емп гранат и падает в энерготопорасберегающий режим только после третьей.Риг в свою очередь, за вспышку не теряет и десяти процентов энергии

**Comment by LagannPM** [comment]
у борга не стоит проверка на силу емп

**Comment by Cinericius** [comment]
Надо бы вкрутить проверочку, да

**Comment by HalilDaBlack** [comment]
Синты и должны помирать от ЭМИ, это расSSово верное механорешение не допускает вторых дион.

**Comment by bob467** [comment]
Разве они не должны станить синта?
И есть спасение это ЭМИ?
