### ISSUE TITLE
Добавить варнингам подтверждение

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#2416]
Сейчас варнинги просто появляются и не мешают зайти за капитана. Нужно чтобы они требовали подтверждения **("Ок, понял!"/"Я передумал")** и только после этого давали зайти в игру.

**Comment by PlinHost** [comment]
Щас бы #1247 закрыть без реализации ключевого пункта...

**Comment by Epicus7** [comment]
Там ни слова про подтверждение

**Comment by Shirlineyn** [comment]
Подтверждения игрока или подтверждения педали?

**Comment by Epicus7** [comment]
Игрока, конечно. Обновил описание чтобы однозначно было
