### ISSUE TITLE
Квалити оф Спейс лайф.

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#242]
*Разнерфать починку скафандра прямо на себе.
*Спиздить у Авроры герметичный пузырь:у каждого космонавтика есть в своем наборе одноразовый пузырь, который его спасет в тяжёлые времена разгермы.Их ещё можно таскать и с их помощью осуществлять перевозки по космосу.

**Comment by Ruforce** [comment]
ну второе что-то нет

**Comment by Penguineapig** [comment]
Стазис бег что ли?
