### ISSUE TITLE
Нерф плазменных резаков

### ISSUE THREAD

**Issue by AmiClerick** [ChaoticOnyx/OnyxBay#2431]
Понимая всю боль наших юных шахтёров, которые погибают от жестокой местной фауны, наши ученики-контрибуторы улучшили резак, но что мы получили?
Мы имеем инструмент, который **лучше любого оружия** в билде, способный сносить головы первым выстрелом(да, голова это тоже конечность), действующий на расстоянии и имеющий самозарядку. Гении-абузеры берут РИГ раундстартом и идут показывать, как же они хороши в этой игре. 

Реквестирую пересмотр этого улучшения.

**Comment by AmiClerick** [comment]
Некоторые в обсуждениях добавляли варианты нерфа:

1)Убрать резак из РИГа.
2)Убрать шанс отрезания конечностей/добавить проверку в зависимости на расстояние(зачем отрезание конечностей, если он предназначен для войны с симпл мобами)
3)Добавить особый вид зарядки для этого резака, выпилив ему самозарядку.

Дополню это сообщение, если что-то ещё вспомню.

**Comment by MrMagick2104** [comment]
> 1)Убрать резак из РИГа.

Обязательно нужно сделать, ибо плазменные резаки в РИГах - некошерно.
> Убрать шанс отрезания конечностей/добавить проверку в зависимости на расстояние(зачем отрезание конечностей, если он предназначен для войны с симпл мобами)

Потому что так в оригинале было. По-хорошему, дать бы ещё любым предметам с флагом THICK_MATERIAL защиту от отрезания: шляпам, шлемам, вёдрам на голове.
Кроме того, предложение Наноанона звучит тоже неплохо:
просто надо, чтобы работал на кусках плазмы и только на них, имел два режима - для добычи, который обычный и расходует мало заряда, но и урона мало, и боевой - который уебет и фауну астероида, и человеку пизды даст, если стрелять не на большое расстояние, но расходует по цельному куску плазмы за раз
При условии номера три. Для зарядки используются чистые бруски плазмы.
Оригинальный иссуй Добряка несёт в себе непрактичные нёрфы, которые убивают суть шахтёрского инструмента как инструмента, так и как оружия.

**Comment by Rodial-Admiral** [comment]
Хотел завести иссуй, но тут уже имеется. 

Предлагаю следующий проект улучшения:

1) Отпиливание конечностей оставить только для давлений меньше 5 кПа. 

2) Ввести зависимость урона от расстояния с полной деградацией через экран. Т.е. поинтбланком оставить полный урон, но с увеличением расстояния - снижать на определенный процент. Предлагаю 10-15% на тайл, в этих границах.

3) Снизить скорость самозарядки в два-три раза, оставив текущую емкость.

**Comment by Rodial-Admiral** [comment]
@dnivji @Moscowchief

**Comment by MrMagick2104** [comment]
> Снизить скорость самозарядки в два-три раза, оставив текущую емкость.

Зарядка плазмой и работа при 0 заряде исключительно как шахтёрским инструментом звучит лучше, по-моему.
> Т.е. поинтбланком оставить полный урон, но с увеличением расстояния - снижать на определенный процент. Предлагаю 10-15% на тайл, в этих границах.

Только если в условиях атмосферы. В вакууме же заряд не теряет своей энергии, сколь далеко он бы не пролетел. А в атмосфере уже предложено спилить отрубание.
Ну и 30 бёрна - не так уж и много, до 25 можно снизить всё равно. У плазменного резака больно делает отрубание конечностей с шансом в 33%.

**Comment by Doster-d** [comment]
В работе.

**Comment by Doster-d** [comment]
> 2. Ввести зависимость урона от расстояния с полной деградацией через экран.
Как только beam выходит за экран отправителя, то его урон будет равен нулю, вместе с возможности отрубанием конечностей, верно?

**Comment by MrMagick2104** [comment]
> Как только beam выходит за экран отправителя, то его урон будет равен нулю, вместе с возможности отрубанием конечностей, верно?

У луча уже киллкаунт = 5, он не может покинуть пределы экрана отправителя, т.к. исчезает.
Наверное, да?

**Comment by Doster-d** [comment]
Сообщаю статус разработки:
Готово:
1. РИГ модуль - плазменный резак, не существует.
2. Теперь конечности будут отрываться только если давление меньше 5
3. Теперь невозможно снять голову с плеч, если на ней надет шлем с флагом THICKMATERIAL
4. Добавил перезарядку через твердый форон, убрал зарядку через зарядное устройство.
В процессе:
Смена режима без возможности отрыва конечности для копания ресурсов, без ограничения по имеющимися заряду, только при заряде равным нулю.

**Comment by Animesku** [comment]
А может не надо жесткую границу в 5 делать? Уменьшать шанс и более плавно можно.

**Comment by Doster-d** [comment]
Ваше предложение?

**Comment by Voldirs** [comment]
Не отрезать сквозь thickmaterial вообще все конечности, сильно уменьшать шанс отрезания конечности с расстоянием, дефолтный шанс поставить в 20%. Я бы как-то так сделал.

**Comment by Doster-d** [comment]
> Не отрезать сквозь thickmaterial вообще все конечности, сильно уменьшать шанс отрезания конечности с расстоянием, дефолтный шанс поставить в 20%. Я бы как-то так сделал.

У одежды есть еще флаг ITEM_FLAG_STOPPRESSUREDAMAGE, что я считаю более логичным для остальных частей, чем ITEM_FLAG_THICKMATERIAL

**Comment by Doster-d** [comment]
> А может не надо жесткую границу в 5 делать? Уменьшать шанс и более плавно можно.

Принял, сделал это число более случайным
