### ISSUE TITLE
Ребаланс цен абилок генокрада

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#2440]
Ну как-то смешно, когда снижают раундстартовые ДНК, а в иссуе по этой теме ОП пишет:

> Возможно, дополнительный ребаланс цен после реализации проекта, но на это наверное отдельный иссуй заведем ближе к делу.

(источник: #1063 )

Чего сделано не было, лололололололол генокрад сосать
Ну, очевидно это вопрос для геймдизайнеров, коим я не являюсь и уж тем более по теме космостанции я им не являюсь, но хотелось поднять этот вопрос и чтобы его могли обсуждать здесь. Что в день реализации обновления все галдели, мол, генокрад это теперь трейтор с армблейдом вместо есворда, что до сих пор это недовольство просматривается, равно как и увеличенная доля раундов с генокрадами, в которых генокрады проигрывают довольно рано.

**Comment by MrMagick2104** [comment]
Гениальная  ситуация.

**Comment by Epicus7** [comment]
@TapKo4eB, а плашку генокрада?
