### ISSUE TITLE
Гунчат не грузится

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#2441]
![image](https://user-images.githubusercontent.com/48406301/82554819-4cc6e600-9b6f-11ea-86f7-cb83a51d9859.png)
прошло минут уже пять...

да хрен там минут пять - весь раунд
при том ни релог, ни кнопка фикс чат не помогают

**Comment by Animesku** [comment]
а через час примерно становится вот так
![image](https://user-images.githubusercontent.com/48406301/82643766-ccf55600-9c18-11ea-97e1-698e91465885.png)

**Comment by Epicus7** [comment]
Держу пари это связанно с тем, что у всех игроков гунчат оч медленно загружается. Анимеску прост не повезло.

Надо разбираться в целом, почему гунчат так медленно грузится.

**Comment by ucnaHez** [comment]
О у меня бывает. Правда теперь уже первое сообщение вылядит как пустота, потому что кто-то отключил отображение чего бы то ни было, кроме сообщения "иф чат нот лоадинг ор скрин из блек вейт", но все остальное один в один. Второе сообщение (где чат есть, но странный) фиксится последней стадией кнопки фиксчат. Иногда.

**Comment by igorsaux** [comment]
Неактуально #5486
