### ISSUE TITLE
Кастомные описания и названия предметов в лоадауте

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#2445]
Добавить возможность в лоадауте поменять название и описание предмета на кастомное.

Сделать фичу доступной только патронам начиная с какого-то ранга.

**Comment by koronoshka** [comment]
"Медаль за ЕРП"
(награда нанотрайзен) - 8 очков

**Comment by kreeperHLC** [comment]
> Добавить возможность в лоадауте поменять название и описание предмета на кастомное.
> 
> Сделать фичу доступной только патронам начиная с какого-то ранга.

По сути реализация кастомок, но в другом виде. Отказано.
