### ISSUE TITLE
Вкрутить атмос Зуллаеля или его функциональный аналог

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#246]
Ньюфаги не знают, олдфаги не помнят, а между тем это было волшебно. Не то что это костыльное нерфоклоунское говно с бесконечными станами, которое бееговноеды называют гордым словом "Атмос".

**Comment by Cinericius** [comment]
Краткая суть для тех, кто не играл на Ферне и других билдах с этим поистине восхитительным атмосом:
1) Воздух в разгерму, даже небольшую, утекает быстро, нет, действительно БЫСТРО.
2) Вместе с воздухом в разгерму примерно с той же скоростью утекают космонавты, а так же мебель, ящики и вообще все, что не привинчено к полу. То, что привинчено, утекает чуть-чуть медленнее.
3) Если космонавтик в процессе утекания в разгерму (или противостояния ей с помощью магбутсов) сталкивается с шкафчиком, ящиком или иным тяжеловесным предметом, он очень быстро превращается в фарш четвертой категории (тот самый, который рубится с костями, одеждой, личными вещами, частями интерьера и кусками мебели).
4) Идет ученый по РнД, видит - токсины горят. Открыл аирлок и ГРОБ ГРОБ КИШКИ ГОВНО РАСПИДОРАСИЛО ДАВЛЕНИЕ ХУЙ В ОДНУ СТОРОНУ ЧЕРЕП В ДРУГУЮ ПОТОЛОК ГОРИТ ПИДОР.

**Comment by SilenceInsider** [comment]
Ты че дебил)
А то что беевское говно вместо атмоса почти не занимает ресурсов в сравнении с старым убожеством которое сервер убивало на несколько минут это ничего?
Буквально всё говно которое ты расписал никуда не пропало из кода атмоса но имеет значения которые не позволяют прозойти тому что ты хочешь. . .
