### ISSUE TITLE
Нерф фауны

### ISSUE THREAD

**Issue by Shleld** [ChaoticOnyx/OnyxBay#247]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
В том, что фауна слишком имбовая и жрет очень много ресурсов машинки

**Опишите ваше решение проблемы**
Снизить количество фауны на астероиде и понерфить ее

**Опишите альтернативы, о которых вы думали**
Не вижу альтернатив. Это попросту проще и быстрее

**Дополнительная информация**
Игроки за шахтеров и ксенобиологов очень страдают. Голиафы которые мгновенно станят тебя своими тентаклями и базилиски кнокающие тебя с одного удара это слишком жирно. Плюс их просто дохренища и они жрут огромное количество ресурсов

**Comment by Cinericius** [comment]
Количество и процентовку фауны уже уменьшили, теперь ее в целом меньше и более слабых мобов относительно больше.

Насчет нерфа надо подумать.

**Comment by PlinHost** [comment]
> Количество и процентовку фауны уже уменьшили

Если ты про то, что меня просил, то не уменьшили пока 😉.

**Comment by Cinericius** [comment]
Ощим василиск нихуя не понерфился несмотря на то, что температурный эффект от его плевка поменялся в два раза. Вестимо, придется его редачить более плотно, чем и займусь сегодня. Скорее всего он вообще перестанет морозить и будет делать какую-нибудь другую гадость.
Еще сделаю сегодня спрайт грязекраба поконтрастнее, а то я чот перестарался с маскировочными пятнами и в итоге он стал квазиневидимым.
Ну и еще, если совсем попрет, попробую сделать щупальцам голиафа проверку на турфы под голиафом и жертвой, чтобы он не мог действовать через плитку, а то это какой-то рофел. Да и небольшую задержку перед станом надо вернуть, да.

**Comment by Cinericius** [comment]
Сделал все заявленное и даже чуть больше. Иссуй закрываю и жду принятия ПРа.
