### ISSUE TITLE
Garrran о шахтерских вендоматах и ригах.

### ISSUE THREAD

**Issue by PrimeTed** [ChaoticOnyx/OnyxBay#249]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Шахтеры запросили какие-нибудь лоу-тир модификации для ригов в шахтерский вендомат.

**Опишите ваше решение проблемы**
Добавление лоу-тир модификаций для ригов в вендоматы.

**Опишите альтернативы, о которых вы думали**
А их нет. Мое предложение единственное и довольно-таки просто реализуемое.

**Дополнительная информация**
Вписываем пару строчек в вендомат...
Ловим профиты.

**Comment by Cinericius** [comment]
Походу не перенес.
Короче я тогда просто модулей всяких напихаю.
