### ISSUE TITLE
27.05.2020 порт 2507 ака лавфул сдох

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#2499]
### Описание
сабж, логи оч интересные

### Характеристики
 - 30074e4009b45f67546fc410dbaabaaf7b427ea5 - release/lawful - 2020-05-23
 - b7m-alpt

**Comment by Epicus7** [comment]
Логи где, зачем снижать приоритет, если у тебя сервер может умереть в любую секунду опять

**Comment by O0oMaximo0O** [comment]
Я же правильно понимаю, что это древнее-древнее... явно неактуально и это можно закрыть?

**Comment by DarkHunter7756** [comment]
Год прошел. Лавфула больше нет. Карта другая. Логи не завезли и вроде ничего не крашилось, чтобы об этом багрепорте вспоминали. Вероятно устарело

**Comment by O0oMaximo0O** [comment]
Рискну.
