### ISSUE TITLE
Протолат и консоль РнД.

### ISSUE THREAD

**Issue by ZeR3Y** [ChaoticOnyx/OnyxBay#250]
Приветствую, в раунде за инженера решили соорудить личный протолат, для того что-бы не бегать в РнД и выпрашивать всякое "добро", но столкнулись с одной проблемой.
При сборке консоли РнД и так-же самого протолата (и его подключения к ней), меню консоли застывает и сама консоль перестаёт работать, единственное что помогает в данной ситуации - открутить её с помощью отвёртки и обратно прикрутить, тем самым сбросив все настройки и само меню протолата.
 
С этим багом я столкнулся очень просто.
1. Собрать консоль РнД.
2. Собрать протолат.
3. Подключить протолат к РнД.
4. Нажать на кнопочку "Protolahte construction menu" и понять что что-то здесь не так.
===========================================================

В том же раунде (bWt-bDu6), просили помощи у педалей, с места не сдвинулись. Подключали и отдельно провода и переставляли протолат с места где он был.

**Comment by Ruforce** [comment]
проблема в говнокоде бэя и в том что для конкретной работы нужен сиркуитинпринтер

**Comment by Vmihey** [comment]
**Описание бага**
(E) (C) (M) contents = /list (14)
1: [0x203338d] - the circuit board (protolathe) (/obj/item/weapon/circuitboard/protolathe)
2: [0x20333e9] - the matter bin (/obj/item/weapon/stock_parts/matter_bin)
3: [0x20333e7] - the matter bin (/obj/item/weapon/stock_parts/matter_bin)
4: [0x203340f] - the micro-manipulator (/obj/item/weapon/stock_parts/manipulator)
5: [0x203340e] - the micro-manipulator (/obj/item/weapon/stock_parts/manipulator)
6: [0x2033753] - the beaker (/obj/item/weapon/reagent_containers/glass/beaker)
7: [0x201436c] - the beaker (/obj/item/weapon/reagent_containers/glass/beaker)
8: [0x2016839] - the beaker (/obj/item/weapon/reagent_containers/glass/beaker)
9: [0x2016855] - the beaker (/obj/item/weapon/reagent_containers/glass/beaker)
10: [0x203374a] - the super matter bin (/obj/item/weapon/stock_parts/matter_bin/super)
11: [0x203355c] - the super matter bin (/obj/item/weapon/stock_parts/matter_bin/super)
12: [0x20336b5] - the pico-manipulator (/obj/item/weapon/stock_parts/manipulator/pico)
13: [0x203361c] - the pico-manipulator (/obj/item/weapon/stock_parts/manipulator/pico)
14: [0x20168b0] - the circuit board (protolathe) (/obj/item/weapon/circuitboard/protolathe)

Примечание: из-за этого протолат не работает

**Comment by O0oMaximo0O** [comment]
Протестировано на локалке, баг не обнаружен, собрал протолат и РнД-консоль в Engineering Workshop на Исходе, подключил, всё работает
