### ISSUE TITLE
Рантайм в chisel

### ISSUE THREAD

**Issue by PlinHost** [ChaoticOnyx/OnyxBay#2502]
https://github.com/ChaoticOnyx/OnyxBay/blob/37d4a7a0b30411ce6edcacd1209d31ebbb4d92c9/code/modules/mining/mine_items.dm#L651-L655
`playsound` не принимает строку с именем файла, там должен быть файл либо имя пресет звука, автор мудак.

**Comment by Pos13** [comment]
А в билде нет звуков 'chisel1.ogg' и 'chisel2.ogg'. И в истории коммитов его нет. И у бейцев нет. И у тг. И вообще нигде. Это какая-то хуйня из-под коня.

**Comment by PlinHost** [comment]
Ну тогда снести ветку ифа и все дела.

**Comment by Pos13** [comment]
Я уже нашёл подходящие бесплатные звуки в интернете.
