### ISSUE TITLE
У магуси поломались заклинания

### ISSUE THREAD

**Issue by xmaebx** [ChaoticOnyx/OnyxBay#2505]
### Описание бага
Магуся вместо заклинаний рассказывает нам циферки и символы.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем сервер
2. Открываем сервер, становимся магусей
3. Нажимаем на заклинание
4. Видим ошибку: Месиво из циферок и символов

### Ожидаемое поведение
Не должно было быть символов и циферок, очевидно же.

### Скриншоты
Если проблема может быть показана на скриншотах - прикрепите их.
![image](https://user-images.githubusercontent.com/58894285/83029776-bb0e1b80-a03b-11ea-9203-4f053488c4e9.png)

**Comment by TobyThorne** [comment]
Нынче такого не видно. Видимо, в какой-то момент пофиксилось.
