### ISSUE TITLE
Карма

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#2511]
Добавить возможность игрокам лайкать друг друга.

1. Лайкать других игроков могут только **Признанные 2D Космонавтики**. Каждый **Признанный 2D Космонавтик** может лайкнуть/дизлайкнуть другого игрока только один раз, но всегда может поменять свой выбор. Лайкать/дизлайкать игрока можно только в конкретном игровом раунде, через его персонажа, указав причину лайка/дизлайка.
2. **Признанные 2D Космонавтики** могут делать **Признанными 2D Космонавтиков** других игроков.
3. **Признанный 2D Космонавтик** может перестать быть таковым по решению сената.

Требуется:

1. В БД добавить информацию о том, какие игроки являются **Признанными 2D Космонавтиками** и кто их сделал таковыми (если такой игрок есть). Добавить таблицу с лайками/дизлайками.
2. В игре добавить Ghost-у возможность лайкать/дизлайкать игроков персонажей **Признанным 2D Космонавтикам**. При лайке/дизлайке **Признанный 2D Космонавтик** обязательно должен указать причину. Новый голос затирает старый.
3. В дискорде добавить боту возможность вывести топ игроков по их карме.

В дальнейшем на карму, вероятно, будем привязывать какие-то функции (например, приоритет выдачи профессий/ролей) + добавим больше мест, где можно карму посмотреть.

**Comment by Epicus7** [comment]
Чтобы выделять игроков, которые интересно отыгрывают свои роли в отдельных историях ролевой игры, очевидно.

**Comment by Animesku** [comment]
А че их в цифрах-то вдруг понадобилось выделать? За интересную игру и так скажут спасибо.

**Comment by Epicus7** [comment]
Чтобы использовать эту информацию, например для того, чтобы выдавать социальные роли, типо капитана, игрокам которые играют на них интереснее.

Еще чтобы поощрять таких игроков, например, опиксами. Ну и кучу других причин можно придумать в численной оценке интереса игры одних игроков по оценке других.

**Comment by PlinHost** [comment]
> Чтобы использовать эту информацию, например для того, чтобы выдавать социальные роли, типо капитана, игрокам которые играют на них интереснее.
> 
> Еще чтобы поощрять таких игроков, например, опиксами. Ну и кучу других причин можно придумать для численной оценке интереса игры одних игроков по оценке других.

Блин, опять ты за свое. Остановись и не порти идею.

**Comment by Animesku** [comment]
Ну так если игрок хорошо сыграл например за СБ, то это еще не значит, что он захочет вообще, или будет хорошо играть капитаном, или антагонистом. 
Да и на группу лайкающих/дизлайкающих людей бремя возлагается, ведь на каждую отметку придется хоть немного, но в ситуации разбираться. А то ставишь дизлайк человеку за хреновую игру - допустим он постоянно срал эмоутами на пол - а потом выясняется, что ой, а он там например под действием импланта подчинения был. Дизлайк убираешь и идешь искать того, кто этот имплант вколол. Через n дней находишь, дизлайкаешь, а он вдруг говорит, что это его попросил вколоть имплант тот человек, который срал на пол. Снова ставишь дизлайк срущему, а он оправдывается, что просил совсем не те "законы" в импланте. А второй ответит, что первый под "не те" имел ввиду выпил станции, поэтому решил пошутить и отправил срать на пол. И тут уже хрен пойми кому дизлайк ставить, а кому лайк. А если бросить и не ставить никому, то ты зря просрал кучу времени на выяснения. В общем в сс13 даже такая ситуация может оказаться довольно глубокой, что ее без разговоров в ООС/дискорде или без логов не разберешь так просто. Да и вообще это скорее педалей работа банить или просто писать ПМки тем, кто плохо играет, а тех, кто хорошо, игроки сами похвалят.

**Comment by PlinHost** [comment]
> Признанный 2D Космонавтик может перестать быть таковым по решению сената. В таком случае Признанным 2D Космонавтиком также перестает быть тот, кто сделал Признанным 2D Космонавтиком первого игрока.

Сенат может сам решить, снимать ли выдавшего. Лишний пункт.

> В дальнейшем на карму будем привязывать какие-то функции (например, приоритет выдачи профессий/ролей)

Не нужно.

> При лайке/дизлайке Признанный 2D Космонавтик обязательно должен указать причину.

Зачем это нужно, кто это будет читать?

Лучше сделать возможность давать только кармомет без инвайтилки.

**Comment by Epicus7** [comment]
>> Признанный 2D Космонавтик может перестать быть таковым по решению сената. В таком случае Признанным 2D Космонавтиком также перестает быть тот, кто сделал Признанным 2D Космонавтиком первого игрока.
>Сенат может сам решить, снимать ли выдавшего. Лишний пункт.

Убрал

>> В дальнейшем на карму будем привязывать какие-то функции (например, приоритет выдачи профессий/ролей)
>Не нужно.

Карма появляется у игрока при интересном отыгрыше ролей. Поощрять игроков за это, имхо, хорошая идея. Энивей, к иссую напрямую это не относится и написано просто для понимания будущих возможностей, которые открываются после запила этого иссуя.

>> При лайке/дизлайке Признанный 2D Космонавтик обязательно должен указать причину.
> Зачем это нужно, кто это будет читать?

Читать это будут любые другие игроки, которым интересно за что игрока залайкали. Сделаем возможность прочитать это в дискорде, мб в игре тоже. Хз

> Лучше сделать возможность давать только кармомет без инвайтилки.
Если я правильно понял, то это дополнительное усложнение, которое можно будет сделать потом, если оно реально нужно.

**Comment by kokokobold** [comment]
Название не нравится совершенно. «Признанный 2D космонавтик» не отражает сути, а также не отскакивает от языка. 
Ничего в голову не лезет, правда.

И можно не только гостам дать возможность лайкать или дизлайкать? А так, алгоритм выглядит нормально.

**Comment by Epicus7** [comment]
> И можно не только гостам дать возможность лайкать или дизлайкать? А так, алгоритм выглядит нормально.

Ну госту через ПКМ можно сделать, а живым игрокам это будет захламлять ПКМ-менюшку. Не знаю как сделать так, чтобы живым было удобно этим пользоваться.

**Comment by kokokobold** [comment]
Через вкладку ООС, например? OOC→Karma→Choose a player, ну а дальше уже ставишь лайк или дизлайк. Лучше уж так, чем через ПКМ ловить мобов.

**Comment by Epicus7** [comment]
> Через вкладку ООС, например? OOC→Karma→Choose a player, ну а дальше уже ставишь лайк или дизлайк. Лучше уж так, чем через ПКМ ловить мобов.

Ну в иссуе написано про лайки через персонажей. Мы будем в этой Choose a player палить всех персонажей на станции? Синдикатовцев там? Или как?

**Comment by kokokobold** [comment]
Я думал над сикеями. Вот что делать, если в раунде А ты поставишь дизлайк космонавту, который играет на одном персонаже, а в раунде Б поставишь лайк этому же космонавту, который играет уже на другом персонаже?

**Comment by Doster-d** [comment]
> Я думал над сикеями. Вот что делать, если в раунде А ты поставишь дизлайк космонавту, который играет на одном персонаже, а в раунде Б поставишь лайк этому же космонавту, который играет уже на другом персонаже?

Голос затирается, сказано же...

**Comment by MrMagick2104** [comment]
Имхо, лайки и дизлайки - нормальная фича, просто чтобы у игроков была карма, но без вот этого "признанности" (хотя можно давать какие-то бонусы за лайки), т.е. лайкать могут все и вся, кроме аккаунтов младше n дней, наверное?
> указав причину лайка/дизлайка.

А вот это вообще прикол. Кому это нужно? Можно ли будет обжаловать дизлайк потом в суде? И так далее.

**Comment by PlinHost** [comment]
Хороший ответ, я джва месяца ждал.

> Карма появляется у игрока при интересном отыгрыше ролей. Поощрять игроков за это, имхо, хорошая идея. 

Карма появляется при нажатии кнопочки, а не при интересном отыгрыше. Заставить людей тыкать кнопочку только объективно интересно отыгрывающим ты не сможешь.

<br>

> Энивей, к иссую напрямую это не относится и написано просто для понимания будущих возможностей, которые открываются после запила этого иссуя.

Смотрим иссуй: 

>В дальнейшем на карму будем привязывать какие-то функции

Тут четко написано "будем", а не "возможно если геймдизайнеры решат".

**Comment by Epicus7** [comment]
> Тут четко написано "будем", а не "возможно если геймдизайнеры решат".

Пофиксил

**Comment by vsss412** [comment]
Данная фича получила реализацию на форуме. Пользуемся только там.
