### ISSUE TITLE
Сторителлер: выдача ролей через предметы

### ISSUE THREAD

**Issue by koronoshka** [ChaoticOnyx/OnyxBay#2526]
Основываясь на иссуях #976 #1866 #2515 #2512 предлагаю более сложную систему выдачи ролей для отдельной личности сторителлера. На станции за одну секунду несколько спокойных и уравновешенных человек могут неожиданно стать инопланетными машинами для убийств/наемниками-профессионалами/культистами с промытыми мозгами. Это не очень логично, дак еще и нет пояснения как это отыгрывать, кроме как "представь что ты им был всегда." Пусть заместо неожиданной выдачи случайной станционной роли, эта личность сторителлера будет спаунить в различных местах предметы, выдающие эти роли. У них должны быть различные места появления, или даже различные способы их получения. Если прорабатывать последнее, то нужно продумать способы получения роли на каждый отдел, или даже на каждую профессию. Артефакты, дающие роль, можно так же оставлять на месте смерти внестанционного антагониста, некоторым дать волю создавать самому за определенную плату. Изредка, оставлять после некоторых ивентов на станции.

**Comment by MrMagick2104** [comment]
> эта личность сторителлера будет спаунить в различных местах предметы, выдающие эти роли. 

Например? Кроме ксеноархеологии.
Кокон чужого с хэдкрабом генокрада в техах?
Валяющиеся контракты Синдиката в гетто?
Просто возникает вопрос. Что они там, блин, забыли?
Некоторые роли сложновато оправдать.
Если, допустим, кокон хэдкраба генкорада ещё понять можно, как и, допустим, агитплакаты революционные (пропаганда аки та способность из Компани оф Хироз 2, с сбрасыванием на врага бомб с листовками) и кольцо всевластия для становления магом.
Но с предателем что?
Может быть, уведомление на КПК: "Привет, пишет Синдикат, хочешь стать трейтором?!?!?!?!?"
Такое себе, по-моему.

**Comment by koronoshka** [comment]
Придумать можно много чего. Случайные контракты можно впихнуть торговцам, можно впихнуть как случайно полученное сообщение во время отключение связи, но это если быть изобретательным. Можно ставить тайные жучки синдиката настроенные на определенную волну, и естественно, они не будут просто так валятся на полу в гетто. Как пример, человек находит такой жучок, достает его, разбирает и находит ключи шифрования синдиката. Когда он их вставляет в наушник, ему нарратируется что-то про секретную волну передачи синдиката и всплывает приглашение. Если человек откажется, он может сдать такую бесполезную побрякушку СБ как ответственный гражданин и его похлопают по плечу.

**Comment by Epicus7** [comment]
Сторителлеру нужны механизмы быстрой выдачи ролей ради баланса. Если тупо предмет где-то класть - его никто не возьмет и баланс выравнять не получится.

**Comment by koronoshka** [comment]
Поэтому я предлагаю это как отдельный модуль ИИ сторителлера, если люди захотят больше ролевой составляющей в раунде и готовы пожертвовать балансом. Не уверен правда как они по итогу выбираются, ротацией или голосованием в конце раунда.

**Comment by MrMagick2104** [comment]
> Сторителлеру нужны механизмы быстрой выдачи ролей ради баланса. Если тупо предмет где-то класть - его никто не возьмет и баланс выравнять не получится.

Так это ЛИЧНОСТЬ сторителлера. Не все же будут так работать, для разнообразия геймплея, я думаю.
> Если человек откажется, он может сдать такую бесполезную побрякушку СБ как ответственный гражданин и его похлопают по плечу.

Может, лучше радио сделать? Заодно и аплинк там же.
Оно должно быть одноразовым?

**Comment by koronoshka** [comment]
Наверно можно и радио, но это даст еще больше проблем с балансом. Я не хочу пока это разбирать.

**Comment by PlinHost** [comment]
Редкие предметы, дающие роль, должны быть редкими, а не спавниться на дрожжах, когда сторителлеру мало ролей.

**Comment by koronoshka** [comment]
Ноу щит плин. Еще редкие предметы, дающие роль должны выдавать роль. Еще они должны быть предметами.

**Comment by Epicus7** [comment]
Я думаю начать стоит с иссуев, описанных ОПе. Сделать их просто опциональными, рандомноспавнящимися где бы то ни было.

Заменять вообще все механизмы выдачи ролей на такие предметы сейчас как минимум рано. Я сильно сомневаюсь что это вообще нужно, но сейчас это точно не нужно.

Предлагаю отклонить.
