### ISSUE TITLE
Ченжлинги сломались

### ISSUE THREAD

**Issue by kokokobold** [ChaoticOnyx/OnyxBay#2537]
Режим: ченжлинги, у всех них сразу же была ситуация, как на скриншоте. Нет заданий, нет способностей, но могут слышать друг друга.
![](https://i.imgur.com/0uvaGGC.png)

**Comment by Epicus7** [comment]
Посмотрел по горячим следам - хрен его знает, что это было. Генокрад был заспавнен режимом Changeling, а не ивентами или сторителлером. Рантаймов, которые точно относились бы к этому, тоже не нашел. Локально воспроизвести не получилось.

Пусть висит, пока больше инфы не получим, что поделать.

**Comment by MellonDeLuna** [comment]
Слышать могли друг друга, кстати. И была менюшка эволюции.

**Comment by NefrNerf** [comment]
Уже больше года висит, наверное можно закрыть по причине множества обновлений и переработок.
