### ISSUE TITLE
У холодного пива нет спрайта (невидимое)

### ISSUE THREAD

**Issue by Wuattt** [ChaoticOnyx/OnyxBay#2543]
### Описание бага
Делаешь пинту холодного пива - а оно оказывается невидимым. То есть, можно только по alt или пкм найти

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем .. пиво и лёд
2. смешиваем
3. видим, что пиво стало невидимым

### Ожидаемое поведение
Чтобы спрайт холодного пива был

### Скриншоты
![unknown (4)](https://user-images.githubusercontent.com/34631419/83324243-9baa0500-a26c-11ea-863d-08e251523c56.png)

**Comment by Pos13** [comment]
Бар продолжает эксперименты с напитками для мимов.

**Comment by Artemonim** [comment]
Баг не в спрайтах, а в коде. Игра пытается отрисовать для пинты охлаждённого пива спрайт коктейля, но что-то идёт не так. Надо убрать смену спрайта или добавить версию жидкости с кубиками льда.
![2021-02-12_18-23-14](https://user-images.githubusercontent.com/36363466/107813350-5c333280-6d81-11eb-9ede-eeebc439872c.png)

**Comment by Tsurupeta** [comment]
Будет пофикшено
