### ISSUE TITLE
Нельзя посылать по ПДА сообщения, содержащие пробел

### ISSUE THREAD

**Issue by kokokobold** [ChaoticOnyx/OnyxBay#2550]
Вижу уже который раунд, но почему-то оно так не во всех раундах. То есть, например, в одном раунде пробелы могут не работать, а в следующем всё будет хорошо. 
ERROR: Messaging server rejected your message. Reason: contains ' '.

Айди раунда: b7p-cPZ7

**Comment by Rodial-Admiral** [comment]
Это не баг. Иногда рандомно перенастраиваются спам-фильтры сервера ПДА, и иногда - на пробел. Тогда надо писать через нижнее подчеркивание.
"Фиксится" ингейм перенастройкой спам-фильтров в консоли сервера сообщений.
