### ISSUE TITLE
Мясной крюк тотально и абсолютно сломан

### ISSUE THREAD

**Issue by TheUnknownOneGH** [ChaoticOnyx/OnyxBay#2551]
### Описание бага
Он не работает ВООБЩЕ, потому что там хреновая проверка, которая никогда не проходит. Убираем проверку - на него можно вешать людей из первого граба, что приводит к удалению хумана и мгновенной смерти как следствие.
> Unknown (as Andre Hardoker) has forced Zander Smith onto the spike, killing them instantly!

Человека тупо удаляет с карты. В общем, это ультимативное орудие убийства, которое (у меня начинает появляться подозрение, что намеренно) сломали одной проверкой, и вряд ли получится его легко починить.

### Воспроизведение
Мгновенное убийство воспроизводится только если удалить проверку if(!issmall(H)) из прока spike() в коде крюка. Иначе на него невозможно повесить человека, а так как вешать можно только из граба, то это означает, что туда никого нельзя повесить.

### Ожидаемое поведение
Ну как минимум без мгновенного удаления и сопутствующей смерти вешать, да и прогресс повешения не помешает. Возможно также на него должны вешаться и животные, потому что ну иначе это чисто маньяческое оборудование, а не поварское.

### Скриншоты
А вот что происходит, если таки повесить на крюк человека (да, это был человек, не мартышка).
![image](https://cdn.discordapp.com/attachments/698083783072546857/716352539477409852/unknown.png)

### (Опционально) Дополнительная информация
Найти того, кто это кодил, и повесить его на мясной крюк.

**Comment by MrMagick2104** [comment]
>  if(!issmall(H))

Наверное, идея в том, что повесить можно только макаку, а не человека? Тогда это довольно сбалансированно и справедливо, т.к. мартышки - не игроки, их можно и мгновенно убивать.

**Comment by TheUnknownOneGH** [comment]
Я посмотрел и вообще да, по идее обезьян должно нормально вешать на него, хотя я не проверял в игре.
Ну тогда я не знаю, баг ли это. Выглядит логично, но у нас есть #1330 который требует "снять ограничение" с крюка. Если снимать проверку на обезьяну - придётся переделывать крюк, потому что мгновенное убийство это фигня, а с текущей логикой работы крюка по-другому сделать я не знаю как даже.

**Comment by Epicus7** [comment]
Ну как-то да, крюк для обезьян сделан - их на него и надо вешать.

Не понял в чем баг, клюк таким и был задуман. Возможно, его надо УЛУЧШАТЬ через УЛУЧШЕНИЕ, но бага я никакого не вижу. Просто этому крюку 10 лет уже и он остался таким, каким всегда был.
