### ISSUE TITLE
Сервер хаотик оникс УПАЛ в районе 18:06 по Москве

### ISSUE THREAD

**Issue by kokokobold** [ChaoticOnyx/OnyxBay#2568]
Не знаю, связаны ли с этим многочисленные поинт ту, но вдруг?
![](http://media.discordapp.net/attachments/709361547637424130/716669394142363699/unknown.png)

Айди раунда: b7q-b74N

**Comment by Epicus7** [comment]
Посмотрел по логам - ничего нет, даже рантаймов. Тут мы ничего не поделать сейчас.
