### ISSUE TITLE
Возможность лежачим держать в руках предмет и использовать его.

### ISSUE THREAD

**Issue by hekko4** [ChaoticOnyx/OnyxBay#26]
Это предложение, его нужно обсудить. 

Сейчас каждый кто лежит - не может использовать предмет, так как он роняет его из рук. 
Думаю это неплохая идея дать возможность держать в руках предмет, если человек конечно не в критическом состоянии, или же, не под наркозом.

**Comment by PlinHost** [comment]
Всплывет столько подводных камней что охренеть можно.

**Comment by Epicus7** [comment]
Да, механ SS13 к этому совершенно не готов, я бы не стал этого добавлять.
