### ISSUE TITLE
Кинетический ускоритель почти не наносит урона в вакууме

### ISSUE THREAD

**Issue by Stalkeros2** [ChaoticOnyx/OnyxBay#262]
**Описание бага**
Кинетический ускоритель не работает так, как надо, всегда выдаёт пониженный урон по всем монстрам на астеройде, и сам стреляет слабыми снарядами в любом состоянии

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем кинетический ускоритель
2. Выстреливаем пять обойм в Голиафа
4. Понимаем, что тут что-то не так

**Ожидаемое поведение**
Ускоритель наносит нормальный урон

**Скриншоты**
![default](https://user-images.githubusercontent.com/42087567/46008616-093c8000-c0df-11e8-9e60-4f9bb11eb8c4.png)
То-же и с остальными монстрами.

**Характеристики**
 - OS: Windows 7
 - Версия клиента 512.1442
 - Версия сервера c1927605635a6b96f3d4fd6e0402b4b98bd2f77b - dev - 2018-09-24
 - ID игры

**Дополнительня информация**
Здесь можете описать любую дополнительную информацию, которая касается бага

**Comment by Doster-d** [comment]
Нихуя какой кабан у нас был, проверьте

**Comment by O0oMaximo0O** [comment]
Проверяли, есть. Там у мобов астероида стоит снижение урона ниже определённого уровня в сколько то раз.

**Comment by O0oMaximo0O** [comment]
О снижении урона говорит строка с `reduced effect`

**Comment by Artemonim** [comment]
> Там у мобов астероида стоит снижение урона ниже определённого уровня

Тут смешнее - у ускорителя есть расчёт урона относительно наличия атмосферы, но расчёт урона идёт мимо этой проверки.

То есть по изначальной задумке он бьёт давлением воздуха, но а) `оно не работает` и б) `зачем такое шахтёрам?`

**Comment by O0oMaximo0O** [comment]
Нееее, ты что. Он наоборот в вакууме сильнее бьёт

**Comment by TobyThorne** [comment]
>Версия клиента 512.1442
>Версия сервера - dev - 2018-09-24

Давайте просто представим, что оно в какой-то момент починилось. А если не починилось - ждём нового иссуя, видимо.
