### ISSUE TITLE
бессмертные павуки, чел сб, бля пиздец онукс лучший билд по факту

### ISSUE THREAD

**Issue by AmbrosiaBlyatFumari** [ChaoticOnyx/OnyxBay#2627]
### Описание бага
резина дробовика артерию ебашут, у СБ нету никаких дистанционных программ для выдачи ареста, маленькие пауки которые бессмертны, пауки жрут своих собратьев приумножая число пауков, вообщем раунды где чейнджы начинают срать пауками просто пиздец

Чел ты?

**Comment by MrMagick2104** [comment]
Что это.

**Comment by TheUnknownOneGH** [comment]
Амброзия до гитхаба добрался...

**Comment by Epicus7** [comment]
Один иссуй - одна проблема.

Программа у СБ есть, пауки переделываются, чо там у дробовика хз.
