### ISSUE TITLE
Ошибка с дубинкой борга

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#2629]
Шоковая дубинка стандартного киборга
Станбатон дефолтного борга не заряжается в заряднике для боргов

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем Стандартного борга
2. тратим заряд дубинки
3. Пытаемся ее зарядить в заряднике для киборгов.
4. Видим ошибку что дубинка не заряжается

### Ожидаемое поведение
Дубинка должна заряжаться

### Скриншоты
Если проблема может быть показана на скриншотах - прикрепите их.
![image](https://user-images.githubusercontent.com/66428431/83770955-60537000-a68a-11ea-855d-8f7f51725c70.png)

**Comment by Kexilex** [comment]
Поменять обычный батон стандартного борга, на mounted baton, как у сбшного борга

**Comment by Kexilex** [comment]
На этот чудесный баг нет времени ок #3121, но неужели дать другой батон так сложно? Я не хочу бить хармбатоном за разбитые лампочки :[

**Comment by Kexilex** [comment]
Ну разряжается же.
