### ISSUE TITLE
Искусственный идиот

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#263]
Если вас кто -то посмеет тронуть в вашей тру форме генокрада, то говнокод берет руль под свой контроль и приклеивает ваше тело к несчастному пока он не перестанет дышать

**Comment by Ruforce** [comment]
????????????????????????????????что

**Comment by ZerlGray** [comment]
Я когда это читал, вообще нихуя понять не смог.

**Comment by MalinaGirl** [comment]
Блядь, ебаный ты шизоид, ты можешь нормально выражать свои мысли?
Твой поток сознания читать просто не возможно. Возникает ощущение,
что у тебя разорванное мышление или речевая бессвязность.
Просто словесный шум какой-то. Прими таблетки и не забывай посещать психиатра,
у которого наблюдаешься.
