### ISSUE TITLE
Блоки и парирования 

### ISSUE THREAD

**Issue by AmbrosiaBlyatFumari** [ChaoticOnyx/OnyxBay#2635]
Блоки занерфлены так что драться к примеру на баллонах или на мечах хуевая идея, т.к в блоке нельзя ударить в ответ а ещё тебя могут ебануть и ты упадешь. 
Типо прикольно каждый раз снимать блок и бить но по факту когда ты выходишь с блока враг может тебя ударить ещё раз *даже если у тебя макрос, уже проверено* 
Парирования вообще не работают или работают так как мы не знаем, пытались парировать на holosword'ах хуйня, на стульях хуйня, как будто шансы парирования вообще 0.1 процент. 
Stanislav Bolgarkov attempts to parry Unknown (as Konstant O'Greidi)'s attack with their the comfy stool!
Stanislav Bolgarkov attempts to parry Unknown (as Konstant O'Greidi)'s attack with their the comfy stool!
Stanislav Bolgarkov breaks the comfy stool over Unknown (as Konstant O'Greidi)'s back! 
Тут парировал стулом пытаясь выбить стул противника пока он не сломался) 

Можно вернуть старую схему блоков с возможностью дать сдачи в блоке и повысить шанс того что в блоке тебя могут наебнуть на землю если ты в нём находишься постоянно, ну или возможность заграбать блокиратора сразу в синий, дабы устроить ему фистинг продвигая так же тему грабов.

**Comment by TobyThorne** [comment]
Реворк блока с возможностью контр-атаки уже две недели висит в виде ПРа.
Парирования юзаются по-другому - после попытки парирования (удар на граббе) есть окошко, в течение которого удар будет отражён с огромным уроном по пойзу.

**Comment by kokokobold** [comment]
Неактуально, блоки же поменяли.

**Comment by TobyThorne** [comment]
Неактуально, блоки были переработаны с возможностью контратаковать после успешного блока, окно парирования значительно увеличено.
