### ISSUE TITLE
Дионы-гештальты имеют сверхзвуковую скорость

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#2637]
### Описание бага
Дионы-гештальты имеют сверхзвуковую скорость. Это если что какая-то новая фича вроде, когда мелкие дионки объединяются в кучку.

### Воспроизведение
Заходим за дионок, объединяемся с другой и летаем по станции, пролетая экран меньше чем за секунду

### Ожидаемое поведение
У них должна быть скорость не выше чем у обычной мелкой дионки, а то и ниже?

А, да, Game ID: b7u-cGFp

**Comment by PlinHost** [comment]
![na](https://user-images.githubusercontent.com/8840325/83798006-36ab4080-a6ac-11ea-984a-9de167afdb6c.png)

**Comment by Epicus7** [comment]
Скорее всего проблема в том, что в гештальте сидело 2 человека. Соответственно они вместе жмут "идти" и начинают летать.

Во всяком случае тестил это одним игроком - у меня полетать со сверхзвуковой скоростью не получилось.

**Comment by kreeperHLC** [comment]
Сделано в #4005
