### ISSUE TITLE
Изменение принципа работы термалок

### ISSUE THREAD

**Issue by ZippoWelder** [ChaoticOnyx/OnyxBay#265]
Предлагаю изменить принцип работы термальных очков.

Основная идея заключается в том, чтобы заменить видимого человека на тепловой, безымянный силуэт. Это обоснованно их нёрфит, снижая обнаружение ролек каким-нибудь левым детективом.

Для других ролей, у кого есть способность к тепловому зрению, можно ничего не изменять. Но тут на ваше усмотрение.

![image](https://user-images.githubusercontent.com/12947348/46154200-d345fa00-c29e-11e8-8181-8ff7b0aa2eb6.png)

**Comment by MalinaGirl** [comment]
Классно, конечно, нерфить термалки, но в мире, где существуют мезонки, материалки, эти новые термалы будут выглядеть крайне странно и тупо.

**Comment by Ruforce** [comment]
хотите унерфать - введите заряд батареи, как у риговских.

через %X% секунд они разряжаются и нихуя не показывают, подрезая обзор как маска сварщика

**Comment by DeltaEpsilon7787** [comment]
Сразу предупреждаю: я уже пытался реализовать подобную хуйню, чтобы видеть людей в ящиках и скажу так: там просто термоядерная ебля. Идея намного сложнее в реализации, чем думаешь.

**Comment by Cinericius** [comment]
Не стоит вскрывать эту тему...
