### ISSUE TITLE
Пофиксить пауков.

### ISSUE THREAD

**Issue by Pl3aseJust3ndMyPain** [ChaoticOnyx/OnyxBay#2653]
Пауки размножаются десятками, часто даже сотнями, убивая и используя тела других пауков как гнёзда. В итоге мы получаем апокалипсис пауков каждые 2-3 раунда.

Следует убрать возможность делать гнездо из пауков, или мы продолжим страдать от тысячи пауков по всей станции.

**Comment by kokokobold** [comment]
Дубликат #2632.
