### ISSUE TITLE
Запретить кириллицу в именах мобов и предметов

### ISSUE THREAD

**Issue by pkuzic** [ChaoticOnyx/OnyxBay#2654]
### Улучшение
Некоторые игроки (судя по всему - новички) создают персонажей, используя кириллицу, в итоге это:
во-первых, выбивается из общего вида.
во-вторых, имя не выводится при наводке на персонажа.

Так же это применимо к предметам.

### Решение
Проверка на наличие кириллических символов в именах мобов и названиях предметов.

**Comment by PlinHost** [comment]
Хороший детектор тех, кто не читал правила.
