### ISSUE TITLE
Хардсьюты а.ка конкурс спрайтиков на максималках

### ISSUE THREAD

**Issue by AmbrosiaBlyatFumari** [ChaoticOnyx/OnyxBay#2658]
Если в конкурсе одобрят скафандры тех или иных людей я предлагаю не спиливать старые образцы а оставить с возможностью кастомки внешности скафандра. 
К примеру вот есть у нас 
![xd3X8cFQonUhQAAAABJRU5ErkJggg](https://user-images.githubusercontent.com/43430615/83952313-c1bd3f80-a840-11ea-9112-516a5a6b54c3.png)
И
![R7FHWJeHAHS5zgDQALpcRzGbtwJ1Ha68QXunLpoJ6vIQgC7XAgAaQJfrKGbzVqCuwxVAe6cumgnq8hCALtcCY7761a9eLHdKZkMB](https://user-images.githubusercontent.com/43430615/83952314-c550c680-a840-11ea-9a4e-05eab4390aea.png)

Вот можно сделать так чтобы к примеру стандартный скафандр можно было заменить на один из этих спрайтиков, зачем спиливать старые если те же в свою очередь уже давно внесли свой шарм в ссочку и так же отсылают к чему то, ну или просто разнообразить ассортимент скафандров и сделать так чтобы спавнились разные виды.

**Comment by MrMagick2104** [comment]
> стандартный хардсьют

Стандартный хардсьют - это кто?
Не очень понятно без конкретики, т.к. хардсьюты со скафандрами особенно ничего много и не имеют. Хардсьюты - костюмы, надеваемые на спину, войдсьюты - обычные скафандры, которые валяются в ЕВА в микроотделах: СБ, инженерный, мед.
Софтсьюты - скафандры не из металла, а из мягких тканей. Это те, которые легко рвутся и вообще не самые полезные. О чём речь тут?

> Если в конкурсе одобрят хардсьюты тех или иных людей я предлагаю не спиливать старые образцы а оставить с возможностью кастомки внешности хардсьюта.

Я бы предложил возможность менять тип скафандра, если это подразумевается быть войдсьютом, при помощи сьют цайклеров. Там уже есть т.н. customisation routine, меняющая скафандры.
Хотя, если это - войдсьюты, то как в них должен сворачиваться и разворачиваться шлем?

**Comment by AmbrosiaBlyatFumari** [comment]
Немного ошибься, в любом случае имею ввиду спрайты стандартных скафандров, те же самые инженеры/сбшные, просто не спиливать их а добавить к ним возможность либо кастомизировать под новые спрайты которые в конкурсе или же сделать так чтобы была разновидность скафандров которые по статам никак не отличаются.

**Comment by TobyThorne** [comment]
>тканевый скафандр который сейчас у нас довольно старый и не особо то красивый и его можно было бы спилить.

Себя спили.


Кастомизация выглядела бы адекватно в виде каких-то минорных аксессуаров, но никак не в виде полной переделки внешнего вида. И так скафандры - цирк из абсолютно разных дизайнов, который не помешало бы хоть как-то стандартизировать.
