### ISSUE TITLE
Where is my xenoreform?

### ISSUE THREAD

**Issue by TwinIndifferent** [ChaoticOnyx/OnyxBay#267]
Собственно, всё как в заголовке.
Ксеносы играют огромную роль в нашем ксенофобском cumмьюнити (ведь надо иметь белых ворон для избиения), а потому, сука, трахните себя в жопу и займитесь реформами для онных.
Какого хуя пидарасы в чешуйках и котики одинаково горят? Какого хуя на диеты всем похуй и я часто вижу бармена-ящера-вегана-гея-феменистку? И хули у РИГов нет нормальных спрайтов для пушистиков?
И да, надо больше ксеносов. Верните пернатых рапторов, введите мотыльков с ТГ как новый вид топлива для розжига крестовых походов и мать вашу, верните блядских неубиваемых ИПЦ. На кого нам дрочить кроме негров и трапо-котов? Правильно, на ИПЦ. И на Шепарда.
А ещё пора давать пизды грифонерам ксеносов форноуризон, ибо быть фурриёбом - не их выбор, а генетическая предрасположенность, а значит и ксеносы должны иметь права, блеать, на бар и голые танцы в коридоре. И нахуй Сильверпавла.
С любовью, Твин.

**Comment by Ruforce** [comment]
>И да, надо больше ксеносов. Верните пернатых рапторов, введите мотыльков с ТГ как новый вид топлива для розжига крестовых походов и мать вашу, верните блядских неубиваемых ИПЦ. 

а еще верните твина на парашу, кто его вообще выпустил?

**Comment by TwinIndifferent** [comment]
Сосни хуйца и делай бочку даже без вопроса.

**Comment by PlinHost** [comment]
> Какого хуя на диеты всем похуй и я часто вижу бармена-ящера-вегана-гея-феменистку?

Джобки/вайтлист на специи зачем)

**Comment by HalilDaBlack** [comment]
На таукитах это реализовано через два реагента-подтипа нутришенов, один из них накидывает скрелам токсины. Зачем тебе нужно еще больше респрайтов хуманов?

**Comment by Cinericius** [comment]
ИПЦ нахуй, человекореспрайты нахуй. Если и завозить алиенов, то таких, шобы сука сразу было ясно, шо это какая-то инопланетная ебанина. 
В принципе у меня есть прожектик один, но нужен кодер, а кодеров выгоднее отправлять кодить более полезные штуки.
