### ISSUE TITLE
Трость для слепых

### ISSUE THREAD

**Issue by AmbrosiaBlyatFumari** [ChaoticOnyx/OnyxBay#2671]
Повысить дальность видимости для слепых персонажей с тростью на ещё один тайл, будет толк от трости за то если все медики помрут.
Трейторской трости можно на все две, ибо она круче...

**Comment by Voldirs** [comment]
Годная идея кстати

**Comment by MrMagick2104** [comment]
> Трейторской трости можно на все две, ибо она круче...

Идея годная, но вот это чёт такое себе. У трейторской прикол же в том, что внутри ножик.
