### ISSUE TITLE
Разнерфить/Бафнуть дробовик.

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#2683]
### Улучшение
Всегда было интересно, почему у нас на станции почти никто (кроме дробовиков-самоделок доступных любому assистенту) не используют дробовики для робуста. Как оказалось, урон шрапнели от дробовика **при выстреле вполтную** - где то на уровне от обычного выстрела с кольта.
Помню во время боя, по одной незащищенной голове более 3-4 раз выстрелил вплотную из дробовика - противник продолжал бегать, прыгать, хохотать. Даже последующие затыкивания выстрелами павшего с критом - не приводили к гибу головы. У нас чертова ППшка голову трупу может гибнуть, а вплотную выстрел из дробовика не может.

### Решение
Апнуть статки дамага для семейства дробных.

**Comment by ArmenianOnyx** [comment]
Есть так же мимохуйное предложение выдать бригу один нормальный боевой дробовик, а не "Кусок червивой деревяхи педофила из нижнего Техаса", я про дробовик бармена, в оружейной брига.

**Comment by MrMagick2104** [comment]
> Помню во время боя, по одной незащищенной голове более 3-4 раз выстрелил вплотную из дробовика - противник продолжал бегать, прыгать, хохотать. Даже последующие затыкивания выстрелами павшего с критом - не приводили к гибу головы. 

А проблема не в том, что патроны были бинбегами?
Если не в этом, то точно не в дробовиках, а в красных патронах.
Со слагами же дробовик превращается в какую-то снайперскую винтовку.
> я про один единственный дробовик бармена, в оружейной брига, с за жопой патронов для его.

У бармена - двустволка. У вардена лежит какая-то пародия на Ремингтон 870, наверное, в дереве?

> бригу один нормальный боевой дробовик

У ХоСа же лежит один? Или уже убрали?
> Апнуть статки дамага для семейства дробных.

Было бы смешнее, я думаю, поднять количество прожектайлов у обычных патронов. Правда, это, наверное, превратит дробовик с ними в лагопушку.

**Comment by Voldirs** [comment]
У меня дежа вю.
https://github.com/ChaoticOnyx/OnyxBay/commit/3574b9afc647cf0d04ce2263a58d29713904c758#diff-36e0da2eb50cae525254a12da474083f
Давайте не будем опять цифорки менять, этот вопрос надо по-другому решать как-то. Да и как по мне дробовики и так нормальные.

**Comment by kokokobold** [comment]
Этот вопрос можно было бы полностью решить с помощью #1038.
Днивжи вот говорит, что это было «частично пофикшено». Как именно?

**Comment by kokokobold** [comment]
Дробовики не так плохи, тут надо не дробовики баффать, а действительно подумать лучше над их работой и поменять это. Мне кажется, что основная проблема дробовиков в том, что они разбрасывают урон слишком сильно, даже если ты стоишь  почти в мили.

**Comment by MrMagick2104** [comment]
> Дробовики не так плохи, тут надо не дробовики баффать, а действительно подумать лучше над их работой и поменять это. Мне кажется, что основная проблема дробовиков в том, что они разбрасывают урон слишком сильно, даже если ты стоишь почти в мили.

Имхо:
Надо бы им разброс иметь в 30 градусов, правда, не знаю, сколько сейчас. Сорок пять, наверное. 
Если так будет, на расстоянии в один-два тайла убивать должно. 
По-хорошему бы поднять количество дробинок, но это сервер будет класть при каждом выстреле, скорее всего.

**Comment by TobyThorne** [comment]
С момента открытия иссуя уже была переработана механика нанесения урона по органам выстрелами, равно как и урон пуль.
