### ISSUE TITLE
ниндзя как гейммод

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#269]
ужасен в принципе.

лютейший аутизм, в котором антаг либо бегает на научном астероиде, боясь проебать гринтекст, либо хуячит есвордом из инвиза

решение - перенос как мидраунд ивент (тг-стаил)

**Comment by Fourest** [comment]
Так он обычно только так и используется, ниндзя – игрушка педалей, на случай, когда надо отпиздить заигравшеюся робусторольку

**Comment by Cinericius** [comment]
Да, хорошая тема.
