### ISSUE TITLE
Пропажа кнопок блок, тугл блок и резист

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#2692]
пропало!
![image](https://user-images.githubusercontent.com/48406301/84316252-7de57580-ab73-11ea-9fbb-6f48e2cba39c.png)
Client Version: 513
Server Revision: ee2c6c94c2e7cb085618073de708ec8bda97ec34 - release/chaotic - 2020-06-07
Game ID: b7A-c1D3
Current map: NSS Exodus

**Comment by kreeperHLC** [comment]
Слишком мало инфы

**Comment by Zert0X** [comment]
![изображение](https://user-images.githubusercontent.com/42303535/164062560-fbb48276-143d-4596-a72f-0f64641401b6.png)
