### ISSUE TITLE
Появляются черные квадраты в космосе

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#2697]
![image](https://user-images.githubusercontent.com/48406301/84389055-31934780-abfe-11ea-9689-cb52a167976c.png)
вот такое иногда появляется в космосе
Client Version: 513

Server Revision: 183a96bd7b21e62060486542e17915337b96c681 - release/chaotic - 2020-06-11

Game ID: b7B-bVy0

Current map: NSS Exodus

**Comment by Zert0X** [comment]
![изображение](https://user-images.githubusercontent.com/42303535/164062586-f6032f62-c0b9-4245-95d3-a8c9dd556fdf.png)
