### ISSUE TITLE
Добавить больше мини-ивентов.

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#27]
Простенькие ивенты которые смогут оживить или разнообразить раунд.

**Comment by Ruforce** [comment]
просто повысьте шанс мидраунд метеоров или блоба.

на другие рандомивенты труженики даже внимания не обратят, продолжая ролеплееть в баре.

**Comment by Epicus7** [comment]
Надо новые ивенты придумать и реализовать, по-хорошему.

**Comment by Cinericius** [comment]
#124

**Comment by Epicus7** [comment]
Прикольные идеи из #124:

1. Прорывы рандомных труб с газом.
2. Поломка проводки (чтобы перегрузка которая иногда случается - сжигала часть проводки).
3. Добавить проебанные аномалии, вроде телепортов, смещения объектов в комнатах etc.
4. Случайные взрывы взрывоопасных приборов. Например случайно взрывающиеся фуелтанки.
5. Случайная поломка системы контроля температуры, из за чего температура в комнате опускается СЛИШКОМ СИЛЬНО. Или поднимается. (Поломка термостатов)
6. Проебы в СМЕСАХ, из за чего большая часть энергии поставляемая в отдел сжирается холодным вакуумом\превращается в тепло.
7. Проебы в шлюзах, которые будут изредка открывать шлюзы в свежесть вакуума.
8. Улучшить код генерации рандомвирусов (там щас у него проблемы большие), добавить аномалии.
9. Весовые коэффициенты перед шансом генерации сделать адекватными.
Чтобы совсем смешное было - добавить оружию шанс оказаться НЕИСПРАВНЫМ. Вот заходишь в оружейку, берешь ствол - идешь воеват. А он неисправен.
10. Добавить смешную фичу с возможность спавна с расширенным\зауженным доступом (типа ошибка отдела кадров ЦК) случайным образом.
Поломка обычных ID карт. Типа ID карта опять же херового качества. 
(это надо согласовать с https://github.com/ChaoticOnyx/OnyxBay/projects/1)
11. Добавить шанс того, что после старта раунда какой то отдел окажется без оборудования. Тупо без вещей. Инженерка без суперматерии, пустая оружейка, РнД с нихера etc.

**Comment by Cinericius** [comment]
Кое-что из новых ивентов нам смержит с Гомобея @PlinHost, там вроде как раз всякие поломки проводки и компуктеров.

**Comment by Cinericius** [comment]
Надо

**Comment by kreeperHLC** [comment]
Перенёс всё адекватное по отдельным иссуям, закрываю
