### ISSUE TITLE
Выпилить visitor'ов

### ISSUE THREAD

**Issue by PlinHost** [ChaoticOnyx/OnyxBay#2700]
### Улучшение
Какие нафиг посетители на "научной" станции? Экипаж должен состоять из сотрудников НТ.

### Решение
Сабж.

### Альтернативы
Переименовать его в что-нибудь вроде "сотрудник, валяющий дурака", но я не придумал, как назвать это точнее, чем уже существующий "ассистент".

**Comment by Epicus7** [comment]
> Экипаж должен состоять из сотрудников НТ.

А выбор фракции в настройках персонажа?

**Comment by PlinHost** [comment]
> А выбор фракции в настройках персонажа?

Пока они работают на НТ - они яваляются сотрудниками НТ.

**Comment by Voldirs** [comment]
Ну да, контрактниками. Просто дело в том что если уж на научной станции есть бар, клоун, мим, психолог, то можно предположить что станция не такая уж и сикретная. Может и экскурсии там водят, не знаю. Скажем так, я бы оставил визиторов как профессию, но убрал бы у них доступ в теха

**Comment by PlinHost** [comment]
Дело не в том, что станция секретная, а в том, что смотреть на ней особо нечего. Щас бы приезжать в ебеня только выпить в баре и посмотреть на перфоманс клоуна.
Но если очень хочется оставить, доступ спилить в техи обязательно, можно вообще айди не давать.

**Comment by ArmolitskiyCarpoeb** [comment]
> Но если очень хочется оставить, доступ спилить в техи обязательно, можно вообще айди не давать.

Идея хорошая, можно будет снять свою ID карту и замаскироваться под визитёра... Только пусть по прибытию они в манифест не зачисляются.

**Comment by MrMagick2104** [comment]
> Идея хорошая, можно будет снять свою ID карту и замаскироваться под визитёра... Только пусть по прибытию они в манифест не зачисляются.

Ну это уже вообще прикол какой-то. С точки зрения целостности игрового мира. Нужно им какой-нибудь другой документ выдавать тогда, не айдишник, а что-то вроде бумажного паспорта.
К '[Бумажки, Пожалуйста!](https://github.com/ChaoticOnyx/OnyxBay/projects/1)' приклеивается хорошо, в таком случае.

И, ещё, нужны фейковые документы в аплинке, обязательно. Для стелс-нюкотрейторов.

**Comment by PlinHost** [comment]
Геймдизы не заметили мой иссуй и запилили свой #2748

**Comment by TapKo4eB** [comment]
ъуъ
\
