### ISSUE TITLE
Кресты на инженерах

### ISSUE THREAD

**Issue by TheUnknownOneGH** [ChaoticOnyx/OnyxBay#2702]
### Описание бага
После последнего обновления почти на всех персонажах-инженерах постоянно рисуется красный крест. Причём это скорее всего не баг спрайта какого-то предмета (вывод сделан по наблюдениям, так как кресты появляются только на тех, кто заходит с работой инженера).

### Скриншоты
![image](https://cdn.discordapp.com/attachments/447559366237880341/720958596547870800/unknown.png)
(скриншот с хаотика)

### (Опционально) Дополнительная информация
Скорее всего связано с изменением названия работы инженера.

**Comment by TapKo4eB** [comment]
крестоносцы

**Comment by TapKo4eB** [comment]
чо пишет крест при наведении на него мышкой

**Comment by PlinHost** [comment]
Проблема скорее всего на стороне клиента.

**Comment by kokokobold** [comment]
Выяснилось, что эта проблема встречалась не только у ОПа, но не с инженерами. Кроме того, выяснили, откуда именно этот крест. От ид-карты инженеров. Сама карта отображалась прекрасно, а вот на мобе вместо неё (или вместе с ней) был красный крест. Сам крест никак не подписывался, он сливался с мобом.

**Comment by TheUnknownOneGH** [comment]
Вдобавок выяснилось, что крест виден только с секьюрити ХУДом и при надетой карте инженера.
Из чего мы можем сделать вывод, что проблема в спрайте иконки ХУДа для карты инженера. И опять же это скорее всего связано с изменением названия работы инженеров.
