### ISSUE TITLE
Спрайт вэйпа

### ISSUE THREAD

**Issue by Godofspace21** [ChaoticOnyx/OnyxBay#271]
**Описание бага**
При экипировке е-сиги (дешёвой, с дорогой не проверял) используется плейсхолдер маски

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем е-сиг
2. Экипируем
3. ??????
4. PROFIT

**Ожидаемое поведение**
Должен был появиться хотя бы спрайт обычной сигареты

**Скриншоты**
![image](https://user-images.githubusercontent.com/27782156/46629704-783bbf00-cb4a-11e8-9d21-f29eb725bdd0.png)

**Характеристики**
 - OS: Шиндовс 8
 - Версия клиента 512.1448
 - Версия сервера  b851043e1cacf70cfe44789f88cbad360720e836 - dev - 2018-10-05
 - ID игры  bWJ-c4m0

**Comment by blakecrazy13** [comment]
![screenshot_69](https://user-images.githubusercontent.com/45846185/50135423-d968d700-02df-11e9-90bb-fb2b0b7b3d97.png)
![screenshot_66](https://user-images.githubusercontent.com/45846185/50135424-da016d80-02df-11e9-9c54-61b7db3847f8.png)
![screenshot_67](https://user-images.githubusercontent.com/45846185/50135425-da9a0400-02df-11e9-9d0b-4ce19afdadb6.png)
![screenshot_68](https://user-images.githubusercontent.com/45846185/50135426-da9a0400-02df-11e9-85ad-a90a389598fe.png)

**Comment by blakecrazy13** [comment]
Все же нормально показывается...

**Comment by MorJams** [comment]
@blakecrazy13 В руке возьми

**Comment by Epicus7** [comment]
Я чинил это - все должно работать.

Возможно есть проблема с какими-то конкретными сигаретами, но тогда нужно конкретика.

Т.к. автор пропал - закрываю до воспроизведения.
