### ISSUE TITLE
toggle darkness странно действует на гостов

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#2711]
ну сравните
![й](https://user-images.githubusercontent.com/48406301/84546867-f599d880-ad0a-11ea-99d8-54d64c605423.png)
![2](https://user-images.githubusercontent.com/48406301/84546888-05192180-ad0b-11ea-85c0-b7924208ce80.png)

**Comment by O0oMaximo0O** [comment]
Что-то я не понял... Лампа переехала что ли?

**Comment by TobyThorne** [comment]
Сравнил, ничего не понял.
