### ISSUE TITLE
Возможность менять цвет для одежды в лодауте

### ISSUE THREAD

**Issue by SukaYaEbalPridumivatImya** [ChaoticOnyx/OnyxBay#2726]
Обязательно добавить такую возможность для Long black jacket и для обычного Black leather jacket.
Ещё неплохо было б добавить для серого пальто такую же хрень, но это опционально уже.
Остальные виды разноцветной одежды уже на ваше усмотрение.

**Comment by kokokobold** [comment]
Вопрос простой: это делать для лодаута или сделать возможность в игре как-то поменять цвет? Если в игре, то как?

**Comment by SukaYaEbalPridumivatImya** [comment]
> Вопрос простой: это делать для лодаута или сделать возможность в игре как-то поменять цвет? Если в игре, то как?

Сделать в лоадауте, как и для других видов одежды.

**Comment by kokokobold** [comment]
Ага, вот это надо было сразу писать.
