### ISSUE TITLE
Цвет ника НЕ СОХРАНЯЕТСЯ.

### ISSUE THREAD

**Issue by MorJams** [ChaoticOnyx/OnyxBay#2736]
Пробовал через преференсы, пробовал через сетап чарактерс. Результат один - сбрасывается к самому последнему доступному варианту.

**Comment by MorJams** [comment]
Поставил как-то во вчерашнем раунде другой цвет, на следующий сбросился.

Сегодня захожу во время уже начатого раунда - всё ещё цвет стандартный (самый последний), но внезапно после перезапуска раунда цвет стал таким которым я его выбрал вчера.

**Comment by MorJams** [comment]
WeRememberYouGarold: У меня половина сохраненных персонажей в сетапе пропала
WeRememberYouGarold: Вернее, они рандомно исчезают и появляются после каждого выхода и входа в меню сетапа

Хуй знает, мне кажется что это может быть чем-то связным

**Comment by TheUnknownOneGH** [comment]
У меня такая хрень с сохранёнными персонажами была как минимум полгода назад примерно так же, как описал Гарольд. Не понятно, с чем связанно, никаких явных причин я найти не смог.
А ещё одна ржака, которая до сих пор у меня сохранилась - когда я сбрасываю слот персонажа (Reset slot), у меня появляется не стандартный человек, а Синвикта, которого я создал, какое-то время играл, а потом удалил и пересоздал в другом слоте месяцев девять назад. Опять же, с чем связано - неизвестно.

**Comment by Animesku** [comment]
По сути #2501

**Comment by Epicus7** [comment]
Не, #2501 тут не причем. У тебя все настройки слетели, а тут проблема только с опцией цвета ника.

**Comment by MorJams** [comment]
Плин говорил, что это из-за того, что сначала загружаются донаты, а потом преференсы. Или наоборот. Я не помню что он говорил.

В любом случае, выше я сказал, что иногда они рандомно возвращались.
