### ISSUE TITLE
Make virology great again

### ISSUE THREAD

**Issue by CBNTYC** [ChaoticOnyx/OnyxBay#2738]
ФИЧА: make virology great again

Давайте начистоту: вирусология в нынешнем виде сосёт жопу. При том, что её выделили в отдельную профессию, у неё крайне скудный диапазон средств и направлений разработок в сравнении с другими схожими отделами типа ксенобиологии и ксеноботаники, и в 90% игр этот отсек просто бесполезен. У меня есть несколько предложений:

1. Добавить фичи из других механик. На данный момент у вирусов буквально 2,5 полезных синдрома, часть из которых едва ли пригодится, а часть вообще не работает. Раз уж черви убраны из ротации, а клонирование фактически не используется, то можно часть плюшек добавить в виде синдромов для вирусов, заодно взяв интересные синдромы с других серверов, а то взяли только синдромы для самогиба. Ибо одно дело полчаса выдрачивать безопасный патоген с  неработающей телепатией, другое - создание халков, телекинетиков, ну или просто чего-то более полезного для быта станции.

2. Перебалансировка вирусов. Сейчас, даже если ты выведешь полезный вирус (что получается из-за рандома отнюдь не всегда) - его применимость крайне спорна. Проявления полезных синдромов ждать долго, их польза минимальна и может не  подходить под сменившуюся 5 раз за время течения болезни ситуацию, да и длится этот полезный эффект относительно недолго, ибо сама полезная болезнь быстро проходит. Это же отчасти мешает использовать вирусы как оружие, потому как выходит слишком ненадежно. Как исправить: пусть преимущество в ротации синдромов у вирусов, заказанных с ЦК и появившихся после мутации будет у полезных, либо наиболее редких и опасных, а также ввести механизмы воздействия на развитие болезни - такое как более быстрое проявление синдромов и непрекращаемость болезни со временем (либо с помощью новых синдромов, либо добавлением новых характеристик, как с заражающимися видами). Случайно возникающие и подхваченные от мышей вирусы могут все также быть разной степени поганости.

3. Возможность регуляции базы данных. В случае создания и прививания  полезного вируса ты для медиков помечен также, как и космоспидозник. В случае если карго не работает, из-за многократного облучения судного запаса вирусов база данных заполняется ненужными полудубликатами. А редкий вирусолог-тритор или просто решивший провести массовый эксперимент учёный не могут наполную использовать свой арсенал, ибо иначе легко спалятся даже до получения каких-либо результатов своих действий. Решение: дать возможность вирусолога регулировать базы данных, маркируя безвредные и полезные патогены, а также удаляя по каким-либо причинам просканированные патогены.

**Comment by Voldirs** [comment]
Тут лучше глянуть как на других билдах с этим дела обстоят, по первым двум пунктам не особо много конкретики, третий пункт нравится

**Comment by anihillator** [comment]
> Тут лучше глянуть как на других билдах с этим дела обстоят, по первым двум пунктам не особо много конкретики, третий пункт нравится

Берем и смотрим в ТГ вирологию.
Для начала, добавление симптомов и мутация не совсем рандомны- есть десяток или около того различных химикатов, которые выдают симптомы определенного уровня. Начиная от вирусфуда, у которого только первый уровень, заканчивая урановым гелем, который еще и хрен достанешь.
Синаптизин удаляет один рандомный симптом (приходится делать много копий вируса и надеяться, что удалится нужный.
Еще есть формальдегид, который симптомы нейтрализует, но не удаляет.
У нас в химии большинства этих вещей нет, но закодить рецепты несложно.

Далее.
У вируса есть характеристики типа скрытности- собственно 
>В случае создания и прививания полезного вируса ты для медиков помечен также, как и космоспидозник
Высокая скрытность=сканер не палит.
Низкая опасность=сканер палит как добровирус.
Все описывать не буду.
Ну а сами симптомы если переводить, то выйдет стена текста, но поверь мне, там достаточно интересные вещи.

**Comment by CBNTYC** [comment]
Второй пункт: заказ новых вирусов или мутацию старых применяют для получения более полезных синдромом, на крайняк - чтоб получить пригодные виды распространения. Это ломается о рандом, скудное разнообразие симптомов и малое количество путей их получения. Я предлагаю увеличить шанс появления при мутации и заказе с ЦК либо полезных синдромов, либо угрожающих жизни, здоровью и имуществу, либо наиболее интересных, с предварительным созданием соответствующих категорий. 
Другой проблемой является то, что полезные и опасные синдромы находятся на более поздних ступенях, что вкупе с долгим и постепенным развитием болезни заставляют слишком долго ждать желаемого результата, который к тому же по прошествии времени может быть бесполезен либо вреден, если вообще успеет наступить. Вдобавок к этому, вовред полезным вирусам идёт то, что со временем организм их сам перебарывает и отключает, из-за чего схема действия полезного синдрома вырождается в "20 минут жду эффекта - 15 минут наслаждаюсь эффектом - вирус выведен, сосу жопу дальше". Предлагаю ввести дополнительные параметры для вируса, наподобие заражаемых видов и типа распространения, но отвечающих за скорость развития болезни и способность к сопротивлению пассивного иммунитета

**Comment by forestpsy** [comment]
Одно могу сказать точно - вирусология в нынешнем  состоянии действительно страшная тоска. Нужно больше опасных симптомов, больше полезных. Больше вирусов которых сложнее лечить (убивает быстрее чем вырабатываются антитела), что бы вирусологам пришлось контрить симптомы у обезьяны или человека, пока не появится вакцина. Что бы меры карантина имели хоть какой то смысл. Сейчас рецепт против всех вирус один. И это очень скучно. Можно даже вирус  не изучать -  взял макаку, вколол вирус, вколол радий, две минуты и готово.

**Comment by forestpsy** [comment]
Можно  убрать облучение радиацией и заменить на шанс мутации при заражении нового хоста. Таким образом будет весело разводить обезьянок. Так же, можно попробовать добавить зомби вирус и сегменты которые будут усиливать зомби - тогда вирусологи могут выводить зомби вирусы и отсек вирусологии может заиграть новыми красками.

**Comment by TobyThorne** [comment]
С момента открытия иссуя вирусология уже была переработана, так что он не шибко актуален.
