### ISSUE TITLE
Речь под алкашкой и так как говно выглядела, а сейчас ещё хуже.

### ISSUE THREAD

**Issue by SukaYaEbalPridumivatImya** [ChaoticOnyx/OnyxBay#2741]
Лучше уж, блять, обратно верните старый вариант. Он хоть и хуйня был, но не настолько, как нынешний.
После трёх глотков рома, блять, речь, как после трёх бутылок водки разом.
Тупое говно тупого говна, говно.

**Comment by Pos13** [comment]
> Тупое говно тупого говна, говно

Похоже, эффект ещё действует.

**Comment by SukaYaEbalPridumivatImya** [comment]
> > Тупое говно тупого говна, говно
> 
> Похоже, эффект ещё действует.

Т'по г'ВН уп'О г'а Но
Вот так вот эффект действует. Эффект говна.

**Comment by Pos13** [comment]
Хуйню сказал. Пруфы или не было.

**Comment by SukaYaEbalPridumivatImya** [comment]
> ~Хуйню сказал. Пруфы или не было.~
> Количество заглавных букв уменьшено. Кавычки больше не спавнятся случайно, а вырезают только гласные с определённым шансом. Короче, копируй реальные цитаты, а не выдуманную хрень.

Вы нахуя шансы убрать гласные выкрутили на сто процентов?

**Comment by Pos13** [comment]
> Вы нахуя шансы убрать гласные выкрутили на сто процентов?

О чём ты говоришь вообще?
Во-первых, раньше они вообще были случайными.
Во-вторых, шанс замены составляет 33%.
В-третьих, некоторые гласные не заменяются никогда.

**Comment by SukaYaEbalPridumivatImya** [comment]
> > Вы нахуя шансы убрать гласные выкрутили на сто процентов?
> 
> О чём ты говоришь вообще?
> Во-первых, раньше они вообще были случайными.
> Во-вторых, шанс замены составляет 33%.
> В-третьих, некоторые гласные не заменяются никогда.

Глассные раньше заменялись и, мать его, это хотя бы было можно разобрать.
Но вот когда я три раза хотел сказать слово "Какой" и у меня три раза вышло "К'г'й", то вот вообще хуйня, знаешь ли.

**Comment by Pos13** [comment]
А в-четвёртых, бхиэ вщэ мнга глсных проглтвйт.

**Comment by SukaYaEbalPridumivatImya** [comment]
> > Вы нахуя шансы убрать гласные выкрутили на сто процентов?
> 
> О чём ты говоришь вообще?
> Во-первых, раньше они вообще были случайными.
> Во-вторых, шанс замены составляет 33%.
> В-третьих, некоторые гласные не заменяются никогда.

Любой алкашки глотни в баре три раза, а потом через пять минут попробуй поговорить, я посмотрю на твои успехи.

**Comment by Pos13** [comment]
> Но вот когда я три раза хотел сказать слово "Какой" и у меня три раза вышло "К'г'й"
Буква "К" никогда не заменяется на "Г". Вывод - ты пиздишь.

**Comment by Pos13** [comment]
При экстремальном невезении могло получиться Х'х'й (шанс 1,19%).

**Comment by Pos13** [comment]
@SukaYaEbalPridumivatImya Короче, показывай чат. Если всё так плохо - снизим параметр в 33%. Но пока ты приводишь выдуманные примеры из воздуха.

**Comment by Voldirs** [comment]
Хорошая речь, качественная, что-то понятно, что-то непонятно, но по большей части суть уловить можно

**Comment by SukaYaEbalPridumivatImya** [comment]
> @SukaYaEbalPridumivatImya Короче, показывай чат. Если всё так плохо - снизим параметр в 33%. Но пока ты приводишь выдуманные примеры из воздуха.

https://sun3-10.userapi.com/YpMibMwg2xfab16-fUjphRxDcxN4BFRnMKo50A/CCz-NXQbnoY.jpg
Внимание на речь Борьки. Если часть предложений можно разобрать, то в некоторых словах гласных вообще нету, даже, если изначально было три.

**Comment by Pos13** [comment]
Ржака.
Надо бы гласные от согласных отдельно проверять, с пониженным шансом... Хотя так тоже атмосферненько.

**Comment by koronoshka** [comment]
Я трачу столько же времени на распознавание пьяной речи, сколько на распознавание этого пьяного текста, но если такой разнос идет после трех глотков рома то чет не очень.
