### ISSUE TITLE
А почему бы не добавить зомби?

### ISSUE THREAD

**Issue by SukaYaEbalPridumivatImya** [ChaoticOnyx/OnyxBay#2749]
Не, ну реально. Мог бы быть интересный режим, но только при достаточном количестве людей.

И чтоб как в Валькиных Дедах люди не хотели признаваться, что они зомби, чтобы их не пристрелили.

Такая драма могла б быть и такой же экшон.

Можно сделать им абсолютный резист к боли, но убрать любые регенеративные способности, даже минимальные. Вот и всё, получился зомби. Ну, ещё речь как-нибудь испортить или вообще любое слово на кряхтение заменить.

**Comment by ArmenianOnyx** [comment]
Иссуй с зомбями уже давно есть, просто он в гробу и геймдизи за него не берутся.
https://github.com/ChaoticOnyx/OnyxBay/issues/1834#issuecomment-638058551

**Comment by SukaYaEbalPridumivatImya** [comment]
> Иссуй с зомбями уже давно есть, просто он в гробу и геймдизы за него не берутся.
> [#1834 (comment)](https://github.com/ChaoticOnyx/OnyxBay/issues/1834#issuecomment-638058551)

Я честно скажу, не понимаю, чего такого сложного. Можно всё через вирус организовать просто. Чтоб он убирал боль, но и не давал регенерировать, как я написал уже. Только с некоторыми правками.
Чтоб при заражении писалось, что вы чувствуете недомогание и желание есть мясо. А при смерти, уже будучи на определённой стадии заражения выдавалось сообщение, что ваше тело скоро встанет.

**Comment by Epicus7** [comment]
Дубликат, как уже отметили.
