### ISSUE TITLE
У инженеров протерялись спавнпоинты

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#2750]
### Описание бага
После #2386 у инженеров слетели спавнпоинты.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Жмём реди с префами на инженера до начала раунда.
2. Ждём 180 секунд до начала раунда.
3. Спавнимся не в инженерном отделе, а на выбранном в меню настройки персонажа спавнпоинте (вместо переодевалки инженерного - шаттл прибытия, например).

### Ожидаемое поведение
Ты спавнишься на спавнпоинте инженеров, а не дефолтном.

**Comment by Epicus7** [comment]
Пофикшено в #3044
