### ISSUE TITLE
Баг с плодами растений

### ISSUE THREAD

**Issue by Scadouge** [ChaoticOnyx/OnyxBay#2755]
### Описание бага
Через некоторое время после начала раунда. При посадке семян, плоды/семена всех других растений меняются на них.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем семена любого растения **(Х)** и
(меняем любой ген в биобаллистике и сажаем)
ИЛИ
(сажаем и мутируем растение).

### Ожидаемое поведение

- Все растения на карте будут производить плоды растения **(Х)**. 
- Плоды будут иметь одинаковые свойства как у растения **(Х)**, но окрас будет под цвет оригинала. 
- Если повторить баг и получить новые плоды другого растения **(Х2)**, то все плоды **(Х)** будут анализатором показываться как плоды **(Х2)**.

### (Опционально) Дополнительная информация

- У всех новых растений номер 186 (заметка в пределах раунда)
- Первые растения не багуют.
- Начал замечать этот баг чаще, когда ботаники начали по кд мутировать растения.

**Comment by Scadouge** [comment]
Кусачками тоже получаются семена не того растения

**Comment by Scadouge** [comment]
![bug](https://user-images.githubusercontent.com/22453846/84890443-16638480-b0a3-11ea-8177-de484acd823e.png)
Проверил. На скриншоте нижнее правое растение имеет номер 185, все остальные ксенорастения получили номер 186, с них падают одни и те же плоды.

**Comment by Scadouge** [comment]
В другом раунде номер остановился на значении 188

**Comment by Mark-Silverstein** [comment]
Прям квантовая запутанность какая-то, но я этот баг сегодня видел.
С томатом (он мутировал) и бананами (стали дубликатом томатов). 
Вот айди раунда.
Client Version: 513
Server Revision: 57a55ba122299f4abe21c2901b63b594839fc5f4 - release/chaotic - 2020-06-14
Game ID: b7H-bxbC

**Comment by Scadouge** [comment]
Если в раунде больше одного ботаника/ксеноботаника которые мутируют или изменяют растения, то "место" под новые цветочки заканчивается минут за 30, дальше ксеноботаник просто сидит отдыхает до конца раунда.
