### ISSUE TITLE
Добавить новый мажор ивент: Нашествие "Creature"

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#2761]
Предлагаю добавить мажор ивентом нашествие на станцию жутких существ, которые в билде имеют название "Creature"
Как все будет происходить:
- Оповещение с ЦК о блюспейс аномалии.
- В гетто появляются 3-5 особей.
- You get a feeling you should run.

![image](https://user-images.githubusercontent.com/62835631/84878676-5bdc7d80-b0b4-11ea-982c-33cf60da6b84.png)
![image](https://user-images.githubusercontent.com/62835631/84878706-6434b880-b0b4-11ea-84fc-7d840f5acf15.png)

Как мажор ивент абсолютно вписывается в реалии ССки, имеет разные ответвления для развития истории, а так же это не конченный блоб спам.

**Comment by MrMagick2104** [comment]
> Предлагаю добавить мажор ивентом нашествие на станцию жутких существ, которые в билде имеют название "Creature"

Они говно, нет? 
С оповещением слишком просто будет, ибо если ты знаешь об их присутствии, они тебе ничего особо сделать не могут.
Они довольно слабые:
Если у тебя есть хоть какая-то бумпалка, то их практически всё ваншотает, а если нет, но есть товарищ, то всё равно особо сделать тебе ничего не могут, т.к. в несколько целей они не могут.

**Comment by forestpsy** [comment]
Оповещения на самом деле может быть интересно. Например в начале раунда становится известно что синдикат вооружен боевыми мехами и собирается уничтожить станцию. Может получится забавный режим, где роботехи пересаживают СБ в гигагсав (включая спасенные мозги) и другие фанавые штуки. Будет как нюка, только с оповещением (но не таймером), где раунд по сути будет не очень длинным, но длинее чем спидран на нюке это точно. Сам же синдикат не будет ждать пока станция  приготовит все что нужно, а по возможности саботируют, затем через х времени они могут телепортироватся к боевыем мехам и обратно уже с ними на станцию.

**Comment by ArmenianOnyx** [comment]
> Оповещения на самом деле может быть интересно. Например в начале раунда становится известно что синдикат вооружен боевыми мехами и собирается уничтожить станцию. Может получится забавный режим, где роботехи пересаживают СБ в гигагсав (включая спасенные мозги) и другие фанавые штуки. Будет как нюка, только с оповещением (но не таймером), где раунд по сути будет не очень длинным, но длинее чем спидран на нюке это точно. Сам же синдикат не будет ждать пока станция приготовит все что нужно, а по возможности саботируют, затем через х времени они могут телепортироватся к боевыем мехам и обратно уже с ними на станцию.

Ты иссуем ошибся. Тут другое обсуждение.

**Comment by Epicus7** [comment]
Можно добавить как событие сторителлера, но судя по всему оно не очень серьезное.
