### ISSUE TITLE
Добавить социальные предметы

### ISSUE THREAD

**Issue by PatapoIIIa** [ChaoticOnyx/OnyxBay#2767]
### Улучшение
В игре отсутствует такой важнейший социальный предмет как цветы и предметы для дарения из ряда несущих повышенную ценность
### Решение
- Добавить цветы;
- Добавить букеты из цветов;
- Добавить больше сладостей;

**Comment by Doster-d** [comment]
Опять трап выходит на связь...

**Comment by MrMagick2104** [comment]
> Добавить кольца, кулончики

Уже есть, емнип.

**Comment by kokokobold** [comment]
Насчёт кулонов не уверен, а вот кольца в билде действительно есть. Даже обручальные!

**Comment by MrMagick2104** [comment]
>  кулонов 

Не уверен, что это то, но, по-моему, в лоадауте есть "сильвер локет".
Кулон с фоточкой внутри, т.е.
Не думаю, что сложностью станет наделать парочку копий и респрайтов.

**Comment by PlinHost** [comment]
Произошло будущее и цветы перестали быть актуальны. Лучший подарок девушке - изолированные перчатки и мультитул.
