### ISSUE TITLE
Роль для персонажей в крите

### ISSUE THREAD

**Issue by mikhailtyutkin** [ChaoticOnyx/OnyxBay#277]
#### Описание проблемы
Роль выдаётся персонажам в критическом состоянии в середине раунда

#### Разница между реальным поведением и ожидаемым

Ожидается, что персонаж в критическом состоянии не получит роль вместо здорового экипажа

#### Как воспроизвести проблему?

Ввести персонажа в крит и ждать, что тебе выпадет роль

#### Конкретная информация

Чуть позже скриншот прикрепляю

#### Как долго известно о проблеме?

Встретилось на этой неделе с утра при маленьком онлайне(~8 человек)

#### Дополнительная информация

- [ ] Проблему можно воспроизвести хотя бы один раз
- [ ] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [ ] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [ ] Проблема случилась в недавнем раунде (прошло меньше недели)
- [ ] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by Cinericius** [comment]
Да, стоит пофиксить.
