### ISSUE TITLE
Накодить нейронку

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#2770]
### Улучшение
В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.

_Недостаточно большое количество ревертов неработающих и поломанных вещей._

### Решение
Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы.

_Накодить нейронку которая будет заменять кодеров опуха._

### (Опционально) Альтернативы
Опишите альтернативы, о которых вы думали. Почему именно ваше решение является лучшим?

_Накодить стандартный алгоритм без машинного обучения, который так же прекрасно заменит кодеров опуха._

**Comment by ZerlGray** [comment]
Потенциально таким же методом можно решить и проблемы с игроками

**Comment by Voldirs** [comment]
![image](https://user-images.githubusercontent.com/4889771/85151917-068fa000-b25d-11ea-8e75-56217be25fed.png)

**Comment by kokokobold** [comment]
Не.
