### ISSUE TITLE
Переосмысление бюрократии

### ISSUE THREAD

**Issue by forestpsy** [ChaoticOnyx/OnyxBay#2791]
> ### Улучшение
> В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.

Я один из тех кто считает что бюрократия может быть интересной игровой механикой. Но беда в том, что ебатня с бланками ингейм - ужасная тоска. Я считаю что нужно переосмыслить бюрократический механизм в игре, путем изменения или добавления игровых механик, а так же в целом придания этому занятию некий смысл. 

Сразу хочу сказать, что я понимаю что не все получают от бюрократии удовольствие, а так же том что это в целом противоречивый элемент  игры. 

Я заметил что у вас в проектах есть референс на Papers, Please, маленькая индюшка о  пограничнике и проверке документов. Можно было бы проанализировать то как игра превращает проверку различных бланков, документов, рабочих виз в увлекательную мини игру. При этом все на достаточно серьезном тоне. 
Я бы выделил в первую очередь то, что у нас сам процесс создания и заполнения бланка достаточно уныл, часто требует оос источник, и выглядит это все достаточно тоскливо. 
В Papers, Please, документы генерируются и собираются в красивые бланки и формы, с печатями и прочими атрибутами. 

> ### Решение
> Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы.

Я предлагаю отказаться от использования BB кода при работе с документами и вместо этого запилить девайс для печати документов. Он будет содержать в себе нужные бланки и \ или фрагменты для генерации необходимых пропусков, разрешений или иного. 
Тут конечно минус такого подхода  в том, что нужно заранее продумать возможные бюрократические нужды. Но некоторые можно выделить сразу:

Временный гостевой пропуск например. То что есть сейчас, меня на самом деле устраивает, это пример того как отказались от BB кода в пользу геймплейного решения. 

Смена должности у ХоПа - не очень редкое событие, которое генерирует тоскливые документы, которые мало куда попадают. Можно придумать множество улучшений - включая возможность дистанционно менять допуск карты. Это конечно может сильно отразиться на геймплее, тут стоит поискать плюсы и минусы. Но в целом это же мега логичная фича, которая существует уже сегодня, что там про супер продвинутое будущие. Больше нельзя будет украсть карту капитана и ходить с ней весь раунд, при обнаружении пропажи она просто аннулируется. 

Карго может печатать накладные просто сканируя ящики. 
Ксеноботаник может распечатать удобную форму генома для ведения записей.
Возможность составлять  опись инвентаря отсека просто сканируя тайлы и затем в конце получать готовый документ для печатей глав. 
Система должна сама генерировать документы там, где это можно сделать автоматически. 

> ### (Опционально) Альтернативы
> Опишите альтернативы, о которых вы думали. Почему именно ваше решение является лучшим?

Это конечно все очень концептуально сейчас, можно подумать в совершенно разных направлениях и найти другие решения и компромиссы. Хотелось бы что бы бюрократия  не раздражала игроков и при этом являлась бюрократическим геймплеем, который бы поощрял тех кто знает в этом деле толк. У бюрократии должна быть функция и рычаги воздействия на станцию (как например хоп, который может давать или отбирать доступ).

Что если отчеты АВД будут сохранятся между раундами? Тогда у его расследований будут последствия (например в коротком джоб бане, как уже как то предлагалось). Может тогда и судьям будет что делать, разбирать отчеты с прошлых раундов и олицетворять таким образом силу правосудия НТ(нет). Те кого судят, смогут играть представителя осуждаемого и говорить от его имени. Адвокаты, прокуроры. Делать наказание в  виде джоббана на все профессии кроме "заключенный", который будет иметь лишь одно место спавна - тюрьма. Может быть весело и  даже создать некий фидбек между осужденными на бан \ джоббан и администрацией. Но это не точно.

**Comment by ZerlGray** [comment]
1) Можно добавить функцию распечатки бланков с готовым BB шаблоном. И добавить набор шаблонов из вики.

2) Чтобы бюрократия работала, нужно чтобы у нее было хоть какое то отражение в механике, а не только в воображаемом арпи.

3) А чтобы реализовать адекватно механику, нужны люди, которым это будет интересно делать. Судя по тому, как уже какой год подряд починка чего бы то ни было в билде сводится к вырезанию этого самого, никто это делать не будет.

**Comment by forestpsy** [comment]
> 1. Можно добавить функцию распечатки бланков с готовым BB шаблоном. И добавить набор шаблонов из вики.

Даже это будет хай-теком в сравнении с копипастой кода с помощью ручки на бумагу. 

> 2\. Чтобы бюрократия работала, нужно чтобы у нее было хоть какое то отражение в механике, а не только в воображаемом арпи.

Самым очевидным примером будет хоп. Это роль бюрократа, который не имеет нормальных инструментов для работы.  
Накладные в карго никто не пишет в первую очередь потому что в рот сношали они эту ужасную бумажную работу. Но если это будет автоматизировано, это же полезная ингейнм информация для глав - сколько ресурсов добыто, в какие отделы они направлены. 

> 3\. А чтобы реализовать адекватно механику, нужны люди, которым это будет интересно делать. Судя по тому, как уже какой год подряд починка чего бы то ни было в билде сводится к вырезанию этого самого, никто это делать не будет.

Ну это уже как есть.

**Comment by ZerlGray** [comment]
> это же полезная ингейнм информация для глав - сколько ресурсов добыто, в какие отделы они направлены

Нет. Им от этого не горячо, не холодно. Нет системы поощрений.
