### ISSUE TITLE
Добавить метод получения кастета

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#2808]
В одобренном ПРе #2714 добавлен кастет. Но нужно определиться с методами получения. 

Варианты:
1. Добавить во взломанный автолат. //плохое
2. Добавить в техтоннели и гетто с определённым шансом спавна.
3. Можно будет делать из разных материалов.

Мне больше всего нравятся варианты 2 и 3.

**Comment by MrMagick2104** [comment]
2 и 3, учитывая возможности делать самодельные ножи и биты - самые лучшие варианты. 1 - херня.
А из других вариантов как-то не особо подходит:
1. Делать в научке?
2. Продавать в аплинке?
3. Заказывать в карго?
4. Положить в арсенал?

Так что, я думаю, два и три куда лучше всего,  хотя три опционален, ибо смысла не очень много.

**Comment by koronoshka** [comment]
Гачи клуб в гетто звучит как хорошее место для парочки кастетов с некоторым шансом спауна.

**Comment by ArmolitskiyCarpoeb** [comment]
Так как кастет имеет 10 force (если он из обычной стали), то самым верным вариантом является спавн кастета в техах с некоторым шансом.

**Comment by MrMagick2104** [comment]
> Так как кастет имеет 10 force (если он из обычной стали), то самым верным вариантом является спавн кастета в техах с некоторым шансом.

Если кастет будет спавниться с некоторым шансом в техах, им просто никто не будет пользоваться.
Как, например, с ножами-бабочками. Куда вероятнее встретить человека с тактическим ножом, чем с нею, так будет и с кастетами, пусть они и могут быть объективно лучше, т.к. возможностей получить их более-менее регулярными методами нет.

**Comment by kokokobold** [comment]
Вместо шанс на спавн лучше его точно спавнить где-то, вопрос только в том, где именно его спавнить. Вариант с автолатом мне не очень нравится.

**Comment by MrMagick2104** [comment]
> Вместо шанса на спавн лучше его точно спавнить где-то, вопрос только в том, где именно его спавнить. Вариант с автолатом мне не очень нравится.

А вариант с крафтом из материалов?

**Comment by kokokobold** [comment]
Из каких материалов? У нас система крафта не развита толком, а кастет — просто металлическое оружие.

**Comment by MrMagick2104** [comment]
Да из любых. Как биты делаются. Емнип, код кастетов это уже позволяет.

**Comment by ArmolitskiyCarpoeb** [comment]
всем похуй? геймдизы так и не проверили иссуй, хотя кастеты в билде уже давно лежат

**Comment by ArmolitskiyCarpoeb** [comment]
запрашиваю поддержку геймдизайнеров!!!

**Comment by TobyThorne** [comment]
Сначала надо привести кастеты в нормальное состояние, сейчас они действуют несколько сомнительным образом.
