### ISSUE TITLE
Баланс арсенала

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#282]
Убрать булпапы и комбат сьюты из арсенала.Заменить все бронежилеты на плэйткэрриеры

**Comment by Cinericius** [comment]
Которые комбат сьюты? И чем плохи буллпапы?

**Comment by bob467** [comment]
Гранаты уже есть в арсенале.

**Comment by bob467** [comment]
Нахуя емп патроны если есть ионные пушки?

**Comment by Demisov** [comment]
Я про емп вариант

**Comment by Ruforce** [comment]
>емп патроны

простите что?

**Comment by bob467** [comment]
https://www.youtube.com/watch?v=6ykB3cBtQ0M
