### ISSUE TITLE
Убрать дилей на хоткей блока

### ISSUE THREAD

**Issue by SukaYaEbalPridumivatImya** [ChaoticOnyx/OnyxBay#2821]
Хоткей блока работает через раз.
В бою ещё хуже.
Почему.

OS: Окна седьмые.
Client Version: 513
Server Revision: 9b2cd49f8bcba9222484d6b9d0aa49515116e91c - release/lawful - 2020-06-20
Game ID: b7P-bqjg
Current map: NSS Exodus

**Comment by Animesku** [comment]
ну там делей просто

**Comment by SukaYaEbalPridumivatImya** [comment]
> ну там делей просто

Зачем.

**Comment by Animesku** [comment]
@TobyThorne нахуя делей на блок??

**Comment by TobyThorne** [comment]
@Animesku так надо.

**Comment by SukaYaEbalPridumivatImya** [comment]
> @Animesku так надо.

Пришлось делать костыль. Поставил макрос на блок на ту же кнопку. Работает гораздо лучше.

**Comment by MrMagick2104** [comment]
> Пришлось делать костыль. Поставил макрос на блок на ту же кнопку. Работает гораздо лучше.

> так надо.


Ставить делей на хоткей.

**Comment by kokokobold** [comment]
Так это не баг тогда!

**Comment by PlinHost** [comment]
> Пришлось делать костыль. Поставил макрос на блок на ту же кнопку. Работает гораздо лучше.

Хоткей это литералли макрос на блок, странно что он иначе работает.

**Comment by vsss412** [comment]
Кусок с "макросом быстрее" проверим, лол.
