### ISSUE TITLE
Стиралки выплёвывает вещи только после второго открытия

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#283]

**Comment by denver1000** [comment]
К слову, если засунуть мелок, затем открыть/закрыть, он выпадает , а вот засунуть его снова уже нельзя

**Comment by ArmoredBaka** [comment]
Разве? Я его туда сувал без проблем по нескольку раз. Он, право, не красил нихрена (такую фичу просрали, ря), но совался без проблем.

**Comment by denver1000** [comment]
М. Если в ПУСТУЮ стиралку засунуть мелок, открыть/закрыть, то в ПУСТУЮ стиралку нельзя снова засунуть мелок. В стиралку с уже помещенной внутрь вещью всё ещё можно

**Comment by ArmoredBaka** [comment]
А какой смысл ТОЛЬКО мелок совать в стиралку? Баг багом, но приоритет у него ниже низкого. Лучше уж более важные вещи пофиксить, аля (не)дамаг Резака по камням. Он за три выстрела разрушает тайл камня, а должен (чисто судя по инфе с вики) за выстрел три тайла сносить. И это при стоимости 4к+ поинтов, ну бред же. Сделать хотя бы пробиваемость выстрел = тайл и нормас + возможность снаряжать его рудой этой розовой (ща бы название забыть) с меньшей эффективность, нежели иным способом.
