### ISSUE TITLE
Боль должна быть более убедительной для игрока.

### ISSUE THREAD

**Issue by SukaYaEbalPridumivatImya** [ChaoticOnyx/OnyxBay#2832]
Сейчас у нас боль почти не чувствуется в плане отыгрыша, потому что человек не проникается ей. Для игрока это просто красный экран и замедленный персонаж.

Можно добавить новых эффектов для большей иммерсивности.

Например:
- Гул в ушах при сильной боли или от ударов тупыми предметами по голове. (Можно добавить временное ухудшение слуха).
- Тряска экрана при ударах по голове. (Можно добавить непродолжительно покачивание сразу после удара)
- Если человек в крите, то можно добавить всё вместе ещё и с ухудшением слуха. Ну, типа, человек лежит полумёртвый уже, глаза кровью залиты, в голове каша, но слух у него до сих пор в полном порядке. Не норма же.

Это вот самый минимум, который я придумал. Но, думаю, можно ещё чего такого впилить по теме.

**Comment by Kexilex** [comment]
Можно включать серый фильтр и рябь при сильной боли и обильном кровотечении.

**Comment by MrMagick2104** [comment]
> Гул в ушах при сильной боли или от ударов тупыми предметами по голове. (Можно добавить временное ухудшение слуха).

Хорошо бы в префы отключаемость звуковых эффектов, если таковые будут, а то будет страдать игрок из-за прекрасной балансировки звука у наших аудиофайлов.

> Тряска экрана при ударах по голове. (Можно добавить непродолжительно покачивание сразу после удара)

А тряска подразумевается короткой, но интенсивной, либо долговременной, но умеренной?
Я бы предложил сделать тряску от адреналина в крови (и добавить ему каких-нибудь баффов наконец, он же совсем бесполезный у нас), как при опьянении. Типа эффекта трясущихся рук.

> Если человек в крите, то можно добавить всё вместе ещё и с ухудшением слуха. Ну, типа, человек лежит полумёртвый уже, глаза кровью залиты, в голове каша, но слух у него до сих пор в полном порядке. Не норма же.

В крите слышно только всякие звуки, вроде стрельбы и прочего, а речь ту же не слышно.
Кроме того, человек продолжает воспринимать звуки, но не может их осознавать, даже если он находится без сознания.
Т.е. он может _услышать_ громкий стук, выстрел, etc. вообще без проблем, как и речь, но вот осознать он её не сможет.
Это, как бы, норма.
А по поводу других эффектов, вроде тряски и прочего, то в крите тупо чёрный экран. Зачем это нужно?
> Можно включать серый фильтр и рябь при сильной боли, и/или обильном кровотечении. Также это может распространяться на переломы. Если берешь что-то сломанной рукой или ходишь с переломом ноги, таза или грудной клетки.

Серый фильтр при боли - такое себе. При кровопотере - нормально (меньше крови в глазах - хуже работают, нормальная логика, что.), но от боли у человека не пропадает цветовая дифференциация. Можно было бы чутка контрастность вместо этого повышать, имхо.
Вместо серого фильтра, либо вместе с ним, можно было бы снижать обзор, как при трейте слепоты.
>  рябь при сильной боли

Не надо, пожалуйста, щадите глаза игроков.
Итак уже какой-то мегагеймдизайнер придумал сделать мезонные и термальные оверлеи такого цвета, что у тебя от них дальтонизм разовьётся через некоторые время, так ещё и рябь добавлять.

> Также это может распространяться на переломы.

Может, но почему должно? Будет диким костылём, т.к. переломы уже накидывают пейндамаг и не дают тебе брать предметы в руки и нормально ходить, если у тебя проблемы.

> Сейчас у нас боль почти не чувствуется в плане отыгрыша, потому что человек не проникается ей. Для игрока это просто красный экран и замедленный персонаж.

Имхо, в плане отыгрыша боль слабая, потому что, зачастую, когда тебе больно, тебе не до отыгрыша, потому что персонаж просто помрёт, если сильно отвлекаться на это.
Вот в меде и при допросах отыгрывать ничего не мешает, тут уже проблема в игроках в основном, я считаю.
Можно было бы чисто технически добавить всяких эмоутов, которые персонаж делает сам без помощи игрока от боли:
-Тех же криков, при крайне высоком уровне боли
-"Персонажнейм прикусывает губу и морщится" (видно в радиусе нескольких тайлов)
-"Персонажнейм стискивает зубы"  (тоже только нескольких тайлов)
-etc.
Кроме того, можно было бы добавить кастомизируемые "реакции" персонажей на боль, которые игрок мог бы настроить для персонажа самостоятельно:
-Крики, стоны, шипения, етц.
-Слова, которые персонаж пытается сказать без необходимости ввода игрока, если ему больно.
-Эмоуты.
-Возможно, переключаемая потеря сознания и, соответственно, эффекты выше при уровне боли ниже, чем нужно для обычного персонажа (можно в трейты закинуть, как пониженный болевой порог).

Альтернативное решение проблемы того, что тяжело отвлечься на боль во время ситуаций, когда нужно спасать персонажа от неизбежной смерти, если писать много в чатик:
-сделать СС пошаговой :trollface:.
