### ISSUE TITLE
Подкрутить спрайт ионному пистолету

### ISSUE THREAD

**Issue by Demisov** [ChaoticOnyx/OnyxBay#284]

**Comment by Cinericius** [comment]
А чо не так со спрайтом ионного пистолета?

**Comment by Demisov** [comment]
Он отображается как ионка

**Comment by Cinericius** [comment]
Хотя это не самое смешное

**Comment by Penguineapig** [comment]
До сих пор разве есть проблема эта?

**Comment by Cinericius** [comment]
Нету, вчера с ионником норм бегал. Возможно, проблема проявляется ИНОГДА, но тогда надо ловить контенкст.
