### ISSUE TITLE
Возможность резать вены

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#2850]
### Улучшение
Добавить возможность порезать себе (кому-нибудь другому) вены с помощью ножа.

### Решение
При выставлении куклы на левую/правую кисть и при нажатии себя  ножом на хелпе, будет появляться менюшка: 
You shure want to cut your veins?
Yes.                                  No.

При нажатии Yes, в течении 15-30 секунд ожидания, персонаж получит открытую артериалочку.

### Зачем это нужно? 
А нахера вы добавили тупую петлю, на которой надо 30 лет умирать? Это тоже разновидность тупой петли, но уже в брызгами крови.
И вообще это тоже интересная механика.

**Comment by MrMagick2104** [comment]
> левую/правую кисть

Вены на кисти? Запястье же относится к руке в целом, а не к ним?
> себе (кому-нибудь другому) вены

Бесполезно, т.к. уже можно срезать оппонентам сонную артерию острыми предметами.
Только если маскировать убийство под самоубийство?

**Comment by ArmenianOnyx** [comment]
> > левую/правую кисть
> 
> Вены на кисти? Запястье же относится к руке в целом, а не к ним?
> 
> > себе (кому-нибудь другому) вены
> 
> Бесполезно, т.к. уже можно срезать оппонентам сонную артерию острыми предметами.
> Только если маскировать убийство под самоубийство?

Не очень удобно случайно себя ножиком тыкнуть и постоянно эту менюшку получать. Если и хочешь себя порезать, то пусть это будет через такую удобную схему через руки.

**Comment by CokeUser** [comment]
> > левую/правую кисть
> 
> Вены на кисти? Запястье же относится к руке в целом, а не к ним?
> 
> > себе (кому-нибудь другому) вены
> 
> Бесполезно, т.к. уже можно срезать оппонентам сонную артерию острыми предметами.
> Только если маскировать убийство под самоубийство?

Можно сделать по аналогии с разрезом горла. Берешь в синий граб и ножом на харма тыкаешь, выбрав заранее руку, которую хочешь "вскрыть"

**Comment by MrMagick2104** [comment]
> Не очень удобно случайно себя ножиком тыкнуть и постоянно эту менюшку получать. Если и хочешь себя порезать, то пусть это будет через такую удобную схему через руки.

Это если у тебя уже прицел на руки выставлен. А если на кисти? Такая же штука. Плюс, можно сделать ограничение по режиму атаки.
> Можно сделать по аналогии с разрезом горла. Берешь в синий граб и ножом на харме тыкаешь, выбрав заранее руку, которую хочешь "вскрыть"

Ну да.

**Comment by Kexilex** [comment]
Так вены или артерии режем? С вен брызгать не должно, а космонавтик, который тычет в руку в поисках артерии, - это ржака.

**Comment by MrMagick2104** [comment]
> Так вены или артерии режем? С вен брызгать не должно, а космонавтик, который тычет в руку в поисках артерии, - это ржака.

У нас вены брызжут, неясно почему.

**Comment by Seldorne** [comment]
По-нормальному это делается через любой острый предмет в руках и suicide, а что именно при этом разрезается - руки или горло - не так важно. Не обязательно это даже делать мгновенной смертью, т.к. на вашем билде suicide отключён, вроде, чтобы именно мгновенно себя не убивали.

**Comment by MrMagick2104** [comment]
> По-нормальному это делается через любой острый предмет в руках и suicide, а что именно при этом разрезается - руки или горло - не так важно.

Зачем вёрб для этого, если есть харм на себя?
Вообще, лучший способ суицида - ампутация трёх конечностей самому себе при помощи тактического ножа и складного стульчика.

**Comment by Seldorne** [comment]
> Зачем вёрб для этого, если есть харм на себя?
Прокликивания себя и других одинаковыми объектами с одинаковым прицелом по кукле должны выдавать одинаковый результат. Ты не можешь с удара вскрыть руку или горло другому. Вёрб с одной стороны даёт защиту от дурака или случайных кликов, с другой стороны ускоряет процесс, избавляя от лишних движений, вроде грабов себя, которые в принципе невозможны.

**Comment by NefrNerf** [comment]
Нож в одну руку, целишься на кисть другой руки на хэлпе, вена режется
Только на себя, кому-то другому такое делать - слишком жирно
