### ISSUE TITLE
Генки на VR Human

### ISSUE THREAD

**Issue by BooJ1K** [ChaoticOnyx/OnyxBay#2867]
### Описание бага

Безспрайтовые генки с резистом на боль.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Заходим за генку в гейпод.
2. Погибает в геймподе.
3. Выходим из геймода.
4. Трансформ> имя ВР ХУМАНА.

### Ожидаемое поведение
Если вы сделали всё правильно, то вы стали ВР хуманом без спрайта и невосприимчивостью к боли.

**Comment by PlinHost** [comment]
Решается #2173.

**Comment by BooJ1K** [comment]
ВР делитнули, закрываю.
