### ISSUE TITLE
генки

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#287]
1) Проебали в навыке быстрого пассивного регена снятие флажков типа "сломано", "пробита артерия" etc, из за чего оное теперь это не лечит, но очень пытается.
2) Хедкраб вываливается из органа. Т.е. теперь такая схема: Человек -> орган -> хедкраб. Сложна.
3) У хедкраба чутка маловато хп, по моему.
4) По какой то непонятной причине, фейковый армблейд больно бьет.

**Comment by ZerlGray** [comment]
5. При использовании devided очки ДНК уходят в отрицательную сторону. При этом стоит сократить количество требуемых днк - ибо общее их число стало меньше, и мартышек жрать нельзя. в итоге сложна.
6. Хедкрабы имеют кд на стан меньшее, чем время внедрения в тело.

**Comment by Cinericius** [comment]
Чот пофикшено, чот не пофикшено, надо думац

**Comment by Cinericius** [comment]
Закрою, если что-то из этого актуально - надо отдельные иссуи.
