### ISSUE TITLE
Есть ступня, нет ноги

### ISSUE THREAD

**Issue by denver1000** [ChaoticOnyx/OnyxBay#289]
У человека есть ступня, но нету ноги. Её оторвало лазером

**Скриншоты**
https://prnt.sc/l9mbrg

**Характеристики**
Client Version: 512
Server Revision: 0594ca2839b451888322ac4d7006cacac633091e - dev - 2018-10-18
Game ID: bWY-c2Mu
Current map: NSS Exodus

**Comment by Ruforce** [comment]
сука хуле ты на закрылся выблядок
