### ISSUE TITLE
Возможность брать деньги в лоадауте

### ISSUE THREAD

**Issue by SukaYaEbalPridumivatImya** [ChaoticOnyx/OnyxBay#2909]
Ну, деньги, ебать, чего объяснять особо.

Стоимость и количество на усмотрение кодеров.

Всё равно лишняя копейка не повредит.

**Comment by kokokobold** [comment]
Хорошая идея. Только стоимость и количество заставляет сильно задуматься. За 5 очков 500 талеров, например?

**Comment by SukaYaEbalPridumivatImya** [comment]
> Хорошая идея. Только стоимость и количество заставляет сильно задуматься. За 5 очков 500 талеров, например?

Балан на усмотрение геймдизов. Хотя лучше бы и за меньшее количество чего-нибудь придумать, потому что часто остаётся не так много свободных очков.

**Comment by kokokobold** [comment]
Ну просто не надо себе хлам брать в лодауте.
