### ISSUE TITLE
стриминг соунда прямо ингейм

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#2917]
### Улучшение
ну я тут в хехму играл недавно и заметил что там есть ссылочка на бота типо одного а там стриминговый сервис бадасс музыки и я теперь её слушаю всем рекомендую кстати http://music.tspigot.net:8000/moo

### Решение
вариации различны но основной посыл прост
сначала запилить механ воспроизводства стрим соунда ингейм, потом
1. замутить новый итем под названием радио с возможностью перехвата музыки
сам же соунд по лору будет просто летать в космосе как радиоволны, ну вы знаете
2. сейм щит но внедрить прямо в жукбокс

### (Опционально) Дополнительная информация
наверняка это можно где-то спиздить, но я не в курсе

**Comment by MrMagick2104** [comment]
> замутить новый итем под названием радио с возможностью перехвата музыки
сам же соунд по лору будет просто летать в космосе как радиоволны, ну вы знаете

Можно ещё замаскировать триторское радио под такое радио.
Вопрос. А нельзя ли будет абузить такое радио, погружая клиент подходящих к нему людей в лаги?
Кроме этого, фича крайне хорошая, имхо.
Можно и "радиостанции" разные делать, с соответствующей музыкой.

**Comment by MemoryDreams** [comment]
> Вопрос. А нельзя ли будет абузить такое радио, погружая клиент подходящих к нему людей в лаги?

А с жукбоксом так нельзя уже сейчас?

**Comment by MemoryDreams** [comment]
Я думаю, что из-за этого билд сильно лагать будет.

**Comment by anihillator** [comment]
Радио в жукбоксе перебор, это вроде как исключительно проигрыватель.

**Comment by MrMagick2104** [comment]
> А с жукбоксом так нельзя уже сейчас?

Только с бумбоксом (с жукбоксом сложнее, так как замедляет при таскании, а также надо крутить и песню выбирать), а это донатная фича, так что всё нормально.

**Comment by MrMagick2104** [comment]
Надо радио тоже за донат сделать.

**Comment by MemoryDreams** [comment]
Может, с бумбоксом и радио сделать так, чтобы музыка у всех сразу скачивалась?
Вообще, было бы идеалом сделать фоновое скачивание музыки, чтобы сервер не останавливал все другие процессы во время скачивания файлов. Это возможно сделать на бьенде?

**Comment by MrMagick2104** [comment]
> Может, с бумбоксом и радио сделать так, чтобы музыка у всех сразу скачивалась?
Вообще, было бы идеалом сделать фоновое скачивание музыки, чтобы сервер не останавливал все другие процессы во время скачивания файлов. Это возможно сделать на бьенде?

У бьонда, вроде как, должен быть стриминг, который загружает музыку постепенно, из-за чего пролага не должно быть. Только он не работает.
А если подгружать _всю_ музыку по заходу на сервер - загружаться будешь десять лет, такое себе решение. Да и плюс в бумбоксах же кастомная музыка.
