### ISSUE TITLE
Для тонкотрапов (и пацанов) нету масок и оверлеев

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#2936]
Да-да, не удивляйтесь. Раны что на толстых, что на тонких, одни и те же, то есть у тонкого они просто заходят за границы спрайта. Надо добавить отдельный файл для них.

**Comment by MACTEP-ABATAP** [comment]
Ещё там спрайт протеза руки выглядывает из за одежды и это выглядит, так будто на руке гребень

**Comment by Animesku** [comment]
@MACTEP-ABATAP Ну так протез-то легко поправить. Ты напиши иссуй что за протез хоть.

**Comment by O0oMaximo0O** [comment]
Кажется раны исправляли, но не уверен.

**Comment by hard-res3t** [comment]
Исправлены. Вроде. Эпикус вроде делал.
