### ISSUE TITLE
Freeze and Vanish генкооргана вызывает застревание в вентиляции.

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#2944]
Если за краба залезть в вентиляцию и прожать Freeze and vanish - вы застрянете на ебанное навсегда.
![image](https://user-images.githubusercontent.com/62835631/87920891-84281500-ca82-11ea-9335-322c5c5507f8.png)

**Comment by bosslobster** [comment]
Это наказание за слабость духа.

**Comment by Shabat-Sholom** [comment]
Решил протестить баг. Freeze and Vanish вообще не работает.

**Comment by Shabat-Sholom** [comment]
Ага. Не работает, если спавнишь хедкраба. Отделился от человека и прожал способку в вентиляции. Баг подтверждён.

**Comment by TobyThorne** [comment]
В какой-то момент починилось. Наверное, во время реворка передвижения.
