### ISSUE TITLE
Новый способ застрять в вентиляции, а также попасть в нуллспейс

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#2945]
Если в тот момент, когда вентиляцию ТОЛЬКО НАЧНУТ заваривать, краб начнет ползти в ЗАВАРИВАЮЩУЮСЯ вентиляцию - он к хуям нахуй застрянет на бесконечное навсегда.
Еще раз повторю - сварочкой варят вентиляцию - крабик в этот момент только начинает ползти - аирлок заварился - крабик залезает в заваренный вентиль и застревает к хуям.

Если попытаться разобрал вентиляцию с крабиком - тебя к хуям выкинут в nullspace, не ебу что это.

**Comment by Doster-d** [comment]
Тебя телепортирует по нулевым координатам, проблема может быть актуальна и для бибизян, которые лезут в вентиляцию, вероятно решение будет просто добавить проверку.

**Comment by Epicus7** [comment]
Скорее всего это касается не только краба чейнжлинга, но и любых других мобов, которые лазают по вентиляции.

**Comment by Epicus7** [comment]
Награда выдана partingglass
