### ISSUE TITLE
Beehive ничего не производит

### ISSUE THREAD

**Issue by Ra30R3** [ChaoticOnyx/OnyxBay#295]
**Описание бага**
Пчёлы из Beehive не вырабатывают ничего, за почти 2 часа времени.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Ставим Beehive у ботаниста по всей инструкции
2. Ждём
3. ???
4. Profit (Ничего не получится)

**Ожидаемое поведение**
Должен был производиться воск и мёд.

**Скриншоты**
https://i.imgur.com/zeL2oMV.png

**Характеристики**
 - OS: [Windows 7] 
 - Версия клиента [511/1385]
 - Версия сервера Client Version: 511 Server Revision: 4c3b772d335fcd9ac7173e84375afd46fefb3b66 - dev - 2018-11-01
 - ID игры Game ID: bW0-bIKJ

**Дополнительня информация**
На SS13 вики - гайд по другой сборке, не по бэй 12, использовался этот гайд с бэй 12 - https://wiki.baystation12.net/Guide_to_Hydroponics#Apiculture

**Comment by denver1000** [comment]
Там походу теперь нужно юзать отдельную штуку под названием экстрактор мёда
https://github.com/ChaoticOnyx/OnyxBay/commit/e4727ab11676430a3a8b25bdd84a5f24959cdc8b

**Comment by Cinericius** [comment]
Вроде пчеловодство фиксили
