### ISSUE TITLE
Нечестный заработок на консоли торговцев

### ISSUE THREAD

**Issue by DrNuker** [ChaoticOnyx/OnyxBay#296]
**Описание бага**
С помощью торговой консоли мерчантов можно покупать товар у торговцев, и продавать этот же товар этим же торговцам, но уже в два раза дороже, и так до бесконечности, тем самым поднимая свой капитал.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Заходим за мерчанта
2. подходим к консоли
3. находим торговца фигурками или животными
4. покупаем фигурки, или животных.
5. Продаем торговцу этот же товар сразу же.
6. Получаем больше денег.

**Ожидаемое поведение**
Цена продажи должна быть ниже цены покупки, что бы не было возможности зарабатывать на подобных операциях. 

**Скриншоты**
------

**Характеристики**
 ------

**Дополнительня информация**
Добавьте больше товаров которые захотят купить торговцы в консоли. А то покупают только животных, органы и сигареты.

**Comment by Ruforce** [comment]
ну это классика, лол, невидимая рука рынка.

**Comment by Demisov** [comment]
Ну остаётся только денежной пушкой
