### ISSUE TITLE
Химикаты генокрада перестают вырабатываться

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#2965]
Внезапно химикаты калограда практически перестают вырабатываться. Все медленее и медленнее происходит выработка. Около минут пяти может занять то, что бы выработать себе хотя бы 10 химикатов.

Время 1:59
Server Revision: fd3626e654d990f2681792c25f3ec711832ac642 - release/chaotic - 2020-07-20

Game ID: b8h-b4FH

Current map: NSS Exodus

**Comment by Shabat-Sholom** [comment]
Знать бы ещё, как ты это сломал.

**Comment by ArmenianOnyx** [comment]
Да все знают уже как сломано.
Мемконтроль умирает, а вместе с ним и химикаты. @Shabat-Sholom

**Comment by TobyThorne** [comment]
Исправлено в #7084 
Реген поломается только если все контроллеры хрюкнут, но в таком случае химикаты будут меньшей из проблем
