### ISSUE TITLE
Дроппоучи/поучи не юзаются

### ISSUE THREAD

**Issue by BlakeCrazy** [ChaoticOnyx/OnyxBay#297]
**Описание бага**
Дроппоучи/поучи le fantom

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем дроппоучи/поучи(проверено почти на всех поучах и дроппоучах) в активную руку
2. Нажимаем E(кипировать)
3. опа
4. Видим ошибку - поучи канули в паралельный мир, не экипировавшись при этом на одежду, еще и спрайтих остался в активной руке.

**Ожидаемое поведение**
Поучи должны были экипироваться.

**Характеристики**
 - Шиндовс 7
 - 512.1441
 - Никому не известно...
 - Никому не гадано...

**Дополнительня информация**
В целом, баг не смертельный, лишь неприятный - поучи пропадают, оставляя лишь спрайт в руке. Хотя так быть не должно.

**Comment by Ruforce** [comment]
они рабочие, кстати

**Comment by BlakeCrazy** [comment]
> они рабочие, кстати

Разве? У меня ничего не совалось в одежду с псевдоприкрепленными поучами

**Comment by Ruforce** [comment]
они все еще работают как контейнер - их можно открывать, класть вещи и прочее

**Comment by BlakeCrazy** [comment]
> они все еще работают как контейнер - их можно открывать, класть вещи и прочее

а, сейчас проверил - да, они мало того, что исчезают - так еще и создают халявный контейнер в руке. 

Щас скрин прилеплю

**Comment by BlakeCrazy** [comment]
![bug_go_fuck](https://user-images.githubusercontent.com/44750896/47967448-38b0b600-e0a9-11e8-9a54-ef4f4ba75fae.png)

**Comment by denver1000** [comment]
https://github.com/Baystation12/Baystation12/issues/19970
На это бей забил почти год как. huh!
