### ISSUE TITLE
Нельзя слезть с каргопаравозика если у тебя нет ног

### ISSUE THREAD

**Issue by BlakeCrazy** [ChaoticOnyx/OnyxBay#298]
**Описание бага**
Вечный водила.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. У нас НЕ должно быть ног. Это крайне важно.
2. Берем паровозик из карго, садимся на него, запускаем движок.
3. Поздравляю, теперь Вы не можете ни покататься на паровозике, ни слезть с него, т.к. Вам постоянно выдает стан (James Crime collapses!)

**Ожидаемое поведение**
Ничего. Я должен был начать кататься на паровозе.

**Скриншоты**
Потеряны

**Характеристики**
 - Шиндовс
 - 512.1441
 - Никому не ведомо...
 - Никому не гадано...

**Дополнительная информация**
Меня пытался снять с паровоза борг, но у не получалось. Также, опробовал все методы, чтобы слезть - не помогло. После того, как мне заспавнили коляску на соседнем тайле, а борг разбил паровозик, и я пересел на кресло - вроде бы прошло.

**Comment by denver1000** [comment]
![issue 298](https://user-images.githubusercontent.com/33289670/50450068-7b21a100-093c-11e9-8421-3b97c2967f16.png)
На локалочке потестил, не подтвердилось
