### ISSUE TITLE
Проблемы с loadout - ом

### ISSUE THREAD

**Issue by BlakeCrazy** [ChaoticOnyx/OnyxBay#299]
**Описание бага**
Лоадаут заболел

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Открываем лоадаут
2. И уже в нем видим кучу проблем, багов и недоработок.
2.1 Аксессуары: 
-holster selection тратит 3 очка, а не 1. А еще -  имеет нерабочую штуку для выбора варианта И че оно ваще тут делает, это же такт. экип.
-wallet не выбирается
Части одежды:
-hawaii shirt выбирается также и в Аксессуарах. Баг или фича?
-waistcoat выбирается также и в Аксессуарах. Баг или фича?
Косметика:
-Че-то как-то грустно, добавьте помаду там, пудру, прочее дерьмо для СвЕтСкИх ДаМ
На уши:
-Все хорошо
Основное(Генерал?):
-Все хорошо
Очки:
-glasses имеет своего двойника в этом же разделе.
Перчатки:
-Все хорошо
Шляпы:
-beret, red не выбирается
Обувь:
-Все хорошо
Аксессуары-хранители:
-Все хорошо
Костюму и верхняя одежда:
-overalls не выбирается
Такт. экипировка:
-holster selection, именно - machete sneath. Смысл от них, если самого мачете не найти, а что-то другое в ножны не лезет
Униформа:
-suit selection не выбирается
-generic jumpskirts не выбирается
-tactocool turtleneck выбирается и в Такт. экипировке
-casual pants selection, не уверен, что ВСЕ - но black jeans имеет битую текстуру
Утилиты:
-Все хорошо
Ксеноодежда:
-colored headtail chain(Skrell) не выбирается
-colored headtail band(Skrell) не выбирается
-male colored headtail cloth(Skrell) не выбирается
-female colored headtail cloth(Skrell) не выбирается
-Zhan headscarf не выбирается

**Ожидаемое поведение**
Лоадаут не болей

**Скриншоты**
Зачем

**Характеристики**
 - Шиндовс 7
 - 512.1441
 - Никому не ведомо...
 - Никем не гадано...

**Дополнительня информация**
Как насчет добавления в лоадаут мачете, косметики, прочегих псевдополезных штук?

**Comment by kreeperHLC** [comment]
#300
