### ISSUE TITLE
Поломка крематория

### ISSUE THREAD

**Issue by Baneuus** [ChaoticOnyx/OnyxBay#3028]
Если перед крематорием будет стоять что-то тяжёлое(ящик-человек-любое-другое), то тот откроется, выдвижная часть сожрётся этим несдвигаемым предметом, а сам крематорий будет утерян, поскольку зависнет.
![image](https://user-images.githubusercontent.com/66535081/89022668-105ff500-d32b-11ea-833f-c6ecd044139a.png)

**Comment by Epicus7** [comment]
Исправлено в #3569.
