### ISSUE TITLE
ревёрт ревёрта джукбокса

### ISSUE THREAD

**Issue by LLIkolnik** [ChaoticOnyx/OnyxBay#307]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
аааааааааааа

**Опишите ваше решение проблемы**
ревёрт ревёрта джукбокса нужен

**Опишите альтернативы, о которых вы думали**
нету

**Дополнительная информация**
плин лох

**Comment by PlinHost** [comment]
Сам лох.
