### ISSUE TITLE
Куртка

### ISSUE THREAD

**Issue by Weapos** [ChaoticOnyx/OnyxBay#308]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
В лоадауте есть только коричневая кожаная куртка, но нет чёрной кожаной куртки.
**Опишите ваше решение проблемы**
Добавить выбор цвета куртки.
**Опишите альтернативы, о которых вы думали**
Я не умею думать.
**Дополнительная информация**
В билде чёрная куртка есть, а в лоадауте её выбрать нельзя.

**Comment by Penguineapig** [comment]
Плес скинь точные названия
Инглиш

**Comment by TobyThorne** [comment]
> Плес скинь точные названия
> Инглиш

Пингвин, не пинай трупы.
commented on 19 Nov 2018

**Comment by Penguineapig** [comment]
Не всё то труп шо старое

**Comment by Cinericius** [comment]
Сделано, говорят
