### ISSUE TITLE
Бумажные легкие

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#3096]
Какая то шваль точно что то меняла в циферах органов. Легкие теперь рвутся как раньше, от пары секунд в разгерме или при пожаре они чуть ли не мгновенно отказывают и в труху. Что это за ржака?

**Comment by TapKo4eB** [comment]
опять сложная математика

**Comment by lKameRUNl** [comment]
> Какая то шваль точно что то меняла в циферах органов. Легкие теперь рвутся как раньше, от пары секунд в разгерме или при пожаре они чуть ли не мгновенно отказывают и в труху. Что это за ржака?

Это насколько долгие должны быть пять секунд, чтобы лёгкие так дико сгорали? Да и как по мне реалистично.

**Comment by MrMagick2104** [comment]
> Это насколько долгие должны быть пять секунд, чтобы лёгкие так дико сгорали? Да и как по мне реалистично.

То, что лёгкие сгорают/рвутся от пожара - нормально, с точки зрения реализма. А вот разрыв вакуумом - прикол. Так-то, вакуум в принципе лёгкие рвать не должен, в худшем случае пролапс случится, да и всё.

**Comment by lKameRUNl** [comment]
> > Это насколько долгие должны быть пять секунд, чтобы лёгкие так дико сгорали? Да и как по мне реалистично.
> 
> То, что лёгкие сгорают/рвутся от пожара - нормально, с точки зрения реализма. А вот разрыв вакуумом - прикол. Так-то, вакуум в принципе лёгкие рвать не должен, в худшем случае **_пролапс_** случится, да и всё.

 Ржу нахуй, пролапс лёгких. Так вот, лёгкие пористая структура, и из за вакуума он теряют свои свойства. Внутреннее кровотечение обеспечено как минимум. А при пожаре они повреждаются в силу такого прекрасного физического явления как температура и повышения давления из за расширения газов от нагрева.

**Comment by MrMagick2104** [comment]
> Так вот, лёгкие пористая структура, и из за вакуума он теряют свои свойства. Внутреннее кровотечение обеспечено как минимум.

Понимаю. А в каком источнике про это можно почитать?

**Comment by lKameRUNl** [comment]
> > Так вот, лёгкие пористая структура, и из за вакуума он теряют свои свойства. Внутреннее кровотечение обеспечено как минимум.
> 
> Понимаю. А в каком источнике про это можно почитать?

https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D0%BE%D1%82%D1%80%D0%B0%D0%B2%D0%BC%D0%B0#%D0%91%D0%B0%D1%80%D0%BE%D1%82%D1%80%D0%B0%D0%B2%D0%BC%D0%B0_%D0%BB%D1%91%D0%B3%D0%BA%D0%BE%D0%B3%D0%BE

**Comment by MrMagick2104** [comment]
> [Длинная ссылка](https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D0%BE%D1%82%D1%80%D0%B0%D0%B2%D0%BC%D0%B0#%D0%91%D0%B0%D1%80%D0%BE%D1%82%D1%80%D0%B0%D0%B2%D0%BC%D0%B0_%D0%BB%D1%91%D0%B3%D0%BA%D0%BE%D0%B3%D0%BE)

Баротравма, которую можно получить по ссылке, должна получаться от использовании маски с высоким давлением в принципе, что не совсем то (но как раз от чего в теории должны защищать скафандры). При выходе в космос ты же просто не сможешь дыхание задержать, скорее всего, потому весь воздух быстренько выйдет, из-за чего такого повреждения от разницы давления быть не должно.

С этим вопросом пришлось выйти в интернет. Мне удалось обнаружить, что интересующий нас феномен - [взрывная декомпрессия](https://ru.wikipedia.org/wiki/Неконтролируемая_декомпрессия#Взрывная_декомпрессия).  Именно она приводит к травме лёгких ввиду понижения давления более быстрого, чем воздух выходит из лёгких.
Как можно прочитать из статьи, баротравмы настолько опасны, насколько они опасны у нас, при декомпрессии с большой разницей давления. В СС же, в большинстве случаев, декомпрессия происходит при разнице давления всего в одну атмосферу, что не очень много, а к смертельным травмам приводить не должно. Более того, сам по себе вакуум не опасен (судя, опять же, по материалам из статьи) для лёгких, важна только сама декомпрессия. Т.е. если ты вышел в космос через шлюз, с медленной откачкой кислорода, ты не должен умереть от лёгочной травмы, а только от кислородного голодания.
Соответственно, люди находящиеся не прям рядом с местом, куда уходит атмосфера, также не должны получать значительных травм.

**Comment by koronoshka** [comment]
Во многом эффекты взрывной декомпрессии можно нейтрализовать предварительно выдохнув весь воздух из легких, так разницы между атмосферным давлением космоса и легких будет минимальным, разве-что за исключением некоторых запасов кислорода которое тело оставляет в легких инстинктивно. 
Это все конечно круто но я не могу придумать не костыльного способа привязывания этой информации к игровой механике.

**Comment by Shabat-Sholom** [comment]
В разгерме лёгкие не бумажные, нам наврали. Бегал до потери сознания несколько раз. Итог - без урона и минор. Пожар же и должен дамажить сильно, ожог лёгких наступает моментально с попаданием в них перегретого воздуха.
