### ISSUE TITLE
Переработка окон. Подоконники, и виды окон.

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#3118]
### Улучшение
На текущий момент, окнами являются просто односторонние стеночки, вылепленные по всем сторонам и с запихнутой внутрь решёткой.

Помимо того что они ломаются от любого чиха и устраивают разгермы, они абсолютно не релеванты для защиты важных отсеков, ибо откручиваются за пол секунды ломом и отвёрткой, имеют реально малое количество здоровья, а решётки внутри можно разбить даже без перчаток любым предметом что не проводит ток. (e.g. осколок стекла от этого же окна)

Помимо того что они станут логичнее (ибо однотайловые), они дадут возможность для вариативности под разные нужны. Хулл окна для выходов в космос, реинфорсед с наэлектризованными решётками внутри для защиты важных отсеков, обычные между цивильными отсеками.

В добавок, подоконники не дадут просто взять и пройти через разбитое окно, ибо помимо всего их придётся перелазить или разбирать.

Проблему перспективы можно вполне решить перепилом спрайтов под тот же top-down стиль что и стены на текущий момент.

### Решение
Реализация представляется в виде портирования и обтачивания окон и подоконников с того же бея. Проблему перспективы можно вполне решить перепилом спрайтов под тот же top-down стиль что и стены на текущий момент.

![glass](https://user-images.githubusercontent.com/48761132/89733441-29208700-da5e-11ea-913a-04c4c28a45ec.png)

**Comment by MrMagick2104** [comment]
Так у нас же уже есть стенки из стекла укреплённые. Выглядят нормально, вроде, а также не имеют проблем односторонних стеночек из стекла.

**Comment by TapKo4eB** [comment]
не имеют подоконников, плюс иссуй включает в себя создании масок склеивания для окон рядом с друг другом

**Comment by MrMagick2104** [comment]
> не имеют подоконников

Окна с подоконниками объективно лучше окон без подоконников?
> плюс иссуй включает в себя создании масок склеивания для окон рядом с друг другом

Стенки из стекла уже склеиваются же? Или речь не об этом?

**Comment by TapKo4eB** [comment]
>Окна с подоконниками объективно лучше окон без подоконников?

да, одно препятствие лучше нуля препятствий

>Стенки из стекла уже склеиваются же? Или речь не об этом?

![hm](https://user-images.githubusercontent.com/48761132/89734047-3dff1980-da62-11ea-89de-375969f05a6c.png)
не, речь конечно о том же

**Comment by MrMagick2104** [comment]
Это не те стенки из стекла.
Я говорю о том, что можно поставить основу для обычной стены, крутануть отвёрткой, а затем добавить любого стекла. Получится прозрачная стена, которая:
а) Долго ломается
б) Очень долго разбирается
в) Если даже ты её сломал, тебе нужно ещё ломать либо гриддер, либо разбирать его
г) Они тоже уже склеиваются.
Эти-то ещё хуже, чем обычные.

**Comment by lKameRUNl** [comment]
Что насчёт укреплений для гриддера? Чтобы он не ломался от каждого пердежа в его сторону. Арматура как никак.

**Comment by MrMagick2104** [comment]
Имхо, стёкла для обшивки надо именно на базе стен делать.
> Что насчёт укреплений для гриддера? Чтобы он не ломался от каждого пердежа в его сторону. Арматура как никак.

Это не арматура, а решётка. В плане, она даже не сварена сама с собой. 
Из разряда забора-сетки.

**Comment by lKameRUNl** [comment]
> Имхо, стёкла для обшивки надо именно на базе стен делать.
> 
> > Что насчёт укреплений для гриддера? Чтобы он не ломался от каждого пердежа в его сторону. Арматура как никак.
> 
> Это не арматура, а решётка. В плане, она даже не сварена сама с собой. 
Так может сделать её свариваемую версию? Защита от космирования будет обеспечена.
> Из разряда забора-сетки.
Ну и нахуй тогда оно на станции надо в каждом окне?

**Comment by MrMagick2104** [comment]
> Так может сделать её свариваемую версию? Защита от космирования будет обеспечена.

На арматуру ток подать нельзя.
> Ну и нахуй тогда оно на станции надо в каждом окне?

Ток подавать.

Имхо, гриддеры внутри четырёх стёкол ставить - такое себе.
Я за такие стёкла, которые прекрасны. У них есть уровни баланса нормальные:
1) Обычная стена из стекла. Ломается за четыре удара огнетушителем, +-.
2) Укреплённая стена из стекла.
3) Обычная стена из укреплённого стекла. 7-8 ударов, тоже огнетушителем.
4) Укреплённая стена из укреплённого стекла. Около 14 ударов огнетушителем.

При этом, когда ты сломал стекло, под ним ещё и гриддер остаётся, который нужно разобрать. Правда, спрайты спефицичные. Выглядят, как стенки из какого-нибудь Призон Аркитекта, но их ведь можно перерисовать.
![элитное_steklo](https://user-images.githubusercontent.com/58848742/89737481-ee2c4c80-da79-11ea-99c0-aedba8af1581.PNG)

**Comment by lKameRUNl** [comment]
> Ток подавать.

Ты не понял... Абсолютно в **каждом окне**.

>  Выглядят, как стенки из какого-нибудь Призон Аркитекта, но их ведь можно перерисовать.

Тихо спиздил и ушёл, называется нашёл. Ждём импорт текстур с дргуих сборок, или я могу попробовать нарисовать тайлсет. В дискорд пишите.

**Comment by MrMagick2104** [comment]
> Ты не понял... Абсолютно в каждом окне.

Как минимум, без решётки окна крайне смешно выглядят. Ну и можно подавать ток на _каждое_ окно по желанию.

**Comment by PlinHost** [comment]
Вместо добавления подоконников можно использовать готовые гирдеры, да. Спрайты нужны в любом случае.

**Comment by TobyThorne** [comment]
Как все успели заметить, уже сделано. И всем безусловно понравилось.
