### ISSUE TITLE
Мизерный дамаг

### ISSUE THREAD

**Issue by Weapos** [ChaoticOnyx/OnyxBay#312]
**Описание бага**
Конструкторы бессильны против людей, любые.
**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Становимся конструктором
2. Пытаемся избить кого-то
3. Понимаем, что что-то не так

**Ожидаемое поведение**
Нормальный урон.
**Скриншоты**
![image](https://user-images.githubusercontent.com/23001598/48794821-1b682280-ed0c-11e8-990b-7ec0f19eb1e0.png)
**Характеристики**
 - OS: Windows
 - Версия клиента 512.1454
 - Версия сервера c62132010a6bd7861c0598fb138c1d2be35b4e35 - dev - 2018-11-20
 - ID игры bXq-cHje
**Дополнительня информация**
Фиксите,

**Comment by TobyThorne** [comment]
Проблема не только с констрактами, но вообще с любыми simple_animals, которыми управляют игроки. Если посадить игрока в карпа - тоже не будет наносить урон. Уже фикшу.

**Comment by Ruforce** [comment]
мой любимый трапуссинька куда-то проебался, пофиксил
