### ISSUE TITLE
Генки к генкам, хедкрабы к хедкрабам

### ISSUE THREAD

**Issue by TobyThorne** [ChaoticOnyx/OnyxBay#3122]
_Нашёл идею годовалой давности, про которую успешно забыл когда трупанулся. Чутка довёл до ума. Если будет аппрув - запилю на днях._

Собсна, разделить нынешнего генку на две разные рольки с разным геймплеем, ибо нынешний - какая-то мэрисьюшная солянка.

= Нынешнего генку переименовать в, скажем, паразита. Отпилить у него стелсовые фичи, но чутка баффнуть боевые. В итоге получим что-то между Нечто, хедкрабами из Халфы и Parasyte.
- Убрать уколы.
- Убрать поглощение генов.
- Убрать превращение.
- Убрать стазис и, опционально, абилки на ускоренный хил.
- По дефолту дать армблядь, генкомобов, невосприимчивость к боли, etc.
- Добавить способности типа подрыва тела (собственно, взрыв + вспышка вместо спавна генкомобов), хоррорформы, армщита, мясного скафандра, etc.
- Очки на прокачку получаются за успешное размножение.
- Вместо поглощения генов и синдикатоцелек, добавить цель в виде размножения (типа как у культистов, да).
- Размножение можно либо оставить по типу нынешней абилки (лёгкий способ), так и сделать более хардкорный вариант в виде заражения трупов со временем на инкубацию, во время чего труп своим видом неиллюзорно намекает, что с ним что-то не так, да ещё и может быть уничтожен, а если всё прошло гладко - гостота может в него вселиться и появиться новым паразитом.
- Паразит палится в медицинских сканнерах даже когда находится в груди.
+ Что имеем? Логичное развитие филькиных генок без оглядки на оригинальных. Больше направленный на активные PvP сражения режим, слегда отдающий алиумами. Более очевидные цели, больше командной работы.

= Генокрада сделать имеенно генокрадом. Таким, какой он был. Стелсовая ебака с жалом, притворяющаяся своими поглощёнными жертвами. 
- Вернуть и разнерфить уколы, включая парализ и дедстинг.
- Никаких генкоорганов. У него одно тело, проебал его - проиграл.
- При этом никак не палится медицинскими способами, лишь своими действиями.
- Без армблядей и прочих диких фокусов с телом. 
- И без размножения. 
+ Что имеем? Генку. Старого доброго генку. Каким он всегда был. Когда к тебе в дормах слишком близко подходит человек и у тебя начинает потеть жопа.

**Comment by TapKo4eB** [comment]
флексиш браток

**Comment by lKameRUNl** [comment]
Иихуя идея, ждём. Таким темпом и каскадный резонанс станет истиной.

**Comment by MrMagick2104** [comment]
> Убрать стазис и, опционально, абилки на ускоренный хил.

А зачем это убирать? Имхо, если стазис ещё можно понять, то ускоренная регенерация как раз обязательна такому пришельцу из космоса, потому что пришелец, которого можно убить одним выстрелом в сердце смешным рандомом, при том, убить насмерть - такая себе опасность.
> По дефолту дать армблядь, генкомобов, невосприимчивость к боли, etc.

Для дефолта жирновато будет. Имхо, лучше по дефолту дать минимальный набор абилок, как у наших генок сейчас, а также дать очки на развитие, чтобы человек мог свои стратегии использовать.
> Добавить способности типа подрыва тела (собственно, взрыв + вспышка вместо спавна генкомобов), хоррорформы, армщита, мясного скафандра, etc.

Недавно ещё Кэррион вышла, про это же игра, можно оттуда что-нибудь стащить.

**Comment by ghost** [comment]
>По дефолту дать армблядь, генкомобов, невосприимчивость к боли, etc.

Армблядь? Эта та, что голову с двух ударов сносит? А теперь мы боль уберем, получив машину для убийств с штукой, которая моментально убивает.

**Comment by NefrNerf** [comment]
Пока откладываем в ящик, дадим генокрадом отдохнуть после нескольких лет насилия над кодом
