### ISSUE TITLE
Дюпокрад

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#3129]
МАЛЬЧИКИ ДЕВОЧКИ, ГАЙД ПО ДЮПУ ВСЕМ СМОТРЕТЬ!

### Описание бага
Ебанный калокрад дюпает геномы.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Покупаем способность размножение гавнокрада Division
2. Ищем космонавтика или ссдшного апатика и заражаем его калокрадовской биоструктурой
3. Космонавтику накидывается ролька и стартовые 10 геномов
4. Абсорбируем свежего ссдшного мочакрада и забираем все его геномы, профит.

Об этой ебанной хуйне знает каждый, но чинить нахуй никто не собирается. У вас блядь вся ебанная способность Divison поломана и предназначена только для ебанного дюпа, ахуенно!

**Comment by Ruforce** [comment]
Багу года два уже, нашёл чем удивить.

**Comment by O0oMaximo0O** [comment]
Хм, ввести генокраду "родителя"? У сторителлерных/раундстартовых null, у задивизионных - собственно тот кто породил.
Если родитель высасывает своё дитя - даётся только 2 очка.
Хотя вчера проверил такое на заспауненных телах - просто вернуло 2 очка. Возможно это уже исправлено.

**Comment by Nod404** [comment]
пофикшено в недавнем апдейте
