### ISSUE TITLE
Нерф LOOC

### ISSUE THREAD

**Issue by PlinHost** [ChaoticOnyx/OnyxBay#3133]
Переименовать LOOC в Direct OOC. Указать в описании, что команда предназначается для крайних случаев, а не для комментариев или болтовни.
Добавить вербу выбор целевого персонажа в зоне видимости. Сообщение не должно быть видно ливинг мобам, кроме этого персонажа. Госты и педали будут видеть как раньше. К сообщению добавить кнопку ответа.
Отправка сообщения и ответа должна быть доступна только когда получатель в зоне видимости.

---

**_За закрытие этой задачи выставлена награда размером в 1000 рублей!_**

_Чтобы получить награду необходимо открыть пуллреквест с улучшениями описанными в задаче, который пройдет ревью двух разработчиков билда. После того как пуллреквест будет принят, а данная задача будет закрыта, пишите Epicus#1570 (Discord) для получения вознаграждения._

* _Если вы хотите заняться данной задачей, то вы можете её забронировать на какое-то время, но в случае отсутствия активности, бронь будет сниматься._
* _Обратите внимания на комментарии к задаче. Там могут быть пояснения и уточнения о том как её следует выполнять._

**Comment by lKameRUNl** [comment]
Нахер надо, если таким образом игроки смогут передавать абсолютно любую инфу, и никто их не "услышит". Да и для чего? Для помощи бедным новичкам? Или может это для антагов? Новички спросят в OOC или в Ahelp, а антаги могут юзать AOOC. А если хочется просто попиздеть, есть дискорд, в котором сидит большинство игроков.

**Comment by PlinHost** [comment]
Ну как никто, госты слышат и всё логируется.
Некоторые вещи нельзя спрашивать в ооц, так как это выдаст ингейм информацию. Ахелп, конечно, вариант, но педали не всегда доступны. А вот AOOC, кстати, надо выпилить.

**Comment by lKameRUNl** [comment]
> Ну как никто, госты слышат и всё логируется.
> Некоторые вещи нельзя спрашивать в ооц, так как это выдаст ингейм информацию. Ахелп, конечно, вариант, но педали не всегда доступны. А вот AOOC, кстати, надо выпилить.

Для вопросов ингей инфы, можно отойти в сторонку и в лоок писать, никто ничего тебе не скажет. Создаём себе же проблемы и сами их решаем? Нахуя, а главное зачем?

**Comment by PlinHost** [comment]
Нахуя писать в лоок более чем одному человеку?

**Comment by lKameRUNl** [comment]
> Нахуя писать в лоок более чем одному человеку?

Нахуя писать одному человеку?

**Comment by PlinHost** [comment]
Сказать ему, куда нажимать, например.

**Comment by lKameRUNl** [comment]
> Сказать ему, куда нажимать, например.

Супертайная кнопка, о которой не должен знать никто.... https://cs4.pikabu.ru/post_img/2015/02/09/0/1423430002_468474662.jpg
А если серьёзно, то что может быть секретного в нажатии блять кнопки? Окружающие не увидят действия что-ли? Не узнают об этой... Страшнейшей тайне?....

**Comment by PlinHost** [comment]
Это ты лучше ответь, почему все окружающие обязательно должны знать, какую кнопку кому-то рядом посоветовали нажать.

**Comment by lKameRUNl** [comment]
Чтобы как раз таки окружающие знали о тайном заговоре Навального, и в случае сговоров в ЛООК можно было пожаловаться на метагейство. Как ты сам сказал, педалей порой на серве нет, поэтому, Морфиус, твоя матрица хуйня. ЛООК больше для попизделок создан, причём в основном внеигровых. ПМ смогут видеть призраки? Ну и нахуй тогда он нужен, если вся тайна развеивается сама собой.

**Comment by Ruforce** [comment]
С каждым геймдизайнерским решением билд всё краше и краше. Как похорошел опухбей при текущей команде!

**Comment by PlinHost** [comment]
>ЛООК больше для попизделок создан, причём в основном внеигровых.

А я думал, что он сделан, чтобы не приходилось ((скобочки)) в сей писать когда очень надо. Раз для попизделок очень нужен, оставим как есть!

**Comment by MrMagick2104** [comment]
Вопрос.
Как должен ДООЦ работать по отношению к людям, которые находятся в мехах/шкафах/в сумках в виде ММИ/других контентсах?
Если закодить ровно по описанию в иссуе, то тогда не все ситуации смогут быть покрыты (по сравнению с текущей реализацией). 
Альтернативно, может быть, сделать дооц на турф? Отправляется всем, кто находится там, но не уведомляет отправителя, кому пришло это сообщение, если только ему не отвечают, чтобы избежать меты. Однако, это может вызвать проблемы, если хочешь написать кому-то, кто не стоит на месте.

<hr>

Кстати, может быть стоит не выпиливать ЛООЦ, а добавить возможность включать его педалям, как сейчас с АООЦ (который постоянно выключен, кстати), по умолчанию - отключено?

**Comment by Artemonim** [comment]
У нас есть DOOC as Discord OOC. Всё ещё хотим дублировать имя?
И я не думаю, что игрокам надо ставить преграду в виде списка имён (даже если там будут лишь имена в радиусе от игрока), которая будет отнимать время на поиск и выбор адресата. Ну а для суперсекретных вопросов тебе скорее понадобится написать AHelp, чем какому-то игроку.

**Comment by Epicus7** [comment]
Много нюансов, сложность высокая.

**Comment by Epicus7** [comment]
**За закрытие данной задачи выставлена награда размером в 1000 рублей!**

Подробности в ОП-посте.

**Comment by Tsurupeta** [comment]
Эм достер...

**Comment by Doster-d** [comment]
> Эм достер...

Что?

**Comment by Wuattt** [comment]
~~Как насчёт опции в контекстном меню для написания сообщения владельцу объекта?
Типа, пкм по ММИ, человеку или мыши, и там в менюшке под Examine выбрать Direct Message. А далее в чате сообщения как Ахелп, можно отвечать через ссылку в чате.~~
прочитал чуть внимательней - уже предлагали

**Comment by Waklaidan** [comment]
Попытаюсь закодить. Бронирую задачу

**Comment by Epicus7** [comment]
Награда выдана
