### ISSUE TITLE
Даешь human/blank в Карго!

### ISSUE THREAD

**Issue by TerraViJa** [ChaoticOnyx/OnyxBay#3135]
### Улучшение
У вас в билде есть такие "мобы" как  /mob/living/carbon/human/blank, так почему бы их не ввести как один из товаров в Карго?  Они могут понадобится на кухне, в Медбее, в НаУчКе. Стоимость им поставить в 30-50 кредитов и можно радоваться Катоникам, с прикольными шлемами из пластика.

### Решение
Они уже готовы в билде, осталось только в коробочку их положить и все.

**Comment by MrMagick2104** [comment]
Стоит тогда альтернативой запилить автомат по распечатке этих надувных людей на базе машинерии.

**Comment by lKameRUNl** [comment]
Обделяете робототехов работой, а робастерам даёте халяву? Уж слишком выгодно получается, мне кажется в макаку после смерти будет целесообразнее. Потерял тело? Нет уж, дружочек, будь добр, теперь терпи. Хоть какое-то наказание за утрату тела. Звучит глупо, но как по мне давать станции такую халяву ещё глупее, обленятся.

**Comment by Doster-d** [comment]
Перму ОПу

**Comment by Shabat-Sholom** [comment]
Ну такое, как по мне. Достаточно и того, что они у торгашей встречаются.

**Comment by TobyThorne** [comment]
Реализовано в #4930 (хоть и не бланки, а ватгровны).
