### ISSUE TITLE
Возвращение IPC.

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#3144]
Сейчас вместо IPC есть фулл-синтетики, что я считаю утраченным потенциалом. Full body органы в настройке персонажа дают лишь ПОЧТИ неуязвимость ко всем видам оружия, кроме ионки. Думаю, гораздо лучше будет иметь не всяких робокопов, а АНДРОИДОВ с очень интересным простором для ролеплея и восстанием машин с блэкджеком и видеокартами, конечно же.

Им будут доступны все профессии, кроме глав и СБшников. Добавлю, кстати, что в библиотеке есть целая книга со статьей про IPC с вики. Зачем она там, если самих ИПС выпилили?

**Comment by Doster-d** [comment]
Дубликат: https://github.com/ChaoticOnyx/OnyxBay/issues/2981

**Comment by Ershovdi** [comment]
А, ну круто.
