### ISSUE TITLE
Добавить стеклянный пол/потолок

### ISSUE THREAD

**Issue by PlinHost** [ChaoticOnyx/OnyxBay#3146]
Сабж, чтобы уровень ниже было видно.

<details>
<summary>
Картинка анрелейтед
</summary>

![ГЕТ](https://user-images.githubusercontent.com/8840325/90043643-0b108c00-dcd5-11ea-8b13-61bfbf0b6181.png)
</details>

**Comment by kreeperHLC** [comment]
https://github.com/ChaoticOnyx/OnyxBay/pull/10483
