### ISSUE TITLE
Runtime in unsorted.dm,1109: ... was unable to be GC'd

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#3185]
Очень частый рантайм, надо бы разобраться из-за чего они выпадают.

Возможно вызвал падение мастер-контроллера в #2924, но это не точно.

[16.07.20_09.08_b8a-bxJQ_runtime.log](https://github.com/ChaoticOnyx/OnyxBay/files/5093905/16.07.20_09.08_b8a-bxJQ_runtime.log)

**Comment by Epicus7** [comment]
Высокий приоритет, так как очень часто стреляет и возможно аффектит стабильность сервера.

**Comment by PlinHost** [comment]
Это сборщик мусора не смог собрать объект, потому что на него где-то осталась ссылка. У нас такая фигня по всему билду, а сам рантайм безобидный и ничего не прерывает.

**Comment by kreeperHLC** [comment]
Тоби фиксит такое, так что сам иссуй можно закрывать потому что в нём ноль конкретики
