### ISSUE TITLE
Лоадаут не показывается

### ISSUE THREAD

**Issue by Wuattt** [ChaoticOnyx/OnyxBay#3196]
### Описание бага
При нажатии кнопки Show loadout в Character Menu - General
Убирается головной убор. После, если нажать на Hide loadout, головной убор убирается!
Однако, остальные вещи из лоадаута даже не показываются. Ни при каких условиях, на картинке под Preview, что в Character Menu - General
### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем .. Нажимаем кнопку Hide load out в Character Menu - General
2. Открываем .. Loadout в Character Menu - Loadout
3. Нажимаем .. Accessories, потом bowtie, потом colour select, потом кнопку Take. Нажимаем General в Character Menu - General. 
4. Видим ошибку .. На спрайте космонавтика не видно бабочки, хотя она должна была быть там.

### Ожидаемое поведени
Должно быть видно бабочку на космонавтике

 - ID игры b8I-cjHG

**Comment by Zert0X** [comment]
Спустя 20 раз и смены тысячи разных предметов, повторить не удалось, видимо пофиксили.
