### ISSUE TITLE
Добавить OOC-лейаут для NanoUI без IC-деталей

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#3202]
Дефолтное пустое окошко NanoUI сейчас выглядит так:

![image](https://user-images.githubusercontent.com/5204667/90699699-9ae1a780-e28c-11ea-91ad-1e01cdf48893.png)

Как видно, тут везде торчит НТ-символика + сверху-слева виден символ, что компьютер активен. Такое окошко не очень смотрится для всяких OOC-вещей, вроде педальных кнопок или окна информации о донатах.

Нужно на основе текущего единственного шаблона `nano\templates\layout_default.tmpl` написать новый шаблон, в котором не будет НТ-символики и символов статуса. Вообще OOC-окошкам хочется придать более простой вид, например, такой (это захардкоженное окно Admin Secrets):

![image](https://user-images.githubusercontent.com/5204667/90699821-f4e26d00-e28c-11ea-96e0-45b1ad80e477.png)

Возможно на других билдах уже есть темплейты, которые можно тупо забрать к нам.

P.S. Как происходит подстановка и выбор этого шаблона для окошек можно посмотреть здесь:
https://github.com/ChaoticOnyx/OnyxBay/blob/e74408890b0aba128b44d645de82ba7f5ee916c5/code/modules/nano/nanoui.dm#L288

**Comment by BadRyuner** [comment]
![image](https://user-images.githubusercontent.com/54708336/92324408-6aeb2000-f052-11ea-9246-dc6ba6d2fbf5.png)
Примерно вот такой?
