### ISSUE TITLE
Забрать доступ в теха у ассистентов

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#3208]
Почему какие то левохуи на станции имеют доступ в технические помещения, а ебанный **пЕрСОнаЛ сТаНцИи** не всегда имеет туда доступ. Настолько сладкая и удобная роль ассистента и визитора, что у нас треть станции всегда лутатеры асистосы. Инженерка вообще мертва и пуста.

Раз боритесь с лутательством гетто путём удаления гетто, то сделайте уже что-нибудь главными манчкинстами станции.

**Comment by Judge1987** [comment]
а) Теперь лутерством будут заниматься инженеры и грузчики. Шпашибо.
б) Ассистент - он на то и ассистент, чтобы сам себе занятия по душе искать. Хочет лут искать - пусть ищет (и получает по голове, если, а если точнее - когда не повезёт). Хочет идти к ХоПу проситься на должности - он идёт туда. Ассистент - это краеугольный камень SS13, без него в эту игру играть смысла не будет.

**Comment by ArmolitskiyCarpoeb** [comment]
>улучшение

АХАХАХАХАХХАХАХ

армянин, лично я думал, что из тебя получится геймдиз, но, как я вижу, получится лишь гейдиз!

начнём разбор твоего говноиссуя:

>Почему какие то левохуи на станции имеют доступ в технические помещения
Не левохуи, а ассистенты (помощники). Что вообще должны делать ассистенты на станции? Обучаться чему-то, помогать кому-то. Например, какой-нибудь учёный может послать ассистента в техтоннели за металом. Сами ассистенты часто бродят по техтоннелям в поиске чего-нибудь интересного.

>а ебанный пЕрСОнаЛ сТаНцИи не всегда имеет туда доступ
Ну, смотри, зачем учёным, докторам (кроме парамедика) и некоторым другим профессиям доступ в техтоннели? У них есть своя работа в своих отделах, доступ им ни к чему (учёный может в теха послать ассистента, доктор - парамедика). Это создаёт некий баланс, так скажем.

>Настолько сладкая и удобная роль ассистента и визитора, что у нас треть станции всегда лутатеры асистосы.
Сладкая и удобная? Доступ только в техтоннели, да в дополнительное хранилище инструментов, самая низшая роль в иерархии (мальчик на побегушках, принеси-подай-ка и так далее), даже клоун выше (он же заслуженный актёр и самый главный развлекальщик на станции). Да и не все ассистенты - лутеры.

>Инженерка вообще мертва и пуста.
Именно поэтому мы выпилим доступ в теха у ассистентов))) ГЕНИЙ ГЕЙМДИЗАЙНА! Да, мы не будем делать инженерное дело интереснее (например запилить новый реактор или изменить существующий), лучше будем выпиливать что-нибудь.

Да и просто люду не понравится такое решение. Ассистент с доступом в теха - классика и не стоит ничего здесь менять!

**Comment by MrMagick2104** [comment]
> мальчик на побегушках, принеси-подай-ка и так далее

Половина ассистентов в этой роли выступать не будет в любом случае. Вот даже если ассистент не послушается кого-то, что ему могут сделать?
Уволить?
> визитора

А у визитора зачем доступ в теха?
> а, мы не будем делать инженерное дело интереснее (например запилить новый реактор или изменить существующий)

Лучше бы что-то связанное с автоматизацией a la Факторио. Одним реактором сыт не будешь, рано или поздно надоест (скорее всего рано), либо найдёшь самую оптимальную стратегию по использованию за пару часов настройки.

**Comment by bosslobster** [comment]
Никто не высказался за, кроме создателя. Закрываем.

**Comment by Kexilex** [comment]
Какой приоритет ещё, зачем?

**Comment by ArmenianOnyx** [comment]
Давно пора.
Или впиливать доступ в теха ВСЕМ, или выпиливать доступ левохуям-визиторам и ассистосам.

**Comment by Vanner0** [comment]
Наберешь.

**Comment by Shabat-Sholom** [comment]
Так приоритет пониженный...

**Comment by Shabat-Sholom** [comment]
Забирать доступ в теха у их кореных жителей - такое.

**Comment by Vanner0** [comment]
За такие иссуи надо по пальцам бить. Хуевые, говорит, у нас геймдизайнеры. Выпиливают все.

**Comment by PlinHost** [comment]
Визиторов давно нет, расходимся.
