### ISSUE TITLE
Речь должна быть слышна, если она воспроизводится персонажем за пределами твоего экрана

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#3211]
Короче, если персонаж говорит в пределах экрана, то его прекрасно слышно, а если он просто вышел на один тайл за границы экрана, то его не слышно. Сделать так:
Если другой персонаж ушёл за пределы экрана, но не больше, чем на 3 тайла от границ экрана, то его всё ещё можно будет слышать, но его текст в чате будет меньше, чем обычный.

**Comment by MrMagick2104** [comment]
> Если другой персонаж ушёл за пределы экрана, но не больше, чем на 3 тайла от границ экрана, то его всё ещё можно будет слышать, но его текст в чате будет меньше, чем обычный.

Лучше сделать эффект как с шёпотом, имхо, когда часть слов не слышно. 
Либо 1 тайл за экраном - слышно маленьким текстом, дальше - маленьким текстом с частью слов неразборчиво, как с шёпотом.
