### ISSUE TITLE
Добавить резистов броне баттлмага.

### ISSUE THREAD

**Issue by SukaYaEbalPridumivatImya** [ChaoticOnyx/OnyxBay#3238]
Его броня сейчас от мягкого скафандра отличается только, бля, спрайтом. А это, мать его, мастеркрафтовая херня.
Вопрос один, какова хуя.

**Comment by Ruforce** [comment]
Может он про войдсьют?

**Comment by SukaYaEbalPridumivatImya** [comment]
> > Его броня сейчас от мягкого скафандра отличается только, бля, спрайтом. А это, мать его, мастеркрафтовая херня.
> > Вопрос один, какова хуя.
> 
> Это броня из картона, сделанная магом для косплея. Почему она должна защищать?
> Ну и плюс она всё равно лежит в ящике же, как и любая другая, нужна только для вида.

Да, я про скафандр этот, который ещё и покупать надо.
Который на деле не мастерски сделанная броня, а скафандр с брюликами.

**Comment by MrMagick2104** [comment]
> Да, я про скафандр этот, который ещё и покупать надо.
Который на деле не мастерски сделанная броня, а скафандр с брюликами.

Магическая броня должна давать магические резисты, по закону жанра.

А если серьёзно, у нас так почти со всеми войдсьютами. Вроде как костюм с металлическими вставками, тяжёлый (1 слоудаун), защищает от вакуума, а от чего-либо ещё не защищает. В лучшем случае от ближнего боя.
Например, инженерный войдсьют.
```
name = "engineering voidsuit"
	desc = "A run-of-the-mill service voidsuit with all the plating and radiation protection required for industrial work in vacuum."
    armor = list(melee = 40, bullet = 5, laser = 20,energy = 5, bomb = 35, bio = 100, rad = 80)
```
> all the plating

> bullet = 5

5% защиты - это -1 урон от пульки в 9мм, что вообще ничего не значит. А ещё столько же, насколько защищает, допустим, цилиндр для головы от пуль.

**Comment by ArmenianOnyx** [comment]
Во клоуны набежали. Им говорят что воидсуит мага гавно и поэтому его никто не берёт - клоуны затирают что все скафандры гавно.

И правда зачем антагу интересные способности. Пусть лутается, у нас же тут Escape from Exodus

**Comment by ArmenianOnyx** [comment]
Если бы у мага оставлись в мидл раунде свободные очки, то от спела воидсуита был бы хоть какой то смысл. Но ой, вы же порезали очки магу.

**Comment by Doster-d** [comment]
Бузотеры! Разработ очку не уважаете?

**Comment by jammer312** [comment]
> Магическая броня должна давать магические резисты, по закону жанра.
Зачем магам, которые имеют монополию на магию и не имеют разногласий в своем обществе, броня с резистом к магии, особенно на станции, где других магов нет?
На ТГ броня мага имеет щит, который поглощает некое количество инстансов урона (вне зависимости от того, насколько большой урон прилетает, один заряд щита его полностью поглотит), и перезаряжается специальными батарейками, которые покупаются за очки. Можно нечто подобное запилить.

**Comment by MrMagick2104** [comment]
> Во клоуны набежали. Им говорят что воидсуит мага гавно и поэтому его никто не берёт - клоуны затирают что все скафандры гавно.

Речь была о том, что все скафандры надо бы перебалансировать, не только маговский, потому что у большинства резисты смешные.
> интересные способности

> Броня с кристаллами

А что интересного в обычном бронескафандре, который выглядит красиво?
Лучше бы его в карго пихнули, как эдакий "Pimp voidsuit" за 500 очков или что-то такое.
> Зачем магам, которые имеют монополию на магию и не имеют разногласий в своем обществе, броня с резистом к магии, особенно на станции, где других магов нет?

Бэкстори мага и гильдии магов придумывает маг. Но чисто ингейм они не нужны, это так, оффтоп.
> На ТГ броня мага имеет щит, который поглощает некое количество инстансов урона (вне зависимости от того, насколько большой урон прилетает, один заряд щита его полностью поглотит), и перезаряжается специальными батарейками, которые покупаются за очки. Можно нечто подобное запилить.

А при покупке брони нужно ли давать магу запасные батарейки? Сколько батареек за один поинт мага?
Имхо, лучше сделать щит не очень сильным, 50 хп, условно, но батареек запасных давать больше, по три-четыре штуки за одну покупку дополнительных батареек и одну запасную за факт покупки брони.

**Comment by FarSetV** [comment]
Я пришёл напомнить про баланс магов. И да. Скафандр БОЕВОГО мага не должен быть дуршлаком из Али-экспресс.

**Comment by TobyThorne** [comment]
Закрыто в #6574. Отдельное спасибо тем, кто не лепят иссуи к ПРам и приходится это искать в сотнях страниц.
