### ISSUE TITLE
Шкафы съедают космонавтиков

### ISSUE THREAD

**Issue by Baneuus** [ChaoticOnyx/OnyxBay#3243]
Если начать откручивать дверцу у шкафа, а в это время в нём закроют человечка, то дверца шкафа открутится, шкаф окажется пустым, а человек попадёт в варп, не имея возможности легко выбраться. Только педально, если не ошибаюсь.

**Comment by Tsurupeta** [comment]
Шкаф не окажется пустым, внутри шкафа будет человек, который не сможет выйти из шкафа, ведь при успешном резисте ничего не будет происходить.

**Comment by TobyThorne** [comment]
Исправлял в какой-то момент. Больше не воспроизводится.
