### ISSUE TITLE
Ноутбук ломает верхнюю панельку.

### ISSUE THREAD

**Issue by LLIkolnik** [ChaoticOnyx/OnyxBay#326]
**Описание бага**
Четкое и понятное описание сути бага.
![image](https://user-images.githubusercontent.com/32063181/50052767-75041700-0129-11e9-9d32-12dad2973554.png)

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем ноутбук.
2. Открываем в ноутбуке редактор документов.
3. Нажимаем кнопку превью.
4. Видим знаки вопроса. Много знаков вопроса.

**Ожидаемое поведение**
Четкое и понятное описание того, что должно было произойти.
Я думаю, оно не должно ломаться как на скринах?

**Скриншоты**
Если проблема может быть показана на скриншотах - прикрепите их.
![image](https://user-images.githubusercontent.com/32063181/50052793-02476b80-012a-11e9-9365-d4208a49dd24.png)

Тут после релога проблема чинится, видимо.
![image](https://user-images.githubusercontent.com/32063181/50052795-070c1f80-012a-11e9-99d6-68af7446bf8e.png)

/*

**Характеристики**
 - OS: [e.g. Windows/Linux, эмулятор] 
 - Версия клиента [смотрите в BYOND]
 - Версия сервера [команда "Show server revision" в вкладке ООС на сервере]
 - ID игры [там же]

*/
Не ебу.
**Дополнительная информация**
Здесь можете описать любую дополнительную информацию, которая касается бага
![image](https://user-images.githubusercontent.com/32063181/50052786-dc21cb80-0129-11e9-91fd-f7262c4f46d8.png)

Играло, пожалуйста, НАУЧИСЬ ПОЛЬЗОВАТЬСЯ ГИТХАБОМ И НЕ ПРОТЕКАТЬ.

**Comment by PlinHost** [comment]
#327

**Comment by vekotov** [comment]
Мне просто сказали, накатать иссуху самому.
