### ISSUE TITLE
Нейромод РнД консоль удаляет объекты.

### ISSUE THREAD

**Issue by RufusZero** [ChaoticOnyx/OnyxBay#3262]
**Neuromod RnD Console удаляет любой объект из активной руки при нажатии на кнопку её интерфейса "Insert Neuromod Shell"**

**Steps to reproduce:**
1. Исследуем плату Нейромод Консоли в научном.
2. Строим консоль.
3. Открываем интерфейс.
4. Жмём кнопку Insert Neuromod Shell c любым предметом в руке.
5. Предмет исчезает без следа
6. Консоль может удалять бесконечно и что угодно.

**Expected Behavior:**
Консоль не принимает посторонние предметы и/или выводит сообщение об ошибке.

**Possible Solution:**
Думаю, очевидно, что psychotronics ветка разработки не закончена (нейромоды нельзя создать), но в продакшене полным ходом (РД начинает с психоскопом в чемодане у себя в офисе), нужен минимальный stub-метод для предотвращения удаления предметов. Насколько я понимаю, нужна банальная проверка на held item.

**Обнаружено на:**
Client Version: 513
Server Revision: 8c6c35f577d6da4aac64f011c9e090092b29ab13 - release/lawful - 2020-08-25
Game ID: b8R-btof

**Comment by Shabat-Sholom** [comment]
Ну так фичу так и не допилили.
