### ISSUE TITLE
Печать тел для нейронити.

### ISSUE THREAD

**Issue by Doster-d** [ChaoticOnyx/OnyxBay#3295]
### Улучшение
Пришло время допилить проект https://github.com/ChaoticOnyx/OnyxBay/projects/12 .
Добавить машину для создание людей в ССД (случайное имя и внешность) за мясо для обладателей нейронитей.

### Решение
Предлагаю добавить возможность напечатать плату машину (/obj/machinery) в ~~дроч протолата~~ РнД (технологии: TECH_MATERIAL = 6, TECH_ENGINEERING = 5, TECH_DATA = 3, TECH_MAGNET = 2, TECH_BIO = 6).
Для постройки машина так же нужны: 3 манипулятора, 2 банки, 1 улучшенный сканирующий модуль, 2 лазера.
В случае нехватки мяска будут использованы уже имеющиеся ресурсы, после этого работа будет остановлена, пока не будет добавлена новая порция мяса.
Цена создания тела около ~25 кусков мяса.
Тело - human/blank

Время создания тела 2-3 минуты (стоковые детали) и минута при улучшенных деталях.
Так же в стоковом варианте невозможно будет создать тело сразу, то есть придется добавлять мясо в машину.

Улучшенные компоненты будут увели́чивать скорость воспроизводства существа и уменьшать время создания данных тел. (манипуляторы и лазеры отвечают за скорость, сканирующий модуль с банками за стоимость создания)

Так же у машину будет 3 провода:
Питание - отвечает за работоспособность машины
Активация - отвечает за процесс создания тела
Экспериментальный режим - при нем можно создавать тела обычных людей и ксеносов, в таком случае будет справедливо следующие:
В начале процесса печати нужно выбрать расу тела.
Тела с проком в 50 процентов будут иметь трейт weak или с проком в 15 трейт wimpy, так же тела по умолчанию будут иметь трейт filmsy, по решению геймдизайна можно накинуть с проком в 25 трейт frail
### (Опционально) Альтернативы
Дать возможность за 100-150 очков карго сделать покупку пустого тела, случайная раса и внешность
Можно еще сделать печать различных домашних животных.

### (Опционально) Дополнительная информация
Для реализации машины можно использовать спрайты из icons/obj/cryogenic2 scanner_0 и scanner_1.

**Comment by MrMagick2104** [comment]
> (технологии: TECH_MATERIAL = 7, TECH_ENGINEERING = 5, TECH_DATA = 3, TECH_MAGNET = 2, TECH_BIO = 8, TECH_ILLEGAL = 8).

Что-то лишканул, имхо. Единственный способ получить такой печатник - убить генокрада, а потом через админ панель выдать себе ресёрч дебаг тул, дающий 19-е уровни, потому что иллегал до 8 поднять у нас никак нельзя, по-моему.
Я бы сказал, что:
> TECH_MATERIAL = 6, TECH_ENGINEERING = 5, TECH_DATA = 3, TECH_MAGNET = 2, TECH_BIO = 6, TECH_ILLEGAL = 1

Подошло бы лучше. Если впиливать слишком высокую цену, то в итоге никто просто фичей пользоваться не будет, либо знать о ней вообще.
Опционально иллегал убрать вообще, так как его изучение требует ресурсов, либо пробежку по гетто или дереликтам (а гетто убрали!), что намного уменьшает вероятность того, что машина будет собрано. Очень намного.
> Дать возможность за 100-150 очков карго сделать покупку пустого тела, случайная раса и внешность
> В начале процесса печати нужно выбрать расу тела.

Имхо, лучше при использовании давать возможность печатать стоковых ват-гровн хуманов (только на них нейронить не работает, возможно? Не уверен, баги там какие-то) (можно сделать и вариации с ват-гровн ксеносами (и всем ват-гровнам дебаффов каких-то накинуть, например, трейт на хрупкость по умолчанию (-20% хп)), только тут уже сложнее, ибо спрайты нужны), а при взломе (емагом или проводами) давать возможность печатать обычных людей или ксеносов.

Хорошо бы смотрелась возможность печатать обезьян и домашних животных (котов и собак) в качестве дополнительной фичи.

**Comment by Doster-d** [comment]
> > (технологии: TECH_MATERIAL = 7, TECH_ENGINEERING = 5, TECH_DATA = 3, TECH_MAGNET = 2, TECH_BIO = 8, TECH_ILLEGAL = 8).
> 
> Что-то лишканул, имхо. Единственный способ получить такой печатник - убить генокрада, а потом через админ панель выдать себе ресёрч дебаг тул, дающий 19-е уровни, потому что иллегал до 8 поднять у нас никак нельзя, по-моему.

С иилегалом согласен, сам хотел поставить на 5, а по биотехнологиям у Вас недостоверная информация, не только убив генокрада можно достичь 8 уровня, с кодом вроде Вы дружите, сможете найти :)

> Хорошо бы смотрелась возможность печатать обезьян и домашних животных (котов и собак) в качестве дополнительной фичи.

Хорошая мысль, впишу в иссуй.

**Comment by anihillator** [comment]
> С иилегалом согласен, сам хотел поставить на 5, а по биотехнологиям у Вас недостоверная информация, не только убив генокрада можно достичь 8 уровня, с кодом вроде Вы дружите, сможете найти :)

А давай ты сам назовешь все биопредметы 7+ уровня? Я сходу могу предположить только экстракт, но точно не помню. А еще как-то жирно делать такие высокие уровни, особенно нелегалку, для банальной печати мясных мешков, имхо.

**Comment by Doster-d** [comment]
> А давай ты сам назовешь все биопредметы 7+ уровня? Я сходу могу предположить только экстракт, но точно не помню. А еще как-то жирно делать такие высокие уровни, особенно нелегалку, для банальной печати мясных мешков, имхо.

Легко, взять психоскоп и дрочить слаймов, подрочишь около 10-15 (в зависимости от luck) и у тебя 8 уровень био, берешь диск для записи техов и нажимаешь одну кнопку и все, у тебя 8 уровень.

**Comment by anihillator** [comment]
> > А давай ты сам назовешь все биопредметы 7+ уровня? Я сходу могу предположить только экстракт, но точно не помню. А еще как-то жирно делать такие высокие уровни, особенно нелегалку, для банальной печати мясных мешков, имхо.
> 
> Легко, взять психоскоп и дрочить слаймов, подрочишь около 10-15 (в зависимости от luck) и у тебя 8 уровень био, берешь диск для записи техов и нажимаешь одну кнопку и все, у тебя 8 уровень.

Бля, психоскоп. Ты вспомнил недоделанную, полурабочую фичу, которую лично я в раунде видел один раз (когда напечатал сам чтобы посмотреть, шо таке оно делает).

**Comment by MrMagick2104** [comment]
Смысл в том, что делать данную машину слишком сложнополучаемой в плане уровней и не давать альтернатив по получению платы (вроде заказа её из карго), означает делать машину, которой пользоваться будет один скучающий аутист в сто раундов, что не стоит таких затрат усилий.

**Comment by Doster-d** [comment]
> Смысл в том, что делать данную машину слишком сложнополучаемой в плане уровней и не давать альтернатив по получению платы (вроде заказа её из карго), означает делать машину, которой пользоваться будет один скучающий аутист в сто раундов, что не стоит таких затрат усилий.

Справедливо.

**Comment by Doster-d** [comment]
> Бля, психоскоп. Ты вспомнил недоделанную, полурабочую фичу, которую лично я в раунде видел один раз (когда напечатал сам чтобы посмотреть, шо таке оно делает).

Ну если поставить TECH_BIO на 8 для этой машину, то хотя бы будут причины использовать психоскоп, а там недалеко от иссуев на тему починки нейромодов :)

**Comment by Doster-d** [comment]
> ... для банальной печати мясных мешков, имхо.

Относительно последний вещи, которой можно создать на этой ветке, напомню bluespace organ fixer, 6 уровень, это действительно заслуживает 8 уровня, возможно я ошибаюсь.

**Comment by Doster-d** [comment]
Обновил описание

**Comment by Ruforce** [comment]
Детей РнД полон чатик. Идея хорошая, но пожалуйста, не проебитесь с балансом.

**Comment by Doster-d** [comment]
> Детей РнД полон чатик. Идея хорошая, но пожалуйста, не проебитесь с балансом.

Было бы очень полезно узнать мнение не ребенка РнД, ожидаю Ваше мнение, Ruforce.

**Comment by kemperhun** [comment]
У нас есть https://github.com/ChaoticOnyx/OnyxBay/issues/2448 после которого баланс слетит в любом случае. На мой взгляд, лучше дождаться его, а потом уже балансить что-то здесь, исходя из нового опыта рнддроча с техническими деревьями.

**Comment by Doster-d** [comment]
> У нас есть https://github.com/ChaoticOnyx/OnyxBay/issues/2448 после которого баланс слетит в любом случае. На мой взгляд, лучше дождаться его, а потом уже балансить что-то здесь, исходя из нового опыта рнддроча с техническими деревьями.

Пока реализуют хотя бы основную идею иссуя, мы уже успеем состарится

**Comment by MrMagick2104** [comment]
> Пока реализуют хотя бы основную идею иссуя, мы уже успеем состарится

Достаточно сделать баланс не слишком экстремальным, а там можно и отложить.
Чтобы не было такого, что машинка - бесполезная и ненужная шутка из научки, либо бесконечный штампователь бесплатных тел.
Можно ещё потенциально запилить возможность печатать людей в стиле ксерокопирования, при помощи шприца кровью, но если так подумать, то это уже какая-то клонмашина получается.

**Comment by bosslobster** [comment]
Главное не откройте этой фичей ресторан "У Генокрада", а то все генки будут сидеть и дрочить РНД

**Comment by ArmolitskiyCarpoeb** [comment]
Генокрад может поглощать только те тела, в которых уже есть нейронить. То есть, только что созданные тела без души или нейронити не поглощаются.

**Comment by Doster-d** [comment]
> Генокрад может поглощать только те тела, в которых уже есть нейронить. То есть, только что созданные тела без души или нейронити не поглощаются.

Можно просто не давать им очки за такие тела?

**Comment by Doster-d** [comment]
Проблема решена покупкой тела.
