### ISSUE TITLE
У меха отсутствует спрайт

### ISSUE THREAD

**Issue by PlinHost** [ChaoticOnyx/OnyxBay#330]
**Описание бага**
~У рипли классика нет открытого стейта `ripley-old-open`.~ #345
~Бонус: `ripley-broken-old` должен называться `ripley-old-broken`.~
Бонус: у перекрашенных мех в коде обломки оригинала.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Открываем код мехов
2. Открываем иконки мехов
3. Думаем

**Ожидаемое поведение**
Должны быть ~иконка и~ наверное свои (в коде) обломки у перекрашенных.

**Характеристики**
В релизе сейчас короче.

***Дополнитель*ня *информация***
приветики всем в этом чятике, ня

**Comment by denver1000** [comment]
Дядь, я сделал!
