### ISSUE TITLE
Анимированные фотографии

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#3302]
![анимированные фото](https://user-images.githubusercontent.com/48406301/92304042-2c3a6480-ef83-11ea-9c37-da62524ee871.gif)
какие-то слишком продвинутые технологии

**Comment by Doster-d** [comment]
Темплейт слишком сложно использовать наверное, да?

**Comment by TobyThorne** [comment]
После реворка камер (гетфлатикона) не смог воспроизвести.
