### ISSUE TITLE
Сломан examine: не показывает информацию на желтых створках и не работает на коллекторах.

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#3337]
Теперь ![image](https://user-images.githubusercontent.com/48406301/93003275-080ff200-f546-11ea-909b-82e1daa5f6ac.png) не показывает ![image](https://user-images.githubusercontent.com/48406301/93003282-13631d80-f546-11ea-859a-28ce54eba177.png) если не подойти вплотную.

А еще ![image](https://user-images.githubusercontent.com/48406301/93003307-3261af80-f546-11ea-8ce8-e2a41a6f44b1.png) больше не экзаминится вообще.

Скорее всего это появилось после #3068 (генератор голограммы трейтора)

**Comment by MrMagick2104** [comment]
> Теперь не показывает если не подойти вплотную.

Не баг, а фича ведь. Как ты читать показания барометров/термометров с десяти метров читать будешь? Шрифт-то мелкий.

**Comment by Animesku** [comment]
Офигенная фича. У нас их из новичков и так никто не читает, не зная, что там показания высвечиваются, и тем самым распространяют разгерму или пожар, а ты еще усложнить предлагаешь.

**Comment by jammer312** [comment]
> Теперь не показывает если не подойти вплотную.

Было багом, случайно было пофикшено (не то что бы прям случайно, но непреднамеренно). Не вижу особых причин снова возвращать багнутое поведение.

**Comment by jammer312** [comment]
Коллекторы да, поломались ровно тем ПРом, ща пофикшу.
