### ISSUE TITLE
Невозможно вырастить мутации яблок.

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#3358]
Поломались яблоки, мутировать их невозможно.
Вместо мутации в золотые или ядовитые яблоки, растение мутирует само в себя.
![image](https://user-images.githubusercontent.com/62835631/93347599-f11b1980-f83d-11ea-910b-39d2625a9d08.png)
(Мутировавшее таким образом яблоко не ядовитое, я проверял блендером)

**Comment by TobyThorne** [comment]
Яблоко одного цвета может мутировать в яблоко другого цвета. Деревья у обычных яблок (красных, жёлтых, зелёных) все называются apple tree.

**Comment by ArmenianOnyx** [comment]
ты блядь чем читал мой иссуй?

**Comment by ArmenianOnyx** [comment]
я пишу что яблоки вообще не мутируют в ядовитые или золотые, а он мне это

**Comment by TobyThorne** [comment]
![image](https://user-images.githubusercontent.com/45202681/93379364-8a1e5480-f87f-11ea-96f8-00d262c6517a.png)
![image](https://user-images.githubusercontent.com/45202681/93379389-95718000-f87f-11ea-878f-ea84913b82b6.png)
Всё нормально мутирует. Просто шанс низкий (33.3(3)%) из-за наличия мутаций в другие цвета. ОП хуй.
