### ISSUE TITLE
Make MEME great AGAIN!

### ISSUE THREAD

**Issue by Reishi42** [ChaoticOnyx/OnyxBay#338]
**Meme**
Четкое и понятное описание сути бага.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем МЕМЕ
2. Открываем вкладку МЕМЕ
3. Нажимаем SAY
4. Не видим ничего, текст вводится, но НЕ выводится. Тоже самое с /me. С горем пополам через раз работает Whisper

**Ожидаемое поведение**
Должен был произойти ДИАЛОГ.

**Скриншоты**
Если проблема может быть показана на скриншотах - прикрепите их.

**Характеристики**
 - OS: [e.g. Windows] 
 - Последняя
 - Версия сервера [команда "Show server revision" в вкладке ООС на сервере]
 - Server Revision: 09fcef9866f08952d2451f7dea3017e1ec831c6e - release - 2018-12-22

**Дополнительня информация**
А ещё не работает Анагльгетик, кнопка просто не прожимается, очки не тратятся

**Comment by hard-res3t** [comment]
> Reishi42 commented on 22 Dec 2018

Не актуально. Вкладки МЕМЕ нет. Закрываю.
