### ISSUE TITLE
Биоструктура генокрада исчезает

### ISSUE THREAD

**Issue by TheUnknownOneGH** [ChaoticOnyx/OnyxBay#3402]
### Описание бага
У генокрадов при каких-то туманных обстоятельствах в трёх разных случаях исчезли биоструктуры, просто бесследно удаляются и нельзя использовать никакие способности. В одном случае она выкинулась на пол из тела. Причём игрок остался в теле и мог нормально играть (до первой смерти), а биоструктура была вне него. Вроде как во всех случаях хотя бы один раз до бага использовался стазис.

### Воспроизведение
Хрен знает как, в одном случае биоструктура исчезла после отрезания головы (она была не в голове), во втором - после гиба головы (и тоже была не в голове), в третьем она выкинулась из тела на пол после того, как в человека кинули каким-то предметом (может быть не баг, а фича, но как-то подозрительно).

### Дополнительная информация
Жертвы сего бага: Я в одном раунде, АмиКлерик и Сухарик во втором, который был сразу после первого. Раунды были на Хаотике ночью, ИДов нет потому что лолололололол, первый начался где-то в 23:00 МСК, второй где-то в 1:30.
Возможно вызвано #3341

**Comment by Doster-d** [comment]
Логика возрождения никак не изменена, вина #3341 исключена.

**Comment by Shabat-Sholom** [comment]
Ah, shit. Here we go again.

**Comment by Doster-d** [comment]
А может и виновата...

**Comment by Doster-d** [comment]
Приоритет, пожалуйста, играть невозможно из-за этого бага.

**Comment by Doster-d** [comment]
В качестве меры пока фикс не на сервере, можно делать так: попросить игрока трансформироваться в самого себя (или любую другую личность), или если игрок мертв - возродить, попросить трансформироваться в самого себя (или любую другую личность).
