### ISSUE TITLE
Проблемы с мастерконтроллером (?) после обновления.

### ISSUE THREAD

**Issue by MorJams** [ChaoticOnyx/OnyxBay#3405]
### Описание бага
ADMIN LOG: MC crashed or runtimed, restarting

ADMIN LOG: Failed to recreate MC (Error code: -1), it's up to the failsafe now

После этого были жалобы на то, что неправильно работало освещение, а так же на то, что сообщения в чат не посылались. ООЦ работало.

После того, как я педально рестартнул контроллеры - всё вроде заработало нормально. Игроки говорят, что подобная хрень иногда появляется начиная с недавнего обновления (смотреть ревизию)

### (Опционально) Характеристики
Client Version: 513
Server Revision: 78fa97e063bf1e225f7aff051e587173bf837f5f - release/chaotic - 2020-09-26
Game ID: b9l-b4g9
Current map: NSS Exodus

Время приблизительно 17:05

**Comment by TobyThorne** [comment]
Неактуальное. Всё уже переделывалось тысячу раз.
