### ISSUE TITLE
В конце раунда писать в логи все итоги раунда

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#3409]
Законы ИИ, всех ролей, их цели, успех и так далее. Короче все, что пишется в гринтекст - писать в логи.

Нужно для разбора банхимов всяких.

**Comment by k4m3rn** [comment]
[#7954](https://github.com/ChaoticOnyx/OnyxBay/pull/7954) [#7589](https://github.com/ChaoticOnyx/OnyxBay/pull/7589) [#4747](https://github.com/ChaoticOnyx/OnyxBay/pull/4747) [#4752](https://github.com/ChaoticOnyx/OnyxBay/pull/4752)
Крч это давно уже сделали, требуется закрыть иссуй. Гринтекст пишется в логи, однако коктракты синдиката логируются только если ты их выполняешь, общего списка нет, да и не сильно надо.
