### ISSUE TITLE
УБОРЩИК. BORN TO CLEAN.

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [ChaoticOnyx/OnyxBay#3417]
Хотелось бы сделать работу уборщика более интересной или же удобной. 

Новые вещи:
Bluespace Cleaner - такой же клинер, но с большой вместительностью. Делается в РнД, конечно же.
Advanced mop - швабра, имеющая встроенный бак на 50-100u, куда можно заливать жидкость. Теперь не нужно будет брать ведро с водой. Тоже делается в РнД.
Bluespace trash bag - как мешок, но с большей вместительностью. Делается в РнД. 
Janitor HUD - подсвечивает/показывает загрязнения на полу. 1-2 штуки в шкафчик + делается в РнД.

Автомат в комнату уборщика:
Содержит базовый инвентарь уборщика в количестве 2 штуки (то есть в автомате 2 пары галош, 2 униформы и т.д.) + два спейс клинера и 4 чистящих гранаты. Всё, кроме униформы, покупается за деньги.

Буду дополнять иссуй по мере необходимости, и если у меня появятся ещё идеи (предлагайте и свои).

**Comment by MrMagick2104** [comment]
> Bluespace Cleaner - такой же клинер, но с большой вместительностью. Делается в РнД, конечно же.

Уже химспреер есть, который жжёт на 3х9 тайлов вперёд любой жидкостью (в т.ч. клинером), а имеет вместимость в 600 юнитов.

**Comment by ArmolitskiyCarpoeb** [comment]
>Уже химспреер есть

А как ты его в карман положишь?

**Comment by MrMagick2104** [comment]
А зачем такую вещь в карман класть?

**Comment by ArmolitskiyCarpoeb** [comment]
>А зачем такую вещь в карман класть?
Причём тут это? Пусть блюспейс клинер будет компактной версией химспреера, будет вмещать меньше, чем химспреер, но больше, чем обычный спейс клинер.

**Comment by MrMagick2104** [comment]
Не, вопрос в том, зачем с точки зрения геймдизайна карманный химспреер?
Смысл бутылки в том, что она особо много не вмещает, а химспреера в том, что он тратит довольно много, пусть и делает АоЕ урон.
Нужно ведь понимать, что если ты делаешь что-то, что может распылять реагенты, этим будут распылять нейротоксины, хлорку, фтороводород, всю нашу замечательную химию, а не то, что было запланировано изначально.
И карманный спреер, который вмещает много, тратит как обычный, но не имеет проблем с вмещением любых других реагентов, выйдет машиной робаста.
Можно, вместо этого, сделать распылитель с бесконечным клинером (лубом, если емагом по нему нажать), в который нельзя поместить другие реагенты, я считаю.
Как у нас с экспериментальными сварочниками, к примеру.

**Comment by ArmolitskiyCarpoeb** [comment]
> Можно, вместо этого, сделать распылитель с бесконечным клинером (лубом, если емагом по нему нажать), в который нельзя поместить другие реагенты, я считаю.

Тогда этот бесконечный клинер должен быть самым последним из исследований в категории "Уборка", так сказать, финальным.

**Comment by Shabat-Sholom** [comment]
Блюспейс-пакеты без фикса бага с пакетами в карманах - фри БоХи, которых ещё и три штуки можно таскать. Нужно либо размер им увеличить, чтоб в карман не лезли, либо просто запретить класть в данные слоты.

Касательно автоматов с эквипом за деньги, это надо бы вынести в отдельный иссуй с пометочкой "улучшение", ибо добавлять такую фичу только никому не всравшимся уборщикам - какая-то проигрышная стратегия с точки зрения геймдизайна.

ХУДы, которые палят грязь (но не декальную) через стены, называются материалками, а простую подсветку мусора в поле зрения хз, как можно организовать, ведь грязные тайлы реально видно и в данный момент. Это не Торч, где третья их часть покрыта сеткой и там реально нужно это.

Швабру и голопроектор (который ты не указал) сам Бог ввести велел, это очень даже кайфово.

По итогу имеем, что большая часть идей в данный момент не очень-то и применима к билду. Откинуть бы это "до лучших времён", но я не геймдиз. Пусть они решают, что делать. Тебе же советую иссуи с "подводящими" фичами оставить. Глядишь, награду назначат, да реализуют.

**Comment by ArmolitskiyCarpoeb** [comment]
Разделяю этот иссуй на другие иссуи, закрываю этот, потому что он никому не сдался.
