### ISSUE TITLE
Добавить звук "шумному" поеданию дионой травы из трея.

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3477]
### Улучшение
В описании одного из действий дионы, поедание сорняков в грядке, написано что диона делает это шумно, но звукового сопровождения нет

### Решение
Добавить звук поедания сорняков дионе

### (Опционально) Альтернативы
Убрать надпись гласящую что диона поедает сорняки шумно

**Comment by Shabat-Sholom** [comment]
Мукбанги при поедании дионой травы. Наконец-то фича, достойная Оникса.

**Comment by kreeperHLC** [comment]
![image](https://user-images.githubusercontent.com/14943437/166716877-573f3b73-9b7e-4c51-a4b8-a45328149521.png)
Сейчас бы сложность на неодобренные ПРы
