### ISSUE TITLE
Раковины в робототехнику.

### ISSUE THREAD

**Issue by Shabat-Sholom** [ChaoticOnyx/OnyxBay#3527]
### Улучшение
Добавить наконец то в операционную робототехники раковины. Нельзя делать нормально операции, тк можно занести инфекцию при имплантации или замене частей тела на синтетические. Не прошу даже медикаментов туда, но бегать за мылом или клинерами в соседние отделы как то тупо, одной раковины хватит для этой функции.

### Решение
Добавить раковину.

### (Опционально) Альтернативы
Добавить спейсклинер и стерилизин на стол у операционного стола в робо.

### (Опционально) Дополнительная информация
Работаю ботом и переношу иссуи из канала дискорда. Этот был поддержан более чем 30 лайками. Автор - Edharg
#4721

**Comment by sweden-moose** [comment]
Берусь, хоть с мапой поработаю
