### ISSUE TITLE
Не работают ссылки в гунчате

### ISSUE THREAD

**Issue by Shabat-Sholom** [ChaoticOnyx/OnyxBay#3529]
При открытии ссылки из гунчата он вдобавок к ней тащит кавычки .
https://i.imgur.com/XR66wvK.png

Создано по сообщению из дискорда за авторством Соляра. https://discordapp.com/channels/414832443384659968/606411392811139072/766438729446719520

**Comment by 4310V343k** [comment]
Не воспроизводится
![proof](https://user-images.githubusercontent.com/56449763/96333426-8f371500-1072-11eb-914c-b1af6b1eaf8b.gif)

**Comment by Shabat-Sholom** [comment]
В ахелп воспроизводится.

**Comment by 4310V343k** [comment]
> В ахелп воспроизводится.

Ну вот и надо писать, что кавычки тащит, если пишут в АХЕЛП

**Comment by Shabat-Sholom** [comment]
На сервере воспроизводится в любом проявлении. Вставляется нормальная ссылка, открывается битая.
