### ISSUE TITLE
Кнопка для включения и отключения рандом ивента с Блобом.

### ISSUE THREAD

**Issue by Doster-d** [ChaoticOnyx/OnyxBay#3533]
### Улучшение
Кнопка для включения и отключения рандом ивента с Блобом.

### Решение
Если вы не хотите выпиливать блоба совсем, сделайте хоть кнопку, чтобы можно было вырубать блоба из ротации рандом ивентов. Во вкладку "server" эту кнопку можно засунуть, рядом с "toggle aliens" например.

### (Опционально) Дополнительная информация
P.S. данный иссуй был создан из-за того, что бот сдох

**Comment by Fox231** [comment]
Так и так уже есть возможность спилить его в Event Manager кнопке. Или тебе именно кнопка отдельная нужна?

**Comment by Doster-d** [comment]
> Так и так уже есть возможность спилить его в Event Manager кнопке. Или тебе именно кнопка отдельная нужна?

Ты хочешь каждую итерацию отключать его или один раз нажать и отключить? (В моем ПРе, наоборот, кнопка включает блоба)

**Comment by Shabat-Sholom** [comment]
Уже есть, да и пулл умер.
