### ISSUE TITLE
Специес-рестрикты

### ISSUE THREAD

**Issue by AshtonFox** [ChaoticOnyx/OnyxBay#354]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Ну, смысл в том, чтобы вернуть для ксенов профессии с блюбэя. Это решит проблему того, что я не могу поиграть за таярочку на интересных проффах типа парамедик, инженер и т.п.

**Опишите ваше решение проблемы**
Решение заключается в том, чтобы убрать специес-рестрикты с некоторых профессий.

**Опишите альтернативы, о которых вы думали**
Что?

**Дополнительная информация**
За цивилов реально играть заёбывает. Не интересно.

**Comment by Vostok-Odin** [comment]
please don't

**Comment by AshtonFox** [comment]
не понял щас

**Comment by denver1000** [comment]
Нет спасибо

**Comment by AshtonFox** [comment]
Лор, кстати, нихуя не меняли по этому поводу, кроме высерка под названием "Backstory". Та же статья про кошек, например, до сих пор гласит, что их берут на парамедиков — и это вполне логично, ибо быстрые.

**Comment by TobyThorne** [comment]
![hahaha-no-meme-11](https://user-images.githubusercontent.com/45202681/50669075-147e3200-0f91-11e9-925e-75f939fa31a9.png)

**Comment by LegatePritcher** [comment]
Простите.

**Comment by AshtonFox** [comment]
ясно блять
