### ISSUE TITLE
Улучшение денежных транзакций

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3575]
### Улучшение
Данная идея пришла мне в голову из-за того, что даже торговцы не пользуются терминалом денежных транзакций, ВООБЩЕ никто его не использует. По моему мнению причиной этому является "сложность" настройки терминала денежных транзакций. Предлагаю сделать карты для мгновенной настройки терминалов денежных транзакций на нужный отдел.

### Решение
Сделать в каждом отделе карту которая при использовании ее на терминал денежных транзакций в одно движение настраивался условно на счет бара, добавить возможность распечатки чека о транзакции (Покупатель: Виталий Жопин, клоун. Оплатил товар ''банановый box в box". Уплачено 1337 тайлеров на счет научного отдела. Продавец: Валера Быдло, Ксеноархеолог.). 
Еще могу предложить сделать новую программу на консоли, ноутбуки, планшеты, через которую можно будет мониторить денежные переводы и покупки (Чтобы условный ИИ мог видеть что завхоз продает ассистентам электрошоковые тактические огнетушители), и распечатывать чеки для представления отчета начальству.

**Comment by Voldirs** [comment]
нормально работает этот ефтпос, даже инструкция игровая есть, интерфейс простой, просто игроки как говорится ниасилили

**Comment by Sudar0770** [comment]
> нормально работает этот ефтпос, даже инструкция игровая есть, интерфейс простой, просто игроки как говорится ниасилили

Вот про это я и говорю, я предлагаю его еще сильнее упростить

**Comment by MorJams** [comment]
фича в обход фиче-бота, который собирает по лайкам

но звучит хуёво, куда там упрощать-то лол. Хотите проще - просто просите наличку и выгоняйте всех карто-блядей, это называется РОЛЕПЛЕЙ-МОМЕНТ!

**Comment by Sudar0770** [comment]
Немного набрав мозгов в голове осознал что написал хуйню. Закрываю
