### ISSUE TITLE
Тактикульные модули для огнетушителя

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3577]
### Улучшение
Огнетушитель является самым доступным и в связи с этим популярным оружием. Предлагаю добавить для петушителя различные тактические модули.

### Решение
+ Добавить возможность подключить к огнетушителю батарею, капапатор, провода, скотч. По задумке после этого апгрейда вода из огнетушителя начнет бить током. От грейда капипатора будет зависеть урон током (От урона болью, до полноценного берн домага). Пользоваться только в изолированных перчатках!

+ Добавить возможность подключить к огнетушителю манипулятор, батарею, провода, скотч. Это увеличит мощность струи в зависимости от грейда манипулятора (от простого увеличения дальности струи, до стрельбы водяными проджектайлами опрокидывающими цель на землю).

+ Добавить возможность подключить в огнетушителю батарею, сканирующий модуль, скотч, бейкер. Это даст возможность распылять желаемые реагенты из огнетушителя. Количество доступных реагентов зависит от грейда сканирующего модуля (начиная с какой-нибудь фигни типа сахара, соли, заканчивая флешом, водокалием, термитом, пеной и т.д).
Разумеется от грейда батареи будет зависеть срок службы апгрейда (током без батареи бить не будет, манипулятор не будет нагнетать давление в огнетушителе, анализатор не будет синтезировать химикаты).
Возможно придумать еще кучу улучшений, но меня на данный момент хватило только на эти.

**Comment by Sudar0770** [comment]
Да всмысле WTF? На мой взгляд я все подробно описал

**Comment by Doster-d** [comment]
> Да всмысле WTF? На мой взгляд я все подробно описал

"WTF - What The Fuck
Все понятно, но ты ебнутый, какие модули на огнетушитель?"

Фича классная, геймдизайна не хватает.
