### ISSUE TITLE
Добавить Ассистента Бипски

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3581]
### Улучшение
Добавить в игру возможность собрать бюджетную версию Бипски

### Решение
Робототехник не может получить в бриге шлем и шоковую дубинку и решил сделать своего собственного бипски, но не офицера. Он собирает корпус, но вместо шлема СБ добавляет каску, вместо шоковой дубинки добавляет огнетушитель. Получается Ассистент Бипски, работает как его СБ аналог, но вместо наручников у него провода, а вместо оглушения током у него дизарм огнетушителем.

### (Опционально) Альтернативы
Опционально добавить бипски дальний бой в виде распыления воды в цель, чтобы та подскальзывалась

**Comment by MACTEP-ABATAP** [comment]
Пусть перемещаться будет по техам и гетто, попутно обшаривая всё и собирая предметы, которые будет использовать для улучшения себя. И он будет автоматически атаковать всех сотрудников СБ. :kek: А если серьёзно, да, такой бипски нужен.

**Comment by kemperhun** [comment]
Так суть как раз в том, чтобы доставать дубинку и каску, а иначе слишком просто собрать себе армию получится. Надо впихивать тогда какую-нибудь исследуемую плату. Или запасную карту капитана, че уж.

**Comment by Sudar0770** [comment]
> Так суть как раз в том, чтобы доставать дубинку и каску, а иначе слишком просто собрать себе армию получится. Надо впихивать тогда какую-нибудь исследуемую плату. Или запасную карту капитана, че уж.

Так это будет бюджетная версия бипски, его нужно балансить не ценой, а качеством

**Comment by MorJams** [comment]
фича в обход фиче-бота, который собирает по лайкам

но звучит весело

**Comment by Sudar0770** [comment]
Этот иссуй жив?

**Comment by DarkHunter7756** [comment]
Иссуи не могут умереть. Они живут до скончания оникса

**Comment by Doster-d** [comment]
> Пусть перемещаться будет по техам и гетто, попутно обшаривая всё и собирая предметы, которые будет использовать для улучшения себя. И он будет автоматически атаковать всех сотрудников СБ. :kek: А если серьёзно, да, такой бипски нужен.

Неиронично хочу такое накодить

**Comment by Sudar0770** [comment]
Емагнутный ассистент бипски по идее должен вести себя аналогично старшему брату

**Comment by Sudar0770** [comment]
Ещё можно добавить взаимные оскорбления офицера Бипски и ассистента Бипски когда они видят друг друга.
