### ISSUE TITLE
Полезные ископаемые под поверхностью астероида

### ISSUE THREAD

**Issue by KimihitoOld** [ChaoticOnyx/OnyxBay#360]
**Описание бага**
Все до боли в зубах просто : Нету минералов под землей на астероиде, уже как год вроде нету. 
Если добыча буром кажется простой и слишком имбалансной, то можно просто сделать добычу буром медленной. В общем, нету минералов под поверхностью астероида.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем глубинный сканер. Тот что синенький.
2. Выходим от базы чуть поодаль, ведь изначально 3-4 тайла от базы мертвая зона без минералов
3. Жмакаем на сканер.
4. Профит! Сканер показывает целое Н И Ч Е Г О под землей!

**Ожидаемое поведение**
Сканер должен был показать то или иное количество разных минералов под землей. Рандомно спавнящиеся каждый раунд

**Скриншоты**
http://prntscr.com/m3mq30 Вот скриншот, пожалуйста.

**Характеристики**
 - OS: [e.g. Windows/Linux, эмулятор] 
 - Версия клиента [смотрите в BYOND]
 - Версия сервера [команда "Show server revision" в вкладке ООС на сервере]
 - ID игры [там же]

**Дополнительня информация**
Он тута уже как месяцев восемь, а то и год.

**Comment by Penguineapig** [comment]
так правильно, ничего и не должно быть, в этом и суть старателей. Тебе с этим сканером нужно за 2 километра идти и там включать. 
Легкость добычи буром контрится отдалённостью этой добычи от шахтёрской базы.

**Comment by Voldirs** [comment]
Ээээээ. А там вообще-то всей карте ресурсов нету. Разве нет?

**Comment by Penguineapig** [comment]
Я без понятия, по описанию автор проверял только возле шахтерки.
_Вроде бы_ я в мае играл и находил

**Comment by Cinericius** [comment]
Посоны, я закрою, пушо аналогичное есть в прожекте по шахтерке.
