### ISSUE TITLE
Из вентиляции можно бросать предметы

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#3613]
Насколько я понял трейтор в костюме для лазания по вентиляции может из нее кидать предметы. Критический баг, если его абузят (что нарушает правила сервера, да).

см. ПР #3543

**Comment by Sudar0770** [comment]
Звучит логично если прямо из вента кидаешь

**Comment by Animesku** [comment]
Но не когда из труб

**Comment by dominoCaesar** [comment]
кто пофиксит тот не лох остальные лохи

**Comment by wadangel** [comment]
Поднимаю, потому что всё ещё актуально и довольно критично. Проблема не только в бросании вещей, если ты залезаешь прямо в вентиляцию и кидаешь барахло с того же тайла. Проблема в том, что ты кроме этого ещё и можешь активировать и подрывать разные вещи в карманах, которые будут работать прямо поверх трубы - на том тайле, на котором ты в ней находишься. В итоге можно ползать по трубам и фрагать гранатами бедных жертв.

А ещё костюм не спасает от давления. И это гачи-отсылка, что не есть хорошо. Лучше его переделать нормально без мемов, превратив в какой-нибудь латексный сьют с референсами к металгиру, а ещё добавить защиту.

![image](https://user-images.githubusercontent.com/29904082/123667227-6303a300-d853-11eb-84d7-ea9fd8ce7606.png)

**Comment by Oubifx** [comment]
> Поднимаю, потому что всё ещё актуально и довольно критично. Проблема не только в бросании вещей, если ты залезаешь прямо в вентиляцию и кидаешь барахло с того же тайла. Проблема в том, что ты кроме этого ещё и можешь активировать и подрывать разные вещи в карманах, которые будут работать прямо поверх трубы - на том тайле, на котором ты в ней находишься. В итоге можно ползать по трубам и фрагать гранатами бедных жертв.
> 
> А ещё костюм не спасает от давления. И это гачи-отсылка, что не есть хорошо. Лучше его переделать нормально без мемов, превратив в какой-нибудь латексный сьют с референсами к металгиру, а ещё добавить защиту.
> 
> ![image](https://user-images.githubusercontent.com/29904082/123667227-6303a300-d853-11eb-84d7-ea9fd8ce7606.png)

Звучит как фича, если при этом еще и разрушение трубы добавить на месте взрыва

**Comment by Zert0X** [comment]
> 
> 
> > Поднимаю, потому что всё ещё актуально и довольно критично. Проблема не только в бросании вещей, если ты залезаешь прямо в вентиляцию и кидаешь барахло с того же тайла. Проблема в том, что ты кроме этого ещё и можешь активировать и подрывать разные вещи в карманах, которые будут работать прямо поверх трубы - на том тайле, на котором ты в ней находишься. В итоге можно ползать по трубам и фрагать гранатами бедных жертв.
> > А ещё костюм не спасает от давления. И это гачи-отсылка, что не есть хорошо. Лучше его переделать нормально без мемов, превратив в какой-нибудь латексный сьют с референсами к металгиру, а ещё добавить защиту.
> > ![image](https://user-images.githubusercontent.com/29904082/123667227-6303a300-d853-11eb-84d7-ea9fd8ce7606.png)
> 
> Звучит как фича, если при этом еще и разрушение трубы добавить на месте взрыва

Звучит как баг ибо как ты из трубы под плиткой, выбросишь гранату? В таком случае надо гибать того кто додумался это сделать
