### ISSUE TITLE
Добавить ивент "Вторжение Магнитки"

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#3630]
### Улучшение
https://wiki.ss13.ru/index.php?title=Nova_Magnitka 
Согласно лору существуют космические коммунисты - республика нова магнитка. На данный момент ничего кроме наличия в лоре они не делают. Предлагаю добавить их в виде ивента
### Решение
Когда мы говорим про режим нюки, то обычно приходить в голову крайне быстрый слив, либо победа за 5-10 минут. В случае данного ивента цель - захват станции, реализовать предлагаю 20 минутным взломом коммуникаций станции, причём для начала необходимо оказаться в мостике. Из оружия скорее всего всё огнестрельное, можно добавить пушки уже имеющиеся в билде. Отличатся данный ивент будет большим требованием к населению станции 50+, 1/5 будет антагами. Возможно часть антагов будут в виде скрытых агентов, которые могут заняться саботажем до прибытия шаттла. Шаттл стыкуется непосредственно со станцией(место выбирается с консоли, как у торговцев). По снаряжению хуже, чем у нюки. Условие проигрыша, смерть 90% группы или провал взлома
### (Опционально) Альтернативы
Можно реализовать цель в полном подавлении службы безопасности и глав(не очень звучит)
Можно добавить спавн до двух дополнительных шаттлов при гибели 70% штурмотряда (госты смогут зайти, как в ерт или детсаде)
### (Опционально) Дополнительная информация
Я точно знаю, что существует множество спрайтов для обмундирования. Возможно есть спрайты для оружия

**Comment by ArmolitskiyCarpoeb** [comment]
У нас в билде даже калашей нет, какие коммуняки в космосе без ебанных калашей? Ну или САЙФАЙ калашей.

**Comment by Destrolaric** [comment]
> У нас в билде даже калашей нет, какие коммуняки в космосе без ебанных калашей? Ну или САЙФАЙ калашей.

Как я помню, в других есть, можно скомуниздить

**Comment by ArmolitskiyCarpoeb** [comment]
Закодить и нарисовать калаш легче простого. Но сколько времени будут его добавлять и добавят ли - вот в чем вопрос

**Comment by Destrolaric** [comment]
Тут почти всё можно вырвать из других частей кода

**Comment by HentaiStorm** [comment]
Мерки 2.0

**Comment by sweden-moose** [comment]
Звучит как еще один каэсочный режим
