### ISSUE TITLE
Добавить Нюке и предателям в аплинк инъекцию с синдикатовскими наномашинами.

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3639]
### Улучшение
Этот иссуй направлен на то, чтобы разнообразить режим нюки. Добавление в ряды трейторов и нюковцев боргов добавит новые тактики и новые ситуации как для нюки, так и для защитников станции. Разумеется у борга должен быть манипулятор для диска и взвода бомбы, встроенный пинпоинтер, различное оружие включая есворд чтобы ломать стены и двери, (у него не должно быть доступа по станции, иначе это будет имба), Гипоспрей с боевыми лекарствами типа гиперзина, оксикодона и трика) для оперативников, система самоуничтожения которую можно активировать будучи даже трупом (как у нинджи), Джетпак, и возможно что-то важное что я забыл(жду предложения в комменты).
Иногда Нюке дропается задание не на уничтожение, а на захват и убийство, предлагаю добавить нюко-боргам наручники.

### Что даст это улучшение
Увеличит популярность ионок у СБ 
Создаст массу смешных ситуаций где условный клоун посаженный в тюрьму резко превращается в вооруженную машину для убийств из-за того, что у него не проверили слот ушей, или где Завхоз создает армию роботов и захватывает станцию.
Даст нюке и трейторам шанс на вторую жизнь при сильных ранениях.
Позволит нюковцам пополнять свою численность на станции за счет экипажа (по моему мнению это лучше чем просто убивать бедных ассистентов, так они смогут поиграть и к тому-же пострелякаться с СБ, в частности с тупым Васей Пупкиным на офицере который посадил его за рисование на стене или м*даком на ХоСе который не захотел брать его на работу).

### Решение
Дать возможность Нюковцам и трейторам заказывать в аплинке инъекцию с синдикатовскими наномашинами, которые при введении в кровь гибают и превращают в Нюко-борга.

### (Опционально) Альтернативы
Добавить в аплинк нюковский позитронный мозг из которого собирается нюко-борг и добавить возможность нюковцам собрать на своей базе борга. Это моя изначальная задумка, но если нюка прилетит на 40 минуте игры с армией боргов, то будет уже не так весело, я отказался от этой идеи.

### (Опционально) Дополнительная информация
Не мне диктовать что деймдевам делать, но предложу сделать этим боргам простую перекраску в цвета нюки для узнаваемости экипажем угрозы.
Цена инъекции должна быть велика для баланса сил
Могу вместо высокой цены инъекции предложить ограниченное время жизни борга.

**Comment by ArmolitskiyCarpoeb** [comment]
Борги для нюкеров есть на ТГ.

**Comment by Sudar0770** [comment]
> Борги для нюкеров есть на ТГ.

Что такое ТГ?

**Comment by Kexilex** [comment]
Это все очень занимательно, но борг пососет от флешки и ионки ну очень глубоко. От флешки можно ещё какой-нибудь супернюка визор прилепить с термалами и защитой от вспышек, но в это слабо верится. Ионка уничтожит борга без шансов. 

Также что делать с доступом? Если будет полный доступ, то это какой-то кринге.

**Comment by Sudar0770** [comment]
> Это все очень занимательно, но борг пососет от флешки и ионки ну очень глубоко.

Так в этом и суть, нюковец меняет приемущества и слабости человека на приемущества и слабости борга.
> Также что делать с доступом? Если будет полный доступ, то это какой-то кринге

Разумеется полного доступа быть не должно и я предложил как решить эту проблему в самом иссуе

**Comment by Doster-d** [comment]
Уже есть синдикатосэвский борг, можно немного потрогать его и будет как в иссуе
