### ISSUE TITLE
При удушении кого-либо жертва может говорить и задыхается слишком громко.

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3663]
### Описание бага
Есть замечательная функция удушения которую я всегда считал идеальной для скрытных убийств, но когда я вырубил цель, утащил ее в теха и начал там душить, то весь сервер слышал звуки как тот задыхается, потом он пришел в себя и как ни в чем не бывало начал в общий канал докладывать кто, где и как его убивают.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем ассистента
2. Душим ассистента
3. Слышим звуки как он задыхается и рассказывает всем что его убивают
4. Видим как весь сервер сбегается на эти звуки

### Ожидаемое поведение
По моему мнению жертва не должна иметь возможность разговаривать при убивающем грабе на ней и не должна дышать вовсе(В этом же суть удушения)

**Comment by sweden-moose** [comment]
Фича

**Comment by Doster-d** [comment]
В чем проблема взять человека за рот? Тогда он не сможет ничего сказать. А со звуками, да, проблема.

**Comment by Sudar0770** [comment]
Уже не актуально
