### ISSUE TITLE
Новый ивент "охотничьи угодья Ятжа"

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3665]
### Улучшение
Добавить новый ивент под названием "Охота". Ятжа(Хищники из одноименного фильма, они же из вселенной в которой есть ксеноморфы) высокоразвитая раса собирающая трофеи с охоты на другие расы. Физически они очень сильны и выносливы, некоторые из них генетически модифицированы для боя. Отряд из трех ятжа состоит из опытного воителя и двух младших. Целью будет сбор черепов.
Обожают использовать оружие ближнего боя, но имеют наплечные плазменные пушки для ведения дальнего боя.
Свои технологии сохраняют ценой жизни, если в руки человека попадут технологии Ятжа, то вместо обычного сбора черепов это перерастет в геноцид станции. Если Ятжа терпит поражение, то он взводит сильнейшую взрывчатку способную неплохо порушить какой-нибудь отсек.
Любимой целью для охоты Ятжа являются ксеноморфы, поэтому при режиме ксеноморфов шанс паявления Ятжа значительно увеличивается (Если ксеноморфов починят)
Прилетают Ятжа ближе к середине игры т.к. нападать на не вооруженных членов экипажа которые еще не продвинулись в науке НЕ ПО ЧЕСТИ ВОИНА. Так же Ятжа не трогают тех, кто не может сражаться (инвалиды, старики, женщины)
Уважают силу, если их жертва проявила себя в бою, то высок шанс что они перестанут преследование и сразятся с ней на равных.

### Решение
Добавить новую расу и новый ивент связанный с этой расой.

**Comment by MACTEP-ABATAP** [comment]
Уже вижу лентяев которые хотят в роботу и отпиливают себе ногу

**Comment by Kexilex** [comment]
Режим похож на нюку ниндзь. Сетки, инвиз, самоуничтожение. Как противовес для какой-нибудь бяки типа генососы/вампиры может и подойдет, например, отправляется сигнал бедствия(вместо жалоб на цк лол, им не похуй что ли), но кто его поймает ерт или хищники(или клоуны душепоглощатели?)? Чужих у нас нет, а как fake ert выглядит более правдоподобно. 

> Уважают силу, если их жертва проявила себя в бою, то высок шанс что они перестанут преследование и сразятся с ней на равных.
Думаю, речь идет о мужестве

**Comment by Sudar0770** [comment]
> Режим похож на нюку ниндзь. Сетки, инвиз, самоуничтожение. Как противовес для какой-нибудь бяки типа генососы/вампиры может и подойдет, например, отправляется сигнал бедствия(вместо жалоб на цк лол, им не похуй что ли), но кто его поймает ерт или хищники(или клоуны душепоглощатели?)? Чужих у нас нет, а как fake ert выглядит более правдоподобно.


Слууууш, звучит гениально, вместо ЕРТ может прилететь режим на звуки битвы.... Я влюбился в эту идею. Тупо представляю себе ситуацию где генокрады загрызли станцию так сильно что остатки экипажа зовут ЕРТ, но прилетает отряд Ятжа и начинает резать генокрадов, просто супер!

**Comment by Kexilex** [comment]
Ну идея не моя, такое есть на святых tgmc. При красном коде можно посылать сигнал бедствия, который тригерит спавн ерт, или сектоидов, мимохуев пиратов типа, или ксеноЕРТ(просто пополняет ряды ксеноморфов).

**Comment by Kexilex** [comment]
С сигналом бедствия вообще можно много чего интересного придумать. Например, станция ловит сигнал бедствия и может отправить туда шаттл с юными натуралистами и добровольцами. Шаттл отправляется на дереликт(из пула нескольких дереликтов) с заспавненным из гостов чем-то(вампир? клоун-генокрад? засада ~~джокера~~ синдиката?)

**Comment by Kexilex** [comment]
Вот бы скучного ниндзю заменить на веселого хищника..
