### ISSUE TITLE
Гунчат вызывает лаги на клиенте при быстром выводе множества сообщений

### ISSUE THREAD

**Issue by ucnaHez** [ChaoticOnyx/OnyxBay#3680]
По просьбам эпикуса открывается иссуй.

Гунчат вызывает лаги на клиенте. Когда в чат выводится много сообщений подряд - клиент виснет, виснет собственно игровое окно, где все рисуется, и сообщения так методично тык-тык-тык выводятся в чат. Звуки идут. Когда вся пачка сообщений проходит - игра развисает, только ты к этому времени уже убит.

Вопроизведение? Легко. Экзамайн? Лаг клиента. Кликнуть себя на хелпе? Лаг клиента побольше и уже заметный. Устроить перестрелку, где быстро стреляют человека четыре? Держи провисание клиента до конца перестрелки.

Еще у меня иногда экзамайн, прогружая иконки на каждом предмете, роняет дримсикер, но не уверен, что это связано.

В мае, когда еще не было юникода, я отключал гунчат через ПШШ, и описанные лаги пропадали

И да, проблема есть не у всех, но тех, у кого есть - ставит в плохое положение. Лаг сервера тормозит всех, лаг клиента тормозит только тебя, с понятным результатом.

**Comment by Kexilex** [comment]
#3105 та же проблема

**Comment by Sudar0770** [comment]
Ага, а блудшарды мага вообще выключают дримсикер у того, в кого он попал, я думал это фича такая

**Comment by Tsurupeta** [comment]
Встретил человека с пистолетом пулемётом - он по мне кликнул и я завис на 10 секунд. Отвис уже трупом. Гениально. ВОт бы ещё понять, у кого этих лагов нет и почему.

**Comment by Kexilex** [comment]
Люди жаловались и больше года назад, в ноябре появился багрепорт по требованию мистера Э. Иссуй в приоритете, ту би континьед.

**Comment by Tsurupeta** [comment]
Я у себя эту хуйню починил просто обновив джаву. Ну или "скачав". https://www.java.com/en/download/

**Comment by ucnaHez** [comment]
Че клозед че клозед

Непонятный серверсайд фикс, в приложенных видео разницы особо не видно

**Comment by Vallat** [comment]
А разницы и нет, открывать снова надо. Проблема не решена, решается она иначе и более сложным методом. Не понимаю аппрува ПРа

**Comment by HentaiStorm** [comment]
Сервер еще не ребутали. Публичные тесты покажут эффективность.

**Comment by igorsaux** [comment]
Похоже, решено в тгчате #5486

**Comment by metaludw** [comment]
> Похоже, решено в тгчате #5486

Почему у меня с сервера тг чат не скачивает?
Выдает ошибку: failed to load fancy chat, click HERE to attemp to reload it. 
Но HERE не прокликивается
