### ISSUE TITLE
Добавить неинвазивное заживление костей

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#3691]
### Улучшение
На данный момент хирургия заполнена случаями челиков с поломанными костями. Но в реальной жизни большинство переломов лечиться без участия хирурга. Плюс это сделает **i never asked for this** жестянок менее привлекательными
### Решение
 Учитывая, что мы находимся в будущем, предлагаю добавить дополнительные способы лечения 
Из примеров:
Аналог гипса, вылечивающий конечность за 5-7 минут игрового времени
Препарат, вероятно тяжелый в варке, но доступный химику.(выдать его антагам в аптечки)
Натуральное лечение с вероятностью дебаффа на конечность (15 минут)
### (Опционально) Альтернативы
Разделить переломы на открытые и закрытые, первые будут возможны в лечении только хирургом

**Comment by Sudar0770** [comment]
Это ах*уенная идея, мне тоже не нравится что переломы обязательно лечатся в операционке. Пусть кости сами восстанавливаются, гипс тогда станет невероятно популярен.

**Comment by MrMagick2104** [comment]
Разве гипсы, которые уже есть, не лечат переломы?

**Comment by Sudar0770** [comment]
> Разве гипсы, которые уже есть, не лечат переломы?

Они позволяют использовать конечность, но ничего не лечат.

**Comment by SlippyMitch** [comment]
Не забывайте про гетто сплинты, которые делаются из арматуры+скотч, мне кажется они должны лечит помедленнее, все же это является аналогом гипса

**Comment by kcalbCube** [comment]
Операция по излечению перелома занимает от силы полторы минуты. Необходимо делать инвазивный метод лечения переломов очень сложным, но тут есть проблема - лечение органов в груди и черепе требует нанесения перелома и его лечения. Если их лечение будет затруднительным, то все будет очень хреново. Да и вообще не сильно нравится идея что можно фиксером любой орган вылечить. Если делать переломы вариативнее, то нужно выпиливать всю систему к хренам собачим и заменять более длительным лечением. Это было бы конечно очень круто, но кому это надо?

**Comment by Shabat-Sholom** [comment]
Помню, мифы ходили, что молоко кости лечит. Пора реализовывать?

**Comment by kcalbCube** [comment]
> Помню, мифы ходили, что молоко кости лечит. Пора реализовывать?

Ну... скорее коэффицент регенерации костей, увеличивающийся молоком и еще чем-то..

**Comment by Sudar0770** [comment]
> Помню, мифы ходили, что молоко кости лечит. Пора реализовывать?

Отлично, теперь химики будут выводить кальций из молока, смешивать его с условным углеродом и получать лекарство для регена костей.

**Comment by kcalbCube** [comment]
> > Помню, мифы ходили, что молоко кости лечит. Пора реализовывать?
> 
> Отлично, теперь химики будут выводить кальций из молока, смешивать его с условным углеродом и получать лекарство для регена костей.

Ограниченно и очень быстро. В стиле Space Station!

**Comment by kcalbCube** [comment]
Только это скорее быстрое заживление(в стиле перидаксона) или медленное?

**Comment by Sudar0770** [comment]
> Только это скорее быстрое заживление(в стиле перидаксона) или медленное?

Ну пусть будет медленно, но если смешать с клонексадоном, то быстро

**Comment by Sudar0770** [comment]
И еще один вопрос, ящеры будут быстрее регенить свои кости чем люди?

**Comment by kcalbCube** [comment]
Так. Какие примерно лекарства? Одного будет достаточно? Тогда какие будут полочки, овердозы?

На данный момент из молока получается кальций, из кальция некоторые лекарства : кальциксон -  действующий подобно перидаксону, но для костей и... Все?

**Comment by Sudar0770** [comment]
> Так. Какие примерно лекарства? Одного будет достаточно? Тогда какие будут побочки, овердозы?
> 
> На данный момент из молока получается кальций, из кальция некоторые лекарства : кальциксон - действующий подобно перидаксону, но для костей и... Все?

Могу еще предложить яды на основе кальция которые наносят вред костям
