### ISSUE TITLE
Добавить в раздатчики мед. отдела банки с глюкозой.

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3708]
### Улучшение
Мой перфекционизм наносит мне много брейндомага когда я отпускаю пациента здоровым но со статусом сильного голодания, хочу обкалывать людей глюкозой!

### Решение
Добавить банки с глюкозой в раздатчики меда.

### (Опционально) Альтернативы
Можно еще добавить банки с протеином чтобы лечить Е*УЧИХ ЯЩЕРОВ! ОНИ ГНИЮТ КАК *******!!!

**Comment by Sudar0770** [comment]
Знаю что глюкоза имеется в медицинком РИГе, но его пусть носят парамедики.

**Comment by Sudar0770** [comment]
Так же глюкоза имеется у продвинутой хирургической модели киборгов.

**Comment by kcalbCube** [comment]
Если ты не знал, можно вкалывать сахар(есть в раздатчике у химиков). Тот же самый эффект.

**Comment by kcalbCube** [comment]
Но в целом да, иметь нормальную глюкозу будет лучше.

**Comment by Sudar0770** [comment]
Глюкозу принялись добавлять, но не докодили. Что произошло?
