### ISSUE TITLE
От кастомизированных мехов остаются обломки обычных

### ISSUE THREAD

**Issue by PlinHost** [ChaoticOnyx/OnyxBay#371]
**Описание бага**
Сабж.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Открываем код мехов
2. Думаем

либо (не пробовал)
1. Кастомизируем меха
2. Ломаем

**Ожидаемое поведение**
Обломки должны быть кастомизированного меха, спрайты есть.

**Характеристики**
 В релизе сейчас короче.

***Дополнитель*ня *информация***
~Я забыл пофиксить шаблон багрепорта.~ Какие-то нехорошие люди закрыли #330.

**Comment by denver1000** [comment]
Да пони я, пони...добреду до работы во вторник и пофиксю!

**Comment by PlinHost** [comment]
Ну это чтобы не потерялось, тот иссуй же закрыли.

**Comment by Cinericius** [comment]
@denver1000 и как оно?
