### ISSUE TITLE
Баг с bluespace cell.

### ISSUE THREAD

**Issue by spacecarp** [ChaoticOnyx/OnyxBay#372]
**Описание бага**
Когда создается bluespace cell из exosuit fabricator, получается 2 батареи. Одна заряженная, вторая разряженная.

**Воспроизведение**
1. Заходим в интерфейс exosuit fabricator
2. Создаем bluespace cell
3. Получаем две батареи (заряженная и разряженная)
4. ???

**Ожидаемое поведение**
Логично, должна была появится только одна батарея, разряженная, полагаю.

**Характеристики**
 - OS: Windows 7
 - Версия клиента: 512.1462
 - Client Version: 512
 - Server Revision: 700ef5b9dda9d9661843641ea6d7b86c586e3195 - release - 2019-01-09
 - Game ID: bYh-dgyk

**Comment by ZerlGray** [comment]
Это две батарейки. Одна из них, находясь в заряднике, заряжает другую. В этом их суть.
