### ISSUE TITLE
Изучение странной биоструктуры. Генокрады производства НаноТрайзен.

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3721]
### Улучшение
Во время режима "генокрады" можно раздобыть биомассу этих самых генокрадов и изучить ее, если не ошибаюсь, то в ней содержится 10 биологии и 10 нелегальщины. Технологии биологии выше 6 уровня не существуют. Предлагаю добавить в протолат сыворотку генокрада которая будет требовать условно 8 биологии и 5 нелегальщины. Сыворотка "убивает" носителя и выращивает в его теле нового генокрада без обжективов. Новорожденный генокрад будет иметь память и манеры тела в котором он появился.

### Почему мой иссуй имеет право на жизнь
1) Сейчас исследовать биоструктуру имеет смысл только ради нелегальщины, 10 уровень биологии не оправдан. Можно исправить это.
2) На вики имеется намек что вероятно генокрадов посылает на задание Синдикат. Следовательно если генокрадов изучить, то можно создавать своих.
3) Вживление сыворотки в трупы будет давать гостам дополнительную возможность принять участие в раунде.
4)Ручные НаноТрайзеновские генокрады серьезно расширят игру, будет множество кековых и кринжовых ситуаций каких ранее небыло.

### Решение
Добавить генокрадский(ую) сыворотку/имплант использование которого превращает в генокрада без обжектива.

### Опционально
Вероятно ученые будут создавать живые клетки генокрада и отдавать их ксенобиологам. Те в свою очередь будут выращивать, воспитывать и дрессировать маленьких ''пузожителей'', и уже после этого вживлять их в тело трупа, ССДшника, обезьяны и прочее.

**Comment by Doster-d** [comment]
Уже есть, выйди со мной на связь в дискорде, я объясню как получить, то что ты хочешь.
