### ISSUE TITLE
Спонтанно исчезают слоты персонажей

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#3726]
### Описание бага
Время от времени кол-во слотов сокращается с 15 до 10 на некоторое время (от одного раунда до пары дней), потом они возвращаются без изменений. Иногда персонажи спонтанно заменяются на других, которые были раньше в соответствующем слоте, иногда часть слотов стирается вовсе и потом так же спонтанно возвращается. Где-то в октябре (13 октября, насколько я понял по моим поискам ключевых фраз в канале трансляции ООС) этого года у меня вообще все персонажи стёрлись начисто и без возвращения, с тех пор это говно прекратилось, но вот сегодня снова возникло исчезновение последних пяти слотов. Причём это, похоже, не только у меня, а ещё и у минимум одного человека (@Ershovdi ) в начале того же раунда они исчезли.

### Воспроизведение
Я не знаю как. Моё единственное наблюдение - иногда это происходит после того, как отыгрываю раунд за персонажа, за которого долго не играл.

### Ожидаемое поведение
Ну неправильно это всё, не должно так быть, ролеплеить мешает.

### (Опционально) Дополнительная информация
Game ID: 
b95-coeK
(не знаю, поможет ли, но на всякий пожарный - раунд, в лобби которого у меня исчезли последние пять слотов, на момент написания они не вернулись)
Искренне извиняюсь, если дубликат, но жопа немного подгорает от этого и не хочу рыться в 1200 иссуях.

**Comment by Sudar0770** [comment]
У меня вообще разок стерлись все слоты

**Comment by Ershovdi** [comment]
Заметил ещё штуку. Буквально сегодня днем делал себе персонажа, добавил там лодаут, рекордсы, все дела. Все это я поменял на уже созданном персонаже. Ну, захожу через раунда два-три, а мой персонаж откатился на его изначальную версию. Перезаход или начало нового раунда не помогло. Пришлось снова все переделывать.

**Comment by TimErmolt** [comment]
В какой-то момент этот ебучий случай перестал появляться и воспроизводиться. Последние задокументированные на гитхабе случаи датируются весной 2021 -- наверное, что-то в базах данных починили с тех пор, и оно убило этот баг. Пока что закрою иссуй, но если возникнет вновь -- открою заново.
