### ISSUE TITLE
Суккумб для мыши.

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#3736]
Иногда мышки появляются в техах без вентиляционной системы и оттуда просто невозможно выбраться, а значит - бесконечное мышиное житие без возможности коммуникации и т.д. и т.п. Педалей часто не бывает.

Решение - дать мышкам команду succumb. Или вообще поставить эту команду во вкладу IC/OOC, чтобы не надо было в строчку писать.

**Comment by sweden-moose** [comment]
Если чо, можно гостануться из мыши

**Comment by Ershovdi** [comment]
А.
