### ISSUE TITLE
Добавить срабатывание флеша при метании.

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#3745]
### Улучшение
Много раз представлял себе что если не аккуратно бросить флеш, то он приземлится на кнопку и сработает, предлагаю воплотить эту маленькую мелочь в жизнь. Если флеш при броске попадет в стену, на пол, в мебель, во что угодно, то сработает как при использовании флеша в руке и незначительно ослепит всех в радиусе. (привет любителям забывать тазеры и кидаться станбатонами в убегающих)

### Решение
Добавить срабатывание флеша при броске.

**Comment by sweden-moose** [comment]
> Если флеш при броске попадет в человека, то сработает как при нажатии таргетного применения

Ты типа прям в глаза кидаешь?

**Comment by Sudar0770** [comment]
> Ты типа прям в глаза кидаешь?

Дыа :D

**Comment by Sudar0770** [comment]
> > Если флеш при броске попадет в человека, то сработает как при нажатии таргетного применения
> 
> Ты типа прям в глаза кидаешь?

Я подумОл и решил что да... не нужно кидать прямо в глаза.
