### ISSUE TITLE
Добавить возможность держать предметы лёжа

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#3748]
### Улучшение
В текущей сборке билда опуха падение в 99% случаев означает - гроб, могила. Но мы понимаем, что это А) не реалистично. Б)Превращает игру в поиск мыла или другого предмета, который роняет. В) Превращает упавшего в беззащитного овоща, которого можно добивать
### Решение
Оставляем, что спейсмен роняет свои предметы, когда падает. Однако он имеет возможность их подобрать, дополнительно он может взять предмет из инвентаря. Стрельба так же будет доступна. При rest, человечек терять предметы не будет
### (Опционально) Альтернативы
Возможно запретить доступ к рюкзаку, когда в упавшем состоянии
### (Опционально) Дополнительная информация
Механика есть на тг, поэтому место копипаста нам известно

**Comment by Sudar0770** [comment]
Нокнуть человека можно если ты хорошо подготовлен или если цель плохо подготовлена. Я считаю что ронять предметы при падении честно. Мне тоже кажется что если человек ложится на землю самостоятельно, то предметы из рук выпадать не должны, но чет мне чудится что что игра не стоит свеч, фича не стоит кодинга.

**Comment by Destrolaric** [comment]
@Sudar0770 А вот если реализовать передвижение в упавшем(без перетягивания иконки, а через основное) будет полное тг
