### ISSUE TITLE
Добавить урон взрывающейся сигарете

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#38]
Взрывающаяся сигарета вызывает слабый взрыв, который не наносит урон. Нужно добавить дополнительный урон конкретно для лица или руки.

Может быть можно как-то добавить этот код не самой сигарете, а конкретно эффекту взрыва химической реакции, который там вызывается. Лучше было бы, конечно, так, но надо смотреть.

**Comment by Epicus7** [comment]
Хочется, чтобы после взрыва сигареты с плазмой или нитроглицерином лицо становилось неузнаваемым. Топливо для этих целей слабовато должно быть.

**Comment by Cinericius** [comment]
Вроде есть
