### ISSUE TITLE
какая-то хуйня если пиздить попугая на харме

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#3804]
что значит мне бросить нечего и почему по два сообщения

![зоражение](https://user-images.githubusercontent.com/48761132/100363045-40838000-300d-11eb-88ff-2062ac31a2af.png)

**Comment by sweden-moose** [comment]
Ты зачем попуга мучаешь.....

**Comment by TapKo4eB** [comment]
он меня заебал

**Comment by TapKo4eB** [comment]
![изображение](https://user-images.githubusercontent.com/48761132/100363803-4cbc0d00-300e-11eb-8b66-700b9b66ee9e.png)
я на сто процентов уверен что сообщение высирается чисто из-за того что тут какого-то хуя лежит usr а не src
