### ISSUE TITLE
Добавить огурцы

### ISSUE THREAD

**Issue by sweden-moose** [ChaoticOnyx/OnyxBay#3811]
### Улучшение
Добавить огурцы

### Решение
Добавить огурцы с мутациями

### Дополнительная информация
Добавить огурцы с мутациями, реализую сам.

**Comment by Ruforce** [comment]
фрактал кукумбер 
![image](https://user-images.githubusercontent.com/34314865/100447420-9c0f4580-30c1-11eb-87b7-b42a66fc64e8.png)

**Comment by sweden-moose** [comment]
Не нашел готового спрайта, по трупам
