### ISSUE TITLE
аи-контроллед симпл энимал не наносят ламга

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#382]
?????ядебил и не допилсал

**Comment by Ruforce** [comment]
https://github.com/ChaoticOnyx/OnyxBay/blob/dev/code/modules/mob/living/simple_animal/hostile/hostile.dm#L150

сюда допишите environment_smash

**Comment by PlinHost** [comment]
дописал не благодари

**Comment by Ruforce** [comment]
должно заработать я надеюсь
