### ISSUE TITLE
У Слаймо-людей нету спрайтов волос.

### ISSUE THREAD

**Issue by Jhonas25** [ChaoticOnyx/OnyxBay#383]
**Описание бага**
И так, вот наконец-то повысили шанс трансформации в прометеев, но после пары минут перебывания в состоянии прометея, я понял, что СПРАЙТИКОВ ВОЛОС В ВЫБОРЕ, таки, НЕТУ.
**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Становимся прометеем при помощи зелёного слайм экстракта
2. Чекаем во  вкладочке Ability кнопку(Сук, не помню как называется), вроде, Change hair.
3. Дальше идёт эмоут на появление волос, но менюшка с выбором не появляется.

**Ожидаемое поведение**
Я, подозреваю, что в прометеях в выборе прометея просто нету волос, так-же и у других возможных для трансформации рас, то-есть у скреллов не будет щупалец на выбор.

**Дополнительная информация**
И да, благодарю за понижение смертоносности мутационного токсина в прометея, думаю этой информации достаточно для выводов.

**Comment by TobyThorne** [comment]
Забавно, но бафф слаймтоксина ещё не завезли. Просто больше повезло. 

А по сабжу, для прометеанцев тупо нет причёсок. Надо будет нарисовать какие-нибудь тентакли, как руки дойдут.

**Comment by LLIkolnik** [comment]
Зачем рисовать когда можно спиздить с парадайзов или ещё какой фуррихерни по типу вора

**Comment by Epicus7** [comment]
Нужны ли вообще прически? И сами слаймолюди нужны?

**Comment by Cinericius** [comment]
Слаймолюди нужны - это фича слаймоэкстрактов.

А вот на прически можно и хуй положить.

**Comment by Cinericius** [comment]
А давайте попробуем (хуй положить)
