### ISSUE TITLE
У вампиров удаляются вербы после использования

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#3842]
Второй раз использовать верб не получается, так как удалился.

Вынесено отдельно из #3841

**Comment by Andromedasss** [comment]
Они удаляются и появляются через некоторое время, так и должно быть, да, можно поднять вопрос корректировки длительности перезарядок, но это уже другое дело.

**Comment by Doster-d** [comment]
@Andromedasss Вы же в курсе, что если моб будет в чем-то (ящик, например), то он не сможет получить свои вербы? Такая проблема была у генокрадов.

**Comment by Epicus7** [comment]
Блет, я забыл про эту фигню.

**Comment by Epicus7** [comment]
Вот он иссуй с генокрадами: #1575. Действительно, если моб не находится на карте, то ему не добавляются вербы.

Интересно, а как это было сделано на ВГ? Там тоже вербы удаляются-добавляются?
