### ISSUE TITLE
У вампиров не вернутся вербы, если он сидит в шкафу

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#3858]
Баг бьонда: http://www.byond.com/forum/post/1833666

Вербы не добавляются к мобу, если он не находится на карте, а находится, например, в шкафу. У вампиров как раз вербы удаляются-возвращаются.

Из баги #3842 стало понятно, что это вызовет проблемы у вампиров. Надо бы пофиксить.

**Comment by Epicus7** [comment]
На ВГ то как было сделано? Там такой же баг?

**Comment by Epicus7** [comment]
> Сделать кулдаун с проверкой в самом вербе, как у тех же визардов спеллы сделаны. У них даже кнопки есть в отдельной менюшке, по которым визуально кулдаун видно, так что ничего не удаляется никуда.

Как вариант.

**Comment by kcalbCube** [comment]
Так че бы не сделать общий интерфейс для абилитис и пихать его повсюду?

**Comment by alexred2002** [comment]
> 
> 
> Так че бы не сделать общий интерфейс для абилитис и пихать его повсюду?

Согласен, это бы и генкам пригодилось. Заменить немного неочевидный индикатор химикатов во вкладке статуса(когда способности в отдельной вкладке)

**Comment by Epicus7** [comment]
> Так че бы не сделать общий интерфейс для абилитис и пихать его повсюду?

Есть уже, у магов. Но там ужасный говнокод и вообще старый код очень. У ТГшников есть апгрейд системы абилитис удобный с иконками в интерфейсе и прочими плюшками. Его бы в идеале перенести и дальше юзать везде

**Comment by Zert0X** [comment]
Облазил все шкафы на станции, ни разу не пропали вёрбы, видимо починили заодно с генокрадами

**Comment by O0oMaximo0O** [comment]
Так, я не понял, если замержено, то почему ещё открыт?

**Comment by Zert0X** [comment]
Потому что баг ещё остался
