### ISSUE TITLE
Забрать у вампиров костыли и дать им ноги

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#3859]
Убрать кукожную систему перезарядки способностей через удаление-выдачу вербов. Сделать кулдаун с проверкой в самом вербе, как у тех же визардов спеллы сделаны. У них даже кнопки есть в отдельной менюшке, по которым визуально кулдаун видно, так что ничего не удаляется никуда. 

Позволит пофиксить #3858 и другие возможные проблемы.

**Comment by Epicus7** [comment]
Дубликат
