### ISSUE TITLE
Сломанные книги в библиотеке

### ISSUE THREAD

**Issue by P00TiZ** [ChaoticOnyx/OnyxBay#392]
**Описание бага**
Книги из библиотеки - нечитаемые (кроме тех, что на английском)

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем любую книгу из библиотеки
2. Открываем её

**Ожидаемое поведение**
Нормальный текст

**Характеристики**
 - OS: Windows 10
 - Версия клиента 512.1463
 - Версия сервера 512
 - ID игры bYz-cA2R

**Comment by Megmeehey** [comment]
Требует чистки БД, возможно починки кодировки, в которой сохраняются книги.
