### ISSUE TITLE
full body prothesis buff

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#3931]
Под баффом синтов я подразумеваю изменение эффектов от попадания ионкой по синтетическому игроку. Сейчас есть все шансы ваншотнуть обычного синта хорошей такой ионкой по башке, просто гиб головы мгновенный. Я же предлагаю эту штуку реворкнуть.

Ну, например. Сделать синто-органам такой урон, который будет понижаться только от электромагнитного воздействия. Первое попадание ионкой наложит на синта эффект пьяницы, игрок не сможет контроллировать свою ходьбу, из рук будут выпадать предметы (которые все же можно поднять); второе попадание просто уронит синта, после чего его можно связать или продолжить застреливать из ионки, с каждым разом повышая шанс гиба той или иной конечности (включая мозг).

Таким образом игра за синтов станет чу-уть более приятной. Чисто теоретически, если в каждом раунде люди будут использовать ионное оружие, то все синты станут умирать в первые двадцать минут раунда. Ну, там уже на усмотрение ЛЮБИМЫХ геймдизайнеров. Если надо будет, могу доработать/переработать идею.

**Comment by sweden-moose** [comment]
У вас дубликат #2825
