### ISSUE TITLE
Компоненты для R-UST в карго

### ISSUE THREAD

**Issue by PleaseJustEndMyPain** [ChaoticOnyx/OnyxBay#3944]
Улучшение.

 Добавить ядро, инжектор топлива и платы в карго. При этом поставить такие цены, чтобы быстрее было исследовать, а не заказать в карго вышеуказанные компоненты. 

Альтернативно можно уменьшить уровень требуемых технологий для создания вышеуказанных вещей, облегчив сборку. 

У нас есть возможность собрать СМ и сингу с нуля из карго, но R-UST мы собрать не можем. При том, что двигатель выдаёт меньше, чем та же СМ при должной настройке.

**Comment by Doster-d** [comment]
Вы сначало закончите ее, а потом уже добавляйте.

**Comment by PleaseJustEndMyPain** [comment]
Хорошо, отложим до отладки двигателя.
