### ISSUE TITLE
Запилить и добавить на карту односторонние стекла

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#3948]
### Описание бага
пикрелейтед
![ss13aaatemp](https://user-images.githubusercontent.com/60045066/101814930-d8b25680-3b2f-11eb-86b9-f9820e134aa3.png)
(снятие термал очков не помогло, другие люди, входившие сюда, так же не видели)

**Comment by vsss412** [comment]
Нету больше таких стёкол.

**Comment by vsss412** [comment]
Мне передали что такие стёкла есть. Будем смотреть.
