### ISSUE TITLE
Тоби въебал отличный ПР, одобряю! 

### ISSUE THREAD

**Issue by TerraViJa** [ChaoticOnyx/OnyxBay#4009]
### Улучшение
Теперь в Лоддауте Безпальцевые Берцы и Рабочие ботинки могут брать только Таяре и Унатхи. Есть проблема. Таяре не могут в раундстарт СБ и инженеров, а Унатхи не могут в инженеров. Внимание, вопрос. Нахуя тогда было добавлять такие ограничения? Я, как игрок за ксенорасу, требую вернуть возможность брать безпальцевую обувь. Если не хотите, то расширить им выбор профессий на данные отрасли. Иначе это уже говно какой-то.

### Личные пожелания
Отобрать у Тоби возможность изменять билд?

**Comment by Judge1987** [comment]
Не могу не поддержать этот иссуй всецело и всеобъемлюще, ибо с каждым апдейтом какое-то говно прибавляется.

**Comment by sweden-moose** [comment]
Пофиксили
