### ISSUE TITLE
Инвалидность

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#402]
Ваш соляр-инвалид удалил у чейнджей абилку infest, которая позволяла маленьким чейнджам заползать в других людей, оставив при этом абилку с долгим станом - paralyse, никак ее не меняя.
Найс разработочка.
Просто хлопаю.
Смотреть тут: https://github.com/ChaoticOnyx/OnyxBay/commit/ca40c708ebe40ed99d4724e5ccb775c71e75524f

**Comment by Cinericius** [comment]
Батя обещал, батя сделал #408
