### ISSUE TITLE
Добавить научные очки за исследования

### ISSUE THREAD

**Issue by sweden-moose** [ChaoticOnyx/OnyxBay#4058]
Текущие виды исследований заменяются на одноименные Научные Очки(TM), или, которые получаются путем разбора предметов на деструктив анализаторе, получать мы будем тем больше очков, чем есть в предмете уровней Научных Очков(на данном этапе - прошлые уровни исследований, растущие по логарифмической шкале, например, SP(Science Points) = `2^(ITEM_LEVEL)*10*k`, где k - коэффицент эффективности изучения предмета, распределенный по трем возможным итерациям исследования предмета следующим образом: 0.5-0.3-0.2. Дальнейшие итерации исследования предмета SP приносить не будут. Таким образом, исследовав предмет три раза, мы полностью его изучим и дальнейшего интереса для науки тот представлять не будет.

**Comment by kemperhun** [comment]
А это вообще реализуется в отрыве от #4059? Это кто-нибудь реализует этот иссуй, а потом мы два года не сможем выкатить обнову, чтобы предметы первого левела не давали 2^1*10*0.5=10(!) уровень технологии (Если оно вообще скомпилируется). Может, таки объединить?

**Comment by sweden-moose** [comment]
Сначало бы просто реализовать систему получения очков, пусть даже они будут не юзабельны в игре.

**Comment by sweden-moose** [comment]
2^10 * 0.5 = 10 (32) очков, с уровнями исследований это никак не связано.
> Стоимость технологии определяется в зависимости от того, на каком Уровне(Tier) находится технология, растет так же - логарифмически, например, 10*2^(TIER)

**Comment by Destrolaric** [comment]
Взрыв лимиток в зачёт берём? Слаймы? Ботаника?

**Comment by sweden-moose** [comment]
#4060

**Comment by Doster-d** [comment]
В идеале реализовать совместно с #4059 , так по моему мнению, будет проще.

**Comment by Shootnik01** [comment]
Че, как у вас там дела?

**Comment by kcalbCube** [comment]
> Че, как у вас тут дела?

Это просто дождь

**Comment by MACTEP-ABATAP** [comment]
Так обед же.

**Comment by Destrolaric** [comment]
bounty назначьте запилим за день.

**Comment by MACTEP-ABATAP** [comment]
> bounty назначьте запилим за день.
> 

За ваши головы?

**Comment by Doster-d** [comment]
> bounty назначьте запилим за день.

![bounty](https://user-images.githubusercontent.com/51989098/106366439-7a8e3c80-6344-11eb-9e91-9dd8ef873a9e.jpg)

**Comment by Shootnik01** [comment]
:\

**Comment by kcalbCube** [comment]
А го

**Comment by kcalbCube** [comment]
Кубик готов к работе и уже печатает план работ. Ожидайте 3-6 рабочих недель

**Comment by Shootnik01** [comment]
Кубику - лайк и уважение жителей Попуха

**Comment by kcalbCube** [comment]
@sweden-moose Хочу прояснить. То есть вместо всех направлений исследований, которые есть сейчас, мы впиливаем просто одно направление исчисляющееся в очках? Или как.

**Comment by Doster-d** [comment]
> @sweden-moose Хочу прояснить. То есть вместо всех направлений исследований, которые есть сейчас, мы впиливаем просто одно направление исчисляющееся в очках? Или как.

Я это понимаю так: есть глобальные очки, а есть очки направлений, при изучении datuma с вещами тратятся очки направления, если их не хватает идет конвертация глобальных очков с умножением на коэффицент количество изученных датумов / 1.

**Comment by kcalbCube** [comment]
> > @sweden-moose Хочу прояснить. То есть вместо всех направлений исследований, которые есть сейчас, мы впиливаем просто одно направление исчисляющееся в очках? Или как.
> 
> Я это понимаю так: есть глобальные очки, а есть очки направлений, при изучении datuma с вещами тратятся очки направления, если их не хватает идет конвертация глобальных очков с умножением на коэффицент количество изученных датумов / 1.

> Сначало бы просто реализовать систему получения очков, пусть даже они будут не юзабельны в игре.

Значит направления оставляем, добавляем очки направлений и глобальные очки. А остальное не трогаем до #4059 ?
