### ISSUE TITLE
Сохраните вымирающий вид рельс.

### ISSUE THREAD

**Issue by Jhonas25** [ChaoticOnyx/OnyxBay#406]
**Описание бага**
Рельса  из РнД сломана.
**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Крафтим рельсу в РнД
2. Достаём катридж с материей из рельсы
3. Тыкаем отвёрткой.
3. Находим то, что тебя наебали и ни батарейки, ни конденсатора нельзя заменить.
4. Итог, спасибо за сломанную рельсу.

**Ожидаемое поведение**
Будет возможность доставать батарейку и конденсатор с возможностью заменить их.

**Дополнительная информация**
Так-же, хотел сказать то, что армор пирсинг не играет роли из-за вашей системы рикошетов, проявите акт милосердия перед рельсой, плез.

**Comment by HalilDaBlack** [comment]
Пенетрейт и армор пирсинг - разные вещи

**Comment by LLIkolnik** [comment]
Небагафича, кстати.
