### ISSUE TITLE
Добавить больше образцов вирусов в морозилку вирусологии.

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#4070]
Сейчас вирусов всего 5 в морозилке, крайне малы шансы получить хороший вирус, который бы в теории мог бы разнообразить раунд чем-нибудь смешным и интересным. 

Итак аутантская работка, смысл которой лишь сделать вакцину и остальные 2-3 часа сидеть и ждать шаттла или метеора. Поэтому предлагаю сделать не 5 образцов вирусов, а 10 штук.

**Comment by Shootnik01** [comment]
Закиньте в иссуй по вирусологии

**Comment by sweden-moose** [comment]
Еще бы количество аппаратуры увеличить вдвое, чтобы два вирусолога могли ужиться.
