### ISSUE TITLE
Смол еган превращения

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#4138]
Small energy gun при переключении режимов стрельбы меняет спрайт

**Comment by hard-res3t** [comment]
Вероятнее всего дубликат #5559

**Comment by Gojatlay** [comment]
Другой баг, не связан с #5559

**Comment by NefrNerf** [comment]
Видно когда-то починили или не было бага

![image](https://user-images.githubusercontent.com/85663436/122516966-1977b480-d018-11eb-8a76-aeffd1cd2a99.png)
![image](https://user-images.githubusercontent.com/85663436/122516996-24cae000-d018-11eb-8849-495073c870c9.png)
![image](https://user-images.githubusercontent.com/85663436/122517165-5fcd1380-d018-11eb-905d-e8c7796b96dc.png)

**Comment by TobyThorne** [comment]
> Видно когда-то починили или не было бага
> 
> ![image](https://user-images.githubusercontent.com/85663436/122516966-1977b480-d018-11eb-8a76-aeffd1cd2a99.png)
> ![image](https://user-images.githubusercontent.com/85663436/122516996-24cae000-d018-11eb-8849-495073c870c9.png)
> ![image](https://user-images.githubusercontent.com/85663436/122517165-5fcd1380-d018-11eb-905d-e8c7796b96dc.png)

Ну вот, выше пруф, что всё работает. Видимо, я в какой-то момент их случайно починил, пока чистил спрайты пушечек.
