### ISSUE TITLE
Небольшие изменения реагентов

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4140]
Гуляя по коду реагентов я наткнулся на несколько упущений, которые стоит заполнить:
1. Охлаждающая жидкость Coolant не охлаждает персонажей и используется только в машинах археолога. Стоит добавить охлаждение до температуры действия крио и клонксадона и генерацию токсинов.
2. Фосфор не светится при взаимодействии с кислородом (как сказано на вики). Стоит добавить свечение при разливе на пол/персонажа/стену.
3. Смазка не смазывает механизмы. В коде стоит пометка сделать ускорение боргов при распылении на них смазки. Не вижу в данной фиче ничего плохого.
4. Ксеномикробы, которые обычно встречаются в плодах растений ксеноботаника вообще никик не взаимодействуют с живыми существами. Их можно пить как воду. Предлагаю добавить либо превращение в какого либо антага, либо мутацию(телекинез и подобное), либо хотя бы накинуть токсичности.
5. Реагенты gold и silver из ксеноботании нельзя преобразовать в твердые слитки. Добавить рецепт.
6. Сера является антисептиком ИРЛ. В игре у нее вообще никаких эффектов на организм/пол/органы=вода. Можно добавить слабый антивирусный эффект на равне с куриным супчиком.
7. Вольфрам в игре подобен сере. ИРЛ вольфрам помогает от ионизирующего излучения(в том числе альфа бета и гамма радиации). Предлагаю добавить небольшой резист радиации при обливании вольфрамом
8. На вики написано про активную реакцию натрия с водой. В игре ее разумеется нет. Согласно реакции с википедии при взаимодействии натрия с водой выделяется газ водород. Спорное решение, но почему бы не добавить? Небольшое выделение водорода для активации атмосферной тревоги.
Все предложения можно изменять в угоду балансу или чему то еще. Я лишь предлагаю возможные пути увеличения химического опыта.

**Comment by kokokobold** [comment]
1-2 нормально. 3 неясно, как реализовывать. 4 довольно нереалистично выглядит, но тут можно что-нибудь интересное сделать. 5-6-7 нормально. 8 как-то слишком мелко, такое вряд ли вызовет атмосферную тревогу.
