### ISSUE TITLE
Энергоячейки в карго

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#4145]
![Без имени3232](https://user-images.githubusercontent.com/62835631/103443040-c094a980-4c8d-11eb-97d4-5af7f027d546.png)
**Появляется 2 новых объекта:**

### Высокоёмкий Аккумулятор - тяжелое устройство, которое не взять в руки. 
- Существует возможность прикрутить ключом оный к определенным объектам - зарядным платформам для экзоскелетов. При присоединении начинает заряжаться от электрической сети. 
- Аккум имеет высокую энергоемкость и предел поступаемого электричества в момент времени. Если его превысить - акку м загорится и сгорит. 
- Осмотр (Экзамайн) аккума показывает степень зарядки в процентном соотношении, численный предел поступаемого тока. У аккума 3 спрайта в зависимости от степени зарядки. При низком уровне уровень красный (мигающий). При среднем желтый. При высоком зеленый. 
- Среднестатистическая суперматерия на 30 Мегаватт заряжает аккум за 15 минут, отдавая лишь часть энергии(15%) зарядной платформе.  Если инженер опытный, то может уменьшить время до 7 минут, являющихся пределом.
- Аккум заказывается в размере 3 штук за один ящик. Стоимость заказа - 20 каргопоинтов
- Полностью заряженный аккум продается в карго по себестоимости в 50 каргопоинтов. То есть при профессионализме инженерного состава карго может получить за 10 минут 130 каргопоинтов при вычете стоимости заказа. При новичках - за 15 минут. 

```
Для примера: 
Ботаник может поставить за это время из неисчерпаемого запаса семян +-50 каргопоинтов
Киборг, печатающий ящики - 50-200 каргопоинтов
Шахтер - 200 каргопоинтов
```

- Аккум использует редкие радиоактивные элементы для хранения энергии. При около-полной зарядке (80%) начинает выдавать слабый фон. Такого фона будет достаточно, чтобы нанести вред космонавтам, но мало, чтобы питать им станцию. 
- Зарядными платформами оснащены все реакторы (фронтир, исход, поляр) в размере 3 единиц

Чтобы чудеса инженерии имели бы хоть какой то практический смысл:
![image](https://user-images.githubusercontent.com/62835631/103442586-16675280-4c8a-11eb-9aba-c600a43d5283.png)
(missing R.U.S.T. photo)
![image](https://user-images.githubusercontent.com/62835631/103442596-444c9700-4c8a-11eb-8062-eb10cd3e4320.png)

**Comment by Doster-d** [comment]
Не смог в дискорде, полез сразу в гитхаб

**Comment by MrMagick2104** [comment]
Имхо, фича с энергокредитами a la stellaris поинтереснее была, реализуя то же самое.
Сама по себе идея с именно такими энергоячейками - такое себе, имхо. Можно было бы сделать условный космический лазер/мазер, который бы отправлял энергию через космос на ЦК, автоматизированно, без ручного переноса энергоячеек (потому что передавать энергию в батарейках - такое себе. Не сайфайно). Похожее было в игрушке 'Deliver us the moon'.
К слову, такую штуку (в т.ч. из ОП-поста) можно было бы привязать к [тому проекту, который никто не будет кодить](https://github.com/ChaoticOnyx/OnyxBay/projects/17). Соответственно, из энергии можно генерировать либо то, либо это, за счёт универсальной машинерии, если делать это на ней. 

> Не смог в дискорде, полез сразу в гитхаб

Так и надо.

**Comment by ArmenianOnyx** [comment]
> Имхо, фича с энергокредитами a la stellaris поинтереснее была, реализуя то же самое.
> Сама по себе идея с именно такими энергоячейками - такое себе, имхо. Можно было бы сделать условный космический лазер/мазер, который бы отправлял энергию через космос на ЦК, автоматизированно, без ручного переноса энергоячеек (потому что передавать энергию в батарейках - такое себе. Не сайфайно). Похожее было в игрушке 'Deliver us the moon'.
> К слову, такую штуку (в т.ч. из ОП-поста) можно было бы привязать к [тому проекту, который никто не будет кодить](https://github.com/ChaoticOnyx/OnyxBay/projects/17). Соответственно, из энергии можно генерировать либо то (каргопоинты), либо это (научкопоинты), за счёт универсальной машинерии, если делать это на ней.
> 
> > Не смог в дискорде, полез сразу в гитхаб
> 
> Так и надо.

У нас на станции педальные генераторы стоят. Имейте совесть не упоминать лорные аспекты и логику.

**Comment by ArmenianOnyx** [comment]
По такой логике можно задать очень много вопросов существованию самой станции. У нас тут речь все же идет в добавлении фичи, которая придаст отделам приятного от их проделанной работы. Что бы отделы взаимодействовали с друг-другом.

**Comment by MrMagick2104** [comment]
> У нас на станции педальные генераторы стоят. Имейте совесть не упоминать лорные аспекты и логику.

Лорные аспекты упомянуты не были. Лора нет.
Речь просто об автоматизации. Автоматизация - круто, вручную таскать ячейки - такое себе.

> По такой логике можно задать очень много вопросов существованию самой станции.

Лора нет х2. Объяснить тоже можно всё.

> Вместимость можно сделать в 5 000 ~ 10 000 ед, при условии что ячейку никуда невозможно вставить на станции, кроме портов в реакторе

Очень маленькая вместимость, если речь о джоулях. На том же педальном генераторе, подключённом к общей сети, можно закрутить это за минуту, емнип.
Надо хотя бы по курсу 1 МДж - 1 каргопоинт, имхо.

**Comment by ArmenianOnyx** [comment]
Забыл кстати упомянуть. Анимеску обещал нарисовать спрайты ячеек и портов.

**Comment by Kexilex** [comment]
Шахтер может сделать 500+ очков на фороне и платине с буров за один рейс, а у вас одно очко за МДж))

**Comment by ArmolitskiyCarpoeb** [comment]
зачем ЦК батарейки?

**Comment by ArmenianOnyx** [comment]
> зачем ЦК батарейки?

Разрядились! Мы тут не для ЦК хотим батарейки добавить, а что бы карго и инженерам было что делать с 5 матерями в мидле.

**Comment by pro100Player** [comment]
Изобретаете тут PTL (power transmission laser) с гунов? Правда, там экономика такая, что если ПТЛ будет передавать максимум (999 терраватт), то каждый ассистент там будет с миллионами на счету бегать. Ладно, загнул, с сотнями тысяч при среднем онлайне в 50 лиц, учитывая, что денежки с него распределяются между членами экипажа и счетами отделов.
Ну да ладно, один мегаджоуль - один каргопоинт - маловато будет, у нас же в среднем с материи выходит мегаватт, который почти весь уходит станции, а если разгоняют, то **обычно** до 10-15 мегаватт. Что означает... *глянул учебник физики за 8 класс* За час _**примерно 40 гигаджоулей**_?.. Тогда наоборот один каргопоинт за 10 мегаджоулей :YOBA:

**Comment by ArmenianOnyx** [comment]
В скриншоте с живым СЕ, мы разогнали до 30 мегаватт.

**Comment by ArmenianOnyx** [comment]
Ждем геймдизайнеров

**Comment by TobyThorne** [comment]
Фича прикольная, да. Вот только с ценами надо основательно думать. А то всё разнобойное, РИГи дороже материи, патроны по цене хрен знает чего, когда проще заказать стали и напечатать самому, а очки вообще фармятся в любых количествах смешными бурами.

**Comment by ArmenianOnyx** [comment]
Ну что по проработке:
Пусть стоить будут по 15 в разделе инженерной карго. Приходить будут в инженерном ящичке в количестве 1 шт. Ячейку взять можно в руки, но нельзя положить в портфель по весу. По объему ячейки, можно взять вместимость как у блюспейс батарейки или другой чуть круче. Порты пусть заряжают со скоростью зарядников обычных. И так полностью заряженная батарейка будет продана ЦК ну минимум хоть за 60 поинтов карго.

**Comment by MrMagick2104** [comment]
> По объему ячейки, можно взять вместимость как у блюспейс батарейки или другой чуть круче

Да откуда такие объёмы берутся вообще? В топике уже предлагали более-менее нормальные: 1-100 МДж - один поинт, условно x. Пусть тогда будет вместимость батарейки в 50 или 100 каргопоинтов, соответственно 50x или 100x энергии в каждой.
Вместимость блюспейс батарейки должна быть *на порядки* меньше, чем такой предполагаемой каргобатарейки.

А если не сделать вместимость предполагаемой батарейки на порядки больше обычных, то:
> перестройке реакторов будет смысл

Не нужна будет перестройка реакторов. Это будет просто способ нафармить очков для карго, чтобы заказать пушечки/суперматерии/что-то ещё.

> Ячейку взять можно в руки, но нельзя положить в портфель по весу.

Я бы предложил сделать вместо этого куб 1х1х1 метр, который нужно таскать и прикручивать куда надо гаечным ключом. Иначе откуда такая вместимость энергии?

Если пилить зарядники, то стоит пилить их через машинерию, наподобие зарядников для мехов. Плату пихнуть одну на склад, впихнуть ящик для заказа в карго, впихнуть в научку. Для постройки использовать условные два конденсатора, один сканер, одну (или две) катушку(и) СМЕСа (проводимую или любую), а также тридцатник проводов. Соответственно, если хочется впилить "улучшаемость" деталек (но не нужно, имхо) можно капнуть скорость заряда в 10/20/100/1000 МВт для каждого уровня деталек.
Если хочешь зарядить быстрее батарейки - изволь сходить в научку за деталями или достроить зарядных портов из катушек и плат из карго.

Альтернативно, можно сделать зарядниками эмиттеры и гиротроны. Должно быть забавно и сравнительно балансно - нужно дозаказывать эмиттеры для подзарядки, либо более дорогие гиротроны, которые обладают большей мощностью. Можно впилить, к слову, сверхзаряд, в таком случае, таким батарейкам, при котором они бахали бы аки фуелтанк. Тогда и оправдать с точки зрения геймдизайна такое хранилище очень просто - специальные кристаллы суперматерии для хранения и передачи энергии.

Излучение радиации после зарядки (0,5 Бк за 1 каргопоинт в хранении) - тоже смешная фича, которую можно было бы впилить, она бы добавила ещё чутка опасности такой классной фиче по получению очков в карго.

**Comment by ArmenianOnyx** [comment]
> > По объему ячейки, можно взять вместимость как у блюспейс батарейки или другой чуть круче
> 
> Да откуда такие объёмы берутся вообще? В топике уже предлагали более-менее нормальные: 1-100 МДж - один поинт, условно x. Пусть тогда будет вместимость батарейки в 50 или 100 каргопоинтов, соответственно 50x или 100x энергии в каждой.
> Вместимость блюспейс батарейки должна быть _на порядки_ меньше, чем такой предполагаемой каргобатарейки.
> 
> А если не сделать вместимость предполагаемой батарейки на порядки больше обычных, то:
> 
> > перестройке реакторов будет смысл
> 
> Не нужна будет перестройка реакторов. Это будет просто способ нафармить очков для карго, чтобы заказать пушечки/суперматерии/что-то ещё.
> 
> > Ячейку взять можно в руки, но нельзя положить в портфель по весу.
> 
> Я бы предложил сделать вместо этого куб 1х1х1 метр, который нужно таскать и прикручивать куда надо гаечным ключом. Иначе откуда такая вместимость энергии?
> 
> Если пилить зарядники, то стоит пилить их через машинерию, наподобие зарядников для мехов. Плату пихнуть одну на склад, впихнуть ящик для заказа в карго, впихнуть в научку. Для постройки использовать условные два конденсатора, один сканер, одну (или две) катушку(и) СМЕСа (проводимую или любую), а также тридцатник проводов. Соответственно, если хочется впилить "улучшаемость" деталек (но не нужно, имхо) можно капнуть скорость заряда в 10/20/100/1000 МВт для каждого уровня деталек (соответственно уровню).
> Если хочешь зарядить быстрее батарейки - изволь сходить в научку за деталями или достроить зарядных портов из катушек и плат из карго.
> 
> Альтернативно, можно сделать зарядниками эмиттеры и гиротроны. Должно быть забавно и сравнительно балансно - нужно дозаказывать эмиттеры для подзарядки, либо более дорогие гиротроны, которые обладают большей мощностью. Можно впилить, к слову, сверхзаряд, в таком случае, таким батарейкам, при котором они бахали бы аки фуелтанк. Тогда и оправдать с точки зрения геймдизайна такое хранилище очень просто - специальные кристаллы суперматерии для хранения и передачи энергии.
> 
> Излучение радиации после зарядки (0,5 Бк за 1 каргопоинт в хранении) - тоже смешная фича, которую можно было бы впилить, она бы добавила ещё чутка опасности такой классной фиче по получению очков в карго.

Особо разногласий у меня с твоими предложениями нету. Для меня самое главное: социалка с инженерами и наличие хоть доли смысла и выгоды строительства реакторов.

**Comment by DarkHunter7756** [comment]
Собираю весь ворох идей в одну общую концепцию

Появляется 2 новых объекта:

### Высокоёмкий Аккумулятор - тяжелое устройство, которое не взять в руки. 
- Существует возможность прикрутить оный к определенным объектам - High-Energy Port. При присоединении начинает заряжаться от электрической сети. 
- Аккум имеет высокую энергоемкость и софткап поступаемого электричества в момент времени. 
- Осмотр (Экзамайн) аккума показывает степень зарядки в процентном соотношении. У аккума 3 спрайта в зависимости от степени зарядки. При низком уровне уровень красный (мигающий). При среднем желтый. При высоком зеленый. 
- Среднестатистическая суперматерия на 30 Мегаватт заряжает аккум за 15 минут, отдавая лишь часть энергии(15%) Если инженер опытный, то может уменьшить время до 7 минут, являющихся софткапом. Дальнейшее уменьшение времени зарядки затруднено
- Аккум заказывается в размере 3 штук за один ящик. Стоимость заказа - 20 каргопоинтов
- Полностью заряженный аккум продается в карго по себестоимости в 50 каргопоинтов. То есть при профессионализме инженерного состава карго может получить за 10 минут 130 каргопоинтов при вычете стоимости заказа. При новичках - за 15 минут. 

```
Для примера: 
Ботаник может поставить за это время из неисчерпаемого запаса семян +-50 каргопоинтов
Киборг, печатающий ящики - 50-100 каргопоинтов
Шахтер - 200 каргопоинтов
```

- Аккум использует радио-активные элементы для хранения энергии. При около-полной зарядке (80%) начинает выдавать слабый фон. Сделано это, чтобы были хоть какие-то меры предосторожности и трудности в транспортировке. 


### High-Energy Port - непереносимая машинерия, через которую можно пройти
- Откручивается для переноски ключом. Подключается также ключом. 
- Данными портами оснащены все реакторы (фронтир, исход, поляр) в размере 3 единиц
- Порты можно заказать в карго за 10 карго-поинтов. Заказ включает 1 порт.
- Порты начинают работать при условии наличия провода под ними (см. подключение генератора Пакман)
- Порты потребляют 15% энергии из сети при подсоединенном аккуме
- Порты выглядят, как видоизмененный спрайт портов для зарядки мехов.

**Comment by Artemonim** [comment]
> Аккум использует радио-активные элементы для хранения энергии.
Атомная энергетика работает на распаде радиоэлементов. Я не физик, но предполагаю, что на гипотетическое восстановление ядерного топливного элемента в изначальное состояние нужно потратить больше энергии, чем он может отдать, а значит КПД аккумулятор стремится к нулю.

Я бы предложил сделать так, чтобы кристалл суперматерии испарялся выдавая энергию, эти испарения нужно было бы отфильтровывать и потом уже продавать. Собственно, на Исходе уже есть мало кем используемая система для таких операций - нужно только ввести этот газ.

Если говорить про чёрную дыру ЕОСа, то такой генератор может излучать антиматерию.

**Comment by No-Tips** [comment]
Кто кодить будет? :kek:

**Comment by No-Tips** [comment]
А вообще какой нахер распад материи, мы сука играем в 2д симулятор газов. Давайте не усложнять до пизды что-то.
