### ISSUE TITLE
Рефакторинг генкоабилок

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#415]
Запрос рефакторинга https://github.com/ChaoticOnyx/OnyxBay/commit/6aedcc47ab99f2fa8c5719f9eeb5db56c8a020b6

**Comment by ZerlGray** [comment]
![image](https://user-images.githubusercontent.com/32713309/52571403-8a927600-2e26-11e9-8d6e-f56f4d601835.png)

**Comment by TobyThorne** [comment]
Генка зарефакторен.
