### ISSUE TITLE
Фикс флавора после трансформации генокрада

### ISSUE THREAD

**Issue by P00TiZ** [ChaoticOnyx/OnyxBay#416]
**Описание бага**
После трансформации остается флавор прежней оболочки.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем генокрада
2. Открываем черепушку космонавта и выпиваем из него все соки
3. Нажимаем на способность трансформации и трансформируемся в того несчастного космонавта
4. Видим свой привычный флавор

**Ожидаемое поведение**
Хотелось бы видеть флавор новой оболочки

**Характеристики**
 - OS: Windows 10
 - Версия клиента 512.1463
 - Версия сервера 512
 - ID игры "локалка"

**Comment by ZerlGray** [comment]
Я пытался это пофиксить двумя разными способами, хотя бы обнуляя флавор - по какой то причине оно не работало. Формально в коде прописан сброс, фактически - не работает.

**Comment by ZerlGray** [comment]
![image](https://user-images.githubusercontent.com/32713309/52652713-ab7aca00-2eff-11e9-963b-6896ac1e7ac6.png)

**Comment by P00TiZ** [comment]
Может быть flavor_texts ?

**Comment by ZerlGray** [comment]
> Может быть flavor_texts ?

Это вроде лист (но это не точно) и я вроде его тоже пробовал трогать и ничего не обнулялось.

**Comment by Cinericius** [comment]
Это еще актуально, кстати?
