### ISSUE TITLE
Вампирский вэил стэп

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#4168]
В описании "кликните пкм в тайл в тени", по факту нужен альтклик+лкм.

**Comment by Zert0X** [comment]
ПКМ выделяешь тайтл, Veil Step
![изображение](https://user-images.githubusercontent.com/42303535/107751994-2c5b3f00-6d2f-11eb-99c2-1136da8b60d7.png)

**Comment by Zert0X** [comment]
наверное всё таки пора закрыть? Автор просто не разобрался что ПКМ по турфу это значит зайти в вёрбы этого турфа
