### ISSUE TITLE
Chad distress beacon вместо virgin факса

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#4175]
Случаются такие смены, когда творится хаос, генки сожрали всех офицеров, нюкеры гоняются за мартышкой с диском или воксы забрали в рабство трапов медбея. Экипаж может попытаться дать отпор, но воевать с залутанными генками или нюкерами без оружейной почти нереально. Блоб так же является гарантированной нюкой в ебучку. 

Предлагаю вместо вызова ерт или факсов с мольбами к цк(может у цк интернет упал) просто заменить на сигнал бедствия ака distress beacon. Вызвать можно в красный код и после определенного времени с начала сменены. А кто может откликнуться на сигнал бедствия? Кто угодно! С большей вероятностью его должны принять ЕРТ, но те же воксы или синдикатовцы не прочь помародерить. А может и маг, а может и вампир подскочить доесть тепленьких.

Даст вторую жизнб гостоте и добавит в раунд событий. В идеале накодить так, чтобы для "помощи" на сигнал бедствия не нужно было щитспавнить, но можно что-нибудь подкрутить. 

В закрепах пример того, как это звучит на тгмк.
[beacon.zip](https://github.com/ChaoticOnyx/OnyxBay/files/5771686/beacon.zip)

**Comment by ArmolitskiyCarpoeb** [comment]
Хорошая идея.
