### ISSUE TITLE
Революционеры могут приглашать издалека

### ISSUE THREAD

**Issue by hekko4** [ChaoticOnyx/OnyxBay#42]
Необязательно стоять вплотную, чтобы пригласить вступить в революцию. Это Баг или фича?

**Comment by PlinHost** [comment]
Нормально, надо только проверку на взаимную видимость (слышимость?) запилить.

**Comment by Epicus7** [comment]
Проверка на видимость должна быть по-дефолту, скорее всего. Это же верб.

**Comment by PlinHost** [comment]
Она проверяет только видимость приглашаемого приглашающим, но не наоборот.
