### ISSUE TITLE
Пойнтбар для генокрадов

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#420]
Аналогичный алиеновскому. Если кто-то займется - тыкайтесь в дискорде, вышлю спрайтики, они уже с год назад отрисованы и анимированы еще для вайтовского Нечто. 
![screenshot_8](https://user-images.githubusercontent.com/3739131/52916889-e7de6980-32f5-11e9-9abe-d3a9229dfd38.png)

**Comment by Ruforce** [comment]
было на тг вроде

**Comment by Cinericius** [comment]
На ТГрине по идее мог быть, я собсно для него спрайт и пилил исходно

**Comment by TobyThorne** [comment]
Ставлю на то, что Панча по поводу спрайтов тыкать уже бесполезно.
