### ISSUE TITLE
Обычные солнечные очки не видны на космонавте

### ISSUE THREAD

**Issue by TheUnknownOneGH** [ChaoticOnyx/OnyxBay#4205]
### Описание бага
Тупо не видны, причём работают нормально. Видимо какая-то проблема с соответствующими спрайтами.
Что интересно, у толстых солнечные очки (которые в одной из комнат в дормах лежат) всё в порядке.
Насчёт секьюрити и прочих очков не знаю.

**Comment by TobyThorne** [comment]
В процессе фикса. Почему оно сломалось - понятно, а вот почему вообще работало - непонятно.
