### ISSUE TITLE
ПРОБЛЕМЫ с атмосом

### ISSUE THREAD

**Issue by PleaseJustEndMyPain** [ChaoticOnyx/OnyxBay#4214]
### Описание бага
Надувные стены, стекла и ещё некоторые обьекты пропускают газы при определенных условиях, я сейчас пишу не про их поломку, а про фактическое прохождение газа через них, как через пустой тайл. Баг воспроизводится через раз и не в каждом раунде.
### Воспроизведение
Поджигаем реакторную, на выходе из нее ставим тонкое стекло и закручиваем его. Открываем дверь, и о чудо! Теперь горит и комната, смежная с реактором!
### Ожидаемое поведение
Стекло должно было помешать газу, но оно спокойно пропустило его.

### (Опционально) Дополнительная информация
Зачастую это происходит при модификациях камеры материи, когда меняешь расположение стекла.

**Comment by No-Tips** [comment]
Стекло нужно ставить не на том же тайле, где у тебя условная комната горения, а на соседнем. Вот и все...

**Comment by No-Tips** [comment]
Недофича, так сказатб

**Comment by TobyThorne** [comment]
Со стеклом воспроизвести не удалось. Только в случае, когда оно не было прикручено.
