### ISSUE TITLE
Баланс скиллов вампира

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#4222]
Вампиров добавили, но часть их скиллов крайне кринжовая.
- "Blood Heal" - скилл довольно сильный, возможно стоит немного замедлить скорость лечения при условии выполнения этого иссуя #4183
- "Hypnotise" - не работает на генках и вампирах, думаю, так  и надо.
- "Presence" - крайне ролеплей ориентед скилл, проблема в высокой стоимости кровяной валюты, нет возможности вести сколько-нибудь продолжительную беседу, не слив при этом всю кровь. По ощущениям нужен расход крови раза в два меньше, ввиду проблематичного использования в реалиях хаотического попуха. 
-  "Touch of Life" - ну, инструмент для парамедика месяца. Ввиду дороговизны не позволяет быть шаманом для ассистентов, а так хочется.
- "Summon Bats" - это кринге, спавнит инвалидных мух вместо кровососущих порождений ночи(убивается с удара кулаком). Нужно что-то делать с этим, пока выглядит, как инструмент королевского ролеплея. >Спавнит мышей и испаряется. ???? Было бы шикарно, если мыши могли налететь на цель, снизить её обзор, пососать кровь немного из неё кусями. А еще по ним промахиваешься, это же летучие мыши. 
- "Chiropteran Screech" - вампир делает screeeeee. Скилл ок, но что так дорого снова((
- "Veil Walking" - джаунт, да? Прошел десять тайлов и остался без крови. Спрайт приведеньки кринжовый, нужны какие-нибудь призрачные мыши или кровяная бяка, это же вампир, а не культяпка. 
- "Dominate" - очередной ролеплей ориентед скилл для принуждения слэйвов исполнять твои ерп желания. Нормально, наверное.
- "Enthrall" - ловушка ЕРПшера. С этим скиллом можно собрать целый гарем трапиков. Ролеплееры опуха одобряют. Снизить цену хотелось бы
- "The Embrace" - скилл для расширения сетей гаремов, ок. 

Огорчает высокая стоимость некоторых скиллов, что выливается в отсутствие крови после 2-3 прожатых кнопок при том, что эти самые скиллы бесполезные против генок и космонавтиков с защитой глаз(они же краснозадые). Что заставляет бегать по станции в поиске ОДИНОКОЙ жертвы, вместо ерп с трапами и не только.

**Comment by ArmenianOnyx** [comment]
какого хуя не Тоби нерфит?

**Comment by Kexilex** [comment]
Подрядчик сдал работу с косяками и забрал оплату, а на фиксы косяков бюджета не хватает блядб

**Comment by Zert0X** [comment]
Иссуй обновлён, ненужное было вырезано.
