### ISSUE TITLE
Крю Манифестное

### ISSUE THREAD

**Issue by No-Tips** [ChaoticOnyx/OnyxBay#4227]
Изменения личных данных в крю манифесте не санитайзятся, что приводит к возможности вставить любые ХТМЛ теги и устроить ржаку клиенту.

![картинка](https://user-images.githubusercontent.com/8840325/104103121-68732e00-52b1-11eb-8e86-8e8fdd066f72.png)

![картинка](https://user-images.githubusercontent.com/8840325/104103125-6b6e1e80-52b1-11eb-877a-051ebf05cea4.png)

**Comment by PlinHost** [comment]
Решается выпилом модульных компутеров и возвращением консолей.
