### ISSUE TITLE
Ввести болу в сборку

### ISSUE THREAD

**Issue by Shootnik01** [ChaoticOnyx/OnyxBay#4250]
### Улучшение
Добавить в билд болу. Причина - вывод из строя нарушителей **без боли** от тазера/батона(например в зеленый код), а также - больше игровых ситуаций с погонями, не сводящимся к перестрелкам/бесконечным побегушкам по станции 

### Решение
Болу можно легко перенести с других билдов. Порывшись в инете, нашел немного полезной [инфы](https://tgstation13.org/wiki/Makeshift_weapons#Bola)

З.Ы. 24 лукаса в дисе

**Comment by sweden-moose** [comment]
![shitcurity](https://user-images.githubusercontent.com/63788778/104811260-678b5080-580b-11eb-9d72-e3a43cf148e2.jpg)

Как же я люблю СБ, вот они слева направо

**Comment by Shootnik01** [comment]
Ахахахах!! Ну, это - праща у них, добавим в следующем иссуе)))
