### ISSUE TITLE
Лаги гунчата.

### ISSUE THREAD

**Issue by PleaseJustEndMyPain** [ChaoticOnyx/OnyxBay#4292]
Клиент очень сильно залагивает, когда в чате одновременно появляется 4 и более сообщения, очень сильно мешает при стрельбе из огнестрела, а стрелять из дробовика вплотную - зависать секунд так на десять.

**Comment by HonkyDonky** [comment]
Лагает? Обнови компьютер :smiley:

**Comment by sweden-moose** [comment]
Лагает? Запости #3680

**Comment by Kexilex** [comment]
Атак логи создают фризы на слабых ПК, да. Вот бы впилить функцию отключения атак логов на клиенте

**Comment by Destrolaric** [comment]
Может для такого галочку на вырубание гунчата?
