### ISSUE TITLE
Change Mob Appearance

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#430]
В педальных менюшках Change Mob Appearance не хватает:
1) Бодибилдов. Нельзя сделать тонкотрапов, ррреее.
2) Возможности протезировать отдельные части тела.
3) Опционально - татуировок.
4) Может быть еще и флаворов. 

Зачем? Во славу мидраунд-ивентов, конечно.

**Comment by Terydd** [comment]
Бодибилды сейчас есть.

**Comment by incatnator** [comment]
Флаворы через другую кнопку уже имплементированы и без педалей.
