### ISSUE TITLE
Некорректное отображение отсутствующей ладони при повороте персонажа

### ISSUE THREAD

**Issue by No-Tips** [ChaoticOnyx/OnyxBay#4302]
Была ампутирована правая кисть, при повороте персонажа она магическим образом появлялась, лишь визуально. Пикчу прилагаю
![image](https://user-images.githubusercontent.com/75416333/104961400-eedced80-59de-11eb-8dc7-824fd605813e.png)

**Comment by TobyThorne** [comment]
Это не ладонь, а пузо просвечивает. Да, у спрайтов одежды специальные "прорези" под руки. Да, это так работает. Да, это так работает ВЕЗДЕ. 

В теории это можно изменить, но надо будет перепиливать половину билда.
