### ISSUE TITLE
Вернуть воксов в хейсту и вернуть хейсту

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#431]
Собсно тож не новая идея, но чот не нашел иссуй.
На данный момент у воксов забагована их одежка (спрайты отклеились), а так все полностью рабочее.
После починки одежки надо сделать хейстеров воксами. Кроме того, надо проверить и починить шаттл хейсты, если он сломан.

**Comment by Ruforce** [comment]
Хейст в реалиях нашего комьюнити идет по двум разным - диаметрально разным - вариантам игры
Вариант А: антаги берут максимальное число валын и представляют себя нюкерами, выпиливают экипаж и сосут от одной очереди буллпапа
Вариант Б: хейстеры - особенно в случае с целью на ресурсы - бьют стахановские рекорды как труда, так и аутизма, весь раунд копая астероид.

Хейст говно и не нужен

**Comment by Penguineapig** [comment]
Непонятно почему не хотят в социалочку и рабство гамать, отправляя захваченный экипаж принудительно копать им ресы

**Comment by Cinericius** [comment]
...если пилить воксов, то можно загнать им закон, типа, никакого тяжелого труда своими руками.

**Comment by Firefroge** [comment]
Но никакой уважающий себя вокс не будет копать сам, если можно заставить работать пленных.

**Comment by Fritcher36** [comment]
Именно ;)

**Comment by Penguineapig** [comment]
И хоть будет мотивация не выпиливать весь экипаж что только завидят

**Comment by ZerlGray** [comment]
1. Дать риги каждому воксу, с соответствующим инструментарием - медриг, инжериг, боевой риг и стелс риг.
2. Взрывимпланты, импланты внушения, дать им больше химикатов для нейтрализации.
3. Дать больше вещей для стелса.
Они не могут играть по стелсу, потому что у них банально для этого нет возможностей.

**Comment by Firefroge** [comment]
У них все РИГи есть, но они не делают ничего особенного, да.
Желательно было-бы добавить им пушек, которые будут обезвреживать.

**Comment by ZerlGray** [comment]
РИГ, а не скафандр. Это разные вещи. У них есть ток стелсриг.

**Comment by kreeperHLC** [comment]
Филя вернул перед смертью, но без ротации
