### ISSUE TITLE
Добавить синдром Туретта

### ISSUE THREAD

**Issue by sweden-moose** [ChaoticOnyx/OnyxBay#4315]
Чтобы матюки сами добавлялись в предложения, ну и чтобы кукла иногда их озвучивала.

**Comment by Destrolaric** [comment]
Оно уже в билде, в генетике

**Comment by Zert0X** [comment]
> 
> 
> Оно уже в билде, в генетике

у нас есть генетика? Тип мб как механ да есть, а вот лечить всё это и прочее уже нельзя вроде как

**Comment by Destrolaric** [comment]
Можно, это генетическая мутация, для них Ryetalyn.
