### ISSUE TITLE
Убрать локи с мехов вне Роботики

### ISSUE THREAD

**Issue by sweden-moose** [ChaoticOnyx/OnyxBay#4317]
Родиал сказал, что эти локи айди делались от набегаторов на ЦеКа. Но сейчас Мародёров и Серафимов на ЦК нет, лок остался, а сами мехи продаются у мерчантов, но без емага и копания в этом говне они неликвид, еще и забивающий телепад

**Comment by PlinHost** [comment]
Звучит как баг.

**Comment by Doster-d** [comment]
Дубликат #1873
