### ISSUE TITLE
Улучшение робототехники (аугментика)

### ISSUE THREAD

**Issue by HexBro** [ChaoticOnyx/OnyxBay#4328]
### Улучшение
Улучшение механик различных имплантов для большего разнообразия в плане их механа. Сейчас протезы - просто спрайтики, ничем не отличающиеся друг от друга.

### Решение
Расширение механики имплантов, возвращение их печати в РнД (именно бренды), плюс уникальные импланты для аплинка и трейтонюкеров

1) Убрать импланты из меха-фабрикатора. С чар сетапом тоже подумать надо.
2) Новый аппарат для отдела - Branded limbs fabricator (Первая залупа на пикче, но можно и лучше сделать). Потребляет железо, стекло, алмазы и все остальные ресурсы, а также кислоту. Имеет функцию "Sync with servers" для апдейта базы данных, подобно остальным принтерам РнД
3) Ввод печати всех брендированных протезов, какие есть ингейм:

- НаноТрахен. Самые дешевые импланты, жопа говна (всё самое лучшее для работников!). Немного резиста при избиении, и ничего более. 1000 металла 500 стекла. Доступно раундстартом.
- Жень-Ху. Продукция космической поднебесной для инженерного дела. Встроенная изоляция, высокий резист к ожогам, небольшая защита от EMP. 1500 металла, 500 стекла, 500 пластика. Открывается при материалах 3, инженерном деле 4, энергии 4.
- Зион. Аугментика полюбившаяся космоскаму за простоту изготовления и дешевизну. Выглядит ужасно с оголённой проводкой и открытыми приводами, но имеет пару ништяков: дешевые приводы для усиления удара и урановые накладки, резиновые накладки для отвода ударов током. Небольшой резист от ударов током и шока (тазеры батоны), небольшой бонус при давании оппонентам в пиздак. 1000 металла, 500 стекла, 400 урана. Инженерия 2, комбат 4, материалы 2, энергия 3
- Вэй-Мед. Специально для медицинских работников от медицинской корпорации (логично, да). Ноги имеют повышенную скорость передвижения (бонусы парамедикам, чтобы те пуллили критованных быстрее и быстрее их убивали), руки считаются стерильными как если в перчатках. 500 металла, 1000 пластика, 1000 стекла, кислота. Медицина 4, инженерия 2, материалы 2, энергия 4.
- Гефест. Военные импланты для сильных духом. Повышенная защита от типов урона, включая ЕМП, ноги имеют хардмод, по эффекту схожий с гиперзином, в случае если обладатель носит скафандр или тяжелую разгрузку, на руках алмазные острые накладки для еще более мощного давания в пиздак нарушителям. 2000 металла, 500 стекла, 1000 пластика, 500 алмазов, кислота. Инженерия 6, энергия 4, комбат 7, материалы 5.
- ВарКрайм Синдикорп. Только из аплинка капсулой с наноботами, которая при введении преобразует конечности в железо. Резисты от урона немногим выше Гефестов, но полная защита от ЕМП урона и брутмод для рук, сурово увеличивающий шанс кнока при ударах. Не крафтится в РнД.

Также ввод глазных имплантов на пересадку:
- НТ. Нихуя не делает. 1000 стекла, 300 пластика, кислота. Разве что поправить потерянные родные глаза.
- Жень-Ху. Имеет встроенную защиту от ЭМИ, сварочной слепоты и мезонный сканер. 1000 стекла, 500 пластика, 500 металла, кислота. Инженерия 5, энергия 4, материалы 4.
- Зион. Встроенное ПНВ и… всё. 1000 пластика, 500 стекла, кислота, 500 металла. Комбат 3, инженерия 5, энергия 4.
- Вэй-Мед. Встроенный МедХУД. 1500 стекла, 500 пластика, кислота. Медицина 5, биология 4, энергия 4.
- Гефест. Термальный мод, защита от флэша. 1000 стекла, 1000 металла, 500 пластика, кислота. Комбат 8, биология 6, инженерия 8, материалы 6.
- ВарКрайм Синдикорп. Термальный мод, защита от флэша, защита от ЕМП. Берется в аплинке отдельной капсулой, помимо руконог.

### (Опционально) Дополнительная информация
ВарКрайм и респрайты старых аугов приклеил. Можно и глазным уникальные нарисовать.

![unknown](https://user-images.githubusercontent.com/30608328/105606909-edc80980-5dac-11eb-93b0-4a9917cc0ff8.png)

**Comment by MrMagick2104** [comment]
Уровни для создания протезов очень странные. Местами слишком низкие, местами слишком высокие.
> Зион - комбат 4

Инженерные протезы требуют боевых технологий?

> Гефест - Инженерия 6, энергия 4, комбат 7, материалы 5.

Инженерные технологии 6-5-4 открываются в научке даже без ресурсов. Маловато.

> Зенг Ху - Встроенная изоляция

Изоляционки для учёных почти раундстартом - вот это класс.

Нужно учитывать, что у учёных раундстартом есть пластик. Из-за этого, можно пойти и поставить себе ножки от Вей-меда, чтобы бегать быстро, а также изоляционные руки от Зенг Ху в первые десять минут раунда.

Имхо, спрайты Гефеста, Ксеона, НТ и Вей-Меда выглядят хуже, чем раньше, за исключением деталей с тем, как они установлены, что выглядит неплохо. Опять же, имхо, плохая цветовая палитра была выбрана (раньше более-менее нормальная была уже). Тёмно-зелёно-серые Вей-Меды с красными крестами вообще не сочетаются, синие протезы от НТ вообще смешно выглядят (как прикол только пойдёт, пластиковые, считай, если оставить текущие спрайты в небрендовых протезах, они довольно неплохие дженерики), у Зиона спрайты изначально хорошие были, с приятной цветовой гаммой. Гефест не похож на условные военные протезы, скорее, на протезы тактикульного военного косплейщика. Когти как у унатхов на ногах смешно выглядят.

Если респрайтить, то нужно учитывать, что нужны протезы таза, головы и торса для синтов.

> на руках алмазные острые накладки для еще более мощного давания в пиздак нарушителям

А как же ручные ракетницы, встроенные в протезы, крюки-кошки для быстрого перемещения и огнемёты для борьбы с джедаями? Почему их забыл?

Лучше бы титановые вставки упомянуть.

Кстати, если говорить об увеличении урона при ударе, то любые протезы должны его давать (кроме пластиковых), так как удар металлической палкой, в большинстве случаев, больнее, чем удар кулаком, я думаю.

Мне кажется, концепт такой себе. Лучше бы сделать не раздел по протезам, а условные "апгрейды". Сами протезы чисто декоративные, берутся раундстартом, но в принтере можно распечатать тулкит, который при имплантации в протез даёт эффекты. Это было бы логичнее и удобнее в плане сохранения баланса. Иначе, нужны какие-то минусы этим робоконечностям.

К слову, возникает концептуальный вопрос: что будет, если поставить один такой протез, один - другой? Вариант с имплантацией улучшений его решает.

> по эффекту схожий с гиперзином, в случае если обладатель носит скафандр или тяжелую разгрузку
> Ноги имеют повышенную скорость передвижения (бонусы парамедикам, чтобы те пуллили критованных быстрее

Звучит так, словно бы протезы Вей-меда - бюджетный вариант гефестовских.

**Comment by HexBro** [comment]
Я накидал примерные уровни научных знаний, чтоб в принципе понимать о чем речь.

>Инженерные протезы требуют боевых технологий?
Зион не инженерные же, я предложил Зион (как отсылку к Матрицей) сделать протезами любителей гаттера и бундов.

>Изоляционки для учёных почти раундстартом - вот это класс
Раньше в РнД крафтились милитари протезы. Ноги дающие спидбуст аки приводы на Гигаксе, и руки с форсед модом, который с 1 удара делал внутряки и ломал бронестекла. Чудо, если их заказывал хоть кто-то.
Про спрайты отдельная тема. Мне уже сказали в спрайтояме, как их пофиксить, да и в принципе я так просто накидал примерный ребилд. НТ и есть рофел, что любимая корпорация пихает пластиковое говно "лишь бы работало" своим дорогим сотрудникам.

>А как же ручные ракетницы, встроенные в протезы, крюки-кошки для быстрого перемещения и огнемёты для борьбы с джедаями? Почему их забыл? Лучше бы титановые вставки упомянуть.

А я хотел. Но у нас титяна нет, так что выбор пал на уран (для нищих) и алмазы для богатых. И про клетку Фарадея еще смотрел (потому в крафте и завязан пластик, думал еще дерево вписать, но это цирк - оно сгорит при первом кз)

>Мне кажется, концепт такой себе. Лучше бы сделать не раздел по протезам, а условные "апгрейды". Сами протезы чисто декоративные, берутся раундстартом, но в принтере можно распечатать тулкит, который при имплантации в протез даёт эффекты. Это было бы логичнее и удобнее в плане сохранения баланса. Иначе, нужны какие-то минусы этим робоконечностям.

Да что угодно нужно делать с РнД, превращая его из цирка с конями и вортексами на 15 минуте/аутизмом уровня "ну мы всё изучили но оно скучное и бесполезное" со сломанными психоскопами, вырезанными контентом и прочим в нормальное и интересное Рисеч н Девелопмент. Тулкиты тоже хорошая тема, просто по лору у нас вроде как некоторые протезы реально люксовый класс, а поставить их себе в сетапе может даже бомж, что слегка идет вразрез с логикой.

>Звучит так, словно бы протезы Вей-меда - бюджетный вариант гефестовских.
Не, эффекты таки разные - "аля гиперзин" это нет дебаффа скорости при надевании тяжелых сьютов, но константа начальной скорости не меняется, а ускорители это как раз наоборот - меняется сама скорость, но сьюты дебаффают ее

**Comment by MrMagick2104** [comment]
> Зион не инженерные же, я предложил Зион (как отсылку к Матрицей) сделать протезами любителей гаттера и бундов.
> Аугментика полюбившаяся космоскаму за простоту изготовления и дешевизну

Звучит как простые, рабочие протезы.

> Ноги дающие спидбуст аки приводы на Гигаксе, и руки с форсед модом, который с 1 удара делал внутряки и ломал бронестекла.

Ну, пластик есть раундстартом. Кроме того, у нас есть синты-робототехники и синты-учёные, которые могут сесть на стул, отпилить себе две ноги, поставить новые, пойти гулять И я о том, что он может быть в принципе не нужен в рецепте, потому что  они чисто символические и делаются ради баланса. Например, для чего нужно серебро и алмазы для создания огнестрельного оружия???

> Но у нас титяна нет

Титан был, по крайней мере есть стенки из него. Только вот внутриигровыми способами он не получается.

> протезы реально люксовый класс, а поставить их себе в сетапе может даже бомж, что слегка идет вразрез с логикой.

Почему нет? Бомжи не всегда были бомжами. Убирать это - ограничивать свободу отыгрыша. Что мешает быть бывшим аристократом с какой-нибудь Гайи Магны, который разорился и ушёл на заработки себе на пропитание работать в каком-то захолустье, куда он только и годится при своих навыках?
Ну и чисто ООЦ - некоторые протезы выглядят как говно, субъективно. Нехорошо бы было их ограничивать механом сетапа, ибо играть с отвратительным спрайтиком не всем хочется.

Если говорить о реализации сетапа с такой протезной системой, можно в сетапе выдавать т.н. "restricted" версию протезов, которая не имеет баффов, просто выглядит так.

> Не, эффекты таки разные - "аля гиперзин" это нет дебаффа скорости при надевании тяжелых сьютов, но константа начальной скорости не меняется, а ускорители это как раз наоборот - меняется сама скорость, но сьюты дебаффают ее

Но если человек с Вей-медом имеет ускорение, допустим, в единицу, то он может бегать в сьюте как ни в чём не бывало, потому что он замедляет на единицу? Не с повышенной скоростью, а нормальной.

> это нет дебаффа скорости при надевании тяжелых сьютов

Насколько сильно должно быть отсутствие веса? В магбутсах бегать можно?

> Тулкиты тоже хорошая тема

Имхо, тулкиты интереснее, потому что им можно впилить и "обычных" фич. Например, зажигалку в протез вставить, магбутсы, хирургический набор для автодоков, пулемёт, как в трейлере Деус Экса: ХР, и так далее.

**Comment by Ruforce** [comment]
Через века, через года, дети блюбеевского РнД все ещё грезят мечтами о протезах.

**Comment by Shootnik01** [comment]
Красиво. Но если реализуют, то через 9999 лет

**Comment by MaxFreemen** [comment]
Я готов взять на себя иссуй, но с парочкой НО. Понятное дело, что просто так производить протезы другой корпорации на станции Нано-Трейзен - незаконно, поэтому я подготовил несколько вариантов решения проблемы. Товарищи геймдизайнеры, нужна ваша помощь

Первые несколько вариантов объединяет тот факт, что протезы имеют единые характеристики, а все их различие лишь в цвете и форме. Т.е клиент просто может выбрать желтый протез от Зень-Ху, ибо он инженер, и протез подойдет по цвету к его форме, скажем.
1. Взлом фабрикатора для печати "паленых" протезов или покупка лицензии у торговцев/карго
2. Выбор разных дизайнов, что фактически удалит привязку протеза к корпорации-производителю.
Забыл добавить, что в протезы можно будет установить различные улучшения, которые выберут геймдизайнеры, и будут сделаны либо позже мной, либо другими людьми.

Третий вариант приближен к первоначальной концепции. Мы изучаем технологии, чтоб открыть новые протезы. Этот вариант мне кажется странным, ибо на эффекты протезов должна влиять их "начинка", а не внешний вид.
