### ISSUE TITLE
Перерезание сухожилий и горла не админлогируется

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#434]
А надо чтобы админлогировалось, а то вдруг кто-та грифонеть будет!!111!!!11

**Comment by Firefroge** [comment]
"ATTACK: Firefroge/(Rick Mertz) hamstrung Vatapro98/(Garry Nixon) (INTENT: HARM) (LOC) (MOB)"
Оно через раз логируется.
