### ISSUE TITLE
Раундстартовые ивенты

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#4355]
### Улучшение
Как известно, многие раунды, в последнее время, довольно однообразны по своему содержанию, если судить в целом. Суть раундстартовых ивентов состоит в привнесении небольших (или больших) особенностей раунда, которые бы могли разнообразить игровой процесс.
В целом, аналогично ивентам, происходящим в середине раунда, однако реализуя те функции, которые в середине раунда не могут быть исполнены (и некоторые другие, которые в данный момент не реализованы). 

### Решение
Я бы предложил, кроме того, что уже упомянуто в коде #4322:
-Добавить ротацию двигателя суперматерии/синги/РАСТа (если его починят) с некоторым шансом, чтобы разнообразить работку инженеров
-Начало раунда и возможность присоединения к игре только за персонажей одного из двух полов
-Отсутствие арсенала в бриге: в виде какого-то конкретного предмета вооружения (тазеров, пистолетов, etc.), либо в целом отсталость экипировки (вместо станбатонов - полис батоны, вместо обычной униформы - какая-то другая (например, конфедератская), вместо пистолетов - сервисные револьверы (которые с нормальным спрайтом), а в арсенале ~~мосинки~~ - пусто)
-Перемешивание лоадаутов и предметов стартовой экипировки (кроме карточек) игроков между друг другом
-Отсутствие кого-либо на станции, кроме ассистентов
-Некоторые вещи, упомянутые в #2224:

1. Отсутствие генератора гравитации
2. Хронические метеоры (с отсрочкой в 20 минут после начала раунда и оповещением)
3. И другие.

Помимо того, что уже есть из механа в #4322 (конфиги), хорошо бы было добавлять какую-то информацию об ивенте в панель вёрба "Ивент Инфо".

### Дополнительная информация
Уже реализовано в #4322, по большей части.

Сабж.

**Comment by kcalbCube** [comment]
А пилить кто будет?

**Comment by kcalbCube** [comment]
Геймшизы не одобрят

**Comment by ghost** [comment]
Ты разве не в бане?

**Comment by kcalbCube** [comment]
Всмысое в бане? Я же гений dm, отец русского контрибутерства

**Comment by ghost** [comment]
Срёшь много, прекращай.

**Comment by kcalbCube** [comment]
давно мариную мысли об этом. что по геймдизайнерской части вопроса?

**Comment by kreeperHLC** [comment]
Брысь, это не для тебя

**Comment by Doster-d** [comment]
> давно мариную мысли об этом. что по геймдизайнерской части вопроса?

Ето не для тебя и не таких как ты

**Comment by kcalbCube** [comment]
заебитесь.
