### ISSUE TITLE
Переработка заработка карго

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4358]
На текущий момент карго может зарабатывать двумя путями: продажа платины/плазмы (высочайший не сбалансированный заработок) и экзотических семян (минимальный заработок). Это скучно и никак не подстегивает карго взаимодействовать с иными отделами. Я предлагаю ввести иную систему заработка денег прямиком с кримзона. А именно спецзаказы с ЦК

1. Введение дополнительной консоли/программы в карго, информирующей о текущий спецзаказах. 

2. Введение в эту консоль заказов:
  1) Заказ на еду (повар). Суть заказа в предоставлении на ЦК определенной еды. Торты, бургеры, сыры и многое другое. Чем сложнее изготовить пищу, тем больше денег за нее можно получить. 1-3 предмета.
  2) Заказ на экзоскелет (роботехник). Изготавливаем меха - продаем на ЦК. Выручка зависит от типа меха. Но она в несколько раз выше, чем остальные заказы. 1 предмет.
  3) Заказ на плоды мутации растения (ботаник/ксеноботаник). 10 предметов.
  4) Заказ на обыденный предмет на станции в большом объеме (ассистент). Donk-Pockets, ломики и т.д. 10 предметов.
  5) Заказ на вирус с определенным симптомом (вирусолог)
  6) Заказ на определенный орган (хирург, медик). 1-3 предмета.
  7) Заказ на экстракт слизня определенного вида (ксенобиолог). 1 предмет.
  8) Заказ на любой предмет Синдиката (СБ). 1 предмет.
  9) Заказ на определенный реагент, лекарство, вещество в нескольких экземплярах полных банок (химик). 2-5 предметов.
  10) Заказ на мусор (уборщик). Включает в себя пустые пакеты, бычки от сигар, гильзы и подобных хлам. 10 предметов. 
  11) Заказ на слитки определенного материала (золото, серебро, уран и т.д.) (шахтеры) 10-60 предметов.
  12) Заказ на определенный напиток (бармен). 1-5 полностью наполненных подходящих под напиток емкостей. 
  13) Заказ на предмет из протолата (ученые). 1-3 предмета. 
  14) Заказ на полный баллон определенного газа (инженер). 1 предмет.
  15) При выполнении 5 заданий ЦК список получает еще 5 заданий, тем самым карго деятельность не останавливается. 
Для выполнения всех заказов хватит просто отправить предметы на карго шаттле
Итого мы имеем:
1. Карго отдел начинает активнее взаимодействовать с другими отделами
2. Способы заработка становятся разнообразнее
3. У карго появляются хоть какие-то причины общаться не с шахтерами.

**Comment by ArmenianOnyx** [comment]
Идея замечательная, но тут есть самое главное противоречие,  которое может попросту убить отдел карго. 
> не подстегивает карго взаимодействовать с иными отделами.

Карго просто физически не может не взаимодействовать с отделами. Вся станция приходит в карго, что бы добрый КМ исполнил их самые каверзные желания. И как человек который очень часто возглавляет этот отдел, я тебе с уверенности могу сказать что половина игроков даже не знает о том, что платину и форон нужно продавать. 

> У карго появляются хоть какие-то причины общаться не с шахтерами.

Карго это вам не игра в одни ворота РнД, которое пошлет всех нахер и закроется бластдурами, социал идет постоянно. Сначала нужно щиты доставить, затем ящики догрузить, затем медбею доставить заказы, потом РнД ресурсы, постоянный социал с другими отделами.

И вообще конкретно я повинен в том, что люди считают что карго бафнутое. На самом деле это не так легко заработать пару тысяч поинтов на ресурсах, это нужно зауметься в спидране.

**Comment by MrMagick2104** [comment]
Дубликат #1028 же.
А ещё, уже реализовано в #1046.

**Comment by DarkHunter7756** [comment]
А, ну тогда ждем автора. 
![image](https://user-images.githubusercontent.com/76823962/106364024-1caa2680-633d-11eb-8fbc-41bf307c744a.png)
