### ISSUE TITLE
Граб лежачих

### ISSUE THREAD

**Issue by Schutze88** [ChaoticOnyx/OnyxBay#438]
**Описание бага**
При грабе лежа оба космонавта получают охуенный стан, который лечится только прописыванием дроп_олл педальным образом.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Падаем.
2. Лежа хватаем другого человека грабом. Желательного, такого же лежачего.
3. Охуеваем от того, что ни он, ни мы не можем сдвинуться

**Ожидаемое поведение**
Нужно либо вообще исключить возможность грабать лежа, либо что бы грабали работали как обычно, а не перманентно станили обоих.

**Скриншоты**
Если проблема может быть показана на скриншотах - прикрепите их.

**Характеристики**
 - OS: Шиндос десять 
 - Версия клиента: 512.1464
 - Версия сервера: dba982b565fbbd890dfbc03104e85e21e62ab6ac 
 - ID игры: bYY-dfew

**Дополнительная информация**
Здесь можете описать любую дополнительную информацию, которая касается бага

**Comment by Cinericius** [comment]
Граб кстати не только при лежании делает лежать + станить

**Comment by Cinericius** [comment]
Пока закрою, вдруг оно пофиксилось
