### ISSUE TITLE
Микро-tweak - протезы и лампочки

### ISSUE THREAD

**Issue by Shootnik01** [ChaoticOnyx/OnyxBay#4425]
### Улучшение
Разрешить вытаскивать лампочки включенными, если делаешь это протезом(он не чувствует тепло)

### Решение
Добавить такую возможность, это несложно, ревьюерам предложение повесить *просто* на иссуй(если это реально просто😑)

### (Опционально) Альтернативы
"Делай или не делай, пытаться не надо" - Йода

### (Опционально) Дополнительная информация
Я хорошо покушал; всем приятного аппетита

**Comment by kcalbCube** [comment]
И вообще, поджечь себя зажигалкой можно, а лампочку горячую вытащить нельзя.

**Comment by MrMagick2104** [comment]
Уже можно, не?

**Comment by Shootnik01** [comment]
Неа
