### ISSUE TITLE
Борги из нанитов не могут открыть меню девайса (шлюз, консоль, etc)

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#4431]
По всей видимости, люди, превращенные в боргов с помощью нанитов, не могут открыть девайсы. Например, использовать консоль или наэлектрелизовать шлюз. С хоткеями можно открывать-закрывать шлюзы. Не проверял на локалке.

**Comment by Terydd** [comment]
https://user-images.githubusercontent.com/91453615/142747823-03e500f5-fd6a-475d-be48-21c5025ea372.mp4

**Comment by TobyThorne** [comment]
Штош, не воспроизвелось.
