### ISSUE TITLE
Подключение камер к электросети

### ISSUE THREAD

**Issue by Shootnik01** [ChaoticOnyx/OnyxBay#4466]
### Улучшение
Камеры не подключены к электросети, что приводит к тому, что при отключении электроэнергии камеры все еще работают(на чем, простите?). Это ограничивает возможность их отключения до ручного отключения каждой камеры.

### Решение
Дать камерам небольшой(20-50w) расход энергии, привязать к АПЦ к группе "Equipment"

### (Опционально) Дополнительная информация

Иссуй набрал более 30 лайков в Дискорде

**Comment by Destrolaric** [comment]
Я как малфо ИИ не одобряю, предлагаю альтернативу, вставить в камеры батарейки от ноутбуков, и дать им ≈ 20 минут работы без сети.

**Comment by Shootnik01** [comment]
Ненене, размечтался. Первое - задолбешься менять механ в камерах на батарейки. Второе - тебе и так могут камеру поломать

**Comment by kcalbCube** [comment]
А провода

**Comment by Shootnik01** [comment]
А провода что? С проводами все в порядке.

**Comment by Shootnik01** [comment]
Кубик, сможешь закодить?

**Comment by oleggorru** [comment]
> ### Решение
> Дать камерам небольшой(20-50w) расход энергии, привязать к АПЦ к группе "Equipment"

Уже привязано и жрет
	idle_power_usage = 5 WATTS
	active_power_usage = 10 WATTS
