### ISSUE TITLE
Смерти и концы, концы и смерти

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#449]
Вернуть окончание раунда после смерти/деспавна визарда, малфа и ниндзи.

**Comment by Cinericius** [comment]
А еще лучше вместо этого починить автодосыпалку антагов.

**Comment by Epicus7** [comment]
Автодосыпалка антагов уже есть в виде сторителлера. Будем дальше развивать его в рамках https://github.com/ChaoticOnyx/OnyxBay/projects/15
