### ISSUE TITLE
Фикс ксеноморфиков

### ISSUE THREAD

**Issue by PleaseJustEndMyPain** [ChaoticOnyx/OnyxBay#4511]
Пофиксить яйца и добавить лицехватов.
-Лицехваты могут моментально напрыгнуть на космонавта без маски и шлема, начав заражение
-Лицехваты могут снять маску или шлем с жертвы, но это займёт N секунд.
-Эмбрион чужого может быть извлечен хирургическим путем.
-Кислотная кровь лицехватов проплавит обшивку, если её вовремя не убрать. 
Большие спрайты 
-Сейчас все спрайты чужиков выглядят мелкими, та же квина однотайловая не выглядит грозно, нужно исправлять. 
Абилки на хоткеи как в РИГе
-Сейчас все абилки юзаются нажатием в верхней панели, выбором цели и только потом активации. Предлагаю заменить эту механику на механику привязки абилок к СКМ, что облегчит боевое применение вышеуказанных абилок.
Отсутствие upper body у ксеноморфиков
-Самая большая проблема. 

Режим ксеноморфов имеет большой потенциал, вот только им никто не занимается.

**Comment by Shootnik01** [comment]
@TobyThorne, к твоему иссую про ксеносов

**Comment by Shootnik01** [comment]
> -Эмбрион чужого может быть извлечен хирургическим путем.
> -Кислотная кровь лицехватов проплавит обшивку, если её вовремя не убрать.

Не согласен. 1 - у лицехватов не будет шансов, если их можно будет отцепить. 2 - идея с кровью - не очень, будут обузить

**Comment by TobyThorne** [comment]
Реализовано в #4949.
