### ISSUE TITLE
Ротация движков в инженерке 

### ISSUE THREAD

**Issue by PleaseJustEndMyPain** [ChaoticOnyx/OnyxBay#4512]
## Сейчас настройка суперматерии предельно скучна и однообразна. 
Предлагаю ввести ротацию движков в инженерку по типам и степени собранности
Из них:
-Материя 45% шанс
-Синга 55% шанс
-РАСТ с руководством 5% шанс
У всех кроме РАСТа так же свой рандом степени собранности, Т.Е. мамка может появится с разобранными ТЭГами рядом, синга без проводки и так далее. 
### Данные изменения принесут хоть какое то разнообразие, сейчас на инженерке только рпшить и аутировать в стройку, никакого разнообразия в отделах между раундами. 
Пофиксить прыжки синги между Z левелами и ломание щитов. 
По поводу РАСТа, движок рабочий, но для него ещё нужно написать руководство, чем я и займусь.

**Comment by kreeperHLC** [comment]
Думал об этом, но тут прикол в том, что заменять нужно больше одного предмета.

**Comment by kreeperHLC** [comment]
Ладно, с заменой предметов справиться можно, но с заменой целых кусков карты - не очень

**Comment by Destrolaric** [comment]
Тут только к ротации карт логично подобное присобачивать.
Ждём фронтира.

**Comment by PleaseJustEndMyPain** [comment]
> Ладно, с заменой предметов справиться можно, но с заменой целых кусков карты - не очень

Ну, исключая сингу там фигня вопрос. Мать от РАСТа отличается только наличием инжекторов топлива и гиротрона, и инертным газом в качестве теплоносителя

**Comment by No-Tips** [comment]
Синга сломана, зачем её добавлять в ротацию. Это менять карту под каждый движок... Новички будут стабильно сосать.

**Comment by PleaseJustEndMyPain** [comment]
> Синга сломана, зачем её добавлять в ротацию. Это менять карту под каждый движок... Новички будут стабильно сосать.

Проблема новичков что они гайды не читают, а потом ноют. Сингу пофиксить довольно просто.

**Comment by MrMagick2104** [comment]
> Ладно, с заменой предметов справиться можно, но с заменой целых кусков карты - не очень

На каком-то билде такое было, по-моему (если не ошибаюсь, билд Флаффи, лол). И там это реализовано было через руины. Может, на Опухвау такое тоже сработает, у нас же были руины где-то, вроде?
> Синга сломана

Синга не сломана же. Что в ней сломанного?

**Comment by PleaseJustEndMyPain** [comment]
> > Ладно, с заменой предметов справиться можно, но с заменой целых кусков карты - не очень
> 
> На каком-то билде такое было, по-моему (если не ошибаюсь, билд Флаффи, лол). И там это реализовано было через руины. Может, на Опухвау такое тоже сработает, у нас же были руины где-то, вроде?
> 
> > Синга сломана
> 
> Синга не сломана же. Что в ней сломанного?

Синга не проверяет что под ней и во время прыжка по левелу может сожрать щит

**Comment by MrMagick2104** [comment]
> Синга не проверяет что под ней и во время прыжка по левелу может сожрать щит

Так если у тебя щиты стоят друг под другом, сжирания происходить не должно?
Или она может в один тик расширится и во время него же прыгнуть вниз?

**Comment by PleaseJustEndMyPain** [comment]
> > Синга не проверяет что под ней и во время прыжка по левелу может сожрать щит
> 
> Так если у тебя щиты стоят друг под другом, сжирания происходить не должно?
> Или она может в один тик расширится и во время него же прыгнуть вниз?

Да, именно так

**Comment by HonkyDonky** [comment]
> Альтернативно можно, я думаю, просто ротацию карты скрытно впилить для игроков, сделав два варианта мапы.

Здесь мало того, что в таком случае нужно будет перед каждой ротацией перекомпилировать билд, что заставит игроков в конце раунда ждать. Так ещё и над двумя версиями карт нужно будет работать одновременно.

**Comment by No-Tips** [comment]
У меня появилась идея. Это немного не тема этого иссуя, но можно и тут что-то придумать. Почему бы на карте не спавнить изначально мать, а дать право выбора СЕ - сгенерировать мать случайно или поставить стандартную скучную материю. Тоже самое можно добавить и в этом иссуе. Если СЕ нет - лепить обычную мать. Если есть СЕ - дать ему право выбора, а на чем будет работать станция в этом раунде.

**Comment by No-Tips** [comment]
> > Синга не проверяет что под ней и во время прыжка по левелу может сожрать щит
> 
> Так если у тебя щиты стоят друг под другом, сжирания происходить не должно?
> Или она может в один тик расшириться и во время него же прыгнуть вниз?

Именно настолько смешно она работает. Она даже расти не должна для того, чтобы съесть щит, потому что кроме движения по Z, мать во время прыжка по уровням сдвигается еще и по X Y координатам, прыгая прямо на генератор щита.

**Comment by kcalbCube** [comment]
Уберите Z перемещение и радуйтесь

**Comment by No-Tips** [comment]
Реализовано на Фронтире, закрываем?

**Comment by vsss412** [comment]
Давайте закроем, если потребуется - прошу отдельный иссуй для вашей-карты-нейм!
