### ISSUE TITLE
Пофиксить отклеивание космоса

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#452]
Баг существует со старта сервера, но особо никто не пробовал его фиксить. Иногда космос отклеивается и все белеет. Возможно, это как-то связано с тем, что у нас кастомный космос, который криво вставили, надо посмотреть.

**Comment by PlinHost** [comment]
Верните космос и будет всем щастье.

**Comment by TermService** [comment]
ничего не понятно

**Comment by Doster-d** [comment]
Все еще актуально.

**Comment by KamSurvivor** [comment]
> Все еще актуально.

Фикс белого космоса на инфинитибеях. Билды плюс минус идентичны, может сработает этот фикс.

https://github.com/infinitystation/Baystation12/pull/2015/files

**Comment by Doster-d** [comment]
> > Все еще актуально.
> 
> Фикс белого космоса на инфинитибеях. Билды плюс минус идентичны, может сработает этот фикс.
> 
> https://github.com/infinitystation/Baystation12/pull/2015/files

Его вроде уже фиксили, там проблема была в фиксированном размере космоса.

**Comment by kreeperHLC** [comment]
> > > Все еще актуально.
> > 
> > 
> > Фикс белого космоса на инфинитибеях. Билды плюс минус идентичны, может сработает этот фикс.
> > https://github.com/infinitystation/Baystation12/pull/2015/files
> 
> Его вроде уже фиксили, там проблема была в фиксированном размере космоса.

![image](https://user-images.githubusercontent.com/14943437/136150711-ce4db107-f387-481e-8ead-faaae38b5d86.png)

**Comment by Doster-d** [comment]
Ок.

**Comment by BlackCrystalic** [comment]
Так и не пофиксили?
