### ISSUE TITLE
Нерф мэнитеров

### ISSUE THREAD

**Issue by No-Tips** [ChaoticOnyx/OnyxBay#4526]
Эти твари, что мутируют из дион - идеальное оружие для убийства любого человека, который захочет в одиночку с ними сразиться.
В чем заключается проблема:
1. Мэнитеры СЛИШКОМ долго умирают, никак не станятся при получении дамага. По ним требуется попасть четыре-пять раз с лазгана, чтобы те умерли. А в ближнем бою они тебя загрызут.
2. Имеют ускорение, благодаря которому способны догнать любого в поле зрения.
3. С первых двух укусов нокают, после чего ты уже ничего  не можешь сделать, а только беспомощно умирать.
4. Сражаться против одного мэнитера можно. Но если, не дай бог, ты захочешь избить ДВУХ мэнитеров - пиши пропало, ведь достаточно, чтобы каждый тебя укусил один раз, чтобы ты успешно нокнулся. А укусить тебя очень легко исходя из пункта 1 и 2.

Исходя из этих пунктов - нужно что-то придумать, чтобы с ними было возможно сражаться, не применяя плазмафаер, а не постоянно отсасывать от куста мэнитеров, что постоянно спавнит по тройке этих тварей.

**Comment by Iarick** [comment]
Практика показала что можно просто заболтировать зараженный отсек, и дальше делать вид что его не существует. А уж идти с ними воевать это личный выбор каждого.

**Comment by DarkHunter7756** [comment]
Госты могут периодически заходить за менитеров. Сломал окно и коридор захлебнулся в тварях.

**Comment by Iarick** [comment]
Окна аварийными шлюзами перекрываются, или дальше часть коридора дополнительно заболтировать, все равно будет место где нет окон.

**Comment by DarkHunter7756** [comment]
Апдейт один был, теперь симплмобы могут открывать аварийные шлюзы
Против болтов же нет идей

**Comment by MrMagick2104** [comment]
> Апдейт один был, теперь симплмобы могут открывать аварийные шлюзы

Заварить?

**Comment by Iarick** [comment]
И откачать атмосферу пока они не передохнут, а не в ксочку играть с половиной сотни менитеров.

**Comment by DarkHunter7756** [comment]
Пара генов на стойкость и их не убьет даже плазма. Но это не точно.
