### ISSUE TITLE
Настенный автомат Бара забагован

### ISSUE THREAD

**Issue by Penguineapig** [ChaoticOnyx/OnyxBay#456]
**Описание бага**
1. Красивый спрайт настенного автомата меняется на спрайт напольный
2. Анимация выдачи из настенного спрайта отсутствует. В моментт выдачи действует анимация напольного автомата

**Воспроизведение**
Шаги чтобы воспроизвести баг:
неизвестно
1. ждём 2 часа раунда
или... много раз используем автомат пока баг не появится?
2. Покупаем что угодно

**Ожидаемое поведение**
1. Спрайт должен оставаться таким каким есть вначале
2. Должна быть анимация выдачи из настенного автомата.

**Скриншоты**
![image](https://user-images.githubusercontent.com/39528097/53696030-84f7d280-3dcb-11e9-9e79-d3ba2e6a157a.png)

**Comment by TobyThorne** [comment]
Кое-кто поленился впиливать отдельный объект для настенного автомата и просто изменил icon_state на карте. Обновляется - ломается.

**Comment by Penguineapig** [comment]
> Кое-кто поленился впиливать отдельный объект для настенного автомата и просто изменил icon_state на карте. Обновляется - ломается.

Ржака. Но несколько раз почему-то работает. Возвращается в первичное состояние
