### ISSUE TITLE
Улучшить механику влияния температуры на человеков и ксеносов

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4564]
У нас сломано влияние температур на тело, все это знают. Космонавтик может гулять с температурой -1000 как ни в чем не бывало. Что я предлагаю:
1. Тело человека обладает несколькими состояниями
Стандартное состояние (36.6C). Организм полностью функционирует, негативных эффектов нет.
Жар(38-43C). Ускоряется накапливание голода. Вирусы на 1 стадии излечиваются с определенным шансом. [Ситуативно] Ускоряется метаболизм
Гипертермия(44-48С). Нарушается кровообращение и доставка кислорода в мозг (оксигенация падает с средним шансом каждые n секунд). Кровь начинает выпариваться из организма (каждые p [p>20] секунд 5 единиц крови персонажа исчезает из организма.)
Тепловой удар (49-51С). Начинается рвота, повышается пульс, появляется головокружение, слабость, боль и спазмы(как от тазера). Выпаривание крови усиливается до 10-15. Имеется риск остановки сердца (низкий шанс)
Остановка сердца(52С). 100% эффект.
Охлаждение(32-35С). Замедляется накапливание голода. Ускоряется перемещение. Понижен иммунитет [Ситуативно] Замедлен метаболизм
Гипотермия(29-31). Возникает дрожь(эмоут), сильная усталость(сон), оглушение, невнятная речь, галлюцинации. С некоторым шансом случайная конечность становится неоперабельным ожогом.
Сильная гипотермия(25-28С). Персонаж впадает в паралич(как от бромида), начинает задыхаться.
Тепловая смерть(24С). Остановка сердца 100%.
2. Температура тела изменяется на 1-5% от температуры воздуха, а также температурной пушки, душа и напитков.
3. Плюшки рас: 
Скреллы(ибо амфибии) вместо тепловой смерти впадают в стазис и нагревают себя
Таяране получают бонус к повышению температуры, но резист к понижению (если нет такого)
4. Скафандры и иная защита уменьшают изменение температуры тела от атмоса и температурной пушки максимум до 0.1%. То есть комната с температурой 500С будет повышать температуру человека в скафандре на 0.5 каждые z секунд. 
5. Охлаждающий модуль не охлаждает, а стремится к установке температуры на 36.6С
Итого мы имеем: 
Пожары и заморозки комнат становятся эффективнее и интереснее
Температурная пушка становится эффективнее
Еда и напитки, нагревающие и охлаждающие, становятся полезнее

На ваше обсуждение

**Comment by Shootnik01** [comment]
Очень крутая идея, одобряю!! Вирусам бутет раздолье, ммм)))

**Comment by Shootnik01** [comment]
Только почему при слабом охлаждении скорсть увеличится?

**Comment by DarkHunter7756** [comment]
> Только почему при слабом охлаждении скорсть увеличится?

Этим я решил добавить небольшое улучшение охлаждающим напиткам и еде. Навернул пивасика из холодоса и воевать. Либо сожрать батин суп и...исход очевиден впринципе

**Comment by Shootnik01** [comment]
> > Только почему при слабом охлаждении скорсть увеличится?
> 
> Этим я решил добавить небольшое улучшение охлаждающим напиткам и еде. Навернул пивасика из холодоса и воевать. Либо сожрать батин суп и...исход очевиден впринципе

Честно? Ну такое себе:)

**Comment by No-Tips** [comment]
Напомните, пожары у нас случаем не поднимают температуру тела?

**Comment by MrMagick2104** [comment]
> Унатхи вместо тепловой смерти впадают в стазис и нагревают себя

Унатхи хладнокровные, так-то. Они наоборот должны умирать от низкой температуры намного быстрее, в отличии от пушистых.

К слову у нас можно надеть на человека охладитель для скафандра и подставить его под холодный душ, тогда у него температура тела будет моментально нулевой.

**Comment by DarkHunter7756** [comment]
> Унатхи хладнокровные, так-то. Они наоборот должны умирать от низкой температуры намного быстрее, в отличии от пушистых.

Тут ты прав, имелось в виду состояние анабиоза, к которому оказывается подвержены амфибии. Меняю на скреллов.

> К слову у нас можно надеть на человека охладитель для скафандра и подставить его под холодный душ, тогда у него температура тела будет моментально нулевой.

Это не правильная система. Охладитесь должен стремиться к нормализации температуры на отметке 36.6С. Это не сломает охлаждение синтов. Вроде
Душ же работает по > Температура тела изменяется на 1-5% от температуры воздуха, а также температурной пушки, душа и напитков.

**Comment by Shootnik01** [comment]
> Напомните, пожары у нас случаем не поднимают температуру тела?

Да

**Comment by Shootnik01** [comment]
А хотя хз. Но если пр добавят, то - точно

**Comment by Shootnik01** [comment]
Кстати, можно еще при заморозке красивое затуманивание сделать, галюны(музыка) и сообщения в чат сначала про холод, а потом про неожиданное тепло и расслабление. Источник - [https://pikabu.ru/story/kak_nastupaet_smert_ot_pereokhlazhdeniya_6483745](url)

**Comment by No-Tips** [comment]
А теперь посмотрим на это со стороны кода и оптимизации.
Худший вариант - проверка температуры каждые n тиков и накидывание бафов/дебафов в зависимости от разных рас. Лишняя околоненужная хрень, что сильно будет нагружать сервер.
Вариант слегка лучше - проверка когда меняется температура. В обычном раунде проблем меньше. Но представьте вариант, где станция будет медленно нагреваться. Тогда у вас будут спайклаги от просчета бафов-дебафов, от всей тонны эмоутов с рвотой, просчета выпаривания крови у каждого персонажа с последствиями выпаривания крови и тд.
А учитывая, что имо это фича вообще не нужна - она ещё и будет тяжёлой для сервера.

**Comment by MrMagick2104** [comment]
> А теперь посмотрим на это со стороны кода и оптимизации.

Да у нас уже температура измеряется каждый ход, по-моему, с нанесением дамага, если она не в комфортных пределах.
На самом деле, большая часть вещей с температурой уже есть, кроме теплового удара и переохлаждения, как описано в иссуе, но, имхо, их и не стоит добавлять, так как температура у космонавтов в большей степени условная, она может очень сильно скакать ввиду некоторых приколов из кода, за всеми которыми не уследишь.

**Comment by Shootnik01** [comment]
> > А теперь посмотрим на это со стороны кода и оптимизации.
> 
> Да у нас уже температура измеряется каждый ход, по-моему, с нанесением дамага, если она не в комфортных пределах.
> На самом деле, большая часть вещей с температурой уже есть, кроме теплового удара и переохлаждения, как описано в иссуе, но, имхо, их и не стоит добавлять, так как температура у космонавтов в большей степени условная, она может очень сильно скакать ввиду некоторых приколов из кода, за всеми которыми не уследишь.

Если и делать, то чинить температуру полностью, да.
