### ISSUE TITLE
Бафф температурной пушки

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4566]
На текущий момент пушка абсолютно бесполезна. С температурой газов в канистрах/баллонах, слизнями, людьми, предметами и многое другим практически не взаимодействует. Что предлагаю:

1. Стрельба по баллонам/канистрам с газами изменяет температуру на 40% от температуры в пушке для баллона и 10% для канистры. [Альтернативно сделать связь с давлением]
2. Стрельба достаточно низкой температурой по луже вещества (вода, топливо, радий) превращают ее в смазку(У нас же нельзя посмотреть имя вещества на полу? Пусть будет аналог льда). Стрельба достаточно высокой температурой высушивает пол
3. Стрельба по людям имеет весомый эффект [#4564]. 
Альтернативно высокая температура будет делать ожоги и поджигать, а низкая замедлять и накладывать эффект паралича
4. Холод убивает слизней. Дистанционная альтернатива воде.
[Ситуативно] Стрельба по предметам делает их краснее и белее от высокой и низкой температуры

Предлагайте иные идеи в комментариях.

**Comment by No-Tips** [comment]
Нужно делать привязку к молям, чтобы меньшее кол-во газа нагревалось сильнее, и наоборот. Тогда это будет эдакой интересной заменой теплообменника для небольшого кол-ва газа. Или смешным нагревом канистры при температуре 100к+.

**Comment by Shootnik01** [comment]
Эх, умел бы ты еще кодить.. Женился бы за такие иссуи
