### ISSUE TITLE
More Implants

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4567]
Маловато у нас полезных имплантов. Почему бы не портировать с ТГ? Предлагаю ввести в распечатки протолата/фабрикатора робоцеха следующее:

Импланты низкого уровня (низкие затраты по ресурсам)

1. **Reviver Implant.** Вводит в организм носителя дозу стабилизирующих препаратов при критических повреждениях. Однако ЭМИ может остановить сердце

2. **Anti-Drop Implant.** Вещи из активной руки не выпадают от боли или дизарма. Однако ЭМИ вызовет 100% коллапс на пару десятков секунд

3. **Breathing Tube Implant.** Возможность дышать от баллона не обладая маской на лице. Однако ЭМИ вызовет удушение

Импланты среднего уровня (средние затраты по ресурсам. Возможна трата ресурсов с шахты)

1.**Welding Shield Implant.** Иммунитет к флешам и сварке. Однако ЭМИ вызовет временное ослепление

2. **Medical HUD Implant/Security HUD Implant.** Постоянный ХУД

3. **All Languages Implant.**  Добавляет в разум персонажа базовый пакет языков, среди которых языки скреллов, унатхов, таяран, боргов(аудио кодировка)

Импланты высшего уровня (высочайшие затраты по ресурсам. Требуются алмазы, плазма и многое другое)

1.**Toolset Arm Implant/Surgical Arm Implant.** В панели верхней части экрана появляется возможность достать в используемую руку модуль хирургии медицинского борга/аналог с инструментами инженерии. Дропнуть предмет нельзя, механика подобна армблейду. Однако ЭМИ вызовет с некоторым шансом гиб руки

2. **Thermals Implant**.  В панели верхней части экрана появляется возможность включить/выключить термальные сенсоры.

P.S. Я предложил лишь идеи для кодеров, разумеется все эти вещи вместе взятые делать не надо

**Comment by Shootnik01** [comment]
Круто!

**Comment by Shootnik01** [comment]
Так чего? Будут импланты?
