### ISSUE TITLE
Безумная наука

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4568]
Очередной иссуй про РнД и очередной порт с других проектов(не совсем). Что можно сделать для интересного времяпрепровождения ученых:
1. Уменьшающий лучемет и увеличивающий лучемет(Свое). "Оружие" взаимодействует с размерами предметов и мобов, увеличивая или уменьшая их. Ради баланса стоит позволить 2 раза изменить размер на 20-50%
2. Bluespace Wormhole Projector (ТГ). Портальная пушка собственной персоной. Генерирует 2 портала, которые легко пролетают сквозь стекла. Ради баланса стоит задвинуть пушку ближе к вортексу, ибо манипуляции можно сотворить дикие
3. One-point Bluespace-Gravitational Manipulator(ТГ). Гравипушка из халвы. 2-3 режима. Захват, бросок. Расстояние ограничено лишь экраном персонажа. Сила броска выше обычной человеческой, но ниже выстрела пневматики на полном давлении.
4. Cryostasis Shotgun Dart(ТГ) Патрон, в который можно залить реагенты. Реагенты будут вступать в реакцию лишь по прилету в противника. 
5. Устройство смены пола(Свое). Небольшое устройство за высокие исследования. Наведение на персонажа меняет его пол на противоположный
6. Advanced Heals Analyzer. Весь функционал стационарного сканера здоровья в ваших руках. Имеется в билде уже. Добавить на высоких медицинских технологиях за весомые ресурсы
7. Multi HUD(Свое). ХУД с возможностью вставки и активации нескольких матриц. 
8. Красящий лучемет(Свое). Зависящий от заряда своей батареи, лучемет может менять цвет моба/предмета на выбранный в внутренней панели. 
9. Устройство смены тел(свое). При наведении на иного моба/человека, обладатель устройства через 20 секунд меняется с ним разумами. Например синт переносится в макаку и наоборот. Взлом устройства емагом обнуляет время перед сменой тела. Требуются высокие уровни исследования, ибо это идеальная мимикрия аля генка. 

P.S Я предложил лишь идеи для кодеров, разумеется все эти вещи вместе взятые делать не надо

**Comment by Shootnik01** [comment]
Загляни в проекты

**Comment by DarkHunter7756** [comment]
> Загляни в проекты

"Заря над бездной" гораздо дольше и продвинутей этого иссуя. Это лишь дополнение/список идей на будущее

**Comment by Shootnik01** [comment]
Можешь приклеить туда иссуй

**Comment by DarkHunter7756** [comment]
#4059

**Comment by O0oMaximo0O** [comment]
Портальную пушку даже уже делают

**Comment by Doster-d** [comment]
Все еще напоминаю, что нужный спрайты.
