### ISSUE TITLE
Запретить синге прыгать между гетто и станцией

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#4575]
Запретить синге прыгать между гетто и станцией, но прикрутить пожирание тайлов, над/под которыми она находится.

**Comment by MrMagick2104** [comment]
Зачем? Если для того, чтобы пофиксить сингу, так там баг с пожиранием щитов (ввиду прыжка одновременно с расширением и смещением), не лучше нормально пофиксить, нет?

**Comment by HonkyDonky** [comment]
Нормально - это как?

**Comment by MrMagick2104** [comment]
> Нормально - это как?

Убрав смещение и увеличение синги одновременно с прыжком по З-уровням.
Если я правильно всё понял из предыдущих обсуждений, то проблема именно в этом.

**Comment by Kexilex** [comment]
Из-за того, что синга скачет, инженегры не могут держать её в поле на станции, а им так хочется. Если она будет жрать одновременно два уровня, то и без прыжков нормально будет.

**Comment by MrMagick2104** [comment]
Если расположить щиты синги друг под другом, то убегать она не должна, логично ведь? Если убегает - значит баг так как, очевидно, принципы работы нарушены. Имхо, фиксить это убиранием фичи со скаканием синги - такое себе.

**Comment by O0oMaximo0O** [comment]
Неактуально, нынче синга мультиуровневая
