### ISSUE TITLE
Сломанный биокаулдрон генок или как можно выпилить всю станцию без логов

### ISSUE THREAD

**Issue by Tsurupeta** [ChaoticOnyx/OnyxBay#4579]
### Описание бага
ГЕНКОУКОЛЫ ХИМКАУЛДРОНОМ НЕ ЛОГИРУЮТСЯ, РЯЯЯЯЯЯЯЯ

### Воспроизведение

1. Берем КАУЛДРОН
2. Открываем ИНТЕРФЕЙС
3. Нажимаем УКОЛОТЬ ПЛАЗМУ
4. Видим ошибку ОТСУТСТВИЯ ЛОГОВ У ПЕДАЛЕЙ УКОЛА ПЛАЗМЫ В КРОВЬ ЧЕЛОВЕКА

### Ожидаемое поведение
ОЖИДАЮ ЛОГИ

### Скриншоты
*здесь мог быть скриншот ничего*

### (Опционально) Дополнительная информация
Сам по себе код этого биокаулдрона сломан и его нужно переписывать с нуля, ибо там половина вещей банально не работает, это просто ПИЗДЕЦ. Да, я пишу это на сгоревшей жопе, но всё равно.

**Comment by TobyThorne** [comment]
Исправлено в #7084 путём выпиливания котла
