### ISSUE TITLE
Смертельные телепорты в стеночку

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#4593]
### Улучшение
Есть проблема в том что космонавтики телепортируются в стену. И могут выйти из неё в любую стоорону

### Решение
Сделать чтобы любые телепорты (спеллы, вортексы, модуль рига, вормхолы, джаунты, баг со шкафчиком) в стену заканчивались гибом. Ибо нехуй

### (Опционально) Альтернативы
Как вариант, их можно выталкивать из стены с получением урона и станом

**Comment by HonkyDonky** [comment]
Бага с шкафчиком уже давно нет, кстати.

**Comment by TheUnknownOneGH** [comment]
Гиб - как-то чрезмерно, как по мне. Один идиот с вортексом сможет отправить в иной мир кучу людей из толпы, которым не повезёт оказаться в стенке. Стан (с выталкиванием из стены или без) с переломом рандомной части тела (ну, или с отрыванием любой, кроме гроина и головы, если повышать ставки) - будет нормально. Но это сугубо моё мнение, финальное решение за геймдизайнерами.

**Comment by Voldirs** [comment]
>Бага с шкафчиком уже давно нет, кстати.

![image](https://user-images.githubusercontent.com/4889771/110238342-33522780-7f52-11eb-97eb-5ab78df428b0.png)

**Comment by Destrolaric** [comment]
Бага с перилами тоже

**Comment by Shootnik01** [comment]
Гиб рандомной части тела(втч гроина и головы) - отличный и реалистичный вариант

**Comment by Shootnik01** [comment]
Можно шансы просто уменьшить на них(а можно и не уменьшать, реалистичность же)

**Comment by Shootnik01** [comment]
Телепомидоры - смертельное оружие ассистентов))

**Comment by DarkHunter7756** [comment]
> Телепомидоры - смертельное оружие ассистентов))

Хоть причина будет мутировать в них

**Comment by DarkHunter7756** [comment]
Я предлагаю вариативность:
1. Гиб одной пятки/ладони - 100%
2. Гиб одной конечности или пары пяток/ладоней - 70%
3. Гиб нескольких конечностей - 50%
4. Гиб гроина/мозга - 10%
5. Гиб тела со всеми **вытекающими** последствиями - 5%
Вероятность считается от меньшего к большему
Вроде балансно, не так ли?

**Comment by Shootnik01** [comment]
Норм

**Comment by No-Tips** [comment]
Это будет пиздец, господа. Человек кидает в тебя помидором в драке - ты теряешь пятку, что фактически является смертью. Ты берёшь маячок и закрываешь его стенами - оружие смертоубийства. Звучит очень убого. Просто стан и брут урон.

**Comment by MrMagick2104** [comment]
С точки зрения баланса - фигня, да.

Вортекс будет ещё большей метой, чем сейчас, так как он может телепортировать всех людей в радиусе экрана (+-) в рандомную локацию.

Стоит делать только выталкивание и кратковременный стан (1/3 секунды, например) с небольшим уроном (10-20 брута) на пару случайных конечностей, а лучше вообще не делать, имхо.

Кроме того, в стенку всё равно можно влезть тучей способов, кроме телепорта. На них тоже штрафы накладывать, что-ли?

**Comment by Voldirs** [comment]
>Это будет пиздец, господа. Человек кидает в тебя помидором в драке - ты теряешь пятку, что фактически является смертью. Ты берёшь маячок и закрываешь его стенами - оружие смертоубийства. Звучит очень убого. Просто стан и брут урон.

Помидоры не так уж просто делаются, а так будет стимул пиздить тех кто их выращивает.
Ты берёшь маячок и кидаешь в материю, чем хуже?

>Кроме того, в стенку всё равно можно влезть тучей способов, кроме телепорта. На них тоже штрафы накладывать, что-ли?

Да................

**Comment by Shootnik01** [comment]
> > Это будет пиздец, господа. Человек кидает в тебя помидором в драке - ты теряешь пятку, что фактически является смертью. Ты берёшь маячок и закрываешь его стенами - оружие смертоубийства. Звучит очень убого. Просто стан и брут урон.
> 
> Помидоры не так уж просто делаются, а так будет стимул пиздить тех кто их выращивает.
> Ты берёшь маячок и кидаешь в материю, чем хуже?
> 
> > Кроме того, в стенку всё равно можно влезть тучей способов, кроме телепорта. На них тоже штрафы накладывать, что-ли?
> 
> Да................

👍👍👍

**Comment by MrMagick2104** [comment]
> Да................

Инастагиб стенкой от РЦД - вот это реально тема.

**Comment by DarkHunter7756** [comment]
> Инастагиб стенкой от РЦД - вот это реально тема.

Наконец то инженеры смогут дать отпор ССДшникам

**Comment by MrMagick2104** [comment]
> Наконец то инженеры смогут дать отпор ССДшникам

Да это больше про ниндзю, который ворует РЦД из РИГа СЕ раундстартом, а потом идёт _незметно_ гибать СБ постройкой стены из инвиза.

**Comment by Voldirs** [comment]
Да с инвизом вообще можно дичи много делать. Телепорт, пшикалка с политриником, банальная сетка+меч, гранатки гибающие. И всё незаметно. Да и я предложил и альтернативу, не обязательно гибать.

**Comment by NefrNerf** [comment]
Скорее всего закроется вместе с #4945
