### ISSUE TITLE
Педальное

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#4595]
Педальные генераторы вырабатывают очень мало электричества. Они конечно же не должны вырабатывать много, но когда 20 морд педалит и этого не хватает что бы хотяб один отдел запитать - не круто. Фича с педальными рабами не практичная и вообще просто для виду.

Решение: подкрутить педальным генераторам выработку в пару раз, но увелить расход голода космонавта.

**Comment by Tsurupeta** [comment]
Педальные генераторы создавались как средство перемещения.

**Comment by MrMagick2104** [comment]
Педальные генераторы, так-то, физически не могут вырабатывать много энергии.

В любом случае, бафф не нужен, так как если поиграться со СМЕСами, то даже один педальник может выдавать мегаватт мощности (но очень кратковременно). Двадцать человек выдают 20*10 кВт, т.е. 200 кВт, в то время как станция потребляет примерно половину мегаватта. Это значит, что станцию можно спокойно запитать 20 педальниками, если правильно подключить их к СМЕСам.

**Comment by ArmenianOnyx** [comment]
Но у нас супер педали будущего, пусть вырабатывают чуть больше

**Comment by MrMagick2104** [comment]
> Но у нас супер педали будущего, пусть вырабатывают чуть больше

Десять киловатт - уже очень много, по сравнению с нормальными педалями, которые, от силы, выработать смогут ватт сто (не киловатт), и то, если крутить быстро и оценку делать с огромным преимуществом в сторону большой выработки.
