### ISSUE TITLE
Лицензия для торговца

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#46]
> Добавить лицензию для торговцев. Бумажка, где написано, что вот есть Торговая Компания ВоруйГусей и у них договор о торговле с кораблями и станциями НТ. 
> 
> Опционально: в лицензию пишем большой рандомгенерируемый список кораблей и станций, куда КСН "Исход" попадает с не-100%-ной вероятностью. Чиста чтобы было интересно проверять бумаги.

Также еще было бы неплохо сделать так, чтобы эту лицензию надо было покупать и она имела ограниченный список товаров, которые можно покупать/продавать. То есть если привезти на станцию, например, оружие, то лицензия от СБшников не поможет - надо прятать.

ПРИОРИТЕТНО: лицензия реально нужна. Сейчас торговцев беспрепятственно могут грабить всем бригом. Опциональные штуки можно будет допилить потом.

**Comment by Cinericius** [comment]
Бамп. Лицензия приоритетно нужна, но ее все нет.

**Comment by Fourest** [comment]
> Ко-ко-ко, грябют
Покупаешь оружие@Воруешь@Убиваешь@Продаёшь вещи, снятые с трупов@Покупаешь ещё больше оружия

**Comment by Cinericius** [comment]
Слыш работать

**Comment by ArmolitskiyCarpoeb** [comment]
>Бамп. Лицензия приоритетно нужна, но ее все нет.

>Cinericius added the 🔺приоритет label on 10 Jan

))))))))) за два года нихуя ))))))))))

**Comment by sweden-moose** [comment]
Пришло время покончить с этим иссуем
