### ISSUE TITLE
Вырезать весь Торч

### ISSUE THREAD

**Issue by Cinericius** [ChaoticOnyx/OnyxBay#460]
Нет, не надо набегать на Бей, давайте просто удалим торчеошметки из нашего билда, они все равно не будут у нас нормально работать и смысловой нагрузки не несут, а билд засирают дай боже.

**Comment by SilenceInsider** [comment]
>Легко
>Оптимизация

**Comment by Cinericius** [comment]
Но ведь его легко вырезать и это оптимизирует как минимум размер билда, как максимум еще скорость компиляции. Не вижу противоречий.

**Comment by SilenceInsider** [comment]
Бери@Вырезай

**Comment by Cinericius** [comment]
Вырежу, если кто-нибудь, кто собирается что-нибудь заливать в ближайшем будущем, не вырежет до меня. Все еще не понимаю, что тебе не нравится.

**Comment by PlinHost** [comment]
Это рефакторинг скорее.

**Comment by Cinericius** [comment]
Резонно

**Comment by Cinericius** [comment]
ДОНЕ
