### ISSUE TITLE
Протезы, починка

### ISSUE THREAD

**Issue by Nettledash** [ChaoticOnyx/OnyxBay#461]
Починка сильно поврежденных протезов для киборгов-людей(cyborg human) не работает

При попытке починить протез в порядке: "отвертка-лом-провода/сварка-лом-отвертка" протез банально не чинится, не brute не burn урон не понижаются

Сильно поврежденный протез(на стадии когда он начинает искрить, время от времени перестает функционировать) должен чиниться вышеуказанным порядком, но это не работает, урон не уменьшается

Client Version: 512
Server Revision: 7f9f67f5c02c201e40c9ce62c585f6d0883c35f3 - release - 2019-03-05
Game ID: bY0-bzXL

**Comment by PlinHost** [comment]
Это считается операцией, поэтому работает только когда пациент лежит (rest), желательно на операционном столе.

**Comment by Nettledash** [comment]
Нет, это НЕ РАБОТАЕТ. Все шаги выполнялись на операционном столе, но после шага с сваркой/проводами урон НЕ УМЕНЬШАЛСЯ

**Comment by Epicus7** [comment]
И чего, в билде вообще не работает фикс протезов сейчас? Офигенно

**Comment by TapKo4eB** [comment]
Дык может это ирреперебл травма была, чё спешить. Нормально всё работает и чинится, чё шумиху наводишь. Если было ирреперебл, то только ампутацией и новую приноси.

**Comment by Epicus7** [comment]
> [23:56] TaTarin: только что перепроверил протезы
> [23:56] TaTarin: всё нормально чинится
> [23:56] TaTarin: так что иссуй :wheelchair:

Закрываю тогда
