### ISSUE TITLE
Продолжаем починку мага.

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#4621]
### Улучшение
Перечислю то, что я хочу изменить и добавить:

- Corrupt Form в текущей форме не является чем-то играбельным. Улучшить планирую увеличив скорость до уровня космонавтика, ХП поднять в три раза, причиной тому является его крайне слабая выживаемость. И самое главное, дать ему возможность каста спеллов мага, ибо по превращению вы не являетесь человеком, следовательно не можете кастовать.

- Баттлмаг имеет слишком смешное количество очков, предлагаю увеличить до 9. 

- Переделаю урон у меча баттлмага посмотрю, что там с ним не так.

- Рефактор друида (Отдельное обсуждение)

**Comment by Destrolaric** [comment]
Можете добавить ваши предложения фиксов, ибо не всех магов я успел потыкать.

**Comment by O0oMaximo0O** [comment]
В Ониксе я по сравнению с творящими невообразимое(по моим меркам) крайне неопытен, посему сей коммент можно смело игнорировать.

Играл за мага раза 3. Всегда брал боевого из-за скафандра.
На мой взгляд, боевой маг нацелен на прямое столкновение и продолжительный бой, соответственно должен выдавать постоянный нормальный урон(есть) и иметь хорошую защиту/щит/сопротивление(есть:скаф,щит,аура), а также возможность отступить(пасс применить сложно: либо недалеко, либо долго и видно куда) и исцелиться(дохлое,но есть).

Corrupt Form не использовал, но предложение выглядит логично. Боевая форма мага без магии звучит не очень.
Думаю, Ей Нах подходит только Варлоку, это явно чёрная запретная магия). Боевому не хватает телепорта.
Прощу прощения, если написано не по делу или вообще писать комментарии кому угодно где угодно нельзя.

**Comment by LordNest** [comment]
Батлмагу требутеся:
-Blink для экстренной телепортации, так как кроме Passage у него нет никаких телепортирующих заклинаний. Скролл не в счёт - это совсем экстренная телепортация в клоунскую, к тому же лимитированная. Давать Джаунт или что-то ещё будет имбовее, но блинк+пассаж могут значительно повысить мобильность не только на сокращение, но и на разрыв дистанции. 
-Замена или улучшения Mirage. Так как призраки карпов это всё ещё призраки карпов. От него нет никакого практического применения, кроме как прятаться от них за 2-3 выстрелами, так как лопаются они с 1 попадания (что логично)
-Выдать бы от варлока Burning grip. Чисто для сражений против большого количества СБ/угнетения одинокого патрульного.

**Comment by MrMagick2104** [comment]
> Замена или улучшения Mirage

Для миража можно было бы вызывать карпов, которые всё ещё лопаются от пары выстрелов (как и обычные карпы, кстати), но бегущие на врага и наносящие голоурон/пейнурон. Миражи глубокого погружения.

Альтернативно, можно впилить возможность создавать миражи с переключаемым прямым контролем и кастомизацией того, как он выглядит: дженерик предметы, по типу стенок (непрозрачных), стульев и прочих табуреток, на более высоком уровне возможность управлять миражом через какой-нибудь вёрб вселения, а также создавать миражи дженерик инженеров/СБ/учёных/капитанов и конкретных предметов (или мобов). На самом высоком уровне - либо возможность давать миражам атаковать как в первой идее, либо что-нибудь смешное по типу перманентных миражей.



А у текущих варлоков нет Элдрих бласта?

**Comment by Artemonim** [comment]
Актуально ли это после последней переработки магов?
