### ISSUE TITLE
Интегральный концентратор сжирает пробелы

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#4626]
В конце и перед буквами исчезают пробелы, например, " что-то " + " ещё что-то", то получится "что-тоещё что-то".

**Comment by HentaiStorm** [comment]
Достер починил ужо в #4393

**Comment by Doster-d** [comment]
> Достер починил ужо в #4393 

Вы не правы.

**Comment by HentaiStorm** [comment]
Вах вах, как так?

**Comment by DarkHunter7756** [comment]
Это не баг. Просто бери побольше конценератор и ставь дебаггером пробелы между выражениями
