### ISSUE TITLE
И снова мутации вирусологии

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#4637]
Допустим, у нас есть схема мутаций A->B->C->D, минимальные стадии симптомов 1,1,2,3 соответственно. У нас есть вирус с симптомом А на 3 стадии, если мы мутируем его в В, то этот В принимает свою минимальную стадию 1, а не 3, какая была у исходного симптома. На примере, у нас есть Facial Hypertrichosis 3 стадия, но при мутации мы получаем Unified Appearance Syndrome 1 стадии. 
Возникает вопрос, оправдана ли такая ебота с мутациям, т.к. отнимает много времени на аккуратные сдвиги и мутацию на нужной стадии. Или всё же это баг? Я ожидал, что если у нас Facial Hypertrichosis 3, то и Unified Appearance Syndrome мутирует на 3 стадию, но это оказалось не так. 
@kemperhun

**Comment by Shootnik01** [comment]
Это не фича? Теперь же можно создать кучу симптомов в одном вирусе
