### ISSUE TITLE
Make Singularity Great Again

### ISSUE THREAD

**Issue by TobyThorne** [ChaoticOnyx/OnyxBay#467]
Починить излучение сингулярностью радиации (сейчас - почти не фонит, пока не вырастет до размеров хрущёвки) и, опционально, заменить ею материю. 
Ну и материя - скучное говно, включающееся за пару минут (кроме тех случаев, когда кто-то возится два часа ради шести гигаватт). Для синги хоть нужно выкатываться в космос и включать щиты.
I dunno *shrug

**Comment by Cinericius** [comment]
На Эклипсе синга, надо обновить контент на нем и накатить его.

**Comment by Firefroge** [comment]
А может не надо сингу?
А то вспоминая как чудо-инженеры её умудрялись проёбывать и какие были в итоге последствия.

**Comment by Jhonas25** [comment]
Знаете что, кажется, я знаю компромисс между выходом в космос и анти-долбоём-инженегр систем, ебашьте заместо материи СОЛЯРКИ, крута-жи, солярки не смогут сбежать, а в космос прийдётся выходить и они нр будут настраиваться за пять минут. :omegalul:

**Comment by Voldirs** [comment]
>включающееся за пару минут
Так это же наоборот пиздато, не надо тратить время на аутирование, запилил и всё, творишь экшон.
