### ISSUE TITLE
Оружие стреляет только в интенте харма.

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#4686]
Напомните, у нас станция для постоянных КСочек? Почему я не могу просто заряженным стволом потыкать по человеку, без угрозы прошить ему голову? По идее интент хелпа должен считаться предохранителем.

**Comment by TheUnknownOneGH** [comment]
> я не могу просто заряженным стволом потыкать по человеку, без угрозы прошить ему голову?

Можешь. Оружие в упор стреляет только на харме, на хелпе - тыкаешь его, на дизарме - удар прикладом, на грабе - парирование. На дистанции, конечно, стреляет на всех интентах.
Если делать, то тогда лучше чтобы стреляло на любом интенте кроме хелпа - про это даже в экзамине оружия написано.

**Comment by No-Tips** [comment]
Ес чо у нас оружие на хелпе впритык не стреляет, а трогает.
