### ISSUE TITLE
время до начала раунда в лобби медленнее реального

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#4693]
### Описание бага
4 сом ризон общее время в игре (до начала раунда, прошедшее время игры и возможно что-то другое) движется медленнее реального. Алсо есть десинхрон между локал таймом и раунд дюрейшеном

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. заходишь в раундстарт лобби
2. достаёшь секундомер
3. смотришь на обратный отсчёт и считаешь

### Ожидаемое поведение
перестать гнуть временной-континуум и выровнять ход времени на ониксе

**Comment by No-Tips** [comment]
Может, дело в том, что время, что считается ингейм - это условная разница в тиках, что постоянно меняется по причине лагов\фризов\прогрузок? Могу подтвердить, что такая проблема есть. Но стоит ли этот баг фиксить? Можно оправдать это тем, что это свое условное время, и оно никак не связано с ИРЛ.

**Comment by TapKo4eB** [comment]
чувак я конечно понимаю что время относительно согласно законом физики но тем не менее с точки зрения наблюдателя находящегося в одном месте (часы) оно всегда идёт одинакого
соотественно часы тикера нарушают законы физики и ты идёшь н а h u y

**Comment by Artemonim** [comment]
Рассинхрон реального и виртуального времени может происходить при зависании и лагах сервера. И тут нужно уже какую-то систему синхронизации вводить по запросу фичи.

**Comment by Artemonim** [comment]
И да, я проверил на локалке - за 9 минут от инициализации сервера рассинхрона не произошло даже в пределах нескольких секунд

**Comment by Tsurupeta** [comment]
так у тебя локалка не лагает
