### ISSUE TITLE
незапитанный инъектор в атмосе эксодуса

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#4696]
сабж см пикрелетед
фиксите зоны

![pic](https://user-images.githubusercontent.com/48761132/112143597-29365700-8be9-11eb-8cca-20ca8122b66e.png)

**Comment by hard-res3t** [comment]
Призываю инженеролобби.
Что вообще оно должно делать?? Воздух из атмоса в космос отправлять?
Если да, то зачем если сверху слева такой уже есть.
![image](https://user-images.githubusercontent.com/59255670/116722101-acb44680-a9e6-11eb-9a47-dfed1e22296b.png)

**Comment by Doster-d** [comment]
> Призываю инженеролобби.
> Что вообще оно должно делать?? Воздух из атмоса в космос отправлять?
> Если да, то зачем если сверху слева такой уже есть.
> ![image](https://user-images.githubusercontent.com/59255670/116722101-acb44680-a9e6-11eb-9a47-dfed1e22296b.png)
> 

Этот инъектор служит выбросом газов, которые не прошли сортировку по красной линии (плазма, кислород и т.д.), сверху слева для выброса из оранжевой линии насколько я помню.

**Comment by No-Tips** [comment]
А что фиксить-то.. Там просто тайл зоны добавить. Но всем настолько все это время было впадлу это делать, что уже очень долгое время этот инжектор не работает. Поэтому и реликвия.

Предлагаю закрыть иссуй по причине "Инженеры будут очень злы от того, что реликвия будет уничтожена".

**Comment by hard-res3t** [comment]
Согласен. Надо закрыть.

**Comment by TapKo4eB** [comment]
лол не можете одну зону поменять

**Comment by hard-res3t** [comment]
![FFFFFUUUUUUU-](https://user-images.githubusercontent.com/59255670/116819158-6c380280-ab77-11eb-994a-52b3cbd2f362.png)
