### ISSUE TITLE
Реворк work-визы из лоадаута

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#47]
> Щас она тупая и непонятная, да еще и от SolGov, которого у нас в бэке нет. Короче в нынешнем виде она вообще совершенно точно не нужна. Чо я предлагаю сделать: выпилить ее из лоадаута, а не членам НТ сделать визы, в которых написано, що НТ договорилась с их корпорацией и им можно работать на объектах НТ. И их добавлять сразу в рюкзак.

В эту визу писать прямо имя персонажа, компанию из которой он прибыл, родную планету, возраст и так далее. Papers please в 2d космонавтиках, короче.

**Comment by TobyThorne** [comment]
- В лодауте визы больше нет.
- Не-члены НТ - это или мерчанты со своей лицензией, или всякие нюкеры-воксы со своими пушками.
- Одобрено в доисторические имена.
Думаю, можно закрывать.

**Comment by MrMagick2104** [comment]
> Не-члены НТ - это или мерчанты со своей лицензией, или всякие нюкеры-воксы со своими пушками.

В чар сетапе всё ещё можно выбрать другую фракцию и ****гражданство****.
![image](https://user-images.githubusercontent.com/58848742/106454449-cf909680-649b-11eb-8bd0-f867f6155b25.png)
![image](https://user-images.githubusercontent.com/58848742/106454481-de774900-649b-11eb-8fa3-2b1997a6eb27.png)
![image](https://user-images.githubusercontent.com/58848742/106453916-0fa34980-649b-11eb-9f53-111a24e87194.png)

Гражданам других стран, по определению, нужна виза для работы.
Ни у граждан других стран, ни у членов других факций виз нет, так что выполненным иссуй назвать нельзя.

> Одобрено в доисторические имена.

Геймдизайнерской командой же, всё равно. В виде Панча.
Если и закрывать, то решением двух геймдизайнеров. Но зачем закрывать?
