### ISSUE TITLE
слизебатарейки не самозаряжающиеся, не высокоемкие

### ISSUE THREAD

**Issue by Shirlineyn** [ChaoticOnyx/OnyxBay#4740]
ожидание:
![image](https://user-images.githubusercontent.com/26092405/112921934-4bae0000-9114-11eb-9efb-cfa1bf5d5199.png)
реальность:
![image](https://user-images.githubusercontent.com/26092405/112922268-ddb60880-9114-11eb-9b90-394e240dfa61.png)

**Comment by O0oMaximo0O** [comment]
Давно пора что-то решать с этим... А, статья-то в архиве, и метроиды у нас давно. Можно закрывать
