### ISSUE TITLE
БАГ: Один ивонт с отключением всех энергоисточников (СМЕС, АПС) заставляет Фронтир уплывать в сингулярность.

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#4744]
Ивент Automated Grid Check вызывает отключение СМЕСов. Вырубается СМЕС двигателя - вырубаются эмиттеры - вырубаются щиты - синга съедает все и вся. Вообще, это решается обычным присоединенем пары проводков коллекторов к проводкам АПС комнаты и эмиттеров. Думаю, это надо впилить в саму карту.

**Comment by hard-res3t** [comment]
Вероятно починили в #4667
> Добавил наружному АПЦ у синги емп-защиту

**Comment by NefrNerf** [comment]
Ну раз починили в #4667 значит починили, узнаем если опять уплывет
