### ISSUE TITLE
Выставка или музей со статуями Onyx Awards 2019 и 2020

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#4751]
_"Таких друзей — за хуй, да в музей"_

Предлагаю восстановить музейную секцию на ЦК с победителями Onyx Awards 2019 и 2020 годов, по типу той, что была в 2018. Это поощрит активных участников сообщества, разнообразит локацию ЦК и в целом будет довольно забавно.

**Comment by MalinaGirl** [comment]
кринжовая хуйня не нужна

**Comment by Ershovdi** [comment]
да.

**Comment by Judge1987** [comment]
нужна.
