### ISSUE TITLE
Ротация карт

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4758]
По окончанию раунда/во время начала нового раунда активировать автоматическое голосование на выбор следующей карты: NSS Exodus или Frontier

[Из коллекции фич "Спизжено из дискорда, ибо бота не чинят"]. 47 репап

**Comment by Ershovdi** [comment]
Будет мешать, потому что все будут выбирать Исход, потому что на фронтире сложнее играть с онлайном в 70 игроков, и наоборот, слишком уныло играть на исходе с онлайном 10 человек

**Comment by DarkHunter7756** [comment]
Проскакивала идея о том, чтобы ввести данное голосование только при определенном онлайне [Онлайн<N]

**Comment by Primudash** [comment]
Осуществлено!
