### ISSUE TITLE
Вернуть карликов

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4760]
Не надо сильно заморачиваться, просто сделайте трейт на низкий рост, который будет уменьшать scale (или что там) на 10-15%. Если уж развоняетесь из-за баланса (мол маленький спрайт), то можно тогда еще и скорость понизить на 5%.

Либо сделать ползунок (просто выбор цифры) от 0 до -10%, чтобы можно было немного уменьшить свой рост.

[Из коллекции фич "Спизжено из дискорда, ибо бота не чинят"]. 34 репапа

**Comment by Shootnik01** [comment]
И увеличение тоже стоит добавить - гигантики)
