### ISSUE TITLE
Сделать стационарные медицинские сканеры разбираемые

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4761]
Большая часть сервера терпеть не может, когда их молча кладут в сканер и затем тащат на операцию. Дайте возможность активным космонавтам разбирать сканеры и медицинский засияет по-новому, теперь СМО заставит тебя общаться с людьми, а еще неугомонные серые пижамы могут пользоваться тем, что ты не следишь за отделом и демонтировать тебе вундервафлю.
Астрологи объявят неделю без медсканеров как только эта фича будет добавлена в игру.

[Из коллекции фич "Спизжено из дискорда, ибо бота не чинят"]. 56 репапов

**Comment by NefrNerf** [comment]
Скоро введут в #5589

**Comment by TimErmolt** [comment]
#5589 замёржен, закрывайте.
