### ISSUE TITLE
Убрать из операционных стационарные сканеры

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#4762]
Будем честны - медицинский должен страдать, хирурги не исключение. Забыл сделать печатную форму в сканере среди кучи народа и нуждаешься в ней - страдай. В операционке стоит шикарный мониторчик, который и так показывает как дела у твоего пациента.

[Из коллекции фич "Спизжено из дискорда, ибо бота не чинят"]. 43 репапа

**Comment by kcalbCube** [comment]
ну чё пацаны, погнали

**Comment by Mrbuble** [comment]
не актуально на исходе отсутствуют
![изображение](https://user-images.githubusercontent.com/87055072/161393176-39a62bab-b1d9-4a71-859f-6062f617cfad.png)

**Comment by Mrbuble** [comment]
не актуально для исхода, на фронтире в единственной операционной стоит мед сканер
![изображение](https://user-images.githubusercontent.com/87055072/161393262-90ecf6e3-a5f9-4c84-8428-0822634989a6.png)

**Comment by Mrbuble** [comment]
абсолютно не актуально, на фронтире также отсутствуют сканеры в операционных
