### ISSUE TITLE
Anomaly Power Utiliser не работают

### ISSUE THREAD

**Issue by Vostok-Odin** [ChaoticOnyx/OnyxBay#480]
Как известно, результатом жизнедеятельности ксеноархеологов на орбите Эксодуса являются большие артефакты, обладающие особыми свойствами. Заботливые разработчики оставили ксеноархеологам машинерию, способную забирать свойства больших артефактов, заряжать их энергией особые батарейки и использовать в Anomaly Power Utiliser (APU). Однако APU с заряженной аномальной батареей отказывается работать, позволяя выставить настройки но замертво зависая при нажатии кнопки Старт. После нажатия этой кнопки, контекстное меню APU не открывается, не давая ни выставить новые настройки, ни вытащить батарею, превращая APU в бесполезную иконку.
И ещё не помешало бы добавить в прото-автолаты возможность печатать эти батарейки.
![Будни аномалиста](https://user-images.githubusercontent.com/38241773/54867757-08865d00-4d95-11e9-9e7a-659715883be9.png)

**Comment by Vostok-Odin** [comment]
Странно. Через раунд APU начали работать, но сломались после одного использования.

**Comment by RichardJones1** [comment]
Если будете фиксить, советую взять код с /vg/, там ребята хорошо сделали.

**Comment by Cinericius** [comment]
Мы собственно портировали ксеноархеологию с ВГ и это, вероятно, косяки порта.

**Comment by Jhonas25** [comment]
Ещё один пример, почему этот билд называют чудобилдом.

**Comment by DeltaEpsilon7787** [comment]
Не лезьте в аномалистику, она уже давно сломана и почти не несет никакой функции.

**Comment by Vostok-Odin** [comment]
Можно же починить и заставить работать, тем более первые шаги уже сделаны.

**Comment by DeltaEpsilon7787** [comment]
Нельзя, у аномалистики фундаментальные проблемы в целом.
