### ISSUE TITLE
Генокрады: Невозможность инфеста

### ISSUE THREAD

**Issue by BooJ1K** [ChaoticOnyx/OnyxBay#481]
**Описание бага**
Находясь в частях тела или будучи хедкрабом, невозможно заинфестить тело человека живого/мертвого.
**Воспроизведение**
Шаги чтобы воспроизвести баг:
Это случается рандомно: Игра просто считает, что мы кого-то инфестим.
**Ожидаемое поведение**
В нормальной ситуации, При нажатия инфеста, наша "рука/нога/торс/хедкраб" должен встать на одну клетку с "телом" и пойдёт "шкала действия" 
Если забаговалось, то происходит следующее – Наш Юнит стоит на месте и в чат пишется "We are already infesting!"
**Характеристики**
 - OS: Windows 10 education
 - Версия клиента 512.1464
 - Версия сервера 512
 - ID игры   ##bZq-ckvN

**Дополнительная информация**
Случался баг уже два раза, 
1) Меня тащили грабом и я заранее переместил свою био структуру в ногу и воспользовался способность "Body Disjunction" после этого я не мог никого заинфестить. 
2) Мне удалось вселиться в одного человека, но второй раз, когда я оторвался от тела, мне писало, что я кого-то пытаюсь заразить.

**Comment by ZerlGray** [comment]
А эта фигня уже не пофикшена?

**Comment by Jhonas25** [comment]
Если висит, значит нет.

**Comment by Cinericius** [comment]
А мне кажется пофиксили, да

**Comment by Voldirs** [comment]
Кажется или точно пофиксили? Разные вещи же

**Comment by ZerlGray** [comment]
Судя по всему, инфест все же залипает, но по какой то другой причине и при невыясненных обстоятельствах. На локалке вроде все роботаит. В игре говорят, что залипало.

**Comment by Cinericius** [comment]
А давно залипало последний раз?
