### ISSUE TITLE
Автоматы раздачи инженерных вещей на базе торговцев не взломаны.

### ISSUE THREAD

**Issue by SanecMan** [ChaoticOnyx/OnyxBay#482]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Автоматы раздачи инженерных вещей на базе торговцев не взломаны.

**Опишите ваше решение проблемы**
Ну чё добавить emagged=1 вроде я вам чё дев я вообще багрепорт пишу.

**Опишите альтернативы, о которых вы думали**
Я хз.

**Дополнительная информация**
Я б сам сделал и помог но мне жутко лень.

**Comment by Voldirs** [comment]
Сэйм щит с раздатчиком бухла там же

**Comment by kreeperHLC** [comment]
#716
