### ISSUE TITLE
Отдельное логирование для публичного хаба.

### ISSUE THREAD

**Issue by MorJams** [ChaoticOnyx/OnyxBay#4827]
Создать новый лог-файл "story.log", в который должна дублироваться вся IC информация раунда - say, emote, все игровые события.

Цель - выделить логи без такой секретной информации, как IPшники и сикеи. Такой новый лог будет публиковаться в хабе.

Предыдущее описание:
>### Улучшение
> Всякие люди без педалей должны иметь логи прошлого раунда БЕЗ айпишников, айдишников, куки, ЕАМС, педального чата (под вопросом) и прочей конфиденциальной и педальной информацией.

> ### Решение
> Как Эпикус и предложил, запилить отдельный прок вроде story_log с IC информацией

**Comment by Doster-d** [comment]
Товарищ сенатор, Вы репой ошиблись! Репа Форума на 2 блока ниже!

**Comment by MorJams** [comment]
> Товарищ сенатор, Вы репой ошиблись! Репа Форума на 2 блока ниже!

Изменения касаются билда, сладкий.

**Comment by Epicus7** [comment]
Обновил описание

**Comment by MorJams** [comment]
> без такой секретной информации, как IPшники и сикеи.

Страшно. Вместо них будут полу-рандомные ник-айди?
