### ISSUE TITLE
Добавить джоббаны на дронов

### ISSUE THREAD

**Issue by Mark-Silverstein** [ChaoticOnyx/OnyxBay#4852]
### Проблема, которую решает улучшение:
Любой  бан на синтетиков не ограничивает заход человека за дрона (который по сути является отдельной синтетической ролью со своими законами). А как известно, нередки случаи, когда именно на них люди намеренно нарушают правила.

### Решение:
Вынести отдельный джоб-бан на дронов в бан-панель.

**Comment by Tsurupeta** [comment]
Ну это не улучшение, а БАГ того, что таких банов НЕТ.

**Comment by MrMagick2104** [comment]
> Ну это не улучшение, а БАГ того, что таких банов НЕТ.

Отсутствие чего-либо в билде, если банально не закодили - не баг.

Багом тут может быть то, что бан на синтетиков не обрезает возможность за дрона зайти.
