### ISSUE TITLE
проблемы педального Aghost'a или "какого хуя у меня не работает F11"

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#4856]
по какой-то совершенно необъяснимой и неизвестной причине, **порой** при использовании агхоста, `гост` на которого ссылается вар `teleop` внутри `моба` оказывается в `нулях` но `референс` на него `не удаляется`, из-за чего мы получаем такую смешную ошибку

```
[21:02:29] Runtime in admin_verbs.dm,458: Cannot modify null.admin_ghosted.
  proc name: Aghost (/client/proc/admin_ghost)
  usr: Medical Cyborg-997 (/mob/living/silicon/robot) ([0x3000089]) (the floor) (145,111,2) (/turf/simulated/floor/tiled/white) (tapko4eb)
  usr.loc: The floor (/turf/simulated/floor/tiled/white) ([0x1016c23]) (145,111,2) (/area/medical/medbay3)
  src: TapKo4eB (/client)
  call stack:
  TapKo4eB (/client): Aghost()
  ```

так вот, я ебал работать с куделами, пусть кто-нибудь сделает это за меня, самое интересное по ссылкам ниже дальше сами разберётесь
https://github.com/ChaoticOnyx/OnyxBay/blob/d00c9906468c597f984242ef599588c1fefe94cd/code/modules/admin/admin_verbs.dm#L455-L462
https://github.com/ChaoticOnyx/OnyxBay/blob/d00c9906468c597f984242ef599588c1fefe94cd/code/modules/mob/observer/ghost/ghost.dm#L180-L185

**Comment by Primudash** [comment]
Педалю три года и ни разу такого не встречал
wtf?
Не воспроизводится

**Comment by Primudash** [comment]
Педалю три года и ни разу такого не встречал
wtf?
Не воспроизводится
