### ISSUE TITLE
Нерфобафы синтов

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#4884]
Предлагаю увеличить физическую уязвимость и уменьшить ЭМИ уязвимость синтам.

Физически синтов нерфануть, сделать так, чтобы при уроне по конечностям и телу тратился какой-то заряд батарейки. Например, пуля .45 калибр в руку потратит 50 единиц заряда батарейки и нанесет чуть меньше брутдамага, чем обычному человеку.

ЭМИ заряды не будут уничтожать мозг синта за один выстрел. Вместо этого, будут отнимать 100 единиц заряда из пистолетика, 150 из карабина. Наверное, там какие-то ограничения можно поставить в код. 

С точки зрения геймдиза сделать так, чтобы сначала синта разряжали, он терял сознание, а потом его добивают по башке. Возможно, стоит добавить возможность ОЧЕНЬ медленно передвигаться в разряженном состоянии, чтоб до станции зарядки добраться.

**Comment by HonkyDonky** [comment]
С этим правда что-то стоило бы сделать. 
Там синтетика разорвали с одного выстрела из ионного пистолетика. Звучит не очень смешно.

**Comment by Ershovdi** [comment]
Если тупо убрать ЭМИ убийство синта одним кликом, то синты будут дизбалансными и всем доступными, а это плохо. Поэтому тупо вводить синтов в инвалидное состояние ЭМИ зарядами, как в Деус Эксе каком нибудь - хорошая альтернатива. Но это моё мнение.

**Comment by MrMagick2104** [comment]
Решение такое себе, так как у нас есть научка и блюспейс батарейки, имхо.
Поставил себе блюспейс-батарейку -> стал терминатором.
Есть и более хорошие (пусть и не более простые) [решения](https://github.com/ChaoticOnyx/OnyxBay/issues/1220) проблемы синтов.


Альтернативно, можно просто убрать бёрндамаг синтам при попадании ионки, заменив его долговременным станом (от 15 до 40 секунд, с рандомом, ест-сна) и разрядом 1/4 (3 или 5) заряда батарейки при попадании, либо резистать урон от ионки при ношении одежды с сименсом, равным нулю, а не делать такие приколы.

**Comment by Shootnik01** [comment]
Синты должны страдать.
