### ISSUE TITLE
На Фронтире съезжает картинка космоса при положении по Х более 256.

### ISSUE THREAD

**Issue by Altehor** [ChaoticOnyx/OnyxBay#4894]
### Описание бага
При положении по X координате более 256 картинка космоса постепенно съезжает влево. Кажется, эксклюзивно на Фронтире.

### Воспроизведение
1. Запускаем Фронтир.
2. Заходим в раунд гостом.
3. Летим направо до упора.
 
### Ожидаемое поведение
Наблюдаем белую полосу, наползающую с правого края.

### Скриншоты
https://drive.google.com/file/d/1IUkViTkBRsZ-rDHFsuBGqjt4qBJmqI-V/view?usp=sharing

### (Опционально) Характеристики
 - OS: Windows
 - Версия клиента 513.1542
 - Версия сервера 9a8561c43ba0be332c19272a5aa505ba445b0f25 - release/eos - 2021-04-09
 - ID игры cbx-b9Pc

**Comment by MaxTheAstronaut** [comment]
![dreamseeker_sjSGsmn2g1](https://user-images.githubusercontent.com/47484306/132114745-8bb54913-501f-49dc-ba7a-9d5551eb58b9.png)
