### ISSUE TITLE
Взять тайл с решеткой для корридоров с других билдов

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#49]
Взять этот тайл с Торча/Маринов
![default](https://user-images.githubusercontent.com/6437377/43946860-a78811dc-9cb0-11e8-920d-a4d5df7debd8.png)

**Comment by Epicus7** [comment]
Эти тайлы не подходят под наш стиль. Нужно рисовать

**Comment by Cinericius** [comment]
Скинь сюда ПНГшку или ДМИшку самого спрайта. Я мож быть попробую его переделать под наши полы.

**Comment by Cinericius** [comment]
Закрываю до появления спрайтов. Собсно хотите чот менять в визуале - постите со спрайтом или хотя бы договаривайтесь с кем-то из спрайтеров заранее.
