### ISSUE TITLE
Вы слишком много болтали

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#492]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Нельзя вырезать язык, если уж идти по дороге луфчанки то качественно.

**Опишите ваше решение проблемы**
Запилить орган - язык, вставить его в башню, дать возможность его вырезать (и вешать на ниточку)

**Опишите альтернативы, о которых вы думали**
Никаких

**Дополнительная информация**
As simple as that. Ну надо сделать заменялку фраз в зависимости от урона по языку, чем больше урона, тем больше букв "прожёвывается"

**Comment by LLIkolnik** [comment]
Ещё запилить возможность его прокалывать, чтобы всякие трапы радовались.
