### ISSUE TITLE
Преф на раунденд репорт

### ISSUE THREAD

**Issue by TobyThorne** [ChaoticOnyx/OnyxBay#4928]
### Улучшение
Сделать преф для вывода раунденд репорта.

### Решение
Сейчас раунденд репорт выводится И в чат, И в отдельное окошко. Надо сделать преф для переключения между двумя вариантами. А ещё прикольнее - опции для вывода и туда и туда и убирания вывода вовсе.

### (Опционально) Альтернативы
Выпилить к хуям отдельное окошко, ибо зачем оно нужно. Но лучше префы. Мало ли, какие извращенцы бывают.

### (Опционально) Дополнительная информация
Да.

**Comment by Zert0X** [comment]
ты бы ещё вспомнил титры, которые у нас в билде есть
