### ISSUE TITLE
Хитмаркеры проигрываются для всех

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#493]
**Описание бага**
Хитмаркеры проигрываются для всех

**Воспроизведение**
Просто побыть рядом с перестрелкой

**Ожидаемое поведение**
Хитмаркеры должны проигрываться только для того кто стрелял

**Дополнительная информация**
Выпилите эту хуйню

**Comment by Cinericius** [comment]
А разве стоящие рядом космонавтики не должны видеть влет маслин в товарищей по несчастью?

**Comment by Voldirs** [comment]
Ну не так убого же

**Comment by Cinericius** [comment]
Меняем хитмаркеры на брызги крови?)))00)))

**Comment by Voldirs** [comment]
Бля не, давай лучше просто текст в чатике))))))

**Comment by HalilDaBlack** [comment]
Текст проебать легко, визуал необходим

**Comment by Voldirs** [comment]
Лол, всмысле текст проебать легко, это похоже на тех людей которые таскают людей пуллом и тупо не видят что им в чатике срёт, что не надо так делать если не хочешь убить человека. Неужели жирные красные буквы так незаметны?

**Comment by Voldirs** [comment]
Мммм, поебота задумана по дизайну, ну пасибо
