### ISSUE TITLE
SS for lighting

### ISSUE THREAD

**Issue by TobyThorne** [ChaoticOnyx/OnyxBay#499]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Нынешнее освещение мало того, что забагованно, так ещё и дичайше грузит сервер.

**Опишите ваше решение проблемы**
Добавить SS для освещения. С очередями и прочими радостями. Опционально - ещё и портировать освещение с какой-нибудь Европы.

**Опишите альтернативы, о которых вы думали**
Потайловое освещение, но это слишком смешно.

**Дополнительная информация**
Мемори, тыжбэтмен, найди свежую кровь для Фиксик-Сквада.

**Comment by Megmeehey** [comment]
#696
