### ISSUE TITLE
Киборг(научный) не может положить листы в автолат с помощью sheet loader.

### ISSUE THREAD

**Issue by O0oMaximo0O** [ChaoticOnyx/OnyxBay#5009]
### Описание бага
Киборг(научный) не может положить листы(конкретно в момент обнаружения бага - стекла) в автолат с помощью sheet loader манипулятора.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем листы материала sheet loader манипулятором.
2. Нажимаем им на автолат
3. Видим ошибку "You can't place that item inside autolathe."

### Ожидаемое поведение
Листы загружены в автолат.

### (Опционально) Дополнительная информация
Было обсуждение бага в ДС с вариантом решения:
https://discord.com/channels/414832443384659968/447559366237880341/837033661399302165
```c#
/obj/item/weapon/gripper/no_use/loader //This is used to disallow building with metal.
    name = "sheet loader"
    desc = "A specialized loading device, designed to pick up and insert sheets of materials inside machines."
    icon_state = "gripper-sheet"

    can_hold = list(
        /obj/item/stack/material
        )

    if(!wrapper)
        return wrapper

    return FALSE
```
Хотя наверно хватит просто 
```c#
return wrapper
```

**Comment by hard-res3t** [comment]
Вообще предложенное решение не работает (да и не должно, если я правильно понимаю).
Мне кажется проблема где-то в автолате. В прото он ведь нормально загружает. Может строчки нет которая отвечала бы за принятие из рук борготы.

**Comment by HonkyDonky** [comment]
Проблема в самом научном киборге. Его нужно удалить.

**Comment by kreeperHLC** [comment]
> Проблема в самом научном киборге. Его нужно удалить.

^^^ Поддерживаю человека выше. Этот борг - всё РнД в кармашке. Зачем он нужен, почему его вообще создали - непонятно

**Comment by DarkHunter7756** [comment]
> Проблема в самом научном киборге. Его нужно удалить.

не понел. А как тогда на боргах играть? 0_0

**Comment by kreeperHLC** [comment]
> > Проблема в самом научном киборге. Его нужно удалить.
> 
> не понел. А как тогда на боргах играть? 0_0

Ну если тебе других недостаточно, то земля тебе пухом

**Comment by DarkHunter7756** [comment]
> > Проблема в самом научном киборге. Его нужно удалить.
> 
> ^^^ Поддерживаю человека выше. Этот борг - всё РнД в кармашке. Зачем он нужен, почему его вообще создали - непонятно

Охранный борг - весь бриг в кармашке
Мед борг - весь мед в кармашке
Инженерный борг - весь инженерный в кармашке
Что дальше? Удалим?

**Comment by HonkyDonky** [comment]
Оставляем стандартного киборга. Его достаточно.

**Comment by kreeperHLC** [comment]
> > > Проблема в самом научном киборге. Его нужно удалить.
> > 
> > 
> > ^^^ Поддерживаю человека выше. Этот борг - всё РнД в кармашке. Зачем он нужен, почему его вообще создали - непонятно
> 
> Охранный борг - весь бриг в кармашке
> Мед борг - весь мед в кармашке
> Инженерный борг - весь инженерный в кармашке
> Что дальше? Удалим?

У научного реально всё РнД в кармашке. Только протолат забыли добавить, чтобы совсем весело было.

**Comment by DarkHunter7756** [comment]
Давайте перейдем в дискорд

**Comment by O0oMaximo0O** [comment]
Проследил цепочку вызовов автолата, наверно нашёл место где возникает проблема:
Автолат:
```c#
user.canUnEquip(eating)
    canUnEquip(obj/item/I)
        I.mob_can_unequip(src, slot)
            mob_can_unequip(mob/M, slot, disable_warning = 0)
                M.slot_is_accessible(slot, src, disable_warning? null : M)
                    /mob/living/carbon/human/slot_is_accessible(slot, obj/item/I, mob/user=null)
 ```
У киборга как `/mob/living/silicon/robot` нет функции slot_is_accessible.

> Вообще предложенное решение не работает (да и не должно, если я правильно понимаю).
> Мне кажется проблема где-то в автолате. В прото он ведь нормально загружает. Может строчки нет которая отвечала бы за принятие из рук борготы.
Ты был прав.
Наверно надо впилить проверку типа моба в автолат.

Возможно так?
```c#
if(iscarbon(user) && !user.canUnEquip(eating))
    to_chat(user, "You can't place that item inside \the [src].")
    return
```

**Comment by Zert0X** [comment]
Сообственно говоря как у нас работает АВТОЛАТ, он проверяет может ли user, дропнуть/положить куда-то то, что у него в руке, т.к. в руке у борга не листы метала а sheet loader то соотвественно ничего не происходит ибо дропнуть и сложить он его не может АВТОЛАТ ругается, что Вы такое положить не можете
