### ISSUE TITLE
Шахматы на голодек

### ISSUE THREAD

**Issue by Vostok-Odin** [ChaoticOnyx/OnyxBay#502]
Добавьте шахматы как один из режимов настройки голодека. Размер позволяет.

**Comment by GoGoLessa** [comment]
Уже представил как мимоассистент залетает и двигает фигурки. Его не нужно будет немного изменить? Там же по клеточкам вроде не совсем сходится.
Но тема хорошая, интересная.

**Comment by Vostok-Odin** [comment]
Нужно восемь на восемь, а голодек десять на десять. 
И фичу для сохранения партии неплохо бы, защитит прогресс партии от переключения режимов.
