### ISSUE TITLE
Uplink Unit - не имеет смысла.

### ISSUE THREAD

**Issue by Rocky-RU22** [ChaoticOnyx/OnyxBay#5023]
Суть проблемы в том, что Аплинк Юнит не имеет никаких выгодных позиций по сравнению со своими аналогами. На некоторых известных мне билдах, Юнит дает сверху 10% Теле-кристаллов на свои грязные синдикатские потребства, компенсируя это тем, что его нельзя запрятать, обезопасить или как-то замаскировать. Что имеем мы: Аплинк, который забирает 10% Теле-кристаллов от обычного количества (117 вместо 130 тк). Так еще и отсутствие каких либо шифраторов, паролей и прочей скрытности, делая его доступным любому, кто завладеет им. 

Тот же аплинк в ПДА имеет и пароль, и обнаружить его никак нельзя, пока не выбьешь код из попавшегося агента. Так и Теле-кристаллы все на месте. А Юнит просто есть, вот...
![uplinkproblem1](https://user-images.githubusercontent.com/60605662/116726286-44c52680-aa0d-11eb-9479-6e94a7f6021f.PNG)

![uplinkproblem2](https://user-images.githubusercontent.com/60605662/116726289-455dbd00-aa0d-11eb-9b02-7436fe9ac360.PNG)

**Comment by NefrNerf** [comment]
Не актуально #5396
