### ISSUE TITLE
Стационарный флешер и борги

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#5089]
Дать боргам невосприимчивость к стационарным флешерам.

**Comment by DarkHunter7756** [comment]
А как ИИ овнить боргов тогда?

**Comment by Kexilex** [comment]
Поправка, флешеры из брига, которые реагируют на бег.

**Comment by DarkHunter7756** [comment]
> Поправка, флешеры из брига, которые реагируют на бег.

Поправка - стационарная флешка ИИ у самого ИИ
