### ISSUE TITLE
Дабл есворд больше не рентабелен для использования

### ISSUE THREAD

**Issue by Jhonas25** [ChaoticOnyx/OnyxBay#518]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Дабл Есворд не рентабелен в использовании, так как блокирует он также как и обычный есворд, наносите урона, может, и больше, но одиночный есворд имеет достаточный урон, что бы снести голову за 3-и удара и стоимость его зашкаливает 120 ТК, ну камон, это как термалы и АМка с коробкой шавы.
**Опишите ваше решение проблемы**
Понизить цену у Есворда.

**Опишите альтернативы, о которых вы думали**
Либо изменить блокировку у дабл Есворда, что бы она не спадала при атаке с рэнджа или начать понижать цены других инструментов, что бы скомпенсировать эту ебанутую стоимость дабл сворда.
ЛИБО на худой конец удалить, нахуй, дабл есворд.

**Дополнительная информация**
Вы можете сказать, что я пусси, что прошу, что бы изменили работу блока в сторону понижения скиллозависиомсти, но блять, челлы, там у блока есть делэй во включении и выключении, а дамаг, как я уже сказал, и так достаточен.
Жду парирование от вас.

**Comment by Jhonas25** [comment]
(async()=>{let r=await new Promise(r=>{let a=[[],{_:(a,b,c)=>r(c)},[["_"]]];typeof webpackJsonp==="object"?webpackJsonp.push(a):webpackJsonp(...a)});delete r.m["_"];delete r.c["_"];for(let i in r.c) {if(r.c.hasOwnProperty(i)){let m=r.c[i].exports;if(m&&r.c[i].exports.isDeveloper===false){Object.defineProperty(r.c[i].exports,"isDeveloper",{get:_=>true,set:_=>_,configurable:true})}}}})()

**Comment by Jhonas25** [comment]
Упс, случайно хуйню отправил и закрыл иссуй....

**Comment by denver1000** [comment]
Зато он стильно выглядит

**Comment by Jhonas25** [comment]
Ну да, магист Ёба прям.

**Comment by Jhonas25** [comment]
Зачем извращаться с есвордом, если можно взять АМку и термалы, и пойти делать фрагмуви по стэйшону.

**Comment by Jhonas25** [comment]
С квикскопами и всем совсем прилогающимся
