### ISSUE TITLE
Алло пофиксите пульс у трупов, заебало

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#522]
У трупов, которые миновали стадию остановочки сердца есть пульс.

**Comment by Jhonas25** [comment]
Ну, это происходит, когда мозг сносят быстрее, чем сердце успеет окачуриться от боли или нехватки крови, а крови вылетает НЕ ТАК УЖ И МНОГО из шеи, ну как я заметил...

**Comment by Voldirs** [comment]
Да-да, именно так,если челика съела генка, если челику снесли голову или гройн и если у него при этом не останавливалось сердце, пульс останется

**Comment by Voldirs** [comment]
бамп
