### ISSUE TITLE
Ксенофлора это какая-то гачи ебля мужиков.

### ISSUE THREAD

**Issue by Jhonas25** [ChaoticOnyx/OnyxBay#526]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Ксенодебилы могут наебашить рандомных химикатов АБСОЛЮТНО РАНДОМНЫХ, даже админодазолин, что превращается в клоунаду, чел выращивает биотоксин, который добывается из убитой рольки, и идёт тыкать им людей, он же в свою очередь убивает мозг в течение 3-ёх секунд, причём это, ведь, не только этим ограничивается, они могут получить рольку из специального химиката чейджлингов, не буду искать в коде этот химикет, но у него есть строка add.antag.

**Опишите ваше решение проблемы**
Сделать определённый набор химикатов, который можно добыть.

**Опишите альтернативы, о которых вы думали**
ЛИБО, УДАЛИТЬ НАХУЙ и заменить техами.

**Дополнительная информация**
Нет, ну это совсем ржака, парни, челлы как на лавалэнде дрочат пол раунда для данного биотоксина и идут тыкать людей через гиппоспрей, да и не только это.

**Comment by Cinericius** [comment]
>Ксенодебилы могут наебашить рандомных химикатов АБСОЛЮТНО РАНДОМНЫХ, даже админодазолин,

Ay blyad baystation happened

**Comment by Firefroge** [comment]
> дрочат пол раунда
Тащемта 10 минут

**Comment by LegatePritcher** [comment]
__... Ксенобиолог пришёл и оставил здесь свой биотоксин... __

**Comment by Jhonas25** [comment]
4r real, delet this shit.

**Comment by Jhonas25** [comment]
Хоть эта поебота случается не часто, но серьёзно, это вообще не фан, фановее даже будет расстрел из слагов ебальника, да даже глупое затыкивание веселее, ДА ДАЖЕ ХЛОРКА НЕ НА СТОЛЬКО КОНЧЕННАЯ, от хлорки есть некоторое спасение, в виде кофе, что даёт тебе время выкрикнуть что-то, чем этот один тык, ебучим, гиппоспреем с биотоксином.

**Comment by Jhonas25** [comment]
Как говорится на Рэнди параше "У МЕНЯ ЖОПА ### ГОРИИИИИТ!"###

**Comment by TobyThorne** [comment]
### Бриг это какая-то гачи ебля мужиков.

**В чем смысл вашего улучшения? Какую проблему оно решает?**
Щиткурити могут набрать робастных пушек АБСОЛЮТНО РОБАСТНЫХ, даже лазерные карабины, что превращается в клоунаду, чел забегает в оружейку, которая добывается из спалившейся рольки, и идёт стрелять им людей, он же в свою очередь убивает мозг в течение 3-ёх выстрелов.

**Опишите ваше решение проблемы**
Сделать ограничение на одного щиткурити в раунде.

**Опишите альтернативы, о которых вы думали**
ЛИБО, УДАЛИТЬ НАХУЙ и заменить техами.

**Дополнительная информация**
Нет, ну это совсем ржака, парни, челлы как на тандере бегут в начале раунда для данного оружия и идут тыкать людей через ЛКМ, да и не только это.

**Comment by Jhonas25** [comment]
Ну а хуле?

**Comment by Jhonas25** [comment]
Гачи бриг это хотя бы весело, в отличии от одного тыка гиппоспреем.

**Comment by kreeperHLC** [comment]
Ну это баг, который нужно исправить

**Comment by O0oMaximo0O** [comment]
> Ксенодебилы могут наебашить рандомных химикатов АБСОЛЮТНО РАНДОМНЫХ, даже админодазолин.

Для реагентов есть список запрещённых для рандомной генерации. Там как раз админодазолин. Баг неактуален.
Хотя роль получить можно, да. Но это фича. И тот реагент однажды создал прекрасное РП без антагов.
