### ISSUE TITLE
.357/.44 wrong damage

### ISSUE THREAD

**Issue by Tsurupeta** [ChaoticOnyx/OnyxBay#5274]
У патронов калибра .357 Magnum урон больше, чем у .44 Magnum. А должно быть наоборот.

**Comment by MrMagick2104** [comment]
Так это же не баг, а фича.

**Comment by Tsurupeta** [comment]
Не

**Comment by MrMagick2104** [comment]
Багом это было бы, если была ошибка в логике/коде.

Внутриигровые калибры не обязаны соотноситься с реальными.
А, так, ничто не мешает пуле с меньшим диаметром наносить больше урона, ведь даже длины пули в названии патрона нет, не говоря уже о массе порохового заряда и прочем.
Внутриигровой .44 Magnum может быть сопоставим с реальным .44 Special, например.

Кроме того, .44 более распространён в игре (банально дешевле у тех же трейторов, емнип). Если бы это был баг - это было бы не так.

Ну и, конечно, нужно учитывать, что, так или иначе, .357 является культовым калибром в видеоигровой культуре, начиная ещё с первого Халфлайфа, наверное.
