### ISSUE TITLE
Тут собираю багрепорты на трейты

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#531]
Сюда класть багрепорты на трейты. Все будут пофикшены по мере времени и возможности.

**Comment by TobyThorne** [comment]
![buratino](https://user-images.githubusercontent.com/45202681/56812868-caec7800-6809-11e9-8aa1-45c7df7db926.png)

**Comment by ZerlGray** [comment]
Проблема: Геннадии не жрут трейты.
Решение: Перенести списки в тело?

**Comment by Epicus7** [comment]
Чо за трейты? 🤷‍♂️

Баги надо вынести отдельными иссуями, а этот закрыть.

**Comment by HonkyDonky** [comment]
Хорошо пофикшены.
