### ISSUE TITLE
Гении вайтлистовой инженерии. AI, pAI и Positronic Brain

### ISSUE THREAD

**Issue by Jhonas25** [ChaoticOnyx/OnyxBay#534]
_Внимание: эта задача оплачивается. Если вы хотите выполнить её, обязательно заасайните себя на эту задачу и сообщите об этом в комментариях._

### Описание задачи

На данный момент игрок не может выбрать в лобби вход за пИИ и позитронный мозг, т.к. они являются _профессиями_, которые можно получить только будучи в white листе. Это происходит, т.к. они, по сути, являются AI. Необходимо разделить профессии AI, pAI и Positronic Brain. Только AI должна быть в white листе. pAI и Positronic Brain должны быть доступны всем. Кроме этого, игрок должен не иметь возможности зайти за pAI, если у него не заполнено описание pAI.

### Критерии приема задачи

- Профессии AI, pAI и Positronic Brain разделены
- Игрок с вайтлистом на AI может зайти за AI, pAI и Positronic Brain
- Игрок без вайтлиста на AI может зайти pAI и Positronic Brain
- Игрок не может зайти за pAI без заполненных полей описания pAI

Если у вас есть вопросы по требованиям, адресуйте их автору задачи в комментариях, либо @Vmihey. Также вопросы можно задать в нашем официальном [discord](https://discord.gg/VCDcen2).

### Дополнительная информация

![image](https://user-images.githubusercontent.com/26259146/60354737-9184e400-99d5-11e9-9046-d8a943e7b34e.png)

![image](https://user-images.githubusercontent.com/26259146/60354752-98135b80-99d5-11e9-9e3f-2bc144e3a037.png)

![image](https://user-images.githubusercontent.com/26259146/60354758-9d70a600-99d5-11e9-8d07-5fd9d6f2cf88.png)

### Вознаграждение: **4** кружки кофе.

[Chaotic Onyx](https://discord.gg/VCDcen2) одобряет выполнение всех задач. Однако, за данный issue разработчику, выполнившему все требования, будет выплачено вознаграждение в размере стоимости указанного количества кружек кофе. Критерии выполнения будут проверяться ответственными лицами. К сожалению, мы не можем предусмотреть всех нюансов выполнения задачи, однако, мы действительно стараемся максимально полно описывать требования. Будьте готовы, что некоторые детали требований могут быть не предусмотрены. Внимание: не следует воспринимать это как плату за работу. Ваша работа стоит значительно дороже. Это просто небольшой, но приятный бонус, которым мы хотим вас поддержать. Стоимость непритязательной кружки кофе в Петербурге на данный момент 70₽.

Также, пожалуйста, обращайте внимание на комментарий "Подтверждено" от @Rampoch или @Vmihey. Это гарантирует, что выполнение этой задачи будет вознаграждено. Chaotic Onyx не несет ответственности за любые иные обещания награды. Они остаются целиком на совести обещающих.

**Comment by Vmihey** [comment]
![image](https://user-images.githubusercontent.com/26259146/57982929-74fba080-7a54-11e9-8610-d4e38fc13d21.png)
И ведь действительно в бане

**Comment by Jhonas25** [comment]
Скорее всего из-за этого челы и не заходят за позики...

**Comment by Vmihey** [comment]
Подтверждено.

**Comment by Fritcher36** [comment]
Запилю ASAP как только починю свой гит

**Comment by Megmeehey** [comment]
#696
