### ISSUE TITLE
Из закрытой коробки достаются пробирки.

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#535]
**Описание бага**
Из закрытой коробки с пробирками достаются пробирки.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Открываем ключ картой закрытую коробку с пробирками
2. Вставляем туда пробирку из другой коробки
3. Закрываем ключ картой коробку с пробирками
4. Перетаскиваем коробку на себя и спокойно достаём пробирки из закрытой коробки, не смотря на то что чат пишет что она закрыта.

**Ожидаемое поведение**
Естественно из закрытой коробки должно быть невозможно достать пробирки.

**Скриншоты**
![image](https://user-images.githubusercontent.com/48761132/57024017-38e6d400-6c3c-11e9-9f98-ec10db56580c.png)

**Характеристики**
 - OS: Windows 10
 - Версия клиента 512.1467
 - Версия сервера  c67e2a0a2e0859978de4ff05d19255cc3ddc3d9e - release - 2019-04-23
 - ID игры bZ3-ckSg

**Comment by Jhonas25** [comment]
Карта не в ПДА. :agony:

**Comment by FMajesty** [comment]
Может не надо о пробирках?
