### ISSUE TITLE
Анонсы о прибытии в общий канал

### ISSUE THREAD

**Issue by LegatePritcher** [ChaoticOnyx/OnyxBay#537]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Пишет анонсы о прибытии людей не в канал их отдела, а по общему каналу.

**Опишите ваше решение проблемы**
Всё очевидно. Не нужно чекать ПДА, либо писать в чатике о том, какая твоя должность и что ты прибыл. Всё сразу будет отписано в общий чатик.

**Опишите альтернативы, о которых вы думали**
М.

**Дополнительная информация**
На самом деле, можно и не делать это. Лоу приорити, на геймплей в слабой мере влияет, но всё-таки.

**Comment by FMajesty** [comment]
Можно.
