### ISSUE TITLE
Обновить главную на вики

### ISSUE THREAD

**Issue by Vmihey** [ChaoticOnyx/OnyxBay#540]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
На главной странице вики информация не актуальна
https://wiki.ss13.ru/index.php?title=Getting_Started
Например, ссылки на каналы discord имеют протухший инвайт

**Опишите ваше решение проблемы**
Вычитать страницу и обновить информацию до актуального состояния

**Дополнительная информация**
В качестве дополнительного улучшения, будет неплохо, если ссылка на сервер будет большой и заметной, а не скрытой где-то в недрах страницы.

**Comment by Rampoch** [comment]
Бинари займется.

**Comment by Vmihey** [comment]
![image](https://user-images.githubusercontent.com/26259146/60355275-b2016e00-99d6-11e9-92b0-43f7e10dd676.png)
