### ISSUE TITLE
Трейты с поинтами

### ISSUE THREAD

**Issue by kcalbCube** [ChaoticOnyx/OnyxBay#5401]
На тг-производных люди берут трейты ради того что бы взять себе какой-то положительный эффект. 
У нас же трейты не берёт никто кроме картавых трапов и детей протолата отыгрывающих обморок от лужи крови в коридоре.
Если же мы портируем систему с тг, то мы побудим людей создавать более разнообразных персонажей со своими нуждами...

**Comment by MACTEP-ABATAP** [comment]
Шаблон иссуя же есть...

**Comment by kcalbCube** [comment]
идеи кубика всегда не соответствовали шаблонам...

**Comment by MrMagick2104** [comment]
У нас мудлетов нет, а довольно большая часть трейтов на ТГ работает на них.

**Comment by kcalbCube** [comment]
> У нас мудлетов нет, а довольно большая часть трейтов на ТГ работает на них.

~40%, не более. Да и всегда можно создать новые, типа диабета того же из гормонального КБП. хоть геймплейный смысл добавится.

**Comment by MrMagick2104** [comment]
> ~40%

Это можно назвать большой частью. Почти половина.

А какие положительные трейты добавлять? Чтобы не приводило к минимаксам и было бы хоть как-то значительно.

**Comment by kcalbCube** [comment]
Положительные трейты? Можно крутить параметры беемедицины, повышать болевой порог, замедлять потерю крови, ускорять заживление ран, увеличивать иммунитет и сопротивление к инфекциям, позволить обнаруживать яд в пище и напитках(через examine), сделать повышенный шанс на реанимацию через СЛР, обнаруживать некоторые заболевания у людей(и у себя) через examine... возможностей много.

**Comment by Epicus7** [comment]
Появился более подробный иссуй #5641. Этот закрываем
