### ISSUE TITLE
Удерживание на мушке

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#541]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Альтернативный режим стрельбы - удерживание на мушке, бесполезен в рамках механики. На мушку можно взять только в прямой видимости и за несколько секунд простоя. Выстрел из этого режима не срабатывает, если цель стреляет в ответ.

**Опишите ваше решение проблемы**
Добавить срабатывание выстрела при открытии огня целью. Проверить срабатывание выстрела при движениях цели. Уменьшить время взятия на мушку.

**Дополнительная информация**
Дополнительно, было бы неплохо ввести логику взятия на мушку тайла. Это позволило бы выстрелить в любое появившееся существо при его появлении в тайле. Это моделирует ситуацию, когда персонаж знает, что его противник скрылся за укрытием и целится близко к нему.

**Comment by Jhonas25** [comment]
C фокусированием на тайле - интересная идея, только бы сделать так, чтобы враг не видел меточки на тайле...

**Comment by Epicus7** [comment]
Прицеливание на тайл надо в отдельный иссуй.

**Comment by MemoryDreams** [comment]
Прицеливание в тайл будет слишком имбовым, я считаю. Никто не мешает самостоятельно держать курсор на тайле и готовиться выстрелить.
Насчёт времени прицеливания, хз. Нужно будет проверить, как оно вообще срабатывает и всё такое.
Насчёт проверки на стрельбу, не знаю. Люди не так уж и часто стреляют друг в друга одновременно, чаще это вопрос того, кто выстрелит первым. Я бы лучше добавил кнопку стрельбы, когда цель на мушке.

**Comment by MrMagick2104** [comment]
> Прицеливание в тайл будет слишком имбовым, я считаю. Никто не мешает самостоятельно держать курсор на тайле и готовиться выстрелить.

Какие-то взаимоисключающие предложения, по-моемому. Это уже можно сделать сейчас без прицеливания на тайл, это не имба, а если это можно будет сделать С прицеливанием, то почему-то это станет имбой. При том, объективно, целиться руками будет лучше, потому что не нужно будет ждать время на прицеливание и можно будет не стрелять по своим.
Хотя прицеливание в тайл и убьёт все те чувства держания угла своими руками, но оно поможет тем, кто пришёл не в шутан играть, а также достаточной реакцией не обладает.
> Насчёт времени прицеливания, хз. Нужно будет проверить, как оно вообще срабатывает и всё такое.

Сейчас прицеливание из-за времени стало настолько нишевым, что им вообще не пользуются, даже для всяких там задержаний и прочего, потому что если ты будешь тратить время на именно прицеливание, то пока ты будешь переключать режимы назад на обычную стрельбу и всё такое, тебе ебало набьют.
Я бы предложил, в случае, если прицеливание прервано, во-первых, автоматически переключать режим, а во-вторых, стрелять в сторону оппонента одну пульку с разбросом в ~30 градусов, а в-третьих, если прицеливание началось, но ещё не прицелилось, а ты кликнул ещё раз, делать выстрел.

Ещё можно было бы сделать возможность прицеливания до доставания оружия.
То есть, ты выбрал режим прицеливания, нажал пустой рукой на космонавтика, который стоит дальше, чем в одном тайле от тебя, на режиме, отличном от хелпа, начал "прицеливание", а затем достал пушку, то ты уже прицелился. Соответственно, никто не будет видеть то, что ты начал целиться до тех пор, пока не достал ствол. Можно ещё добавить каких-нибудь эмоутов, вроде: "Cosmonavt 1 прищуривает глаза, глядя на Cosmonavt 2". Для макаронных дуэлей и advanced нападений.

**Comment by MemoryDreams** [comment]
> Это уже можно сделать сейчас без прицеливания на тайл, это не имба, а если это можно будет сделать С прицеливанием, то почему-то это станет имбой.

Сейчас это зависит только от реакции игроков. То что предлагает ОП, по сути, наделяет всех персонажей на станции идеальной реакцией, что будут абьюзить.
Да и как бы прицеливание само по себе имбовая фича. Человек, которого поймали на мушку уже обречён в большинстве случаев. Он уже проиграл. Для этого прицеливания и сделаны так, что они занимают какое-то время.

>Я бы предложил, в случае, если прицеливание прервано, во-первых, автоматически переключать режим, а во-вторых, стрелять в сторону оппонента одну пульку с разбросом в ~30 градусов, а в-третьих, если прицеливание началось, но ещё не прицелилось, а ты кликнул ещё раз, делать выстрел.

Первое будет задалбывать. Второе лишает игроков шанса убежать. Вот насчет третьего стоит подумать. Быстрая стрельба при прицеливании определенно нужна.

> Ещё можно было бы сделать возможность прицеливания до доставания оружия. 

Опять таки слишком имбово для ССки по причинам описанным где-то выше. Хотя, подумать можно было бы, но не чтобы игрок сразу брался на мушку. Приметить человека глазами и взять на мушку, это не одно и то же. Если ты посещал кружок стрельбы в школе или просто время от времени ходил в тиры, должен понимать, что стрелять от бедра енто не ок. 
Возможно, можно было бы дать бонус при прицеливании или вроде того. Но если чувак двигается, в любом случае стоит прерывать прицеливание.

**Comment by MrMagick2104** [comment]
Кстати, ещё херня по поводу прицеливания:
Ты стреляешь в человека самостоятельно, только если нажмёшь прямо на его спрайтик. Стрельнуть в его сторону и попасть нельзя. Не знаю как другие, но я вот в сам спрайт никогда не целюсь, а стреляю именно в сторону человека, т.к. силуэт у направления куда больше, чем у спрайта => попасть проще. То есть, стрельнуть по человеку во время прицеливания (по крайней мере для меня) становится куда сложнее.

> Человек, которого поймали на мушку уже обречён в большинстве случаев. Он уже проиграл. Для этого прицеливания и сделаны так, что они занимают какое-то время.

Из-за кривости прицеливания, это, чаще всего, не так. приведу пример: мне как-то пришлось пиздить генку с армблейдом в прицеле рукояткой пистолета на дизарме, так как я не знал факт, упомянутый выше, связанный с кривой стрельбой, а переключаться с режима на режим не было времени.
Собственно смысл иссуя в том, чтобы сделать это утверждение верным, так как в данный момент прицеливание - абсолютно бесполезное говно, нужное только для того, чтобы показать, что у тебя есть ствол более наглядным методом.
> > Я бы предложил, в случае, если прицеливание прервано, во-первых, автоматически переключать режим, а во-вторых, стрелять в сторону оппонента одну пульку с разбросом в ~30 градусов, а в-третьих, если прицеливание началось, но ещё не прицелилось, а ты кликнул ещё раз, делать выстрел.

> Второе лишает игроков шанса убежать. 


>  Человек, которого поймали на мушку уже обречён в большинстве случаев. Он уже проиграл. 

Зачем человеку, который уже проиграл, возможность убежать?
>  Приметить человека глазами и взять на мушку, это не одно и то же. Если ты посещал кружок стрельбы в школе или просто время от времени ходил в тиры, должен понимать, что стрелять от бедра енто не ок.

Знаю, понимаю. Но.

> Опять таки слишком имбово для ССки по причинам описанным где-то выше.

Мы говорим про ССку, где можно с магнума .357 раздавать хедшоты на бегу в тяжёлом плитнике класса как минимум четвёртого, что явно сложнее, чем просто стрельба от бедра. Да и игровые условности, как-никак.

Хотя сама идея, как я её изложил, говно, но хотелось бы какие-нибудь чисто механические возможности по подготовке к стрельбе перед собственно стрельбой.

**Comment by MemoryDreams** [comment]
Я бы предложил добавить возможность стрелять, если в режиме прицеливания ты либо быстро кликаешь куда либо прежде чем успел окончательно навести прицел. Это должно исправить огромное количество проблем, связанных с прицельной стрельбой и не будет работать как press X to win. 
Кроме того, добавить возможность стрельбы, когда ты уже прицелился и кликаешь по чару на мушке, даже если он не двигается. Сейчас он, вроде, снимает прицел или просто ничего не делает. Так ведь?

**Comment by MemoryDreams** [comment]
Я бы предложил добавить возможность стрелять, если в режиме прицеливания ты либо быстро кликаешь куда либо прежде чем успел окончательно навести прицел. Это должно исправить огромное количество проблем, связанных с прицельной стрельбой и не будет работать как press X to win. 
Кроме того, добавить возможность стрельбы, когда ты уже прицелился и кликаешь по чару на мушке, даже если он не двигается. Сейчас он, вроде, снимает прицел или просто ничего не делает. Так ведь?
