### ISSUE TITLE
Проблемы с кириллицей

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#544]
**Описание бага**
Кириллица на консолях сломана. В распечатанном виде работает.
Этой проблеме также подвержены книги в электронном виде, каналы ньюскастеров, и чатик, что представлен на скрине ниже.

![image](https://user-images.githubusercontent.com/26259146/58178417-d6b74700-7cae-11e9-8c15-e4abdc72829a.png)

**Comment by Vmihey** [comment]
...You hear something about...&#255

**Comment by Vmihey** [comment]
![image](https://user-images.githubusercontent.com/26259146/60029994-dbef2380-96aa-11e9-924d-bbf18c555043.png)

![image](https://user-images.githubusercontent.com/26259146/60030040-f45f3e00-96aa-11e9-9dab-737a4be7883f.png)

![image](https://user-images.githubusercontent.com/26259146/60030224-4902b900-96ab-11e9-8d91-137dfd2a6810.png)

**Comment by Vmihey** [comment]
![изображение](https://user-images.githubusercontent.com/26259146/60138985-ec8bc080-97b4-11e9-839d-9ca6d042d0eb.png)

A warning sign which reads 'яCCTV'.

**Comment by Vmihey** [comment]
В ньюскастерах очевидная проблема, что выводим клиенту в кодировке 1251, а хранится в кодировке 1252.

**Comment by Epicus7** [comment]
Неактуально, 513 приехала, все кодировки уже должны работать.
