### ISSUE TITLE
Внезапное появление у синтетика человеческих органов

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#545]
**Описание бага**
Внезапное появление у синтетика человеческих органов. (Вероятно, всплывает проблема указанная в [PR#538](https://github.com/ChaoticOnyx/OnyxBay/pull/538)).

Что было сделано: "Мозг в ММИ со старта раунда борговский, каркас с него же. При сборке синта у него появилась _хумановская жопа_. И вот с этого момента и пошло-поехало."
"Борг бегал как обычно, но у него светился значок о кислородном голодании, потом его ткнули вилкой в пах пару раз и он схватил крит. Из него начали вырезать органы, но потом они внезапно появились снова, начался их отказ, от токсинов начался отказ ММИ, от чего он и умер."

Скрины:
https://c2n.me/41KdWNk
https://clip2net.com/s/41KeHW6

Связанные issue:
[#224 ](https://github.com/ChaoticOnyx/OnyxBay/issues/224)

**Comment by Fritcher36** [comment]
Exodus: become human

**Comment by Cinericius** [comment]
На Ониксе даже синта можно критануть вилкой в жеппу.
