### ISSUE TITLE
Minor tweaks for Vampire

### ISSUE THREAD

**Issue by Zert0X** [ChaoticOnyx/OnyxBay#5460]
1. Наносить урон вампирам от нахождения в церкви.
 <details>
 <summary>Альтернатива</summary>
  Добавить урон от святой воды/чеснока.
 </details>
2. Добавить вампирам цели, а то они бесцельно появляются и исчезают. Цели можно взять от трейторов.

**Comment by Kexilex** [comment]
Урон от церкви кринге, может просто запрет на каст умений(как у культей?)
Святая вода, чеснок и серебряное оружие звучит хорошо. Дополнительный бёрн урон от серебряннрно оружия будет хорошей фичей
