### ISSUE TITLE
Уменьшить количество вампиров в раунде

### ISSUE THREAD

**Issue by Kexilex** [ChaoticOnyx/OnyxBay#5471]
Когда вампиров добавляли в ротацию, были раунды, где из антагов были только вампиры, что, на мой взгляд, ухудшало игровой рп экспириенс. 

Предлагаю уменьшить спавн вампиров до одного, а при онлайне >30-40 до двух. Так же стоит добавлять вампиров в случайные раунды (кроме нюки?), а самостоятельных вампиров выпилить.

**Comment by Zert0X** [comment]
Более правильно было бы написать добавить вампира как мидраунд антагониста

**Comment by Zert0X** [comment]
Собственно вампир теперь спавнится сторителлером
