### ISSUE TITLE
Теряется часть букв в базах данных и флаворах

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#549]
Насколько я мог заметить, в нашем билде, да и в целом на всём БЕЕ, есть один очень забавный баг. Например, некоторые буквы при написании их в _базу данных_ или _флавор_ пожирают своих соседей, заменяя их на непонятные символы в _"ВВ"_. 
![Тест](https://user-images.githubusercontent.com/10909882/58470876-d1557300-816c-11e9-8e44-02e0c5d960e1.PNG)
 Конечно, всё правится кнопочками через тот же "VV", но всё же бы хотелось это как-то исправить.
![Тест-2](https://user-images.githubusercontent.com/10909882/58470885-da464480-816c-11e9-910d-58ca8335c575.PNG)

**Comment by kreeperHLC** [comment]
Да это же ещё одно место, где Я не пофиксили.

**Comment by kreeperHLC** [comment]
Пофиксил я в флаворах, базу данных не осилил

**Comment by Epicus7** [comment]
Должно было пофикситься после 513, если не пофиксили раньше.
