### ISSUE TITLE
Консоль управления трафиком теллекомуникаций в РнД

### ISSUE THREAD

**Issue by IvanDonFon** [ChaoticOnyx/OnyxBay#5493]
### Улучшение
Добавить в РнД возможность напечатать плату консоли управления трафиком теллекомов, ведь без неё невозможно в полной мере насладиться процессом системного администрирования данной машинерии
### Какую проблему это решит?
Благодаря этому улучшению, станут доступны множество новых фич, которые ранее были недоступны

**Comment by DarkHunter7756** [comment]
Поддерживаю. 

Сейчас на телекоммах можно только жидко погрифонить процессоры мультитулом. И ради сего занятия был создан спутник?
