### ISSUE TITLE
Передел атмосферки на килородные сады

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#55]
- Создать новую зону кислородные сады
туда закачивается угл газ со станции и фильтруется кислород
каждые 5 сек в зоне проверяется кол-во растений и вычисляется коофицент переработки

- переделать атмосферку 
сделать за место нее комнату смесителя где газы смешиваются прежде чем попасть в атмосферу
убрать эти бесконечные запасы газов

- Убрать ботанику рядом с кухней впихнуть рядом/в кислородные сады
у ботаника новая задача следить за садами

- дополнительно: 
за место старой ботаники сделать столовую
за место текущего "бара" сделать полноценный бар как многие хотят

**Comment by LagannPM** [comment]
готов взятся в плане кода если кто-нибудь переделает карту

**Comment by Ruforce** [comment]
pathetic

**Comment by LagannPM** [comment]
@Ruforce Есть что годного сказать ? нет ?

**Comment by LagannPM** [comment]
@Ruforce твои остроумные коментарии ненужны

**Comment by Ruforce** [comment]
смари

**Comment by Ruforce** [comment]
у тебя есть куча багов
но взамен фиксов

**Comment by Ruforce** [comment]
ты делаешь геймплейныйе фичи, которые никому не нужны

**Comment by Ruforce** [comment]
зачем???????????????????????

**Comment by LagannPM** [comment]
я всего лишь предлагаю новые фичи (сейчас атмосферный отдел скучный и бесполезный), здесь должно быть обсуждение самой фичи, а не обсуждение того что баги никто не чинит

**Comment by Cinericius** [comment]
Когда-нибудь потом, видимо.

**Comment by Epicus7** [comment]
@Cinericius, а закрывать то зачем. Висело бы оно и дальше, мешает что ли?

**Comment by Cinericius** [comment]
Чист_очка

**Comment by Epicus7** [comment]
Чо?

**Comment by Cinericius** [comment]
Не ну пускай еще годик повисит...

**Comment by Cinericius** [comment]
Тут кстати в ОПе нерфоцирк предложен

**Comment by dnivji** [comment]
Предлагаю закрыть.

**Comment by Rodial-Admiral** [comment]
Система переработки углекислого газа в кислород (необязательно растениями) сама по себе выглядит привлекательно, но конкретно данный иссуй в большей степени предлагает нерфоцирк и персональные фантазии аффтара.
Предлагаю закрыть [x2]

**Comment by Rodial-Admiral** [comment]
Плюс, запасы газов не бесконечные и выдыхаются при любой серьезной возне с атмосферкой.

**Comment by kreeperHLC** [comment]
Это интересная идея для одной карты, но не для абсолютно всех. Отклонено в рамках добавления везде.
