### ISSUE TITLE
Медальки из лодаута не отображаются на спрайтах космонавтика

### ISSUE THREAD

**Issue by BreddySome** [ChaoticOnyx/OnyxBay#554]
**Описание бага**
Медали из лоадаута, которые NanoTrasen award selection не отображаются на спрайтах космонавтика и одежды.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем Nanotrasen award selection в Loadout
2. Вытаскиваем медальку из рюкзака
3. Цепляем медальку на одежду
4. Аксессуаров на одежде не видно...

**Ожидаемое поведение**
Появление нескольких пикселей жёлтого/серого цвета в районе груди космонавтика и его одежды.

**Скриншоты**
Мне лень

**Характеристики**
А зачем...

**Дополнительная информация**
Ну, не знаю все ли медальки не имеют спрайтов, ибо брал только командную.

**Comment by Voldirs** [comment]
Вот не думаю что это даже стоит исправлять, а если исправлять то только по уму потому что в таком случае медальки можно будет цеплять на обычные штаны и медалька будет отображаться приколотой к голой груди. Очень пафосно, но надо ли?

**Comment by Fritcher36** [comment]
Делов-то сделать чек на штаны
