### ISSUE TITLE
Починка одежды

### ISSUE THREAD

**Issue by Fritcher36** [ChaoticOnyx/OnyxBay#555]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Полный чертов хаос в одежде.

**Опишите ваше решение проблемы**
Создать типы одежды, сделать наследование кода. Структурирование: надеваются брюки либо комбинезон, рубашка надевается в качестве аксессуара, пиджак надевается в слот скафандра.

**Опишите альтернативы, о которых вы думали**
Оставить текущую хуйню.

**Дополнительная информация**
Также это уберет проблему с перенасыщенным дми файлами, так как все спрайты можно будет рассортировать по типам, все равно переписывать большую часть кода.

**Comment by TobyThorne** [comment]
>надеваются брюки либо комбинезон, рубашка надевается в качестве аксессуара, пиджак надевается в слот скафандра.

Ну как-то так оно сейчас и есть. Бухтёж непонят.
