### ISSUE TITLE
[TODO] по генкам

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#556]
1. Усилить генкоконечности: - Done
1.1) Добавить урона.
1.2) Добавить здоровья конечностям.
1.3) Усилить самолечение при укусе.
1.4) Дать генкоорганам возможность после N укусов спавнить свою копию.
2. Усилить хедкрабов.
2.1) Добавить возможность прыгать на лица как лицехваты.
2.2) Увеличить здоровье. - Done
3. Убить всех человекав.
4. Добавить возможность активировать генкоабилки по клику мышкой. - Done
5. Добавить абилку, которая позволяет инфестить трупы, чтобы через N секунд они превращались в стайку генкоорганов.

Добавляйте сюда свои предложения и баги.

**Comment by Jhonas25** [comment]
Они и так имба со своим паралайз стингом...
Дык ты ещё и баффнуть их хочешь...

**Comment by ZerlGray** [comment]
> Они и так имба со своим паралайз стингом...
> Дык ты ещё и баффнуть их хочешь...

проблемой являются автономные конечности без человека внутри, они слабые и умирают с попадания

**Comment by Jhonas25** [comment]
С баллона принимают добрых 3-и удара.
Может с карабина и егана, да, один выстрел, но на то пухи и сделаны, щас, блять, генычи начнут срать этими конечностями и потом кайфовать от того, что они мимокосмонавту ебало отгрызают за пару тычек, а сам мимокосмонавт не может их уебать, пусть такими же остаются, у них есть говно-стан, что ещё лучше, блять.

**Comment by Jhonas25** [comment]
Либо выпиливай кнок, срезай скорость и баффай сколько хочешь, либо не трогай и оставь как есть.

**Comment by ZerlGray** [comment]
> С баллона принимают добрых 3-и удара.
> Может с карабина и егана, да, один выстрел, но на то пухи и сделаны, щас, блять, генычи начнут срать этими конечностями и потом кайфовать от того, что они мимокосмонавту ебало отгрызают за пару тычек, а сам мимокосмонавт не может их уебать, пусть такими же остаются, у них есть говно-стан, что ещё лучше, блять.

Нужно чтобы они успевали убегать. В этом смысл.

А сами конечности нужно бафать. Просто нужно подумать, как.

**Comment by Voldirs** [comment]
Тоже самое, что и в визурдах, надо добавить охуительный пунктик в этот ваш туду:
>Добавить каких нибудь интересных интеррактов с экипажем, помимо "убей"
Опять же за генок не играл, но в качестве варинтов: поменять двух людей телами, сделать человека х генкой, сделать x копий человека у (обезьяны не считаются, только человеки с игроком внутри) ну и всякое подобное интересное.
Алсо убрать вот это дикое количество геномов для гринтекста.
