### ISSUE TITLE
Обновление контрактов.

### ISSUE THREAD

**Issue by Doster-d** [ChaoticOnyx/OnyxBay#5568]
Этот иссуй был создан как план для разработчика (автора иссуя), чтобы собрать большинство мнений о том как улучшить контракты, добавить новые типы контактов и все такое.

Данные предложения могут выполняться независимо друг от друга.

- Персональные контракты. Трейтор может одновременно выполнять только 3 контракта. Контракты берутся из пулла заданий (как в текущей версии), как только контракт назначается трейтору, он становится недоступным (для выбора, их все еще можно просматривать) для других трейторов. Выбранные контракты отображаются в отдельной таблице перед общем пуллом.
- Кнопка "Подтверждение" для завершения контракта, для некоторых контрактов.
- Генератор Страшного Красного Портала, при активации самоуничтожаеься и создает Страшный Красный Портал, который будет работать одну минуту, сквозь него нельзя пройти. Портал и генератор линкуются автоматически. Туда с красным грабом нужно закинуть человека из контрактов по убийству (награда как за голову) и нового контракта кражи персонала. Цена - 8 ТС.
- Кража персонала. Трейтору необходимо доставить живым и здоровым (активность мозга выше 50%, остальное не важно) члена персонала указанного в контракте, используя Страшный Красный Портал Награда - 12 ТС.
- "Бриг" контракт. Старая, добрая задача на задержание в бриге человека, подтверждение через кнопку в меню контрактов. Награда - 8 TC.
- Отношения между трейторами и фракциями. При выполнения контракта в зависимости от его сложности фракция повышает новую шкалу "доверие", трейтор может разными способами потратить "доверие", например форсануть выдачу контракта в общий пулл (можно также за ТС или за доверие) или в пулл трейтора (за ТС + "доверие"), заказать контракт на убийство (ТС необходимое за голову или за большое количество "доверия"). Если у трейтора высокое "доверие", то фракция может сама предложить задание. Предложенные задания можно брать сверх меры.
- Заменить интент на сложность операций, сложность операции не будет влиять на персональные задание трейторам с высоким доверием.
- Подключить фиксера к системам сторителлера, это позволит в дальнейшем, при развитие сторителлера, больше понимать и подстраивать контракты под раунд. Пока я слабо представляю как можно влиять на фиксера, но можно передавать сложность/интент от сторителлера к фиксеру, чтобы фиксер рандомил по сложности/интенту, который нужен раунду, можно получать список заданий по интенту/сложности и самому (сторителлер) выбирать какое нужно, можно создать прок, который будет по информации от сторителлера собирать контракт (тип, причина, цель, награда).
- Кастомный контакт. Описание и награда полностью задается задается педалей, за выполнением также следят педали.
- Добавить кнопку досрочного выполнения контракта в педальное меню.
- Отображать все контракты, а не только активные в педальном меню.
- Отображать контракты, которые выполнил трейтор за раунд в конце раунде, также отобразить в педальной панель эту информацию.
- Временные контракты. Теперь почти все контракты имеют ограничение по времени, успейте их выполнить!

**Comment by DarkHunter7756** [comment]
Не совсем понятно с Одеждой Заключенного. То есть теперь трейтор должен сам одевать цель в робу? Это немного не вяжется с сутью цели на содержание в бриге, ведь изначально нужно именно подставить человека

**Comment by Doster-d** [comment]
> Не совсем понятно с Одеждой Заключенного. То есть теперь трейтор должен сам одевать цель в робу? Это немного не вяжется с сутью цели на содержание в бриге, ведь изначально нужно именно подставить человека

По моему view трейтору надо выкинуть всю старую одежду из брига и заменить на свою.

**Comment by DarkHunter7756** [comment]
> По моему view трейтору надо выкинуть всю старую одежду из брига и заменить на свою.

То есть мы должны влететь в осиный улей, стырить трусы, положить свои трусы и убежать подставлять цель? Хым

**Comment by Doster-d** [comment]
> То есть мы должны влететь в осиный улей, стырить трусы, положить свои трусы и убежать подставлять цель? Хым

Можно подкупить СБшника, чтобы посадил твоего заключенного именно в твою одежду.

Можно устроить редизайн тюремный робы при помощи ХоСа/Варден.

Множества интересных способов, теперь татору надо думать не только над тем как подставить человека, но и как заставить СБ одеть твою одежду.

**Comment by DarkHunter7756** [comment]
Я конечно на трейторах не играю ( ͡° ͜ʖ ͡°), но зачастую и подставить было интересно. Особенно подставить какого-нибудь важного перца. Особенно на чмошной профессии, которой никто не поверит. Тут же я вижу механ ради механа, подкупить СБ зачастую не выйдет, редизайн робы делается крайне редко, ибо "подозрительно" и нет смысла. Просто why?

**Comment by MrMagick2104** [comment]
> Не совсем понятно с Одеждой Заключенного. То есть теперь трейтор должен сам одевать цель в робу? Это немного не вяжется с сутью цели на содержание в бриге, ведь изначально нужно именно подставить человека

Что-то мне кажется, что чаще будут просто вырезать всё СБ, сажать цель в камеру в одежде и стоять над душой пять минут. Как и бывало раньше с контрактами на заключение.

<hr>

К слову, как-то неприятно, что тебе нужно докупать предметы для контракта: "Камень я не дам". Может быть, давать одноразовую скидку в 100% на необходимые предметы при взятии контракта, но уменьшить награду?

<hr>

> Также некоторые контракты имеют отведенный срок на выполнения, активируется при взятие/полученные от корпы.

А не проще будет сначала выполнить контракт, раздобыв необходимые вещи, потом взять контракт на время и выполнить его?

**Comment by Doster-d** [comment]
Ну так да, но контракт могут забрать другие таторы.

**Comment by bosslobster** [comment]
Как идея - в контактах раз в какое-то время появляется "убермегаважный контракт".
Он появляется без описания что нужно делать, только повышенная награда и время, за которое его надо выполнить. Принять может только один тритор. После принятия он узнает что собственно надо делать.
Ну и самое интересное - если тритор не выполняет задание за указанное время, то всем остальным триторам приходит сообщение в чат - мол этого агента надо устранить и скидывается его последнее местоположение. Можно сделать что если тритор еще жив, то его местоположение отправляется остальным триторам еще 2 раза - через 10 и 20 минут.
Награда за голову этого тритора - раза в 2-3 больше, чем стандартный контракт на убийство. Контракт остается висеть до конца раунда.

**Comment by Doster-d** [comment]
Во! Вот этого я и ждал, хорошее предложение подумаю о том, как это вписать.

**Comment by Kexilex** [comment]
Вы объявлены экс-комюникадо, мистер Уик

**Comment by Epicus7** [comment]
> Персональные контракты. Трейтор может одновременно выполнять только 3 контракта. Контракты берутся из пулла заданий (как в текущей версии), как только контракт назначается трейтору, он становится недоступным (для выбора, их все еще можно просматривать) для других трейторов. Выбранные контракты отображаются в отдельной таблице перед общем пуллом.

Зачем это нужно?

> Кнопка "Подтверждение" для завершения контракта, для некоторых контрактов.

Зачем это нужно?

> Генератор Страшного Красного Портала, при активации самоуничтожаеься и создает Страшный Красный Портал, который будет работать одну минуту, сквозь него нельзя пройти. Портал и генератор линкуются автоматически. Туда с красным грабом нужно закинуть человека из контрактов по убийству (награда как за голову) и нового контракта кражи персонала. Цена - 8 ТС.

Чот это больше для культа подходит, чем для трейторов. Кражу персонала лучше бы через какие-нибудь поды реализовать, или еще как-то, хз.

> "Бриг" контракт. Старая, добрая задача на задержание в бриге человека, подтверждение через кнопку в меню контрактов. Награда - 8 TC.

А что мешает просто ее нажать. Подтверждения через кнопку звучат очень сомнительно. Мб лучше через фотографию, хз + при проверке, как и раньше, время автоматически чекать?

> Отношения между трейторами и фракциями. 

У нас бека нет, какие фракции. Бек сначала напишите, а потом будем механ для фракций делать.

> Подключить фиксера к системам сторителлера, это позволит в дальнейшем, при развитие сторителлера, больше понимать и подстраивать контракты под раунд. Пока я слабо представляю как можно влиять на фиксера, но можно передавать сложность/интент от сторителлера к фиксеру, чтобы фиксер рандомил по сложности/интенту, который нужен раунду, можно получать список заданий по интенту/сложности и самому (сторителлер) выбирать какое нужно, можно создать прок, который будет по информации от сторителлера собирать контракт (тип, причина, цель, награда).

Если "фиксер" - это логика раздачи контрактов, то я бы полностью втащил ее внутрь сторителлера, чтобы контракты раздавал сторителлер. Контракты напрямую влияют на историю, поэтому неплохо было бы, если бы раздавал их тоже сторителлер.

> Кастомный контакт. Описание и награда полностью задается задается педалей, за выполнением также следят педали.
> Добавить кнопку досрочного выполнения контракта в педальное меню.
> Отображать все контракты, а не только активные в педальном меню.
> -Отображать контракты, которые выполнил трейтор за раунд в конце раунде, также отобразить в педальной панель эту информацию.

Это нужно, да

> Временные контракты. Теперь почти все контракты имеют ограничение по времени, успейте их выполнить!

Опять же, зачем это нужно? Какую проблему решаем?
