### ISSUE TITLE
Накидки главам и донатерам

### ISSUE THREAD

**Issue by Doster-d** [ChaoticOnyx/OnyxBay#5581]
Добавить накидки как на ТГ, но с нормальными спрайтам.

Добавить пару накидок для донатеров от 15 опиксов, как идея: накидка с улитками, карпами.

UPD: рефы.

Для капитана, ХоСа и ХоПа:
![unknown-5.png](https://user-images.githubusercontent.com/63081538/122273316-f7801400-cee9-11eb-9dca-3c0bd035899b.png)
![Без названия (1).jpeg](https://user-images.githubusercontent.com/63081538/122273327-fbac3180-cee9-11eb-8a35-0d6eb41da30f.jpeg)

**Comment by PlinHost** [comment]
\>NOERP, YESERP в иц

**Comment by Doster-d** [comment]
> \>NOERP, YESERP в иц

Напиток ERP?

**Comment by Wuattt** [comment]
накидки норм, erp на накидках лишние

**Comment by Doster-d** [comment]
Ок.

**Comment by kcalbCube** [comment]
в какой слот кладутся, можно ли в них класть вещи, где проработка

**Comment by Doster-d** [comment]
> в какой слот надеваются, можно ли в них класть вещи, где проработка

Сказано же как на ТГ, но с нормальным  спрайтами.

**Comment by kcalbCube** [comment]
понятно.

**Comment by Voldirs** [comment]
всё ещё фу

**Comment by Epicus7** [comment]
А чо сложного? Новые предметы одежды добавлять нам уже сложно?

**Comment by Doster-d** [comment]
> А чо сложного? Новые предметы одежды добавлять нам уже сложно?

Сложность заключается в спрайтах.

**Comment by Doster-d** [comment]
Сложность же определяется разработчиком. Для меня спрайты пиздец сложно, геймдизайну ничего не понравится, если я сделаю, поэтому поставил сложно.

**Comment by Doster-d** [comment]
> Так он про теги, которые вы поставили. 

Я и указал в чем заключается сложность

**Comment by Doster-d** [comment]
Добавил рефы.

**Comment by NefrNerf** [comment]
У нас главы и так разукрашены да и не очень это будет, превращение в цветастое ТГ, донатерам можно подумать если придем к этому, то лучше как отдельный иссуй. Минус
