### ISSUE TITLE
Добавить больше настроек хайлайтам чата

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#5583]
### Улучшение
В частности, добавить возможность использовать поиск только по целым (-ому) словам (-у) и учёт регистра искомой строки.
Очень не хватает данных функций в некоторых ситуациях. Например, при игре за ИИ, максимально полезное действие - добавить хайлайт на "ИИ", чтобы не пропускать сообщения, требующих твоего внимания, но хайлайт будет выделять все сообщения, содержащие "ИИ" даже как окончания, вне зависимости от регистра и прочего. Например: "На станции", - он выделит.

### Решение
Добавить соответствующую кнопку/ползунок/галочку, либо ключевой символ (§, #, $, @, *), который надо добавить перед необходимым словом для включения данной функции, написав об этом куда-нибудь поблизости.

**Comment by igorsaux** [comment]
Вы только что регулярки

**Comment by hard-res3t** [comment]
А почему закрыли? Хорошее же улучшение

**Comment by igorsaux** [comment]
Нет, для этого есть регулярки. А вот игнорирование регистра я уберу.
