### ISSUE TITLE
БАГ: Турели под ИИ убивают тех, кого не должны.

### ISSUE THREAD

**Issue by Judge1987** [ChaoticOnyx/OnyxBay#5597]
### Описание бага
Турель в аплоуде не убивает СЕ, RD и прочих, а вот те пушки, что под ИИ и рядом с капитанской — ещё как горазды пострелять по квалифицированному персоналу.

### Ожидаемое поведение
Отсутствие пальбы по уполномоченному персоналу.

**Comment by No-Tips** [comment]
Может быть это потому, что в ядре ИИ выключен режим "проверять авторизованный персонал", из-за которого турели не стреляют в аплоуде?

**Comment by Judge1987** [comment]
> Может быть это потому, что в ядре ИИ выключен режим "проверять авторизованный персонал", из-за которого турели не стреляют в аплоуде?

Ну дык снаружи тоже такую же функцию надо поставить по-умолчанию, а то бредово как-то.

**Comment by No-Tips** [comment]
Так ты можешь это сделать через управление турелей. Для этого багрепорт писать не стоит.

**Comment by Gojatlay** [comment]
Так и хотели. Этим все сказано. Бага в этом нет.
ИИ при желание сам может выставить эту настройку на турели.
