### ISSUE TITLE
Передел генетики

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#56]
Это рассчитано на новую систему научного отдела за работу в отделе даются медицинские "очки" которые можно использовать на исследования
- Генетика теперь будет в научном отделе
- В начале смены у тебя есть эмбрион который растет в крио
после некоторого времени он вырастает в апатика, в нем полно неисправностей с шансом на хроническое заболевание (если в таком состоянии в него запихнуть нейраллейс человек точно сдохнет)
- Ученый режет этого апатика на "детали" и пытается улучшить (исправить) каждый орган.
Исправление зависит от человека если он понял в чем причина (скажем выбрать один и вариантов лечения) в случае неправильного выбора состояние может ухудшится. При этом даются очки исследований
после этого повторяет процесс выращивания и проверяет улучшилось ли состояние и повтор процесса
- в случае полного выздоровления апатик готов к ресливеру (если конечно его сделают)
- Если наука сильно продвинулась добавить возможность у апатика появления сознания (аля рес гостов с новой личностью)
edit:

1. Выращивать можно любую расу если конечно будет эмбрион на руках (из карго мб ?)
2. В сборке есть особые подтипы расы людей (грав адаптированые и тд) можно использовать
3. Можно использовать мутации например изменение типа газа для дыхания (заставлять воксов дышать кислородом)

**Comment by Cinericius** [comment]
Генетику можно, но не в таком варианте.
