### ISSUE TITLE
[TODO] по визардам

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#560]
Рано или поздно я это сделаю (но скорее поздно чем рано):
1. Стандартизировать все книги.
1.1) В каждой книге должны быть
1.1.1) Заклинание перемещения
1.1.2) Заклинание лечения
1.1.3) Заклинание атакующее
1.1.4) Заклинание защиты
1.1.5) Специальные заклинания
1.2) Добавить ультимативные спеллы.
1.3) Разница книг должна проявляться в эффективности заклинаний и количестве заклинаний соответствующего типа.
1.4) Добавить глобальные спеллы, которые будут влиять на вот вообще весь раунд.
2. Добавить спеллы вообще. Их крайне мало.
3. Добавить интересных артефактов.
4. Добавить каких нибудь интересных интеррактов с экипажем, помимо "убей".
5. Активация абилок по клику, а не через контекстное меню, боже, какое же тупое говно. Фаерболы летящие "куда ты смотришь" это пиздец.

Визард должен стать в разы сильнее. Концепт заключается в том, что визхурд должен стать как стихийное бедствие - его не должны мочь вынести толпой сб с автоматами. Moar кооперации и интересных взаимодействие, и меньше тупого зерграша.

Мб в отдаленном будущем стоит добавить абсолютно другой метод использования магии. Like a ритуалистика, которая требует длительной подготовки, сбора ингредиентов, etc, однако спеллы которой будут иметь колоссальный результат.

**Comment by Fritcher36** [comment]
Книги не трогай, остальное - вещь. Я планирую переделать маленько файрбол. Сейчас он уносит солидный кусок станции, но мало вредит людям, в которых попал

**Comment by ZerlGray** [comment]
> Книги не трогай, остальное - вещь. Я планирую переделать маленько файрбол. Сейчас он уносит солидный кусок станции, но мало вредит людям, в которых попал

Чому книги не трогать?

**Comment by Fritcher36** [comment]
Потому что они вполне рабочие и сбалансированные. Надо сами скиллы потыкать и касты сделать по клику, а так списки книг вполне нормальные.

**Comment by ZerlGray** [comment]
> Потому что они вполне рабочие и сбалансированные. Надо сами скиллы потыкать и касты сделать по клику, а так списки книг вполне нормальные.

Юзлес же половина.

**Comment by Fritcher36** [comment]
Скиллы - да, потыкать. Но в самих книгах всё норм. Назови хоть один юзлес вариант?

**Comment by Cinericius** [comment]
Да почти все книги кроме стандартной и пространственной сосут, ну еще баттл-мейдж из себя что-то выдавить может.

**Comment by Fritcher36** [comment]
Остались-то друид и клирик. Клирик для мирнороли, да и при должных навыках робаста вполне может, а друиду нужно починить и пробаффать скиллы, сами они вполне неплохи.

**Comment by Voldirs** [comment]
Я за визурда не гонял ни разу, но мне кажется вот этот пунктик:
>Добавить каких нибудь интересных интеррактов с экипажем, помимо "убей" ((вот это самая охуительная мысля))
надо совместить с:
Да почти все книги кроме стандартной и пространственной сосут, ну еще баттл-мейдж из себя что-то выдавить может.

То есть чтобы на каждый сет можно было найти применение, я хоть и не любитель гринтекстодроча, но это должно зайти. Стандартизировать книги не надо.
