### ISSUE TITLE
Больше симптомов в вирусологию, богу симптомов в вирусологии

### ISSUE THREAD

**Issue by IvanDonFon** [ChaoticOnyx/OnyxBay#5604]
### Улучшение
У вирусов сейчас не так много симптомов. Ещё меньше интересных и смертельных, тех симптомов, что могли-бы сделать вирус уникальным - минимум. Вот некоторые симптомы, которые эту проблему могут решить

### Решение
* Antigen-intolerant-Adaptation-{Антиген}(4) - По достижению этой адаптации, антиген вируса, необходимый для его излечения меняется на другой, указанный в названии. Мутирует из Rapidly-Changing-Syndrome
* Rapidly-Changing-Syndrome(3) - Мутирует из Antineg-intolerant-Adaptation, при достижения этой стадии, синдром заменяется на другой, случайный синдром
* Skinner-Syndrome(2) - Заражённый теряет свою кожу и становится скелетом
* New-Personality-Syndrome(4) - Заражённый сначала теряет сознание, а на его место берётся случайный человек из гостов, после чего вирус излечивается сам по себе. Новая личность ничего не помнит о прошлой жизни, а также о жизни её оболочки, из-за чего вкладка Notes будет полностью очищена
* Wart-syndrome(2) - На теле заражённого появляются наросты, что повышает эффективность заражения контактным способом. Мутирует из Outgrowth-Syndrome
* Outgrowth-Syndrome(2) - Улучшенная версия Wart-Syndrome. На теле заражённого появляются наросты, сам заражённый начинает этими наростами кашлять, а то, что он выкашливает, некоторое время остаётся в виде ростков на стенах, от которых можно заразиться.
* Burning-Man-Syndrome(3) - Пациент самопроизвольно возгорается
* Organ-Failure-Syndrome(4) - Органы пациента начинают отказывать
* Название не придумал(2) - Пациент начинает строго верить в то, что лечиться ему не нужно, а вирус ему только поможет. Появляется стойкое желание передать этот вирус как можно большему количеству человек
* Mute-Syndrome(2) - Заражённый не может говорить
* Fake-Death-Sydnrome(4) - Заражённый время от времени теряет сознание, а на всех сканерах он показывается, как мёртвый.
* Rejection-Syndrome(3) - Кибернитические части заражённого начинают ломаться и отказывать
* Colorblindness-Syndrome(2) - Заражённый становится дальтоником
* Polymorph-Syndrome(4) - Мутирует из синдрома Манкинизма. Превращает человека в случайного моба
* Elder-Syndrome(4) - Заражённый стареет. Каждую минуту он стареет на один год. Волосы теряют окрас, а кожа становится более бледной. По исполнению сотни лет, заражённый умирает.
* Traitor-Syndrome(2) - Заражённый становится убеждён, что на судне есть некий предатель, и СБ следует его в немедленном порядке найти.

**Comment by Doster-d** [comment]
Дубликат #223
