### ISSUE TITLE
Алиены могут плеваться кислотой из вентиляции

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#5610]
### Описание бага
Если алиен заползает в вентиляцию, то он всё равно может применять способности плевков.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем алиена
2. Залезаем в вентиляцию
3. Стреляем кислотой

### Ожидаемое поведение
Алиен не должен плеваться из вентиляции.

**Comment by DarkHunter7756** [comment]
Добавлю сюда схожий баг. Алиены могут дропать фейсхагеров из вентиляции. Получается, что те возникают из-под пола, что быть ни с логической точки зрения, ни с точки зрения баланса не должно.

**Comment by MrMagick2104** [comment]
> Добавлю сюда схожий баг. Алиены могут дропать фейсхагеров из вентиляции. Получается, что те возникают из-под пола, что быть ни с логической точки зрения, ни с точки зрения баланса не должно.

Это, конечно, тоже очень нехороший баг, но к алиенам он слабо относится. У нас любые мобы могут скидывать вещи из вентиляций, что приводит ко всяким макакам-гренадёрам.
Тем более, что уже есть [иссуй на эту тему](https://github.com/ChaoticOnyx/OnyxBay/issues/3613).

**Comment by TobyThorne** [comment]
Ну ёлки, ну прикручивал же абилкам проверку на вентиляцию. Видимо, не всем прикрутил.
