### ISSUE TITLE
Звуки в игру

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#57]
Добавить в игру звуки для многих действий, эмоций  и предметов
например :  Крик , чих, гейгер, торговые автоматы и тд

**Comment by Ruforce** [comment]
>крик

тогда нужно делать делей на эмоуты

**Comment by Ruforce** [comment]
иначе можно будет класть сервер

**Comment by Epicus7** [comment]
Откуда озвучку будем брать?

**Comment by LagannPM** [comment]
freesound или другие билды

**Comment by Epicus7** [comment]
Ну добавить можно, когда-нибудь потом. Делеи надо не на эмоуты, а на их озвучку ставить для каждого объекта.

**Comment by LagannPM** [comment]
я однажды видел как чуваку засовывали станбатон в жопу и он спамом крика засрал весь чат

**Comment by Voldirs** [comment]
>спамом крика засрал весь чат
Смари, можно сделать так что если персонаж делает 5 скримов в секунду или более, то у него рвутся лёгкие))
