### ISSUE TITLE
Педальные ранги не берутся из конфигурации

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#5707]
Педальные ранги загружаются из конфигов в методе **/proc/load_admin_ranks()**.

Но при попытке редактирования опции из которых можно выбрать ранг - захардкожены на список "Game Master","Game Admin", "Trial Admin", "Admin Observer":
https://github.com/ChaoticOnyx/OnyxBay/blob/20593094585c2d074a6cef278eb6e521c917cd2f/code/modules/admin/topic.dm#L130

Нужно пофиксить код по последней ссылке так, чтобы ранги и соответствующие пермишены брались из конфига, а не были захаркожены. Ранг и пермишены будут отправляться в БД точно так же, как будто их руками проставили, с точки зрения БД ничего менять не надо.

**Comment by kreeperHLC** [comment]
Только что проверил и всё работает. По коду - хардкод вызывается только при случае, когда ранги в конфиге пусты.
