### ISSUE TITLE
Русификация анонса о радшторме

### ISSUE THREAD

**Issue by LegatePritcher** [ChaoticOnyx/OnyxBay#574]
**В чем смысл вашего улучшения? Какую проблему оно решает?**
Я хочу, чтобы анонс о радшторме был на русском языке. Мало того, что на русском языке, так ещё и с прямым указанием: "СТУПАЙТЕ В ТЕХТОННЕЛИ ДО ТЕХ ПОР, ПОКА ШТОРМ НЕ ЗАКОНЧИТСЯ И НЕ РАЗВЕЕТСЯ". В итоге, русификация:
1) Самого анонса о радшторме;
2) Анонса об открытых техах;
3) Анонс о начале;
4) Анонс о конце;
5) Анонс о закрытых техах.

**Дополнительная информация**
Спасите.

**Comment by PlinHost** [comment]
Русификация только опциональная, плс.

**Comment by gurland** [comment]
#676

**Comment by Voldirs** [comment]
Космонавты должны страдать...

**Comment by kreeperHLC** [comment]
Да тут английского 1 класса хватит
