### ISSUE TITLE
Переработать картечь дробовика

### ISSUE THREAD

**Issue by MrMagick2104** [ChaoticOnyx/OnyxBay#5747]
### Улучшение
Сейчас, при стрельбе картечью, дробовик выпускает 1 (один!) кусок, который летит прямо всё своё ничтожное время существования, по какой-то причине не разлетаясь. Более того, он практически во всём уступает слагу: ниже урон, нет пенетрейшна, угасает со временем быстрее и т.д.
Картечь, фактически, довольно бесполезна.

### Решение
Впилить разлёт картечи дробовика. Опционально изменять его в зависимости от типа дробовика, например, так:
-Боевой и барменский - 30 градусов разлёта
-Обыкновенный варденовский - 45 градусов
-Самодельный и обрез - 60 градусов.
Это позволит дробовикам с картечью быть намного эффективнее, чем сейчас. Они даже станут конкурентами слагов: увернуться при наличии разлёта сложнее, а попасть - проще.

В принципе, это уже реализовано на ТГ и некоторых других билдах, так что можно портировать оттуда.

Стоит, также, впилить соответствующие спрайты картечи, а то выглядеть будет неказисто.

**Comment by TobyThorne** [comment]
> он практически во всём уступает слагу: ниже урон, нет пенетрейшна, угасает со временем быстрее и т.д.

Слаг:
- 55 урона
- 20 арморпена
- х1 множитель урона по органам
Дробь:
- 20*6 урона (-20 за каждый тайл)
- 0 арморпена
- х1.2 множитель урона по органам

В итоге у слагов хороший урон в любых ситуациях, у дроби - огромный упор при стрельбе вблизи по целям без брони и плоховатый в остальных случаях.
