### ISSUE TITLE
Heat Exchange Pipes не охлаждают почти.

### ISSUE THREAD

**Issue by LLIkolnik** [ChaoticOnyx/OnyxBay#575]
**Описание бага**
Heat Exchange Pipes (которые такие радиаторы в космосе) не работают так, как должны работать. Охлаждают ОЧЕНЬ медленно.

**Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем хрупкого трапика, канистру форона и радиаторы возле суперматерии.
2. Открываем помпу, закачивающую форон в контур.
3. Нажимаем анализатором воздуха по контуру.
4. Видим ошибку в генетическом коде бэедауна. Девятнадцать градусов. Охлаждение идёт, но до боли медленно. На полное охлаждение канистры с фороном уйдёт не меньше четырёх часов. Точного времени не будет.

**Ожидаемое поведение**
Трубы как на ВГ, охлаждают нормально, быстро, эффективно. 

**Скриншоты**
![image](https://user-images.githubusercontent.com/32063181/59853029-84d70f00-9389-11e9-96d9-c3b79c518352.png)
Это за восемь минут где-то. Два градуса сбилось. Ря?

**Характеристики**
 - OS: Окна. 
 - Версия клиента:  512.1470
 - Версия сервера: за десятое мая.
 - ID игры: локалка.

**Дополнительная информация**
Хочу ВГатмосмашинерию, но кому моё мнение нужно. Это далеко не критбаг, но разнёрф очень сильно поменяет мету материи на ТЭГах с большим шансом. Настолько сильно, что нам придётся думать головой.

**Comment by Voldirs** [comment]
Ммммм, а почему газ должен охлаждаться быстро в вакууме? Ря?

**Comment by DeltaEpsilon7787** [comment]
Это абсолютно нормальное поведение. Беевцы используют формулу идеального темного тела -- потеря температуры сделана вполне реалистично. [Black-body radiation](https://en.wikipedia.org/wiki/Black-body_radiation)

Температура слишком низкая. Попробуй для интереса засунуть туда что-то на 5000 градусов -- оно будет гораздо резвее охлаждаться, за счет чего суперматерия и работает, потому что иначе бы суперматерия тупо перегревалась.

**Comment by kreeperHLC** [comment]
Как говорится, не баг а фича
