### ISSUE TITLE
Добавить возможность изменять транспортную систему станции

### ISSUE THREAD

**Issue by Artemonim** [ChaoticOnyx/OnyxBay#5767]
### Улучшение
В данный момент цели доставки трубопровода захардкожены в карту и их нельзя изменить IC
> у мусорок нет имен
> никакого меню настройки тоже нет
> на карте есть перекрестки труб где указано какой таг посылок отправлять в сторону
> ингейм ты никак это не изменишь

В устройстве Destination Tagger есть опция Custom Location, но она никак не используется, так как в принципе нельзя создать какую-либо локацию, которая не вбита в устройство изначально.

### Решение:
 Добавить меню настройки в sorting pipe.
Это односторонне направленная труба с ответвлением вправо.
Вписывать в неё названия локаций. Если указание на теге соответствует любому из списка - посылка отправляется вправо.

### Дополнительные проблемы
- Для решения задачи также необходимо изменить работу трубы "sorting pipe (untagged)". В данный момент она проверяет теги на посылке по списку назначений. Необходимо сделать так, чтобы она проверяла лишь наличие тега, а не его содержание.
- ~~Остаётся вопрос, как изменять список локаций в существующих и новых destination tagger-ах, ответа на который у меня нет. А этот вопрос нужно решить, так как на локации вне этого списка скорее всего забьют.~~ [есть решение в обсуждениях](https://github.com/ChaoticOnyx/OnyxBay/issues/5767#issuecomment-869156991)
- Если новые направления не будут гарантированно автоматически попадать в список таггеров, то это может быть способом провести почту в секретные отсеки - тут и пригодится кнопка таггера Enter Custom Location.

**Comment by Artemonim** [comment]
Буду благодарен, если будет сделано вместе с #5770

**Comment by Artemonim** [comment]
Предложенная в Discord реализация:
>> давай поэтапно: ты делаешь трубу, тебе надо вкодить её "таггирование", а затем прилепить новый таг в список тагов?
> 1. Ставим сортировочную трубу
> 2. Вписываем в неё ключевые слова
> 3. Если на теге посылки есть одно из ключевых слов - посылка уходит в сторону
> 4. Дальше, каким-то магическим образом, новые теги должны попадать в устройство destination tagger, а удалённые из него исчезать.
> 4а. При этом, хотелось бы иметь возможность создать направление, но не вписывать его в таггер - анатаги смогут делать скрытые пути направления, которые нужно прописать в таггер, а не просто выбрать.

> Можно сделать датум и там хранить все места посылок, а потом для таггера черпать их оттуда.
> А обновлять этот датум стоит в двух случаях: когда его обновляют (например, через мультитул прописать, да) и когда его уничтожают опять вызывать обновление и стирать строчку, ну а таггер будет подхватывать списки, когда его активируют в ручках.
> Может, конечно, не самый лучший вариант, ибо каждый раз когда берешь таггер считывание будет, но приемлимый.

**Comment by PlinHost** [comment]
Автоматическое добавление в таггер ключевых слов при настройке трубы чот такое. Можно в какую-нибудь консоль запихать настройку ключевых слов для таггеров, ну и всегда есть кастомная локация. Можно также сделать секретный тег, доступный только при емаге консоли или таггера.
Еще есть идея сделать сканер, который при проходе по трубам собирать все теги и обновлять базу.
