### ISSUE TITLE
Сегмент трубопровода с клапаном (закрывающимся при потери целостности трубопровода)

### ISSUE THREAD

**Issue by Artemonim** [ChaoticOnyx/OnyxBay#5770]
### Улучшение
Добавить сегмент трубы с клапаном.

Такой сегмент может понадобится, чтобы закупорить трубопровод при его ремонте.
То есть, произошло разрушение отсека. Ставим блокирующий сегмент. После восстановления трубопровода открываем клапан, и все посылки, что скопились, возобновляют свой путь по трубопроводу.

### Опционально
Если это возможно закодить, хотелось бы, чтобы такой клапан мог проверять целостность трубопровода перед собой и автоматически закрываться при возникновении повреждений в трубопроводе.

- Для инженеров на станции появится новая дополнительная задача - улучшить трубопровод, разместив в нём подобные клапаны;
- Это позволит провести на шаттлы автоматически блокирующиеся трубопроводы.

**Comment by MrMagick2104** [comment]
Для этого уже есть шатофф валвы и магнитные клапаны, цепляющиеся на трубы из инженерного раздатчика, разве нет?

**Comment by No-Tips** [comment]
Ура! Я не изучают атмоснауку, и лезу в иссуи!

**Comment by No-Tips** [comment]
У нас есть стазис клампы и шатофы, но ведь я лучше напишу иссуй, чем полезу изучать!

**Comment by NefrNerf** [comment]
Люди выше написали, почему иссуй - не имеет смысла

**Comment by Artemonim** [comment]
@MrMagick2104 @No-Tips @NefrNerf речь про грузовой трубопровод, а не про атмосферные трубы
