### ISSUE TITLE
Невидимые сообщения в чатике

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#578]
### Описание бага
![mfff](https://user-images.githubusercontent.com/4889771/59947165-3141ef80-9475-11e9-8c8e-b1827b5cdb82.png)

### Воспроизведение
Заходишь на сервер, пялишься в чатик

### Ожидаемое поведение
???

### Скриншоты
Выше сделал

### (Опционально) Дополнительная информация
Вылезло после последнего апдейта

### (Опционально) Характеристики
Долго искать

**Comment by Vmihey** [comment]
Зачинено господином Улиткой
