### ISSUE TITLE
Внедрение полезных функций в "ПИИ"

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#579]
-  Возможно, покажется странным, но в данный момент, **ПИИ** является бесполезной штукой, которая и может, что _отыгрывать_ "**ЕРП"** с мышками и другими озабоченными.

  

- В целом-то, будь у него возможность копировать криптоключи из радио, а также открывать двери и копировать их доступ с карт, то он превращается из бесполезной штуки в полезного недо-ассистента без балона в лапках. Подобные возможности, на мой взгляд, как раз подходят подобной штуке как **"ПИИ"**.

**Comment by v-vmikheev** [comment]
Не докопаться ради, а разъяснений для:
1) Если пии получит возможность копировать криптоключи, для чего это может использовать обладатель пии? Верно я понимаю, что он сможет читать каналы, непредназначенные для него?
2) В контексте дверей, что значит, "...копировать их доступ с карт"?

**Comment by Vmihey** [comment]
Не докопаться ради, а разъяснений для:
1) Если пии получит возможность копировать криптоключи, для чего это может использовать обладатель пии? Верно я понимаю, что он сможет читать каналы, непредназначенные для него?
2) В контексте дверей, что значит, "...копировать их доступ с карт"?

**Comment by ZerlGray** [comment]
По поводу 2. ПИИ же уже могут ломать любые двери. Но есть минус - это делается очень... очень медленно.

**Comment by Voldirs** [comment]
Для начала было бы неплохо чтобы за них можно было бы зайти БЕЗ ВАЙТЛИСТА

**Comment by Exapster** [comment]
> 
> 
> Не докопаться ради, а разъяснений для:
> 
>     1. Если пии получит возможность копировать криптоключи, для чего это может использовать обладатель пии? Верно я понимаю, что он сможет читать каналы, непредназначенные для него?
> 
>     2. В контексте дверей, что значит, "...копировать их доступ с карт"?


 Вообще, без доступа в канал отдела, в котором работает, он вообще никакого смысла не имеет, ибо это глухая и, получается, бесполезная хрень. Конечно, с этим можно легко поспорить "А как он с этим поможет". В целом-то, хотя бы не будет молчаливым куском пластика, коих так много на станции ходит. И да, возможность копировать крипто-ключи - можно заменить на вставку этих же ключей в корпус ПИИ. Знаете ли, тоже вариант. 

 Копировать доступ с карт - это как картой агента провести по другой карте, разницы нет. Опять же, вам будет лень писать код, как можно (было бы) запихать ПИИ в консоль и выдать ему тот же доступ, дабы этот кусок пластика мог открыть дверь в ваш отдел, а не истошно орать в общее радио и "Просить и умолять" хозяина открыть ему этот шлюз. 

 В данный момент, ПИИ - это недо-ассистент. Он без доступа куда-либо, без особых возможностей, кроме, конечно, взлома дверей. Да, бл*ть, это такая полезная способность.

**Comment by Exapster** [comment]
> 
> 
> Для начала было бы неплохо чтобы за них можно было бы зайти БЕЗ ВАЙТЛИСТА

Это уж приколы наших Девелоперов.

**Comment by Epicus7** [comment]
Чот опять накидано в одну иссую, как в помойку.

Нужно разобрать на отдельные иссуи и оценить действительно ли оно нужно.

**Comment by Cinericius** [comment]
Для начала надо идей внести. Копирование криптоключей я бы заменил непосредственно вставлением их в пИИ как в наушник, благо вытащить их из наушников дело двух кликов.

**Comment by Cinericius** [comment]
Копирование доступа карт - это смешное, да. У триторов для этого специальные карточки есть, а тут бесплатно всем вообще.
Разве что, опять же, сделать возможность вставить в него карту или две.

**Comment by koronoshka** [comment]
Внедрите хотя бы функции программ с ноутбука/планшета. Было бы очень удобно просматривать камеры своего отдела не теряя контроль персонажем. Плюс там куча других полезных фич вроде управлением каргошаттлом, непрослушиваемая почта, недоигрушки для вечно скучающих Пии, на некоторых билдах мониторинг материи и энергии на станции, и еще бог знает чего. Все это просматривать через Пии для разных глав будет очень полезно. Раз уж Пии буквально уменьшенный ИИ (даже открывашка дверей есть), дак пусть и этими функциями с консолей может пользоваться.

**Comment by Cinericius** [comment]
А вот это в принципе можно, хотя там есть некоторые жирные вещи, в том числе требующие доступ.

**Comment by koronoshka** [comment]
Ну думаю возможность считывай карточку нужно вводить так или иначе. Это как бы базис для введения чего-либо полезного для пИИ. В чем нужно разобраться, это в том как такие функции будут вообще установлены на пИИ, ведь его свободное место и свободное место на ноутбуках работают на совершенно разных величинах. Бонусом хорошо бы привинтить возможность установки в диррективах не просто устные запреты и разрешения на пользование определенными программами. КМовский пИИ заказывающий тысячу клоунских костюмов конечно весело, но регулировать то это надо.

**Comment by Cinericius** [comment]
Можно авторизацию проведением карты. Тогда пИИ не сможет неавторизованно чудить.

**Comment by koronoshka** [comment]
Не знаю, можно ли тут так некропостить, но только подумал что пИИ нужно ввинтить сигналлер. Обычно эта такая штука с которой долго возиться самому (особенно если сигналов несколько) и которую было бы удобно перекинуть на подручного. Можно будет нормально бомбы активировать если на пол повалят. Жаль только не сможет угрожать нажатием на кнопку.

**Comment by Cinericius** [comment]
Кстати про сигналлер для пИИ годная тема.

**Comment by NefrNerf** [comment]
Геймдизайнеры закрыли в #4391
