### ISSUE TITLE
Поднять минимальный возраст аккаунта на сервере для доступа к ролям до двух месяцев.

### ISSUE THREAD

**Issue by wadangel** [ChaoticOnyx/OnyxBay#5794]
### Улучшение
Чтобы уменьшить количество абсолютных новичков, ещё не ознакомившихся с особенностями билда и сервера на таких важных позициях.
### Решение
В заголовке.
### Дополнительная информация
![image](https://user-images.githubusercontent.com/29904082/123629729-0e99fc80-d82e-11eb-8dc8-0965170d787a.png)

**Comment by Epicus7** [comment]
Завел другой баг #5884 с выносом значения в конфиг. В конфиге потом настроите сами у себя.
