### ISSUE TITLE
Задание "украсть ИИ" может выпасть, если ИИ нет

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#58]
В принципе, его можно собрать, но мне кажется, что это не нужно и лучше пофиксить.

**Comment by kreeperHLC** [comment]
Так пустая оболочка ИИ вроде как всегда есть в ядре

**Comment by Ruforce** [comment]
Там идет проверка на интелкарту с мобом внутри.

Следовательно, тебе нужно собрать свой личный ИИ.
