### ISSUE TITLE
Лечение мозга у мёртвых людей

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#583]
### Описание бага
Можно починить мозг человеку, у которого умер мозг. Слава б-гу, это не воскрешает трупик, но такой воскрешенный мозг внезапно можно пересадить куда-нибудь.

### Воспроизведение
Убиваешь человека, вскрываешь череп, лечишь мозг, вырезаешь и пересаживаешь его куда-нибудь.

### Ожидаемое поведение
Если мозг умирает, то это по сути гейм овер, для того чтобы вернуть умершего в билде есть нейросетка. Эта механика работает, хоть и коряво, но всё же работает.

**Comment by Fritcher36** [comment]
Воскрешается ли игрок? Или мозг просто становится здоровым куском мяса? По идее мозг должен просто быть предметом, в который можно всадить нейраллейс.

**Comment by Voldirs** [comment]
Мозг становится внезапно пригодным для пересаживания в мми, чего происходить не должно. А нейралейс не втыкается в мозг, это отдельный орган

**Comment by LegatePritcher** [comment]
Бамп.

**Comment by TermService** [comment]
не подтверждено. Вылеченный мозг не дает никаких преимуществ, он просто умирает снова и снова. А вот если клиент не убегал с мозга то да, его можно пересаживать, награда за черный экран.

**Comment by kreeperHLC** [comment]
Вылеченный мозг можно в МИИ засунуть

**Comment by TermService** [comment]
Мозг который умер тоже можно засунуть, главное чтобы клиент был в нём
