### ISSUE TITLE
Бесконечное мясо и пусть никто не уйдет обиженным.

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#585]
_Внимание: эта задача оплачивается. Если вы хотите выполнить её, обязательно заасайните себя на эту задачу и сообщите об этом в комментариях._

### Описание задачи

Meat grinder производит бесконечное мясо, если в него засунуть disfigured head. Необходимо исправить данное поведение. Если игрок в meat grinder положил disfigured head, или любую иную конечность или орган, то орган или конечность должны быть уничтожены, а содержимое meat grinderа, соответственно, опустошено. При этом, meat grinder должен производить конечное количество мяса. Произведенное мясо должно содержать корректное описание, что это за мясо, аналогично тому, как это происходит сейчас.

### Критерии приема задачи

- Meat grinder производит конечное количество мяса из disfigured head, опухолей и прочих генкоорганов. Из одной курицы производится пара кусков, посему, предлагается создавать также только пару кусков из disfigured органов, и по одному из опухолей.
- Meat grinder уничтожает их в процессе также, как он это делает сейчас для человека, или животных.

Если у вас есть вопросы по требованиям, адресуйте их автору задачи в комментариях, либо @Vmihey. Также вопросы можно задать в нашем официальном [discord](https://discord.gg/VCDcen2).

### Вознаграждение: Кружка кофе.

[Chaotic Onyx](https://discord.gg/VCDcen2) одобряет выполнение всех задач. Однако, за данный issue разработчику, выполнившему все требования, будет выплачено вознаграждение в размере стоимости указанного количества кружек кофе. Критерии выполнения будут проверяться ответственными лицами. К сожалению, мы не можем предусмотреть всех нюансов выполнения задачи, однако, мы действительно стараемся максимально полно описывать требования. Будьте готовы, что некоторые детали требований могут быть не предусмотрены. Внимание: не следует воспринимать это как плату за работу. Ваша работа стоит значительно дороже. Это просто небольшой, но приятный бонус, которым мы хотим вас поддержать. Стоимость непритязательной кружки кофе в Петербурге на данный момент 70₽.

Также, пожалуйста, обращайте внимание на комментарий "Подтверждено" от @Rampoch или @Vmihey. Это гарантирует, что выполнение этой задачи будет вознаграждено. Chaotic Onyx не несет ответственности за любые иные обещания награды. Они остаются целиком на совести обещающих.

**Comment by Vmihey** [comment]
Подтверждено.

**Comment by ZerlGray** [comment]
> Meat grinder уничтожает их в процессе также, как он это делает сейчас для человека, или 
> животных.

Хуево подтверждено. Он делает бесконечное мясо из вообще любых мобов. Условие - моб должен быть жив.

**Comment by Vmihey** [comment]
>Хуево подтверждено

Ты жопой читаешь, к чему это относится. Комментарий относится к тому, что это не рандомные обещания, а наши, и мы несем за них ответственность.

>Он делает бесконечное мясо из вообще любых мобов. Условие - моб должен быть жив.

Нет, не делает. Вот локальный запуск дева на текущем состоянии.

https://imgur.com/a/HvELBIf

https://imgur.com/IQ4h3Ho

Алсо, ты в дискорде говорил, что там **нет рантаймов**. Вот он:

![Gib](https://user-images.githubusercontent.com/26259146/61282960-ff4a5180-a7c4-11e9-9207-5189df987ea9.JPG)

**Comment by ZerlGray** [comment]
> > Хуево подтверждено
> 
> Ты жопой читаешь, к чему это относится. Комментарий относится к тому, что это не рандомные обещания, а наши, и мы несем за них ответственность.
> 
> > Он делает бесконечное мясо из вообще любых мобов. Условие - моб должен быть жив.
> 
> Нет, не делает. Вот локальный запуск дева на текущем состоянии.
> 
> https://imgur.com/a/HvELBIf
> 
> https://imgur.com/IQ4h3Ho
> 
> Алсо, ты в дискорде говорил, что там **нет рантаймов**. Вот он:
> 
> ![Gib](https://user-images.githubusercontent.com/26259146/61282960-ff4a5180-a7c4-11e9-9207-5189df987ea9.JPG)

Я запускал локалку. Не было рантаймов. И inf мясо делалось даже из куриц, если их заживо запихать.
Могу даже скрин скинуть, так же.
Там occupant не исчезает просто.

**Comment by ZerlGray** [comment]
![image](https://user-images.githubusercontent.com/32713309/61286965-a54d8a00-a7cc-11e9-854d-f91fe91fa0c8.png)

**Comment by ZerlGray** [comment]
Да у тебя самого на первом видео тоже самое показано, что он делает из живого моба inf мясо. Без рантаймов, о чем ты вообще?
