### ISSUE TITLE
Актуализировать Donations Panel

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#586]
_Внимание: эта задача оплачивается. Если вы хотите выполнить её, обязательно заасайните себя на эту задачу и сообщите об этом в комментариях._

### Описание задачи

Актуализировать Donations Panel

1. При нажатии на донат панель игрок получает сообщение "You have not donated or donations database is inaccessible". Это сообщение мало дает понимания, что на самом деле происходит. Будет хорошо, если сообщение будет уточнено. Нужно разделить его на два случая: _действительно нет подключения к базе_ и _нет донатов от игрока_.
2. Нужно _полностью_ актуализировать предметы в панельке, чтобы в ней были только те предметы, которые реально работают. Безжалостно выбрасывайте нерабочие версии, или версии, которые имеют серьезные проблемы. Выброшенные предметы по возможности заменяйте на аналогичные по ценности. Соберите в список типы всех выброшенных из панели предметов, а также укажите в нём, по каким причинам был удалён каждый предмет. Передайте нам этот список для дальнейшего использования.
3. Текущий принцип работы поощрений в донат панели не соответствует нашему видению. Требуется изменить поведение на систему обычной покупки: у игрока есть некая сумма на счету, на которую он может покупать интересующие его предметы. После приобретения с лицевого счета игрока списывается сумма равная сумме покупки, сохраняется в БД, а купленный предмет становится доступен игроку в этом и во всех последующих раундах. Очевидно, для списания необходимо сделать запрос в базу, уменьшающий *текущее* количество донатных очков. Если предмет уже был доступен игроку, необходимо, чтобы система сообщала ему о том, что покупка не была совершена, т.к. предмет уже куплен. Каждый купленный предмет можно достать только один раз за раунд. Для лучшего понимания ситуации, сейчас мы имеем систему при которой сумма доната равняется сумме очков в донат панели. Эти очки в свою очередь свободно тратятся в течении раунда и восстанавливаются вновь в следующем раунде.

### Критерии приема задачи

- При нажатии на донат панель выпадающее сообщение об ошибке разделено на два разных сообщения и выбрасывается только в соответсвующих сообщению случаях.
- Все награды в донат панели - рабочие предметы не имеющие серьезных проблем с игровой механикой.
- Количество предметов в донат панели не менее 70. Сейчас их больше 80.
- Все удаленные из донат панели предметы перечислены в списке, с указанной для каждого причиной удаления.
- Приобретение предметов в донат панели возможно единственный раз для аккаунта.
- Игрок, купивший предмет N имеет возможность получить предмет N один раз в этом, и в каждом следующем раунде.
- Сумма лицевого счета при покупке уменьшается соответственно стоимости купленного предмета и сохраняется в БД, в колонке current.

Если у вас есть вопросы по требованиям, адресуйте их @Rampoch в комментариях, либо @Vmihey. Также вопросы можно задать в нашем официальном [discord](https://discord.gg/VCDcen2).

### Дополнительная информация

![image](https://user-images.githubusercontent.com/26259146/60355447-0f95ba80-99d7-11e9-9109-c8efe8884f1a.png)

Структура таблицы, с которой предстоит работать (База MariaDB):

```sql
CREATE TABLE IF NOT EXISTS `donators` (
  `ckey` varchar(32) NOT NULL DEFAULT '',
  `total` float(7,2) NOT NULL DEFAULT 0.00,
  `current` float(7,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`ckey`)
) ENGINE=Aria  DEFAULT CHARSET=utf8 PAGE_CHECKSUM=0;
```

### Вознаграждение: **13** кружек кофе.

[Chaotic Onyx](https://discord.gg/VCDcen2) одобряет выполнение всех задач. Однако, за данный issue разработчику, выполнившему все требования, будет выплачено вознаграждение в размере стоимости указанного количества кружек кофе. Критерии выполнения будут проверяться ответственными лицами. К сожалению, мы не можем предусмотреть всех нюансов выполнения задачи, однако, мы действительно стараемся максимально полно описывать требования. Будьте готовы, что некоторые детали требований могут быть не предусмотрены. Внимание: не следует воспринимать это как плату за работу. Ваша работа стоит значительно дороже. Это просто небольшой, но приятный бонус, которым мы хотим вас поддержать. Стоимость непритязательной кружки кофе в Петербурге на данный момент 70₽.

Также, пожалуйста, обращайте внимание на комментарий "Подтверждено" от @Rampoch или @Vmihey. Это гарантирует, что выполнение этой задачи будет вознаграждено. Chaotic Onyx не несет ответственности за любые иные обещания награды. Они остаются целиком на совести обещающих.

**Comment by Vmihey** [comment]
Подтверждено.

**Comment by DeltaEpsilon7787** [comment]
Закодь панель в 2014 @ Чисти в 2019 за награду.

**Comment by DeltaEpsilon7787** [comment]
Сделано.
