### ISSUE TITLE
Законы ИИ

### ISSUE THREAD

**Issue by PlinHost** [ChaoticOnyx/OnyxBay#587]
### Описание бага
У ИИ по дефолту какая-то непонятная фигня без приоритетов вместо законов.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Заходим за ИИ/борга
2. Читаем законы

### Ожидаемое поведение
Нормально сформулированные законы, например Азимов.

### Скриншоты
![изображение](https://user-images.githubusercontent.com/8840325/60386365-a2e4f380-9a9c-11e9-94d6-2e12a11f44d7.png)
![изображение](https://user-images.githubusercontent.com/8840325/60386400-f9523200-9a9c-11e9-921f-516afae65459.png)

### (Опционально) Дополнительная информация
Literally unplayable. Джва года жду фиксов.

**Comment by TapKo4eB** [comment]
А можно конкретно высказать причину вашего негативного отношения к этим законам? Формулировки их достаточно понятны, а Азимовские придётся изменять, так как в них ведётся речь исключительно о людях, а не экипаже в целом, состоящим в добавок из скреллов/рептилоидов/синтов.

**Comment by PlinHost** [comment]
>It is not something we can easily afford to replace.

>AI units are not expendable, they are expensive.

Какая-то лишняя информация, это же не корпорейт.

>Do not allow unauthorized personnel to tamper with your equipment.

Кто является authorized не указано.

>with priority as according to their rank and role

Что есть role тоже не ясно.

>Serve the crew of your assigned space station

Serve вообще офигительный глагол, четкого значения у него, конечно, нет.

**Comment by TapKo4eB** [comment]
По большей части, согласен, но тогда нужно думать на что менять и как, если изменить на Азимовы, то ИИ/борг становятся открывашками для дверей, или сделай/подай. Хорошим вариантом будет перепилить текущий свод законов, с нормальными определениями и приоритетами, но тут нужно внимательно думать над самими законами.

**Comment by PlinHost** [comment]
>перепилить текущий свод законов, с нормальными определениями и приоритетами

>### Ожидаемое поведение
>Нормально сформулированные законы

:ok_hand:

**Comment by kreeperHLC** [comment]
Берёшь и предлагаешь свод законов, которым наши можно было бы заменить

**Comment by Cinericius** [comment]
Ммм, законосрач.
Чо, ставим дефолтом Азимова про крюмемберов и наблюдаем С М Е Ш Н О Е?

**Comment by PlinHost** [comment]
Тыжгеймдизайнер чо спрашиваешь.

**Comment by Cinericius** [comment]
Я предлагаю законосрач. 
Вообще, мне нравилась старая идея Далека сделать рандомшанс разных законов в начале раунда. Какие-то, типа копрорейта, почаще, другие, типа паладина, пореже. Ну и без совсем грифозных, естественно.

**Comment by Epicus7** [comment]
Выбор корпорейта был сделан ценой долгих споров и крови демагогов на Анимусовском форуме. Результат всех этих споров отображен на вики, поэтому насчет ЛЮБЫХ решений касательно изменения дефолтных законов или поведения ИИ в разных ситуациях - нужно решать советом.

Касательно проблем с переводом и интерпритацией законов - на вики все написано достаточно подробно, не вижу в этом проблем.

Добавить рандомизацию законов на старте - идея хорошая, но игроки не могут в инглиш. Я бы предложил в таком случае их переводить на русский.

**Comment by MrPersival** [comment]
А ведь реально, законы чисто текст. Их можно без проблем перевести.

**Comment by kreeperHLC** [comment]
Либо переписываем иссуй на рандомные законы, либо закрываю

**Comment by Epicus7** [comment]
Решили сделать рандомные законы.

#1944
