### ISSUE TITLE
Вынести минимальный возраст аккаунта для игры ролями в конфиг

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#5884]
Вынести значение переменной min_player_age антагонистов в конфиг.

![image](https://user-images.githubusercontent.com/5204667/124306104-9f464480-db6e-11eb-80b7-2b7b8784a90b.png)

В конфиге можно сделать некое базовое значение, а конкретным ролям ставить процент от него. Например, трейторам - 1 единицу конфига (там поставим, например, месяц или два), магам - 1,5 единицы конфига (получится 1,5 месяца или 3).

**Comment by TapKo4eB** [comment]
>В конфиге можно сделать некое базовое значение, а конкретным ролям ставить процент от него. 
duhh, ещё доставать калькулятор чтобы высчитать особое количество дней для рольки, уж проще и понятней каждому по кол-ву дней с регистрации, а тем что не прописано брать базовое значение

**Comment by TapKo4eB** [comment]
а как ассигнуться
