### ISSUE TITLE
Не работает сканер здоровья в медицинском РИГе

### ISSUE THREAD

**Issue by Fritcher36** [ChaoticOnyx/OnyxBay#591]
### Описание бага
Просто не работает. В чат не выводит, окно не открывает.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Надеваем РИГ
2. Выбираем модуль
3. Юзаем
4. Видим ошибку ..

### Ожидаемое поведение
Окошко, как у нормальных сканеров

**Comment by LegatePritcher** [comment]
Бамп.

**Comment by MrPersival** [comment]
Попробую.

**Comment by MrPersival** [comment]
Ты же имел ввиду medical voidsuit?

**Comment by Animesku** [comment]
Rescue suit control module

**Comment by MrPersival** [comment]
Сложно, откажусь.

**Comment by Doster-d** [comment]
Ложь и провокация! Не легко, тут проблема с наноуи, наверное.

**Comment by lKameRUNl** [comment]
Отвал теперь не только с РИГовским сканнером. Второй режим обычного сканнера тоже не пашет, а должен выдавать инфу в чат как анализатор роботов.
