### ISSUE TITLE
А что по дальтонизму?

### ISSUE THREAD

**Issue by dominoCaesar** [ChaoticOnyx/OnyxBay#593]
### Описание бага
Ну, на опухе есть куча видов дальтонизма, такие как протанопия, дейтеранопия, тританопия, монохромность. 

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем Сетап черектер
2. Открываем трейты
3. Нажимаем на любой вид дальтонизма
4. Видим ошибку входя в игру что ты отличаешь все цвета как настоящий человек, а не лох инвалидный.

### Ожидаемое поведение
Ну, ты должен перестать различать цвета у вещей определенных. Например при протанопии ты должен путать красный с желтым или зеленым. При дейтеранопии - зеленый с красным и желтым. При тританопии - путаешь зеленый, синий, желтый, а синий и фиолетовый вроде не видишь вообще. Монохромность - видишь всё в серых цветах.

### Скриншоты
А что тут скринить? Ты просто все объекты где есть те цвета, какие ты якобы не можешь различать - различаешь. 

### (Опционально) Дополнительная информация
Не, нету.

### (Опционально) Характеристики
 - OS: Windows
 - Версия клиента: последняя короче.
 - Версия сервера: Client Version: 512 или это не то я хз короче Server Revision: 8466d14af150e876cc75344371299436f6645562 - release - 2019-06-21
 - ID игры: Game ID: b13-bmIr

**Comment by ZerlGray** [comment]
Это так. Извесная фича. Где то хендлер проебался. 
Забанвый факт: При этом у боргов дальтонизм работает!
Пофикшу.

**Comment by Epicus7** [comment]
Пофиксил?)

**Comment by kreeperHLC** [comment]
И не пофиксит

**Comment by dominoCaesar** [comment]
ну че как фикс

**Comment by Doster-d** [comment]
dead issue

**Comment by TermService** [comment]
Когда фикс @ZerlGray

**Comment by Doster-d** [comment]
> Когда фикс @ZerlGray

А он разве не в гробу?
