### ISSUE TITLE
Написать нормальное readme.md

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#594]
### Улучшение
В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.
ридми говно
### Решение
Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы.
очевидно, переписать ридми: добавить ссылки на стартер гайд ту бьенд на вики, ссылку на бьендреф, конфу, имена кодерастов что бы слапать, правила использования мапемержера и перечень основных фич нашей репы, е.г мапбот, автособираемая локалочка, ид ест ид ест
### (Опционально) Альтернативы
Опишите альтернативы, о которых вы думали. Почему именно ваше решение является удалить сервер и на свободных мощностях хостить майнкрафт

### (Опционально) Дополнительная информация
я хочу кушать

**Comment by Voldirs** [comment]
>я хочу кушать

![meal](https://user-images.githubusercontent.com/4889771/60533916-5e11c480-9d09-11e9-85d6-bc4657560979.jpg)

**Comment by PlinHost** [comment]
>удалить сервер и на свободных мощностях хостить майнкрафт

Какую сборку?

**Comment by kreeperHLC** [comment]
Может пора?

**Comment by PlinHost** [comment]
Частично решено гайдом в контрибут.

**Comment by Epicus7** [comment]
Не прошло и года: #2694

(на самом деле больше двух лет сидели с устаревшим ридми)
