### ISSUE TITLE
Улучшить взаимодействие космонавтов с окружением в темноте. 

### ISSUE THREAD

**Issue by Altehor** [ChaoticOnyx/OnyxBay#5948]
### Улучшение
Проблема в том, что космоснавт без источников света на абсолютно темной станции обречен на жуткую смерть, ведь дальше своего тайла он не может совсем ничего.

### Решение
Разрешить космонавтам в абсолютной темноте прокликивать ПКМом соседние с собой (то есть не далее одного тайла от своего) тайлы и, таким образом, ощупав пространство вокруг себя, взаимодействовать с окружением как обычно. Провода класть таким образом будет почти невозможно, но хотя бы шлюз вслепую открыть уже получится, а необходимость все равно угадать где там шлюз где лом достаточно замедлит космонавта сама по себе без необходимости как-то еще ограничивать.

**Comment by MrMagick2104** [comment]
Уже можно же.
Нельзя, если на тебе солнечные очки или секхуды, хотя по поводу последних не уверен.

**Comment by Altehor** [comment]
Действительно можно. Тогда правда не понятно, причем тут солнечные очки.
