### ISSUE TITLE
Пропали настройки чувствительности в настройках Air Alarm

### ISSUE THREAD

**Issue by dominoCaesar** [ChaoticOnyx/OnyxBay#595]
### Описание бага

Поломан вывод настроек чувствительности в окне Air Alarm (см. скриншоты).

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем инженера
2. Открываем аир аларм висящий на стене
3. Нажимаем Sensor Settings
4. Настройки чувствительности отсутствуют.

### Ожидаемое поведение
Ну там должны быть эти настройки, а их нету.

### Скриншоты
1. Старый вариант с вики:
![Zsu4014](https://user-images.githubusercontent.com/52449263/60575615-12612880-9da6-11e9-8063-81703c2500b4.png)
2. Вариант из билда (настройки отсутствуют):
![image](https://user-images.githubusercontent.com/52449263/60575666-2b69d980-9da6-11e9-9242-ca2182f466aa.png)

### (Опционально) Характеристики
 - OS: Windows
 - Версия клиента: Последняя, так и не понял где посмотреть.
 - Версия сервера: Client Version: 512 или Server Revision: 8466d14af150e876cc75344371299436f6645562 - release - 2019-06-21 я все равно так и не понял какой из этих пунктов нужен
 - ID игры: b14-bleO

**Comment by Epicus7** [comment]
Мда, описание было очень непонятным. Если бы скриншот, я бы так и не понял чо случилось.

Переписал описание, баг серьезный.

**Comment by Shirlineyn** [comment]
![image](https://user-images.githubusercontent.com/26092405/80382444-fab1de00-88aa-11ea-8c8d-fbf8e6911c74.png)
Все работает, закрывайте.
