### ISSUE TITLE
Бореры могут управлять телом носителя, даже если они умерли в носителе.

### ISSUE THREAD

**Issue by BooJ1K** [ChaoticOnyx/OnyxBay#5977]
### Описание бага
Если взять под контроль носителя и умереть от давления / высокой температуры (+100°c) то ты сможешь и дальше управлять телом, пока носитель не вернёт контроль или ты сам не отпустишь его.
### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Залезть в носителя.
2. Взять контроль над телом.
3. Повысить температуру или выйти в открытый космос.
4. Ждать пока в чат покажет сообщение >The cortical borer dies.
5. Бегать будучи трупом в носителе.
6. Релизнуть контроль и ты труп.

### Логи из раунда с момента смерти.
https://pastebin.com/rRw7VStn

**Comment by Epicus7** [comment]
> Залезть в носителя.
Взять контроль над телом.
Повысить температуру или выйти в открытый космос.
Ждать пока в чат покажет сообщение >The cortical borer dies.
Бегать будучи трупом в носителе.
Релизнуть контроль и ты труп.

Это нормально, что борер умирает внутри носителя быстрее, чем мозг носителя? Чот сомнительно

**Comment by Epicus7** [comment]
Тут два бага:

1. Борер не должен умирать раньше чем мозг носителя из-за проблем с атмосферой.
2. Мертвый борер, конечно, не должен управлять человеком.

**Comment by Epicus7** [comment]
Награда выдана
