### ISSUE TITLE
Госты могут участвовать в голосованиях на окончание раунда

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#598]
### Описание бага
Госты могут участвовать в голованиях на окончание раунда

### Воспроизведение
Соснул - голоснул

### Ожидаемое поведение
Гостота не должна участвовать в таких голосовалках

**Comment by Ruforce** [comment]
Зашел за ПШШШ и проголосовал, делов-то

**Comment by Voldirs** [comment]
И они тоже не должны в голосовач!!!!!

**Comment by ZerlGray** [comment]
Это логично. Иначе можно делать смешное - убить почти всех на станции, и никто не сможет голосовать. Сасат лежат, так сказать.

**Comment by Voldirs** [comment]
Правильно, лежат сосат, всё верно

**Comment by Voldirs** [comment]
Аж самому стыдно за эту опечатку, соре........

**Comment by Vmihey** [comment]
Да ладно тебе 🌞

**Comment by PlinHost** [comment]
Да ладно, класека же.

**Comment by Vmihey** [comment]
>Госты могут участвовать в голосованиях на окончание раунда

Я считаю, что так и задумано. Это же голосование для всех игроков, не только для живых.
Просто, я могу представить себе ситуацию, что в раунде на 20 человек, померло 14, а из живых двое в афк, один заварен в ящике, а оставшиеся играют в покер попивая виски.

**Comment by Vmihey** [comment]
Алсо, в случаях какого-то намеренного использования голосования не так, как задумано, я предполагаю, педали имеют кнопку отложить конец раунда.
