### ISSUE TITLE
Пытаешься попить ликерчика в удобном кресле, вместо этого происходит самооперация.

### ISSUE THREAD

**Issue by Altehor** [ChaoticOnyx/OnyxBay#5988]
### Описание бага
Пытаешься попить ликерчика в удобном кресле, вместо этого происходит самооперация.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Налил Robert Robust's Coffee Liqueur в коньячный стакан. 
2. Сел в капитанское кресло. 
3. Пьешь.

### Ожидаемое поведение
Вместо выпивания ликера кидает уведомление в чат
"Clothing on Arthur Lynch's upper body blocks surgery!"

### (Опционально) Дополнительная информация
На других напитках, стаканах и креслах не испытывал.

**Comment by MrMagick2104** [comment]
Не баг, на самом деле. Правда, выпить, сидя на кресле довольно трудно без знания как: нужно предварительно выбрать на кукле рот.
Имхо, лучше бы по-другому это реализовать, а то каждый, кто пытается пить сидя, в первый раз обливается.
Возможно, добавить окно подтверждения с выбором необходимого действия?
