### ISSUE TITLE
Возможность надеть счетчик гейгера на радиационный костюм

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#600]
### Улучшение
В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.

Сейчас, судя по всему, на радиационный костюм нельзя нацепить вообще ничего. Считаю, что должна быть возможность повесить на него счетчик, чтобы он не занимал места в кармане или рюкзаке.

### Решение
Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы.

Добавить возможность повесить счетчик гейгера на радиационный костюм, в тот самый слот, куда кладут баллон в скафандрах или пушку в броне.

### (Опционально) Альтернативы
Опишите альтернативы, о которых вы думали. Почему именно ваше решение является лучшим?

Можно и хер забить.

### (Опционально) Дополнительная информация
Добавьте любую дополнительную информацию о вашей идее. Если у вас есть какие-то ресурсы - примеры внутриигрового текста, спрайты, картинки, звуки - обязательно прикрепите. Тогда шансов, что вашу идею реализуют, будет гораздо больше.

**Comment by Vmihey** [comment]
>issues/600
гет?
