### ISSUE TITLE
Runtimes

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#604]
### Список рантаймов

**Runtime in wall_icon.dm, line 43: list index out of bounds**
proc name: update icon (/turf/simulated/wall/update_icon)
src: (178,64,6) (/turf/simulated/wall)
call stack:
(178,64,6) (/turf/simulated/wall): update icon()
the steel wall (178,63,6) (/turf/simulated/wall): update connections(1)
the steel wall (178,63,6) (/turf/simulated/wall): update material()
the steel wall (178,63,6) (/turf/simulated/wall): New(the steel wall (178,63,6) (/turf/simulated/wall), "steel", null)
/dmm_suite (/dmm_suite): create atom(/turf/simulated/wall (/turf/simulated/wall), the steel wall (178,63,6) (/turf/simulated/wall))
/dmm_suite (/dmm_suite): instance atom(/turf/simulated/wall (/turf/simulated/wall), null, the steel wall (178,63,6) (/turf/simulated/wall), 1)
/dmm_suite (/dmm_suite): parse grid("/turf/simulated/wall,/area/out...", "xy", 178, 63, 6, 1, 0)
/dmm_suite (/dmm_suite): load map impl('exodus-6.dmm', 1, 1, 6, 0, 0, 1, 0, -inf, inf, -inf, inf)
/dmm_suite (/dmm_suite): load map('exodus-6.dmm', 1, 1, 6, 0, 0, 1, 0, null, null, null, null)
Exodus (/datum/map/exodus): setup map()
Exodus (/datum/map/exodus): setup map()
/hook/startup (/hook/startup): initialise map list()
callHook("startup", null)
world: New()

-----------

**Runtime in preferences.dm, line 93: Cannot execute null.play to().**
proc name: changed (/datum/client_preference/play_lobby_music/changed)
usr: Gibber7 (/mob/new_player) ([0x3000046]) (NULL) (0,0,0) (NULL) (gibber7)
usr.loc: *null*
src: /datum/client_preference/play_... (/datum/client_preference/play_lobby_music)
call stack:
/datum/client_preference/play_... (/datum/client_preference/play_lobby_music): changed(Gibber7 (/mob/new_player), "Yes")
Gibber7 (/client): set preference(/datum/client_preference/play_... (/datum/client_preference/play_lobby_music), "Yes")
Gibber7 (/client): cycle preference(/datum/client_preference/play_... (/datum/client_preference/play_lobby_music))
Gibber7 (/mob/new_player): cycle preference(/datum/client_preference/play_... (/datum/client_preference/play_lobby_music))
No (/stat_client_preference): Click("Preferences", "infowindow.info", "icon-x=0;icon-y=0;left=1")
Gibber7 (/client): Click(No (/stat_client_preference), "Preferences", "infowindow.info", "icon-x=0;icon-y=0;left=1")

-----------

**Runtime in ignore.dm, line 40: Cannot read null.ignored_players**
proc name: is key ignored (/client/proc/is_key_ignored)
usr: Ahmed Salih (/mob/living/carbon/human) ([0x3000120]) (the brown carpet) (91,157,2) (/turf/simulated/floor/trim/carpet) (bosslobster)
usr.loc: The brown carpet (/turf/simulated/floor/trim/carpet) ([0x10199bf]) (91,157,2) (/area/security/detectives_office)

-----------

**Runtime in disposal.dm, line 150: undefined variable /turf/simulated/floor/tiled/white/var/anchored**
usr: Lucy Tedrow (/mob/living/carbon/human) ([0x300013e]) (the floor) (177,106,2) (/turf/simulated/floor/tiled/white) (nabigalko)
usr.loc: The floor (/turf/simulated/floor/tiled/white) ([0x1016748]) (177,106,2) (/area/rnd/restroom)

**Runtime in disposal.dm, line 150: undefined variable /turf/simulated/floor/tiled/white/var/anchored**
usr: Kate Shark (/mob/living/carbon/human) ([0x3000174]) (the floor) (135,125,2) (/turf/simulated/floor/tiled/white) (ceka23)
usr.loc: The floor (/turf/simulated/floor/tiled/white) ([0x1017a0b]) (135,125,2) (/area/medical/chemistry)

**Runtime in disposal.dm, line 150: undefined variable /turf/simulated/floor/tiled/var/anchored**
usr: Ahmed Salih (/mob/living/carbon/human) ([0x3000120]) (the floor) (86,119,2) (/turf/simulated/floor/tiled) (bosslobster)
usr.loc: The floor (/turf/simulated/floor/tiled) ([0x10173e0]) (86,119,2) (/area/quartermaster/office)

**Runtime in disposal.dm, line 150: undefined variable /turf/simulated/floor/tiled/white/var/anchored**
usr: Karmen Lienesku (/mob/living/carbon/human) ([0x3000163]) (the floor) (146,126,2) (/turf/simulated/floor/tiled/white) (animesku)
usr.loc: The floor (/turf/simulated/floor/tiled/white) ([0x1017b15]) (146,126,2) (/area/medical/reception)

-----------

**Runtime in tanks.dm, line 139: Cannot read null.a_left**
usr: Dallas Fisher (/mob/living/carbon/human) ([0x3000134]) (the reinforced floor) (169,108,2) (/turf/simulated/floor/reinforced) (cuhgukam)
usr.loc: The reinforced floor (/turf/simulated/floor/reinforced) ([0x101693e]) (169,108,2) (/area/rnd/misc_lab)

-----------

**Runtime in lighting.dm, line 266: Cannot read null.lighting_modes**
**Runtime in lighting.dm, line 266: Cannot read null.lighting_modes**

-----------

**Runtime in syringes.dm, line 212: The diona nymph (468) [/mob/living/carbon/alien/diona] was missing their dna datum!**
usr: Kate Shark (/mob/living/carbon/human) ([0x3000174]) (the floor) (134,123,2) (/turf/simulated/floor/tiled/white) (ceka23)
usr.loc: The floor (/turf/simulated/floor/tiled/white) ([0x101780c]) (134,123,2) (/area/medical/chemistry)

-----------

**Runtime in garbage.dm, line 351: /obj/item/weapon/cell/quantum destroy proc was called multiple times, likely due to a qdel loop in the Destroy logic**
usr: Jenna Lafortune (/mob/living/carbon/human) ([0x3000136]) (the floor) (184,123,2) (/turf/simulated/floor/tiled) (kerststf)
usr.loc: The floor (/turf/simulated/floor/tiled) ([0x101783e]) (184,123,2) (/area/rnd/lab)

**Runtime in garbage.dm, line 351: /obj/item/device/transfer_valve destroy proc was called multiple times, likely due to a qdel loop in the Destroy logic**

-----------

**Runtime in , line : bad icon operation**
usr: Unknown (as Metzger Stroheim) (/mob/living/carbon/human) ([0x30000ac]) (the plating) (111,186,2) (/turf/simulated/floor/tiled) (gurinfokusu)
usr.loc: The plating (/turf/simulated/floor/tiled) ([0x101b6b6]) (111,186,2) (/area/security/warden)

-----------

**Runtime in callbacks.dm, line 55: undefined proc or verb /turf/space/unwet floor().**

-----------

**Runtime in update_icons.dm, line 264: Cannot read null.index**
proc name: update body (/mob/living/carbon/human/proc/update_body)
usr: Dmitry_Konovalov (/mob/new_player) ([0x3000016]) (NULL) (0,0,0) (NULL) (dmitrykonovalov)
usr.loc: *null*
src: Lucas Feufer (mannequin) (/mob/living/carbon/human/dummy/mannequin)
src.loc: null
call stack:
Lucas Feufer (mannequin) (/mob/living/carbon/human/dummy/mannequin): update body(1)
the head (/obj/item/organ/external/head): unmutate()
the head (/obj/item/organ/external/head): robotize("Ward-Takahashi", 0, 1)
the head (/obj/item/organ/external/head): robotize("Ward-Takahashi", null, null)
/datum/preferences (/datum/preferences): copy to(Lucas Feufer (mannequin) (/mob/living/carbon/human/dummy/mannequin), 1)
/datum/preferences (/datum/preferences): dress preview mob(Lucas Feufer (mannequin) (/mob/living/carbon/human/dummy/mannequin))
/datum/preferences (/datum/preferences): update preview icon()
Body (/datum/category_item/player_setup_item/general/body): content(Dmitry_Konovalov (/mob/new_player))
General (/datum/category_group/player_setup_category/general_preferences): content(Dmitry_Konovalov (/mob/new_player))
/datum/category_collection/pla... (/datum/category_collection/player_setup_collection): content(Dmitry_Konovalov (/mob/new_player))
/datum/preferences (/datum/preferences): ShowChoices(Dmitry_Konovalov (/mob/new_player))
Dmitry_Konovalov (/mob/new_player): Topic("src=\[0x3000016];show_preferen...", /list (/list))
Dmitry_Konovalov (/client): Topic("src=\[0x3000016];show_preferen...", /list (/list), Dmitry_Konovalov (/mob/new_player))
Dmitry_Konovalov (/client): Topic("src=\[0x3000016];show_preferen...", /list (/list), Dmitry_Konovalov (/mob/new_player))

-----------

**Runtime in Chemistry-Holder.dm, line 11: Invalid reagents holder: *null***
proc name: New (/datum/reagents/New)
src: /datum/reagents (/datum/reagents)
call stack:
/datum/reagents (/datum/reagents): New(120, null)
/datum/changeling (/datum/changeling): ()
(/mob/living/carbon/human): make changeling()
/datum/antagonist/changeling (/datum/antagonist/changeling): update antag mob(XXX (/datum/mind), null)
/datum/antagonist/changeling (/datum/antagonist/changeling): create antagonist(XXX (/datum/mind), 1, null, null)
/datum/antagonist/changeling (/datum/antagonist/changeling): add antagonist(XXX (/datum/mind), 0, 0, 1, null, null)
/datum/antagonist/changeling (/datum/antagonist/changeling): finalize spawn()
Changeling (/datum/game_mode/changeling): post setup()
/datum/controller/gameticker (/datum/controller/gameticker): setup()

**Comment by Megmeehey** [comment]
#696
Новые переоткрою в следующих issue
