### ISSUE TITLE
АВД и его роль на станции

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#606]
В данный момент, АВД представляет из себя существо, что полностью состоит из бумаг и не имеет никакой власти на станции. Его бьют каждый, кому не лень, а СБ стоит, смотрит и ржёт над этим, хотя, АВД должен, в какой-то мере, их сдерживать. Дайте власти АВД! Дайте плюшек АВД! Или выпилите это и сделайте за место него комиссара, пожалуйста.

**Comment by Exapster** [comment]
Опять же, комиссару можно передать всю бумажную работу, вместо того же АВД.

**Comment by Voldirs** [comment]
не-не-не, лучше адвоката из него опять сделать...

**Comment by Ruforce** [comment]
комиссар вообще был турбоежиком с термалами из 2013 года, который охранял глав

**Comment by TobyThorne** [comment]
Комиссар - идиотская помесь ХоСа с детективом, своеобразная метаролька на каждый раунд. Смысла в нём нет никакого, учитывая и без того уехавший в ебеня благодаря не самым логичным техническим решениям и безграничной симпатии администрации к краснорубашечникам игровой баланс. 
АВД же, в теории, смотрится вполне неплохо - представитель NT на станции, ни больше ни меньше. Проблема в том, что Оникс - low/mid-RP сервер, да ещё и с развитым друзьяшничеством. Условный ассистент-Тамаз/Роско/Шульц/etc. может сказать ";<username> охуел, соглы?" и пойти ломать голову хоть Капитану, хоть АВД, хоть ОБРовцам и ни у кого не возникнет лишних вопросов в правильности происходящего. 

Так что наиболее логичным выглядит переименование АВД обратно в адвоката - геймплейно практически ничего не меняется, но бесполезность и спонтанное опиздюливание адвокатов хотя бы выглядит не настолько бредово.

**Comment by ZerlGray** [comment]
Если просто переименовать - ничего не изменится. Имена ничего не значат. 
Нужно добавить механа и плюшек. Сейчас помимо бумажек АВД просто физически ничего сделать не может. А на бумажки всем плевать.

**Comment by Fritcher36** [comment]
> 
> 
> Комиссар - идиотская помесь ХоСа с детективом, своеобразная метаролька на каждый раунд. Смысла в нём нет никакого, учитывая и без того уехавший в ебеня благодаря не самым логичным техническим решениям и безграничной симпатии администрации к краснорубашечникам игровой баланс.
> АВД же, в теории, смотрится вполне неплохо - представитель NT на станции, ни больше ни меньше. Проблема в том, что Оникс - low/mid-RP сервер, да ещё и с развитым друзьяшничеством. Условный ассистент-Тамаз/Роско/Шульц/etc. может сказать ";%username% охуел, соглы?" и пойти ломать голову хоть Капитану, хоть АВД, хоть ОБРовцам и ни у кого не возникнет лишних вопросов в правильности происходящего.
> 
> Так что наиболее логичным выглядит переименование АВД обратно в адвоката - геймплейно практически ничего не меняется, но бесполезность и спонтанное опиздюливание адвокатов хотя бы выглядит не настолько бредово.

Ну, будет расстреливать друзяшек. (:

**Comment by Epicus7** [comment]
У нас есть уже две идеи, которые можно реализовать. Не знаю, не будет ли перебором, если реализовать обе..

1. АВД, который может джоббанить. Подробнее в #997
2. Добавить лицензии торговцам и документы сотрудникам, которые АВД сможет проверять. Идея в том, что там могут быть ошибки, особенно если ты находишься на станции невполне законно. Подробнее в проекте https://github.com/ChaoticOnyx/OnyxBay/projects/1

**Comment by kreeperHLC** [comment]
Бесполезный иссуй, который не предлагает идей, а просто призывает что-то запилить.
