### ISSUE TITLE
Старшие сотрудники

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#607]
Хотелось бы увидеть в каждом отделе того, кто будет помогать в управление главе. Например: Тот же КМ или Смотритель - они имеют власть в отделе, но главы стоят выше их, что сильно упрощает жизнь.

**Comment by Voldirs** [comment]
Не соглашусь, карго это отдельный отсек, там км имеет смысл, за варденом функция слежения за бригом, заключёнными, оружейкой, тоже вполне осмысленная. Но какой смысл от недоСМО, недоРД и недоСЕ? Особенно от недоСЕ, потому что у инжиров и так доступ во всю инженерку есть.

**Comment by Exapster** [comment]
КМ там лишь занимает должность формального главы. Нормальный ХоП будет управлять и Сервисом и Карго лично. НедоРД, НедоСМО, НедоСЕ - могут выполнять поручения главы, тем самым снимая с них часть задач, давай время на те же бумажки.

**Comment by Animesku** [comment]
Почему бы поручения глав не выполнять простым работникам?

**Comment by ZerlGray** [comment]
не ну вообще идея здравая - чем сложнее взаимосвязи тем интереснее играть

**Comment by TobyThorne** [comment]
> не ну вообще идея здравая - чем сложнее взаимосвязи тем интереснее играть

Вводить лишние роли через механ нет смысла. В РнД и медбее просто будут РД и СМО, но без доступа в их кабинеты, а инженеры и так имеют полный доступ к своему отделу (и ко всей карте, если уж на то пошло), ибо атмосферников сократили.
Если уж кому-то так хочется играться в бумажки и скинуть обязанности на кого-то - никто не запрещает назначить заместителя из числа сотрудников через ХоПа.

**Comment by ZerlGray** [comment]
> > не ну вообще идея здравая - чем сложнее взаимосвязи тем интереснее играть
> 
> Вводить лишние роли через механ нет смысла. В РнД и медбее просто будут РД и СМО, но без доступа в их кабинеты, а инженеры и так имеют полный доступ к своему отделу (и ко всей карте, если уж на то пошло), ибо атмосферников сократили.
> Если уж кому-то так хочется играться в бумажки и скинуть обязанности на кого-то - никто не запрещает назначить заместителя из числа сотрудников через ХоПа.

ну на деле нужно не просто ввести профу а реорганизовать дерево подчинения и возможно, вообще взаимосвязи между отделами. Сейчас очень плоская вся эта хуйня.
Было бы неплохо ввести отдельную охрану в РнД, подчиняющуюся РД, перетасовать приоритеты важности (на научной станции РД - один из самых малозначимых глав - это смешное).
У торча с этим все очень хорошо (нет, я сейчас не про военную иерархию)

**Comment by kreeperHLC** [comment]
Основные недостатки идеи уже были тут написаны, и они достаточно весомы, чтобы отклонить это предложение. Максимально из этого, можно вернуть в РнД и карго СБшные посты, как сейчас в медбее (Если и его не выпилили), но эта идея для отдельного иссуя.

**Comment by TapKo4eB** [comment]
> (Если и его не выпилили)

Ещё как выпилили. И наверное даже ОЧЕНЬ давно.
