### ISSUE TITLE
Дробление гуманоидов, тонкоспрайты.

### ISSUE THREAD

**Issue by MaxFreemen** [ChaoticOnyx/OnyxBay#6083]
Пару месяцев назад, когда я только начал играть на Ониксе и писать для него код, наткнулся на репорт бага. Он сообщал о том, что у тонких кибернетических людей отсутствуют спрайты тела. Я запустил локальный сервер, чтоб проверить баг. Действительно, проблема имелась. У мужчин отсутствовало тело, а у женщин ощущалась нехватка спрайтов протезов.
![image](https://user-images.githubusercontent.com/47484306/125710842-561c7034-c9f7-4ed7-9e7a-438a65f7a47d.png)
Разницы между "slim" и "slim alt" не имелось, хотя она должна была быть. Как позже выяснилось, это была лишь вершина ледника. Отправной точкой буду считать [этот](https://github.com/ChaoticOnyx/OnyxBay/pull/2525) проект и момент введения в игру дробления конечностей на две ( руки на кисть и руку, ноги на ступню и ногу, тела на торс и бедра ).

**Суть проблемы**
Спустя год тонкие спрайты все еще сломана и я понять не могу, как уважаемые разработчики и геймдизайнеры пропустили данный проект на столь ранней стадии, проекту явно требовалось дать время на доработку. На данный момент имеется ряд проблем, которые я укажу ниже, да и сказать, что автор не пытался решить проблему с протезами - соврать. Попытки были, но автор быстро сдался, ибо, полагаю, времени на исправление протезов уходило слишком много.

Озвучу список имеющихся багов, которые мне удалось заметить. [Отсутствие рабочих тату для тонких спрайтов, имеющиеся выходят за его границы, превращая человека в ежа.](https://github.com/ChaoticOnyx/OnyxBay/issues/5711) [Тонкие спрайты таяр сломаны, рука висит в воздухе, одежда не подогнана под форму тонких котов.](https://github.com/ChaoticOnyx/OnyxBay/issues/6015) Некоторые бороды выходят за границы лиц у тонких спрайтов, создавая либо висящие в воздухе волосы, либо серый ареол. Отсутствуют тонкие версии кибернетических конечностей и тел. (Репортов двух последних багов не нашел, но для проверки в первом случае достаточно взять персонажа с тонким спрайтом, после чего посмотреть бороды, а во втором открыть .dmi файл с протезами.
![image](https://user-images.githubusercontent.com/47484306/125714662-8cb07c8d-0262-4b00-923f-861d1d63adca.png)

**Пути решения проблемы**
Я предложу несколько решений проблем, которые, возможно, помогут решить проблему.
<details>
<summary>Возможные решения</summary>
1. Установка приоритета на исправление багов тонких спрайтов, ибо они встречаются в игре очень часто, проблема лежит на поверхности.
2. Запуск экспериментального сервера для проверки таких проектов, дабы избежать проблем в будущем.
3. (Фантастика) Дробление тела на конечности будет переработана, тонкие спрайты персонажей останутся. Тело будет состоять из следующих частей: две руки, две ноги, голова, торс, бедра. Такое исправление облегчит и ускорит работу художника в несколько раз.
</details>

Мне больше нечего сказать. Хотелось бы, чтоб на эту проблему обратили внимание, возможно, приняли меры, или объяснили, что я неправ. А если же будет решено все оставить, как есть, то мой багрепорт в этом же материале будет полезен.

**Comment by kcalbCube** [comment]
Не баг

**Comment by MaxFreemen** [comment]
> Не баг

Слишком много багов связано с "небагом", чтоб его оным считать.

**Comment by kcalbCube** [comment]
приложи все иссуи.

**Comment by kcalbCube** [comment]
> В итоге, теперь художник должен рисовать два вида спрайтов, а затем дробить их на куски. И я промолчу, что в случае с женщинами есть еще третий вид спрайта, который увеличивает требуемое количество спрайтов втрое. То, что мы имеем сейчас - неуважение к художникам. Они вынуждены воевать не только с убогим редактором Dream Maker'а, но и с нашей собственной системой дробления тела, что создает гору проблем, вынуждая человека дробить готовый спрайт на кучу мелких элементов.

чё-то наговорил, а что - не ясно.
редактор DM'овский очень даже удобен, кроме отсутствия возможности цвета куралесить, что по сути не проблема - всегда можно пользоваться внешним редактором.
дробить готовый спрайт? зачем? тот кто рисовал спрайты тела сделал это за 1-2 сутки и мы просто этим пользуемся, кто вообще в последний раз их трогал?

**Comment by TobyThorne** [comment]
Какой-то роман-эпопея судя по объему, читал наискосок. 

- Тела и так отрисовываются из частей, много лет как. 
- Отсутствующие туловища-протезы у тонких мужиков можно починить за минут пятнадцать, надо просто у женских спрайтов сиськи стереть. Просто все забыли и забили.

**Comment by PlinHost** [comment]
Решается выпилом ксеносов, синтов и тату. Впрочем, бороды выпиливать нельзя, так что придется найти другое решение.

> 2. Запуск экспериментального сервера для проверки таких проектов, дабы избежать проблем в будущем

Баги распространяются только на новый функционал и ни разу не критические. Не вижу проблем в том, что они обнаруживаются на живом сервере, протестировать абсолютно всё в любом случае невозможно.

**Comment by Epicus7** [comment]
По баге с бодибилдом тонкого ФБП завел багу: #6086
Я так понимаю это основная проблема

> Пути решения проблемы
Я предложу несколько решений проблем, которые, возможно, помогут решить проблему.

Какой конкретно проблемы? Бага? Его просто пофиксить надо и все. Проблемы трех багов? Тоже можно пофиксить просто.

> 1. Установка приоритета на исправление багов тонких спрайтов, ибо они встречаются в игре очень часто, проблема лежит на поверхности.

Это новая фича и баги связаны только с ней. Приоритетными багами считаются баги, с которыми многие игроки встречаются ежедневно и которые аффектят основные механики (см. https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/issues_processing.md). На тонких ФБП почти никто не играет, судя по тому что за полгода багу никто так и не зарепортил.

> 2. Запуск экспериментального сервера для проверки таких проектов, дабы избежать проблем в будущем.

А кто будет играть на этом сервере, какие там будут правила и кто будет его модерировать? Смысла в пустом тестовом сервере не больше чем в его отсутствии, а набить его хоть сколько-то существенным (для проверки фич) количеством игроков мы его едва ли сможем.

**Comment by Epicus7** [comment]
На главный баг-репорт отдельная бага заведена, эту иссую закрываю, т.к. конкретных багов я здесь больше не вижу.
