### ISSUE TITLE
Кнопки от дверей ОБР

### ISSUE THREAD

**Issue by Exapster** [ChaoticOnyx/OnyxBay#609]
Добавить в педальную панель, раздел специальные вербы - кнопку, для разблокировки дверей с экипировкой ОБР.

**Comment by LegatePritcher** [comment]
Ну, так-то на З-лвле с базой ОБР есть отдельная маленькая комнатка с консолькой и кнопками.

**Comment by Exapster** [comment]
Она есть, но нужно делать куклу и выдавать ей доступ, чтобы открыть это всё.

**Comment by Epicus7** [comment]
Такая себе идея пилить очередной верб в эту помойку вербов. Разве гост админа не может нажимать кнопки?

Ну или можно добавить в ПКМ-меню для госта-админа при щелчке по таким дверям опцию "Open"

**Comment by Cinericius** [comment]
Я думаю можно болтировать иссуй
