### ISSUE TITLE
ПЛИТКА THROWFORCE = 0.

### ISSUE THREAD

**Issue by LegatePritcher** [ChaoticOnyx/OnyxBay#611]
### Улучшение
Скинуть throwforce плитки до нуля.

### Решение
В скидывании throwforce плитки до нуля.

### (Опционально) Альтернативы
Перебанить пацанов, что бросаются плитками.

### (Опционально) Дополнительная информация
Но зачем заниматься идиотизмом, если можно скинуть throwforce плитки до нуля...

**Comment by ZerlGray** [comment]
Нахуя. Что за пиздец идеи.

**Comment by Fritcher36** [comment]
Брат, ебни себе куском металла 40 на 40 сантиметров по ебалу и скажи, что не почувствовал.

**Comment by LegatePritcher** [comment]
Брат, дай мне дичайшую силу для того, чтобы швырнуть этот кусок металла на минимум пять метров.

**Comment by Animesku** [comment]
Может стоит сделать, чтобы дальность броска зависела от числа плиток в стаке?

**Comment by LegatePritcher** [comment]
Брат, ничто не мешает снять плитки и по-быстренькому их уложить по-одному в рюкзачок.

**Comment by Fritcher36** [comment]
> 
> 
> Брат, дай мне дичайшую силу для того, чтобы швырнуть этот кусок металла на минимум пять метров.

Он плоский. Считай, что это фрисби с хуевой аэродинамикой.

**Comment by LegatePritcher** [comment]
Ну такое. Если на то пошло, то срежьте хотя бы дальность полёта плитки, про сруфорс уже ладно.

**Comment by Fritcher36** [comment]
Так у нас она и так нерфленая, 2-3 тайла, не?

**Comment by LegatePritcher** [comment]
ЕСЛИ БЫ ОНА ЛЕТАЛА НА ДВА-ТРИ ТАЙЛА, то я бы этот иссуй не поднимал.

**Comment by Cinericius** [comment]
Вы че сука, на швятое покусились.

**Comment by Cinericius** [comment]
Врети короче
