### ISSUE TITLE
Проблема с отображением чёрного галстука / DominoCaesar

### ISSUE THREAD

**Issue by MorJams** [ChaoticOnyx/OnyxBay#614]
### Описание бага
Четкое и понятное описание сути бага.
![Баг](https://puu.sh/DT6Cc/eb46f409c6.png)
### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Выбираем чёрный галстук.
2. Не видим ничего.
3. Браво, вы молодец!

### Ожидаемое поведение
Чёрный галстук должен быть чёрным галстуком, а не невидимым.

**Comment by dominoCaesar** [comment]
Неистово плюсую, Джеймс Морган - молодец.

**Comment by Vmihey** [comment]
[Перенесено](https://github.com/ChaoticOnyx/OnyxBay/issues/623)
