### ISSUE TITLE
Используемые предметы с зарядами у боргов, заменяются на Empty, хотя заряды остаются.

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#615]
### Описание бага
Соматические гели/бинты/другая хрень с зарядами у боргов, которая были истрачены, заменяются на пустую, неюзабельную версию, хотя заряды остаются.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Садимся в Cyborg.
2. Берём к примеру Surgeon (Хирургический) ((хірурга)) модуль.
3. Каким нибудь образом быстро тратим Somatic Gel (соматиц гел), перевязывая чью нибудь тушку. 
4. Видим что он (не тушка, Somatic Gel) становится пустым, хотя заряды могут появляться. Пишем завещание так как вы теперь не сможете перевязывать любые раны.

### Ожидаемое поведение
Очевидно чтобы он не менялся на пустой, а просто восстанавливал заряды.

### Дополнительная информация
Играть больно

### Скриншоты
![image](https://user-images.githubusercontent.com/48761132/61254975-4f96c480-a76f-11e9-921e-0f0d82d1b7fe.png)

###  Характеристики
 - OS: шindows 10 
 - Версия клиента: 512.1471
 - Версия сервера: ca23cec4634352d9ccea963a99fb7cf0dd9f32db - dev - 2019-07-08
 - ID игры: b2f-dsMY

**Comment by Vmihey** [comment]
У медоборга запас биогеля не восстанавливается. Также в медориге не работает меданализатор
