### ISSUE TITLE
Да хренов понитейл два, че ты под федорой ломаешься...

### ISSUE THREAD

**Issue by dominoCaesar** [ChaoticOnyx/OnyxBay#617]
### Описание бага
Когда персонаж с, как минимум вторым понитейлом надевает как минимум федору детектива, то его прическа волшебным образом в совсем ненужном месте исчезает.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем сосаку.
2. Открываем настройку персонажа и берем понитейл 2, заходим за детектива в игру.
3. Нажимаем "снять шляпу" и "надеть шляпу", смотрим на то что меняется в персонаже.
4. Видим ошибку в причесочке и том, как она исчезает.

### Ожидаемое поведение
НУ ОНА НЕ ДОЛЖНА ПРОПАДАТЬ ДУМАЮ ТАМ.

### Скриншоты
![image](https://user-images.githubusercontent.com/52449263/61379676-2e021e00-a8d2-11e9-9558-db0b5be4bc46.png) тут мой прекрасный понитейл без шляпки
![image](https://user-images.githubusercontent.com/52449263/61379717-3fe3c100-a8d2-11e9-86fe-f30a25d4de13.png) тут мой прекрасный понитейл урезался в шляпке до страшного

### (Опционально) Дополнительная информация
Я играю только с понитейлом 2. 13 из 15 моих персонажей бабы и у 13 из 13 моих персонажей понитейл 2.

### (Опционально) Характеристики
 - OS: Windows
 - Версия клиента: Я все еще не научился смотреть, последняя короче.
 - Версия сервера: Server Revision: ca23cec4634352d9ccea963a99fb7cf0dd9f32db - dev - 2019-07-08
 - ID игры: b2h-bWFa

**Comment by Ruforce** [comment]
Рисовать и кодить исключение под понитейл будешь, конечно же, именно ты.

**Comment by Firefroge** [comment]
Клик по шляпе разлочивает причёски............................

**Comment by Voldirs** [comment]
Ооооо, а вот этого я не знал, спасибо

**Comment by dominoCaesar** [comment]
Охуеть. Фрога теперь мой герой просто.
