### ISSUE TITLE
Сторителлер спавнит триторов из гостов.

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6176]
### Описание бага
Сторителлер спавнит триторов из гостов на то место где был призрак.

### Воспроизведение
Берем сторителлер, берем госта, форсим спавн триторов, гост появляется голым с аплинком.

### Ожидаемое поведение
Триторы не должны выдваться гостам или должен производиться форсспавн гостов на шаттле в виде ассистентов.

**Comment by Naturalnenko** [comment]
Господин Нефр, прошу прощения, но есть уже три иссуя на этот счет. Ваш - третий.

**Comment by NefrNerf** [comment]
Неуважаемый господин Натуралненько, скинь их.

**Comment by Naturalnenko** [comment]
А нет, наебал, два иссуя

**Comment by Naturalnenko** [comment]
# 5951

**Comment by Naturalnenko** [comment]
#5951

**Comment by hard-res3t** [comment]
> Исправлена ошибка со спавном ролей из гостов в виде голых людей с аплинками. #6339
