### ISSUE TITLE
Убрать термалы у детектива

### ISSUE THREAD

**Issue by bosslobster** [ChaoticOnyx/OnyxBay#6188]
Я решил написать этот иссуй после того, как видел в ООСе сообщение мол "игра на детективе стала уже не та, интерес пропал в профессии". Не помню точно какой там вывод был, вроде что рольки сосут, играть не умеют интересно. Но я хочу предложить подойти к вопросу с другой стороны.
Скорее всего это предложение наберет тонну хейта и чан бурлящих говн, но я считаю, что вопрос поднять надо. Так что пожалуйста выслушайте меня. 

**Я предлагаю забрать термалы у детектива.**

Что же даст выпил термалов из шкафчика детектива?
Некоторые игроки вспыхнут и воскликнут что-то из этого:

1. Это чудовищный нерф!
2. Детектив теряет свой главный инструмент борьбы с преступностью!
3. Это убьет весь интерес игры на детективе!

А вот не совсем так:

1. Да, это сильный нерф. Но я бы сказал что термалов не должно было быть у детектива изначально. Да и СБ сейчас крайне сильно.
2. Нет, главный инструмент детектива это гибкий ум. Второстепенные - его "forensic tools".
3. Нет, это наоборот сделает игру за детектива "игрой за детектива", что априори интереснее чем игра за патрульного, смотрящего сквозь стены.

Детектив превратился из роли раскрывающей преступления в роль замечающую и пресекающую преступления. Самое неприятное в этом то, что в основном это случается исключительно из-за рандомных таймингов - залез в капитанскую или душишь повара в морозилке? Молись чтобы рядом не проходил детектив, иначе капут - твоё имя знает уже всё СБ и ИИ летит болтировать двери вокруг тебя.

Детективы просто перестали быть детективами, теперь это просто "патрульный с термалами". Сбор улик и опрашивание свидетелей ушли на второй план. А зачем заморачиваться, если можно просто гулять по станции и раскрывать большинство преступлений просто потому что "я вижу через стену что ты там делаешь".
Но это лишь половина беды - когда доходит до прямого столкновения с противником, детектив опять становится офицером и бежит стрелять/задерживать злодеев. Ведь термалы в бою дают неплохое тактическое преимущество.

Я тут не пытаюсь очернить игроков на детективах, ни в коем случае. Все эти грехи я замечал и в своей игре тоже, ибо уж больно сладок плод, невозможно устоять.

Эти проклятые термалы невозможно не использовать, но используя их ты портишь себе опыт игры на детективе.
С термалами игра может быть невероятно веселой и интересной, никто не спорит. Замечать за стенкой преступления и влетать в комнату с братками-офицерами под улюлюканье ИИ это очень и очень весело. 

Но может стоит поумерить пыл?
Может стоит дать некоторым преступлениям свершиться, чтобы у детектива наконец появилась ЕГО работа?

Само собой, что детективу надо дать какую-то альтернативу. Что именно - не знаю, надо думать. Но можно же в качестве эксперимента убрать термалы, к примеру, на недельку и посмотреть что будет.

**Comment by NefrNerf** [comment]
# Главный аргумент в сообщении выше, что детективы - это не детективы, а патрульные с термалами.
Сейчас детективы НЕ МОГУТ быть детективами в той мере в которой должны по мнению автора.

`главный инструмент детектива это гибкий ум. Второстепенные - его "forensic tools".` - Пустословие, сейчас невозможно вести "нормальную" детективную деятельность. Сейчас у детектива есть возможность получить 2 типа улик.

1. Отпечатки
2. Куски ткани

Отпечатки - этот элемент блокируется любыми перчатками, что логично.
Куски ткани - дроп кусков ткани невероятно рандомен и они не появляются там где должны, то есть, почти на любой поверхности.

# Пройдемся по убийствам и побоям:
Сейчас если приходит побитый человек, нет возможности понять чем его били. Доходит до идиотизма, можно понять чем побили труп, а вот чем побили живого человека - нет. Когда побитый может наврать о своих побоях и обвинить кого-то у детектива нет механической возможности проверить, так это или нет.

На убитом человеке не остается остатков одежды, отпечатков и прочих следов убийцы которые там должны быть, а что важнее, на одежде УБИЙЦЫ не остается никаких следов жертвы.

# Опрос свидетелей: 
В лучшем случае, смена 2 часа, поиск и опрос свидетелей, когда чаще всего свидетелей нет? Если такие есть и они не заинтересованы в смерти человека, то они сразу кричат "ААААА.....Какой-то хуй убивает вон того, вон там", где собственно опрос не нужен. А даже если и попадается нестандартное дело, то скорее всего там и не убийство а серьезная драка, которую не раскрыть по описанным в пункте выше причинам. Да и проводя опрос одного человека, детектив конечно выполнит свою работу, только вот на станции трупы появляются как грибы, пока 10 минут человека опрашивать будешь, еще 2 трупа к тебе в кабинет принесут.

# Итог:
Если брать только детективную деятельность, то убийца может просто смыть себя кровь и быть таков, не оставив НИКАКИХ следов. Опрашивая жертву или убийцу мы полностью выключаем детектива на добрые 10 минут из дела.

# Возможные варианты решения
Если убирать термалы то необходимо сделать целую кучу вещей.

1. Добавить второго детектива, а лучше - криминалиста
2. Увеличить шанс дропа кусочков тканей
3. Добавить эти кусочки ткани на атакующего и жертву
4. Добавить дроп волос с человека, для определения цвета и длинны
5. Добавить возможность опознать пол человека по характеру нанесенных ран (внезапно по тому как рана выглядит можно понять, кто ее нанес, здоровый бугай или женщина)
