### ISSUE TITLE
Спрайт ballistic arm guards сломан в кашу

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#619]
### Описание бага
Спрайт ballistic arm guards не поворачивается при повороте поворачивающего боком к экрану персонажика.

### Воспроизведение
Берём-с.
ballistic vest
Крепим ballistic arm guards
Поворачиваемся боком к экрану
Видим что у вас кровоточат глаза

### Ожидаемое поведение
Наверное они должны быть более нормальными.

### Скриншоты
![image](https://user-images.githubusercontent.com/48761132/61523034-3a928d80-aa1c-11e9-9620-7441c9fd6690.png)

### (Опционально) Дополнительная информация
ауе

### (Опционально) Характеристики
 - OS: шиндафс10
 - Версия клиента: 512.1471
 - Версия сервера:  ca23cec4634352d9ccea963a99fb7cf0dd9f32db - dev - 2019-07-08
 - ID игры: b2j-bifY

**Comment by Voldirs** [comment]
Это кстати вроде для тонкотрапов только

**Comment by TapKo4eB** [comment]
> Это кстати вроде для тонкотрапов только

Если я под "тонкотрапом" понимаю слим2, то нет. У меня обычный слим.

**Comment by Voldirs** [comment]
И то, и то тонкотрапы
