### ISSUE TITLE
Куртка детектива и галстук

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#623]
_Внимание: эта задача оплачивается. Если вы хотите выполнить её, обязательно заасайните себя на эту задачу и сообщите об этом в комментариях._

### Описание задачи

Коротко и по делу. У детектива есть две куртки следователя: красная и синяя. Они надеваются на персонажа. Нужно сделать так, чтобы их можно было застегивать на персонаже, то есть нарисовать спрайт застегнутой куртки, добавить кнопку Toggle Coat Buttons, как у куртки парамедика.
Также нужно исправить баг с черным галстуком, который при нахождении в инвентаре белый, а при надевании просто невидимый. Надо сделать так, чтобы он был черным в инвентаре, и черным будучи надетым.

### Критерии приема задачи

Красная и синяя куртки детектива должны застегиваться и изменять спрайт с помощью кнопочки Toggle Coat Buttons.
Галстук должен быть черным в инвентаре и при надевании, а не невидимым.

Если у вас есть вопросы по требованиям, адресуйте их @dominoCaesar в комментариях задачи, либо @Vmihey. Также вопросы можно задать в нашем официальном [discord](https://discord.gg/VCDcen2).

### Важная дополнительная информация
ВЫ ПОНИМАЕТЕ КАК ЭТО ОХУЕННО ВЫГЛЯДИТ???

![изображение](https://user-images.githubusercontent.com/26259146/61583491-2ac09980-ab41-11e9-84f6-936ac50dfdbe.png)

### Вознаграждение:  Три кружки кофе.

[Chaotic Onyx](https://discord.gg/VCDcen2) одобряет выполнение всех задач. Однако, за данный issue разработчику, выполнившему все требования, будет выплачено вознаграждение в размере стоимости указанного количества кружек кофе. Критерии выполнения будут проверяться ответственными лицами. К сожалению, мы не можем предусмотреть всех нюансов выполнения задачи, однако, мы действительно стараемся максимально полно описывать требования. Будьте готовы, что некоторые детали требований могут быть не предусмотрены. Внимание: не следует воспринимать это как плату за работу. Ваша работа стоит значительно дороже. Это просто небольшой, но приятный бонус, которым мы хотим вас поддержать. Стоимость непритязательной кружки кофе в Петербурге на данный момент 70₽.

Также, пожалуйста, обращайте внимание на комментарий "Подтверждено" от @Rampoch или @Vmihey. Это гарантирует, что выполнение этой задачи будет вознаграждено. Chaotic Onyx не несет ответственности за любые иные обещания награды. Они остаются целиком на совести обещающих.

**Comment by Vmihey** [comment]
Подтверждено
