### ISSUE TITLE
Revive 

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#624]
### Описание бага
В меню абилок генокрада появляется кнопка рядом с evolve - revive , но на 3 секунды, а дальше персонаж сам оживает.
Это ломает весь стелс, когда можно подобрать нужный момент для воскрешения. То есть, появляется кнопка воскрешения буквально на три секунды, но после этого способность автоматически используется и персонаж сам собой встает.

### Воспроизведение
1. Берем генку
2. Умираем
3. Воскресаем через 3 секунды

### Ожидаемое поведение
Должна появиться кнопка revive на неопределенное количество времени, чтобы у игрока был выбор, в какой момент времени вернуться к жизни.

**Comment by ZerlGray** [comment]
Это не баг, а фича.
Буквально специально реализованная.
Ее нельзя убирать. Максимум - продлить время с 3-х секунд на больший срок. Ну или самому выставлять время.
Фича эта связана с особенностью работы вербов в сске вообще. Вербы не могут обновляться, если объект находится в каком то другом объекте.
В таком случае, если ты прожал стазис и тебя пихнули в сумку для трупов или морг, верб ревайв у тебя в принципе не появится и можно считать, что тебя на весь раунд вывели из игры.
Более того, это АКТИВНО абузилось людьми.

**Comment by Epicus7** [comment]
В таком случае надо было сделать верб "revive" невидимым.

Но вообще, мне кажется можно кнопку ревайва добавить, например, в интерфейс просто. Или еще как-то обойти не такими костыльними методами.

**Comment by dnivji** [comment]
До сих пор есть и работает через раз, явно баг, Дедфиля чот невнятное выдал.
