### ISSUE TITLE
Биохимический котел генокрада 

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#626]
### Описание бага
У генокрада странно ~не~ работает биохимический котел. Если быть точным, только единицам химикатов синтез и введение прописали правильно. Например, келотан НАОТРЕЗ отказывался вводиться в опасных дозах. Этиловый спирт и вовсе куда-то пропадал. Работала как надо только кислота и хлорка.

### Воспроизведение
1. Берем генку
2. Наполняем котелок химикатом
?????
PROFIT!

### Ожидаемое поведение
Химикаты должны синтезироваться и храниться в биохимическом котле генокрада, пока не будут каким либо образом использованы. Очевидно, они не должны сами собой исчезать.

**Comment by TobyThorne** [comment]
Биокотёл удалён, проблема разрешилась по пути наименьшего сопротивления.

**Comment by Epicus7** [comment]
@TobyThorne, а кто и где удалил биокотел? Нужен ПР, чтобы автору награду выдать.
