### ISSUE TITLE
Отвёртку нельзя положить в раздатчик инструментов

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#627]
### Описание бага
Отвёртку нельзя положить в раздатчик инструментов, если ты случайно её выкинул, ибо открывается панель обслуживания раздатчика. Хотелось бы сделать так, чтобы перетягиванием отвертку можно было затащить обратно в раздатчик.

**Comment by Auesti** [comment]
Протестил, всё работает
