### ISSUE TITLE
Nuclear emergency rebuild: map

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6270]
Необходимо добавить на базу к нюкерам добавить 4 пода с мануальным запуском каждого и случайным местом на астероиде.
Поместить шаттл нюкеров в ангар или как-то по другому заблокировать возможность выбраться с шаттла кроме задуманных для этого шлюзов находясь на базе нюкеров.

https://github.com/ChaoticOnyx/OnyxBay/wiki/Nuclear-emergency

**Comment by MrMagick2104** [comment]
По поводу подов, которые "отправляются в случайные локации на астероид":

Как нюкерам проникать на астероид (я так понимаю, речь идёт о шахтёрско-научном аутпосте), если он есть не на всех мапах, которые стоят сейчас на серверах?
Не выйдет ли смешное, что по каким-то причинам (например, из-за отсутствия доступа/емага, света, консоли шаттла) нюкеру придётся лететь с астероида на станцию на своих двоих полчаса, руиня весь режим?

Не лучше ли сделать один под, чтобы нюкерам не пришлось использовать метазнания для нахождения друг друга?
Не добавить ли пинпоинтер на аутпост, чтобы не пришлось ориентироваться по звёздам?

**Comment by NefrNerf** [comment]
Если потеряются, их проблемы. Проникать взломом, везде есть аванпосты и удаленные зоны.

**Comment by MrMagick2104** [comment]
> везде есть аванпосты и удаленные зоны.

Я про Фронтир. Там аванпостов нет вообще, есть только сама станция.

> Проникать взломом

Емнип, обычный нюкер не может пользоваться консолью шаттла, так как у него нет доступа. Получается, нюкерам либо нужен бесплатный емаг, либо бесплатный доступ.

**Comment by NefrNerf** [comment]
Хороший поинт про доступ, нужно дать к консолям

**Comment by NefrNerf** [comment]
А фронтир, будет кидать в ебеня, пускай летят к станции

**Comment by MrMagick2104** [comment]
> А фронтир, будет кидать в ебеня, пускай летят к станции

Насколько дальние? На станционный з-левел или другой?
Если другой - это не нужно, а если на тот же, то долететь 5 минут.

Про пинпоинтер и ориентирование на местности вопрос остался неотвеченным.

> доступ

Может быть, дать возможность стелсонюкерам выбрать профу из некоторого (возможно рандомного, но всегда с шахтёрами/ксеноархеологами, нельзя выбрать более одной на всю команду) пула доступов профессий цивилианов?
Штурмзолдатенам бы при этом вместо агентайдишника дать условный террорист айдишник, без возможности менять свой внешний вид и название профы.

**Comment by NefrNerf** [comment]
Профа - хуйня, воксы показали, хотите маскировку, маскируйте скафандры. Пинпоинтер на локу - слишком просто. З левел станции. А вот про штрумзолдатенов хороший поинт, что нельзя менять карту, ещё одие разграничитель.
