### ISSUE TITLE
Nuclear emergency rebuild: uplink

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6271]
Переработка аплинка нюкеров.

Необходимо сделать так, чтобы каждый оперативник нюки мог выбрать один из двух вариантов аплинка, с боевым оружием и скрытными инструментами. Так же необходимо выпилить с базы нюки оружие и добавить его в боевой вариант аплинка за 0тк.

В боевом варианте аплинк представляет собой урезанную версию, без возможности выбрать категорию скрытных и незаметных вещей.

В скрытном варианте аплинк также урезан, нет летального оружия кроме скрытного пистолета и инструментов для быстрого вскрытия (емаг, мультитул).

После проведения ядерным диском по аплинку который в режиме скрытного проникновения должна появляться возможность вызвать дроппод с бомбой в двух вариантах.
* Без оповещения в случайную точку станции
*  С оповещением в выбранную локацию

Ввести ограничение на вызов бомбы, если бомба с базы нюкеров не находится на базе.

https://github.com/ChaoticOnyx/OnyxBay/wiki/Nuclear-emergency

**Comment by NefrNerf** [comment]
Возможно стоит разбить это на несколько иссуев, то все касается аплинка

**Comment by MrMagick2104** [comment]
А нужно ли это вообще?

В текущем иссуе есть некоторые непонятные моменты.

Корабль. Как вариант аплинка должен коррелировать с оповещением о прилёте? Должен ли корабль быть вообще доступен стелсонюке, либо только поды?


> Необходимо сделать так, чтобы каждый оперативник нюки мог выбрать один из двух вариантов аплинка, с боевым оружием и скрытными инструментами.

Как поступать, если один нюкер выберет стелс-аплинк, другой - боевой аплинк, в итоге нюкеры будут как сейчас закупаться (с небольшими дополнительными затратами ТК) полным аплинком?

<hr>

Имхо, надо всем нюкерам добавить хотя бы по бесплатному холдаут пистолету (ака Стечкину) без глушителя для самообороны от диких ассистентов, ибо безоружные нюкеры - что-то смешное.
Либо давать всем стелсонюкерам пистолеты с глушителем бесплатно.

**Comment by NefrNerf** [comment]
Это нужно, у игроков есть запрос на стелс, его нужно реализовать и оставить только продуманную возможность, а не выламывание окна. Каждый выбирает себе свой тип, консоль пода можно активировать только при помощи скрытного аплинка например 2 человека в стелс, пытаются захватить скрытно, проваливаются и прилетает поддержка.

**Comment by MrMagick2104** [comment]
> Это нужно, у игроков есть запрос на стелс, его нужно реализовать и оставить только продуманную возможность

Я к тому, нужно ли разделение аплинков. Мне кажется, запрос на стелс можно и без этого реализовать.

> Каждый выбирает себе свой тип, консоль пода можно активировать только при помощи скрытного аплинка например 2 человека в стелс, пытаются захватить скрытно, проваливаются и прилетает поддержка.

Если условные 2 человека летят в стелс, а остальные ждут команды, то тогда остальным что делать? Сидеть, в пасьянс играть? Единственное что они могут - смотреть по камерам консоли, что не слишком-то интересно. Имхо, нужен командный выбор - либо все в стелс, либо все в войнушку, чтобы никто не ушёл обиженным.

Если давать разделение, то я не представляю, как можно предотвратить вот эту проблему, названную выше:
> Как поступать, если один нюкер выберет стелс-аплинк, другой - боевой аплинк, в итоге нюкеры будут как сейчас закупаться (с небольшими дополнительными затратами ТК) полным аплинком?

**Comment by MrMagick2104** [comment]
Кроме того, хорошо было бы оставить некий "класс-универсал" с полным аплинком, меньшим ТК, худшим бесплатным оружием, чем у боевых нюкеров.

Банально потому что некоторые вещи из стелс-набора (емнип), например, емаг, жизненно необходимы нюкерам, иначе они убьются об первого встреченного ИИ.

Не все вещи во вкладке стелс айтемс по-настоящему нужны исключительно для стелса. Емаг, термалы - тому примеры.

**Comment by NefrNerf** [comment]
Емаг и термалы можно добавить в боевой, а куда универсала девать?
