### ISSUE TITLE
Биоструктура генокрада бессмертна пока находится в теле

### ISSUE THREAD

**Issue by Oubifx** [ChaoticOnyx/OnyxBay#6277]
### Описание бага
Биоструктура генокрада не умирает от прямых повреждений находясь в теле (дев ветка).
Иссуй создан для автора иссуя.

### Воспроизведение
<details>
<summary>Шаги чтобы воспроизвести баг:</summary>
ДЕВ ветка

![image](https://user-images.githubusercontent.com/24242919/127867435-ff87a467-2153-4ea0-9b13-678a904ec8b8.png)

</details>

### Ожидаемое поведение
Орган умер > генокрад умер > возможность прожать стазис пропала
### Скриншоты
Есть выше

**Comment by TobyThorne** [comment]
Исправлено во время переписывания генокрада.
![image](https://user-images.githubusercontent.com/45202681/145917671-a7851516-efbe-4e20-8aa3-43964283e65b.png)
