### ISSUE TITLE
Waist pack замещает ПДА

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#628]
### Описание бага
Вейстпак встаёт на пояс, где должен быть ПДА. В итоге ПДА удаляется.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Выбираем в лоадауте waist pack
2. Спавнимся без ПДА

**Comment by Epicus7** [comment]
Хз что такое вейст пак, но ПДА в таком случае надо класть в рюкзак. Или этот вейст пак.

**Comment by Epicus7** [comment]
@TermService, а что с этим багом? Его пофиксили? Или не получилось воспроизвести?

**Comment by TermService** [comment]
Fixed  #1115
