### ISSUE TITLE
Спрайты аптечек

### ISSUE THREAD

**Issue by kreeperHLC** [ChaoticOnyx/OnyxBay#6289]
### Улучшение
Переспрайтить аптечки, либо вернуть старые спрайты.

**Comment by DarkHunter7756** [comment]
А можно приложить старые спрайты для тех, кто в танке?

**Comment by TobyThorne** [comment]
ин процесс 
![image](https://user-images.githubusercontent.com/45202681/128431708-0affc68f-b647-499b-a492-9a96dadaf508.png)
![image](https://user-images.githubusercontent.com/45202681/128431727-091da900-200a-4e11-8f94-54c3ee197a18.png)
