### ISSUE TITLE
Борг может ползать и болтировать двери будучи мертвым

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#629]
### Описание бага
Будучи мертвым боргом можно болтировать двери и передвигаться ползком.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем борга
2. Умираем
3. Открываем в себе второе дыхание и волю к жизни. Ползаем.
4. Смерть не остановит вас. Даже после рокового часа вы можете управлять дверьми.

**Comment by Shverboot** [comment]
Так же в эту тему. Севший аккумулятор. Я наверное час маячил освещением, блокировал двери, и так далее инженерам что бы они догнали меня зарядить. Жаль компьютера не было. Я бы еще и распечатал им сообщение.

**Comment by TobyThorne** [comment]
Уже неактуально.
