### ISSUE TITLE
Улучшить сообщение жертве вампира, опять

### ISSUE THREAD

**Issue by No-Tips** [ChaoticOnyx/OnyxBay#6290]
Девять новых игроков из десяти, которых впервые кусают вампир, как-то коряво читают сообщение, что отображается, и идут всем рассказывать о том, что Фред Коллон кусается в техах. Проблема - стена текста, где важно лишь одно предложение. Нужно сократить, оставив лишь самое важное - ты НИЧЕГО не помнишь про укус, выделив слово nothing жирненьким, желательно.
![изображение](https://user-images.githubusercontent.com/75416333/128253749-f73c5c54-5171-4650-8df6-eae7610bf958.png)

**Comment by MrMagick2104** [comment]
Лучше бы сделать окошко с предупреждением, как от потери памяти.
