### ISSUE TITLE
Реверт / редизайн UI консоли исследований

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#6307]
Когда я впервые услышал об обновлении всех интерфейсов на TGUI - я был рад, ибо они выглядели свежее ( вспомним тот же психоскоп и консоль, которая шла с ним в комплекте ). Те UI хоть и не сильно отходили от оригинального стиля игры, выглядели сочнее и интереснее. И вот выходит спорное обновление UI автолата, UI фабрикатора, UI вендоматов. В UI появились иконки, что выглядело не во всех случаях красиво ( автолат & фабрикатор ). После чего перед нашим взором предстает UI консоли исследований. Далее я опишу проблемы и соберу подборку багов, после чего озвучу свое предложение.

[Фантомные предметы](https://github.com/ChaoticOnyx/OnyxBay/issues/6276) - часть предметов невозможно по какой то причине найти без поиска.
Контракты на кражу чертежей мехов / компонентов роботов - после обновления невозможно украсть что-то, что находится вне меню протолата, часть контрактов невозможно выполнить.
Провисания UI - как бы не старался автор исправить консоль, она все равно на максимальных технологиях вызывает тормоза.

Перечислю основные проблемы нового UI:
1. Неудобная форма окна - UI перекрывает практически все окно с игрой, приходится жертвовать либо вьюпортом, либо чатом.
2. Множество бесполезной информации на экране, малая полезная область меню. Иконки ресурсов, которые не очень красиво смотрятся и кажутся лишними.
![IerH0eA0zS](https://user-images.githubusercontent.com/47484306/128652927-41caad3e-cbf6-4acd-ac17-45aa3bb84c45.png)
3. Постоянно требуется производить синхронизацию, хотя деконструкция происходила на стоящем рядом аппарате. 
![l4DNA4SJXT](https://user-images.githubusercontent.com/47484306/128652953-d183c088-8585-46a7-951d-648e890db244.png)
4. В видео есть момент, где одна из вкладок не прогружается, ибо записывающий является призраком. К сожалению, такой баг случается и во время работы обычного игрока с протолатом.
5. По какой-то неизвестной причине кнопка раздробилась, чего быть не должно, если судить по оригинальному проекту.
![image](https://user-images.githubusercontent.com/47484306/132595448-8ad54aeb-b687-4e0a-b9e5-eac4f9fd1ef7.png)
![image](https://user-images.githubusercontent.com/47484306/132595468-a0058c1a-232b-4d76-ab7e-961a68511a8f.png)

https://www.youtube.com/watch?v=hQwIFNTObH4

Хочу лишь сказать, что я не единственный, кому не нравится данное изменение. Старый UI пользовался и пользуется популярностью у игроков РнД по одной простой причине: простота использования. Раньше исследования происходили быстрее, оставляя игрокам больше времени на взаимодействие друг с другом, теперь изучение происходит в два раза дольше.

Я предлагаю немного переделать UI, вынеся бесполезную информацию АКА очередь и загруженные ресурсы в отдельное окно / скрыв. Вторым вариантом предлагается откат на старую версию и пересмотр того дизайна, что имеется на данный момент.

**Comment by kcalbCube** [comment]
не нужно.

**Comment by O0oMaximo0O** [comment]
Нужно. Даёшь совместимость.

**Comment by kcalbCube** [comment]
к хорошему долго привыкать надо, месяцок подождите.

**Comment by intercepti0n** [comment]
Я из будущего закрываю иссуй себя из прошлого так как это ЕБАНЫЙ СТЫД.
