### ISSUE TITLE
Пустая еда

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#631]
### Описание бага
ССка насмехается над космонавтиками даже когда они просто хотят поесть. В ланчбоксах, да и вне их, попадаются "пустые" куски пиццы или хлеба, пончики и т.п.
Если попытаться её сожрать, в ответ придет сообщение _No more %foodname% left_ (без характерного хрустящего звука поглощения еды)

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем рандомную еду с карты (например, чаще всего это встречается в музее на ЦК)
2. Едим
?????
PROFIT!

**Comment by Firefroge** [comment]
в гетто/техах пустая еда - фича.

**Comment by Epicus7** [comment]
Удалили уже такую еду с карты. ПР не нашел, увы.
