### ISSUE TITLE
Пропадающие сообщения

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#632]
### Описание бага
Иногда бывает такое, что когда ты отправляешь сообщение, оно просто не показывается в чатике. Появляется облако (вопрос, восклицание, многоточие), но в чатике ничего нет.
Причём все остальные твоё сообщение видят.
Был подобный случай, когда общение было в ахелпе. Адресат услышал звук сообщения, но не увидел текста. Поэтому пришлось по-новому отправлять сообщение, и уже на этот раз получатель его увидел.

### Воспроизведение
Шаги чтобы воспроизвести баг (нет четкого понимания, как воспроизвести):
1. Берем космонавтика
2. Шлем ему сообщения
?????
PROFIT???

**Comment by kreeperHLC** [comment]
С Гуночатом могло пропасть, нужно как-то проверить.

**Comment by Epicus7** [comment]
Такие приколы репортили и год назад. Бывает такое, что сообщение тупо пропадает только у одного игрока, очень старый прикол.

Надо поискать похожие проблемы в иссуях других билдов, там точно должно быть что-то похожее.

**Comment by HonkyDonky** [comment]
>Требуется проверка.
Откройте заново если актуально.
