### ISSUE TITLE
Сторителлер спавнит трейторов из гостов в пределах видимости других персонажей

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#6333]
### Описание бага
Сторителлер спавнит трейторов из гостов в пределах видимости других персонажей. Буквально вчера на фронтире именно это и произошло, сижу в баре, прямо на мне появляется голый мужик с аплинком в руке и улепётывает.

### Ожидаемое поведение
Антаги не должны спавниться рядом с неспящими мобами, за которых играет игрок

### (Опционально) Дополнительная информация
ID игры не помню, было вчера на эосе примерно в 23:30 наверное

**Comment by Doster-d** [comment]
Мужик появился потому что следил за тобой.
