### ISSUE TITLE
Игрок спавнится полностью невидимым

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#635]
### Описание бага
Бывает, что игрок спавнится полностью невидимым. Кажется, это связанно со слотами или вроде того. Его не видно на тайле через альт-клик, альфа сбрасывается, как у призрака.

### Воспроизведение
Берём слот выпиленной на Опухе расы с Блюбея и заходим им в игру.
fix_body_build() позволяет вывести пострадавшего из этого состояния.

**Comment by kreeperHLC** [comment]
Проблема в старых сохранённых слотах с Блюбея(?). Возможное решение - либо прописать фикс тела при появлении на станции, либо как-то отлавливать такие слоты.

**Comment by igorsaux** [comment]
Слишком старое🕸️
