### ISSUE TITLE
Тайлы под проводкой бесконечные

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#636]
### Описание бага
Тайлы под проводкой бесконечные. Их можно снимать сколько угодно раз. Т.е. можно создать бесконечное число плиточек пола, которые можно кидать в бесконечное количество людей и получить бесконечное число банов.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем лом
2. Отрываем тайл из под проводки
3. Отрываем тайл из под проводки
4. Отрываем тайл из под проводки
5. Отрываем тайл из под проводки
6. Отрываем тайл из под проводки
7. Отрываем тайл из под проводки
8. Отрываем тайл из под проводки
...

**Comment by Animesku** [comment]
А разве так не с любым укрепленным полом?
