### ISSUE TITLE
Shitton of wizard bugs

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6373]
Охуительных масштабов подборка багов у визарда, цензурных выражений нет, почти 6 лет это было в нашем билде и никто не заметил подвоха.

Баги завязанные на уменьшении кулдана. У багов из списка ниже максимальное количество улучшения параметра Speed, который отвечает за улучшение перезарядки не совпадает с реальным уменьшением с уровнем или данный параметр вообще отсутствует или разработчик настолько ебанулся, что сделал кулдаун скилла равным 0.

1. Magic missle имеет минимальный кулдан на уровне 2 , при максимальном уровне 3
2. Mirage имеет минимальный кулдан на уровне 2 , при максимальном уровне 3
3. Summon bats имеет минимальный кулдан на уровне 2 , при максимальном уровне 3
4. Summon bear не имеет уменьшения кулдауна вовсе, при базов кулдауне в 5 минут, сука
5. Summon hound, при максимальном уровне не имеет кулдауна вовсе. Эту ебалу можно заспавнить и нахуй положить сервер как и засрать любое помещение до ситуации инстагиба любого врага
6. Corrupt form имеет минимальный кулдан на уровне 1 , при максимальном уровне 2
7. Mind control имеет меньший кулдаун чем продолжительность каста.
8. knock имеет уменьшение кулдауна, которое не соответствует заявленным числам (смотри класс скилла)
9. force wall имеет минимальный кулдан на уровне 2 или 3 , при максимальном уровне 4(я уже не помню где точно, перепроверьте это дерьмо)
10. radiant aura имеет кулдаун меньший чем максимальная продолжительность скилла, сделайте равной.
11. etheral jaunt имеет минимальный кулдан на уровне 2 или 3 , при максимальном уровне 4(я уже не помню где точно, перепроверьте это дерьмо)
12. mark and recall имеет минимальный кулдан на уровне 2, сука , при максимальном уровне 4
13. noclothes можно ускорить, но у скилла нет КД
14. Blink имеет минимальный кулдан на уровне 3, при максимальном уровне 4

Желательно перепроверить все скиллы которые не были указаны тут, так как у них тоже могут быть баги с кулдаунами.
Эта хуйня жрала очки скиллов у игроков на протяжении ахуенного количества времени и никто даже об этом не сообщал.

**Comment by Zert0X** [comment]
Билд играбелен, но решить надо быстро
![изображение](https://user-images.githubusercontent.com/42303535/129921707-09141626-75eb-43fa-879c-2b3e30347276.png)
