### ISSUE TITLE
Маг может бросать фаербол из джанунта

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6375]
### Описание бага
Маг может уйти в джаунт и бросить фаербол из джаунта, так быть не должно.

### Ожидаемое поведение
Маг не должен иметь возможность бросать фаербол из джаунта.

![image](https://user-images.githubusercontent.com/85663436/130040934-8542cdc5-1709-425d-b226-7284807dd64f.png)

**Comment by kcalbSphere** [comment]
почему баг, почему боевка, почему убрана 'требуется проверка'

**Comment by NefrNerf** [comment]
![image](https://user-images.githubusercontent.com/85663436/130041569-d0724075-365f-417d-8807-81e7fadacb3b.png)

**Comment by PlinHost** [comment]
> почему баг, почему боевка, почему убрана 'требуется проверка'

![член](https://user-images.githubusercontent.com/8840325/130041587-f4afffae-9625-408d-a940-d997d01a2707.png)

**Comment by kcalbSphere** [comment]
с 'требуется проверка' и 'баг' порешали. почему бовка?

**Comment by kcalbSphere** [comment]
> > почему баг, почему боевка, почему убрана 'требуется проверка'
> 
> ![член](https://user-images.githubusercontent.com/8840325/130041587-f4afffae-9625-408d-a940-d997d01a2707.png)

проржал.

**Comment by NefrNerf** [comment]
Ничего лучшего чем "боёвка" не придумал, по хорошему вывести боевку, стрельбу и спеллы в разные категории.

**Comment by hard-res3t** [comment]
Куб, прочитай ватчерскую инструкцию. Там написано почему 'требуется проверка' убрали

**Comment by kcalbSphere** [comment]
нужно конвертировать в фичу "запретить магу кастовать пока он в джаунте"

**Comment by NefrNerf** [comment]
Закрываю по причине #6377
