### ISSUE TITLE
люди в боди сканнере не так процессятся

### ISSUE THREAD

**Issue by kcalbCube** [ChaoticOnyx/OnyxBay#6385]

**Comment by Oubifx** [comment]
??????

**Comment by kcalbSphere** [comment]
я это и раньше замечал, но тогда забил. сейчас же, когда тестировал инфекции понял это ещё раз. в космонавтике медицина притормаживается в той или иной степени. по сути это крио на минималках.

**Comment by kcalbSphere** [comment]
или на максималках?
