### ISSUE TITLE
economics: vending departaments

### ISSUE THREAD

**Issue by kcalbCube** [ChaoticOnyx/OnyxBay#6399]
Сейчас у всех вендоров один счёт. Улучшение заключается в создании отдельных счетов для каждого департамента. 
На игровой процесс это не повлияет, но это можно будет использовать в будущем.

**Comment by MaxFreemen** [comment]
Куб, у меня вопрос. Про какие отделы идет речь? Автоматы с едой кому профит приносят?

**Comment by kcalbSphere** [comment]
> Куб, у меня вопрос. Про какие отделы идет речь? Автоматы с едой кому профит приносят?

автоматы с едой это департамент цивилианов.
а отдел это в основном медбей конечно.

**Comment by MaxFreemen** [comment]
> > Куб, у меня вопрос. Про какие отделы идет речь? Автоматы с едой кому профит приносят?
> 
> автоматы с едой это департамент цивилианов.
> а отдел это в основном медбей конечно.

А, неплохо. У нас на вики есть стаейка про сервера с деньгами отделов, вроде. Возрождаем фичи с анимуса?

**Comment by kcalbSphere** [comment]
про сервера как-то странно, просто счета добавить и раздать главам номер и пинкод, и весь список куда-нибудь в хранилище.

**Comment by MrMagick2104** [comment]
Счета отделов уже есть, если что.
Главам в нотесы раундстартом пинкод и пароль пишет.

**Comment by Zert0X** [comment]
> Счета отделов уже есть, если что.
> Главам в нотесы раундстартом пинкод и пароль пишет.

Разве пишет?

**Comment by MrMagick2104** [comment]
> Разве пишет?

Ласт тайм ай чекд писало.
Счета отделов всё равно есть, в крайнем случае можно подойти к ХоПу и узнать данные.

**Comment by Zert0X** [comment]
Прост у нас точно помню был иссуй, и я не помню чтобы его закрывали

**Comment by kcalbSphere** [comment]
> > Разве пишет?
> 
> Ласт тайм ай чекд писало.
> Счета отделов всё равно есть, в крайнем случае можно подойти к ХоПу и узнать данные.

а у хопа откуда

**Comment by MrMagick2104** [comment]
Из консоли со всеми аккаунтами, ну.

**Comment by Artemonim** [comment]
Оно уже так работает

**Comment by Tsurupeta** [comment]
Вообще-то не работает. Только тсс.

**Comment by Artemonim** [comment]
Счета департаментов есть. Я ХОПом их видел -_-

**Comment by Tsurupeta** [comment]
Но предложение адресовано на вендоры. В любом случае, оно не имеет смысла.
