### ISSUE TITLE
Система механа эмоций основаная на химикатах

### ISSUE THREAD

**Issue by LagannPM** [ChaoticOnyx/OnyxBay#64]
![default](https://qph.fs.quoracdn.net/main-qimg-749740b0c56debb903cdf42f948879f6)
При обработки веществ в крови происходит какие либо реакции
Можно сверху прикрутить психологические расстройства которые изменяют химикаты
Вещества не будет видно в обычном сканере но будет видно в спектрометре

**Comment by Ruforce** [comment]
чего блядь

**Comment by Ruforce** [comment]
билингв, ты совсем ебобо что ли?

**Comment by fluorescent-net** [comment]
забыл таблеточки от биполярочки принять

**Comment by ZerlGray** [comment]
Сначала мне это показалось странной идеей, но потом я увидел "Аутизм" и понял - это то, что нужно опуху.

**Comment by ZerlGray** [comment]
А вообще - прикрути к этому норм механ - и будет забавная система, которая чутка реанимирует психиатрию. Но по моему - ето сложно.

**Comment by Epicus7** [comment]
Слишком сложная система получится, относительно других механик. Я думаю не стоит настолько неравномерно углублять сложность механики в одних местах, когда в других у нас тупо ничего не работает. Это раз.

Два, идея очень слабо проработана. Нет, она вообще не проработана. Кинуть пикчу с кучей веществ и эмоциями - этого недостаточно, чтобы все поняли чего ты хочешь. Нужно прописывать конкретную механику для КАЖДОГО вещества и КАЖДОЙ эмоции. Прописывать о каких расстройствах ты КОНКРЕТНО говоришь, как они будут влиять на игру.

**Comment by LagannPM** [comment]
@Epicus7 Я пока что просто делаю вброс чтобы узнать ваше мнение.
Если идею сразу забракуют то мне нет смысла ее развивать.
И пикча скинута чтобы в общем понять картину, и идея настолько сложной не будет мб максимум 5-6 основных химикатов и их смеси

**Comment by Cinericius** [comment]
Сложно, сервер нагружать нет смысла такой системой.
А эмоции по-хорошему должны отыгрывать сами игроки. Максимум, что можно сделать - систему потребностей, которая частично (в виде голода, например) уже и так реализована. И к ней прикрутить какие-то штрафы и оповещалки для игрока, что ему чего-то там не хватает или наоборот всего много и заебись. Примерно так это, кстати, работает на Луфе. 
Но, мне кажется, если это и делать, то не сейчас, сейчас оно не очень приоритетно.

**Comment by LagannPM** [comment]
Это больше система не эмоций а чувств.
Типо страха, стресса эфории.
На эти статусы можно навешать механ. Скажем если ты боишься то шанс промазать. Или если стресс можно добавлять псих растройства.
И нагружать это сильно не должно

**Comment by Ruforce** [comment]
не стоит

**Comment by Cinericius** [comment]
Блин, это все отыгрываться должно по-хорошему. Все-таки у нас ролевая игра, а не текстовое интерактивное кино.
