### ISSUE TITLE
Порт способностей вампиров

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6404]
### Улучшение
Сейчас вампиры конечно играются как средние антагонисты, но им явно не хватает способностей, необходимо добавить им разнообразия и больше возможностей для боя
### Решение
Перенести еще способностей вот отсюда https://wiki.ss13.co/Vampire
### (Опционально) Альтернативы
Да нет альтернатив, везде вампиры одинаковые, ТГ вампиры нам не пойдут, а вот доделать наш обрубок можно.

**Comment by Zert0X** [comment]
И что ты хочешь чтобы мы портанули, Гроб вместо Вейл степа?

**Comment by NefrNerf** [comment]
Гроб хочу, андед фишки, связи с треллами и больше способностей

**Comment by Zert0X** [comment]
Имхо Гроб - имба, для побега есть веил степ
Связь с треллами - гуд
Больше способностей? Ну остался только Cancel stuns - отмена станов с нанесение брута, за каждую секунду стана

**Comment by NefrNerf** [comment]
Предлагаю сделать возможность вампирам после их убийства вернуться в гроб и чтобы убить вампира можно было лишь разрушив гроб.

**Comment by NefrNerf** [comment]
Вейл степ заменить на превращение в летучую мышь, как там и написано.

**Comment by Zert0X** [comment]
Такс жду одобрения от овнеров и прописанного, что конкретно портировать и что на что заменить

**Comment by NefrNerf** [comment]
1. Заменить Veil step на Bat form
2. Добавить Speak to Thralls
3. Добавить механику гроба

Механика гроба: аналогична описанной в вики, с отличием в том, что вампир возвращается в гроб после смерти и восстанавливается там в течении какого-то времени (числовые значение по решению исполнителя). Полноценное убийство вампира возможно только с уничтожением гроба.
