### ISSUE TITLE
Обновление химии.

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6406]
### Улучшение
Добавить различные варианты исхода смешивания реагентов.

### Решение
Как это происходит сейчас? Сейчас у нас есть жесткие соотношения, например 2 к 1 и только в таком случае получается препарат. Почему бы не сделать эту систему 4 этапной?
1. Базовый компонент(определяет назначение препарата)
2. Второй компонент (определяет эффект, который будет происходить при введении в человека)
3. Третий компонент (определяет дополнительный эффект)
4. Модификатор (определяет тип введения лекарства)

**Базовый компонент**, можно из старых что-то можно из новых сделать, определяет что ты сделать хочешь : лечить или калечить
**Второй компонент**, это тип урона который он лечит или наносит и какой объем
**Третий компонент**, дополнительный эффект (сонливость, ускорение метаболизма итд.)
От третьго компонента будут зависимы характеристики первого, подмешал карпотоксин в подобие бикардина, получи усиленный эффект на протяжение большего времени, но урон по мозгу и немоту.
**Модфификатор**, тут уже придется вводить новые рецепты, модификатор определяет какие бонусы будут при введении лекарства предназначенным для него путем.

Это только набросок, больше взаимодействий приветствуются и вообще, нужны идеи

**Comment by NefrNerf** [comment]
Тут основная проблема в том, что у нас при изготовлении препаратов нет случайности, нет элемента рандома и возможности модификации, температура ничем полезным не будет, так она добавит кроме соотношения всего еще один параметр. А возможность создать свое лекарство с особыми параметрами как одну субстанцию. 

Ну слушай, как она может быть не завязана на уроне или хиле? У нас все идет через урон или хил чего-то, урон по органам, урон по крови. Лекарства просто уменьшают эти значения. И если это было бы не важно, то тогда бы никто не варил целый склад раундстартом.

**Comment by MrMagick2104** [comment]
> У нас все идет через урон или хил чего-то, урон по органам, урон по крови.

Очень много медикаментов не оперируют именно уроном, о котором ты, как я понимаю, говоришь, например:
-гиперизин
-обезболивающее (хотя это можно притянуть как лечение болевого урона, но всё же, стоит упоминания)
-снотворное
-все антидепрессанты
-взрывчатки-напалмы-ионки
-убиратели волос, останавливатели сердца, нейротоксины и прочие паралитики
-все рецепты с изготовлением материалов, в т.ч. краски и синтмясо
-спейс люб, клинер, кулант, стерилизин, люминол и вода.
Я не понимаю, как должны существовать реагенты выше в реалиях предложенного, если речь об измении химии в корне (так, чтобы вообще *все* реагенты варились подобным образом).

> нет случайности
> параметры

Имхо, лучше иметь много зависимых или независимых параметров, которые делают (своим количеством и взаимосвязанностью) какую-либо реакцию непредсказуемой, но нерандомной.

**Comment by NefrNerf** [comment]
Ну тогда просто стоит добавить больше основ для медикаментов, не 2 основы будут а 4 или больше, в зависимости от применения лекарств
