### ISSUE TITLE
Перерисовать спрайт галстука

### ISSUE THREAD

**Issue by Megmeehey** [ChaoticOnyx/OnyxBay#642]
### Улучшение
Посмотрите на это
![изображение](https://user-images.githubusercontent.com/2480466/61667407-93934780-ace2-11e9-80a5-b9413d17fde9.png)

### Решение
Нужно взять и решительно перерисовать спрайт галстука на полу. Это месиво из пикселей заставляет страдать каждого, кто еще не успел вырвать себе глаза.

### Альтернативы
Никаких. При одном взгляде на это, хочется задушить этим галстуком создателя и начать галстучную революцию.

### (Опционально) Дополнительная информация
Приоритет данной задачи где-то на уровне оверлеев котоушек. И шарфиков.

**Comment by Penguineapig** [comment]
Я даже болльше скажу. Чёрный галстук из лоадаута на самом деле говняно-серый. Дада, СЕРО_БЕЛЫЙ галстук цвета рубашки. И спрайт, и одетый спрайт
