### ISSUE TITLE
Переработка протезов: параметры защиты

### ISSUE THREAD

**Issue by MaxTheAstronaut** [ChaoticOnyx/OnyxBay#6422]
**Улучшение**
На данный момент все протезы в игре лишь косметика, которая никак не влияет на игровой процесс. Предлагается добавить им параметры защиты ко всем типам урона.

**Решение**
К примеру, у нас есть два протеза: первый военный, который ставится работникам СБ, дабы те не падали от первого ЕМП импульса, а второй сделан в гетто из стали, дерева и проводков. На данный момент отличий нет, я предлагаю поставить протезам параметры защиты, при этом сбалансировав их, используя [ограничения на профессии](https://github.com/ChaoticOnyx/OnyxBay/issues/6418) и на [качество протезов](https://github.com/ChaoticOnyx/OnyxBay/issues/6423). Какие-то протезы будут выдерживать три-четыре импульса из ионной пушки, другие будет сложнее помять или прострелить. За основу предлагается взять параметры, что используются у одежды и перенести на протезы.

**Comment by DarkHunter7756** [comment]
Неиронично, но даже я бы выбрал идею убрать из сетапа многие протезы (по крайней мере не добавлять новые с плюшками) и ввести остальным бОльшее преимущество уже в игре

Разумеется - больше преимуществ - выше цена. Ни "качество", ни ограничения проф не будут хорошими идеями. 

Оставить в сетапе имбовые протезы - сломать и так сломанный баланс.

**Comment by MaxFreemen** [comment]
>В решении, которое ты представляешь, смысла идти к робототехнику нет, ведь у тебя СБ раундстартом получают суперпротезы с защитой, если утрировать.
Ну, как бы сказать, я пляшу вот от [этого проекта](https://github.com/ChaoticOnyx/OnyxBay/pull/6087). В нем добавлены диски с чертежами от разных корпораций, которые можно либо купить, либо откопать, часть протезов недоступна в лодауте. Убермощных протезов раундстртом не будет.

>Если же ты просто добавишь защиту от ЭМИ, то тогда у тебя умрёт баланс и протезы станут метой.
Я не хочу сделать протезы неуязвимыми к ЭМИ, но сам факт, что протез по прочности как рука меня смущает. Предлагается добавить параметры защиты как у одежды, при этом сбалансировав ее дебафами на скорость и качеством конечности.

>Больше бы проблем решилось, если бы робототехник мог ставить протезы, которые бы давали реальные преимущества. Например, как работают имплантаты на ТГ-бистейшене, с армблейдами, всякими визорами, а также нанитами, которые могут регенерировать протезы самостоятельно.
Это не протезы, а аугментика, над диздоком по ней я работаю, первые шаги к ее добавлению сделаны в [этом проекте](https://github.com/ChaoticOnyx/OnyxBay/pull/6087).

>Почему косметика должна влиять на игровой процесс?
Кстати, протезы уже не являются косметикой, ибо влияют на игровой процесс. Ты должен их чинить, они гибаются, в них нельзя воткнуть иглу.

В общем, я все клоню к тому, что данная механика будет нова, ибо не встречается в других билдах, привлечет людей к отделу робототехники. Да, можно оставить протезы как есть, пусть они будут однообразными скинами, но я придерживаюсь иной точки зрения на проблему.

**Comment by MrMagick2104** [comment]
> Убермощных протезов раундстртом не будет.

Все раундстартовые протезы должны быть равными. Иначе игроки будут жаловаться на то, что не могут брать предметы по причинам отыгрыша, а потом другие будут выть, когда разницу, неизбежно, спилят, как было с лоадаутом.

> Предлагается добавить параметры защиты как у одежды, при этом сбалансировав ее дебафами на скорость и качеством конечности.

А зачем? Эти изменения, как мне кажется, слишком поверхностны, не добавляют особой глубины геймплю, однако могут приводить к проблемам с балансом. Как мне кажется, если ты хочешь протезы лучше - ставь бронеплиту у робототехника какую-нибудь, которая уже будет иметь эффекты.
Бейзлайн протезы - просто протезы, не лучше и не хуже обычных конечностей в целом, они должны иметь одинаковые характеристики изначально, имхо.

> Кстати, протезы уже не являются косметикой, ибо влияют на игровой процесс. Ты должен их чинить, они гибаются, в них нельзя воткнуть иглу.

Я не про это, а про то, что протезам следует быть равными. Раньше же у нас были только анбрандед протезы в билде, потом добавились рескины, емнип. Относительно обычных протезов, все остальные - просто косметика.

> привлечет людей к отделу робототехники.

Непонятный тейк. Робототехника, в основном, отдел для новичков, потому как имеет довольно простые и понятные обязанности, начинающие игроки очень часто туда сливаются, по очевидным причинам. Как мне кажется, никого туда и не нужно привлекать?
А если ты говоришь про желание посещать робототехника, то, как мне кажется, протезы-аугменты были бы в *разы* интереснее и полезнее с точки зрения обычных игроков.

**Comment by MaxTheAstronaut** [comment]
Ясно, продолжаем. Начну тогда с самой забавной части твоего ответа, @MrMagick2104 .
>Непонятный тейк. Робототехника, в основном, отдел для новичков, потому как имеет довольно простые и понятные обязанности, начинающие игроки очень часто туда сливаются, по очевидным причинам. Как мне кажется, никого туда и не нужно привлекать?
>
Чтоб ты понимал, мне не особо важно, кто на Хаотике играет за робототехников и привлечение их внимания меня не волнует. К примеру, на ЕОСе достаточно хороших людей, которые выбираютют эту роль, и призывать их поиграть не требуется.
Моя цель - привлечение людей в отдел, дабы те давали работу робототехнику, да, странно звучит. Я наиграл на этой роли достаточно и могу смело заявить, что попадание человека в этот отдел приводит к выходу из игры в большинстве случаев, ибо превращение в статную бочку не всем нравится. Если офицер СБ теряет руку то тому пришивают простенький протез в медбее, после чего тот убегает крошить воксов или ещё кого.
К чему же я клоню? А к тому, что у протезов нет качественных отличий между собой, а тратить время на установку скина люди не всегда готовы. Да, мой проект, что сейчас висит на ГитХабе решит проблему стальной бочки, но не отменит того факта, что офицерики не будут забегать за протезами к робототехнику. И я скажу больше: протез практически не отличается от руки человека, его можно нашинковать катаной, можно разломать ломом, его можно изрешетить парой выстрелов. Именно поэтому посмотрим вот на этот отрывок твоего комментария:
>Бейзлайн протезы - просто протезы, не лучше и не хуже обычных конечностей в целом, они должны иметь одинаковые характеристики изначально, имхо.
>

>А если ты говоришь про желание посещать робототехника, то, как мне кажется, протезы-аугменты были бы в разы интереснее и полезнее с точки зрения обычных игроков.
>
Протез не имеет никаких качественных отличий от руки, поэтому люди будут ставить бронепластину под кожу, ибо они не хотят, чтоб их рука отлетал от первого импульса. Если же мы их ограничим, то они не будут ставить ее в принципе, ибо лишняя волокита им не нужна. И ещё стоит добавить, что добавление в билд аугментов будет проблематично из-за пяткобоевки и геймдизвйнеров, которые прекрасно понимают эту проблему.
В общем, я все клонил к тому, что я пытаюсь потихоньку превратить протезы из рескина конечности, в металлическую палку с бафами и дебафами, которые можно будет использовать по ситуации. В общем, пытаюсь сделать протезы протезами, как в ролевой игре Cyberpunk 2020.

**Comment by MaxTheAstronaut** [comment]
> Неиронично, но даже я бы выбрал идею убрать из сетапа многие протезы (по крайней мере не добавлять новые с плюшками) и ввести остальным бОльшее преимущество уже в игре
> 

@DarkHunter7756 , хорошо. Что ты подразумеваешь под "более имбовыми протезами"? Поддерживаешь ли ты саму идею со статами защиты для протезов или готов предложить что-то иное?
