### ISSUE TITLE
Перевести спелы на level-based систему

### ISSUE THREAD

**Issue by igorsaux** [ChaoticOnyx/OnyxBay#6431]
Что у нас сейчас - кринже система с абстрактными empower и quicken и вшитыми формулами по которым изменяются атрибуты спелов.
Что надо сделать - возможность задать список атрибутов с определенным значением для каждого спела на каждом его уровне:
```dm
    attributes = list(
        // ключ атрибута | лист уровней атрибута (индекс - номер уровня спела, значение - значение атрибута)
        list("cooldown", list(10, 8, 8, 5)),
        list("damage",   list(1, 3, 5.5, 8)),
        list("radius",   list(4, 6, 8))
    )
```
Максимальный уровень спела = максимальному кол-ву уровней атрибута из всех атрибутов.
Если у спела есть атрибут `list("some_attribute", list(2, 6.6))` но уровень у спела больше чем элементов в листе - берётся последнее значение листа (в данном случае `6.6`).

**Comment by NefrNerf** [comment]
level-based можно конечно, но не в качествен замены и слияния улучшения скиллов в единичную ветку, а как рефакторинг. Убрать абстрактные empower и quicken заменить на уровни скорости и силы.
