### ISSUE TITLE
вырезаем хуй из граффити

### ISSUE THREAD

**Issue by Nod404** [ChaoticOnyx/OnyxBay#6432]
плин попросил вырезать хуй из граффити, поэтому сделаю иссуй, дабы закрыть его ПРом

**Comment by DarkHunter7756** [comment]
Попрошу объяснить мотив сего удаления. Более подробно, чем "Плин попросил"

**Comment by No-Tips** [comment]
Член является отсылкой на 21 век, ведь лишь в этом веке люди умеют рисовать такое!!!!!!!!

**Comment by No-Tips** [comment]
(нахуя ты это делаешь, ты ебобо, за что член)

**Comment by DarkHunter7756** [comment]
> Член является отсылкой на 21 век, ведь лишь в этом веке люди умеют рисовать такое!!!!!!!!

Если с Йобой можно прикопаться, ибо "Мем 21 века", то с Х*ем не понятно 0_о

**Comment by No-Tips** [comment]
хуй это запрещенная в РФ организация.

**Comment by Nod404** [comment]
у плина спроси, зачем его вырезать

**Comment by No-Tips** [comment]
@PlinHost Отвечай

**Comment by bosslobster** [comment]
Плин хочет вырезать хуй и унести домой
