### ISSUE TITLE
Новая способность бореру.

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6438]
### Улучшение
Обновление борера, делаем из скучного, ненужного паразита полезного симбионта.

### Решение
Добавить бореру возможность захватывать контроль над трупом, после смерти носителя (по факту анкоментить уже готовый код), бафнуть дав майндшилд от всех ментальных атак, дать возможность отключать болевые рецепторы человеку (пейн дамага). Предполагается, что таким образом маленький червяк будет сводить в могилу людей, захватывать контроль над трупом и покорять станцию.

**Comment by kreeperHLC** [comment]
Нефр, где декомпозиция...
