### ISSUE TITLE
Улучшение инженерии: программа для мониторинга материи

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#6441]
**Улучшение**
На данный момент любая материя на станции будет отслеживаться, даже если та упала на дропподе синдиката на далекий Биаркет, а статус и ее местоположение отследить никак нельзя. Предлагается сделать "трекер Шредингера", который будет иметься в каждой материи.

```
[Engineering] Supermatter Monitor (F) states, "Danger! Crystal hyperstructure instability! Integrity at 89%"
```
<img width="194" alt="dreamseeker_82LruGJ13a" src="https://user-images.githubusercontent.com/47484306/131488167-d1ae64d9-5b26-40c2-ab9d-cfe7123a0841.png">

**Решение**

- Требуется добавить нумерацию каждой материи, отдельно помечать материю синдиката и материю стартовую.
- Требуется добавить выбор материй в приложении для мониторинга статуса оных.
- Материю синдиката нельзя выбрать в приложении для мониторинга статуса материй.

**Comment by NefrNerf** [comment]
А зачем так сложно, у нас скорее всего одна материя на станцию, если материя не находиться в какой-то точке, на каком-то турфе, то просто ничего не делать.

**Comment by MaxTheAstronaut** [comment]
> А зачем так сложно, у нас скорее всего одна материя на станцию...

А если их несколько? Я порой экспериментирую с движками, ставя несколько материй, скажем. Одна из них в критическом состоянии, а ты думай, какая из них. Это квалити оф лайф фича, которую инженеры одобрят.

**Comment by MaxTheAstronaut** [comment]
@NefrNerf , добавлена альтернатива более простая.

**Comment by NefrNerf** [comment]
Оставить только уровень станции определенно стоит, я считаю, что можно создать специальный турф который на который можно помещать материю и с компьютера через приложение смотреть состояние материи на этом турфе, сообщение в канал должно идти только с материи которая стоит на таком турфе

**Comment by MaxTheAstronaut** [comment]
@NefrNerf , сейчас пообщался с инженером. Он предлагает просто трекер на материю вешать и отслеживать по нему. К примеру, станция будет уничтожена, а игроки смогут поселиться на Биаркете, построив движок на материи. Оповещения приходить не будут, ибо это не станция. А так, если будет трекер, то будут.

**Comment by NefrNerf** [comment]
Как ты на материю которая все что к ней прикасается сжигает будешь маяк вешать?

**Comment by No-Tips** [comment]
Анонимный инженер на связи. Надо учитывать, что касание к материи почти любым предметом - смерть.

**Comment by No-Tips** [comment]
И как-то отображать, что на материи есть трекер. А это еще один спрайт.

**Comment by MaxTheAstronaut** [comment]
Так прикол в том, что у материи есть стенд, кхм.

**Comment by MaxTheAstronaut** [comment]
И мы еще можем пуллить.

**Comment by NefrNerf** [comment]
Ну так в чем проблема? Почему тогда не оставить оповещение каждой материи, может в стенде датчики?

**Comment by MaxTheAstronaut** [comment]
Я все к тому, что спрайты - не проблема, у меня есть художник, который нам не только дорисует нехватающие спрайты, но и поправит старые.

**Comment by NefrNerf** [comment]
Просто каждой материи номер дайте и все

**Comment by MaxTheAstronaut** [comment]
> Ну так в чем проблема? Почему тогда не оставить оповещение каждой материи, может в стенде датчики?

У нас нет выбора из инпута.

**Comment by NefrNerf** [comment]
Ну, добавить выбор с какой материи получать информацию можно

**Comment by MaxTheAstronaut** [comment]
В общем, я все к тому, что синдикатовская материя сейчас странная, ибо отслеживается. Почему крутая организация не смогла обрубить систему отслеживания на ее стенде?

**Comment by No-Tips** [comment]
Можно давать нумерацию материям, которые заказаны. А стандартную материю как-то особенно подписать

**Comment by No-Tips** [comment]
А синдиматерию подписать как-то смешно.

**Comment by MaxTheAstronaut** [comment]
> Можно давать нумерацию материям, которые заказаны. А стандартную материю как-то особенно подписать

Да, можно, в принципе.

**Comment by NefrNerf** [comment]
Не-не, давай без тайного бума материей из пода

**Comment by MaxTheAstronaut** [comment]
Так или иначе, но надо добавить ей трекер. Фикс напоминает собой то, что я с мехами месяца три назад делал.

**Comment by MaxTheAstronaut** [comment]
> Не-не, давай без тайного бума материей из пода

Pathetic.

**Comment by MaxTheAstronaut** [comment]
Так, давайте подводить итоги. 

- Добавляем ли трекер?
- Добавляем ли выбор из инпута материй?

**Comment by NefrNerf** [comment]
Трекер внутри стенда для всех материй, а также особые названия для синди материи и первой материи в раунде, добавляем инпут выбор инпута для всех материй, кроме синди

**Comment by MaxTheAstronaut** [comment]
> Трекер внутри стенда для всех материй, а также особые названия для синди материи и первой материи в раунде, добавляем инпут выбор инпута для всех материй, кроме синди

Принято, корректирую иссуй и вызываю Опух овнеров для рассмотрения фичи.

**Comment by MaxTheAstronaut** [comment]
@NefrNerf , как тебе иссуй в данном виде?

**Comment by NefrNerf** [comment]
Пойдет
