### ISSUE TITLE
tgui_alert

### ISSUE THREAD

**Issue by kcalbCube** [ChaoticOnyx/OnyxBay#6463]
tgui_alert в случае краша тгуи просто выносит нас на окно ошибки тгуи, и ничего не сделать. это критично для fix chat, ибо невозможно переключится на старый чат без доступа к окошку.
можно сделать fallback стратегию тгуи алерту на вызов обычного алерта в случае ошибки тгуи, или же запурджить его нахуй

**Comment by stylemistake** [comment]
Fix tgui/chat просто должен вызывать обычный алерт, не нужно всей этой драматичности.
