### ISSUE TITLE
Сломана "порча" у культа

### ISSUE THREAD

**Issue by MaxTheAstronaut** [ChaoticOnyx/OnyxBay#6475]
При активации пентаграммы культа на захват области все стены, полы и окна должны превращаться в искаженные версии. По неизвестной причине искажаются лишь стены и полы, а окна остаются прежними, что явно является багом т.к часть требуемых объектов в билде есть (фото ниже).

![image](https://user-images.githubusercontent.com/47484306/132922485-d07cf532-3d06-48e0-ab4b-11448f0acb84.png)

**Comment by NefrNerf** [comment]
И где ты тут баг нашел? Я культостекл не вижу например

**Comment by O0oMaximo0O** [comment]
Я так думаю, под частью объектов имеется в виду решётка.

**Comment by NefrNerf** [comment]
Если мне память не изменяет, то культификация затрагивает только турфы, решета - объект

**Comment by NefrNerf** [comment]
Здесь скорее должен быть дизайн и пересмотр механики культификации, что вообще можно культифицировать

**Comment by O0oMaximo0O** [comment]
Да, турфы.

**Comment by O0oMaximo0O** [comment]
Про окна вообще в коде нигде нет.

**Comment by TermService** [comment]
где ты окна увидел хватит баги плодить
