### ISSUE TITLE
Слишком много всплесков адреналина.

### ISSUE THREAD

**Issue by vsrneji** [ChaoticOnyx/OnyxBay#648]
_Передано от Блейдраннера. За неактуальность ответственности не несу._

### Описание бага

От ран с большим брут или фаер-уроном появляется боль. От боли - всплеск адреналина. И каждый тик вызывает всплеск адреналина. В итоге передоз адреналином, который дамажит органы.

_____
_Воспроизведение и ожидаемое поведение не считаю нужным сюда добавлять. И так все ясно._

**Comment by HonkyDonky** [comment]
>Требуется проверка.
Откройте заново если актуально.
