### ISSUE TITLE
порт бореров

### ISSUE THREAD

**Issue by TermService** [ChaoticOnyx/OnyxBay#6489]
### Улучшение
Обновление бореров, текущие бореры скучные и морально устарели

### Решение
Порт бореров с Осириса/ириса

### Что будет добавлено 
Механика эволюции борера, включающая:

- Новые возможности в зависимости от степени эволюции борера (невидимость, телепатия и т.д.).
- Больше химикатов, доступных борерам для взаимодействия с носителем в зависимости от уровня борера.
- Улучшение хранилища химикатов и регенерация в зависимости от уровня борера
- Усиление действующих механик чтобы борер не был сосальщиком.

**Comment by TermService** [comment]
И ещё это решит ряд багов связанных с нашими борерами

**Comment by O0oMaximo0O** [comment]
Прошу кинуть ссылку на код и вики бореров, откуда их предлагается портировать.
