### ISSUE TITLE
Деды ветераны не могут в войну с щитсеками

### ISSUE THREAD

**Issue by KJIOYNz** [ChaoticOnyx/OnyxBay#649]
### Описание бага
Нельзя лежа развязать себя от наручников и тд.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем и отрываем себе ноги..
2. Отыгрываем деда, что воевал и ходим творим беспредел..
3. Попадаем под щитсека..
4. Либо пристыковываем себя самостоятельно к стулу, либо лежим сосем дальше с наручниками..

### Ожидаемое поведение
Твой ветеран должен был развязаться

### Скриншоты
-

**Comment by TobyThorne** [comment]
Наручники снимаются с помощью ног. Нет ножек - нет радости.

**Comment by KJIOYNz** [comment]
Каким образом они вообще без ничего снимают наручники ногами? покажите примером как люди снимают наручники, так ещё и ногами... наручники при этом остаются полностью целыми и их можно повторно использовать
