### ISSUE TITLE
Кнут для ГСБ

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6542]
### Улучшение
Ввести новый предмет для ГСБ - кнут, работает как стан дубинка сб с отличием что бьет через один тайл.
Если цель стоит прямо перед человеком - кнут не нанесет ему урон, а если между ними есть свободный тайл, но по нему пройдет урон.

**Comment by TobyThorne** [comment]
Это уже совсем какие-то мемы. Гачи достаточно в жукбоксе, не надо в механ тащить.
