### ISSUE TITLE
В некоторые ситуация кровь на предметах не обновляется (удаляется).

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#655]
### Описание бага
Кровь ксеносов остается на спрайте перчаток в инвентаре, но не на спрайте персонажа, когда ее смываешь в раковине. При том с человеческой такого не замечал.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Надеваем перчаточки.
2. Безжалостно режем чертовых ксеносов.
3. Смываем кровь в раковине.
4. Видим, что кровь осталась.

### Ожидаемое поведение
 Кровь должна смыться, да.

### Скриншоты

![перчи1](https://user-images.githubusercontent.com/48406301/62291610-0b910880-b46d-11e9-9978-82b47635f9b8.png)
но в то же время
![перчи2](https://user-images.githubusercontent.com/48406301/62291626-121f8000-b46d-11e9-8515-bd1d24af7cec.png)

**Comment by hard-res3t** [comment]
Сейчас глянул на локалке и все нормально работает.
Закрывайте наверное.

**Comment by Doster-d** [comment]
Ой, вспомнил, я такое недавно встречал для не перчаток, а для одежды в душе.

**Comment by TobyThorne** [comment]
> Ой, вспомнил, я такое недавно встречал для не перчаток, а для одежды в душе.

С одежды в душе кровь не смывается, если она закрыта другой одеждой. Нужно снимать скафандр чтобы помыть штаны, вроде логично.

**Comment by Doster-d** [comment]
> > Ой, вспомнил, я такое недавно встречал для не перчаток, а для одежды в душе.
> 
> С одежды в душе кровь не смывается, если она закрыта другой одеждой. Нужно снимать скафандр чтобы помыть штаны, вроде логично.

Она была снята, все равно оставался оверлей крови, а по описанию она была без крови.

**Comment by TobyThorne** [comment]
Вот эту хуйню надо заново проверить.

**Comment by k4m3rn** [comment]
Неактуально. Разве что при дире вбок не видно крови ваще, но это проблема отсутствующих оверов.
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/61733704/531b1b08-146c-44b0-baec-427b3ba96b4f)
ED: Перчатки если что латекски обычные.

**Comment by k4m3rn** [comment]
Вот после мытья рук.  
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/61733704/440e275b-9413-4c1a-bb6b-82cbe8ec9806)
