### ISSUE TITLE
Добавить повару шкафчик с одеждой для него

### ISSUE THREAD

**Issue by Zert0X** [ChaoticOnyx/OnyxBay#6595]
Я хочу поварской китель, а его нет.

**Comment by ghost** [comment]
Все, ща все будет.

**Comment by Mrbuble** [comment]
> Все, ща все будет.

Не сбылось😭

**Comment by vsss412** [comment]
Более актуальный дубль уже есть! https://github.com/ChaoticOnyx/OnyxBay/issues/10765
