### ISSUE TITLE
Сам себе пишу иссуи чтобы сделать

### ISSUE THREAD

**Issue by ZerlGray** [ChaoticOnyx/OnyxBay#661]
1) Резист наручников, будучи прикованным, идет в один этап (т.е. тебе не нужно сначала встать, а потом снять наручники, это одно действие - если ты снял наручники  то ты свободен)
2) Проклятый кубик должен стать сильнее. Он слишком сука тупой.
3) Попробую прикрутить нормальное зрение в темноте некоторым ксеносам и генкам. Опять.
4) Пофиксить зомби (опять).
5) Обнуление холдеров химикатов для генок.
6) Зрение на трейтах и рантаймы.

**Comment by Epicus7** [comment]
Что это блет и что с этим делать?

**Comment by Cinericius** [comment]
Кринж-троллинг от Философа

**Comment by Cinericius** [comment]
Но идеи вообще говоря не самые плохие, хотя наручники лучше оставить как есть.

**Comment by Cinericius** [comment]
Короч философ болен, но плашки я все сниму, потому что глазамозолят зазря. Будут четкие иссуи/ПРы - тогда поговорим.

**Comment by Epicus7** [comment]
@Cinericius, может закрыть тогда?

**Comment by HonkyDonky** [comment]
Какашка.
