### ISSUE TITLE
Storyteller: gamemods 

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6612]
### Улучшение
Уйти от понятия гейммода в принципе, оставить Extended, а сторителлер будет доспавнивать антагов в зависимости от внутреннего режима.
### Решение
У нас в сторителлере уже описаны условия для спавна большинства ролей, было бы логично использовать его как инструмент с более гибкой настройкой. Можно сохранить прессеты уже существующих режимов, а сама система будет их спавнить после начала раунда, это позволит уйти от старой неповоротливой системы, которая еще может отказаться запускать раунд, как например с Малфом.

**Comment by Epicus7** [comment]
1. Нужно в сторителлер добавить понятие раундстартовых триггеров и характеру раундстартовую логику, чтобы он мог на старте раунда посчитать метрики и вызывать раундстартовые триггеры.
2. Педалям надо добавить возможность в лобби перед стартом включать раундстартовые триггеры, которые будут запущены на старте, независимо от мнения сторителлера. Это нужно чтобы педали могли заспавнить нюку, например, иначе мы останемся без педальной нюки.
3. Добавить игрокам голосовалку за характер сторителлера. Добавить опцию конфига на автоматический запуск голосовалки в начале каждого раунда.
4. Нужно выпилить все отсылки на режимы по всему коду - довольно много работы.

Я думаю надо (1), (2) и (3) в отдельный иссуй вынести и поставить приоритет. Когда их реализуем, сделаем просто вечную эксту в конфиге и посмотрим как оно работает. Когда убедимся что все ок - тогда уже займемся (4) и выпилим режимы окончательно.
