### ISSUE TITLE
Wizard(subclass): necromancer

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6619]
Убиваем клерика, делаем некроманта

Уникальные скиллы
Заклинание призыва 1: 

уровень 1: оживление скелета - поднимает из тела гуманойда скелета, с атакой чуть сильнее кулаков. Труп гибается.
уровень 2: поднятие упыря - подъем более сильной, быстрой, крепкой нежити(возможно, разносящей вирусы). Труп гибается.

Заклинание призыва 2:
Мясной/костяной голем - на случай, если нет трупов - грабишь кухню, собирая кости/мясо и поднимаешь нежить-танка.

Заклинание урон/хилл 1:
С каждым уровнем повышается количество наносимого урона
Урон другому - вытягивание жизни - наносит Х урона органам, востанавливает 0.25Х хп

"Усилить нежить" - коснитесь нежити для улучшения, коснитесь трупа - труп гибается и скелет/упырь становятся сильнее. Скелету окошко выбора: скелет-лучник и скелет-мечник. Упырю выбор: плевальщик(урон токсинами, не пробивает броню) и коготь смерти(выше урон когтями и скорость, меньше хп) 

Утилитарное заклинание 1:  воскрешение - поднимает человека, но не как нежить, а как человека. Все раны исцеляются, появляется закон служения некроманту. Пропадает дыхание и пульс, на ХуД-ах - труп. Та же система - сначала госту тела, потом остальным. Если никто не идет - возврат части маны и "Ритуал провален". 

Бафф 1:  Форма Лича - возможность стать нежитью.
Дебаффы - заметность - большой и страшный спрайт, священник набьет тебе морду библией и святой водой.
Баффы - нет вирусам, уменьшен дамаг от пуль, но увеличен от огня и ближнего, уменьшенный урон от вакуума, не нужен кислород

Пассивный навык 1: разговор с мертвецами - переключается на вкл/выкл - некромант сможет видеть и слышать гостов

**Comment by O0oMaximo0O** [comment]
А зачем лекаря удалять?

**Comment by NefrNerf** [comment]
Он бесполезен и геймдизайн хочет смерти мирнокласса

**Comment by TobyThorne** [comment]
>гуманойда 

автор ты кто

**Comment by NefrNerf** [comment]
> >гуманойда 
> 
> автор ты кто

Автор человек, а писался иссуй вместе с Шутником и Дарком, не увидел ошибки.

**Comment by TobyThorne** [comment]
Если рассматривать описание иссуя - слишком куча каких-то новых механик, слишком уж выбивающихся от нынешнего визарда.
Идейно уж больно напоминает культомага, но зачем-то сделанного по-новой.
Какую-нибудь воскрешалку в виде SpOoKy-скелета можно сделать, конечно, но без фанатизма. И отдельным иссуем.

**Comment by Zert0X** [comment]
By Nefr
Оживление скелета - 1
Поднятие упыря - 1 (заражает при ударе спейс Спидом)
Плеть - бесплатная покупка, улучшение 1 навык 
Усиление нежити - пассивное, раз в 5 минут 
Воскрешение - 3 очка
