### ISSUE TITLE
Улучшение системы ближнего боя.

### ISSUE THREAD

**Issue by Jencent-hub** [ChaoticOnyx/OnyxBay#662]
### Улучшение
   Мили-система битвы в СС13 походит на нелепую беготню и персонажу с мили-оружием ОЧЕНЬ сложно справляться с противником, который бежит от него шустро и резво. Учитывая, что у нас игра с аркадными условиями (Читай как нельзя убить с одного удара топора в голову), то улучшение системы в сторону ближнего боя - это хороший шаг для улучшения игрового опыта в целом.

### Решение
   Предлагаю заимствовать философию из одной известной настольной игры, а именно: Warhammer 40.000. В ней персонажи ближнего боя, как только сблизились с целью - запрещают ей стрелять и форсируют на ближний бой. Таким образом отряды ближнего боя - это не еда для отрядов дальнего боя, ибо исключают таким образом возможность "кайта".

Собственно, что я предлагаю: Ввести условие, при котором атака ближнего боя вводит персонажей в некий "лок", который не позволит им бегать или делать что-либо, кроме непосредственной драки в любой из её форм. Стрелять персонажам с дальним оружием всё равно будет позволено (Иначе будет лишком легко для персонажей ближнего боя.).

**Comment by Firefroge** [comment]
Если у тебя дробовик, то что тебе мешает ёбнуть из дробовика в упор?

**Comment by Jhonas25** [comment]
Дядь, вы не в тот шлюз попали.
