### ISSUE TITLE
Питомцы для донатеров

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6625]
### Улучшение
Необходимо ввести возможность получить питомца игрокам с уровнем патрона `Wizard` и выше.
### Решение
На данный момент питомцы реализованы по #1750  в #6259. Необходимо ввести в лодаут новую вкладку `Питомцы`, в которой пользователь может выбрать доступного ему питомца. При появлении на станции, у игрока будет предмет клетка, в которой находиться питомец. Клетка может быть активирована любым человеком, а также питомец может быть помещен обратно в клетку, питомец будет воспринимать человека который достал его из клетки как хозяина. Также можно сделать клетку одноразовой, дабы не вводить полноценную механику клеток.
 
### (Опционально) Альтернативы
Альтернатива способу выше - спавн моба рядом с владельцем на станции, из этого вытекает несколько при реализации со стороны кода, например роли с местом спавна вне станции, а также возможное нежелание игрока, чтобы питомец находился с ним весь раунд.
 
### (Опционально) Дополнительная информация
Можно расширить количество питомцев, приветствуются идеи и спрайты.

**Comment by ghost** [comment]
Нефр, как бы сказать: у нас и так не очень много патронов, а самый высокий тир, как я помню - ХоС. Никто не будет платить ебаные двадцать бачей и выше ради чертовых 2д зверушек. На много лучше снизить требуемый тир до ХоСа. Это самый идеальный вариант т.к тир не очень дешев и не пиздецки дорогой. Подумай над этим на досуге.
![image](https://user-images.githubusercontent.com/47484306/135727383-d96a89fe-ebbb-41ce-a525-352e16a22a9d.png)

**Comment by NefrNerf** [comment]
Этот вопрос зависит не от тебя, не от меня, а от сената, иссуй написан по запросу Хэддева. Можешь посоветовать снизить цену в #сенат-открытый. Дана была задача продумать появление питомцев и расписать иссуй, задачу я выполнил. Я сам считаю, что цену можно и снизить, но опять же, все вопросы по данной теме к сенаторам, может сейчас у них будет другое решение.

**Comment by ghost** [comment]
@NefrNerf , зря быканул, прошу прощения.

**Comment by DarkHunter7756** [comment]
Есть еще альтернатива. Новая вкладка в карго консоли "Спец предложения". Тогда туда можно закинуть не только питомцев, но и другой донатный стафф, так или иначе воздействующий на раунд. Разумеется ею могут пользоваться только донатеры нужного ранга.

Если так и делать, то можно поставить электронный замок на имя карточки донатера. Ну и конечно возможность спиздить питомца/стафф емагом или мультитуллом

**Comment by NefrNerf** [comment]
Возможность через карго обсуждалась, только вот если так сделать, то карго будет самым неприятным отделом где воруют всех донатных петов просто ради гадости или сбрасывать в космос или анигилировать лифтом, как по мне, карго - плохой вариант получения пета и донатных шмоток.

**Comment by DarkHunter7756** [comment]
> Также можно сделать клетку одноразовой, дабы не вводить полноценную механику клеток.

Это может быть интересно и для простых игроков. Заказать ванильного питомца могут же и не донатеры. Не думаю, что стоит ограничиваться одноразовой механикой, раз вводим подобный предмет

**Comment by NefrNerf** [comment]
Разве? В любом случае, это уже на реализацию девелоперов и мнение овнеров.

**Comment by KamSurvivor** [comment]
Простите что вмешиваюсь, а зачем вводить какие-то там клетки, так еще и одноразовые? Почему бы не делать питомцев в кубах, как и мартышек?

**Comment by Epicus7** [comment]
Награда выдана

**Comment by Epicus7** [comment]
Награда выдана
