### ISSUE TITLE
Поставить КД на распечатку репортов анализатора растений у боргов и предположительно людей

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#6659]
Ей-богу, срать бумагой - кринж
![image](https://user-images.githubusercontent.com/76823962/136114018-d6238537-7a2f-482b-9d28-d796a7ef028b.png)
![image](https://user-images.githubusercontent.com/76823962/136114037-13f82986-882d-47d4-8e91-78bbfc1efc22.png)

**Comment by kreeperHLC** [comment]
![image](https://user-images.githubusercontent.com/14943437/136169013-8fd9829a-62ba-4e83-9e64-d37d5316e037.png)
И целых три метода печати репорта
