### ISSUE TITLE
Один из багов мерчей

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#667]
### Описание бага
Те торговцы-неписи, которые появились в начале раунда не подвергаются ротации, то есть с ними можно торговать весь раунд

### Воспроизведение
Шаги чтобы воспроизвести баг:
1)Залипаешь в консоль
2)Видишь что первые 2-3 торговца никуда не меняются, тогда как остальные меняются

### Ожидаемое поведение
Все торговцы должны быть подвергнуты ротации

### (Опционально) Дополнительная информация
Есть один важный момент, я глянул в варах, у этих торгашей вообще напрочь отсутствуют вары duration_of_stay и typical_duration. Может где-то косяк в инициализации. Чекать вары можно в Debug -> List Traders если что

**Comment by JILMbIX** [comment]
Но баг ли это, или фича...
Конечно иногда на постоянной основе выпадают говноеды, которые продают хлам и ничего не покупают, или покупают то что очень геморно/нереально достать, но с другой стороны, если попадется там какой-нибудь медик, скупающий органы, или рудопереработка, то это задает какую-то не обязательную цель и уверенность в том что ты не останешься с голой задницей, если сможешь достичь ее.

**Comment by Voldirs** [comment]
Дополнительно чекнул, именно торгаши, которые появляются именно до старта раунда не имеют нужных варов.

**Comment by Voldirs** [comment]
а чо я ещё не закрыл это, я же пофиксил
