### ISSUE TITLE
Крайне тяжело сделать ED-209

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#668]
### Описание бага
Нужно родить конкретный броник и конкретный тазер чтобы его сделать

### Воспроизведение
Пытаемся сделать ЕДа, просим тазеры у охраны, а они внезапно не подходят

### (Опционально) Дополнительная информация
А всё потому что в дереве какой-то особо одарённый человек поместил classictaser не как подтип тазера, а сам по себе в ветке. В итоге мы сука имеем сейчас в билде аж три вида тазеров, которые отличаются друг от друга чуть менее чем нихуя. Аналогичная ситуация с тактическими тазерами, их аж ТРИ ШТУКИ в коде висит, два из них которые абсолютно одинаковы. Возможно с бронниками такая же хуйня, не смотрел

**Comment by TobyThorne** [comment]
ПР с фиксом уже есть, но не принимается.
