### ISSUE TITLE
Ребаланс энергетических щитов (структуры)

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#669]
### Улучшение
Щиты сейчас абсолютно непробиваемы ничем если есть энергия. И даже никакие супер детали из РнД не нужны. В итоге имеем всяких гробиалов, которые запираются в щите и выковырять их становится задачей чрезвычайно нетривиальной.

### Решение
Ну моя идея была в том чтобы полностью убрать реген щита, СИЛЬНО уменьшить потребление энергии если щит полностью целый (ну например чтобы жрало 50-100kWh при полном щите) и экспоненциально увеличивать потребление с нарастанием урона на щите. Если энергии не хватает на поддержание щита, он необратимо отключается в течение 2-10 минут (в зависимости от деталек, которые вставлены туда). Ручное отключение щита мгновенное без каких либо последствий, запуск щита занимает 0.5-3 минуты в зависимости от деталей. Также потребление энергии щитом от урона должно увеличиваться со временем (скорость увеличивания тоже должна зависеть от деталек), то есть давно запущенный щит держит урон хуже чем "свежий". Настройки щита не могут изменяться когда он включен, в том числе и РАДИУС. А ещё поменять систему модуляции щита, они не должны жрать больше энергии, но должны помимо плюса давать и определённые дебафы к щиту (ну кроме того модуля что закрывает другие з-левелы), а модуль резистов можно выбрать только один. Увеличил резист к одному виду урона, все остальные уменьшились. Увеличил все резисты, но щит стал "стареть" гораздо быстрее. Решил хакнуть и включить два заблокированных модуля? Оба из них снижают резисты щита, а если энергии для поддержания щита будет не хватать, есть шанс что генератор бахнет с приличной силой. Для упрощения жизни, в интерфейсе где можно выставить предельную нагрузку, которую щит может брать на щиты можно по формуле расчитывать для инженера при каком уроне он решит упасть, и сделать небольшой настраиваемый радиомодуль в самой машинерии который позволил бы сообщать состояние щита в инженерный и командный канал.

### (Опционально) Дополнительная информация
Я может что-то забыл написать, тому что придумал перед сном. И это, поменьше линейных функций, побольше степенных. Никто ж не будет это делать, да?

**Comment by Epicus7** [comment]
Продолжаем рубрику "Нерфоцирк имени Волдирса".

Многобуков ничего не понятно. Нужен разбор геймдизайнером, декомпозиция на несколько иссуев и подтверждение на запил.

Вообще щиты и правда сейчас какие-то хехмда, так что действительно стоит подумать над этим.

Сложность из-за объемов, после декомпозиции должна снизиться.

**Comment by kreeperHLC** [comment]
Многобукв, но всё понятно. В принципе годная идея, но вот старение щита как по мне лишнее

**Comment by Voldirs** [comment]
Старение щита я предложил для того чтобы нельзя было щит включённым держать прям постоянно, чтобы была необходимость его время от времени перезапускать

**Comment by Cinericius** [comment]
Может быть еще сделать энергопотребление и резисты в зависимости от размера щита, причем чем он больше - тем стабильнее работает (типа распределяет энергию по всей площади)? Тогда сидеть в щите будет сложнее, а вот станцию от метеоров прикрыть вполне реально.

**Comment by Cinericius** [comment]
Сыро

**Comment by TobyThorne** [comment]
Не проработалось за три с половиной года.
