### ISSUE TITLE
Реабилитация Офицера Бипски

### ISSUE THREAD

**Issue by TobyThorne** [ChaoticOnyx/OnyxBay#670]
Нужно сделать, чтобы Бипски, при виде человека с иконкой wanted тут же бросался на него с батоном на перевес. Прямо сейчас он какое-то время просит арестанта остановиться, чем даёт довольно жирное окно, чтобы сбежать.
Бить Бипски должен на хелпе и по ногам. Когда жертва упала, на неё должны надеваться наручники из проводка, как это происходит сейчас. 
Фразы Бипски, которые он говорит, можно оставить, но без периода ничегонеделанья. Пусть кричит свои фразочки прямо во время атак. 

Оригинальный пост:
> Бипски уже давно превратился в бесполезный кусок говна, который даже одноногого ассистента догнать не может. Беевские нерфоклоуны плез.

**Comment by Cinericius** [comment]
#1176

**Comment by MemoryDreams** [comment]
Обновил иссуй.
