### ISSUE TITLE
Фичи которые мы потеряли, но не забыли

### ISSUE THREAD

**Issue by Mo3goed** [ChaoticOnyx/OnyxBay#671]
Не все застали те замечательные времена когда можно было услышать призраков, или когда при помощи метроидов прокормить всю станцию, а можно было и боргостанцию устроить используя соответствующий бургер, или заражение алиумами, круто же правда? А вот все скатилось, теперь этого делать нельзя, фичи вырезаны чуть более чем полностью, вещи которые придавали веселья порублены в корне.

А теперь суть иссуя:

1. Возможность слышать мертвецов, с опредленным шансом, для каппелана удвоено.
 Это же весело, гостота которая скучает, может докучать живым, и сводить с ума каппелана.

2. Разнерфить культ, вернуть ему былое обличие, когда культ это мать его культ, а не ХОТИТЕ ЛИ ВЫ БЫТЬ КУЛЬТИСТОМ.

3. Вернуть революцию и лолфлеш, потому-что, мы хотим что-бы вы... ВО СЛАВУ ВЕЛИКОЙ РЕВОЛЮЦИИ!

4. Вернуть ожирение для всех, но ведь пухлячек может пробежать пару кружков вокруг станции и сбросить весь, ну или к хирургу в гости зайти.

5. Разнерф генокрадов, вернуть смертоукол, который убивает, а не чучуть наносит урона.

6. Вернуть в рандомные ивенты ГБС, Ретровирус и прочее, а иначе нахер эта вирусология нужна тогда.

7. Вернуть кастомные бургеры, с соответствующими эффектами, превратить станцию в боргов, или заставить ассисстентов спонтанно плеваться фаерболлами, или ЕЙНАХАТЬ друг-друга, что может быть веселее.

8. Вернуть гиб калиеводе, ну серьезно, кто на это поведется то.

9. Вернуть старых добрых алиумов, и ксенохлеб.

**Comment by TobyThorne** [comment]
Два кензибургера этому господину.

**Comment by ZerlGray** [comment]
8. Уже давно есть.
3. Революция как режим не нужна. Максимум - переосмыслить и как нечто более сложное.
2. В смысле "разнерфать"? Он у нас более простой чем на старобее, не нужно ебаться с поиском слов. Проблема скорее в том, что он опять же, требует полного ревока, а не разнерфа.
5. Ты видимо давно не играл, и не знаешь, что у нас ревокнутые конокрады которые в данный момент нифига не требуют бафов. У них есть абилка со встроенным химраздатчиком, позволяющим варить какую угодно гадость. И куча других весьма мощных абилок. И они практически неубиваемы сейчас.

**Comment by Megmeehey** [comment]
>Возможность слышать мертвецов, с опредленным шансом, для каппелана удвоено.
>Это же весело, гостота которая скучает, может докучать живым, и сводить с ума каппелана.

Да, если это культ. Во всех остальных вариантах тематика раунда не очень-то подходит. Особенно учитывая, что гостота = смесь иц и ооц.
Хотя, священника донимать, это звучит мило.

>Разнерфить культ, вернуть ему былое обличие, когда культ это мать его культ, а не ХОТИТЕ ЛИ ВЫ БЫТЬ КУЛЬТИСТОМ.

Как? Что разнерфать кроме лолконверта?

>Вернуть революцию и лолфлеш, потому-что, мы хотим что-бы вы... ВО СЛАВУ ВЕЛИКОЙ РЕВОЛЮЦИИ!

В ротации её нет, но её вроде форсят. Что разнерфать кроме лолконверта?

>Вернуть ожирение для всех, но ведь пухлячек может пробежать пару кружков вокруг станции и сбросить весь, ну или к хирургу в гости зайти.

Что сейчас есть, и какое поведение ожидается?

>Разнерф генокрадов, вернуть смертоукол, который убивает, а не чучуть наносит урона.

Нет.

>Вернуть в рандомные ивенты ГБС, Ретровирус и прочее, а иначе нахер эта вирусология нужна тогда.

Что такое ГБС? Что такое Ретровирус? Вирусология вообще сейчас закрыта по умолчанию.

>Вернуть кастомные бургеры, с соответствующими эффектами, превратить станцию в боргов, или заставить ассисстентов спонтанно плеваться фаерболлами, или ЕЙНАХАТЬ друг-друга, что может быть веселее.

С некоторыми эффектами - возможно.
Случайно эйнахающий игрок, это ~любой маг~ не весело.

>Вернуть гиб калиеводе, ну серьезно, кто на это поведется то.

Что сейчас есть, и какое поведение ожидается?

>Вернуть старых добрых алиумов, и ксенохлеб.

Кто такие алиумы? Что такое ксенохлеб?

**Comment by Cinericius** [comment]
Вообще я не помню, чтобы кто-то кроме капеллана раньше слышал гостоту, но вот у капеллана этой способности сейчас остро не хватает, да.

Алиумы - чужие, ксеноморфы. Ксенохлебушек - особая еда из алиумов, которая, если ее съесть много, превращает со временем в чужого (человека гибает и переселяет в отспавненного взрослого алиена случайного класса кроме квины). Реализовано это было засчет особого реагента в мясе чужих.

**Comment by Epicus7** [comment]
Нужно разбить на много иссуев и обсуждать каждый пункт отдельно.

В общем работа для геймдизайнера.

**Comment by kreeperHLC** [comment]
3 уже в отдельном иссуе, 6 сделано. Попросил создателя иссуя разделить на несколько
