### ISSUE TITLE
Не очищать поля ввода при записи банов в банпанели

### ISSUE THREAD

**Issue by Altehor** [ChaoticOnyx/OnyxBay#6745]
### Описание бага
При выписывании джоббанов на банпанели после добавления джоббана необходимо по новой выбирать тип, заполнять поля сикея, IP, CID, времени и ризон.

Раньше после добавления джобки панель не чистилась и позволяла быстренько прокликивать профессии.

**Comment by Epicus7** [comment]
> раньше

Вроде никогда оно так у нас в билде не работало. Ставлю улучшение. Если реально раньше так работало, то надо назад баг вернуть и найти изменения, которые это сломали.
