### ISSUE TITLE
Звук запуска шаттла

### ISSUE THREAD

**Issue by Destrolaric** [ChaoticOnyx/OnyxBay#675]
### Улучшение
Уменьшить громкость звука запускаемого шаттла.
### Решение
Уменьшить громкость звука запускаемого шаттла в исходном файле.
### Дополнительная информация
**Сильно** выделяется на фоне других звуков. Очень громко.

**Comment by MrPersival** [comment]
Возьмусь.

**Comment by MrPersival** [comment]
Окей, большенство считает что и так хорошо. Ты уверен?

**Comment by Destrolaric** [comment]
По моим ощущениям, сильно громче других звуков.

**Comment by Epicus7** [comment]
Если это так, то это баг. Но скорее всего нет)

Надо в каком-нибудь раунде спросить в ООС у людей ровно перед отлетом шаттла и посмотреть, кто чо скажет.

**Comment by MrPersival** [comment]
Пофиксил, закрывай.
