### ISSUE TITLE
Поменять количество онлайна нужного для появления вампира

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#6754]
Вампиру, у которого ограничения по онлайну есть, предлагаю совсем убрать это ограничение.

**Comment by Epicus7** [comment]
Аналогично, не понял о чем идет речь, как и в #6562.

Вот описание режима:
https://github.com/ChaoticOnyx/OnyxBay/blob/dev/code/game/gamemodes/vampire/vampire.dm

Нужно минимум два игрока для включения режима. Для спавна сторителлером опять же зависимость идет не от онлайна, а от количества СБшников и других спец. ролей.

**Comment by Shirlineyn** [comment]
Вампиры выключены в конфиге.
