### ISSUE TITLE
Из-за неблагоприятной атмосферы борер внутри человека умирает быстрее, чем мозг

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#6757]
Создано из обсуждения #5977.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Залезть в носителя.
2. Взять контроль над телом.
3. Повысить температуру или выйти в открытый космос.
4. Ждать пока в чат покажет сообщение >The cortical borer dies.
5. Борер умер, а человек жив. Такого быть не должно, мозг умереть должен первым.

**Comment by O0oMaximo0O** [comment]
Допустимо ли, чтобы борер внутри живого человека вовсе не получал урон от окружающей среды?

**Comment by Epicus7** [comment]
Награда выдана
