### ISSUE TITLE
Пулл должен занимать руку

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6760]
### Улучшение
Сейчас пулл - 3 фантомная рука и можно тащить огромные предметы, людей.
С этим изменением хорошо бы ввести возможность баклить к каталкам мешки для трупов и крио.

### Решение
Портировать с ТГ фичу, при которой пулл человека может совершаться только если он грабнут первым уровнем граба.

### (Опционально) Альтернативы
Абсолютный нерф пулла, все предметы которые можно тащить, должны занимать руку, каталки, ящики итд.

### (Опционально) Дополнительная информация
Тапок решил этим заняться, так что ПР возможно появиться в скором времени, делаю иссуй абы работа не пропала зря, если решат отменить или поднимется слишком большая буча.

**Comment by TimErmolt** [comment]
Я за оффтоп конечно извиняюсь, но может вы сразу билд на ТГ смените, чем по кускам его превращать, а то уже смешно выглядит.

**Comment by kreeperHLC** [comment]
Кто вы то?

**Comment by kreeperHLC** [comment]
Пока это не полноценный ПР, даже думать о таком смешно

**Comment by k4m3rn** [comment]
У нас пулл предметов уже замедлен. Да и объяснить просто (теперь стало ещё проще). Персонаж ногой за собой подтаскивает предметы. Неважно как, это уже игровая условность. Пулл скорее является грубой силой, чем захват предмета рукой. Будет невероятно тупо выглядеть то, что космонавтик будет пуллом тащить по полу ручку или любой другой мелкий предмет. Как бы _это_ выглядело ИРЛ уже?
