### ISSUE TITLE
Noticeboard в кабинете детектива не удалял фотку кнопкой Remove

### ISSUE THREAD

**Issue by Altehor** [ChaoticOnyx/OnyxBay#6766]
### Описание бага
Noticeboard в кабинете детектива не удалял повешенную ранее фотку кнопкой Remove.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Вешаем фото на доску фотку.
2. Пытаемся фотку с доски убрать.

### Ожидаемое поведение
Фотка должна была удалиться из списка и пропасть с доски.

### (Опционально) Дополнительная информация
Не проводил даже минимальных тестов, кроме того что после жалобы игрока сам попробовал эту фотку снять. Не вышло.

**Comment by Terydd** [comment]
https://user-images.githubusercontent.com/91453615/138613905-3085e872-cdb8-406e-a421-40f9e332cb33.mp4

Ну, баг определённо есть на Исходе. Врядли это зависит от карты, но всёж уточню.
