### ISSUE TITLE
Кровь делает слип-слип

### ISSUE THREAD

**Issue by TobyThorne** [ChaoticOnyx/OnyxBay#6774]
Добавить возможность поскользнуться, бегая по мокрой крови, процентов так 15-25%. Только на больших мокрых лужах крови и гиббах, без высохших луж и капелек. 
При падении в лужу должны мараться не только ноги, но и вся открытая одежда. 
Магбутсы/нослипы/галоши и ходьба шагом не дают упасть - так же, как и в случае с водой.

Больше респекта уборщику, больше смешных покатушек.

**Comment by Artemonim** [comment]
Кровь же вязкая. Наоборот липнуть должны
