### ISSUE TITLE
Добавить какую-нибудь пользу интегральным корпусам на заброшенном аванпосте (данж астероида)

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#6779]
Они сейчас только имитируют полезный лут, в своей сути оставаясь ПУСТЫМИ корпусами. 

Может ввести в них какую-нибудь интересную для шахтеров или ученых схему по типу зарядника для всего/качественной буровой установки?
Может добавить в них каких-нибудь уникальных интегральных плат, которые даже на принтере не распечатать?
Или может расположить по всем данжам и дереликтам нечто вышеперечисленное? Решать вам

![image](https://user-images.githubusercontent.com/76823962/138379500-10062885-5485-4bf0-b846-00fa98a6d377.png)

**Comment by Doster-d** [comment]
Велл ю кэн пост сом схематикс ту ад зем виа префабс

**Comment by DarkHunter7756** [comment]
> Велл ю кэн пост сом схематикс ту ад зем виа префабс

сам ивенинг, бат фенкс

**Comment by DarkHunter7756** [comment]
Мы тут подумали и имеем небольшой список идей, которые можно реализовать в этих корпусах:
1. Корпус Дрона - ММИ/пИИ/ММИ+пИИ дрон с функцией открытия двери. Доступ изначально отсутствует. 

2. Корпус Машины

• Генератор сыра (две-четыре емкости, в одной молоко, в другой энзимы, между ними помпа и тикер) 

• Генератор дейтериума (тот же принцип, но вместо молока вода, а вместо энзимов плазма)

3. Корпус Девайса - фонарик / ДИСКО-фонарик / Генератор звуков (до 6 штук)

4. Корпус Механизма.

• Дым-машина с рандомным содержанием и срабатыванием по кнопке. Функция заполнения отсутствует. Выборка производится из: Бикардин+Дермалин, Соляная кислота, Cryptobiolin+Space Drugs, Гиперзин, Смазка. В емкости 120 реагента, то есть 12 срабатываний. Возможно установлю систему определения зарядов. 

• Переносное устройство по вкалыванию реагентов по сканированию. Изначально пустое. Все входы реагентов: Бикардин, Дермалин, Диловене, Дексалин+, Аритразин, Трамадол. Есть порты для входа емкостей с реагентами. 

• Устройство-артефакт. 4 Кнопки, у каждой свое назначение. Подписаны 1, 2 , 3 и 4 соответственно. Имеется несколько вариаций подобных устройств с разными кнопками и назначениями. Среди назначений: Самоподрыв, Создание случайного портала, сброс из граббера редкого предмета, создание дыма из адской воды (одно срабатывание), продолжение следует...

Что из этого пойдет?

**Comment by DarkHunter7756** [comment]
После апдейта буду думать насчет дереликтовых интегралок, а пока жду ответа от достера

**Comment by Doster-d** [comment]
Можно еще этот прикол засхеметировать, средний размер должен хватить с полна.
https://www.youtube.com/watch?v=sqyiYd4iCYY

**Comment by NefrNerf** [comment]
Добавить можно, простенькие функции, +
