### ISSUE TITLE
Починить "Blood Shards

### ISSUE THREAD

**Issue by CokeUser** [ChaoticOnyx/OnyxBay#679]
### Описание бага
Если кинуть сразу оба Осколка в одну цель, то в воздухе останется эффект выстрела осколков из тела (muzzle)

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Используем Blood Shards;
2. Кидаем их оба в одного человека, что есть скорости;
3. Наблюдаем как разлетаются осколки;
4. Лицезреем зависшие эффекты выстрела вокруг цели.

### Ожидаемое поведение
Добавить способности откат \ Убрать возможность кидать несколько осколков.

### Скриншоты
![ywRdEeA](https://user-images.githubusercontent.com/45202681/62628470-34be0700-b94d-11e9-94f3-9053c1ee832c.png)

### (Опционально) Дополнительная информация
Находиться в Warlock книге.

**Comment by Animesku** [comment]
А что за файл///Д:/...?

**Comment by Fritcher36** [comment]
Скрины кинь в дискорд, тут они сломались

**Comment by Fritcher36** [comment]
Ты как бы дал ссылку на свой жесткий диск, лол

**Comment by CokeUser** [comment]
> Ты как бы дал ссылку на свой жесткий диск, лол

А ведь действительно дал. 
Сейчас кину нормально

**Comment by TobyThorne** [comment]
_Пофиксил смешной скриншот в шапке._

**Comment by TermService** [comment]
Кажется это уже пофикшено
