### ISSUE TITLE
Портировать спрайты атмоса

### ISSUE THREAD

**Issue by InfringementOfReality** [ChaoticOnyx/OnyxBay#6793]
Сейчас у нас огонь, форон и нитроксид представляют из себя просто точки, рандомно натыканые в спрайтах. Давайте портируем вышеуказанные спрайты с пчелостанции, чтобы в целом улучшить их внешний вид.

**Comment by ghost** [comment]
Го, я готов это сделать. @NefrNerf , апрувчик?

**Comment by NefrNerf** [comment]
Спрайты в студию @MaxTheAstronaut, потом аппрув

**Comment by ghost** [comment]
Ожидайте проект в 20:00 по МСК.

**Comment by Zert0X** [comment]
Звягин всё. Из-за прозрачности спрайты хуйня в гитхабе
Вот три спрайта огня
![fire](https://user-images.githubusercontent.com/42303535/167112196-620457c6-7fb6-4cbd-a90b-9638eaa1b44c.gif)
![fire2](https://user-images.githubusercontent.com/42303535/167112186-a0b692f8-9043-469e-bf50-92b83db701f5.gif)
![fire3](https://user-images.githubusercontent.com/42303535/167112190-8a963d28-9de8-4b8d-8721-7da1e8520bc7.gif)
Плазма
![Plasma](https://user-images.githubusercontent.com/42303535/167112272-2a84564b-f020-4f78-99ec-c2874644735b.gif)

**Comment by No-Tips** [comment]
commented [on Oct 23, 2021]

Можно еще закись азота оттуда же украсть и водяной пар, но дм жмет их как говно, что нихера не видно. 
Дмка - https://github.com/BeeStation/BeeStation-Hornet/blob/master/icons/effects/atmospherics.dmi
