### ISSUE TITLE
Глайдо-баговое

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#6797]
1. Прыгающее диалоговое окно, нужно накинуть глайд.
![9vbMi3qBay](https://user-images.githubusercontent.com/47484306/138594719-9e1e15c4-1006-4414-99fc-679211d2272c.gif)

2. На второй записи сразу несколько проблем: спрайт призрака, которого убили либо в грабе, либо в крите слегка замедлен и иногда спрайт призрака-следователя не успевает за отлеживаемым.
![A5x8tA25eL](https://user-images.githubusercontent.com/47484306/138595073-7761c5c4-2bd7-4bc4-8c76-fbb5204d3f00.gif)

3. При следовании за киборгами и людьми глайд призрака быстрее, чем глайд движущегося тела.
![HnhSyHyUn7](https://user-images.githubusercontent.com/47484306/139296466-04e617c6-4218-4909-90c6-3d6f31dfd4ed.gif)

P.S
Каталки и коляски починили, баян.
![JRu8sulwAg](https://user-images.githubusercontent.com/47484306/138595089-1934d9e9-27c6-458c-a5ff-dcd0b523e33c.gif)
![7KitHeZPhK](https://user-images.githubusercontent.com/47484306/138595091-667675b0-2c25-44e1-9a80-90108ca67395.gif)

**Comment by Artemonim** [comment]
#6795

**Comment by ghost** [comment]
Дополнил репорт новой информацией.
