### ISSUE TITLE
Новый материал - Титан

### ISSUE THREAD

**Issue by InfringementOfReality** [ChaoticOnyx/OnyxBay#6808]
Титан добывается на астероиде, причём сам титан невозможно переплавить в его печке(У нас же не домна топтира, да?), вместо этого его нужно отправить на шаттле карго чтобы получить с ЦК переплавленный вариант

Титан можно использовать для сборки стен шаттла, продажи в карго и укрепления труб

Титан можно использовать на трубу, тем самым укрепляя её и защищая от прорыва

**Comment by DarkHunter7756** [comment]
Почему нельзя просто поставить блокировку переплавки до получения печкой улучшения РнД. Насколько мне известно, на нее идут детали.

**Comment by InfringementOfReality** [comment]
Наша печка - старый кусок хардкода и не может быть разобрана/улучшена

**Comment by DarkHunter7756** [comment]
Как же много всего в этой игре решается добавлением возможности тупо делать и улучшать машинерию...

**Comment by InfringementOfReality** [comment]
Имхо ты не превратишь плавильню в домну просто добавив детали

**Comment by DarkHunter7756** [comment]
Чуток медной обмотки и твоя печь греет на 500-1000 градусов больше 😼
Да и у нас блюспейс эра, 26 век хули. Добавляем более совершенные микро-лазеры и радуемся прогрессу

**Comment by O0oMaximo0O** [comment]
> Наша печка - старый кусок хардкода и не может быть разобрана/улучшена

Может. Вот собрать нельзя. Разобрать - не пробовал, но улучшить точно можно.
