### ISSUE TITLE
Вернуть МалфоИИ в ротацию

### ISSUE THREAD

**Issue by No-Tips** [ChaoticOnyx/OnyxBay#6811]
### Улучшение
У нас в коде лежит ВРОДЕ КАК (если не считать одного бага, из-за которого он не спавнится, как режим) полностью рабочий малфоИИ, который почему-то выключен, как режим. 

Предлагаю собрать тут все проблемы, почему этот режим не включен, и что стоит сделать, чтобы разнообразить раунды еще одним антагом. Готов взяться их решать по мере поступления.

**Comment by BooJ1K** [comment]
В целом, руками и ногами я за, но Малф унылый в плане кнопок.
На этом билде нет способов с пользой убивать человечков: 
Нет машины для насильственной кибернизации, только автотоматы, которые нужно выращивать двум боргам или боргу с ИИ на дроне, при этом потерять кучу времени, чтоб вывести этот сорт растений.
Нет возможности создать вирус: Мед. киборги, насколько я знаю, могут создать только антивирус, взяв кровь у больного и вколоть макаке, поправьте если не так.
###  Баги?
- Self-Destruct Explosives взрывает ИИ, но не наносит урона окружающим, кукла сидела в клетке от ядра – 0 повреждений, если оставлять концепт этого "аппаратного обеспечения" можно прикрутить какие-нибудь скейлы от взломанных АПЦ или чтоб по стандарту взрывало все клетки пола "processing strata"
- АПЦ можно взламывать на аванпостах, но с них ты не получаешь CPU generation rate и Maximal CPU. (вроде и правильно что не даёт, но зачем тогда есть возможность их взламывать?)

**Comment by O0oMaximo0O** [comment]
Не уверен насчёт мед.боргов, но вот научные...
Хм, глянул код, мед. тоже могут.

**Comment by O0oMaximo0O** [comment]
Надо позволить строить турели с помощью киборгов/дронов.

**Comment by BooJ1K** [comment]
> Не уверен насчёт мед.боргов, но вот научные... Хм, глянул код, мед. тоже могут.

Они могут работать с дисками и оборудованием в вирусологии?

**Comment by O0oMaximo0O** [comment]
Да. Мед/хим захваты могут брать чашки Петри.

**Comment by O0oMaximo0O** [comment]
Не могут понять, могут или нет пробирки или шприц переносить. Надо в игре проверить. А то возникает проблема с размножением вирусов... Новые чашки Петри непонятно откуда брать.

**Comment by Doster-d** [comment]
Текущий малф говна говной с улучшениями говна

**Comment by DarkHunter7756** [comment]
> Надо позволить строить турели с помощью киборгов/дронов.

И как ты это оформишь? Манипулятором не пойдет, он сам начнет стрелять оружием. А иными методами будет костыльно и неудобно

**Comment by IvanDonFon** [comment]
Почему-бы не портировать малфа с фырфынити?

**Comment by Wuattt** [comment]
> В целом, руками и ногами я за, но Малф унылый в плане кнопок. На этом билде нет способов с пользой убивать человечков: Нет машины для насильственной кибернизации

у малфа вроде апгрейды есть. Что если, один из апгрейдов будет Cyborg Factory, который будет из человечка и 10 металла (как у големов) делать робота за 60 секунд?

**Comment by BooJ1K** [comment]
> > В целом, руками и ногами я за, но Малф унылый в плане кнопок. На этом билде нет способов с пользой убивать человечков: Нет машины для насильственной кибернизации
> 
> у малфа вроде апгрейды есть. Что если, один из апгрейдов будет Cyborg Factory, который будет из человечка и 10 металла (как у големов) делать робота за 60 секунд?

И как это должно выглядеть? 

1. Ставишь человечка с живым мозгом на клетку с 10 листами стали и через контекстное меню активируешь способность?  
2. Отдельное строение, похожее на Exosuit Fabricator, которое служит только для переработки человеков в боргов?
3. Добавить уже существующему умению (Machine Upgrade) возможность улучшать Exosuit Fabricator, чтоб борги могли перетаскивать спрайты гуманоидов в эту машину для получения готового киборга?
PS: Для создания киборга с нуля, требуется +90 листов стали

**Comment by Wuattt** [comment]
> И как это должно выглядеть?
1. Ставишь человечка с живым мозгом **на клетку возле ядра ИИ** с 10 листами стали и через **меню абилок** активируешь способность

но для этого обязательно чтоб ядро было живое и какой-нибудь сообщник

**Comment by DarkHunter7756** [comment]
Может вы просто наномашины используете? Например абилка вводит в организм случайного лежачего человека в ядре 20 наномашин. А то слишком много условностей у вас с проверкой на наличие стали

**Comment by No-Tips** [comment]
Ребзи, а ничего так, что на финиках малф такой же, как и у нас? Что портировать-то...

**Comment by No-Tips** [comment]
Строить турели это идея говна, у малфа и так  есть потенциал делать много смешного, турели ни к чему. Да и кто мешает на крайний случай скоопиться с инженером, который за свою жизнь будет строить турели?
