### ISSUE TITLE
Поправка к описанию режима heist.

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#6824]
По поручению от Лида Хаотика, Совет Хаотика предлагает следующие поправки: Заменить описание раундстартовое описание роли Вокса на следующее: 
_You are robbers, not raiders. Avoid direct confrontation with the station, the loss of fellows is unacceptable._
_Вы грабители, не налетчики. Избегайте прямой конфронтации с станцией, потери собратьев неприемлемы._

**Comment by kreeperHLC** [comment]
Ловла, какое просто к неодобренному иссую

**Comment by Zert0X** [comment]
> Ловла, какое просто к неодобренному иссую

А разве нельзя ставить сложность без одобрения?

**Comment by kreeperHLC** [comment]
> > Ловла, какое просто к неодобренному иссую
> 
> А разве нельзя ставить сложность без одобрения?

Сложность оценивается только после одобрения геймдизайна, либо если это баг
