### ISSUE TITLE
Слепые зоны на камерах ИИ на карте "Рубеж"

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#6832]
Я собрал ряд фотографий, на которых заметны слепые зоны камер, которых быть не должно. Для фикса требуется изменить положение камер / добавить новые.

1. Слепая зона в бриге, не видно камер с заключенными, пропал кусок коридора.
![dreamseeker_dqfDxaNIir](https://user-images.githubusercontent.com/47484306/139442343-6ad4533d-4588-438b-a21f-8ab1539cd19d.png)
 
2. Обилие слепых зон в коридорах и комнатах общего пользования.
![dreamseeker_NdQ6dGiKkE](https://user-images.githubusercontent.com/47484306/139442474-0b3eefea-0cea-4ec3-8a5a-41bf7269b157.png)
![dreamseeker_PzROxKdjI0](https://user-images.githubusercontent.com/47484306/139442483-6418ea73-1066-4735-8487-0c026dbb7812.png)
![dreamseeker_SHJPPnrRk1](https://user-images.githubusercontent.com/47484306/139442490-7d480abc-c86a-4f50-a965-f32d25067da6.png)
![dreamseeker_anoZGPNcKa](https://user-images.githubusercontent.com/47484306/139442502-513f0094-45af-4491-9d17-14980ec194b9.png)
![dreamseeker_U2PeGMBTGI](https://user-images.githubusercontent.com/47484306/139442519-c9731b4f-9b7e-4507-9ae1-6012896d1f9e.png)
![dreamseeker_nsk6vpImuW](https://user-images.githubusercontent.com/47484306/139442532-9ea80c58-1073-411d-8a4a-0234d33cc453.png)
![dreamseeker_IwPlKopBjA](https://user-images.githubusercontent.com/47484306/139442548-cf150a01-a478-48a4-ab7e-2abd263ad5f3.png)
![dreamseeker_flASgxfwRB](https://user-images.githubusercontent.com/47484306/139442789-b3b39831-4e5e-4659-88d1-333c910a0093.png)

3. Отсутствуют камеры на шаттле шахтеров.
![dreamseeker_nAoS7Ul7S2](https://user-images.githubusercontent.com/47484306/139442680-565927d0-7b47-4ab7-a151-20265cac4672.png)

4. Не хватает камер в инженерном отделе.
![dreamseeker_OdtjyXTzgf](https://user-images.githubusercontent.com/47484306/139442728-68bcd41d-edce-47ac-b01e-64c30ad53a42.png)
![dreamseeker_wxumH5XPKk](https://user-images.githubusercontent.com/47484306/139442741-98bb22c9-91cc-44ab-9373-33db0a061c80.png)

**Comment by Artemonim** [comment]
Дубль #5644
А ещё большое количество скриншотов надо заворачивать под спойлер

**Comment by ghost** [comment]
@Artemonim , круто, конечно, но в том иссуе написана непонятная хуйня, которую молодой маппер может не понять. А еще скрины под спойлер не лезут, солнце.

**Comment by Artemonim** [comment]
<details>
    <summary>Действительно</summary>

![BOFURI - 04](https://user-images.githubusercontent.com/36363466/139471980-a6982226-27c1-4d08-809d-9ba3a3d36255.png)
![BOFURI - 10](https://user-images.githubusercontent.com/36363466/139471987-6ff00a13-0d3c-46f3-abe8-dfc85ea15da8.png)

</details>
