### ISSUE TITLE
Блоб: эммитеры не наносят урон блобу

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#6837]
Эммитеры не наносят урон обычным тайлам блоба, только ядрам и нодам

**Comment by igorsaux** [comment]
Урон должны наносить только прожектайлы эмитера или все?
Почему прожектайлы эмитера должны наносить урон а другие - нет?

**Comment by NefrNerf** [comment]
Так обычные проджектайлы ему урон наносят, пульсач, болты, а эммитер - нет или я ошибаюсь?

**Comment by igorsaux** [comment]
> Так обычные проджектайлы ему урон наносят, пульсач, болты, а эммитер - нет или я ошибаюсь?

Они наносят урон когда игроки кликают по конкретному тайлу или встречают плотный объект типа ноды или ядра.

**Comment by NefrNerf** [comment]
Было бы правильно, если он любые проджектайлы впитывал, даже без клика по тайлу.
