### ISSUE TITLE
Мозг неглухого человека в ММИ глухой

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#6850]
### Описание бага
Мозг после помещения в ММИ начал (причины или необходимые обстоятельства наверняка не известны) вести себя как глухой или бессознательный: из речи слышит только рацию, не видит эмоуты, и появляются надписи типа "You hear a gunshot!" при соответствующих действиях рядом. Зрение и способность говорить, притом, есть. Только после помещения в ФБП всё стало нормально. Очевидно, до смерти и пересадки в ММИ глухим или слепым не был.

### Воспроизведение
Со мной это произошло после того, как мне отрезали гроин, после чего вырезали мозг и сунули в ММИ. В обмороке я на момент смерти (отрезания гроина) не был, но был под наркотиками и подвергался избиению. Глухим также не был. Возможно, что-то прокнуло в тот же тик, на котором я умер, и от этого перенеслось на мозг, либо это последствия от отрезания гроина.
Если кто-нибудь сталкивался с этим явлением, пожалуйста отпишитесь и опишите обстоятельства, приключившиеся с вами до перемещения в ММИ, а также другие факторы, которые могли привести к б*гу.

### Ожидаемое поведение
Он же не должен так делать? Не знаю, если фича, пусть геймдизайн скажет, или кто там за это сейчас отвечает.

ИД раунда потерял, потому что лох. Быть может дубликат, но я не нашёл уже имеющегося иссуя, описывающего этот феномен.

**Comment by TimErmolt** [comment]
Судя по #6858 , случается вообще всегда для всех мозгов в ММИ.

Если это действительно так, то вероятно стоит сюда повесить приоритет, ибо превращает всех ММИ в слепоглухих инвалидов.

**Comment by Doster-d** [comment]
А какое сообщение выдает не помнишь?

**Comment by Doster-d** [comment]
Да, есть такое.
