### ISSUE TITLE
Удаление раундстартовых ФБП

### ISSUE THREAD

**Issue by TobyThorne** [ChaoticOnyx/OnyxBay#6867]
### Улучшение
ФБП - антисмешное детище бееклоунов, несущее своим существованием тьму в наш мир. Их появление - ошибка, за которую нам приходится расплачиваться.

### Решение
Выпилить раундстартовых ФБП. После возвращения клонирования - выпилить ФБП как таковых. Протезы, конечно же, оставить, без них сайфай тухлый.

**Comment by DarkHunter7756** [comment]
А можно более конструктивную критику синтов? 
И сколько ждать этих ваших клонирований?
И какой толк от роботеха будет, если не будет ФБП? В кого ему помещать ММИ? В боргов?

**Comment by k4m3rn** [comment]
Выходит мы полностью отказываемся от нейронитей? В чём смысл перехода на клонирование, если уже в билде есть нормальная альтернатива.

**Comment by DarkHunter7756** [comment]
"Нормальная альтернатива" сырая, не обязательная для игроков механика  с гигантским временем перевода в новое тело. Это время невозможно ускорить улучшениями. Само тело для транспортировки стоит половины бюджета карго. Чёт не очень

**Comment by k4m3rn** [comment]
> "Нормальная альтернатива" сырая, не обязательная для игроков механика с гигантским временем перевода в новое тело. Это время невозможно ускорить улучшениями. Само тело для транспортировки стоит половины бюджета карго. Чёт не очень

По другую сторону айсберга у нас пиздец имбалансное клонирование, которое питается святым духом и матами медиков. Да и не забываем, что смерть игровая не всегда должна поощряться. Тащемта усё это хуйня. Проще просто накидать ранудстартом колб с телами в мед. Ну или расширить наш прекрасный аппарат, который будет иметь дополнительную колбу, в которой и будут тела выращиваться. 
Клонирование не подразумевает под собой переноса разума носителя почти без потерь. На клонирование всем зачастую было просто похуй. Да и отыгрывать овоща половину раунда хуйня, а не идея. В итоге тебя вновь ёбнет тот же антаг по цельке к примеру.

**Comment by DarkHunter7756** [comment]
>  Да и отыгрывать овоща половину раунда хуйня, а не идея. В итоге тебя вновь ёбнет тот же антаг по цельке к примеру.

Ок, ты оставшуюся половину раунда отыгрываешь инвалидом-макакой без слотов и хп на 1 лазерный болт в грудак. Даже становление дионой более интересно в плане РП и механа

Но мы тут пришли наводить суету по поводу синтов.

**Comment by Wuattt** [comment]
разве после возвращения клонирования не будет как 4 года назад?
![image](https://user-images.githubusercontent.com/34631419/139819404-ff052b80-e8f0-41c9-852e-30da4d03318e.png)

**Comment by k4m3rn** [comment]
> разве после возвращения клонирования не будет как 4 года назад? ![image](https://user-images.githubusercontent.com/34631419/139819404-ff052b80-e8f0-41c9-852e-30da4d03318e.png)

Не будет. Это всё гомоебля с механом. Один факт клонирования уже нарушает атмосферу игры по многим причинам. Ресливерка в это действо хоть как-то, да вписывается.
