### ISSUE TITLE
Вернуть атмосферного техника в ротацию в качестве отдельной профессии

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#6871]
### Улучшение
В общем, суть довольна проста: вернуть атмосферного техника а ротацию в качестве отдельной профессии, 
 разблокировать зачеркнутый на данный момент слот.

### Решение
Понизить количество инженеров на две позиции, добавить две позиции атмосферника.

### Альтернативы
Опционально можно отредактировать меню выбора профессии, вырезав атмосферника, удалить оного как отдельно профессию, сделав просто альтернативным названием инженера.

**Comment by NefrNerf** [comment]
Не нужно, от слова совсем, инженер более обширная профессия, которая включает в себя еще и работу с атмосферой, минус
