### ISSUE TITLE
Невидимые лозы

### ISSUE THREAD

**Issue by vekotov** [ChaoticOnyx/OnyxBay#690]
### Описание бага
Невидимые лозы жрут людей.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Ждем или форсим эвент с лозами
2. Видим как космонавтики не могут с ними справится, так как часть из них невидима и бить их можно только через альт.
### Ожидаемое поведение
Лозы должны быть видимыми

### Скриншоты
Лозы невидимые...

### (Опционально) Дополнительная информация
Приложу переписку с пострадавшим
>[19:32:09] crusherz -> vlad777: Мне лень регаться там, но суть в том, что ЛОЗА УБИВАЕТ И НЕ ОТПУСКАЕТ
>[19:32:27] crusherz -> vlad777: ОНА НЕВИДИМАЯ. ТЫ НАЧИНАЕШЬ ЕЁ БИТЬ, ОНА ПРОПАДАЕТ... НО ОНА ПРОДОЛЖАЕТ ЖРАТЬ ТЕБЯ
>[19:32:45] crusherz -> vlad777: Ты не можешь двигаться и она понемногу кусает тебя...
>[19:33:07] crusherz -> vlad777: The strange plants's thorns pierce your upper body greedily!

### (Опционально) Характеристики
 - OS: мастдай
 - Версия клиента 512
 - Версия сервера Server Revision: 648528000e2f7aad01b25b01e5bff72fc2982dcb - release - 2019-08-06
 - ID игры b2G-cSxF

**Comment by Megmeehey** [comment]
#703
