### ISSUE TITLE
Дать унатхам нормальную скорость, иммунитет к гиперзину оставить.

### ISSUE THREAD

**Issue by Ershovdi** [ChaoticOnyx/OnyxBay#6975]
Сейчас унатхи двигаются со скоростью меньше человеческой, не знаю почему. Я решил это исправить в одной потнейшей игре за офицера-унатха, гиперзин просто не сработал, я всё так же был медленным. Кажется, с гиперзином так и должно быть, иначе унатхи были бы имбой. Но вот пониженная стандартная скорость просто мешает - за офицера никого нельзя догнать и приходиться использовать дальнобойное оружие, что типа нарушает всю философию унатхов и бла-бла-бла.

Решение проблемы - установка унатхам стандартной скорости. Кстати, возможно, это пришло из-за повышенного пойза? Не знаю даже.

**Comment by MACTEP-ABATAP** [comment]
Ксеносы должны страдать, в этом вся суть.

**Comment by Ershovdi** [comment]
Не, ну есть конечно второй вариант - оставить стандартную скорость, но дать возможность быстро бегать при употреблении гиперзина. Два стула.
