### ISSUE TITLE
Ломается превью

### ISSUE THREAD

**Issue by Fedortyk** [ChaoticOnyx/OnyxBay#698]
### Описание бага
При создании персонажа происходит поломка пред показа персонажа

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем редактируем персонажа
2. Открываем после меню "умения", роли" и после открываем все остальные, нажимаем там что-нибудь
3. Нажимаем обратно в "General"
4. Видим ошибку с превью

### Ожидаемое поведение
Должно было показать персонажа как он одет, вместо этого происходит отображение другого персонажа.

### Дополнительная информация
Мы можем увидеть, что на персонаже должна быть одета: "Sport shirt,  red", "Long John  Bottoms". Этого не происходит

### Скриншоты
![Проблема](https://user-images.githubusercontent.com/54238893/63224640-7d59a800-c20a-11e9-8fc2-4359c288ae14.jpg)
Спасибо!
Если баг был где-то описан, приношу мои извинения.

**Comment by Megmeehey** [comment]
@Fedortyk _Hide job gear_ под превью должно помочь
