### ISSUE TITLE
Медицинский борг (улучшенный) с блюспейс батареей не может перезарядить встроенный бинт

### ISSUE THREAD

**Issue by riuminkd** [ChaoticOnyx/OnyxBay#699]
### Описание бага
Медицинский борг (улучшенный) с блюспейс батареей не может перезарядить встроенный бинт

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем медицинского борга, вставляем улучшенный мед борг модуль и bluespace battery
2. Юзаем встроенный бинт (гель от брут дамага) пока он не кончится
3. Вуаля! Вы остались без бинта навсегда. Зарядник боргов не зарядит ваш бинт.

**Comment by TapKo4eB** [comment]
Дубликат #615

**Comment by Megmeehey** [comment]
> Дубликат #615
