### ISSUE TITLE
Маг

### ISSUE THREAD

**Issue by Pro100Nikit** [ChaoticOnyx/OnyxBay#700]
### Описание бага
Когда за мага покупаешь айтемы которые должны спавниться в шкафчиках (Scrying Orb; Mastercrafted armor set) то появляется пустой шкафчик без дверцы. (Вероятно баг связан с появление дверок у шкафчика как отдельного элемента)

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем мага
2. Открываем книжку
3. Нажимаем на Scrying Orb
4. Видим пустой ящик без дверцы

### Ожидаемое поведение
Должен появляться шкафчик с нужными айтемами

### Скриншоты
http://prntscr.com/oupgmd

### (Опционально) Дополнительная информация
Карта Эклипс. Сервер Лайт

**Comment by Megmeehey** [comment]
Get
