### ISSUE TITLE
выпилить банковский аккаунт ассистентам, пусть спавнятся с рандомным баблом в карманах

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#7001]
### Улучшение
ассистенты неполноценные сотрудники станции не имеющие конкретного закреплённого за ними рабочего места и вообще просто лохи что ищут себе счастливого будущего в попытке поднять бабла/пожрать забесплатно

соответсвенно они не проходили полную процедуру регистрации как остальные нормальные сотруднички и не должны иметь закреплённого за ними банковского аккаунта

### Решение
спавним ассистентов без зареганного банковского аккаунта и кладём рандомсумму кредитсов в карман

### Очевидный профит
наличка начинает циркулировать по станции
менее забитый список банковских счетов

**Comment by DarkHunter7756** [comment]
Я бы еще добавил им какой-нибудь херовый кошелек. Что думаете?

**Comment by No-Tips** [comment]
А зачем херовый, если есть обычные кошельки.

**Comment by DarkHunter7756** [comment]
> А зачем херовый, если есть обычные кошельки.

Потому что обычный есть в лодауте )

**Comment by TapKo4eB** [comment]
нахуй кошелёк нужен лишнее место в инвентаре занимает
тупо бабло в слот кармана положить и проблем нет

**Comment by DarkHunter7756** [comment]
Что насчет остальных проф? Мб и им ввести допустим 30-60% текущей зарплаты в виде нала?

**Comment by TapKo4eB** [comment]
нахуя если всё можно оплачивать через пда/картой привязанных к счету
представь если бы ты ИРЛ мог оплачивать абсолютно всё что угодно своей банковской картой, захер тебе тогда вообще при себе наличку держать?

**Comment by DarkHunter7756** [comment]
> нахуя если всё можно оплачивать через пда/картой привязанных к счету представь если бы ты ИРЛ мог оплачивать абсолютно всё что угодно своей банковской картой, захер тебе тогда вообще при себе наличку держать?

Абсолютно всем на станции похер на всякие устройства перевода денег с акка на акк. А товарообмен производится не только с помощью вендоматов. Вот допустим какой-нибудь химик решил продавать за наличку реагенты. Покупателям (всем) придется идти к АТМ, списывать деньги, идти обратно. И все это учитывая очередь, которая нередко появляется.

**Comment by TapKo4eB** [comment]
ну и пусть идут к банкомату снимают, чё сложного?
я понимаю если бы он один на станции стоял, но они то на каждом углу считай

**Comment by DarkHunter7756** [comment]
> ну и пусть идут к банкомату снимают, чё сложного?

Покажи мне человека, которому не влом этим заниматься. Я лично видел лишь раздражение у покупателей. Никому не нравится, когда их время тратят на бесполезную в текущих рамках херню.

**Comment by TapKo4eB** [comment]
я
не щитаю это настолько важной проблемой пройти два шага до ближайшего атм
плюс покупают за наличку особые приколы у химиков и у других исключительно ассистенты и у них как раз деньги все будут храниться на руках

**Comment by DarkHunter7756** [comment]
ну хз. Если нашей задачей является 
> наличка начинает циркулировать по станции

То лучше бы сделать ее всегда под рукой, а не в АТМ, который, хоть и находится в "двух шагах", является затягиванием процесса оплаты

**Comment by DarkHunter7756** [comment]
А вообще, лучше бы не париться с этой наличкой, а ввести полноценную полу-автоматическую торговлю (#3576) с помощью карточек. И людям удобнее. И деньги зарабатывать быстрее. И тратить их есть куда

**Comment by TapKo4eB** [comment]
>задачей является

не путай результат с целью, я это как задачу не дефайнил, это лишь вытекающее из этого
7001 был запилен лишь для того чтобы ввести разнообразие в жызнь ассистентов и ещё раз подчеркнуть что они лошпеды

**Comment by DarkHunter7756** [comment]
Окей. Как тебе угодно.
