### ISSUE TITLE
Баг при заполнении книги

### ISSUE THREAD

**Issue by 13Minor** [ChaoticOnyx/OnyxBay#701]
### Описание бага
При заполнении книги ручкой через меню Контент, буква "я" преобразуется в "ÿ", причем "Я" пишется нормально.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем ручку
2. Открываем ей книгу
3. Нажимаем Content
4. Пишем символ "я"
4. Видим ошибку в заполненной книге в место "я" будет "ÿ"

**Comment by kokokobold** [comment]
Я думаю, что это пофиксилось с переходом на 513. Да, «я» всё ещё не работает в книгах, но там вообще все буквы не работают.  В теории, если пофиксить #2398, то всё будет хорошо.
