### ISSUE TITLE
Возможность открытия порталов bluespace rift generator по любому входящему REF маячка

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7013]
Обычно платы bluespace rift generator и Teleporter Locator работают в связке для телепортации на любые, даже не доступные для визуального контакта, маячки. Но в bluespace rift generator ввод не какой-то уникальной переменной, а простого REF. Следовательно он, по понятной логике, должен работать и с иными средствами определения REF по типу сенсоров и локаторов. Отсканировал REF - телепортировался на отсканированный маяк. 

В общем, предлагаю запилить данную возможность.

Сие улучшение упростит использование модифицированных хенд теле устройств, даст им больше возможностей.

**Comment by Doster-d** [comment]
Он не по маячкам ходит, а по сути по консоли, которая связана с генератором портала.
Можешь указать консоль Teleporter Control Console и телепортироваться, то что ты предлагаешь, это улучшение

**Comment by DarkHunter7756** [comment]
Окей. Сделаем фичу...
