### ISSUE TITLE
Переработка ксеносов, добавление особенностей операций над Таярами

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#7028]
### Улучшение
Немного меняем взаимодействие Таяр и хирургии.

### Решение
1. Наркотические вещества а также болеутоляющие действуют на котов сильнее чем на людей
2. Под действием любых наркотиков начиная от табака у котов могут появится галюцинации и дефекты речи
3. Ментол также должен вызывать галлюцинации и опьянение

**Comment by ghost** [comment]
Круто, когда апрув?

**Comment by DarkHunter7756** [comment]
Усложнение ради усложнения. Просто еще одно действие в алгоритм для медботов

Проработай какие-нибудь дополнительные механики ножницам, ибо срезать одежду ну вообще не требуется. Операционный стол и так всю одежду снимает

**Comment by NefrNerf** [comment]
Операции могут быть не только на мед столе, потом подумаем про стрижку, это не один иссуй про ксеносов, дальше будут механики

**Comment by NefrNerf** [comment]
Изменил описание
