### ISSUE TITLE
Переработка ксеносов, добавление особенностей операций над Скреллами

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#7030]
### Улучшение
Немного меняем взаимодействие Скреллов и хирургии.

### Решение
1. Скреллам нельзя переливать человеческую кровь, в случае переливание происходит иноксикация и заражение. Нанокровь не в счет.
2. Из-за биологических особенностей, в биологии реагенты через крио усваиваются хуже.
3. Таблетки усваиваются хуже чем введения лекарств через шприцы.

**Comment by DarkHunter7756** [comment]
Первое и так имеется.
