### ISSUE TITLE
Переработка ксеносов, влияние человеческих лекарств на Ксеносов

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#7031]
### Улучшение
Усложняем лечение ксеносов при помощи добавления еще одного препарата.

### Решение
Так как биология ксеносов отличается от человеческой, они не могут в полной мере пользоваться лекарствами людей. Применения обычных медикаментов на 30% менее эффективно чем для людей. Ввести для каждой расы отдельный препарат который если находиться в организме ксеноса позволяет медикаментам работать на 100% эффективности.

**Comment by Shootnik01** [comment]
Неплохо, кста
