### ISSUE TITLE
Механики капеллана

### ISSUE THREAD

**Issue by IPKv** [ChaoticOnyx/OnyxBay#704]
Сейчас отсутствуют механические фишки капеллана при определённых режимах. Такие как:

- Святая вода не лечит при употреблении 
- Святая вода не льётся на пол из бутылки
- Святая вода не создаёт приграду магу при проливании её на пол (можно ещё сделать это культу) 
- Нульрод не имеет функционала вообще. 
- Привинтить роду возможность снимать рольку культа
- Делать нульродом воду святой 
- Библия при ударе не лечит, не наносит брейндамаг
- Библия не наносит фаердамаг культистам

Это основные фишки с бей12 (?), которые необходимы капеллану, чтобы он перестал быть бесполезным.

**Comment by Mo3goed** [comment]
Нуль род, должен конвертить культистов обратно в персонал.

**Comment by Epicus7** [comment]
Это не с бей12, а с ТГ скорее всего. Слишком много пунктов для одного иссуя, такое надо разбивать на несколько.

В общем, можно конечно так пилить, но если кто-то разобьет - будет круто.

Сложность поставил из-за объемов. Зачем тут был пониженный приоритет - без понятия.
