### ISSUE TITLE
Ввод нового ивента: похолодание

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#7042]
Необходимо ввести новый ивент при котором температура станции опускается до -40 градусов, такая температура держится 20-30 минут. По окончанию отведенного времени, температура возвращается в норму.

**Comment by DarkHunter7756** [comment]
Имеется в #2224
![image](https://user-images.githubusercontent.com/76823962/143620314-931e42bd-2730-49f1-8392-8d043e434fff.png)
Закрываем?

**Comment by NefrNerf** [comment]
Линкаем, так сказать декомпозируем
