### ISSUE TITLE
Ore Redemption Board

### ISSUE THREAD

**Issue by MrLooneyDG** [ChaoticOnyx/OnyxBay#705]
**Описание by Голиаф:**
Добавить возможность сделать плату переработчика руды (Ore Redemption) в РнД, чтобы если от взрыва потеряется изначальная, то её можно было бы заменить
_**Описание by Epicus:**_

> Добавить плату переработчика руды (Ore Redemption), чтобы его можно было создать с нуля.

_Старое описание:_

> Вообщем, суть в том что плату для переработчика руды  - Ore Redemption Board, невозможно изготовить, ну или она где-то запрятана глубоко. Запасных плат так же не нашел.

**Comment by Voldirs** [comment]
А она для чего вообще? Может её вообще в коде нет?

**Comment by MrLooneyDG** [comment]
Она для переработчика руды, который у шахтеров стоит. Если его взорвали или еще чего, то уже никак не восстановить.

**Comment by Voldirs** [comment]
А, понял. На этом билде эта машинерия вроде не разбирается.

**Comment by MrLooneyDG** [comment]
Ну не знаю, тогда это не баг, а предложение улучшения, не знаю как сменить тег.

**Comment by Epicus7** [comment]
Перекинул теги, переписал первый пост

**Comment by kreeperHLC** [comment]
Снова переписал первый пост про причине незнания старого переписывателя

**Comment by Pl3aseJust3ndMySuffering** [comment]
Беру.
