### ISSUE TITLE
Тазеры, борги, ФБП и урон электричеством

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#7058]
### Улучшение
Есть проблема в отсутствии дистанционных не летальных способов нейтрализации ФБП и боргов.

### Решение
Добавить продвинутому тайзеру(мочелуч) - урон электричеством

Принцип работы продвинутого тайзера:
- На людей работает так же как и обычный тайзер, но кроме этого есть шанс нанести бёрн и шок урон.
- Боргов боевой тайзер разряжает и наносит урон по проводке.
- При попадании в протез, шанс вывести его на короткое время из строя и нанести урон.Э
- Также разряжает РИГи и мехов.
 
 Шаги для актуализации:
 1. Добавить вместо ионных пистолетов 3 продвинутых тайзера в оружейную СБ
 2. Стан винтовка становится скорее боевым оружием, с нанесением высокого электрического урона по протезам и боргам, но сильно теряет стан свойства.
 
 ### Альтернатива
 
 Делаем так, чтобы все тайзеры наносили электрический урон и отжирали заряд и здоровье у железных.

**Comment by TimErmolt** [comment]
Но ионки же и так разряжают батареи боргов и наносят им немного бёрн-урона. Полного аккумулятора (6, вроде, выстрелов) ионного пистолета как раз хватает чтобы разрядить полностью исправного борга до состояния отключки, где у него чёрный экран, и он не может ничего делать, но восстановить его ещё можно без особо сложных манипуляций.

Взаимодействие с РИГами аналогично -- ЭМИ разряжает батарею и случайным образом вышибает модули. Ещё визор (секьюрити-очки, мезонки, термалы и т.д.) начинает сбоить, если он включён.

С ФБПшками-протезами и мехами другое дело.

Насчёт мехов не знаю, как именно ионка с ними взаимодействует, кроме нанесения урона и, возможно, разрядки батареи. Здесь мех не игрок -- ничто не мешает накинуться на вылезающего из обломков пилота и скрутить его -- поэтому его уничтожение, как правило, не настолько важно.

А вот моментальное уничтожение протезов и как следствие ваншот ФБП от АОЕ-эффекта ЭМИ -- сомнительная вещь. Что-то сделать по этому поводу стоит, но нужно ли ради этого впиливать новый механ, в том числе частично то, что уже делают ионки, для продвинутых тазеров, заменяя ими нормально переносимые маленькие ионки (винтовки можно носить только на спине или на броне, а пистолеты -- как тазеры) в арсенале, или лучше уже имеющиеся ионки твикнуть, заодно заменив эти самые ваншоты, вокруг которых периодически образуется недовольство (#2825, #4884, а ведь ваншотает не только выстрел из ионки, а любое ЭМИ, в том числе от вируса и метеоров), на несмертельную нейтрализацию.
Например, чтобы ионки не уничтожали протезы, а временно отключали их, нанося небольшой урон ожогами тоже (слишком много урона приведёт к гибу, очевидно). Тогда в случае с ФБП это будет полный паралич, во время которого можно или добить, или скрутить и задержать/похитить, или оттащить в безопасное место.
По сути, не слишком много меняется -- ЭМИ всё ещё специализированно контрит кремниевых ублюдков, -- но случаи его применения дают больше возможностей для развития ситуации, кроме бездумного ваншота игрока в госты. Заодно не придётся впиливать этот механ продвинутым тазерам, которые до сего иссуя вообще никакого отношения к данной теме не имели.

**Comment by DarkHunter7756** [comment]
>Насчёт мехов не знаю, как именно ионка с ними взаимодействует, кроме нанесения урона и, возможно, разрядки батареи.

Мех начинает искрить до потери ВСЕГО здоровья от любого достаточного ЭМИ. Это долгий процесс, не сильно мешающий убивающему тебя меху. Сомнительно.

**Comment by DarkHunter7756** [comment]
Насчет протезов и ФБП. ФБП страдают от эффекта паралича, накладываемого тазерами. Им требуется не сильно больше попаданий, чтобы упасть. 

Я не вижу в данном иссуе смысла, так как проблема уже решена в рамках игрового контента
