### ISSUE TITLE
Ввести возможность квине использовать консоли вызов шаттлов.

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#7059]
### Улучшение
Если они каким-то образом появились на астероиде алиенов ждет мало чего хорошего, также если люди спрятались на астероиде, до них только по космосу лететь

### Решение
Дать доступ Квине к консоли управления.

### (Опционально) Альтернативы
Дать ей абилку на вызов шаттла.

**Comment by DarkHunter7756** [comment]
А возможно ли настроить рандом перехода с Z левела астероида на станцию и обратно для чужих с 100% шансами?

Вылетел в космос со станции - прилетел на астероид. Вылетел с астероида - прилетел на станцию.

Потому что использование алиенами технологий более кринжовое, чем тоже самое увидеть от мага
