### ISSUE TITLE
Улучшение создания книг

### ISSUE THREAD

**Issue by 13Minor** [ChaoticOnyx/OnyxBay#706]
### Улучшение
Книга создается из 1 листа бумаги, при редактировании которого объем символов сильно ограничен, но возможно использовать коды для редактирования текста (курсив, списки, подписи и т.п. ). Если добавлять текст в уже созданную книгу через меню Content то можно добавлять огромное количество символов (я не смог найти ограничение), но при этом любые коды не работают и просто записываются как текст, а весь добавленный текст добавляется блоками один за другим.
Предлагаю несколько вариантов решения.

### Решение
Включить работу кодов редактирования текста при заполнении книги через команду Content.

### (Опционально) Альтернативы
1- Убрать ограничение на количество символов у обычного листа бумаги.
2- Дать возможность переплетчику книг создавать книги из нескольких скрепленных листов (что возможно самое логичное и правильное создание книги, ведь она не делается из 1 листа?)

### (Опционально) Дополнительная информация
В будущем если одно из выше перечисленных решений будет принято, то было бы желательно перелопатить архив книг сервера, так как многие книги раздроблены на 5-6, 10+ частей и их можно свести к 1 книги дабы сократить количество позиций в списке библиотеки.

**Comment by Cinericius** [comment]
#1233 дубли подкатили
