### ISSUE TITLE
Спрайт кистей и стоп, собранных на станке у роботиста

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#708]
### Описание бага
Нету спрайтов протезных кистей и стоп, которые собираются у роботиста. Эти кисти и стопы используются для сборки синтетов

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Открываем станок протезов у роботиста в операционной
2. Нажимаем на right hand/left hand/right foot/left foot
3. Станок делает их, сообщая об этом, но сами стопы и кисти можно подобрать только через правую кнопку мыши
4. Если их положить в рюкзак, то у них все равно не будет спрайтов , поэтому их невозможно оттуда достать

### Ожидаемое поведение
У них должны быть спрайты

**Comment by Fox231** [comment]
Там не только станок роботиста. Органические конечности из биопринтера так же невидимые.
