### ISSUE TITLE
Заказы ЦК reborn

### ISSUE THREAD

**Issue by vekotov** [ChaoticOnyx/OnyxBay#7095]
### Тред посвящается проклятой фиче заказов с ЦК
Если кратко, для тех кто уже успел забыть, то суть фичи в генерации заказов с ЦК, состоящих в отправке чего-то или кого-то на шаттле, с получением за этой награды.
Тот самый проклятый и до сих пор не доделанный ПР: https://github.com/ChaoticOnyx/OnyxBay/pull/1046

В данный момент планирую сделать заказы следующих категорий для ЦК:

+ Civilian
Сюда входит еда (сложная, требующая либо редких ингредиентов (мясо карпа например), или же сама по себе сложная в создании (см. noel)
Также сюда входят сложные напитки, требующие несколько реакций для их приготовления
Также сюда входят картины (никак не проверяются, просто проверка что они finalized. Оплата рандомная (допустим от 0 до 100 CP)

+ Research
Сюда входят всякие сложные вещи из RnD и робототехники (включая мехи), а также (возможно?) лимитки.

+ Xenoscience
Сюда входят жопки слаймов, растения с определенными характеристиками (которые можно сделать из стандартного набора за несколько модификаций генома), а также ксеноархеологические артефакты (как мелкие обычные, так и аномальные большие)

В этот тред призываются геймдизайнеры для перерасмотра фичи заказов с ЦК, и утверждения того, что было бы неплохо добавить в экспорт-контракты.

**Comment by vekotov** [comment]
Также есть следующие идеи которые могут пригодится в инструментарии при создании каких то интересных комбинаций:
+ Приоритет при генерации заказа (например заказы с приоритетом 2 будут в 2 раза чаще попадаться, чем заказы с приоритетом 1)
+ Возможности при емаге (отправка на ЦК трупов конкретных людей с оплатой за них, каких нибудь штанин хопа, больше если честно идей нет)
+ Награда в виде вещей (после выполнения заказа в следующем шаттле с ЦК прилетит коробка/ящик с наградой, можно награждать например всякими рарными вещами, которые не достать обычным путем)

**Comment by vekotov** [comment]
@Doster-d предложил ещё интегралки продавать, но я слабо представляю как их чекать на то, что они допустим что то делают, чтобы это не превратилось просто в игру "напечатай детальки".

**Comment by Shootnik01** [comment]
При емаге, кстати, есть предложение вывозить (отмывать) бабос. Так и ценность у денег появится, и больше интерфейс для взаимодействия с карго.

**Comment by Shootnik01** [comment]
По ценности 1:10, или больше

**Comment by kreeperHLC** [comment]
ПР в итоге так и не реализовали, так что этот исууй уходит отсюда
