### ISSUE TITLE
Наноботы

### ISSUE THREAD

**Issue by SIRoNAME** [ChaoticOnyx/OnyxBay#711]
По идее тут и объяснять нечего (кто знает о них).
С их помощью можно заменить "умных и знающих своё дело" медиков, так же дать некие плюхи СБ и капитану (как пример реген) и даёт ветку развития для РнД.
Как по мне вполне полезно.

**Comment by Mo3goed** [comment]
Наноботы уже давно впилены в сску, и задача у них совсем другая, она людей в боргов превращает.

**Comment by SIRoNAME** [comment]
Ну так лучше, чем сдохнуть от тупых медов (если такие есть).

**Comment by SIRoNAME** [comment]
В любом случае лучше будет, чем сдохнуть от тупых медов (если такие будут).

**Comment by LLIkolnik** [comment]
Нет.

**Comment by SIRoNAME** [comment]
Ну ок
