### ISSUE TITLE
Краш

### ISSUE THREAD

**Issue by Shadugr** [ChaoticOnyx/OnyxBay#714]
### Описание бага
Краш сервера при попытке зайди в Options в Player Panel

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Хостим локальный сервер
2. Запускаем раунд на сервере
3. Через админку заходим в Player Panel
4. Жмем крестик напротив игрока в стобике Options

### Ожидаемое поведение
Опции игрока не открываются, сервер тупит пару секунд и крашится без ошибок

### (Опционально) Характеристики
 - OS: Windows 10
 - Версия клиента 512.1478
 - Версия сервера Revision Unknown (Версия клиента 512)
 - ID игры b2S-ciu1

**Comment by Megmeehey** [comment]
[Fix](https://github.com/ChaoticOnyx/OnyxBay/commit/38902d3bf6d6c0241721db30a423c5bb8feb58e3)
