### ISSUE TITLE
Ускорить работу машинерии вирусолога

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7142]
90% машинерии вирусолога работают крайне медленно. 

Чтобы извлечь симптом (довольно обычная для вирусолога работа) нужно ПОДОЖДАТЬ минуту-две.  Потом еще 30 секунд ждем сохранение на диск. Мы играем в симулятор Ждуна или песочницу про ЧС? Полторы минуты просто сидеть в отделе и ничего не делать. 

Хочешь вакцину? Жди 30 секунд, пока выделится из крови вирус. Потом еще минуту, пока он созреет. Еще минуту делается вакцина. Итого 2:30 похеренного времени

Собственно, что я хочу. Либо ускорение этих самых процессов в 2-3 раза. Либо возможность улучшать комплектующими РнД и/или строить машинерию самостоятельно с закономерным ускорением производство от качества или количества машин.

**Comment by TobyThorne** [comment]
согласен с автором, вакцина за две с половиной минуты - это не очень

нужно продлить до 15 минут с шансом на фейл в конце

**Comment by DarkHunter7756** [comment]
Доеб принят. Но все это время ты ничего не делаешь и просто ждешь. Запилить бы возможность как-то поучаствовать в создании сей панацеи. А не два клика и готово

**Comment by DarkHunter7756** [comment]
Реализовано в каком-то там ПРе про постройку новых машинок вирусологу
