### ISSUE TITLE
Пофикшенные камеры в коридорах Фронтира теперь не видны совсем

### ISSUE THREAD

**Issue by Bleckhausen** [ChaoticOnyx/OnyxBay#7154]
### Описание бага
Три камеры вылечились, но остальные имеют только две сети null. 

### Скриншоты

Те камеры, которые стали работать нормально.
![image](https://user-images.githubusercontent.com/95778514/145732445-89474a5e-5c91-47de-bf4e-ff602b0b8473.png)

Нерабочие камеры.
![image](https://user-images.githubusercontent.com/95778514/145732466-e797fd28-16bf-4f41-9c62-dc21f0556db3.png)

Список всех камер(до появления бага).
![DWAjJUCncK](https://user-images.githubusercontent.com/95778514/145732553-8cba6a86-6904-4264-9652-0aa27b8fc264.png)

**Comment by Terydd** [comment]
Все, или как минимум большинство этих камер расположены в первых двух вкладках и вполне работают. Считаю, что не воспроизводится
![image](https://user-images.githubusercontent.com/91453615/173440968-33bb11de-aa64-441c-911f-75af2f4140ad.png)
