### ISSUE TITLE
ИИ нужно больше власти!

### ISSUE THREAD

**Issue by AsanteFenix** [ChaoticOnyx/OnyxBay#718]
### Улучшение
На данный момент роль ИИ в раунде довольно уныла. По факту, все доступные инструменты ограничиваются клацаньем дверей, огромным (но уязвимым) обзором и доступом к любой видимой электронике. Да, я понимаю, что у игрока за ИИ больше упор идёт на РП, но тем не менее.
Сделайте из ИИ играбельную роль, вместо большого и толстого ПИИ для всей станции сразу.

### Решение
Прикрутить больше возможностей. Возможность сесть за полноценного борга, а не только бота. Больше турелей по станции для расширения возможностей обороны. Персональный спасательный под в подвальчике для капитана и ХоСа. Отдельный фабрикатор боргов и ботов под ядром. Кнопка для "очистки" коридоров станции путём блокировки всех дверей отсеков и открытия шлюзов в открытый космос одной кнопкой, через одну минуту, с автоматическим предупреждением персонала. Инструмент для установки камер в техах и гетто (инженерам и боргам). Малф отключен, часть его фич сделать доступным обычному ИИ. И много чего еще придумать можно, были бы руки.

### (Опционально) Альтернативы
Альтернативой является только увеличение задач антагов по взаимодействию (не летальных для последнего) с ИИ, но так как инструментов у ИИ мало, то ничего противопоставить он им не сможет. Да и взаимодействовать получится только тем же самым открыванием дверей.

### (Опционально) Дополнительная информация
Практически всё предложенное можно осуществить обычным маппингом и/или скриптом без добавления новых материалов, звуков и прочего.

**Comment by Voldirs** [comment]
То есть ты предлагаешь сделать его ещё более невыносимым и грифозным? Фабрикатор боргов чтобы сразу послать нахуй гробототехников? Одна кнопочка чтобы разгерметизировать к хуям всё? Камеры и так можно ставить, только это сложнее чем "нажать одну кнопку".

>большого и толстого ПИИ для всей станции
В этом и его суть как раз

Всё хуйня, однокнопочные дауны не нужны

**Comment by AsanteFenix** [comment]
> То есть ты предлагаешь сделать его ещё более невыносимым и грифозным?
Малфа как режим вырезали, так что насчёт грифозным, это уже к игроку вопросы.

> Фабрикатор боргов чтобы сразу послать нахуй гробототехников? 
А что мешает включить в этот момент обслуживание роботехами? Дополнительный вариант для антага поднасрать ИИ, если получит доступ замаскировавшись под роботеха или будучи им.

> Одна кнопочка чтобы разгерметизировать к хуям всё?
Опять же, кто запрещает подвязывать эту возможность к живому персоналу или еще как-то ограничить? Опять же, антагам будет интерес взломать ИИ, для доступа к такому.

> Камеры и так можно ставить, только это сложнее чем "нажать одну кнопку"
Инженерам как правило похеру на всё, что происходит снаружи отсека. Так что про такую уже существующую возможность я не знал.

> В этом и его суть как раз
Быть бесполезным куском металла, который жмакает двери и может только орать в каналы. Ну или забить болт на всё и летать дроном.

> Всё хуйня, однокнопочные дауны не нужны
Мсье "Мне нравится это говно и я буду жрать только его" удаляется, так и не принеся ничего полезного в дискуссию.

**Comment by Voldirs** [comment]
>Малфа как режим вырезали, так что насчёт грифозным, это уже к игроку вопросы.

Триторка всё так же может выпасть ИИшке, да. Лучше бы предложил идеи, что бы такого с малфом хорошего сделать чтобы его вернули.

>А что мешает включить в этот момент обслуживание роботехами? Дополнительный вариант для антага поднасрать ИИ, если получит доступ замаскировавшись под роботеха или будучи им.

А что мешает в текущей ситуации, когда робототехники и так могут собрать корпус для киборга? Это и так часть их работы.

>Опять же, кто запрещает подвязывать эту возможность к живому персоналу или еще как-то ограничить? Опять же, антагам будет интерес взломать ИИ, для доступа к такому.

Тем что этот процесс уже есть, только он посложнее чем просто нажать одну кнопку.

>Инженерам как правило похеру на всё, что происходит снаружи отсека. Так что про такую уже существующую возможность я не знал.

Это уже проблема игроков.

>Быть бесполезным куском металла, который жмакает двери и может только орать в каналы. Ну или забить болт на всё и летать дроном.

Хз, я помню много случаев когда это не так и ИИ при этом не антаг. Так что проблема игроков.

>Мсье "Мне нравится это говно и я буду жрать только его" удаляется, так и не принеся ничего полезного в дискуссию.

О, а разве сеньор "Поиграл за ИИ пару раз и взгрустнул потому что выпиливать людей слооожна, давайте сделаем одну кнопку для этого дела" предложил что-то толковое?

**Comment by AsanteFenix** [comment]
> Триторка всё так же может выпасть ИИшке, да. Лучше бы предложил идеи, что бы такого с малфом хорошего сделать чтобы его вернули.

Если бы я смог поиграть за малфа, сказал бы, но режим вырезан. Если не насовсем, попробую спросить педалей.

> А что мешает в текущей ситуации, когда робототехники и так могут собрать корпус для киборга? Это и так часть их работы.

Так как подразумевается беггинер, ибо как ИИ на мейне в вайтлисте, то мешает скилл роботехов. Там порой просто ремонт борга превращается в проблему.

> Опять же, кто запрещает подвязывать эту возможность к живому персоналу или еще как-то ограничить? Опять же, антагам будет интерес взломать ИИ, для доступа к такому.
Тем что этот процесс уже есть, только он посложнее чем просто нажать одну кнопку.

Тем не менее, было бы неплохо повысить интерес антагов к ядру ИИ, а не штанам капитана. Цель более вменяемая.

> Быть бесполезным куском металла, который жмакает двери и может только орать в каналы. Ну или забить болт на всё и летать дроном.
Хз, я помню много случаев когда это не так и ИИ при этом не антаг. Так что проблема игроков.

Это видимо просто мастер по жмаканию дверей играл сидел. ИИ слишком зависит от понимания экипажа, что с ним можно взаимодействовать. 

> О, а разве сеньор "Поиграл за ИИ пару раз и взгрустнул потому что выпиливать людей слооожна, давайте сделаем одну кнопку для этого дела" предложил что-то толковое?

Вместо того, чтобы трясти мудями и показывать уровень интеллекта, лучше бы сразу зашёл с аргументов, а не воплей "ВЫ ВСЕ ГОВНО"

**Comment by kreeperHLC** [comment]
У ИИшки и так она есть, куда ему ещё.
