### ISSUE TITLE
Новое холодное оружие

### ISSUE THREAD

**Issue by SuicideLoser** [ChaoticOnyx/OnyxBay#725]
### Улучшение
Я могу скрафтить зип ган, гаусс пушку, самодельный дробовик, арбалет, но при всем при этом выбор холодного оружия это пара ножичков и игрушечные мечи которые можно найти в гетто. В лодауте есть кобура для мачете и она не имеет смысла без самого мачете, я предлагаю возможность печатать его на автолате из алюминия и стали. Я чувствую себя приниженным унати воином из Алмазных пиков когда не могу вооружиться хорошим клинком. 

### (Опционально) Альтернативы
Или же вернуть архивный крафт меча - склеивание сваркой двух лезвий.

### (Опционально) Дополнительная информация
Вот пару спрайтов и звуков
[Machete.zip](https://github.com/ChaoticOnyx/OnyxBay/files/3562552/Machete.zip)

**Comment by Voldirs** [comment]
Я докинул мачете торгашам в ассортимент, но вообще да, неплохо было бы иметь способ получить эту штуку и другим способом. Желательно не из говна и палок.

**Comment by Voldirs** [comment]
Хотя внезапно у мачете такие же статки как и у топорика, просто спрайт другой. Лучше сначала это как-то подправить чтобы была разница между ними

**Comment by MrPersival** [comment]
Попробуй сделать. Только бы не заговнокодить.

**Comment by MrPersival** [comment]
Окей, теперь её можно сделать на автолате. Взломаном, естественно. Планирую повысить статуи относительно топорика. Что ещё?

**Comment by LLIkolnik** [comment]
Сделай крафт.

**Comment by Epicus7** [comment]
Нужно больше конкретики чо тут делать.
