### ISSUE TITLE
Странный баг с фотографиями

### ISSUE THREAD

**Issue by danxnader** [ChaoticOnyx/OnyxBay#734]
### Описание бага
На фотографии проявились предметы, которых не было. Так-же другой пол.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Приходим дормы с фотоаппаратом.
2. Шёлкаем.
3. Видим баг.

### Ожидаемое поведение
Этого не должно было проихойти.

### Скриншоты
![image](https://user-images.githubusercontent.com/55185311/64684657-2ef89b80-d48e-11e9-8422-f18f80c70691.png)

### (Опционально) Характеристики
 - OS: Windows 10
 - Версия клиента последняя на данный момент
 - Версия сервера 722827649187b16b9c8e8f1f19bfca12b2160763
 - ID игры b3b-a7Xh

**Comment by Epicus7** [comment]
Фотоаппарат работает на костылях и велосипедах - нужно разбираться.

**Comment by Animesku** [comment]
Там отчасти починено, вроде

**Comment by Epicus7** [comment]
Тогда надо посмотреть и проверить статус на сегодня.

**Comment by MemoryDreams** [comment]
По-моему, все замечательно и ничего менять не надо.

**Comment by HonkyDonky** [comment]
Фича.
