### ISSUE TITLE
Возможность изготовления золотого кубка-черепа

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7357]
Соединение кубка-черепа (или простого черепа) и 2 слитков золота создают золотой кубок-череп
![image](https://user-images.githubusercontent.com/76823962/148510372-f9f24146-8f61-4e7b-baf6-e3bacd55d75f.png)
Больше черепов трону черепов

**Этот иссуй был поддержан более чем 17 лайками.**

**Comment by Doster-d** [comment]
Разве уже нет? https://github.com/ChaoticOnyx/OnyxBay/blob/dev/code/modules/organs/external/head.dm#L231

**Comment by DarkHunter7756** [comment]
Принял, понял, обработал
