### ISSUE TITLE
Улучшаемость машинерии повара

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7360]
Спрос на жрачку поднялся. Время увеличивать предложение.

`Микроволновка:`
1 уровень. Базовая микроволновка.
2 уровень. Ускорение процесса готовки. 
3 уровень. Существенное ускорение готовки. При провале рецепта падает сгоревшее нечто, не имеющее в составе токсинов.
4 (блюспейс) уровень. При провале рецепта сгоревшее нечто получает дополнительные нутрименты.

`Печь, фринюрница, гриль:`
1 уровень. Базовая машинерия.
2 уровень. Ускорение процесса готовки.
3 уровень. Существенное ускорение готовки. Время до сгорания продуктов увеличено.
4 (блюспейс) уровень. Продукты не могут сгореть. Коэффициенты добавляемых реагентов при обработке увеличены.

`Сахарная машина, машина для хлопьев` - ускорение работы

**Этот иссуй был поддержан более чем 25 лайками.**

**Comment by Shootnik01** [comment]
Нот бэд
