### ISSUE TITLE
Ресурсная фурнитура

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7361]
Хочу алмазный трон, золотой унитаз, урановый гроб, плазменный ящик и серебряный шкаф. Или что-то подобное. В общем возможность показать, насколько ты богатый 😎 . Почему бы и нет? А то довольствуемся только алмазной ложкой и платиновой дверью.

**Этот иссуй был поддержан более чем 23 лайками.**

**Comment by kreeperHLC** [comment]
Нужны спрайты

**Comment by DarkHunter7756** [comment]
Спасибо, капитан-очевидность 
![image](https://user-images.githubusercontent.com/76823962/154026813-c528daf7-bd8d-48b9-834d-ce966a336a5f.png)
