### ISSUE TITLE
Возможность создавать ресурсную плитку.

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7362]
Каюта квартирмейстера явно нуждается в золотой плитке. Ну или плитке из какого-нибудь другого ресурса 😼 

**Этот иссуй был поддержан более чем 21 лайками.**

**Comment by kreeperHLC** [comment]
Чего, из слитков можно делать ресурсную плитку

**Comment by DarkHunter7756** [comment]
а? Перепроверю конечно, но вроде нельзя из условного золота сделать плитку
