### ISSUE TITLE
Кастомизируемая панель команд (дополнительные вкладки)

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7365]
Предлагаю ввести функцию создания и редактирования дополнительных вкладок на панели кнопок чата. 
### Создание новой вкладки
Функция активируется путем нажатия кнопки "+" на панели вкладок. 
[Альтернатива: контекстное меню лаунчера/вкладка Preferences или OOC]
![image](https://user-images.githubusercontent.com/76823962/148609694-1241f4df-bc85-4ff2-8d2a-ca25fd6052dc.png)
### Редактирование
После открывается панель редактирования вкладки. Здесь возможно ввести новые команды и изменить имя вкладки на предпочитаемое вам.
![image](https://user-images.githubusercontent.com/76823962/148609255-abd6e39b-2702-49ec-aadb-7e9a3a608ac5.png)
Редактирование команд производится на манер макросов. То есть, для создания команды, вызывающей сейлог, необходимо вписать в команду `say "ваш текст"`. Наименование команды на панели можно менять из этого же окна. 
![image](https://user-images.githubusercontent.com/76823962/148610561-6011fddf-9346-461b-86dc-7b20580ef550.png)
После выхода из окна на панели появляются ваши команды+команда setting, открывающая закрытое окно для редактирования вкладки.
![image](https://user-images.githubusercontent.com/76823962/148609975-a93ace44-125a-4ce5-b86d-8fb160a7be87.png)

Всего можно создать до 5 дополнительных вкладок. Вкладка "+"  не пропадает с экрана до создания последней, пятой вкладки. Удаление вкладок производится путем оставления поля названия вкладки пустым

Внедрение подобного меню позволит игрокам самостоятельно создавать свои эмоут панели, робаст панели, собирать в одном месте часто используемые команды и удобно управлять ими.

**Comment by Zert0X** [comment]
Фактически возможно, но 
![изображение](https://user-images.githubusercontent.com/42303535/148613809-3d18c613-3b6d-48de-af24-864f13c34f2f.png)
вот это не должно работать, ибо это просто категории, а не команды.

**Comment by DarkHunter7756** [comment]
> вот это не должно работать, ибо это просто категории, а не команды.

Триггер на открытие этой категории нельзя поставить?

**Comment by DarkHunter7756** [comment]
Вариантов по вопросу открытия новой вкладки довольно много. Либо тут
![image](https://user-images.githubusercontent.com/76823962/148615517-255dc82b-8b54-4549-bc71-4caae787ddcd.png)
Либо в преференсах или ООС
