### ISSUE TITLE
Сделать химию.

### ISSUE THREAD

**Issue by Roxreic** [ChaoticOnyx/OnyxBay#7366]
### Улучшение
Это просто, блядь, ужасно. 0 контента, 0 фич, 0 реагентов. Ни нагревалки (которую с бея можно спиздить), ни дымовой машины, ни разных эффектов при передозировке, просто НИХУЯ. На билде при попытке смешать напалм просто нихуя не происходит. Максимум, чем ты можешь себя развлечь - это лишь спейс луб и хейр ремувер.

### Решение
Либо длиннопост, либо ничего.
Спиздить идеи с ТГ по химии и попробывать их реализовать. Ну или с гунов или любого нормального билда где химия ВЕСЕЛАЯ. Темная материя, которая притягивает к себе все вокруг, какой нибудь мет, который делает из тебя суперчеловека, но при этом твой мозг умирает, етс
Сделать разные эффекты от передозировок. У нас сейчас максимум печень откажет или галлюны начнутся. Ну это же несмешно.
Возможно сделать так, чтобы когда ты по-разному используешь реагент (таблетки, шприц, условный "патч", которого сука тоже нету) были разные эффекты на пациента. Типа, если колишь реагент, то он не работает, а если его схавать - то работает.

**Comment by Roxreic** [comment]
Вообще нахуя это реализовывать если все это на кримзоне есть...

**Comment by Zert0X** [comment]
> Вообще нахуя это реализовывать если все это на кримзоне есть...

Написал бы портаните химию с бишек

**Comment by Roxreic** [comment]
реал
