### ISSUE TITLE
Заменить жижу в шприцах для казни в срочном порядке

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7367]
Сейчас шприцы для смертельной инъекции наполнены хлоркой, и это определённо, прошу прощения, кал говна. Человек не умирает мгновенно, человек не умирает через 5 минут. Не умирает через 30 минут. Он целый час пялит в блэкскрин без возможности что-либо сделать. По итогу у нас самый гуманный способ казни превращается в оружие отбитых извращенцев.

Возможные решения:

- Лексорин (смерть за +-5 минут). Газовая камера на минималках.

- Potassium Chlorophoride (смерть за 4-6 минут). Инфаркт подкрался незаметно.

- Смесь из токсичных веществ. Зависит от состава.

- Changeling Toxin (или Strange biotoxin, не помню точно) (смерть за 5 секунд). 

- Impedrezene. Медленная смерть мозга. Очень медленная. Зато симптомов нет.

**Comment by Shirlineyn** [comment]
**Так и задумано.** Так надо и вводить весь шприц в 60 единиц, тогда и не валяться в крите полчаса, нет?
