### ISSUE TITLE
Улучшение ERT

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#74]
Emergency Response Team - это, в первую очередь спасатели, которые, почему-то, скатились в этаких царьков с ЦК, которые просто прибегают и всех нагибают.

Нужно сделать их настоящими спасателями. Предлагаю следующее:

1. Во время спавна ЕРТ выбирается лидер, который получает сообщение примерно такого содержания:

> Внимание! Вы были выбраны лидером отряда спасения. Ваша главная задача - стабилизировать обстановку на станции и не допустить гибели персонала и уничтожения станции. Приоритетная задача - сохранение имущества корпорации и обеспечение безопасности глав.
>
> Полученное сообщение со станции:
> [сообщение, которое отправили во время вызова ЕРТ]

2. На старте ЕРТ сохраняется количество глав и если оно уменьшится к концу, то ЕРТшникам засчитывается поражение, о котором пишется рядом с рольками в конце раунда.

Возможно, стоит добавить еще какой-то критерий уничтожения станции и потери имущества, но тут сложнее.

[GameDisUpd:] Второй пункт лучше не надо пока.

**Comment by Ruforce** [comment]
На старте ЕРТ сохраняется количество глав и если оно уменьшится к концу, то ЕРТшникам засчитывается поражение, о котором пишется рядом с рольками в конце раунда.



А если ЕРТ вызвали против одного из глав?

**Comment by YaridaTheDragon** [comment]
А если во время ДОЛГИХ СБОРОВ (в среднем 10-15 минут) один из глав помирает? Его же тут не кинешь в клонилку. Вот умер, пока ЕРТшники собирались и летели на станцию. Сырая идея.

**Comment by Epicus7** [comment]
Ну можно сохранять количество глав в момент прибытия ЕРТ, а не в момент спавна.

**Comment by Cinericius** [comment]
Произошел микродопис в ОП-пост

**Comment by Cinericius** [comment]
Алсо пересекается с #51

**Comment by Fritcher36** [comment]
#51 закрыли, с этим что?

**Comment by Doster-d** [comment]
А зачем сообщение лидеру?
