### ISSUE TITLE
Худочки

### ISSUE THREAD

**Issue by CheckEngineSS13** [ChaoticOnyx/OnyxBay#740]
Из раунда в раунд наблюдаю за такой проблемой как массовый розыск. Утеря такой вещицы СБ как HUD Glasses автоматически за собой подразумевает то, что через, буквально, 10 минут вся станция будет ходить с розыском, Бипски и ED-209 всех будут фигачить тазерами и станбатонами, а в бриге будет выстраиваться очередь из зевак и недовольно спрашивать у официальных представителей СБ 

> "А почему на мне розыск?"

. Из-за этого вместо того, чтобы заниматься своей работой, робототехники приостановят производство Бипских и ED-209 и им придется отключить существующих (если до этого их не уничтожили ассистенты, посчитав сбойными), а офицеры будут бегать по станции и снимать его со всех, вместо того, чтобы заниматься своей привычной работой. Также это лишает СБ координации и возможности ориентироваться в пространстве, отличая настоящих преступников от тех, кому розыск был выдан по ошибке. А всё из-за чего? Худ очки СБ сочетают в себе два полезных свойства. Помимо того, что они могут показывать импланты, профессию члена экипажа и его статус (Wanted, Prisoned, Parolled, Discharcged, None), но ещё и редактировать эти самые статусы нажав по игроку Shift+Click и левой кнопкой мыши по сообщению в чате:

> Status: [None]

Получается, любой обладатель таких очков может выдавать розыск всем подряд (что, собственно, и происходит из раунда в раунд). Педали в этом вопросе бессильны, они, увы, не могут по тем или иным причинам (или просто не хотят, не уведомлен о наличии такого функционала) отследить кто это делает. Как итог - вся станция ходит с белой буковкой W в красном квадратике, что мало того, что мазолит глаз, так ещё и сбивает сотрудников охраны и дизориентирует охранных роботов, которые всеми силами будут пытаться задержать невинных игроков с розыском от какого-то малолетнего дебила.

Это я всё к чему. Я хочу предложить варианты решения этой проблемы. Потому что - ну пиздец.

**Пункт 1**
Введите возможность в логах а также запедаленным педалям в чате видеть строчки с действиями, кто кому изменяет статус и на какой. Ещё такую возможность можно добавить офицерам СБ. Все вы знаете, что когда обновляется арест в консоли или истекает время в клетке, об этом пишется в канал СБ. С редактированием статуса в худ очках можно сделать что-то подобное.

**Пункт 2**
Доступ. Можно просто сделать так, что если у тебя есть Худы Секьюрити то ты можешь только видеть информацию, но не изменять её. Для изменения информации на твоей карте должен быть доступ в Бриг. В таком случае система позволит вносить какие-либо правки, а при отсутствии доступа - покажет ошибку при попытке изменения.

**Comment by Epicus7** [comment]
Фига стена текста.

1. Причем тут вообще педали? Использование очков охраны не охранниками никак не нарушает правил игры, так что педали тут вообще не причем.
2. Откуда очкам знать, кто именно их использует? То есть почему они должны палить в чат имя владельца?
3. Откуда очкам знать, что в кармане владельца есть карта доступа СБ?

Я вообще не вижу проблемы в том, что если офицеры потеряли очки, то кто угодно может понаставить какие угодно статусы. Проблема решается поимкой людей, которые украли вещи охраны, в том числе и очков. Из-за того, что офицеры могут потерять тайзер, мы же не ограничиваем стрельбу из него теми, у кого нет доступа, верно?

> Введите возможность в логах а также запедаленным педалям в чате видеть строчки с действиями, кто кому изменяет статус и на какой. Ещё такую возможность можно добавить офицерам СБ. Все вы знаете, что когда обновляется арест в консоли или истекает время в клетке, об этом пишется в канал СБ. С редактированием статуса в худ очках можно сделать что-то подобное.

Правда здесь есть интересная идея. Любые изменения статуса писать в канал СБ, но вряд ли стоит палить кто именно это сделал (можно писать имя с карты, если изменения произошли с компьютера, но не больше).

**Comment by Epicus7** [comment]
Вынес самую интересную идею в отдельный issue #994.

Этот закрываю, т.к. утеря инвентаря СБшниками - не проблема билда, а проблема СБшников.
