### ISSUE TITLE
Бафф РИПЛИ в условиях астероида

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7416]
РИПЛИ - медленный, бесполезный мех, абсолютно никому не нужный для копания, когда можно пешочком собрать все руды в мешок.

Предлагаю: Повысить скорость РИПЛИ в условиях астероида до скорости Гигакса. 

22 репапа в дискорде

**Comment by Sudar0770** [comment]
Предлагаю вообще забафать его невероятно, чтобы этот мех вообще существовал в игре.
Повысить скорость в вакууме
Повысить сплеш бура, чтобы копалось 3 тайла одновременно, а алмазный просто будет делать это быстрее.
(не знаю есть ли в РИПЛИ мезонки) встроить в мех мезонки
Добавить РИПЛИ джетпак
