### ISSUE TITLE
Сделать так, чтобы генкомобы перестали занимать весь тайл

### ISSUE THREAD

**Issue by EliseyGladkiy** [ChaoticOnyx/OnyxBay#7426]
На данный момент у нас ходячие руки и ноги полностью покрывают собой весь тайл, что делает невозможным быстрый подбор предметов с тайла с ними. Ещё большая проблема в том, в том, что генкомобы при спавне появляются ровно на вашем космонавтике, и если вам надо кровь из носу кликнуть по себе и по предмету на тайле с генкомобом, то приходится ебаться с альт-кликом, и не дай бог вы случайно кликните по этому мобу без альта — он не посмотрит на то, что вы же его и заспавнили, и укусит пару раз.
Ещё во время инфеста, когда жертва находится под паралитическим жалом, приходится кликать с альтом, переходить во вкладку с жалом обратно, потом в тюрф, и там кликать на цель, потому что время действия одного жала не хватает, а кликнуть по космонавтику, лежащему на тайле, нельзя, потому что игрок закрывает его своим спрайтом размером с тайл.

**Comment by O0oMaximo0O** [comment]
Не совсем уверен, что геймдизайн нужен, но поставлю.
