### ISSUE TITLE
Альбом выбора нижнего белья

### ISSUE THREAD

**Issue by Zert0X** [ChaoticOnyx/OnyxBay#7440]
**Улучшение**

Сделать так, чтобы по клику на Equipment открывался не список названий, а альбом со спрайтами. Это сделает выбор проще и быстрее и тем самым побудит больше игроков поэксперементировать со внешним видом.
**Решение**

При открытии меню выбора нижнего белья открывается не список названий, а альбом, в котором можно посмотреть и оценить каждый вариант визуально. В альбоме должны быть спрайты текущего персонажа с применёнными к ним вариантами.

**Comment by Sudar0770** [comment]
Мне кажется, что делать альбом для "трех с половиной" пар трусов - глупо

**Comment by Zert0X** [comment]
> Мне кажется, что делать альбом для "трех с половиной" пар трусов - глупо

А если трусов больше чем *три с половиной пары"? Плюс не забывай про футболки и носки.
