### ISSUE TITLE
Смоченная тряпка работает через противогаз. 

### ISSUE THREAD

**Issue by HekT0** [ChaoticOnyx/OnyxBay#746]
#### Описание проблемы
На вашей хуйне смоченная химикатом тряпка работает через противогаз. Пиздец.

#### Разница между реальным поведением и ожидаемым
Смоченная тряпка не должна работать через противогаз.

#### Как воспроизвести проблему?
Смоченной тряпкой ткнуть того, на ком противогаз.

#### Конкретная информация

Dry Rag - тряпка. 
Gas mask - противогаз.

#### Как долго известно о проблеме?

Только что столкнулся, не далее получаса назад.

#### Версия клиента, версия сервера и идентификатор игры

Версия клиента - 512.1456
Server Revision: 2268012395c917b5661a9176430fe0819850cee6 - release - 2019-09-14
ID - b3l-aeBW
#### Дополнительная информация

- [ ] Проблему можно воспроизвести хотя бы один раз
- [ ] Проблема может быть воспроизведена разными игроками (не зависит от конкретного игрока)
- [ ] Проблема может быть воспроизведена в нескольких раундах (не зависит от конкретного раунда)
- [ ] Проблема случилась в недавнем раунде (прошло меньше недели)
- [x] [Не получилось найти похожую проблему в списке](https://github.com/Rampoch/Chaotic-Onyx/issues)

**Comment by igorsaux** [comment]
https://github.com/ChaoticOnyx/OnyxBay/pull/785/commits/5503fb55565a96b6407c832b129754d882591f0a
