### ISSUE TITLE
Понерфить горячий воздух.

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#75]
Реализм реализмом, но +60 по Цельсию рвут тебе легкие в один тик.

Че за мемы?

**Comment by Epicus7** [comment]
Нужно продумать что должно происходить с человеком в условиях повышенной температуры.

Понятно, что люди вполне себе нормально себя чувствуют, например, в бане, при 120 градусах. Ну и до того как дойти до легких, горячий воздух остынет, так что рвать легкие он должен только при совсем-совсем высоких температурах.

Короче тут надо бы почитать интернетики и придумать как оно должно быть.

**Comment by Cinericius** [comment]
По-хорошему тут много факторов типа влажности роляет, от которых собсно зависит теплопроводность. У нас вообще есть в билдофизике как таковая теплопроводность, шоб ее еще и разную можно было разным предметам ставить?

**Comment by Epicus7** [comment]
Теплопроводность точно есть у стен, а точнее у материалов из которых они делаются. У людей - вряд ли, скорее всего нет.

**Comment by Cinericius** [comment]
Вопрос в том, есть ли она у атмоса.
