### ISSUE TITLE
Больше рекурсивных улучшений для генокрадов

### ISSUE THREAD

**Issue by EliseyGladkiy** [ChaoticOnyx/OnyxBay#7530]
В текущем билде способность "рекурсивное улучшение" является одной из самых бесполезных. Она ещё более-менее использовалась при наличии биохимического котла, но с его удалением потеряла всякую значимость. Почему? Потому что УЛУЧШЕНИЙ НЕТ. Пролистав список способностей, вы найдёте всего пять штук, которые имеют улучшения. Причём местами такие себе улучшения, честно говоря.

В связи с этим, предлагаю сделать больше рекурсивных улучшений, чтобы эта способность оправдывала свою стоимость, была универсальной и разнообразила геймплей на генокрадах.

Deaf Sting, Blind Sting, Silence Sting, Vomit Sting, DNA Extraction Sting, Fake Armblade Sting, Hallucination Sting можно дать возможность пробивать через броню.

Ranged Stinger можно убрать/снизить дополнительный расход химикатов при включённом улучшении.

Улучшенный Digital Camouflage не будет менять внешний вид игрока (ни разу не использовал способность , но по описанию она его меняет).

Rapid Heal будет хилить с большей силой (на данный момент нельзя за один присест отрастить себе обратно всё тело) или снизит стоимость.

Bioelectric Lockpick станет незаметным или снизит стоимость использования.

Painless снизит стоимость поддержания.

Body Disjunction будет спавнить на несколько органов больше (можно нарисовать новые спрайты живой печени, а можно просто на пару рук больше прописать) и/или иметь сокращённый прогрессбар.

Division будет тратить на 1 геном меньше для использования (это получается надо давать новым генкам на 1 ген меньше, падажжи ёбана...)

Passive Regeneration можно усилить лечение или снизить стоимость при улучшении.

Detach Limb будет тратить на 10 химикатов меньше и/или не иметь прогрессбара.

Mimic Voice также можно убрать стоимость поддержания.

Epinephrine Sacs можно добавить какие-либо бонусы к пойзу/добавить возможность снимать наручники/снизить стоимость.

Ещё можно Rapid Chemical-Synthesis и Engorged Chemical Glands соответственно прописать ещё чуть увеличенные синтез и запас при улучшении.

Напоминаю, что Recursive Enhancement стоит 6 очков и просто так всем этим пользоваться не получится.

**Comment by kreeperHLC** [comment]
Разбери на мелкие иссуи по каждой абилке пожалуйста

**Comment by Tsurupeta** [comment]
Декомпозирован.
