### ISSUE TITLE
Суть - не работают криокамеры в медбее на Эклипсе.

### ISSUE THREAD

**Issue by Poromoks** [ChaoticOnyx/OnyxBay#758]
### Описание бага
Не работают крио на Эклипсе. Трубы настроены не так. Посмотрите на экзодусе, как они сделаны, и всё поймёте.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Идём на Эклипс. Заходим в медбей.
2. Включаем крио.
3. Понимаем, что оно не охлаждается, а также там просто огроменное давление внутри камеры, которое вполне может убить, потому что клапан должен быть подсоединён к канистрам. В комнате с одной камерой вообще нет этого клапана.
4. Идём за маппером.

Скриншоты:

Как НЕ должно быть!
![scrnshot1b](https://user-images.githubusercontent.com/55941971/65831575-851a6b00-e2e5-11e9-87a3-7dbafcf58263.png)
![scrnshot2b](https://user-images.githubusercontent.com/55941971/65831578-96fc0e00-e2e5-11e9-989a-6da4b9a24ceb.png)

Как должно быть.
![scrnshot3b](https://user-images.githubusercontent.com/55941971/65831580-9cf1ef00-e2e5-11e9-9b1d-4f54816f674a.png)
![scrnshot4b](https://user-images.githubusercontent.com/55941971/65831584-a3806680-e2e5-11e9-8907-cbe3062358f6.png)

UPDATE (от 02.10.2019)
![scrnshot3R](https://user-images.githubusercontent.com/55941971/66042880-e772a600-e547-11e9-9a57-6ac06657b988.png)

Спасибо, комната с двумя капсулами теперь работает исправно.
![scrnshot1R](https://user-images.githubusercontent.com/55941971/66042884-ed688700-e547-11e9-9ec6-18ae9ab0b5c3.png)

Жаль лишь, что вторая комната не была пофикшена.
![scrnshot2R](https://user-images.githubusercontent.com/55941971/66042897-f48f9500-e547-11e9-9f5b-58fd4e0d8140.png)

**Comment by LLIkolnik** [comment]
Скрины можно, пожалуйста?

**Comment by Poromoks** [comment]
> Скрины можно, пожалуйста?

Добавил.

**Comment by LLIkolnik** [comment]
Что ты мне показываешь. На скринах с Эклипса только последнее крио настроено не то что неправильно, но скорее просто странно. Крио ДОЛЖНО работать. Проблема в тебе, думаю.

**Comment by igorsaux** [comment]
На первом скриншоте нужно ждать пока газ не охладится - и тогда включать вентиль, иначе газ который не успел охладиться обратно во фризеры больше не попадёт (если вентиль односторонний).

**Comment by Poromoks** [comment]
Попробуйте сами включить их на локалке или на одном из серверов.

**Comment by Animesku** [comment]
Какая-то фигня, и в правду, намаплена. В медбее что, инженеры должны сидеть, чтоб в этом разбираться?

**Comment by ZerlGray** [comment]
Инженеры - элита нации. Инженеры вообще должны во всех отделах быть. Вообще всех остальных, ящитаю, в космос нужно спустить и оставить ток инженеров.

**Comment by Poromoks** [comment]
Обновил.

**Comment by Rampoch** [comment]
Про Эклипс мне лучше в дискорде просто писать, я сюда редко заглядываю.

**Comment by Rampoch** [comment]
![image](https://user-images.githubusercontent.com/5979620/66253047-419f8100-e76b-11e9-98d2-64eba0bdbea3.png)
Последнее крио теперь должно работать нормально. Спасибо за репорты.
