### ISSUE TITLE
АнтагТокены

### ISSUE THREAD

**Issue by denver1000** [ChaoticOnyx/OnyxBay#76]
Способов наказания игроков у нас уже прилично, а вот пряников ещё нет. На tg билде есть такая фича - антагтокены. Суть в чем если раунд внезапно упал/ребутнулся/etc или ты чем-то отличился тебе выдают "фишку" на рольку которую можно потратить в начале любого раунда и гарантированно стать ролькой.

Нельзя ли эту тему как то украсть к нам?

**Comment by Epicus7** [comment]
Может быть в будущем. В приоритете у нас система кармы и перепил режимов на ивенты, что будет конфликтовать с этими токенами.

**Comment by Cinericius** [comment]
Предлагаю пока закрыть этот иссуй до востребования.

**Comment by denver1000** [comment]
Востребую! Но если будет что-то другое то закрывайте

**Comment by Epicus7** [comment]
Вместо закрытия может лучше плашку новую сделать "Отложено"? На Эрисе подобная есть.

**Comment by Cinericius** [comment]
Уффф
