### ISSUE TITLE
Новые Анонсы на замену ТТСа с ТГ 

### ISSUE THREAD

**Issue by No-Tips** [ChaoticOnyx/OnyxBay#7624]
Ну пиздец, этот ТГшный ИИ звучит максимально убого, все от него устали, да и список анонсов с озвучкой явно пора обновить, потому что у нас только небольшая часть всех ивентов как-то озвучивается при помощи звука ТТСа. 

Я для ивента как раз готовлю пару анонсов с другой озвучкой. И, раз уж я занялся этим, то могу и заготовить нового анонсера для Опухбея на основе нейронки от 15.ai, чтобы слегка освежить анонсы, допилить новые, может, наконец добавить какой-то текстик для анонсов смены кода, сугги пишите в комменты.

[newannouncer.zip](https://github.com/ChaoticOnyx/OnyxBay/files/8119480/newannouncer.zip)

Прикрепляю зипку с тремя сэмплами анонсов, которые могли бы быть у нас в билде. Главная проблема будет во встречающихся в анонсах названиях станций. Думаю, придется что-то подправлять, но это уже дело геймдизайнеров, решить, как это может быть воплощено в билд.

**Comment by TobyThorne** [comment]
По качеству реплики из зипки прям на несколько порядков хуже тех, что есть сейчас.
Идеально было бы записать новые реплики и обработать для имитации имеющихся.

**Comment by No-Tips** [comment]
Хуже они от того, что сделаны не под идеальную речь ИИ, а под сообщение по радиоканалу с шумами и дисторшином? 
Как грится, я аудиодизайнер, я так вижу, но разве это не как раз то, что могло бы подходить под сообщения на общий канал?

**Comment by MrMagick2104** [comment]
> разве это не как раз то, что могло бы подходить под сообщения на общий канал?

Ты же не ТТС на сейлоги людей делаешь. Для ИИ же вполне реально реализовать ИИ-лайк ТТС, например: https://glados.c-net.org/
В основном по той причине, что, емнип, большинство голосов ИИ довольно в культуре довольно просто алгоритмически получаются из любого голосового инпута, а тот уже можно делать разными готовыми ТТСами.

**Comment by TobyThorne** [comment]
> Хуже они от того, что сделаны не под идеальную речь ИИ, а под сообщение по радиоканалу с шумами и дисторшином? Как грится, я аудиодизайнер, я так вижу, но разве это не как раз то, что могло бы подходить под сообщения на общий канал?

Шумов и дисторшна столько, что я из десятисекундных сообщений едва могу разобрать по три слова. Да и сам голос уж больно неприятный в сравнении с нынешним.

**Comment by No-Tips** [comment]
>  Ты же не ТТС на сейлоги людей делаешь. Для ИИ же вполне реально реализовать ИИ-лайк ТТС

Погоди, а у нас в коде где-то указано, что это произносит ИИ, а не какой-то оператор в колцентре с космоиндусами?

**Comment by MrMagick2104** [comment]
Если ИИ делает аннонс, то там прямым текстом написано, что АИ аннонсмент.
У ИИ есть уже заготовленные тексты (про аниме что-то точно помню), которые озвучены текущим ТТСом.
Вывод: аннонс делает ИИ.

**Comment by igorsaux** [comment]
https://github.com/ChaoticOnyx/OnyxBay/pull/9156
