### ISSUE TITLE
Мех и шаттл в отбытии. Проблема прохода

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#7629]
### Описание бага
При попытке прохода на шаттл в отбытии сидя в мехе - выдает сообщение о невозможности это сделать.
Я полностью пробурил шлюзы, тайлы полов, подавители энергощитов. Но область не пускающая мехи внутрь осталась. (пропала за секунду до отлета шаттла)

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем мех и пробуриваем себе путь на шаттл через двери
2. Видим невидимую область не пускающую мехи на шаттл через уже уничтоженные шлюзы.

### Ожидаемое поведение
Я пробурил алмазным буром проход на шаттл, игра оценила мои усилия и пропустила меня внутрь

**Comment by TobyThorne** [comment]
На входе стоят сенсоры, не пускающие мехов. 
![image](https://user-images.githubusercontent.com/45202681/155451741-511ae1dd-f978-4994-bbc4-cbbbc78c37be.png)
