### ISSUE TITLE
Hydrogen sheets даёт водород при измельчении

### ISSUE THREAD

**Issue by EliseyGladkiy** [ChaoticOnyx/OnyxBay#7654]
На данный момент водород при измельчении в блендере даёт жалкий Hydrazine, который не совсем водород и при выливании оставляет лишь пятна топлива на полу. Было бы круче, если бы водород при измельчении давал, внезапно, водород, и тот бы мог превращаться в газ при выливании, как это делает плазма.
Только у нас жидкого водорода в игре, вроде как, вообще на билде нет.

**Comment by Sudar0770** [comment]
Вообще добавить жидкости было бы прикольно. Типа устроить потоп из жидкостей. Было бы прикольно искупаться в бассейне из крови после выпила СБ.

**Comment by MrMagick2104** [comment]
Жидкости не нужны, потому что их сложно симулировать, атмоса нам не хватает. Выводом будут лаги в больших количествах.

Всё же, у нас не биошок стейшн, чтобы это имело хоть какое-то значение.
