### ISSUE TITLE
Физические упражнения и как они работают

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#7680]
### Улучшение
На мой взгляд практического смысла в качалке 0. Тренажеры просто кушают сытость куклы. Предлагаю сделать им практическое применение помимо выработки энергии на педальном генераторе.

### Решение
Предлагаю повышать пойз и силу куклы после занятий спортом. В качестве платы за силу предлагаю время потраченное на прокачку, обилие еды потраченное во время тренировок и временная боль в мышцах.

### (Опционально) Альтернативы
Возможно заставить организм выделить что-то, что делает куклу эффективнее в физическом труде.

### (Опционально) Дополнительная информация
Так же предлагаю добавить возможность клепать гантели и/или гири из материалов. Ими стукать будет больно, а в перерывах между пАстуками можно подкачаться.
### (Сударь0770 предвкушает)
Сюжет в моей голове выглядит как тонкоассистент которого избили (возможно не только избили) СБшники и он пошел на 40 минут раунда в качалку скупив ВЕСЬ протеин на станции. И вот сидит этот охранник пятерочки, дубинку свою крутит в руках в баре... ничего не предвещало беды, и вот спустя мгновение в бар заходит ОН... машина для убийств, на велотренажере прокачал ноги и стал быстрым, на жиме прокачал граб так, что из него не выбраться даже самым стойким бойцам, а боксерские груши закончились еще 20 минут назад и теперь этот бывший тонкоассистент нашел себе новую грушу. Спустя одну зацензуреную сцену он СО СЛЕЗАМИ НА ГЛАЗАХ воссел над взбитым в кашу СБшником и прошептал смотря вверх "мама, я отомстил..."

**Comment by NefrNerf** [comment]
Можно давать небольшие бусты к урону кулаками, со скоростью проблемы, ее сложно контролировать. А пойз, с чего вдруг занятия на тренажёре повысят тебе устойчивость, ты скорее устанешь и будешь хуже защищаться.

**Comment by Zert0X** [comment]
Опять в обход фичебота...

**Comment by kreeperHLC** [comment]
> Опять в обход фичебота...

Ну и правильно. Ей осталось ещё научиться Овнеров слапать. ~~Она уже лучше Дарка~~

**Comment by Zert0X** [comment]
> > Опять в обход фичебота...
> 
> Ну и правильно. Ей осталось ещё научиться Овнеров слапать. ~Она уже лучше Дарка~

Сударь это она?! Долбаные трапы

**Comment by kreeperHLC** [comment]
А тьфу, мне показалось что это Террид написала фичу. ~~Всё ещё лучше Дарка~~

**Comment by Sudar0770** [comment]
> Опять в обход фичебота...

А это плохо?

**Comment by EliseyGladkiy** [comment]
Предлагаю после тысячи кликов на педалегенераторе и тренажёре просто давать игроку халка.

**Comment by Sudar0770** [comment]
> Можно давать небольшие бусты к урону кулаками, со скоростью проблемы, ее сложно контролировать. А пойз, с чего вдруг занятия на тренажёре повысят тебе устойчивость, ты скорее устанешь и будешь хуже защищаться.

Грабы станут сильнее, грудные мышцы - стронк.
Метание предметов станет сильнее.
Наручники станут сниматься быстрее
Повысится скорость передвижения при переносе в грабе людей
