### ISSUE TITLE
Longsword blade и крафт мечей

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#7696]
Добавить в список крафтов из любых твердых материалов большое лезвие. Разумеется стоить будет дорого, 15-20 листов. В сочетании с деревянной ручкой получится меч. 

Иссуй набрал 22 репапа и 2 репдауна в дискорде

**Comment by Sudar0770** [comment]
А как же мачете? Я че... зря воровал части автолата у ученых? Я зря на свой страх и риск ломал этот протолат без перчаток? Я зря скрутил всю сталь на станции на мачете?
Может аналог какой? Типа... добавить возможность взломать шахтерский чекан монет чтобы он вместо монет чеканил клинки? Стволы пушек? Что угодно?
Не позволяйте простому серопижамнику обзавестись так просто на 2 минуте раунда лонгсвордом(((

**Comment by DarkHunter7756** [comment]
> Типа... добавить возможность взломать шахтерский чекан монет чтобы он вместо монет чеканил клинки

Типа возможность и сейчас есть. Емагнуть магаз шахтеров и получить "СПОЙЛЕР"

**Comment by DarkHunter7756** [comment]
Насчет мачете и аналогов. Есть копье с охеренным уроном при правильной сборке из определенных ресурсов. Есть бита с неплохим уроном. Все это делается на 1 минуте раунда из мрамора. 

Лонгсворд же посложнее ресурсной биты, ибо требует 2x ресов (20 листов урана не каждый шахтер тебе даст) и ручку из дерева (встречается только в гетто и библиотеке).
