### ISSUE TITLE
Починка режимов за вознаграждение.

### ISSUE THREAD

**Issue by AsanteFenix** [ChaoticOnyx/OnyxBay#777]
Техзадание:
Починить один из режимов:
1) Алиены
2) Блоб

Желаемый результат:
1) Чтобы работало и не отваливалось при каждом чихе.

Вознаграждение:
1) На момент написания заявки 450 рублей.

**Comment by Megmeehey** [comment]
@AsanteFenix поищи в девканале в дискорде сообщение от симбирского. Там он расписывал задачу про алиенов, чуть лучше чем _"почините"_

**Comment by Epicus7** [comment]
Все еще нужно более подробное описание. И награды не будет, да.

**Comment by Cinericius** [comment]
Сомнительной нужности иссуй.
