### ISSUE TITLE
Джоббаны на мышей.

### ISSUE THREAD

**Issue by oleggorru** [ChaoticOnyx/OnyxBay#7773]
Педаль состав Эоса просит кнопки на джоббаны мышей. Как было когда-то раньше.

В новую бан панель добавить возможность выдать джоббан на роль мыши.

Опционально можно и на всех симпл мобов.

![image](https://user-images.githubusercontent.com/8418633/159758678-5ccb0699-4a62-44ca-aaae-eb052e50f848.png)

**Comment by Sudar0770** [comment]
А что не так с мышами? Типа что должен делать игрок на мыши чтобы заслужить бан на нее? Через эмоутки общаться аля **Mouse сука адай сыр падла сука**?
Кусать ССДшников?
