### ISSUE TITLE
Замаскированные абдукторы палятся экзамайном

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#7792]
### Описание бага
Выглядит как человек, а в экзамайне an Abductor. Плюс пишется вся экипировка, даже если в игре она выглядит как обычная одежда.
МОЖЕТ БЫТЬ это только госты так видят, а игроки -- как человека, но сомневаюсь.

### Скриншоты
![image](https://user-images.githubusercontent.com/60045066/160165047-c76753d5-ba15-49f3-a12b-86463cbcf726.png)

### (Опционально) Дополнительная информация
Client Version: 514
Server Revision: [a5d4d78e03a1ca303f8c2dda3bc730d754daa66a](https://github.com/ChaoticOnyx/OnyxBay/commit/a5d4d78e03a1ca303f8c2dda3bc730d754daa66a) - 3f8c2dda3bc730d754daa66a - 2022-03-25
Game ID: cg8-cv9J
Current map: NSS Exodus

**Comment by Zert0X** [comment]
> ### Описание бага
> 
> Выглядит как человек, а в экзамайне an Abductor. Плюс пишется вся экипировка, даже если в игре она выглядит как обычная одежда. МОЖЕТ БЫТЬ это только госты так видят, а игроки -- как человека, но сомневаюсь.
> ### Скриншоты
> 
> ![image](https://user-images.githubusercontent.com/60045066/160165047-c76753d5-ba15-49f3-a12b-86463cbcf726.png)
> ### (Опционально) Дополнительная информация
> 
> Client Version: 514 Server Revision: [a5d4d78e03a1ca303f8c2dda3bc730d754daa66a](https://github.com/ChaoticOnyx/OnyxBay/commit/a5d4d78e03a1ca303f8c2dda3bc730d754daa66a) - 3f8c2dda3bc730d754daa66a - 2022-03-25 Game ID: cg8-cv9J Current map: NSS Exodus

Условности билда придумай мне как это наебать не переписываю половину билда и я сделаю

**Comment by DeltaEpsilon7787** [comment]
Examine() у мобов перегрузи.

**Comment by Zert0X** [comment]
> Examine() у мобов перегрузи.

У какого у Хумана? Абдуктор это хуман, разница только в расе

**Comment by Zert0X** [comment]
Закрыто в #7804
