### ISSUE TITLE
Переключение предохранения.

### ISSUE THREAD

**Issue by hekko4** [ChaoticOnyx/OnyxBay#78]
Было бы неплохо сделать возможным убрать предохранение со стволов во время хелп интенета. Это  может спасти и сломать много жизней, думаю оно того стоит.

**Comment by LagannPM** [comment]
сюда же запихнуть хамрбатоны
если Станбатон включен он должен работать как на хелп интенте иначе хармить

**Comment by Cinericius** [comment]
Я думаю можно закрывать, Капс сделал же.
