### ISSUE TITLE
Генокрад после поглощения другим генокрадом не умирает

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#7846]
### Описание бага
Раньше, точно помню, это было не так, и это был один из немногих способов убить генокрада насовсем. Сегодня ситуация: генокрады подрались, один другого победил, высосал. Тот полетал минуты две в гостах и воскрес при помощи стазиса. Ну ебать-копать.
Что весьма смешно, высосанный генокрад превращается в хаска (серая кожа, лысый, обескровленный) и остаётся таким, по-видимому, навсегда, даже после дальнейших использований стазиса, а высосавший получает (вроде бы?) гены за поглощение. Но второй раз высосать, вроде бы, нельзя.
Не знаю, может, это конечно очередное блестящее геймдизайнерское решение, но даже так -- очень сомнительное и реализовано так, что приводит к смешным последствиям.

**Comment by MrMagick2104** [comment]
https://github.com/ChaoticOnyx/OnyxBay/issues/7388

**Comment by TimErmolt** [comment]
Ну, получается, бамп тому иссую.
