### ISSUE TITLE
Ужасные проджектайлы

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#7847]
### Описание бага
Проджектайлы у нас никогда не были идеальными, но в настоящее время всё как-то вообще донельзя смешно и грустно стало. Пули и лазерные пучки просто пролетают сквозь людей, иногда даже если двигаются по прямой, летя в спину, а в некоторых случаях даже в лицо жертве. Особенно часто это происходит, если и проджектайл, и жертва двигаются с большими скоростями (лазеры против ксеноморфов-охотников, каждый второй выстрел пролетает сквозь алиума; электроды тазера против человека под гиперзином или таяры и так далее).

Я знаю, что механики самих проджектайлов не особо менялись, но у нас для лазерного оружия пучки (слаги, т.е. проджектайлы) стали стандартом, а лучи -- исключением, а к тому же все стали быстрее бегать и появились гиперскоростные охотники чужих, не так уж и редко возникающие в раунде, так что теперь минусы проджектайлов особенно заметны и пагубно влияют на боёвку.

**Comment by TobyThorne** [comment]
>Пули и лазерные пучки просто пролетают сквозь людей

Они точно молча пролетают, а не пишут "The laser bolt misses Vasya Zalupkin narrowly!"?

**Comment by TimErmolt** [comment]
Скорее всего точно. Я прошёлся по чатлогу раунда, где была перестрелка против алиумов с несколькими случаями пролетания лазера, летящего по прямой, (после которого я и вдохновился создать иссуй) и там ни разу это сообщение не появляется.

**Comment by DeltaEpsilon7787** [comment]
Это баг времени. Он возникает не только с прожектайлами -- он возникает с вообще многими вещами. Например, иногда люди проходят в друг-друга вместо свопа позиций (без проползания, вот прямо заходят). У атмоса это вообще пиздец как заметно -- двигающиеся сквозняком предметы постоянно то непроходимы, то какую-то хуйню делают.

Предположительно эта хуйня из-за анимаций возникает. Например, прожектайл, анимируя перелет из тайла А в тайл Б таков, что если войти в тайл А из тайл Б ВО ВРЕМЯ анимации перелета, то можно пройти сквозь этот прожектайл. Аналогично с людьми -- если два одновременно человека пытаются войти на один тайл (всего-лишь тик нужно чтоб совпал) -- они будут в одном и том же тайле без свопа.

**Comment by Sudar0770** [comment]
Лично по моему мнению это не является чем-то критичным. Промахи работают для всех и следовательно фиксить это срочно не нужно.
С рофлом на лице и похуйзмом в голове могу сказать "не баг а фича" просто твой персонаж промахнулся и попал в просвет между ногами.

**Comment by MrMagick2104** [comment]
> Промахи работают для всех и следовательно фиксить это срочно не нужно.

Тем временем, перестрелки:
![Gif-VideoID-ZQDW2ccSf-Q](https://user-images.githubusercontent.com/58848742/161847968-c39b7a00-5d97-4abc-9a70-0f0bc4d5e970.gif)


Баг дико замедляет темп боя, что мешает нормальной игре - доходит реально до смешного.

**Comment by Zert0X** [comment]
> > Промахи работают для всех и следовательно фиксить это срочно не нужно.
> 
> Тем временем, перестрелки: ![Gif-VideoID-ZQDW2ccSf-Q](https://user-images.githubusercontent.com/58848742/161847968-c39b7a00-5d97-4abc-9a70-0f0bc4d5e970.gif)
> 
> Баг дико замедляет темп боя, что мешает нормальной игре - доходит реально до смешного.

Не обращай внимания на Сударя.
