### ISSUE TITLE
Захват областей, цены областей, количество участников

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#7895]
В билде уже влиты зачатки войны за областей, данный иссуй ставит целью поставить цену на области и определить количество революционеров и лоялистов.

Зоны можно разделить на 3 типа:
1. Высокая награда для стороны
2. Основная награда для обоих сторон
3. Минимальная награда для стороны

### Революция 
Зоны с высокой ценой для революционеров: кабинеты всех глав, бриг, командный отдел.
Зоны с основной наградой для революционеров: коридоры, помещения отсеков: РНД, инженерный, дормы.
Зоны с минимальной наградой для революционеров: гетто, карго

### Лоялисты
Зоны с высокой ценой для лоялистов: командный отсек, карго, кабинеты всех глав.
Зоны с основной наградой для лоялистов:  гетто.
Зоны с минимальной наградой: технические отсеки, жилые отсеки.

### Почему так?

Явная диспропорция в ценах направлена на игру в кошки-мышки, лоялистам нужно искать и охотиться на революционеров. Так как условному ученому или инженеру легко обклеить свой отдел, так и СБ довольно просто обклеить бриг и жилые отсеки. Революционеры должны совершать атаки, а лоялисты их ловить. 

### Пропорции

Базовое соотношение лоялисты/революционеры должно быть 2/3. 2 лоялиста один из которых глава и 3 революционера, с 33 процентным шансом на главу отдела.

**Comment by NefrNerf** [comment]
Есть вопрос, какие награды за захват зоны выдавать, предложение приветствуются.

**Comment by Sudar0770** [comment]
Значит революционеры захватят условный кабинет ХоПа и.... а чем будет подтерждаться их захват с точки зрения геймдизайна? Типа флаг? Или консоль ХоПа будет взломана? Я не до конца понимаю что предложить в этом плане.

Допустим поставили революционеры условный флаг в кабинет ХоПа и им нужна высокая награда за это.... хм...
Допустим они работают на синдикат и тут с этими вашими телекристаллами проблем нет, телепортация снаряжения и все дела.
Отхватили себе лоялисты кабинет ХоПа обратно и им нужна награда... Вот тут у меня кроме подачек с ЦК вариантов нет. И мне кажется для НТ будет дешевле послать ЕРТ туда убить реву, чем привозить награды за условные флаги в условных кабинетах ХоПа. Это все было с точки зрения моей больной логики, напишите если считаете меня не правым.
Теперь с точки зрения веселья. Будет прикольно если за захват точек стороны смогут получать снаряжение все лучше и лучше. Чтобы рева под конец бегала с есвордами, а лоялисты научились в импланты лояльности

**Comment by NefrNerf** [comment]
Почитай оригинальный иссуй по захвату тер и пр

**Comment by Sudar0770** [comment]
> Почитай оригинальный иссуй по захвату тер и пр

Я не справился с поиском этого иссуя, кинь пожалуйста его номер

**Comment by Zert0X** [comment]
> > Почитай оригинальный иссуй по захвату тер и пр
> 
> Я не справился с поиском этого иссуя, кинь пожалуйста его номер

Нет нельзя, ищи.
