### ISSUE TITLE
Убрать стазисные мешки

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#7896]
### Улучшение
Выпилить к чертям эти стазисные мешки. Я бы предпочёл, чтоб вообще, но это идеальный мир, так что хотя бы из раундстарта, а лучше сделать их эндгеймовой вещью, получаемой только на последних стадиях РнД. Почему? Потому что они _настолько_ сильны.

Ситуация буквально в закончившемся только что (на момент написания) раунде:
Происходит бой между СБ и культом в бриге. Я, офицер, до своей гибели ввёл в крит как минимум двух культистов, и без медпомощи они бы скоропостижно отошли в загробный мир. Однако, тут на сцене под ангельский хор появляется медик-культист с двумя стазис-мешками, в который он упаковывает раненных, оттаскивает их в медблок и выхаживает до полностью здорового состояния. 
Все усилия, приложенные мною и моими коллегами, по устранению культистов обнуляются даже не потому, что медик хороший врач, а потому, что он принёс два мешка, которые увеличивают оставшееся до смерти пациентов время с примерно 3 минут до 13.

Один предмет, несколько экземпляров которого раундстартом может взять любой врач или вообще любой проникший на медицинский склад, абсолютно избавляет станционных лекарей от всякой необходимости спешки при лечении или доставке пациента в медблок.
Парамедику из-за этого предмета уже не нужно быстро проводить анамнез на месте, диагностировать состояние пациента, оказывать первую помощь, погружать на каталку и спешить в медблок, крича хирургам в рацию, чтоб готовили операционную. Он просто суёт пациента в стазис-мешок и спокойным шагом тащит его (а _одобренный геймдизайном_ #6694 и вовсе позволит ему использовать для этого каталку) до медблока и может даже в бар зайти выпить, выкурить пару сигар и поговорить с другими его посетителями.

Это медицинская утопия, которую я бы ожидал увидеть ближе к концу раунда благодаря труду учёных и надёжным поставкам ресурсов от шахтёрского отдела карго. Почему она у нас царит с раундстарта -- загадка.

Да, можно привести аргумент, что стазис-мешки, вообще-то, по задумке одноразовые, да и на деле [мощность стазиса в них постепенно истощается](https://github.com/ChaoticOnyx/OnyxBay/blob/889b15354fd8fcde0fdd835648fabfecc7df4c98/code/game/objects/items/cryobag.dm#L34). В большинстве ситуаций это не имеет значения. Полумёртвый пациент, которому без стазиса осталось не более пары минут, не будет лежать в мешке 10-15 минут -- достаточное время для того, чтобы мощность стазиса мешка ощутимо истощилась. Он будет лежать в нём столько, за сколько его дотащат до медблока, а это, как правило, около минуты-двух. То есть свежим мешком в худшем случае это можно провернуть два раза до тех пор, пока мощность стазиса не истощится в первый раз (а при каждом истощении от неё убавляется 25% от _текущего_ значения). Если мешки можно будет погружать на каталки, то время пути до медблока можно смело уменьшить вдвое, а то и даже втрое.

### Решение
В общем предложение простое -- выпилить стазисные мешки полностью со станции. У ЕРТ, дедсквада и нюкеров (вроде у них есть) можно оставить -- всё-таки, не каждый раунд прилетают и как правило на поздней стадии, а нюкеры вообще антагонисты.
Если всё-таки хочется способ персоналу получить эти мешки без вмешательства извне, то добавить их в список изучений РнД на поздние уровни исследований. Конечно, может привести к штурмующим РнД медботам, но как по мне это интереснее, чем то, что делают мешки сейчас. Можно также и в заказы карго (вроде даже уже есть), но тоже подкрутить цену, чтобы пришлось подкопить карго-кредитов на них.

### Альтернативы
Если не хочется менять наличие мешков в медблоке раундстартом, то баффать истощение мощности стазиса. Сейчас истощение происходит через примерно 5 минут (150 тиков) нахождения пациента в мешке -- пускай будет около 2,5, то есть 75 тиков, вдвое меньше, может, чуть меньше. Тогда одна доставка пациента в мешке в медблок будет примерно укладываться в это время, то есть при каждом повторном использовании мешка он будет истощаться.

И конечно мешки на каталки -- кошмар. Медик, тащащий мешок, движется значительнее медленнее медика, тащащего каталку -- это уравновешивает две ситуации: в мешке пациент гораздо медленнее гибнет, но и врач медленнее его тащит. Если мешки можно будет класть на каталки, это всё мгновенно вылетит в трубу.

За соизмеримый с копипастой текст иссуя извиняюсь, но иначе у меня не получается /shrug

**Comment by Nod404** [comment]
мешки на каталки не запилили

**Comment by Nod404** [comment]
ладно, я брейндед неправильно прочитал

**Comment by Sudar0770** [comment]
### Я согласен с тем, что мешки лишают парамедиков крупного куска романтичности в их работе.
Весь сок этой профы в том, чтобы найти пострадавшего и с максимальной скоростью и точность продиагностировать что с ним случилось имея у себя маленький сканер. Оказать первую помощь и привести к врачам более или менее стабильного пациента.
### Я не согласен с тем, что мешки должны быть лейтовыми
 пусть они и имеются в наличии в меде, но на мой взгляд они достаточно дороги для своего функционала. Единственный способ заабузить эти мешки - вставить в медробота модуль печатки мешков где он может на блюспейс батарейке клепать их из воздуха пока не надоест. Еще скажу что на 20 минуте рауда когда уже привезли пачку ресурсов можно печатать продвинутые каталки которые являются операционным столом, стазисным мешком и каталкой одновременно. Единственный их минус на мой взгляд - их нельзя запихнуть в карманы как мешки.
 ### Я не уважаю обиду автора на культиста со стазис мешками.
 Стазис мешки работают не только на культистов, они точно так же могут спасти и тебя. Если культист убил тебя с лазерного карабина, то это не значит что нужно удалять лазерные карабины с карты.
 ### СТРОГО субъективное мнение Сударя0770
 Мешки отлично подходят для динамики игры и являются отличным инструментом не дать игроку умереть и бесцельно летать на призраке. Даже не взирая на то, что на станции изначально есть несколько мешков, то по моему опыту это не сильно выручает, на хаотике трупы наводняют мед и будь там хоть тысяча мешков, это не поможет делу. На ЕОСе пока спасающий тебя медик закончит эмоутить, то ты скончаешься вне зависимости от ран и стазиса ~от кринжа~
Мешки - хорошо. Геймдизайнеры приняли верное решение добавив мешки медикам раундстартом.

**Comment by Sudar0770** [comment]
Напротив я пишу новый Иссуй в комментах. Предлагаю добавить в приемки меда новый вид машин. Криокапсулы которые поддерживают стазис на пациенте ожидающего операции или внимания врача в целом. Мне кажется это адекватно и актуально для хаотика. Много космонавтиков умирают так и не дождавшийсь помощи.
Да, я понимаю, что криостазис существуют и в нем даже лечат людей, я предлагаю дешевые банки с людьми внутри которые просто замедляют смерть.
Из-за малого знания о билде по данной теме я мог допустить ошибки в своих суждениях. Прошу поправить меня там, где я не прав.

**Comment by DarkHunter7756** [comment]
> Предлагаю добавить в приемки меда новый вид машин. Криокапсулы которые поддерживают стазис на пациенте ожидающего операции или внимания врача в целом. 

Чел, у нас слиперы созданы для этого в частности

**Comment by TimErmolt** [comment]
> продвинутые каталки

Продвинутые каталки отличаются от обычных только спрайтом, [способностью складировать их в сумках](https://github.com/ChaoticOnyx/OnyxBay/blob/ba512723b33e7e8d1c2ec4b2233d0122ec16c207/code/game/objects/structures/stool_bed_chair_nest/bed.dm#L260) и [отсутствием замедления при пулле](https://github.com/ChaoticOnyx/OnyxBay/blob/ba512723b33e7e8d1c2ec4b2233d0122ec16c207/code/game/objects/structures/stool_bed_chair_nest/bed.dm#L224). Это никоим разом не альтернатива стазис-мешку, а просто прямой апгрейд обычной каталки. Стазис-мешок же, по логике, должен быть изучаемым ответвлением от каталок -- гораздо медленнее тащится и медленнее открывается, зато предоставляет пациенту стазис и кладётся в карманы. А он раундстартом.

> Стазис мешки работают не только на культистов, они точно так же могут спасти и тебя.

Это будет та же самая ситуация, только роли поменялись местами: культист на моём месте, а я и мои коллеги из СБ на местах культистов. И культист, вероятно, вряд ли будет рад тому, что его отчаянные попытки унести с собой как можно больше еретиков отменяются парамедиком с мешками. И нет, это не аннулирование деяний рольки, решившей помочить охранку, это дизбалансный предмет в медблоке.

> Много космонавтиков умирают так и не дождавшийсь помощи.

А это плохо? Как по мне, так суровый реализм, к коему мы даже вроде как стремимся. Конечно, игра должна при этом быть интересной для игроков, но если врачи идиоты, то врачи идиоты, и их не должны спасать от кары, от глав или педальной, стазисные мешки. А слаженная команда в медблоке найдёт уйму способов стабилизировать пациентов до того, как им смогут оказать полноценную помощь. Если такая очередь вовсе образуются, ибо 4 врача и СМО -- вообще мастер на все руки в медблоке -- фактически могут оказывать помощь 5 людям одновременно (медикаментов хватит с избытком, в слипере они бесконечные, даже если химики не работают -- эффект почти каждого лекарства можно повторить тем, что есть в медбоке раундстартом) или оперировать 3 человек нормальными инструментами, 4 -- если пошлют парамедика собрать инструменты из гетто-операционной, 5 -- если один из них не побрезгует взяться за кустарные аналоги инструментов. Как правило этого уже достаточно. Если врачей меньше, то есть и вовсе бесконечность способов увеличить их количество или КПД. Всё в руках игроков. Не справятся с этим -- смерти не получивших мед. помощь будут лежать на их плечах. Если это не проблема навыка, а сложившийся исход под влиянием обстоятельств (медблок разбомбили метеоры или взорвали террористы, врачей поубивал маньяк, лекарства украли ассистенты и т.д.), то, что тут сказать, такова игра. Говно случается.
Тем временем большинство трупов, оказывающихся в морге, уже находят мёртвыми на месте, то есть проблема не в некомпетентности врачей, а в том, что кучу людей убивают в техах, и никто не слышит их крик, либо происходят массовые перестрелки, драки, поножовщины и бойни в отделах, где в итоге все оказываются мёртвыми или при смерти. А это, получается, уже и не проблема, ибо такова игра.

> Предлагаю добавить в приемки меда новый вид машин.

Если даже не считать слиперы имеющими такую функциональность, это никак не решит проблему с оказуаливанием работы парамедиков, если данное нововведение не совместить с выпилом стазис-мешков или их нёрфом.
