### ISSUE TITLE
Sanity: базовая механика

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#7931]
### Улучшение
Добавляем переменную sanity - выступает как шкала психического здоровья персонажа. Имеет 2 порога, первый порог - максимальное значение при нормальном самочувствие персонажа, второй - максимальное значение под стимуляторами.
Также обозначаем коэффициент дебаффа который отвечает за понижение получаемого ресурса при каких-то условиях. 
Должны присутствовать флаги, маркирующие возможность или невозможность потери ресурса от определенных источников.

#### Пороги
- SANITY_TRESHOLD_NORMAL = 100
- SANITY_TRESHOLD_BUFFED = 200
#### Коэффициенты получения sanity 
- SANITY_GAIN_BUFF_MINOR = 1.1
- SANITY_GAIN_BUFF_MODERATE = 1.2
- SANITY_GAIN_BUFF_MAJOR = 1.4 

- SANITY_GAIN_DEBUFF_MINOR = 0.9
- SANITY_GAIN_DEBUFF_MODERATE = 0.7
- SANITY_GAIN_DEBUFF_MAJOR = 0.5 
#### Флаги условий
Данные обозначают подвержен ли человек изменению sanity от: зависимости, паранормальных проявлений, еды, возможности баффа/дебаффа.
- SANITY_AFFECTED_BUFF
- SANITY_AFFECTED_DEBUFF 
- SANITY_AFFECTED_ADDICTION
- SANITY_AFFECTED_PARANORMAL
- SANITY_AFFECTED_BUFF
- SANITY_AFFECTED_FOOD

**Comment by Ershovdi** [comment]
Нужно также сделать возможность педалям отключать и включать эту систему. На ЕОСе такая система - классная. На Хаотике? Плох, плох. Это моё мнение, как игрока обоих серверов. Правда, я все равно не понимаю, зачем эти модификаторы нужны.

**Comment by NefrNerf** [comment]
Система будет влиять не так сильно как кажется, сразу по названиям, основная задача - дать антагам и не только им, взаимодействовать с куклой не вредя ей непосредственно физически, чтобы не нужно было отправлять человека в блэкскрин или ломать что-то.

**Comment by NefrNerf** [comment]
А также это позволит как-то контролировать скорость :культификации, декультификации, возможные абилки для священника. Еще это будет большим бонусом для тех кто хочет отыгрывать зависимых/с фобиями. Людям которые не выбирали себе каких-то дефектов боятся нечего, основное что на них будет влиять - урон от боли, непосредственный числовой урон по характеристики от некоторых способностей антагов.

**Comment by Ershovdi** [comment]
> основная задача - дать антагам и не только им, взаимодействовать с куклой не вредя ей непосредственно физически

Можешь пояснить в деталях, как именно ты это видишь?

**Comment by NefrNerf** [comment]
Сейчас как раз расписываю по иссуям, но если коротко, есть кроме максимальных порогов, уровни статуса, на каждом уровне, персонаж будет получать различные баффы/дебаффы. Например, на при уровне 200-190, человека нельзя будет лолконвертнуть, но этот уровень достигается особым методом, а на уровне 10-0 человек не только автоматически культифицироватся будет, даже одним культистом, но если по шкале sanity будет атака какой-то абилкой, получит какой-то дамаг боль/брейн

**Comment by NefrNerf** [comment]
Это конечно можно назвать даже скорее morale, как моральное состояние персонажа, но первым делом подумал на sanity

**Comment by Animesku** [comment]
Нам точно это надо?

**Comment by NefrNerf** [comment]
Смотри, у нас сейчас есть: лолконверт/автостан вампира/автоконтроль борера. Это во многом введения нового ресурса для того, чтобы больше контролировать возможности антагов.

**Comment by Animesku** [comment]
И что это даст? Перед атакой на культ СБ теперь начнет конфеты есть, чтоб не лолконвертили никого?

**Comment by NefrNerf** [comment]
А кто сказал что конфеты им помогут? Я механику перехода между уровнями и механику уровней в других иссуях расписываю

**Comment by NefrNerf** [comment]
Есть у нас пойз, есть у нас пейн, болеутоляющие не дают тебе свалиться от боли. Повышенный пойз не дает тебе упасть от 1 удара. Так же и тут.

**Comment by Sudar0770** [comment]
Сударь0770 поддерживает идею. Загнобить гемофоба протаскивая его по крови будет гораздо веселее

**Comment by Sudar0770** [comment]
Сударь0770 поддерживает идею. Загнобить гемофоба протаскивая его по крови будет гораздо веселее

**Comment by igorsaux** [comment]
> Данные обозначают подвержен ли человек изменению sanity от: зависимости, паранормальных проявлений, еды, возможности баффа/дебаффа.
> - SANITY_AFFECTED_BUFF
> - SANITY_AFFECTED_DEBUFF 
> - SANITY_AFFECTED_ADDICTION
> - SANITY_AFFECTED_PARANORMAL
> - SANITY_AFFECTED_BUFF
> - SANITY_AFFECTED_FOOD

А смысл если это поведение по-умолчанию. Их надо инвертировать

**Comment by Animesku** [comment]
> А кто сказал что конфеты им помогут? Я механику перехода между уровнями и механику уровней в других иссуях расписываю

Ну это механодроч все равно

**Comment by NefrNerf** [comment]
> А смысл если это поведение по-умолчанию. Их надо инвертировать

Да, я просто указал модификаторы, на что будут влиять

**Comment by TimErmolt** [comment]
Странная какая-то фича. Вроде позиционируется как аналог пойза для абилок антагов; в то же время висит эта зловещая фраза:
> дать антагам **_и не только им_**

Что заставляет сию характеристику немного походить на очередное форсирование механом !!!!!ролеплея!!!!! а-ля "увидел труп -> испугался -> потерял сознание", когда я играю за СМО или ХоСа.
С другой стороны, динамическое изменение времени, необходимого для насильного конверта в культ и подобные фракции, мне как-то нравится, потому что заставит культ вкладывать в вербовку чуть больше усилий, чем два культиста с  книжкой и сумкой листочков с конфузом в гетто.
Не знаю, как по мне, всё решат методы понижения и повышения состояния рассудка (s a n i t y), но особенно понижения.

**Comment by NefrNerf** [comment]
В ПРе который я готовлю, будет только ввод переменных, механика не поменяется, по сравнению с тем что работает сейчас. Будет работать как пойз и только. Зависимости, фобии, алкоголь и баффы будут добавлены только после отдельного аппрува по каждому модулю.

**Comment by NefrNerf** [comment]
Что сайнити не будет делать 
- заставлять что-то делать с собой или кем-то другим
- отбирать контроль у пользователя
- ограничивать выполнение любых действий (успех операций например, точность стрельбы)

**Comment by Artemonim** [comment]
Почему бы не связать с брейндамагом?
