### ISSUE TITLE
Склянки с защитой от радиации

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#7939]
### Улучшение
Сделать склянки (бикеры), которые блокируют радиоактивность помещённых в них веществ. Иначе радиоактивные вещества вне химического раздатчика, вроде как, вообще нельзя безопасно хранить.
Такие склянки будут, конечно, только у химиков и в ограниченном количестве. Можно сделать их печатаемыми на автолате, по материалами -- столько же, сколько обычные бикеры, плюс сталь, где-нибудь 25% от количества стекла.

### Альтернативы
Если не хочется давать это химикам раундстартом, можно сделать их изучаемыми в РнД. Тогда про автолат речи не идёт, печататься будут на протолате.

**Comment by Nod404** [comment]
так они уже есть

**Comment by TobyThorne** [comment]
У химиков раундстартом есть два стакана из пластекла, блокирующего радиацию. Новые можно печатать в протолате. 
ОП изобрёл фичу, появившуюся в течение суток после добавления радиации от реагентов.
