### ISSUE TITLE
Добавить стационарные пушки

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#7961]
### Улучшение
В игре для обороны можно поставить турели, но иногда очень хочется сесть за тяжелый пулемет, плазмаган, еган и т.д.

### Решение
Предлагаю добавить в игру тяжелое стационарное вооружение к которому ты баклишься и стреляешь под определенным углом.
**Тяжелый пулемет**: дешевое, доступное и эффективное средство против пехоты на открытых пространствах. Шьет и шьет пока не расплавится ствол или не закончатся боеприпасы
**Тяжелый еган**: большой и мощный ствол с тяжеленным теплоотводом шьет лазером с огромной скорострельностью. Жрет энергию и благодаря теплоотводу не перегревается
**Тяжелый плазмаган**: мощь-пушка, стреляет сгустками раскаленной плазмы с низкой скорострельностью. Скорее всего из-за своего ущерба структуре станции не будет использоваться. Кушает энергию и из-за низкой скорострельности не гереется.
**Баллиста** и как-же без гетто аналога стационарных пушек? Стреляет одним ахуенно большим болтом с ахуенной кинетической мощью опрокидывающей цель на жопу ~(или в гроб)~ В отличии от остальных делается не из машины, а крафтится как арбалет, но требует стационарности и гораздо больше ресурсов. (Как же хочется увидеть как СБ штурмует каргонию, а те обороняются баллистами...)

### Баланс
Эти пушки должны быть гораздо сильнее своих легких аналогов, у пулемета выше плотность огня из-за больших ленточных магазинов, у егана из-за теплоотвода, плазмаган будет ебошить диким уроном.
Эти пушки могут как Дюранд в режиме защитном стрелять только в определенную сторону, зашедший сзади получит превосходство.
Эти пушки неподвижны, штумовать их грейтайдом тяжело без гранат или проделываний проходов в тыл, но разве это не весело?
Эти пушки дороги в получении. Пулемет можно достать только в карго, еган можно построить из платы, материалов и лазерной пушки. Тяжелый плазмаган будет нелегальной технологией и делаться примерно как и еган. Баллиста собирается из дерева, пластика, проводов и стали.
Боеприпасы: Пулемет может иметь в себе слот условного пояса. Заглянул внурть и закинул туда патроны нужные. Еган и Плазмаган кушают энергию и должны стоять на проводах, Баллиста кушает болты из стали (возможно это просто будут арматурины свареные вместе или типа того)

**Comment by DarkHunter7756** [comment]
Откуда берет энергию еган? Из станции? Тогда у тебя бесконечная пушка. Что не есть хорошо.
Какая стоимость покупки пулемета? Карго может стабильно зарабатывать на пару ригов или десяток материй. 
Какие технологии у платы егана? Превращение РнД в фортификацию на 10 минуте раунда - плохая идея

**Comment by DarkHunter7756** [comment]
Какой урон и дальность у баллисты? Не станет ли это очередным ваншот-оружием с гибом головы через пол карты?
Тоже самое про еган. Ибо лазерное оружие
Какие патроны можно загружать в тяжелый пулемет? Какие калибры? Какие виды?

**Comment by Zert0X** [comment]
Фича в обход фиче бота

**Comment by Sudar0770** [comment]
> Какой урон и дальность у баллисты? Не станет ли это очередным ваншот-оружием с гибом головы через пол карты? Тоже самое про еган. Ибо лазерное оружие Какие патроны можно загружать в тяжелый пулемет? Какие калибры? Какие виды?

Я конечно не геймдизайнер и не могу полностью понимать такое понятие как баланс, но пара идей у меня есть. 
Пулемёт по сути будет жрать 7.62
Технология егана как минимум должна требовать ресурсы и 5 уровень боевых технологий, 5 уровень на боевую систему, 7 уровень инженерии и 6 уровень манипуляции энергии. 
Баллиста исходя из её допотопных механик должна скорее выводить из строя, чем гибать и имеет крайне сомнительную бронепробиваемость. В моём представлении это выглядит как: Каргония заварила шлюзы и требует независимости. Щиткуры пошли на штурм со щитами, но прилетела большая арматура в коридор, и щиткур лежит на жопе ахуевающий от жизни. 
Стоимость пулемёта ещё посмотрю по сравнению со стоимостью прочего вооружения и их сравнения по условному "Цена/качество"
Как пушка для гиба бАшки подразумевается нелегальный плазмаган с медленным снарядом и высоким бронепробитием которая помимо нелегальных технологий 5 уровня будет требовать исследования плазмы и блюспейсаблюспейса и скорее всего будет открываться на моменте исследования вортекса.

**Comment by Sudar0770** [comment]
Ради справедливости скажу, что пушки питающиеся от станции имеют свои минусы в обмен на условную бесконечность. ЭМИ или отключение от сети превратят тяжёлый еган в  тяжелый не еган. 
Если еган всё ещё кажется слишком имбалансным, то есть 53378943357 способов сделать его менее популярным. 
Как пример - усложнить сборку. Допустим сначала сделать фрейм машины, поставить провода, плату, конденсаторы штук 6 и анализатор, закрутить отвёрткой и получить основу и далее к ней прикрутить лазеркэнон, раскрутить его отвёрткой, подключить провода, добавить сталь, вставить два манипулятора улучшенных(именно улучшенные как в мехах), добавить ещё провода, добавить пласталь и приварить всё. 
Если и этого мало, то можно сделать так, чтобы к тяжёлому егану прикреплялась консоль с которой и ведётся управление и стрельба. 
Я открыт для критики и предложений. Очень прошу вас накидать свои варианты, дополнения и мысли касательно этого иссуя

**Comment by Nod404** [comment]
> Фича в обход фиче бота

отрежьте ему уже гитхаб...

**Comment by Sudar0770** [comment]
> Фича в обход фиче бота

Чем это плохо?

**Comment by Zert0X** [comment]
> > Фича в обход фиче бота
> 
> Чем это плохо? 

Тем что у нас есть ценз в 30 лайков, и ты его скипаешл заливая фичу сразу сюда итого игроки не голосуют за надобность твоих фич.

**Comment by NefrNerf** [comment]
Ловла, фичебот нужен для простой отправки через дискорд и защиты от дебилов. Это не обязательный механизм

**Comment by Sudar0770** [comment]
> Какой урон и дальность у баллисты?

Дальность зависит от гравитации станции. Если гравитация есть, то в пределах видимости снаряд падает, если гравитации нет, то летит он пока на что-то не наткнется.

Кстати как идея может быть будет прикольно загружать в баллисту что-то помимо болтов? Типа огнетушители как экстренный снаряд, молотов для подавления штурма, пластиковый стаканчик для гиба СБ и т.д. Но если учесть, что желоб в баллисте только для болтов, то либо точность будет снижена и есть шанс запульнуть с погрешностью в несколько тайлов или же вовсе заклинить с шансом в 30%.

**Comment by Animesku** [comment]
> Тем что у нас есть ценз в 30 лайков, и ты его скипаешл заливая фичу сразу сюда итого игроки не голосуют за надобность твоих фич.
 
Нету никакого ценза у нас

**Comment by Animesku** [comment]
А за надобность вон, овнеры голосуют.
