### ISSUE TITLE
Добавить более четкий и приятный звук парированию

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#8001]
Парировать ниндзю ручкой из ПДА при должном умении можно, но иногда не понятно парирую я или нет ибо в бою нет времени читать логи боя и ничего не слышно почти.
Предлагаю добавить парированию звук который будет радовать ушки. По моему мнению это сильно увеличит популярность этого приема и позволит адекватно отслеживать окна для парирования.

**Comment by BooJ1K** [comment]
Так есть звук успешного парирования или нужен звук, "окна парирования?"
