### ISSUE TITLE
инвизо- и сеткопроблемы

### ISSUE THREAD

**Issue by Roxreic** [ChaoticOnyx/OnyxBay#801]
### Улучшение
В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.

- Решает проблему лошья с инвизом и сеткой (нинджа/ученые с прокачанным рнд)

### Решение
Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы.

- Выпилить инвиз из рнд. Наглухо. Тотали ломает баланс всей боевки, нету никакого челенжа играть против ролей, они просто берут, бегают в инвизе по всей станции даже не стараясь в стелс, потому-что их тупо не видно, дальше кого либо станят сеткой, которую практически нереально законтрить, если в тебя попали из невидимого состояния.

- Сделать инвизу полупрозрачность, как у генки, чтобы нинджа не был таким имбовым, а сетку понерфать до скорости черепахи, когда ты в неё попал, потому-что сейчас она тебя останавливает и пропадает через минуту, а сломать её можно только если у тебя изначально есть предмет в руке. Если можно, сделать так, чтобы термалы не могли видеть человека в инвизе за стенками.

- По возможности выпилить возможность телепортироваться с инвизом в РИГе, хотя это уже более глобальная проблема.

**Comment by Voldirs** [comment]
лайк, репост, подписка

**Comment by Srankl1n** [comment]
спасибо

**Comment by Srankl1n** [comment]
бля, еще забыл добавить, что из рнд стоит выпилить сеточку вместе с инвизом

**Comment by LLIkolnik** [comment]
МАКСИМАЛЬНЫЙ РЕПОСТ.

**Comment by Epicus7** [comment]
В целом, нерфоцирк и не нужно.

> Если можно, сделать так, чтобы термалы не могли видеть человека в инвизе за стенками.
Это надо отдельным багом писать.

С сеткой надо думать, мб норм.

Выпиливать инвиз из РнД точно нерфоцирк. Почему бы не добавить там где-нибудь рядом термальные какие-нибудь шлемы или еще чо? Вместо нерфоцирка просто добавить средства борьбы.

И вообще, такие вещи надо бить на несколько иссуев.

**Comment by Cinericius** [comment]
Вот выпилить инвиз из РнД точно надо, когда его вообще успели туда добавить (проиграю, если при мне)?
Сетку особо можно не нерфать, термалы тоже.
Сделать инвиз немножко видимым на ярком свету можно.

**Comment by Epicus7** [comment]
> Сделать инвиз немножко видимым на ярком свету можно.

Какая-то новая неоч очевидная механика. Оставляю плашку сложно.

**Comment by Cinericius** [comment]
Просто делаешь его не совсем невидимым, а чуть-чуть непрозрачным. Тогда на свету будет видно, а в темноте нит.

**Comment by kreeperHLC** [comment]
Оно конечно одобрено, но надо попилить на два иссуя. Один с выпилом инвиза из РнД, другой с нерфом инвиза. Сейчас название и описание иссуя сильно разнится с тем, что в итоге выбрали делать.
