### ISSUE TITLE
нюка

### ISSUE THREAD

**Issue by Srankl1n** [ChaoticOnyx/OnyxBay#803]
### Улучшение
В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.

- Переработка нюки.

### Решение
Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы.

- Выпил телепортера. Ломает баланс ввиде того, что нюкеры имеют халявные бомбы на своем шаттле, закидываю их в первые минуты раунда и рейдят капитанскую. Если подготовиться, то ядерную бомбу можно взорвать за 1 минуту от начала раунда.

- Ядерная бомба не работает без энергии в АПЦ. Nothing much to say

- Нюку каждый раз палит Икарус, и мне это не нравится. Сделать стелс по дефолту.

- Без джетпака бомбу нельзя нормально протащить по космосу, потому-что у неё нет ИНЕРЦИИ. Хотя, в принципе ни у одного обжекта нет инерции в космосе.

Может, есть еще какие проблемы, которые я не упомянул, но это основные.

**Comment by ifromspaceGANG** [comment]
https://github.com/ChaoticOnyx/OnyxBay/pull/830
