### ISSUE TITLE
Разнерфить голод

### ISSUE THREAD

**Issue by ITCups** [ChaoticOnyx/OnyxBay#81]
Голод сейчас по сути ни на что не влияет (кроме лечения и крови насколько мне известно)
Нужно придумать как голод будет влиять на человека и сделать кухню хоть чуточку полезной

**Comment by Cinericius** [comment]
Да, можно банально замедления там всякие или даже вынужденное переключение на шаг, типа силы кончились. Правда, возможно, стоит добавить возможность законтрить этот эффект выбросом адреналина, который наоборот должен форсить бег.

**Comment by Epicus7** [comment]
Ну думайте, чо. Придуймайте как это сделать, чтобы было интереснее и заводите отдельные проекты/иссуи. Запилим со временем.

**Comment by Cinericius** [comment]
Время пока не пришло.
