### ISSUE TITLE
Портировать/придумать геотермалку с Гунов

### ISSUE THREAD

**Issue by Zert0X** [ChaoticOnyx/OnyxBay#8160]
[Мануал](https://wiki.ss13.co/The_Goon_Geothermal_Capture_System_Field_Training_Manual)
[Статья на вики](https://wiki.ss13.co/Powering_the_station#The_geothermal_capture_system)
[Видосик как этим пользоваться, не уверен где но показано](https://www.youtube.com/watch?v=E8jBHLjSGr4)

**Comment by No-Tips** [comment]
Нам точно нужна геотермалка? Как по мне выглядит как абсолютно унылый shit с поиском одной точки на карте и интересным прокладыванием проводов от этой точки до смесов.

**Comment by osumico** [comment]
Не нужно.

**Comment by Zert0X** [comment]
> Не нужно.
> 

Обоснуй, а не высирай.

**Comment by intercepti0n** [comment]
Отваливается вместе с Поляркой в #11430.
