### ISSUE TITLE
Заменить синдикат на русских

### ISSUE THREAD

**Issue by Zert0X** [ChaoticOnyx/OnyxBay#8161]
### Суть
Не ну ледяная планета, го заменим синдикат на русских. Стилистически базу и снаряжение.

### Альтернатива
Добавить базу русских как дереликт для спавна гостов.

**Comment by Sudar0770** [comment]
Наконец-то достойная нюка. 
Вместо цианида водка
В РИГЕ по умолчанию встроен инъектор с водкой. 
Калашниковы как стандартное вооружение
И самым бомбезным будет перерисовка анимации взрыва ядерной боеголовки в виде Герба СССР?

**Comment by Filatelele** [comment]
#11430.
