### ISSUE TITLE
Добавить различных ивентов для полярки

### ISSUE THREAD

**Issue by Zert0X** [ChaoticOnyx/OnyxBay#8164]
1. Метель - создаёт на улице снег, понижает температуру(максимум до -90 на улице), некоторые шлюзы замерзают, видимость ухудшается
2. Набег волков(замените карпов на волков/медведей)
Придумайте что-то ещё

**Comment by No-Tips** [comment]
Инфестейшн из под земли какой-то ебалы?

**Comment by DarkHunter7756** [comment]
Жуки римворлда? ![image](https://user-images.githubusercontent.com/76823962/166224112-23daee1b-5161-4c1a-86a0-f570890853e6.png)
Нашествие медведей из-за границ экрана? 
Крушение осколка корабля/дроппода с мобами?

**Comment by NefrNerf** [comment]
Нашествия проблематичны, ибо у нас везде мины

**Comment by Zert0X** [comment]
> Нашествия проблематичны, ибо у нас везде мины

Смотреть #8162

У тебя мины сейчас как плейсхолдер обрыву

**Comment by No-Tips** [comment]
Да, жуки из римворлда. Я готов попробовать это накодить...

**Comment by Kexilex** [comment]
Гейтвей открывается случайным событием или гейтвей открывается при выполнении задачи экипажем. Гейтвей открывается куда-то, где есть ебаки и уникальные ништяки или куда-то, где спавнятся мидраунд антаги/спец роли выживших этсетера.

**Comment by Zert0X** [comment]
Гейтвей не уникален для полярки

**Comment by Sudar0770** [comment]
Аномальное потепление превращающее некоторые или всё тайлы снаружи станции на лёд со скользкостью смазки? По мне так хорошее подспорье антагам с ноуслип тапками

**Comment by Filatelele** [comment]
#11430.
