### ISSUE TITLE
Белый экран вместо UI.

### ISSUE THREAD

**Issue by TapKo4eB** [ChaoticOnyx/OnyxBay#818]
### Описание бага
Участились случаи ломания Юишек у жукбоксов/пда/иных инструментов с tgUI с чистой заменой окна на белый экран. Появляется раз на раз. Вроде не лечится.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Открываем что нибудь.
2. Видим это.
![image](https://user-images.githubusercontent.com/48761132/67495307-580e6d80-f683-11e9-8411-bef7be325e2d.png)

### Ожидаемое поведение
Восстановить былой вид UI'шек.

### (Опционально) Характеристики
 - OS: win 10
 - Версия клиента: 512.1488
 - Версия сервера: c4940f8c55920f1d246bcf4fdd2b311d60933dd9 - dev - 2019-10-22
 - ID игры: b3S-bJBh

**Comment by igorsaux** [comment]
https://github.com/ChaoticOnyx/OnyxBay/pull/819
