### ISSUE TITLE
Убрать термалы дефективу на Фронтире и заменить их на материалки

### ISSUE THREAD

**Issue by Zert0X** [ChaoticOnyx/OnyxBay#8260]
Убрать термалы дефективу на Фронтире и заменить их на материалки.

###Решение
Отхардкодить термалы у шкафа, положить поверх шкафа на исходе, генезисе, полярке, сансете
Положить  материалки поверх шкафа на фронтире

**Comment by DarkHunter7756** [comment]
А толку ему от мезонок? И почему ты создаешь иссуй без голосования в дискорде?

**Comment by Zert0X** [comment]
> А толку ему от мезонок? 

Потому что лид сказал, надо же сделать.

**Comment by DarkHunter7756** [comment]
Лид не разработки, а сервера. Если он хочет - сам напишет на гитхабе

**Comment by PlinHost** [comment]
> И почему ты создаешь иссуй без голосования в дискорде?

Вы заебали поднимать эту тему в каждом иссуе, дебилы, сука, ебаные, вам сто раз объясняли. От иссуй вотчера такое слышать вообще кринж

**Comment by Zert0X** [comment]
Иссуй поправлен

**Comment by vsss412** [comment]
Высказано резкое ФИ во всех инстанциях кроме лидовой. ЕОСа нет, лида его - нет, все против, вопрос поднимать отдельно когда-нибудь в далеком будущем.
