### ISSUE TITLE
Наномашины не работают

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#8278]
### Описание бага
Навыращивал томаты с наномашинами, нашел добровольца и тот не превращался, подумал что нужно не сам томат кормить, а блендерить его. Еще добровольца нашел и тот не превратился, сделал таблетки и третий ~Доброволец~ не превратился.
### Ожидаемое поведение
Наномашины должны превращать гуманоидов в боргов

**Comment by DarkHunter7756** [comment]
Поправьте, если не прав. Но вроде их на ЕОСе понерфили еще во время правления Альтхора. Где было произведено обнаружение бага?

**Comment by TobyThorne** [comment]
Наномашины превращают в борга только при передозировке (>5 единиц), с шансом в 20% за тик. До этого порога они работают как трик на максималках.
![image](https://user-images.githubusercontent.com/45202681/167472964-fd648d2a-202c-42c9-9352-505b58ba65c6.png)
