### ISSUE TITLE
Убрать тултип (Белую полоску внизу, которая показывает на какой предмет у вас наведена мышка)

### ISSUE THREAD

**Issue by kreeperHLC** [ChaoticOnyx/OnyxBay#8301]
### Улучшение
Плин сказал, что не нужно и во всех играх без этого обходятся.

### Решение
Не надо будет пилить обновленный тултип.

### (Опционально) Альтернативы
Сделать обновленный тултип. Эта идея проиграла, ибо Плин топит за убирание его из игры полностью.

**Comment by DarkHunter7756** [comment]
То есть если на полу лютый срач из 200 предметов, вы предлагаете не удобно наводить на нужный предмет ради узнавания названия, а открывать контактное меню, выводящее клиент на околоземную орбиту? Или протыкивать каждый нужный предмет экзамайном
![image](https://user-images.githubusercontent.com/76823962/167685653-8d62bea6-411b-4712-b274-0db457b47230.png)

**Comment by kreeperHLC** [comment]
> 

Плин сказал Да

**Comment by PlinHost** [comment]
> То есть если на полу лютый срач из 200 предметов, вы предлагаете не удобно наводить на нужный предмет ради узнавания названия, а открывать контактное меню, выводящее клиент на околоземную орбиту? Или протыкивать каждый нужный предмет экзамайном ![image](https://user-images.githubusercontent.com/76823962/167685653-8d62bea6-411b-4712-b274-0db457b47230.png)

Если на полу лютый срач, наведение не сильно поможет, удобнее использовать альт-клик или хотя бы пкм.

**Comment by DarkHunter7756** [comment]
![image](https://user-images.githubusercontent.com/76823962/167687266-e4743e3c-c173-4f6f-9904-4324d5fbba6a.png)

**Comment by Tsurupeta** [comment]
Давайте уберём ПКМ, а также добавим меню подбора одного предмета с пола из всего стака.

**Comment by Animesku** [comment]
Альтклик в радиусе 1 тайла всего работает, + нужно переходить в окошко турфа справа, что мешает, когда открыто что-то другое, + там раскрашиваемые спрайты остаются белыми и всякое прочее недоделанное.

Пкм багованный: может то включать объекты в содержимое тайла, то не включать, + не обновляется в реальном времени.
