### ISSUE TITLE
Мертвый вампир

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#8309]
Делаем вампира мертвым для сканеров датчиков и прочего если не прожата новая абилка revitalize.

revitalize - пассивная переключаемая абилка вампира, во включенном режиме постоянно потребляет кровь, вампир сохраняет цвет кожи, цвет глаз а также отображение на всех сканерах как живой и здоровый человек. В выключенном состоянии на датчиках отображается как труп, имеет описание как очень бледного человека, чем меньше запас крови в выключенном состоянии тем бледнее и мертвеннее.

**Comment by Sudar0770** [comment]
Как бледнота будет показываться на ящерах, котах и жабах?

**Comment by Tsurupeta** [comment]
Отключим им возможность становиться вампирами...

**Comment by Animusin** [comment]
Раздача приоритетов во имя вампирской расы!

**Comment by Epicus7** [comment]
Награда выдана
