### ISSUE TITLE
Макака ломается при отрезании головы держа ее в руках

### ISSUE THREAD

**Issue by SerJo2** [ChaoticOnyx/OnyxBay#8363]
Поломка макаки

Берешь в руки макаку и режущее. Режешь макаку по голове, пока голова не отваливается. После чего макака багается. На текстуре голова остается и рядом валяется еще одна.

### Скриншоты

![unknown](https://user-images.githubusercontent.com/60974487/168473033-09ee2644-9bd6-44ac-b5fd-8c004b070721.png)

**Comment by Terydd** [comment]
Не так давно фиксили обновление иконок кукол. Так же подобных проблем не наблюдалось крайне давно
