### ISSUE TITLE
Нелегальный гранатомет с кластерными светошумовыми гранатами для мехов не работает.

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#8388]
### Описание бага
Поставили этот гранатомет на мех, думая что он может быть заряжен взрывчаткой тестировали его на астероиде Фронтира. Стреляет кластером из светошумовых которые вместо взрыва просто исчезают. Кроме того гранатомет нельзя перезарядить, там всего 6 кластерок. Я как любитель светошумовых сильно прошу накодить работоспособные кластерные гранаты на мехи.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем кластерный гранатомет и ставим его на мех
2. стреляем гранатой куда-то
3. Видим ошибку взрыва нет, кластер просто исчезает

### Ожидаемое поведение
При выстреле кластер светошумовых гранат должен взорваться, разлететься по разным сторонам и там каждая его часть еще раз взорвется светом и шумом. А после этого можно будет перезарядить оружие как любое другое перезаряжаемое.

**Comment by BaraBarax** [comment]
https://github.com/ChaoticOnyx/OnyxBay/pull/11535

**Comment by BaraBarax** [comment]
https://github.com/ChaoticOnyx/OnyxBay/pull/11535
