### ISSUE TITLE
Понерфить автоматическое прицеливание у оружия

### ISSUE THREAD

**Issue by LagannPM** [ChaoticOnyx/OnyxBay#84]
Чтобы залочится на цель нужно 1-2 секунды чтобы цель не двигалась
иначе это имба
тот кто попал кликом с вероятностью 100% застрелит другого без лока

**Comment by Cinericius** [comment]
Да, можно добавить секундный делей.

**Comment by Epicus7** [comment]
Да, звучит толково. Тут еще надо уклонения починить, но это отдельная история.

**Comment by Fourest** [comment]
Тогда в наоборот будет бессмысленная хуйня, не будет смысла этим пользоваться, ведь цель тупо будет бегать покругу, и не лочится

**Comment by Cinericius** [comment]
Не, оно будет осмысленно, просто не для перестрелок, а для всяких арестов, засад и прочих таких вещей. А для перестрелок будет старое доброе закликивание.

**Comment by Fourest** [comment]
Как раз в этом случае тоже будет бессмысленно, как ты будешь арестовывать человека, если он будет от тебя убегать?

**Comment by LagannPM** [comment]
успел залочится - молодец изи добыча. Нет - кликай авось попадешь

**Comment by LagannPM** [comment]
секунда это не такое большое время

**Comment by Epicus7** [comment]
> Как раз в этом случае тоже будет бессмысленно, как ты будешь арестовывать человека, если он будет от тебя убегать?

Также как и раньше? Бежишь за ним и стреляешь из тайзера, пока не уронишь? Пинаешь дубинкой и арестовываешь, пока он в стане.
