### ISSUE TITLE
Сделать машинерию вирусолога полноценным конструируемым объектом

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8400]
На текущий момент инкубатор, центрифуга, изолятор, анализатор и сплайсер являются не разбираемыми, не улучшаемыми и не передвигаемыми объектами на карте. Решение - запилить это

1. Сборка: 
Платы достаются в принтере плат РнД. 

`Инкубатор патогенов`
Технологии: 4 био, 2 электромагнитная, 2 инженерная;

Состав: 1 Scanning Module, 2 Manipulator, 1 Beaker;

Улучшения:  от сканниг модуля повышение шансов мутации/удаления симптома/эволюции, от манипуляторов - скорость работы; от бикера - вместимость внутреннего бака. 

`Изолятор патогенов`

Технологии: 3 био, 2 инженерная

Состав: 1 Scanning Module, 3 Micro-Laser

Улучшения: скорость работы от лазеров; раскрытие антител вируса от сканнинг модуля 3 уровня 

`Сплайсер ДНК вирусов`
Технологии: 5 био, 4 электромагнитная, 2 инженерная, 3 дата;

Состав: 1 Scanning Module, 2 Micro-Laser, 1 Manipulator;

Улучшения: от лазеров - скорость работы, от сканнинг модуля и манипулятора - вероятность сохранения вируса при выделении симптома.

`Анализатор патогенов`
Технологии: 3 био, 4 электромагнитная, 2 инженерная;

Состав: 2 Scanning Module, 1 Micro-Laser;

Улучшения: скорость работы от сканнинг модуля и лазера. 

`Центрифуга`
Технологии: 2 био, 2 инженерная;

Состав: 3 Manipulator;

Улучшения: скорость работы от манипуляторов

Вся машинерия полностью становится разбираемой. Для монтажа требуется машин фрейм в сварочном меню. Демонтаж идентичен подобному у другой машинерии из машин фреймов.

**Comment by O0oMaximo0O** [comment]
Сплайсеру стоит поднять требование по биотехам. Манипуляции с генами, всё-таки.

**Comment by O0oMaximo0O** [comment]
Изолятору можно наоборот понизить. Capacitor лучше заменить на Scanning Module, он же сканирует кровь в шприце на наличие патогенов. В качестве улучшений для него можно сделать просмотр антигенов неизвестного вируса при более хорошем сканере.

**Comment by Sudar0770** [comment]
Плату сплайсера может купить торговец если я не ошибаюсь. Я её купил и собрал консоль вирусологическую. Могу ошибаться

**Comment by DarkHunter7756** [comment]
Могу ошибаться, но сплайсер не разбирается. Поправьте, если нет. В любом случае ждем геймдизов

**Comment by DarkHunter7756** [comment]
Тоже реализовано в #8441
