### ISSUE TITLE
Переработка структуры спрайтов из конкурса спрайтов

### ISSUE THREAD

**Issue by TermService** [ChaoticOnyx/OnyxBay#8408]
### Улучшение
Добавление спрайтов из заранее оговоренного списка в файлы билда.

**Comment by No-Tips** [comment]
У вас дубликат, мсье хеддев #3607

**Comment by DarkHunter7756** [comment]
БОЯН

**Comment by TermService** [comment]
пидорасы

**Comment by No-Tips** [comment]
4. Есть дубликаты? Проверить что на гитхабе уже нет похожих иссуев. Если есть, то написать об этом в комментарии со ссылкой на предыдущую такую же багу (в формате #1234), добавить плашку "дубликат" и закрыть иссуй. Если в иссуе предоставлена дополнительная информация, которая может помочь разобраться с предыдущей иссуей, об этом стоит упоминуть в первоначальной иссуе. Плашки областей, которые мы вешаем прошлым этапом, очень хорошо помогают выявлять дубликаты, т.к. искать среди них гораздо проще, чем сразу по всем иссуям билда.
