### ISSUE TITLE
Баг со спрайтом костюма NT.

### ISSUE THREAD

**Issue by Archazzy** [ChaoticOnyx/OnyxBay#841]
### Описание бага
Купив за мерчанта парочку пилотных костюмов NT и примерив один из них на себе, я обнаружил следующее: этот костюм просто не отображается на персонаже, как будто его спрайт еще не завезли на оникс. В результате мы, по сути, голые, хотя на персонаже уже надет этот костюм.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем в руки NanoTrasen flightsuit.
2. Надеваем его.
3. ???
PROFIT!

### Ожидаемое поведение
Персонаж должен быть одет в этот самый костюм, а не быть голым.

### Скриншоты

![а вот и сам баг](https://user-images.githubusercontent.com/57190168/67919447-e8dcd000-fbd2-11e9-90b2-7e3bd11e08a4.png)

**Comment by Archazzy** [comment]
ну, окей.
есть еще дохрена костюмов, которые не имеют спрайтов. (по большей части - те, которые не имеются на станции и доступны только в магазине/одежде актеров). Надеюсь, когда нибудь у господ разрабов руки дойдут до нарисовки новых спрайтов.

**Comment by kreeperHLC** [comment]
Спрайты то есть, просто пути потерялись. Было бы отлично, если бы писал английские названия сломанных костюмов.

**Comment by Archazzy** [comment]
Это нужно заходить за актора и весь шмот примерять, ну или на локалке чекать. По крайней мере, название этого костюма на пиндосском я написал.

**Comment by Epicus7** [comment]
Если костюмы не рисуются, возможно у них нет спрайта для тонкотрапов.

Если спрайта для тонкотрапов нет, то нужно либо рисовать (просить НянКома), либо выпиливать костюм из игры.

**Comment by Tsurupeta** [comment]
Посмотреол я - и его удалили из кода. Только спрайт униформы в иконках остался.
