### ISSUE TITLE
Раковая Флешкобоевка

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#8444]
Выставляем флешку на 1 секунду, кидаем любому под ноги и побеждаем.
Настоящий рак боевки, понерфите.

**Comment by TimErmolt** [comment]
Короче, писал пасту про кустарные методы контрить светшум, но в итоге пришёл к выводу, что лучший способ его понёрфить -- отпилить возможность настройки таймера отвёрткой. Будем тренировать способности считать 4 секунды в уме перед тем как кидать.

Альтернатива (сокращённая версия пасты) -- впилить самодельные шлемы с защитой ушей. Не за пять листов стали плюс сварку, естественно, но так, чтобы какой-нибудь отряд грейтайдеров из 3-4 человек можно было при слаженной подготовке снарядить.

**Comment by FloweYStyle** [comment]
Если у кого есть сомнения насчёт выпиливания 1 секундных флешек - на ТГ флешки имеют кулдаун в 5 секунд, ни больше ни меньше и там отлично практикуются.

**Comment by Tsurupeta** [comment]
ТГ кал. Не обсуждается.

**Comment by FloweYStyle** [comment]
Нет ты кал.

**Comment by Nod404** [comment]
> Альтернатива (сокращённая версия пасты) -- впилить самодельные шлемы с защитой ушей. Не за пять листов стали плюс сварку, естественно, но так, чтобы какой-нибудь отряд грейтайдеров из 3-4 человек можно было при слаженной подготовке снарядить.

У нас уже есть в билде наушники со стрельбища, но которые никак от шумо почему-то не защищают.

**Comment by TimErmolt** [comment]
> У нас уже есть в билде наушники со стрельбища, но которые никак от шумов почему-то не защищают.

У них защита вообще лучше всего -- 3 (1,5 на обоих ушах), когда у шлема 1, у шлемов скафандров -- 2. По крайней мере так в реворке светшума Тоби написано (#5719), и код соответствует. Хотя могло сломаться, не проверял в полевых условиях.

В любом случае за наушниками условным грейтайдерам придётся проникать на стрельбище, что крайне чревато палевом множеством способов. Я про какой-нибудь предмет защиты, который относительно шлемов и наушников из брига будет как зипган относительно оружия из арсенала -- не такой мощный, но сделать можно из говна и палок в техах. Например, упомянутый кустарный шлем, или какие-нибудь самодельные наушники, или банально беруши.
