### ISSUE TITLE
Сделать законы для боргов\ИИ рандомизируемыми.

### ISSUE THREAD

**Issue by FelixArzt** [ChaoticOnyx/OnyxBay#8471]
Каждый раунд с определенным шансом (40%) вместо корпоративных законов силиконовые получат один из:
Азимов
Тирант
Паладин
Робокоп

Реализация: вместо строчки с назначением корпоративных законов прикрутить список вышеперечисленных с рандомайзером. Можно сделать шанс корпоративных 60%.

### (Опционально) Дополнительная информация
Считаю что нам это нужно для разнообразия геймплея на силиконовых и увеличение просторов ролеплея.

**Comment by FelixArzt** [comment]
Если будет одобрение - сделаю сам.

**Comment by Doster-d** [comment]
Дубликат #1944

**Comment by Sudar0770** [comment]
#3633 когда-то подобный иссуй от меня закрыли
