### ISSUE TITLE
Развитие способностей борера

### ISSUE THREAD

**Issue by IvanDonFon** [ChaoticOnyx/OnyxBay#8475]
Добавить бореру возможности по манипулированию носителем помимо разговоров, а именно:
Отключение слуха/зрения(временное или постоянное);
Слуховые/зрительные(/тактильные?) галлюцинации, в виде админских наррейтов и/или как от наркотиков и/или иным образом.

Это позволит воздействовать на носителя не только зависящей от добросовестности игрока-носителя болью(Torment Host, которая тем более доступна только при полном контроле), но и со стороны механики игры.

Уточнить механику взаимодействия с носителем, что они идут через тело, нервную систему. Воля носителя напрямую не контролируется.

Вдохновлено данным заседанием суда
https://discord.com/channels/414832443384659968/570369482007117846/978748967884046366 

Является переносом [этой](https://discord.com/channels/414832443384659968/606411392811139072/978976937680715807) идеи из дискорда. Сообщение набрало 30 репапов, но по какой то причине, не перенослось на гитхаб.
Если ситуация изменится - удалю.

**Comment by O0oMaximo0O** [comment]
> Является переносом [этой](https://discord.com/channels/414832443384659968/606411392811139072/978976937680715807) идеи из дискорда. Сообщение набрало 30 репапов, но по какой то причине, не перенослось на гитхаб.

Потому что надо за вычетом репдаунов набрать 30.

Закрываю.

**Comment by IvanDonFon** [comment]
Ладно
