### ISSUE TITLE
Руна превращает камень в космос

### ISSUE THREAD

**Issue by Artem-fp** [ChaoticOnyx/OnyxBay#850]
Описание бага
Руна Defile превращает "стены" (камни) астероида в космос (Тайл с названием и спрайтом космоса) 

Скриншоты

![image](https://user-images.githubusercontent.com/55708534/68299597-fc0e0500-00d6-11ea-8c8c-61a78c021a22.png)

**Comment by Fritcher36** [comment]
Произошел пранк над дефайлерами астероида!
