### ISSUE TITLE
Меню шпионских жучков произвольно то включает, то выключает вид с камеры.

### ISSUE THREAD

**Issue by Animesku** [ChaoticOnyx/OnyxBay#8516]
Если привязать жучок (не важно сколько) к ПДА-монитору, а потом его открыть, то получаем то, что изображено на гифке. Режим камеры ритмично и самостоятельно то включается, то выключается. Так не только у меня, проблема не с моей стороны. 

![spybug](https://user-images.githubusercontent.com/48406301/171013658-2fc7f45c-0e71-4e61-9cb8-0f2627c6fa40.gif)

Client Version: 514
Server Revision: [86acf1d94a3b34bf602b38ab65ff3947afebcff8](https://github.com/ChaoticOnyx/OnyxBay/commit/86acf1d94a3b34bf602b38ab65ff3947afebcff8) - 602b38ab65ff3947afebcff8 - 2022-05-28
Game ID: cib-b3cu
Current map: NSS Exodus

**Comment by Doster-d** [comment]
Нет бы темплейтом воспользоваться.

**Comment by Animesku** [comment]
А очень надо?

**Comment by Filatelele** [comment]
Fixed in #11852
