### ISSUE TITLE
Интерактивная внутриигровая карта

### ISSUE THREAD

**Issue by Artemonim** [ChaoticOnyx/OnyxBay#8542]
### Улучшение
Добавить карту станции для лучшего ориентирования по станции

### Решение
Пробовал в #6751, но не по Сеньке шапка.

<details>
<summary>Там же предложили порт голокарты с CEV Eris</summary>

![image](https://user-images.githubusercontent.com/47484306/137799978-4a8b3dda-b1b0-4a03-b21d-963be9559535.png)

</details>

Мне бы очень хотелось иметь настенные бумажные карты и чтобы волшебным образом они в такой стилистике сами генерировались, но можно и портировать с Eris.
Также можно взять интерфейс карт из Camera Monitoring и сделать его более удобным для собственного ориентирования: точка "где я", подписи отделов, масштабирование и панорамирование.

**Comment by Sudar0770** [comment]
Предлагаю сделать карту как скачиваемую программу на компьютеры или по умолчанию в ПДА.
