### ISSUE TITLE
Меняем меч ниндзи

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#8544]
На данный момент, клинок ниндзи - полностью энергетический и потребляет энергию когда находиться в руках. Предлагаю заменить его на физический клинок с возможностью активации энергетического режима. Это позволит ниндзи, если он захочет, с меньшей летальностью применять свое оружие, а также при отсутствии энергии все также сражаться вблизи. 

Если все же идея проходит есть 2 пути ее реализации:
1. Даем возможность ниндзе терять клинок
2. Оставляем старую логику работы

При первом варианте, меч будет в слоте suit storage и являться полноценным предметом который ниндзя может потерять, но при этом затрат на создания клинка не будет.
При втором варианте, меч все также создается из костюма ниндзи и привязан к нему, а для повторного применения необходимо использовать способность РИГа.

**Comment by No-Tips** [comment]
То есть мы хотим сделать Dyrwyn мага, но ниндзе?

**Comment by NefrNerf** [comment]
Да

**Comment by ArmenianOnyx** [comment]
А можно пожалуйста поменять унылую вирусологию? Конченные мехи? Проклятую ксенобиологию и в целом РнД...
А... Нет?... 
Ладно... У нас же СУКА НЕЛЕТАЛЬНЫЙ МИРНОНИНЗЯ НЕ МОЖЕТ СВОИМ МЕЧЕМ НЕЛЕТАЛЬНО ХУЯРИТЬ ГОЛОВЫ. ААААААААААААААААА!!!

**Comment by NefrNerf** [comment]
А можно пожалуйста не срать где тебя не просят? Какого хуя ты не пишешь это под иссуями связанными связанными с вирусологией и РНД?

**Comment by MrMagick2104** [comment]
> При первом варианте, меч будет в слоте suit storage и являться полноценным предметом который ниндзя может потерять, но при этом затрат на создания клинка не будет.

Хранить меч в сьют сторадже не очень удобно. Может быть, ему ножны дать, которые вешаются на униформу и работают как кобура?
В билде уже есть.

Если его делать теряемым, то его нужно баффнуть как-то, с нашей боёвкой уже куда эффективнее залутать огнестрел и использовать его даже на текущий момент. Особенно с хранением меча в сьют сторадже - раундстартом выкидываешь меч и лутаешь кэплазер/пп/... по вкусу или в лучшем случае используешь его как сайдарм для блокирования прожектайлов.

**Comment by Sudar0770** [comment]
Физический меч с возможностью потерять его - круто. Использовать этот меч в летальному режиме сможет только носитель РИГа. К тому-же вернуть пропажу для ниндзи легко, это же не шляпа мага. 
Если ещё будет возможность при спауне выбрать его внешний вид и название, то это + 1000 к крутости.  А ещё лучше, если на  выбор будет несколько классов мечей типа:
Высокочастотный - игнорирует часть или всю броню
Огненный - наносит берн урон и может взаимодействовать с горящими объектами
Электрический - добавляет к урону эффект стана
Классический - ломает шлюзы и вообще емаг на минималках
Световой - дефлект снарядов
Ритуальный - вариант для хардкорщиков, по сути просто пласталевая катана.
