### ISSUE TITLE
Добавляем ниндзе сюрикены

### ISSUE THREAD

**Issue by NefrNerf** [ChaoticOnyx/OnyxBay#8545]
Часто бывает такое, что ниндзя не смотря на свою скрытную натуру берет оружие, предлагаю дать ниндзе энергетически сюрикены для того, чтобы он мог вести бой на средних дистанциях. 

Есть 2 реализации данного подхода
1. Дать ниндзе кламзи на использование огнестрельного оружия, тайзеры, еганы, пистолеты итд., но при этом сделать несколько режимов сюрикенов с малым потреблением энергии и маленьким КД: стан, дамаг
2. Даем только дамажные сюрикены и средним потреблением энергии и средним кд.

**Comment by BooJ1K** [comment]
Что тогда в таком случае будет с арбалетом нинжи? Останется или заменят на сюрикены? Какой дамаг будут вносить сюрикены?

**Comment by Sudar0770** [comment]
Считаю, что использование огнестрела у ниндзи отнимать не логично из-за его высокотехнологичности, однако с точки зрения "каноничности" он должен использовать только возможности своего костюма. 
У ниндзи есть тысяча возможностей навязать ближний бой в котором он безмерно хорош. Телепортация, сетка, невидимость, светошумовые и дымовые гранаты и даже термалки. 
Считаю, что использование огнестрела на ниндже - просто опция для "тяжёлой работки" которую игроку лень осуществлять творчески, и эта опция не заслуживает накидывания на нинджу кламзи. На мой взгляд это будет слишком радикально и убьёт часть вариативности.

**Comment by MrMagick2104** [comment]
> У ниндзи есть тысяча возможностей навязать ближний бой в котором он безмерно хорош.

Ближний бой в нашем билде сосёт огнестрелу в 98% случаев (как и должно быть), делать милишного антага - значит делать ходячий труп.
>1.Ниндзя навязывает ближний бой
>2.В ближнем бою ему стреляют поинтбланком один (1) раз
>3.Артериальное кровотечение, гроб гроб кладбище.

**Comment by Sudar0770** [comment]
> > У ниндзи есть тысяча возможностей навязать ближний бой в котором он безмерно хорош.
> 
> Ближний бой в нашем билде сосёт огнестрелу в 98% случаев (как и должно быть), делать милишного антага - значит делать ходячий труп.
> 
> > 1.Ниндзя навязывает ближний бой
> > 2.В ближнем бою ему стреляют поинтбланком один (1) раз
> > 3.Артериальное кровотечение, гроб гроб кладбище.

Но я говорил про его девайсы. Человек из сетки не сможет стрелять и ещё и оружие потеряет, человек в дымах будет бросаться из крайности в крайность, человек под флешбэнгом - синоним слову труп, не говоря уж про невидимость. Если нинджа посадит в РИГ Ии, то начнётся настоящий цирк с кишками и кровью. 
Не нужно смотреть на меч, как на основное оружие. Сам ниндзя - основное оружие.

**Comment by Tsurupeta** [comment]
> 1.Ниндзя навязывает ближний бой
> 2.В ближнем бою ему стреляют поинтбланком один (1) раз
> 3.Артериальное кровотечение, гроб гроб кладбище.

У СБ вырезали огнестрел, больше таких проблем не будет.

**Comment by DarkHunter7756** [comment]
У РнД, ЕРТ, бармена и детектива не вырезали огнестрел, такие проблемы будут

**Comment by Tsurupeta** [comment]
_У РнД не было огнестрела_, бармен против нинжи воевать не должен намеренно, у детектива огнестрел пососный.
А, забыл что у РнД ППшки есть.

**Comment by MrMagick2104** [comment]
> бармен против нинжи воевать не должен намеренно

Не мешает ассистенту украсть у бармена дробовик, спилить, взять 2 слага и сделать ниндзе рейд окончен (голова, глаза).
> у детектива огнестрел пососный

У него отстойный только .38, который мемеган. С Т9 или Тобигана подстрелить ниндзю вполне реально.

Алсо, карго.

**Comment by Oubi256** [comment]
@NefrNerf Как по мне, чисто идейно, **ниндзя вообще не должен превращаться в оперативника синдиката**, вооружаясь всем возможным огнестрелом. А вот специфичное оружие юзать должен на все 100%. Можно сверху еще повесить дебаф как на клоуна, который стреляя с оружия попадает, то в ногу себе, то в руку, но с меньшим проком и только на то оружие которое ниндзя не должен юзать, т.э. огнестрел.

**Comment by NefrNerf** [comment]
Я такое тоже поддерживаю, но тогда ему нужно больше способностей и инструментов
