### ISSUE TITLE
Борьба с альтернативной энергетикой

### ISSUE THREAD

**Issue by kemperhun** [ChaoticOnyx/OnyxBay#8551]
### Улучшение
_В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема._

С помощью коллекторов радиации и баночек с радием можно получить безопасную, экологически чистую, бесконечную и бесплатную энергию. Это плохо.

### Решение
_Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы._

1. Вводится новый тип излучения - **Энаквазиблюспейсовое излучение** (название временное). Всякие инженерные двигатели будут излучать его вместо (либо вместе с) радиации.
2. Коллекторы радиации переименовываются в **Коллекторы Энаквазиблюспейсового излучения** (название временное) и начинают генерировать энергию от излучения из пункта 1.
3. В инженерный отсек кладутся аналоги счетчика Гейгера, улавливающие уровень излучения из пункта 1 - **Счетчики Вейгера** (название временное).

Таким образом, чистая энергетика будет загнана в подполье педальгенов и солнечных панелей, что есть хорошо.

### (Опционально) Альтернативы
_Опишите альтернативы, о которых вы думали. Почему именно ваше решение является лучшим?_

1. Сделать радиоактивные материалы распадающимися - **анекдот в условиях двухчасовых смен**.
2. Понерфить коллекторы - **уже было и показало несостоятельность**.
3. Понерфить радиоактивное излучение от материалов - **его тогда никто не заметит, а обесценивание механики - это плохо**.

### (Опционально) Дополнительная информация
_Добавьте любую дополнительную информацию о вашей идее. Если у вас есть какие-то ресурсы - примеры внутриигрового текста, спрайты, картинки, звуки - обязательно прикрепите. Тогда шансов, что вашу идею реализуют, будет гораздо больше._

**Энаквазиблюспейсовое излучение** (название временное) в минимуме может быть полным респрайтом радиации. В максимуме - совершенно иной вид излучения, иначе действующий на людей и на предметы вокруг, нежели радиация. Или это может быть излучение, никак не воздействующее ни на что, кроме коллекторов

Для излучения, коллекторов и счетчиков стоит придумать более благозвучные названия.

**Comment by Artemonim** [comment]
> Сделать радиоактивные материалы распадающимися - анекдот в условиях двухчасовых смен.

У нас многие процессы проходят в ускоренном виде, так что период полураспада в 120 минут не будет чем-то нестандартным.

**Comment by Sudar0770** [comment]
Вариант с новым типом излучения звучит как некий костыль. Вариант с выветриванием радиоактивной лужи звучит гораздо лучше и логичнее. Сохнущие лужи которые постепенно теряют свою радиоактивность будут неким вариантом для запуска полностью обесточенного реактора. 
Ещё как вариант нерфа радиоактивной лужи предлагаю сделать так, чтобы эта самая лужа делалась химиками не из чистого радия а из  условного мутагена или любого другого более "стабильного" вещества, чем чистый радий или же сделать отдельный химикат предназначением которого будет создание радиоактивной лужи и прочего грифа.

**Comment by kemperhun** [comment]
Прикол в том, что радиация для радия изначально впиливалась не как вариант "энерголужи", а как [опасность для неосторожных химиков и средство саботажа](https://github.com/ChaoticOnyx/OnyxBay/issues/6594). Убирать радиацию у радия и оставлять специальной луже было бы странно.
Кроме того, радиевая лужа - по сути порошок, а не лужа; сохнущий порошок - это странно, и даже если мы предположим, что радий у нас не чистый, а в виде жидкого сай-фай-раствора, радиоактивность от засыхания бы не уменьшалась. 
Для обесточенного реактора у нас уже есть пакманы, которые даже работают на радиоактивном топливе(!)

> Вариант с новым типом излучения звучит как некий костыль

Некостыльным решением было бы перепилить радиоактивность так, чтобы реакция выделяла энергию в атмос, и делать атомные реакторы на ТЭГах, но это сложно,все равно потребует дальнейшего нерфа коллекторов (у которых сейчас сильно завышен КПД, судя по отношению "действие на человека дозы/энергия от дозы"), а еще сломает баланс радшторма. А из относительно легкореализуемых вариантов этот наименее костыльный, особенно если проработать ему другие последствия облучения.

**Comment by Epicus7** [comment]
Награда выдана
