### ISSUE TITLE
Создать альтернативную карту Фронтира с реактором на Суперматерии вместо Сингулярности.

### ISSUE THREAD

**Issue by Animusin** [ChaoticOnyx/OnyxBay#8552]
Сингулярность заебала сбегать, из-за этого все абузят радий-генераторы, либо плачут, пока их пожирает Лорд Сингуло.
Так что пока не починят Сингулярность (Никогда), нужно решить уже вопрос. Для этого:

Создать альтернативную карту Фронтира с реактором на Суперматерии вместо Сингулярности.

**Comment by No-Tips** [comment]
Одобряйте... Я просто перенесу. Ещё и попиксы за приоритет получу

**Comment by Zert0X** [comment]
Вам не разрешено лепить сложности

**Comment by Animusin** [comment]
> Вам не разрешено лепить сложности

Мне сказал лид Разработочки, я налепил

**Comment by Epicus7** [comment]
Награда выдана
