### ISSUE TITLE
Очищение С̶т̶р̶а̶т̶х̶о̶л̶ь̶м̶а̶  донат магазина

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8557]
Подборка донат предметов, незаслуженно имеющих высокую цену или вовсе практически во всем копирующих бесплатные аналоги
1 )Mime shoes имеет текстуру white shoes. 
"Уникальное" имя обойдется донатеру в 12 опиксов

![image](https://user-images.githubusercontent.com/76823962/171927862-271a815b-e2f6-4136-ba80-eb8ec7e5d02f.png)
![image](https://user-images.githubusercontent.com/76823962/171928989-25f7fb93-8244-4073-b9f5-01e080cd3177.png)

2) Charcoal suit, burgundy suit, chekered suit, navy suit, tan suit отличаются от amish suit лишь наличием пуговиц и изменением цвета штанов. Но стоят 10 опиксов каждый. Для сравнения за ту же сумму можно приобрести gotic dress, выгодно отличающийся от любых предметов
![image](https://user-images.githubusercontent.com/76823962/171935209-bfc25149-9c33-4d1c-9f49-1c80f6024bc2.png)
![image](https://user-images.githubusercontent.com/76823962/171935314-99d761a5-2be4-4099-a85a-1a21c92b1ca4.png)
![image](https://user-images.githubusercontent.com/76823962/171936084-2f3e6f6c-2b79-4e4b-88b2-2f264b2d2dbe.png)
![image](https://user-images.githubusercontent.com/76823962/171935425-6c134487-4053-4942-8c69-1ec226782bdd.png)
![image](https://user-images.githubusercontent.com/76823962/171937713-c7f1a605-b36b-42ae-af2f-43e87d9fb2e9.png)
![image](https://user-images.githubusercontent.com/76823962/171935550-0fdd1b7e-bbf0-49ad-99f1-79d7d9cafb62.png)
![image](https://user-images.githubusercontent.com/76823962/171935950-d4e9bac6-2431-4f58-94a7-35ecaf413f5d.png)

3) Short jumpskirt  это просто осветлённая версия black jumpskirt. 10 опиксов

![image](https://user-images.githubusercontent.com/76823962/171936608-40605aa8-008f-4693-936c-86ed68a1e846.png)
![image](https://user-images.githubusercontent.com/76823962/171937495-e400aae4-da7c-43df-ace5-2b46fb9842d1.png)

**Comment by IvanDonFon** [comment]
Electronic Arts момент
