### ISSUE TITLE
Дать возможность бить в ближнем бою при включенном блоке

### ISSUE THREAD

**Issue by No-Tips** [ChaoticOnyx/OnyxBay#8573]
### Улучшение
Все уже пять раз слышали о том, что оружие ближнего боя у нас сосет, потому что у нас нет возможности сократить дистанцию против тазеров-лазеров-прочей хуйни. Но еще хуже - даже если ты переблочил щитом в руке пару слагов, что в тебя летели, пока ты добегал до цели - тебе НЕОБХОДИМО отключить блок, чтобы ударить противника. Что фактически делает из персонажа абсолютно уязвимую мишень для пары слагов в ебало.

### Решение
Впилить возможность бить оружием ближнего боя при включенном блоке. Это будет будет интересным баффом ближнего боя, и может быть наконец-то поставит его на один уровень с огнестрелом. 

Особенно актуально с добавлением индивидуальных щитов сбшникам.

**Comment by Ershovdi** [comment]
How to troll:
1. Впиливаем фичу
2. Выбиваем нинжу раундстартом
3. Ставим блок есвордом нинжи
4. Бегаем убиваем СБ отражениями снарядов и одновременным хармом есвордом по голове
5. ???
6. Троллинг завершён

**Comment by No-Tips** [comment]
Да, видимо, надо сказать, что такое надо запилить при блокировании ЩИТОМ, а не всякой парашей.

**Comment by FloweYStyle** [comment]
Десворд отлично действует как щит. Иссуй как по мне надо отложить до лучших времён, когда переосмыслят блок и их единственную контру - флешбенги.

**Comment by Sudar0770** [comment]
Может просто разрешить атаковать основной рукой пока блок идёт оффхэндом? 
На мой взгляд это вполне логично.

**Comment by No-Tips** [comment]
А вообще, я сегодня потестил, и можно и так это делать. А вот вчера не мог. Либо что-то криво работает, либо автор (я) еблан.

**Comment by TobyThorne** [comment]
Из блока уже можно атаковать. Но только в течении полутора секунд после последнего успешного блока. 
Но есть проблема с тем, что блокирование выстрелов не обновляет last_block, только мили. Надо исправить.
