### ISSUE TITLE
Бафф температурной пушки (Temperature gun)

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8576]
Текущая реализация, являясь крайне ситуативной и мало вариативной, представляет собой оружие, нагревающее или охлаждающее только сущности гуманоидного типа (макаки, люди, ксеносы, ФБП). 

Ввиду около-нулевого потенциала ее использует минимум людей из научного отдела и практически никто из иных корпусов. 

Посему предлагаю добавить следующие механики:

1. Нагрев и охлаждение баллонов и канистр. Данная возможность позволит дистанционно обезвреживать или активировать лимитированные бомбы, а также быстро изготавливать горячие (вплоть до 500 градусов) или холодные (вплоть до 100К) смеси

1.1 Нагрев и охлаждение кристалла суперматерии. В объяснениях не нуждается

2. Тушение источников огня. Горящий человек или все тайлы, в которых побывал охлаждающий заряд температурной пушки будут потушены. Это повысит потенциал оружия в мирных целях. 

3. Воспламенение топливных луж и гуманоидов в горючем веществе при попадании высокотемпературного снаряда. Это повысит боевой потенциал

4. Охлаждение пола делает его скользким. Не убирает оружию специфичность использования, но дает интересные возможности. Чем ниже температура снаряда, попавшего в плитку - тем дольше держится эффект на плитке. Эффект аналогичен подсказыванию на воде, так что защита от подскальзывания работает и в этом случае. 

5. Возможность целиться в плитки пола. Разумеется, все вышеперечисленные идеи не будут работать, если снаряды будут пролетать мимо назначенной цели.

**Comment by Sudar0770** [comment]
Могу к этому ещё предложить интеракцию с девайсами типа с4 или асемблисами типа игнайтеров. Суть такова, что замороженные устройства температурной пушкой будут замедлять свой отклик - отсчёт. 
Пример: на РД повесили с4 которая взорвётся через минуту. Учёный нашёл своего руководителя и заморозил с4 до прибытия сапёрной команды.
