### ISSUE TITLE
Сделать floral somatoray более отзывчивым для игрока

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8585]
На текущий момент данный предмет крайне не отзывчив, из-за чего многие задаются вопросом - а он вообще работает?

Предлагаю ввести сообщение в чат при достижении снарядов floral somatoray в растения. 

Предлагаю ввести сообщение в чат при повышении yield растения от floral somatoray

`[растение нейм] is hit by the floral somatoray bolt`

**Comment by Tsurupeta** [comment]
Может, просто его вырезать? Он не работает и им никто не пользуется.

**Comment by DarkHunter7756** [comment]
У него есть потенциал дорогого, но бесконечного и желанного предмета для любого ботаника. 

Он работает. Мутирует растения, дает специфические мутации. Работу с генами не тестил. Только починить йелд и вкодить нормальный импакт.

**Comment by O0oMaximo0O** [comment]
yield работает. Просто не так как вы думаете. И вообще floral somatoray работает на гидропонную ванну, а не напрямую с растением. Но работает.

**Comment by O0oMaximo0O** [comment]
При сборке урожая из ванны там накидывается рандомно до 10 доп. ед. урожая.

**Comment by DarkHunter7756** [comment]
Никаких логов это не пишет.
