### ISSUE TITLE
Синтез нового вещества при использовании (испарении) суперкристалла материи

### ISSUE THREAD

**Issue by Artemonim** [ChaoticOnyx/OnyxBay#8594]
## Улучшение
При правильной настройке суперкристалл является вечным двигателем, производящий неиспользуемые игроками выхлопы. Мы можем как решить проблему его вечности, испаряя кристалл при добыче энергии, так и сделать реакции внутри реактора более ценными.

### Получение
При нагреве свыше 2000 градусов суперкристалл начинает выделять в атмосферу вокруг себя газообразное вещество. Вещество нужно отфильтровать из системы охлаждения и остудить в специальном ячеистом контейнере. После остывания материал можно достать из ячеек контейнера в виде слитков.
Есть пассивное ускорение от температуры, а также немного вещества испаряется от каждого попадания в кристалл лазерного луча.
После испарения большого количества вещества реактор нужно остановить и заправить новым кристаллом. Предполагаю, что это должно случатся через 2-3 часа работы при стандартной настройке реактора (2200 градусов и 1 эмиттер). Чтобы быстрее получить полезное вещество нужно сделать реактор мощнее.

### Выгода
- Благодаря твёрдости, плотности и тугоплавкости, данный материал можно использовать для создания брони с высокой защитой от физического и энергетического оружия. Однако, такую броню безопасно использовать только для укрепления мехов - пехотная броня и риги из подобного материала могут слабо облучать тех, кто их использует. Кроме того, возможно облучение персонала, создающего предметы из данного материала.
- Дополнительная экспортная позиция в карго.
- Дополнительный смысл увеличения выработки реактора.

## Что нужно сделать
- Ввести новый газ
- Ввести новый материал
- Продумать использование его в крафтах
- Ввести контейнер для конвертации газа в материал
- Продумать систему охлаждения, в которую будет помещаться контейнер и подводится труба из системы охлаждения реактора.

**Comment by Tsurupeta** [comment]
Создал бронежилет из хассия, а он испарился через 10 минут

**Comment by Artemonim** [comment]
> как можно быстрее остудить (допустим, что в нашей игровой вселенной этого достаточно, чтобы сделать стабильное твёрдое вещество из сверхрадиоактивного газа

**Comment by Battleparrot** [comment]
До кучи, чтобы оправдать намерение инженеров вырабатывать большое кол-во эл. энергии - добавить машинерию которая десублимирует хассий (превращает в пластины) с большим потреблением МВт.

**Comment by No-Tips** [comment]
Геймдизайнеры решили закрыть иссуй.

Высказались против: root, toor

**Comment by No-Tips** [comment]
Если договоритесь с гейдизами - впилю.

**Comment by NefrNerf** [comment]
Я правильно понимаю, что выпаривание материи может привести к ее удалению? А ещё, похоже испарения хассия позволят на коллекторах вырабатывать энергию?

**Comment by Artemonim** [comment]
> Я правильно понимаю, что выпаривание материи может привести к ее удалению?

Да. Я думаю, что стандартная настройка должна выпаривать кристалл за 2-3 часа, но так как это должно зависеть от температуры (а может быть ещё и от давления) решил не писать точных цифр.

> А ещё, похоже испарения хассия позволят на коллекторах вырабатывать энергию?

Я бы хотел, чтобы кристалл был стабилен сам по себе, а всю радиоактивность переложить на хассий. Ну а для того, чтобы его можно было не только отправлять на экспорт, но и использовать на станции - у него должна быть стабильная форма.
Можно усложнить это дело и сделать не просто охлаждение для стабилизации, а воткнуть куда-нить в середину древа развития РНД разработку стабилизатора хассия. Тогда хассий будет сверхрадиоактивным саморазлогающимся отходом реактора до тех пор, пока учёные не улучшат машинный зал - тем самым получив новый материал для крафтов и/или дорогой экспортный ресурс для карго.

**Comment by Artemonim** [comment]
Изначальная идея с охлаждением появилась для того, чтобы использовать комнату охлаждения газов. Не в текущем виде, но по сути.
![2022-06-08_16-42-47](https://user-images.githubusercontent.com/36363466/172631703-231569e5-d780-4a54-a98a-3897b7f1f1d0.png)

**Comment by Artemonim** [comment]
Я ещё забыл уточнить, что реакция распада это довольно сложная цепочка превращений из одного химического элемента в другой, а не просто исчезновение, но вряд ли нам нужно всё это продумывать и симулировать для хассия. Можем сразу превращать его в урановую пыль или радий, если он не был вовремя стабилизирован.

**Comment by Artemonim** [comment]
Redacted with Nefr.
