### ISSUE TITLE
Хранилище для дискет

### ISSUE THREAD

**Issue by Oubi256** [ChaoticOnyx/OnyxBay#8620]
### Улучшение
В вирусологии (да и не только там) существуют GNA disk-и, которые продуктивный вирусолог обычно выкладывает на стол для удобности. Всё бы ничего, но в итоге они начинают захламлять стол, да и в целом выглядит это не совсем привлекательно.

### Решение
Было бы круто иметь хранилище для GNA диско-в по аналогии с хранилищем для колб. Глаза любопытным СБ-шникам не мозолит, место на столе и в инвентаре не занимает.

### Дополнительная информация
viral box
![image](https://user-images.githubusercontent.com/98897017/173078570-3df7b712-9e9d-48df-a6fe-93e21d608900.png)
Реально существующий предмет, по которому можно нарисовать нечто с подобной стилистикой.
![image](https://user-images.githubusercontent.com/98897017/173078833-040eccd3-f8e1-48a4-9972-a94c71b3b9f3.png)

**Comment by No-Tips** [comment]
Для этого у нас сейчас там стоит ящик, да?

**Comment by Oubi256** [comment]
Нет. Ящик стоит для начальных вирусов.

**Comment by Tsurupeta** [comment]
В коробку сложи...
