### ISSUE TITLE
Changling vs Predator (задание на истребление генокрадов для ниндзи)

### ISSUE THREAD

**Issue by Artemonim** [ChaoticOnyx/OnyxBay#8641]
### Улучшение
Клан паука знает про генокрадов и считает их достойной целью для охоты

### Решение
Добавить в ротацию заданий ниндзи "захватить _n_ биоструктур"
Положить на корабль ниндзи переносной контейнер для удобного хранения биоструктур

**Comment by EliseyGladkiy** [comment]
Ожидание: достойное противостояние двух антагов 
Реальность: "LOOC NAGIBATOR228: Бля да падажжи, дай я из твоей структуры биоликвиду откачаю, я тоже поиграть хочу"
