### ISSUE TITLE
Переписать Hydroponics seed storage на ТГУИ

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8643]
Текущая реализация больше похожа на несмешную шутку. 

Белое меню. Гигантский список предметов. Откатывается в начало списка после выдачи КАЖДОГО предмета. Не вмещается вся информация в стандартный размер окна. 
![image](https://user-images.githubusercontent.com/76823962/173206657-6e27c9f4-349e-427b-b328-f15143afdb26.png)

Конкретики улучшения нет. На ваш вкус.

**Comment by Tsurupeta** [comment]
Не убирай мой последний бастион нормального интерфейса в мире отваливающихся нано и тгуи.

**Comment by O0oMaximo0O** [comment]
Поддерживаю

**Comment by O0oMaximo0O** [comment]
Можно добавить фильтры и апгрейднуть до фейкнано. И поправить размер окна.
