### ISSUE TITLE
Добавить мусоропровод на полярку

### ISSUE THREAD

**Issue by Artemonim** [ChaoticOnyx/OnyxBay#8653]

**Comment by Artemonim** [comment]
Только сейчас заметил обычные мусорки-корзинки.
Если эта система интересна, то добавить хотя бы одну транспортную мусорку в каждый корпус:
- Уборщик будет проходить по корпусу и выкидывать мусор в транспортную мусорку, а не переться к _???_ выкидывать мусор
- Транспортная система

**Comment by Artemonim** [comment]
Мусоропровод до введения машинерии-обработчика-мусора может вести на локацию-свалку.

**Comment by Tsurupeta** [comment]
Это преднамеренное решение убирать с полярки мусоропровод, чтобы у уборщика была нормальная работа.

**Comment by No-Tips** [comment]
Отсутствие мусоропровода на полярке фича
