### ISSUE TITLE
Машина для переработки мусорных отходов

### ISSUE THREAD

**Issue by Artemonim** [ChaoticOnyx/OnyxBay#8654]
### Улучшение
Сейчас 90% срача, летящего по мусоропроводу, невозможно ни обработать, не нормально утилизировать. Из-за этого у нас либо образуются пачки по 100 предметов на одном тайле, либо вечно летящий в космосе мусор, нагружающий МК.

### Решение
Предлагается добавить отдельную машинку, которая будет преобразовывать горы мусора в брикеты. Курс 5 предметов - 1 брикет. Брикеты эти можно использовать в строительстве, создавая свои мусорные стены, стулья и прочую утварь. Либо выбрасывать за ненадобностью.

### Альтернатива
Сделать машину с многоступенчатым развитием. В начале раунда это просто мусоросжигатель-генератор, но в последствии можно обвесить эту машину дополнительными модулями:
- Модуль сортировки мусора (перенаправляет указанные предметы с входящего конвеера на второстепенный исходящий)
- Можно заказать (или взять со склада) и подключить модуль переработки стекла
- Такой же модуль для металлов

### (Опционально) Дополнительная информация
Такая машина отлично подойдёт для #8653, из-за невозможности(нелогичности) выкидывания мусора просто за пределы карты.

---
Изначальный иссуй поддержан 28 лайками в Дискорд. Автор: Dark
Мною предложена Альтернатива

**Comment by Tsurupeta** [comment]
а полярка тут при чем?
