### ISSUE TITLE
Сделать Polytrinic Acid по настоящему едкой

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8679]
### Улучшение
Добавить Polytrinic Acid больше применений, чем расплавление лиц космонавтам

### Решение
Ввести нанесение урона при опрыскивании таких предметов, как: шлюзы, двери, стены, окна

### Опционально 
Ввести плавление небольших, но не поднимаемых объектов (стулья, коляски, капельницы, кресла и т.д)  с меньшим шансом, чем обычно.

**Comment by Sudar0770** [comment]
Но политриник разъедает только органику. Например синтетиков политриник не домажит

**Comment by DarkHunter7756** [comment]
Политринник разъедает интеркомы, ХУДы и протезы. 
![image](https://user-images.githubusercontent.com/76823962/173701786-ec44452e-b20a-4070-8415-502a756f9239.png)

**Comment by Sudar0770** [comment]
Но всё ещё не домажит ФБП. Мне кажется нужно либо исправлять то, что ты описал, либо исправлять вики в которой описываются его свойства

**Comment by Sudar0770** [comment]
Но всё ещё не домажит ФБП. Мне кажется нужно либо исправлять то, что ты описал, либо исправлять вики в которой описываются его свойства
