### ISSUE TITLE
Polytrinic Acid при распылении спреем не сжигает бумагу

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8681]
![dreamseeker_zUlXpyIgzR](https://user-images.githubusercontent.com/76823962/173698651-35310c82-4552-40cd-9097-3dfd90babc3a.gif)

**Comment by sephirothseeker** [comment]
У меня бумага спокойно сжигается

**Comment by Shirlineyn** [comment]
Ты кликаешь по тайлу, а не по предмету, гений

**Comment by Artemonim** [comment]
Бумага не сжигается ни по клику по тайлу, ни по клику по бумаге

**Comment by Shirlineyn** [comment]
вы попробовали бы сначала не 5, а 10 единицами поспреить
![GIF 6-19-2022 11-49-19 AM](https://user-images.githubusercontent.com/26092405/174473253-f0369271-81d2-4a4e-9bfc-e7dce4768013.gif)

**Comment by DarkHunter7756** [comment]
Ща бы спреить 10 единицами, когда 5 с первого пшика уничтожают тулбоксы, коробки, тонну весьма крепких предметов, А БУМАГУ НЕТ
