### ISSUE TITLE
Фосфор светится

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8683]
### Улучшение
Заставить фосфор работать по физике и инфе с вики
### Решение
Ввести люминесценцию емкостей с фосфором. Чем больше в емкости реагента - тем ярче свечение. Цвет свечения - зеленый. 

Chem-версия фонарика на случай апокалипсиса

### Дополнение

Ввести свечение таблеток с фосфором

**Comment by EliseyGladkiy** [comment]
Я как-то над фичей про фосфорные краски думал, но посчитал, что мою оценку к "Продавцу кошмаров" в иссуе не оценят

**Comment by Sudar0770** [comment]
Добавить возможность порезать глоустики и добыть из них фосфор

**Comment by Sudar0770** [comment]
Добавить возможность порезать глоустики и добыть из них фосфор

**Comment by DarkHunter7756** [comment]
> Добавить возможность порезать глоустики и добыть из них фосфор

Глоустики не из фосфора делаются. И работают не сразу
