### ISSUE TITLE
Ввести механику испарений реагентов 

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8684]
Для повышения реалистичности профессии химика и химикатов предлагаю ввести механику испарений. Как это работает:

Реализация 1:
- Вещества, способные к испарению, вызывают невидимый беззвучный дым
- Дым происходит каждые 5 секунд
- Дым затрачивает фиксированное количество юнитов реагента, зависящее от типа вещества, при срабатывании
- Дым не срабатывает при закрытой крышке
- Радиус дыма - 1 (тайл с емкостью + перекрестие ближайших тайлов)

Реализация 2: 
- Вещества, способные к испарению, пассивно вводят в желудок и/или кровь космонавтов реагент
- Каждую секунду вводится 0.05 реагента.
- Радиус испарения - 1
- Испарение не срабатывает при закрытой крышке

В обоих случаях противогаз или альтернативный источник кислорода (дыхательная маска/скафандр) защищает от испарения. 
В обоих случаях выливание реагента на пол или персонажа приводит к мгновенному срабатыванию эффекта испарения с повышенным вводом реагента. 

На данном этапе предлагаю ввести данную механику этанолу и...плазме?

**Comment by DarkHunter7756** [comment]
Мне пригодится ваше виденье какие реагенты стоят того, чтобы оказаться испаряемыми

А еще нужны ли нам отдельные эффекты при вдыхании? Например Аммиак при длительном вдыхании может вызвать головокружение

**Comment by Sudar0770** [comment]
Вода просто испаряется
Ацетон тоже вызывает головокружение, но гораздо позднее, чем аммиак. 
Ртуть при испарении должна захламлять печень в долгосрочной перспективе

**Comment by Shirlineyn** [comment]
Главный вопрос: От этого кому-то станет _интереснее_ играть, или это фича ради фичи?
