### ISSUE TITLE
Перемещение реагентов из спрея в ёмкости

### ISSUE THREAD

**Issue by Artemonim** [ChaoticOnyx/OnyxBay#8727]
### Улучшение
Дать возможность попшикать спреем по ёмкости. Полный объём аэрозоля должен переместиться в целевую ёмкость.
Если ёмкость уже полна - спрей оказывается на поверхности, на которой стоит ёмкость, или на руке, которая держит ёмкость.

**Comment by Oubi256** [comment]
Можно еще дать возможность открутить распылитель от ёмкости, для использования как обычная ёмкость. А то я хз как сейчас опустошить его не распрыскав всё на землю
