### ISSUE TITLE
Добавить улучшенный противогаз (БГМ) 

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#8745]
### Улучшение
Добавить в протолат противогаз в раздел "разное" с особым свойством позволяющим дышать даже без кислородного баллона в любых условиях. 
Первое рабочее название BGM (Bluespace gas mask)
Для создания на протолате потребуется пятый уровень блюспейс технологий, материалов и плазмы. 
Создаваться он будет из стали, стекла, пластика и алмазов. 
Предлагаю два вида этого устройства. Один вид будет мерцающим футуристичным противогазом синергирующим с дизайном bag of holding. Второй будет его версией, но без покрытия глаз (респиратор) с возможностью приспускать его как медицинскую маску. 
Носители БГМ не смогут использовать телепортацию основанную на блюспейс технологиях (вортекс, рифт генератор).

**Comment by Sudar0770** [comment]
Он будет иметь в себе технологии 1 уровень блюспейс технологий
4 уровень материалов и 1 уровень плазмы

**Comment by kreeperHLC** [comment]
Геймдиз забыл
