### ISSUE TITLE
Возможность менять размер педальных окошек 

### ISSUE THREAD

**Issue by JonMetal** [ChaoticOnyx/OnyxBay#8761]
Некоторые педальные окошки до ужаса мелкие, некоторые названия объектов не влезают толком. Неприятно.

**Comment by No-Tips** [comment]
Мышкой пробовал менять размер окна?

**Comment by JonMetal** [comment]
Да, у окошка дроппода не работало
Ещё Найтингель называл ряд других, где нельзя было менять размер

**Comment by No-Tips** [comment]
Так дай список, а то иссуй говно

**Comment by JonMetal** [comment]
Окей, на сервер зайду, посмотрю
Из тех, что назвал Найтингейл:
Выбор типа в варэдите, дебаг вербы связанные со спавном, окно выбора атома в адвансед билдмоде
