### ISSUE TITLE
Внешний вид донатмагазина

### ISSUE THREAD

**Issue by TermService** [ChaoticOnyx/OnyxBay#8774]
### Улучшение
Переработать донатный магазин в нормальный человеческий удобный вид, добавить возможность дарить донатные шмотки друзьям, добавить лутбоксы.

**Comment by No-Tips** [comment]
Оооооо лутбоксы, это нам надо.

**Comment by Tsurupeta** [comment]
Лутбоксам анимацию с гунов украсть можно
