### ISSUE TITLE
"Порт" танцев с *******

### ISSUE THREAD

**Issue by Tsurupeta** [ChaoticOnyx/OnyxBay#8775]
### Улучшение
Добавить танцы. Анимированные.

### Решение
Добавить отдельную кнопку во вкладку IC, которая будет называться "Dance". При нажатии её, игрок будет анимироваться и, грубо говоря, подпрыгивать вверх-вниз на несколько пикселей. Можно стоять на одном тайле и одновременно с этим крутиться стрелочками. При любом перемещении анимация сбрасывается. При повторном нажатии кнопки "Dance" анимация также сбрасывается.

### Альтернатива

"Анимация танца" будет просто замедлять, не сбрасываясь при хождении.

**Comment by NoneOfYourBsns** [comment]
Мне кажется, что это кто-то добавил в игру какое-то время назад.

**Comment by kreeperHLC** [comment]
> Мне кажется, что это кто-то добавил в игру какое-то время назад.

#9326
