### ISSUE TITLE
Добавить уничтожение ID карты при взрыве ПДА

### ISSUE THREAD

**Issue by Reroch** [ChaoticOnyx/OnyxBay#8791]
### Улучшение
Сейчас взрыв ПДА, фактически, бесполезен. Он слабый, он маленький, он уничтожает не особо и нужный ПДА. Считаю нужным добавить хоть что-то полезное, в виде уничтожения ID карты, вставленной в ПДА. Это соответствует логики взрыва.
### Решение
Э-э-э, удалять ID карту при взрыве ПДА, вместо выпадения карты на тайл.
### (Опционально) Альтернативы
Увеличить силу взрыва от ПДА?

**Comment by Sudar0770** [comment]
Карту не сжигает даже крематорий заботливо её выплевывая. 
Считаю, что уничтожение карты должно быть дорогим удовольствием

**Comment by Sudar0770** [comment]
Карту не сжигает даже крематорий заботливо её выплевывая. 
Считаю, что уничтожение карты должно быть дорогим удовольствием

**Comment by Tsurupeta** [comment]
> Карту не сжигает даже крематорий заботливо её выплевывая. Считаю, что уничтожение карты должно быть дорогим удовольствием

Это проблемы просто того, что при удалении предмета выплевывается его содержимое.

**Comment by TimErmolt** [comment]
> Считаю, что уничтожение карты должно быть дорогим удовольствием

Оно и есть дорогое. Если посягнёшь на КПК важной личности: охранника или главы, то можешь либо просто потерять детонацию, либо получить детонацию собственного КПК. Вместе со своей же карточкой и шансом на ЭМИ в морду, что особенно печально, если у тебя есть протезы.
Взрывать КПК всяких ассистентов конечно можно будет (особенно если они повыдавали себе полных доступов), но взрыв КПК того, кому трейтору скорее всего реально захочется устранить, потребует риска.
Ну и к тому же на сам картрирдж детоматикса придётся потратить телекристаллы. А их у трейтоты не то что бы много.
