### ISSUE TITLE
Постановка/снятие оружия на/с предохранителя в зависимости от интента

### ISSUE THREAD

**Issue by Artemonim** [ChaoticOnyx/OnyxBay#8797]
### Улучшение
- В игру вводятся предохранители оружия, не требующие дополнительной горячей клавиши для использования.

### Решение
У не самодельного стреляющего оружия появляется предохранитель.
При взятии в руки и при переключении интента проверяется интент. Если интент HELP - активируется предохранитель, если нет - предохранитель дезактивируется.
Переключение предохранителя сопровождается соответствующим звуком.

### (Опционально) Альтернативы
Предохранитель может быть уместен и в режиме DISARM, чтобы можно было бить прикладом без шанса на случайный выстрел.

**Comment by Tsurupeta** [comment]
зачем

Их наоборот выпиливали из игры. Зачем-то. А сейчас возвращать?

**Comment by Zert0X** [comment]
Убери, фу кака

**Comment by MrMagick2104** [comment]
Кринж, на всех нормальных билдах этот мусор выпилен, либо чисто опционален, при том выключен по дефолту.
