### ISSUE TITLE
Карты и свои скайбоксы

### ISSUE THREAD

**Issue by Tsurupeta** [ChaoticOnyx/OnyxBay#8799]
### Улучшение

Привязать к каждой карте отдельный скайбокс.

### Решение

Закинуть в папку скайбоксов задники космоса для каждой карты и в зависимости от выбранной карты, менять его.

### (Опционально) Дополнительная информация

<details>
<summary>Пример картинок</summary>

![bg14](https://user-images.githubusercontent.com/41485301/175822206-f744fb8e-3d81-4356-8e5c-31034bbf8f52.png)
![bg15](https://user-images.githubusercontent.com/41485301/175822207-561288ab-bd5a-4495-a81f-a60b67733440.png)
![bg00](https://user-images.githubusercontent.com/41485301/175822208-1b9985ee-bb1b-4f3a-b10e-e3b31e899494.png)
![bg01](https://user-images.githubusercontent.com/41485301/175822209-a6378b06-236a-478c-a5f0-bbb721ac031a.png)
![bg02](https://user-images.githubusercontent.com/41485301/175822211-6a06146a-4ad8-4f90-a8f4-c711f5f342c8.png)

</details>

Вот такое на фронтир можно, например. Один из этих.

**Comment by Primudash** [comment]
Дубль #7313
