### ISSUE TITLE
Чат агентов Синдиката в аплинке

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#8816]
### Улучшение
Полуанонимный чат для синдикатовцев, доступный в аплинке. В качестве имени пользователя используется пароль от аплинка, через который входят в чат, если аплинк в КПК, иначе случайно сгенерированный юзернейм в том же формате. Нюкеры, если они есть, тоже могут пользоваться чатом. Пароль для входа в чат не требуется -- то есть, если у незадачливого агента спёрли аплинк, то могут чатиться из-под его ника.

По функционалу чат аналогичен чат-клиенту в консолях с одним каналом и равными правами всех участников. Можно посылать текстовые сообщения.

Это по сути альтернатива АООСу, но только для синдикатовцев и внутри игры. Новичок, попавший на роль, сможет спросить у других агентов, что ему делать; в то же время агенты могут выяснять отношения по поводу контрактов, а нюкеры смогут разузнать обстановку на станции, пообщавшись с трейторами. А арестовавшие трейтора охранники -- следить за общением агентов, участвовать в нём, притворяясь одним из них, и навыками дедукции угадывать, кто скрывается под ником в чате. Правильно или же нет.

Можно подумать, что эта фича сделает бесполезным ключ для наушника с трейторским каналом, но не совсем. Для пользования чатом надо достать аплинк, ввести пароль (если он в КПК или наушнике), открыть чат и напечатать сообщение. Притом ты никак не сменишь имя пользователя, и у тебя могут легко украсть личность в чате вместе с аплинком.
Для передачи сообщения по каналу через наушник же нужно только его напечатать (ну, сказать), и если наушник у трейтора заберут, то смогут только слушать, а не говорить, иначе раскроют себя. Но общающихся в канале при этом смогут узнать по голосу, если те не пользуются войсчейнджерами. Так что ключ для наушника остаётся платной заменой чату, пригодящейся, когда надо быстро координировать действия в реальном времени или подключить к каналу кого-то, кто не имеет с собой аплинка.

### (Опционально) Дополнительная информация
Вообще не знаю конкретно, как работает генерация паролей от аплинков и интерфейс самих аплинков, поэтому с технической точки зрения не могу сказать, как можно реализовать. Но сам концепт расписал.

Ещё ниндзя спавнится (или раньше спавнился, может, уже выпилили) с аплинком без телекристаллов, но если впилить чат, то его он использовать сможет. Тут уж не знаю, баг ли или фича, но я б оставил, почему нет. Клан Паука не дешёвая организация и внедрить своего в локальный чат синдикатовцев точно сможет.

**Comment by Tsurupeta** [comment]
А зачем палить пароль от аплинка внутри ника всем? Если я знаю, что Эпсилон327 это повар, я могу захуярить повара и украсть его тк с ПДА?

**Comment by IvanDonFon** [comment]
Чел, у триторов личерали есть код шифрования для наушника, который исполняет ту же самую функцию

**Comment by TimErmolt** [comment]
> А зачем палить пароль от аплинка внутри ника всем? Если я знаю, что Эпсилон327 это повар, я могу захуярить повара и украсть его тк с ПДА?

Эпсилон 327 может и не говорить, что он повар. Это почти как хайвмайнд генокрадов. По одному лишь паролю личность не определишь. Если проговорился -- его проблемы. К тому же, разве воюющие между собой трейторы -- это плохо?

**Comment by TimErmolt** [comment]
> Чел, у триторов личерали есть код шифрования для наушника, который исполняет ту же самую функцию

Ты текст иссуя читал или нет? Прочитай, пожалуйста.
