### ISSUE TITLE
Аугментика 

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8818]
Вдохновленная https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Bionics система аугментаций, механики их запитывания и многого другого
### Глава первая: источники питания:
Любой имплант требует энергию для активации, а иногда и активной работы. Для решения этой проблемы были созданы внутренние источники питания:
- (ТОРС) Battery System - аналог батареи ФБП является основным модулем питания аугментики и хранения энергии. Для ФБП соответственно не нужен. В одном персонаже может быть только один данный модуль. 
- :low_brightness: :two: (ТОРС) Cable Charger System - аугмент открывает абилку схожую с оной у IPC с ТГ. При использовании абилки в руку кладется провод, который можно завести в АПЦ и питать внутреннею батарейку.  Заряжает 50 единиц заряда в секунду
- :low_brightness: :two: (ТОРС) Ethanol Burner - Потребляет этанол, генерируя энергию. Также повышает температуру тела при работе, что может пригодиться в холодном климате. Заряжает 10 заряда за 1 юнит этанола.
- :low_brightness: :two: (ГРОИН) Joint Torsion Ratchet - Генерирует 10 энергии в секунду во время перемещения после активации абилкой. Тратит пойз и при достижении низкого показателя дезактивируется автоматически. Повторное нажатие на активированный модуль отключает его. 
- :low_brightness: :two: (ГРОИН) Metabolic Interchange - Потребляет сытость персонажа, генерируя энергию. Автоматически отключается при достижении критического уровня голода, о чем говорит в чат.
- 1️⃣  (ГРОИН, ТОРС, ГОЛОВА) Trickle Charger - Маломощный долгодействующий источник питания, не требующий потребления чего бы то ни было. Каждый чаржер генерирует 5 единиц энергии в секунду
### Глава вторая: аугментации

Среди них: 

БОЕВЫЕ:

-  :anger: 2️⃣ : (ГОЛОВА)  Anti-Glare Compensators. Существенно снижает оглушение от флешбенков, флешек, флеш-порошка и сварки при активации. В противовес преимуществам уменьшает радиус обзора на 2 тайла. (вместо 8 - 6). 
ЭМИ приводит к временной слепоте. Уничтожение аугмента приводит к постоянной слепоте. 
Активация и деактивация абилкой стоят 100 заряда, но имеют КД в 15 секунд. 
- :anger: :two: (РУКИ, ГОЛОВА, НОГИ, ГРОИН, НОГИ) Alloy Plating. Броня, внедренная прямо в кожу. Поглощает любой урон до окончания собственной прочности.  ЭМИ воздействие бесполезно.
- :anger: :three: (ТОРС) EMP Defence Field Generator. Крайне энергопотребляемый аугмент (100 в секунду), рассеивающий ЭМИ и не дающий другой аугментике попасть под его влияние. Каждый съеденный выстрел слабого ЭМИ забирает у батареи персонажа 20% энергии. Выстрелы ионных винтовок забирают 50%. Активация абилкой. При попадании иона в неактивный щит, аугмент полностью сгорает. 
- :anger: :three: (РУКИ) Monomolecular Blade. По аналогии с Integrated Toolset, выдвижной меч. Наносит небольшой урон брутом, но имеется возможность активации в руке. При этом урон становится берном, увеличивается в пару раз. 
ЭМИ приводит к выдвиганию лезвия, а если уже выдвинуто - деактивации. Сильное повреждение ломает функцию деактивации, отключает режим дополнительного урона, оставляя человека с рукой-мертвым-грузом. 
Потребление энергии на выдвижение 200, на деактивацию 200. Дополнительный режим тратит 40 единиц заряда в секунду и каждый удар по противнику забирает еще 200

ГРАЖДАНСКИЕ:

-  :red_circle: :three:  (РУКИ) Integrated Toolset. Превращая руки в швейцарский нож инженера. Добавляет абилку, позволяющую превратить руку в инструмент, похожий в применении на хирургический модуль киборга. 
![image](https://user-images.githubusercontent.com/76823962/176142104-644a9452-80f8-4378-96e9-dd8d2a8377c0.png)
Со стороны механа это сродни армблейду генокрада. В руку вкладывается предмет, который нельзя выбить дизармом или уронить. Среди возможных инструментов есть: отвертка, лом, сварка, мультитул, кусачки, гаечный ключ. 

На активацию аугментации тратится 300. На смену используемого инструмента 15. Деактивация бесплатна. 
Сильное повреждение аугмента с помощью ЭМИ или другого оружия приводит к невозможности деактивации. Единичное применение ЭМИ вызывает самопроизвольную активацию аугмента. 

- 🔴 3️⃣ (РУКИ) Integrated Medical Toolset. Тот же Integrated Toolset с теми же механиками и потреблением. Но вместо инструментов идут хирургические инструменты 

- :yellow_circle: 2️⃣  (ГОЛОВА) Air Filtration System. Является аналогом противогаза, при включении абилкой потребляет 5 в секунду. Ионное воздействие приводит к временному удушью космонавта.

- :green_circle: :one: (ГОЛОВА) Internal Geiger Counter. Выводит в вкладку статуса уровень радиации. Потребляет 2 в секунду. От ЭМИ начинает выводить 9999999 единиц радиации в статусе на 2 минуты.

- :yellow_circle: :three: (ГРОИН) Blood Filter. Выводит из организма токсины, яды, алкоголь и прочие вредные химикаты. Не дает напиться или ускориться гиперзином, но в обмен позволяет оставаться живым при сильном облучении радиацией или отравлении. Энергию не тратит, но занимает существенный объем в теле. Отключению не подлежит.

- :yellow_circle: :two: (ТОРС) Leukocyte Breeder System. Повышает эффективность любого лечения, но взамен отключает иммунитет организма. Любой вирус через чихание, кашель, сопли, укусы мышей или другие методы заражения 100% попадет в организм. Не тратит энергию, но и отключить нельзя.

- :yellow_circle: :two: (ГОЛОВА) Implanted Night Vision. Принцип работы аналогичен очкам ночного зрения. Потребляет пассивно 7 единиц заряда после активации. ЭМИ уничтожает с 1 попадания, повреждая глаза.

- :green_circle: :one: (ГОЛОВА) Blood Analysis. При активации выводит в чат список реагентов, в текущий момент находящихся в крови. После ЭМИ не работает 2 минуты. Устанавливается в грудь. На активацию затрачивает 50 единиц заряда. 

-  :red_circle: :three: (ТОРС) Sonic Resonator. Вызывает вибрации, уничтожающие каменные породы в радиусе 3 тайлов при активации. Требует 200 энергии на единоразовое использование. Имеет КД в 5 секунд. При воздействии ЭМИ в тех же 3 тайлах радиуса оглушает всех игроков, вынуждая их упасть, после чего ломается полностью.

- :yellow_circle: :two: (ГРОИН) Hydraulic Muscles во время своей пассивной работы потребляет 20 единиц энергии в секунду, немного ускоряет и отключает замедление от голодания. Любые бонусы к скорости (гиперзин, мулл, особенность таяр) не воздействуют на скорость при активном аугменте.  При уничтожении замедляет перемещение

АУГМЕНТЫ ПРЕДАТЕЛЯ
данные аугменты продаются в аплинке

- (6ТК) :two: (РУКИ)Hand-Mounted Laser. Небольшой еган, выдвигаемый абилкой по аналогии с арблейдом генокрада. Имеет емкость в 6 зарядов, перезарядка производится через использование предмета в руке. Выстрелы энергию батареи персонажа не требуют, требует лишь перезарядка, но существенно (700). ЭМИ разряжает еган, одним выстрелом обнуляя боезапас. Сильное повреждение аугмента не дает пользователю его деактивировать. 

- (3ТК) :one: (РУКИ) Finger Razors.  Незаметная простому взгляду замена ногтей аналогом из прочного и острого материала. Повышает урон пустой руки, не тратя энергии на использование. 
- (6ТК) :three: (РУКИ) Monomolecular Blade.
- (4ТК) :three: (ГРОИН) Artificial Night Generator при активации посылает специальное излучение, ломающее все лампочки в радиусе 6 тайлов. Стоит такой праздник 1000 единиц энергии. Попадание ЭМИ мгновенно уничтожает аугмент, нанося берн урон персонажу. 
- (1ТК) Battery System
- (2ТК) Все источники питания

### Глава третья: Методы получения

Основным методом получения имплантов является exosuit fabricator робототехника. 

Информационные аугменты (помеченные :green_circle: ) требуют 3 уровень биологии и 3 уровень теории данных. Каких-то продвинутых ресурсов им не требуется. 
Аугменты, меняющие биологию тела (помеченные :yellow_circle: ) требуют 5 уровень биологии и 3 уровень инженерии. Для них потребуется золото и серебро
Аугменты, увеличивающие возможности персонажа ( :red_circle:) требуют 5 уровень биологии и 5 уровень электромагнетизма. Если они связаны с боевым применением (:anger: ), то к этим технологиям прибавляется 5 уровень боевых технологий. Все они требуют алмазы, уран, плазму. 
Источники питания (:low_brightness:) требуют 4 уровень технологий питания, 3 уровень биологии. Все они требуют плазму.  Исключением является Battery System и Trickle Charger, они доступны на старте раунда. 

### Глава четвертая: Вкладка аугментации
Для упрощения использования вся активируемая аугментика обладает вербом включения в правой панели экрана. При установке первого аугмента вкладка появляется. 

### Глава пятая: Урон

Любая аугментика получает СУЩЕСТВЕННЫЙ урон от ЭМИ. На полное уничтожение хватает 2-3 ионных болтов слабой мощности или 1 болт сильной (с ионной винтовки).  При достижении критического уровня повреждений аугмента, он отключается, исчезает с вкладки аугментов. Чинятся аугменты нанопастой после хирургического раскрытия части тела

### Глава шестая: Аугментная вместительность.

Любой имплант занимает место. Показатели объема каждого импланта обозначены :one:  :two: :three:

Голова вмещает 5 единиц емкости
Торс вмещает 7 единиц емкости
Гроин вмещает 7 единиц емкости
Руки вмещают 4 единицы емкости
Ноги вмещают 4 единицы емкости

В одну часть тела невозможно вставить два одинаковых импланта.

**Comment by DarkHunter7756** [comment]
Жду ониксоидов для критики. Оффтоп не жду

**Comment by ghost** [comment]
Могу закодить.🙃

**Comment by NefrNerf** [comment]
> Alloy Plating. Броня, внедренная прямо в кожу. Поглощает любой урон до окончания собственной прочности.

Звучит имбово

>  EMP Defence Field Generator. Крайне энергопотребляемый аугмент (100 в секунду), рассеивающий ЭМИ и не дающий другой аугментике попасть под его влияние. Каждый съеденный выстрел забирает у батареи персонажа 20% энергии. Активация абилкой

Точно нет

> yellow_circle Air Filtration System. Является аналогом противогаза, при включении абилкой потребляет 5 в секунду. Ионное воздействие не приводит к уникальным эффектам. Устанавливается в торс.

При ЭМИ должен задыхаться

> yellow_circle Blood Filter. Выводит из организма токсины, яды, алкоголь и прочие вредные химикаты. Не дает напиться или ускориться гиперзином, но в обмен позволяет оставаться живым при сильном облучении радиацией или отравлении. Энергию не тратит. Отключению не подлежит. Устанавливается в грудь.
Имба

**Comment by DarkHunter7756** [comment]
Имба даже с учетом стоимости в золоте?

**Comment by NefrNerf** [comment]
Если имплант не потребляет энергию постоянно, то он должен уменьшать максимальное количество заряда перманентно, например с системой фильтрации батарея режется с 1000 до 800

**Comment by NefrNerf** [comment]
> Поглощает любой урон до окончания собственной прочности.

Любой урон - это любой урон в игре, брут, хим, берн. Омни защита это как-то слишком сильно

**Comment by DarkHunter7756** [comment]
Ну батарею можно прокачивать. А снижение макс заряда звучит кринжово. Выставлю энергопотребление

**Comment by NefrNerf** [comment]
Не кринжово, нужно контролировать количество имплантов каким-то параметром

**Comment by NefrNerf** [comment]
Мы же не хотим киберпсихоза

**Comment by DarkHunter7756** [comment]
> Любой урон - это любой урон в игре, брут, хим, берн. Омни защита это как-то слишком сильно

По аналогии с бронепластиной боргов. Оно стоит алмазы, уран и плазму. Оно требует высоких технологий. Да и никто не мешает ему снизить прочность

**Comment by Tsurupeta** [comment]
> Не кринжово, нужно контролировать количество имплантов каким-то параметром

Ввести слоты под импланты. Либо ёмкость тела. Например, в торс вставить 1 имплант на 15 либо 3 импланта на 5. В таком духе.

**Comment by DarkHunter7756** [comment]
Под каждую часть тела или в совокупности?

**Comment by DarkHunter7756** [comment]
Емкость тела кста существует и используется для вставки инородных предметов.

**Comment by TimErmolt** [comment]
Много буков. Прочитал иссуй, но там столько разных имплантов, что их все хрен запомнишь.

Впрочем, сказать могу вот что. В плане аугментики трейторы глубоко сосут у лоялистов. У первых в аплинке даже источника питания для аугментаций нет, то есть, если ты трейтор и не ФБП -- сосёшь. У них две боевые аугментации, а у лоялистов в робототехнике -- пять. Причём в робототехнике именно те аугментации, которые пригодятся как раз антагам (зачем станционному лоялисту броня, когда она есть в арсенале, или вандализировать всё освещение вокруг себя?). Тут только надеяться, что робототехник (а их всего двое) или на крайняк хотя бы кто-то из научотдела (а робототехникой по умолчанию могут пользоваться только сами роботехи и РД -- фиг какой-нибудь учёный туда войдёт, если роботехи уйдут в отказ, получит флешкой в рожу и очередь из пулемёта гигакса) окажется дружелюбным коллегой по двойному агентству. Конечно, любой трейтор сможет пролезть в робототехнику, но чтобы что-то там печатать придётся раздобыть доступ роботеха. Да и само проникновение туда несёт высокий шанс обнаружить себя и загреметь в бриг.
В общем, нужно больше аугментаций в аплинк. Может, какие-нибудь синдикатовские версии некоторых разрабатываемых в робототехнике или уникальные. Хотя бы руку-емаг или взламывающий двери мультитул.

Ну, и ещё, вдобавок ко всему -- почти 100% вероятность, что, если это таки запилят, придётся с учётом нововведённых аугментаций долго и нудно балансить вокруг них остальные части боёвки. Химические препараты в частности, гидравлические мускулы плюс гиперзин -- звучит страшно. Ну, или вместе с запилом самих аугментаций вносить балансирующие изменения, но это будет ещё более непредсказуемо и едва ли уменьшит объём работы.

**Comment by O0oMaximo0O** [comment]
Ессс, Ката вторгается в СС13.

> Leukocyte Breeder System. Повышает эффективность любого лечения, но взамен отключает иммунитет организма.

Довольно странно. Лучше повышать иммунитет в обмен на трату энергии либо сытости персонажа.

> Sonic Resonator. Вызывает вибрации, уничтожающие каменные породы в радиусе 3 тайлов при активации.

Стены бы тоже. Может не уничтожать сразу, но повреждать.

В гражданские можно добавить встроенные скальпели. Ну или в наших реалиях, не только их, а ещё зажим, шприц, расширитель, ещё то что кости на место ставит (можно сразу bone mender).
:red_circle: :three: (РУКИ) Integrated Medical Toolset.

**Comment by IvanDonFon** [comment]
Да просто с оф. бея портаните аугменты и всё

**Comment by DarkHunter7756** [comment]
Ввел мед тулсет, перенес пару боевых аугментов к тритору, пофиксил гиперзинокринж

**Comment by No-Tips** [comment]
Охуенная вещь, но сомнительно, что одобрят

**Comment by DarkHunter7756** [comment]
Придумайте мне красивых аугментов для триторов. С ТК стоимостью, потому что я не шарю про текущую экономику.

**Comment by O0oMaximo0O** [comment]
Трейтору можно поглотитель батарей сделать ещё. 3 ТК (тоже не шарю).
Высасывает энергию у киборгов, ФБП, СМЕСов в радиусе 2 тайлов, передаёт энергию в батареи трейтора.
Ставится в торс, занимает 2 или 3 места.

**Comment by O0oMaximo0O** [comment]
Ещё можно аварийный эвакуатор. Пассивный-активируемый. При активации потребляет немного энергии каждый тик. При потере сознания трейтором, надевании на него наручников, значительной боли телепортирует его на заданные координаты в пределах текущего z-уровня. Для телепортации требует определённое кол-во энергии. При телепортации с недостаточным кол-вом энергии не может создать прокол в пространстве для переноса, в результате чего происходит взрыв/ЭМИ/всплеск радиации, мощность которого зависит от текущего кол-ва энергии.
Ставится в торс или гроин, занимает 2 или 3 места.
Стоит 5 ТК.

**Comment by O0oMaximo0O** [comment]
Направленный излучатель ультразвука. Активный. Требует n энергии для активации. Станит живых на прямой линии в пределах 3-4 тайлов в направлении взгляда трейтора. От него можно защититься как от флешбенга.
Ставится в руку, занимает 1 место.
Стоит 3 ТК.

**Comment by TimErmolt** [comment]
> Придумайте мне красивых аугментов для триторов. С ТК стоимостью, потому что я не шарю про текущую экономику.

Рукоемаг. Потратившись чуть больше, чем на обычный, можно получить практический аналог электроотмычки генокрада, работающей от заряда батарейки для аугментаций. За одно применение -- где-нибудь 100-200 заряда.
Обычный емаг стоит 3 ТК (вроде), пусть аугментированный будет 5.
Естественно ЭМИ его перехреначивает подобно выдвижному мечу.

Ещё одна идея -- какой-нибудь картридж для интегрированного швейцарского ножа, превращающий в нём мультитул в ИВД (инструмент для взлома дверей, тот мультитул, который подкручивается отвёрткой). Стоит 3 ТК, как и обычный ИВД. Как вариант -- можно сделать превращение мультитула в ИВД эффектом от применения емага к швейцарскому ножу. До вживления или после.

**Comment by TobyThorne** [comment]
> Охуенная вещь, но сомнительно, что одобрят

А чего бы не одобрить. Вполне можно одобрить, если попутно выпилим ФБП.

**Comment by MrMagick2104** [comment]
> если попутно выпилим ФБП.

А при чём тут ФБП?

**Comment by PlinHost** [comment]
Среди них:

БОЕВЫЕ:
- солнечные очки но за энергию и с уязвимостью к эми
- но-брейнер броня
- защита от ваншота
- меч но за энергию и с уязвимостью к эми

ГРАЖДАНСКИЕ:
- тулбелт но за энергию и с уязвимостью к эми
- медикал белт но за энергию и с уязвимостью к эми
- противогаз но за энергию и с уязвимостью к эми
- счетчик гейгера но за энергию
- непонятно, как радиация связана с кровью, но прекольно
- изи хил, как мы знаем спейс ковид это миф распространяемый агентами синди кати
- пнв но за энергию и с уязвимостью к эми
- если видишь незнакомое вещество, можно вколоть себе и посмотреть, что это было, прекольно
- шайтан-вибратор, непонятно зачем запиханый в человека, почему от активации не гибает тоже не ясно
- секрет энергии зайца duracell

**Comment by PlinHost** [comment]
Короче, часть можно сделать в виде имплантов, остальное не нужно.
