### ISSUE TITLE
Невозможность говорить при отсутствии воздуха реализована как говно

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#8834]
### Улучшение
Даже малейшее отсутствие воздуха делает тебя немым секунд так на 5. Поскольку даже после возобновления дыхания говорить нельзя ещё где-то 3 секунды минимум. Снизить бы этот кулдаун ну где-нибудь до одной секунды или вообще убрать. Если, конечно, технически это возможно, ибо я знаю, какие ужасы иногда можно в таких разделах кода встретить.
Притом, что интересно, иногда пишется в чат, мол, используй оставшийся воздух, чтобы что-то сказать, и даётся шанс на один сейлог, но зачастую -- нет. Просто сразу становишься мимом. От чего зависит -- так и не понял.
Вдобавок, сейлоги просто в никуда исчезают при попытке поговорить без воздуха. Кажется, будто верб сея сломался. Запилить бы сообщение в чат при этом, типа, у вас нет воздуха в лёгких, и вы не можете говорить.

**Comment by TimErmolt** [comment]
Оказывается, это сообщение всё-таки есть, но только тогда, когда даётся шанс сказать последний сейлог. Иначе -- нет. Значит, это всё не всегда активируется, когда пропадает воздух.

**Comment by Tsurupeta** [comment]
> Поскольку даже после возобновления дыхания говорить нельзя ещё где-то 3 секунды минимум. 

Всё нормально, что плохого?

**Comment by TimErmolt** [comment]
Опытным путём выяснилось, что способность говорить отрубается даже при **малейшей** нехватке воздуха. А именно: если поставить на клапане кислородного баллона выходное давление 20 кПа вместо стандартных 21, сразу становишься мимом. Притом такого давления вполне хватает, чтобы дышать при исправных лёгких. Как-то слишком уже душно.
