### ISSUE TITLE
Выпилить алиенам такл (стан одним кликом)

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#8839]
### Улучшение
Которое вдвое уменьшит количество жалоб на этих антагонистов и режим/рандомивент в целом.

### Решение
Просто выпилить такл к хуям. Убрать, удалить, ремувнуть.

### (Опционально) Альтернативы
Ну можно конечно запилить способы сопротивиться таклу, типа магбуты или просто надетый скафандр. Но лучше выпилить.

### (Опционально) Дополнительная информация
Смотрел в код, но так и не понял, как это работает. Так что скорее всего выпил не однострочный. Тем не менее выпилить стоит.

**Comment by Sudar0770** [comment]
Способность повалить и утащить - каноничная фишка ксеноморфа.
Ксеноморф должен овнить одиночную цель с невероятной лёгкостью. Тем более такл актуален только у хантеров. Квина слишком медленная для него как и сэнител.  От опрокидывания ксеноморфом не должны спасать магбутсы. Способ спасения от такла - напарник. Напарник с оружием полностью закрывает проблему иссуя на мой взгляд. 
Ксеноморф - биологическое оружие уничтожающее всю фауну на планетах и не должен нерфиться из-за "мамочки-мама, я играл в Рэмбо и пошёл с еганом убивать ксеноморфов, а меня затаклили и спиздили"
Ксеноморфы забаланшены тем, что их нужно гасить пока особей мало и это единственный путь на победу. Помимо этого их плевки работают криво и только таргетно на цель при условии, что цель может просто двигаться и задоджить таргетные плевки. Выпилить такл приравниваю к выпилу батонов у СБ. 
#ОСТАВЬТЕТАКЛВПОКОЕ

**Comment by TimErmolt** [comment]
Про канон и реализм можно долго дискутировать, но суть не меняется -- эта фича бесит всех, эта фича мало кому нравится, и никакое доказательство её каноничности ничьё мнение о ней как о игровой механике не поменяет. Собственно я поэтому и предлагаю выпилить -- потому что в фильмах это может быть интересно, а играть в это уже не интересно.

**Comment by FloweYStyle** [comment]
друзья предлагаю просто вызывать шаттл при любом упоминании ксеноморфов как способ быстро избавиться от них и сьебать нахуй


а если честно, алиен и без такла спокойно ебёт соло цель, у них я напоминаю есть плевки, ебейшая скорость или ебейший урон, фейс факеры и буквально дохуя хп. 

такл не спасёт человека даже если он ходил с другом, ибо одного можно надолго уложить, другого отпиздить или бросить фейс хаггер в ебало.

ещё алиены абузят такл плюс пулл выпавшей у человека пушки, что как бы кек нихуя не круто

у этой фичи нихуя святого, залупа дизбалансная, с алиенами драться невозможно, остаётся только клепать лимитки и подрывать гнездо как единственный вариант победы, сударь несёт хуйню, у меня всё

**Comment by Reroch** [comment]
> Про канон и реализм можно долго дискутировать, но суть не меняется -- эта фича бесит всех, эта фича мало кому нравится, и никакое доказательство её каноничности ничьё мнение о ней как о игровой механике не поменяет

Меня не бесит, мне нравится. Можете закрывать иссуй. А если серьёзно - опять же, почему вы решили, что вы с ксеноморфами можете воевать в открытую, одному-вдвоём? Правильно, поэтому они вас и трахают. Игровая логика соблюдена, кожаные мешки < биооружие с экзоскелетом.

**Comment by TimErmolt** [comment]
> Меня не бисит, мне нравится. Можете закрывать иссуй.

Ты вообще кто? Скажи это источникам всех возгласов, что режим/рандомивент говно.

**Comment by TimErmolt** [comment]
Если у нас гитхабом пользуются только те, кому фича нравится, это не значит, что нет тех, кому она не нравится. Или что их -- меньшинство.

**Comment by BooJ1K** [comment]
Перед тем как удалять такл нужно посмотреть какие атакующие умения есть у алиенов.
Охотник: Лип, такл, гат.
Защитник: Два вида плевка, такл.
Королева: Такл, плевки, гат.
Строитель: Ничего.

В итоге у нас охотник останется с одним только липом, потому-что Гат он наносит урон, оставляя раны, так что жертвы скорее просто не выживет до того момента, когда вылупится личинка.

У Защитника остаются плевки, работающие таргетно, Тут вроде бы всё нормально, но как быть с людьми, которые идут тебя пиздить с пожарным топором? 

Квина с её скоростью, такл имеет функцию оборонительную, от ассистентов, решившие набежать толпой.
И с другой стороны, в каком случаи квина идёт в агрессию, а не сидит в гнезде? Правильно – когда она единственный алиен, то есть если вы уберёте такл у квины, то ослабите и без того слабую раннею игру за алиенов, оставив ей способности, которые требуют плазму.

**Предлагаю**
Убрать такл охотникам, но добавить им способность как у Nabber – бегать, держа людей в синем грабе.

**Comment by AmiClerick** [comment]
Мне нравится, что Анноун так порвался из-за смерти в игре, что теперь воюет на гитхабе.

_ciF-cd5a SAY: TheUnknownOneBYND/(Techner Lezver): Очень балансно, да._

**Comment by TimErmolt** [comment]
> Мне нравится, что Анноун так порвался из-за смерти в игре, что теперь воюет на гитхабе.

Дофига героически поднимать приватные (доступные только педаляторам) логи и сюда их выставлять ради доказательства того, что я пишу подобные иссуи на гитхаб после смерти в игре.
Конечно я пишу иссуй после смерти, кто не пишет иссуй после смерти? Полезность и необходимость наличия данной фичи можно определить, только сыграв с ней раунд. В крайнем случае -- пристально пронаблюдав за раундом с ней. Иначе это будут либо основанные на теории предположения, либо сарафанное (комбенизонное) радио.

Говоря о самой проблеме, мне вообще нравится предложение Волка. Грабы в рукопашном бою -- один из самых смертельных приёмов, если оппонент не успеет вырваться, пока его не уложат на столик или не начнут забивать джебами. Раз алиумы по традиции робастнее хуманов -- грабы без потери скорости им подойдут получше. Тут и в улей человека можно утащить, и забить на месте. Правда у того будет шанс вырваться, но только если не снизить пойз до граба.
Смысл, что не стоит сражаться против чужого одному (ибо он грабом тебя победит), остаётся, но при этом имбовость охотников снижается. Я считаю, все в выигрыше.

**Comment by Sudar0770** [comment]
Хантер будет прыгать на цель и в грабе с ней убегать пока та кричит в ужасе. Это и атмосфернее и логичнее, и каноничнее и самое главное сократит количество кнопок которые быстро переключать смогут только Корейцы и Старкрафтеры (сори, две одинаковые картинки скинул🤡). Меньше кнопок без удобного интерфейса - благо. 
 Я считаю, что эта идея с усилинем граба НЕВЕРОЯТНА и BooJ1K заслуживает респект.

**Comment by Tsurupeta** [comment]
Можно просто спилить такл с одного клика, добавив такл на 2-4 клика.

**Comment by Sudar0770** [comment]
> Можно просто спилить такл с одного клика, добавив такл на 2-4 клика.

Как дизарм?

**Comment by Tsurupeta** [comment]
> Как дизарм?

Но сильнее. Либо с пойзом взаимодействовать и за несколько кликов его сбивать.

**Comment by Sudar0770** [comment]
> Но сильнее. Либо с пойзом взаимодействовать и за несколько кликов его сбивать.

Может проще будет усилить им дизармы?
