### ISSUE TITLE
Дверное и атмос-шатерное

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#8868]
Сейчас OBJ дверей частично бессмертны, как и жёлтые шатеры. Да, если их сломать, то будет возможность вскрыть ломом. А если дверь заварена, то только разварить. Что бы уничтожить дверь и вообще снять её, есть лишь 2 способа: инструментами и непрерывное долбление из имттера.

Предлагаю добавить возможность выломать дверь с петель(в том числе заваренную), путем нанесения огромного количества урона.  У нас есть спрайты выломанной двери, у нас есть педальная кнопка по снятию двери с петель, так давайте добавим обычным космонавтам способ грубо выламывать дверь.

**Comment by NefrNerf** [comment]
Чем ты ее собрался ломать? Я напомню, это не дверки толщиной в 5 сантиметров из дерева, это шлюзы которые находятся на космической станции и должны выдерживать огромное давление. Так чем ты их собрался ломать?

**Comment by ArmenianOnyx** [comment]
> Чем ты ее собрался ломать? Я напомню, что это не дверки, расположенные в 5 местах из дерева, это шлюзы, которые находятся на космической станции и должны выдерживать огромное давление. Так чем ты их собрался ломать?

Если долго бить дверь тулбоксом, рано или поздно она сломается.

**Comment by NefrNerf** [comment]
Ты конечно и бетонную стену сможешь рано или поздно проломить если будешь бить по ней инструментами, только сколько на это реально уйдет времени? Я думаю скорее победит стена чем ты.

**Comment by DeltaEpsilon7787** [comment]
Ща пофиксим одной строкой

**Comment by ArmenianOnyx** [comment]
> Ты конечно и бетонную стену сможешь рано или поздно проломить если будешь бить по ней инструментами, только сколько на это реально уйдет времени? Я думаю скорее победит стена чем ты.

Как отметили в чатике, у нас двери делаются из пары листов металла. Какая тут гига-мега прочность, при твоей душниловки в Р Е А Л И З М. Пусть космонавт или группа космонавтов имеют шанс выломать что то, без необходимости манчить фулл эквип инструментов.

**Comment by NefrNerf** [comment]
Я не против чтобы что-то тяжёлое на подобие пожарного топора могло выламывать заваренные шлюзы. Но против того, чтобы они туллбоксами могли ломать шлюзы и напомню, что у нас инструменты по всей станции раскиданы. А если дверь болтами не заблокировали то нужен всего лом и в худшем случае сварка

**Comment by ArmenianOnyx** [comment]
> Я не против чтобы что-то тяжёлое на подобие пожарного топора могло выламывать заваренные шлюзы. Но против того, чтобы они туллбоксами могли ломать шлюзы и напомню, что у нас инструменты по всей станции раскиданы. А если дверь болтами не заблокировали то нужен всего лом и в худшем случае сварка

Тогда надо забалансить количество здоровья двери. Никто же не выступает против этого.

**Comment by NefrNerf** [comment]
Так ты предлагаешь их выносить с петель а не балансить хп

**Comment by ArmenianOnyx** [comment]
> Contributor

Я не понимаю чего ты бля хочешь. Пусть дверь имеет пропорциональное количество здоровья, что бы топором можно было ее вынести с петель, а тулбоксом долбить существенно дольше.

**Comment by NefrNerf** [comment]
Чего я, блять хочу? Чтобы ты перестал генерировать шизофрению. Я тебе сказал дверь если она не заболочена, можно легко открыть, если ты не носишь лом - ты еблан.

**Comment by Sudar0770** [comment]
Бывают ситуации когда СБ ломится в какой-то шлюз и в 3 (иногда и больше) лица бьют шлюз баронами и не могут попасть внутрь из-за болтов и это смешно. Бывают ситуации когда тебе нужно украсть условные мышеловки, но стену разобрать гораздо проще, чем иметь дела со шлюзом и это тоже смешно и нелепо. 
Любой мех с буром может за несколько секунд снести любой шлюз, но шахтёрский бур может лишь сломать его до состояния открытия ломом и это смешно. Сами по себе шлюзы смешные и в них борятся игровая условность с логичностью. 
Что я предлагаю.... 
Болты скрепляют створки шлюза между собой и без инструментов их не прорезать, пусть всё остаётся так как есть. 
То, что вынести стену быстрее и бесшумнее это звучит как какая-то шутка, тут я могу лишь посоветовать заменить все шлюзы неохраняемых отсеков на более тонкие которые можно открыть ломом через 10 секунд прогресс бара. 
Добавить буру возможность как циркулярке и сварке разбираться с болтами.
