### ISSUE TITLE
Маг отправляет в нулл спейс менталфокусом.

### ISSUE THREAD

**Issue by BooJ1K** [ChaoticOnyx/OnyxBay#8890]
### Описание бага
Если человек сидит на стуле и в него прилетел снаряд из магического посоха Менталфокус, то этого человека отправит в нулл спейс.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Садим человека на стул, кресло и тп.
2. Стреляем из посоха менталфокус в него.
3. Фиксируем исчезновение человечка.
Опционально: Повторным выстрелом по стулу, можно вернуть человечка.

**Comment by NefrNerf** [comment]
А ты хорошую идею для заклинания нашел.

**Comment by Tsurupeta** [comment]
К сожалению, плашки "ржака" и "ржомба" были удалены.

**Comment by Primudash** [comment]
Пофикшено, больше не работает
