### ISSUE TITLE
FBP замена батарейки

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#89]
Т.к. недавно мы понерфили им батарейку, стоило бы кое-что им починить, а именно такую немаловажную вещь - замена батарейки. 
Вся проблема заключается в том, что если вытащить у FBP батарейку - он "умрёт" до замены новой.

Нужно сделать так, чтобы при вытаскивании батарейки FBP входил в экстренный режим, как у Боргов например. Но также стоит не забывать, что батарейку могут и сломать, а на него забить. Не думаю что кто-то захочет проваляться целый раунд в теле без батарейки.

**Comment by hekko4** [comment]
Не думаю, им бы возможность суккубнуться.

**Comment by LagannPM** [comment]
я думаю это нужно обсудить
это посути тоже что и с медициной
если дать людям возможность суккумбится по желанию нет смысла спасать
нужно надумать условие по которому будет доступен суккумб

**Comment by hekko4** [comment]
Может после суккумба просто запретить респавниться?

**Comment by LagannPM** [comment]
так себе, представь ты медленно дохнешь и знаешь что тебя никто не спасет... У тебя варианты , ждешь 10 минут черного экрана и потом еще 30 респавна, либо суккумбишься и вообще не респавнишся
lose-lose ситуация

**Comment by Epicus7** [comment]
У киборгов нет возможности гостануться, когда из них вынули батарейку?

В чем проблема с FBP? Ну "умирает", и что? Зато может гостануться и сразу после вставки опять живой.

**Comment by hekko4** [comment]
Ну да, чего такого, пока меняли батарейку - вылетел из тела и понаблюдал за миром, початился с гостотой, всё ок, ага да реализм прям скачет из самого себя.

**Comment by Epicus7** [comment]
Ну да, гостота. Окей.
