### ISSUE TITLE
Оптимизация status

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8960]
Как известно, вкладка status вызывает существенные просадки FPS вплоть до 5 кадров/сек
Ввиду того, что у киборгов, мейнтенс дронов и ИИ лагает больше всего могу сделать вывод, что все из-за избыточной постоянно меняющейся информации:
![image](https://user-images.githubusercontent.com/76823962/178590541-6f373e98-b454-4760-83ab-d46141557ed0.png)

Мое предложение: переместить следующие переменные в отдельные вербы 
- Current Location в верб Show Current Coordinates. Он меняется каждый шаг персонажа и скорее всего и жрет больше всего ресурсов
- Synthesizer'ы в верб Show Materials
- Tank Pressure убрать полностью. Дрон всегда может посмотреть на джетпак в руках для получения инфы о давлении. Если же оно кончится внезапно - имеется огнетушитель. 
- Power Cell Load убрать полностью. Каждый шаг персонажа переменная меняется, постоянно изменяется от действий робота и полностью отсутствует у FBP чем ему абсолютно не вредит. 

Все эти вербы можно всунуть в вкладку Silicon Commands, которая по моим скромным подсчетам ничем существенно не занята у киборгов, мейнтенс дронов и ИИ. Вербы будут вызывать сообщения в чате с текущими показателями

**Comment by Doster-d** [comment]
Этот иссуй будет относится как главный по отношению к иссуям связанные с вкладкой status боргов.
Это очень больно, пожалуйста, сделайте приоритет...

**Comment by igorsaux** [comment]
https://github.com/ChaoticOnyx/OnyxBay/issues/4569
