### ISSUE TITLE
Сделать возможность выбора варианта карты станции

### ISSUE THREAD

**Issue by Animusin** [ChaoticOnyx/OnyxBay#8965]
При смене карты станции функцией Change Map, при наличие для этой карты станции вариантов, перед сменой карты сделать дополнительное окно с выбором этих вариантов.
При выборе варианта осуществлять ремаппинг карты станции, с заменой частей карты, согласно координатам и картам, заложенным в конкретный вариант.

// Иссуй делается для добавления двух вариантов карты Рубежа с разными реакторными

**Comment by Sudar0770** [comment]
С каждым днём мы всё дальше от Лорда...
