### ISSUE TITLE
Амнезиаки

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#8999]
Небольшой триторский имплантер с особым имплантом внутри. При введении импланта в человека, тому вызывается дополнительное окно в середине экрана, повествующее текстом о потере памяти. По прошествии небольшого промежутка времени имплант исчезает. 

Заказывается в аплинке

Применение: [Данные удалены]

**Comment by DarkHunter7756** [comment]
ай нид критикуе

**Comment by Sudar0770** [comment]
Имплант... Может лучше автоинъектор с химикатом? Типа поставить имплант звучит как-то не профитно. Допустим нейрал импринтинг можно поставить и внести команду на забывание и ещё дополнить полезными вещами. 
Химикат будет более гладким решением и сразу будет понятно почему действие закончилось. Рассасывание импланта уже не так гладко на мой взгляд.
