### ISSUE TITLE
Сделать датчики костюмов по умолчанию

### ISSUE THREAD

**Issue by LagannPM** [ChaoticOnyx/OnyxBay#90]
Либо выставить чтобы датчики были включенные с самого начала без местонахождения
Либо форсить окно выбора режима при появлении

**Comment by Ruforce** [comment]
зачем

**Comment by Ruforce** [comment]
естественный отбор дебилов, которые не могут в пкм по костюму. это прекрасно

**Comment by Epicus7** [comment]
СБ, Морган Джеймс отключил датчики! Он предатель, ловите его!

**Comment by denver1000** [comment]
Всегда отключаю датчики. Ибо в суровом холодном космосе полагаться можно лишь на самого себя

**Comment by LagannPM** [comment]
нет у нас дохуя чего сломано, например маячки не отображатся на карте и тд
у них в том ПРе все починено

**Comment by Cinericius** [comment]
Не надо делать датчики включенными с самого начала. Это как делать автонастройку двигателя. Многомудрые пракосмонавты не просто так сделали их выключенными, у этого есть свой сакральный смысл.

**Comment by LagannPM** [comment]
Многомудрые пракосмоновты на самом деле ебаться не хотели и добавлять всякие проверочки на антогов и тд
пэтому просто фичу впихнули в продакшн

**Comment by Epicus7** [comment]
>Многомудрые космонавты просто ебаться не хотели и писать ИИ, чтобы он играл в игру вместо игроков.
