### ISSUE TITLE
Новый препарат с flux эффектом

### ISSUE THREAD

**Issue by JILMbIX** [ChaoticOnyx/OnyxBay#9037]
Суть нового препарата заключается в том что бы со временем растворять и выводить из организма различные инородные объекты вроде шрапнели, осколков, возможно даже торчащих прутьев.

Вообще идея позаимствована с СМ(к слову, оттуда же при желании можно и часть кода взять...), где эта фича не особо то и нужна, ибо у них любую шрапнель можно легко достать ножиком, но вот у нас это может зайти (особенно всяким магам, ниндзям... короче любым антагам-одиночкам.)

В качестве дебаффа можно накидывать токс урон, всё таки через кровь выводим. А для передозировки - вымывание костей за неимением инородных объектов, как вариант. Ну это всё уже на совести балансировщиков...

**Comment by Fillent** [comment]
Как будет вымывание костей работать? Просто в случайной части тела будет перелом?

**Comment by JILMbIX** [comment]
> Как будет вымывание костей работать? Просто в случайной части тела будет перелом?

Ну да, пожалуй случайная, ибо я даже не могу придумать причину по которой бы они начинали ломаться от меньшего к большему.

Так что да, либо в каждый тик передоза добавлять шанс на перелом(что, как по мне, будет слишком жестко), либо каждый тик заполнять шкалу после заполнения которой что-то ломается
