### ISSUE TITLE
Вечно-регенерирующие метроиды

### ISSUE THREAD

**Issue by Tsurupeta** [ChaoticOnyx/OnyxBay#9076]
### Описание бага
Метроиды регенерируют без ограничений по максимальному количеству здоровья.

### Ожидаемое поведение
Если у метроида 0 урона, он не прекращает регенерацию и уходит выше капа здоровья.

### Скриншоты
![image](https://user-images.githubusercontent.com/41485301/181915227-a1962e15-92bf-479f-9c17-6d2f7234f15e.png)
![image](https://user-images.githubusercontent.com/41485301/181915229-59b1965a-c6fe-418b-8e0d-814e67292bc1.png)

**Comment by ArmenianOnyx** [comment]
ВНИМАНИЕ СТРАШНАЯ ТАЙНА ТОП СЕКРЕТ СЕКРЕТЫ ТЕХ КТО ЗАХОДИТ НА СЕРВЕР ХОТЬ РАЗ В ГОД:
*Метроид умирает от огнетушителя и плевка водой, и никто никогда не бьёт их Брут уроном. Это фича, убить их может лишь вода.*
