### ISSUE TITLE
Одеяло сворачивается с любой дистанции.

### ISSUE THREAD

**Issue by AseFantome** [ChaoticOnyx/OnyxBay#909]
### Описание бага
Скидывать одеяло с трапов ещё никогда не было так безопасно. Теперь с любой дистанции, всего благодаря... Alt+LMB

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Идём в дормы.
2. Находим спящего трапа. 
3. Отходим в другой конец комнаты.
4. Нажимаем Alt+LMB.
5. Трапику холодно, а вы извращенец.

### Ожидаемое поведение
Одеяло должно было не предательски сдвигаться.

### Скриншоты
Ксенос в безопасности. (3)
![image](https://user-images.githubusercontent.com/57627192/69000994-782ef680-08e8-11ea-9965-04d767a66677.png)
Ксенос обречён на жестокую смерть. (4)
![image](https://user-images.githubusercontent.com/57627192/69000999-98f74c00-08e8-11ea-8b66-2f939c8ad272.png)

### Дополнительная информация
Нужно просто прикрутить проверочку на ренж.

**Comment by Epicus7** [comment]
Пофикшено в #1402
