### ISSUE TITLE
Keycard Authentication Device не реагирует на смену ДНК.

### ISSUE THREAD

**Issue by AseFantome** [ChaoticOnyx/OnyxBay#910]
### Описание бага
Даже если сменить ДНК (генокрадством), эта хрень выдаст тебе, что ДНК не изменилось и не даст то, что ты хотел (а я хочу соло-нюку за генокрада).

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем генку, шаманим, встаём на исходную.
2. Авторизируемся на первом сканере.
3. Трансформируемся в кого-то ещё.
4. Магическим образом успеваем до второго сканера и активируем.
5. ![image](https://user-images.githubusercontent.com/57627192/69001247-2ee0a600-08ec-11ea-9834-fd8b87e52708.png)

### Ожидаемое поведение
Сканер должен был сработать так, будто его активировал другой человек. В конкретно данном случае - выдать коды нюки.

### Дополнительная информация
Могла бы быть отличная фича. Которой никогда не воспользуются. Я бы мог подорвать пустую станцию. А так, сканер - метагей.

**Comment by LLIkolnik** [comment]
А ты двумя разными картами активировал?

**Comment by AseFantome** [comment]
Да.

**Comment by Epicus7** [comment]
> Keycard Authentication Device

> смотрит на ДНК

Нерфоцирк какой-то
