### ISSUE TITLE
Генкообращение поломалось (возможно)

### ISSUE THREAD

**Issue by Voldirs** [ChaoticOnyx/OnyxBay#913]
### Описание бага
Не смог воскреснуть после обращения генокрада

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Тебя конвертят в генку
2. Прожимаешь реген
3. По концу регена выдаёт We can not do this. We are really dead.

### (Опционально) Дополнительная информация
Возможно это связано с недавней обновой, в результате которой органы гниют после смерти. Возможно это связано с тем что я гостался, но раньше я так делал и таких проблем не было.

По результатам скана: strange biostructure Severe Necrotic

**Comment by TapKo4eB** [comment]
Пали жертвой быстрого гниения органов. btw, probably fixed #917

**Comment by Voldirs** [comment]
Вроде как должно быть пофикшено, но надо тестить

**Comment by Cinericius** [comment]
Закрываю до востребования.

**Comment by Cinericius** [comment]
(которого не должно быть, да)
