### ISSUE TITLE
Гниение синтетических органов (и пара слов про гниение вообще)

### ISSUE THREAD

**Issue by Aehsonneh** [ChaoticOnyx/OnyxBay#914]
### Описание бага
С тех пор, как ввели гниение трупов, теперь гниют синтетические органы у синтов за то время, когда их уже создали, но еще не вставили мозг. Если синт "умрет", то все сгниет за то время, пока его не перезапустят.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем фабрикатор у роботеха
2. Делаем синта по всем правилам, для начала без конечностей
3. Вставляем синту мозг
4. Вуаля - оптический сенсор уже сгнил, пока мы тупили как вставлять мозг

### Ожидаемое поведение
Хотелось бы чтобы синтетические органы не гнили.

### (Опционально) Дополнительная информация
Гниение мертвых тел - это уступка реализму ценой потери сильного кинематографичного эффекта. Самые лучшие моменты на станции, которые остаются в памяти людей годами - именно моменты кинематографичные, эффектные, красивые действия и красивые жесты. Работа доктора, сшивающего мертвые тела для получения живого - это явно из этой серии, к тому же только на моей памяти провоцировала несколько интересных ситуаций и внутриигровых диспутов о моральности таких действий. Если цель была в реализме, то три часа долгой смены - совсем недостаточный срок для гниения. Если же цель была заделать эксплойты, то есть другие, более легкие способы получать здоровые органы, но они не выглядят и вполовину так же круто, поэтому предлагаю отменить полное сгнивание мертвых тел и вернуть как было (тела гниют, только если смерть произошла от гниения или сепсиса).
В качестве альтернативы могу предложить понизить температуру морга до такой, где гниения не будет. К тому же, в моргах действительно холодно,

**Comment by TapKo4eB** [comment]
btw, гниение синтоорганов пофикшено #917
