### ISSUE TITLE
Фикс зомби + ВОЗНАГРАЖДЕНИЕ 

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#9166]
Необходимо ввести пару вправок в самих зомби, что бы приблизить их к играбельности:

- Понизить кулдаун на абилки consume и death breath. "Мертвое дыхание" имеет кулдаун в 60 секунд и крайне неудобно это. Нужно снизить кулдаун до 5 секунд.

- Абилки зомби заражать блокируются наручниками. Нужно позволить им использовать абилку death breath при наручниках.

СДЕЛАНО
- Убрать у зомби Солар комон и заменить на какой-нибудь другой язык, что бы обычные люди не могли понимать речь зомби. (Ну а зомби могли понимать людей и других зомби, так же общаться с зомби.)
СДЕЛАНО
За выполнение данного иссуя назначаю награждение в 300 рублей.

**Comment by No-Tips** [comment]
> фикс
> уменьшение кд

Вам к гейдизайну

**Comment by No-Tips** [comment]
В любом случае без плашки "одобрено" тут - можешь даже не ждать, что кто-то возьмется.

**Comment by ArmenianOnyx** [comment]
@NefrNerf @TobyThorne @PlinHost

**Comment by ArmenianOnyx** [comment]
Надо же. Спустя пару недель одобрили. Чтож, тогда работа упрощается в разы для того, кто займётся этим.

**Comment by ArmenianOnyx** [comment]
Ддостер уже все сделал. Если захочет, могу перевести денюжку ему.
