### ISSUE TITLE
На полярке не отображается блюспейс тайлы

### ISSUE THREAD

**Issue by igorsaux** [ChaoticOnyx/OnyxBay#9187]
![image](https://user-images.githubusercontent.com/55196698/184195968-0b04f219-4a04-4f9f-9656-a028c272d899.png)

**Comment by SVEDETEL69** [comment]
Так это ж поезд, он должен по рельсам ехать, а пока этого не завезли. Смысла в нормальной работе спрайта блюспеса нет

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
