### ISSUE TITLE
Шлюзы вирусолога на полярке не открываются кнопками

### ISSUE THREAD

**Issue by igorsaux** [ChaoticOnyx/OnyxBay#9188]
Видимо из-за кривой частоты, мб ещё что-то

![image](https://user-images.githubusercontent.com/55196698/184196943-7b154070-f040-40c3-a9d3-b096dc702c6c.png)

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
