### ISSUE TITLE
Иней и снег на персонажах и тайлах.

### ISSUE THREAD

**Issue by k4m3rn** [ChaoticOnyx/OnyxBay#9194]
Добавление лёгкого инея на тайлах, персонажах, объектах, который будет зависеть от температуры. В первую очередь будет ОЧЕНЬ канонично смотреться на нашей снежной карте, да и иней снаружи станции будет придавать космосу большую опасность и атмосферность. Будет в виде оверлея, проверяя температуру на тайле, на котором находится, оверлей будет появляться и менять непрозрачность в зависимости от холода(опционально). Прикрутить высокий тикрейт(или к какому-нибудь другому тикрейту, решайте сами) и анимацию появления, чтобы глаза не резало и не было сильной нагрузки от обновления. 

Готов предоставить текстуры, нарисую сам. Будет нужна помощь в получении оригинальных текстур для работы с ними.

**Comment by Tsurupeta** [comment]
не оч сложно
