### ISSUE TITLE
Починка бури на пафосе.

### ISSUE THREAD

**Issue by k4m3rn** [ChaoticOnyx/OnyxBay#9195]
Задумка с мобами в бурю неплоха, но то, что они невидимы, слишком пососно. Время между штормами слишком маленькое. Прочие мелочи. 
Для начала нужно монстрам выдать нормальные имена, а не блюспейс залупа. Уменьшить урон, три укуса уносят в крит моментально. Самое главное что задумка в целом хорошая, но невидимость это полный пиздец. Мудрить с текстурами тоже особо не стоит. Предлагаю концепт прямиком спизженный из сериала LOST. Дымный монстр. Накидываем на монстра спрайтик дыма, перекрашенный в снежный, готово. Ещё обсосный момент, нигде не говорится о монстрах, поэтому надо в оповещении обязательно вставить сообщение о появлении аномальных мобов на карте. Ещё не стоит давать мобам большое поле зрения, иначе будет постоянная долбёжка в окна и прочий кал. Да и для будущих фич с бурей будет островок безопасности.
Для самой бури просто голубого цвета не хватает. Старый концепт с пеплом на астероиде можно перенести сюда в виде снега. При облачности будет идти лёгкий снежок, при буре будет почти нихуя не видно. 
С температурой всё очень странно, я, конечно, понимаю, что вдыхать очень холодный воздух и правда очень больно, но персонаж то по итогу даже не мёрзнет. Но это на потом.

**Comment by Zert0X** [comment]
>С температурой всё очень странно, я, конечно, понимаю, что вдыхать очень холодный воздух и правда очень больно, но персонаж то по итогу даже не мёрзнет.

Мёрзнет у туши опускается температура.-.

>Для начала нужно монстрам выдать нормальные имена, а не блюспейс залупа.

Чё не так с блюспейс залупой?

>Ещё не стоит давать мобам большое поле зрения, иначе будет постоянная долбёжка в окна и прочий кал.

Итак радиус не самый большой и да они не ломают окна и т.п. у них запрет

**Comment by k4m3rn** [comment]
Итак, первое. Хорошо, температура опускается у туши, это ладно. Второе, блюспейс залупа слишком залупа. Третье. Если накинуть им текстурку, то они будут стоять и дрочить под окнами.

**Comment by Zert0X** [comment]
> Третье. Если накинуть им текстурку, то они будут стоять и дрочить под окнами.

Они исчезают после бури

**Comment by k4m3rn** [comment]
> Они исчезают после бури

Их цель в чём? Сохздать опасность космонавтикам. Так это будет хищник, который пялит в окно, вместо того, чтобы бегать и искать заблудших душ. Да, взглянуть прямо в глаза своему страху сквозь тонкое окно это зрелище завораживающее, но будет лучше видеть, как на улице бродят те ужасные существа, готовые напасть в любой момент. А вот эти гляделки в окошко это что-то забавное, особенно с ИИ наших мобов, которые за стеной тебя продолжают целить.

**Comment by Zert0X** [comment]
Исправлено выпилом блюпуп тварей и добавлением эффекта снега
