### ISSUE TITLE
Добавить косякам с топливом и плазмой настоящий взрыв

### ISSUE THREAD

**Issue by EliseyGladkiy** [ChaoticOnyx/OnyxBay#9201]
Сейчас при поджоге косяка в котором содержится плазма или сварочное топливо, происходит исчезновение косяка со звуком взрыва и сообщением в чат. Всё, больше никаких крутых штук нет и взрыв прямо во рту у человека ничего не делает, что очень печально.

Предлагаю добавить настоящий взрыв при поджоге косяка с топливом и плазмой, как это сейчас у нас с плазменными лампочками работает. 
При поджоге косяка во рту персонажа будет гарантированно кидать в стан и наносить урон, размер которого зависит от объёме взрывоопасной жидкости. В случае поджога не во рту стан будет накладываться в зависимости от силы взрыва.

Ну и у взрыва от плазмы урон должен быть чуть повыше, чем у топлива.

**Comment by TobyThorne** [comment]
Кринж в том, что плазма/топливо вообще заставляют сигареты взрываться. Они должны просто мгновенно сгорать, мб нанося лицу бёрн-дамаг. А для подрывов надо впилить какой-нибудь порох.

**Comment by EliseyGladkiy** [comment]
> Кринж в том, что плазма/топливо вообще заставляют сигареты взрываться. Они должны просто мгновенно сгорать, мб нанося лицу бёрн-дамаг. А для подрывов надо впилить какой-нибудь порох.

Нитроглицерин в билде есть, можно его.
А сиги с плазмой/топливом тогда не взрываются, а наносят бёрн по голове и лёгким в зависимости от вещества и его объёма.
Кстати, надо ещё узнать, как плазмиген горит в сигах.
