### ISSUE TITLE
Добавить возможность заварить рот синтетикам

### ISSUE THREAD

**Issue by EliseyGladkiy** [ChaoticOnyx/OnyxBay#9203]
Если взять синтетика в синий граб и использовать сварку, выбрав рот на кукле, то он не будет способен говорить вплоть до разваривания рта обратно. 
Для разваривания рта граб не нужен.

I have no mouth and I must beep

**Comment by k4m3rn** [comment]
Синтам не нужен рот, чтобы говорить. Доказательства? Выходим хуманом в космос, хуман гаспает, говорить не может. Выходим синтом в космос, синту поебать.

**Comment by TobyThorne** [comment]
На некоторых моделях голов вообще рта нет. Вот как сделаем нормальных синтетиков - тогда и будут всякие ржаки в виде откручивания синтезатора речи.
