### ISSUE TITLE
Корованы

### ISSUE THREAD

**Issue by LegatePritcher** [ChaoticOnyx/OnyxBay#9258]
Здраствуйте. Я, Легат. Хотел бы чтобы вы сделали игру, 2Д-экшон суть такова... Пользователь может играть агентами Синдиката, охраной арсенала и ревизором с ЦК. И если пользователь играет агентами то агенты на базе, базу набигают охрана арсенала дворца и ревизор. Можно грабить шаттолы... И агенту раз синдикатские то сделать так что там густые корпорации.. А движок можно поставить так что вдали корпорации картинкой, когда подходиш они преобразовываются в 2-хмерные деревья. Можно покупать и т.п. возможности как в Morrowind. И враги 2-хмерные тоже, и труп тоже 2д. Можно прыгать и т.п. Если играть за охрану арсенала то надо слушаться хуесоса, и защищать арсенала от злого (имя я не придумал) и ревизора, партизанов Синдиката, и ходит на набеги на когото из этих (агентов, ревизора...). Ну а если заревизора... то значит агенты или Синдикат иногда нападают, пользователь сам себе педаль может делать что сам захочет прикажет своим подсосам с ним самим напасть на арсенал и пойдет в атаку. Всего в игре 4 зоны. Т.е. карта и на ней есть 4 зоны, 1 - зона людей (обсерв), 2- зона хуесосов (где бриг), 3-зона Синдиката, 4 - зона ЦК... (в тандердроме, там есть арена...)

Так же чтобы в игре могли не только убить но и отрубить руку и если пользователя не вылечат то он умрет в реальности, так же выколоть глаз но пользователь может не умереть а просто пол экрана не видеть, или достать или купить протез, если ногу тоже либо умреш либо будеш ползать либо на коляске котаться, или самое хорошее... поставить протез. Сохранятся можно...

P.S. Я джва года хочу такую игру.

**Comment by Zert0X** [comment]
Здраствуйте. Я, Ловла. Хотел бы чтобы вы сделали игру, 2Д-экшон суть такова... Пользователь может играть агентами Синдиката, охраной арсенала и ревизором с ЦК. И если пользователь играет агентами то агенты на базе, базу набигают охрана арсенала дворца и ревизор. Можно грабить шаттолы... И агенту раз синдикатские то сделать так что там густые корпорации.. А движок можно поставить так что вдали корпорации картинкой, когда подходиш они преобразовываются в 2-хмерные деревья. Можно покупать и т.п. возможности как в Morrowind. И враги 2-хмерные тоже, и труп тоже 2д. Можно прыгать и т.п. Если играть за охрану арсенала то надо слушаться хуесоса, и защищать арсенала от злого (имя я не придумал) и ревизора, партизанов Синдиката, и ходит на набеги на когото из этих (агентов, ревизора...). Ну а если заревизора... то значит агенты или Синдикат иногда нападают, пользователь сам себе педаль может делать что сам захочет прикажет своим подсосам с ним самим напасть на арсенал и пойдет в атаку. Всего в игре 4 зоны. Т.е. карта и на ней есть 4 зоны, 1 - зона людей (обсерв), 2- зона хуесосов (где бриг), 3-зона Синдиката, 4 - зона ЦК... (в тандердроме, там есть арена...)

Так же чтобы в игре могли не только убить но и отрубить руку и если пользователя не вылечат то он умрет в реальности, так же выколоть глаз но пользователь может не умереть а просто пол экрана не видеть, или достать или купить протез, если ногу тоже либо умреш либо будеш ползать либо на коляске котаться, или самое хорошее... поставить протез. Сохранятся можно...

P.S. Я джва года хочу такую игру.
