### ISSUE TITLE
Меняем материю на тессеракт или Нескучная материя парт 2

### ISSUE THREAD

**Issue by kreeperHLC** [ChaoticOnyx/OnyxBay#9394]
![image](https://user-images.githubusercontent.com/14943437/189888749-989d4433-5adc-4d17-9ed1-42e1ed2368bb.png)

### Улучшение
Заменяем скучный желтый кристалл на нескучный зелёный тессеракт. Добавляем уникальные эффекты:
При попытке тронуть вместо испепеления - выворачивание на изнанку (Оверлей вывернутого наизнанку человека, пока ещё живой, хлещет кровью во все стороны. Адские крики. Опционально - ходит задом наперёд). Синты превращаются в рандомную живую машинерию. За каждый протез на теле шанс превратиться в машинерию будет увеличен.
При попытке взглянуть без мезонок - персонаж начинает видеть мир в негативе.
Предметы кинутые в неё, превращаются в другие аналоги.

Добавляем возможные приколы при плохой стабилизации.

**Comment by No-Tips** [comment]
Да да да да. Надо.

**Comment by Firefroge** [comment]
Вы больные. Зачем вы хотите переделать кусок сжатой материи в... блять, тессеракт..?
Зачем? Ради чего? Как он энергию давать будет..?

**Comment by kreeperHLC** [comment]
> Вы больные. Зачем вы хотите переделать кусок сжатой материи в... блять, тессеракт..? Зачем? Ради чего? Как он энергию давать будет..?

Затем, чтобы он был не скучным. Ради весёлости. Энергию будет из 4д измерения тащить.

**Comment by No-Tips** [comment]
Крипер, перетащи тогда и нескучную материю из того самого пра!!!!
