### ISSUE TITLE
Вместо Nullspace замапить BackRooms

### ISSUE THREAD

**Issue by Medjic** [ChaoticOnyx/OnyxBay#9406]
А че? Весёлое место для бедолаг, которых билд изничтожил до кварков и нейтрино.

![image](https://user-images.githubusercontent.com/75128764/190166205-b00c98a4-9698-40a8-ae2d-5d820e4a89e2.png)

**Comment by Firefroge** [comment]
И минуты не прошло. Дарк уже тут.

**Comment by igorsaux** [comment]
нулспейс это не карта
