### ISSUE TITLE
Нечувствительность к заглавным буквам в протолате

### ISSUE THREAD

**Issue by Wuattt** [ChaoticOnyx/OnyxBay#9438]
### Улучшение
В протолате поисковик чувствителен к заглавным буквам. Т.е. если вбить "диск", а сам предмет называется "Диск", то поисковик его не найдёт. Будет намного удобней, если заглавные буквы при поиске не будут учитываться.

### Решение
Сделать поисковик в протолате нечувствительным к заглавным буквам.

### (Опционально) Альтернативы
Оставить как было

### (Опционально) Дополнительная информация
![image](https://user-images.githubusercontent.com/34631419/190691836-8b8d26bb-61eb-4a89-a565-450ac11f6475.png)
![image](https://user-images.githubusercontent.com/34631419/190691871-c769b88e-74b5-4b63-9ecc-04ba86469f76.png)

**Comment by oleggorru** [comment]
Выйди на связь в #onyxbay-общий. Можешь меня слапнуть Kolomec#9007
https://discord.gg/cnav4Ygm
