### ISSUE TITLE
Легкие убивают чатик.

### ISSUE THREAD

**Issue by ArmenianOnyx** [ChaoticOnyx/OnyxBay#9446]
Наша реалистичная фича с повреждением легких и невозможностью говорить без воздуха - убивает игроку коммуникацию.
При 50% повреждения легких, человек полностью лишается возможности говорить.
При 30% повреждения легких, чат работает 50% на 50%, иногда сообщение пишется, а иногда нет. (А еще через 5 минут останавливается сердце)

Ну допустим, заебись механика... реализм! Но как социалить? Хочешь пообщаться, а тебе тупо не дают. Сообщения удаляются. Получается что бы общаться чатиком, нам необходимо или лутать баллоны кислорода, или Катя Печка? 
Вот пришел к тебе Двинжи, начал отыгрывать изящный эмоут, хармом эротично бить тебя телескопичкой по торсу, а ты в ответ пишешь ему такой же классный длинный ответ, но сообщение не доходит, ведь Двинжи немножечко повредил тебе легкие.

Поэтому я считаю что нам нужен ребаланс эффекта повреждений легких.

**Comment by TimErmolt** [comment]
По сути, уже поднимался данный вопрос в #8834. Вроде с тех пор понёрфили временное превращение в мима от лёгких, но шут знает, я, если честно, в игре не заметил изменений.
