### ISSUE TITLE
Добавить возможность надевать мак и колокольчики на прическу

### ISSUE THREAD

**Issue by LLIkolnik** [ChaoticOnyx/OnyxBay#953]
!!!

**Comment by kreeperHLC** [comment]
Потому что только суровые мужики должны иметь возможность подчеркнуть свою мускулинность маком или колокольчиками.

**Comment by LLIkolnik** [comment]
Так мужики не могут тоже!

**Comment by Epicus7** [comment]
Неебу чо за "мак и колокольчики". Нужны пути до объектов.

**Comment by PlinHost** [comment]
> Неебу чо за "мак и колокольчики". Нужны пути до объектов.

`/datum/seed/flower/poppy` мак и `/datum/seed/flower` колокольчики. Сам объект, видимо, `/obj/item/weapon/reagent_containers/food/snacks/grown`.

**Comment by Epicus7** [comment]
А спрайты где взять?

**Comment by TobyThorne** [comment]
Вижу два варианта решения:
1. Добавить в семена переменную типа "wearable_slot_head" и добавить для нужных растений. Но нужно много спрайтов - вдруг я хочу в голову не только цветы втыкать, а ещё и грибы к затылку прикалывать?
2. Тупо добавить крафт из маков/колокольчиков имеющихся цветочных заколок. A.k.a. копипаст тыквы.

**Comment by kreeperHLC** [comment]
Иссуй крутой, одобряю.
