### ISSUE TITLE
Кривое перемещение в руки

### ISSUE THREAD

**Issue by igorsaux** [ChaoticOnyx/OnyxBay#9542]
Теперь если попробовать вытащить карточку из пда когда все руки заняты - карточка не упадёт на пол а просто "исчезнет" (на самом деле она остаётся внутри пда но её уже никак не вытащить).

Виной тому
```dm
    if(I.loc != src)
        util_crash_with("Called [src]'s ([type]) proc/drop(I = [I], target = [target], force = [force]) while the item isn't located inside the mob.") // This may save us someday.
        return FALSE
```

**Comment by TobyThorne** [comment]
Занятно. Выходит, до #9518 оно просто рантаймило на моменте дропа, но успевало сработать. Самое смешное, что для вытаскивания ручек и картриджей там куда более адекватный код.
