### ISSUE TITLE
Нужно переделать РнД полярки.

### ISSUE THREAD

**Issue by SVEDETEL69** [ChaoticOnyx/OnyxBay#9595]
Проблема заключается в том, что РнД Полярки выглядит плохо, зачастую на ней мы можем видеть полупустые заполненные серыми тайлами пространства, вот те области, о которых я говорю.
У РД офис - говно
Нужно что-то со входом делать
И переделать робототехнику
![аа](https://user-images.githubusercontent.com/114770504/193843073-6ad0feb2-46da-43d5-8307-d182b3d46fd8.png)

Комната отдыха сделана на отъебись и ещё по мелочи вроде пола неподходящего для туалетов и душевых.
![п](https://user-images.githubusercontent.com/114770504/193843816-da655d08-4ca8-46f1-9ead-f54bb11da481.png)

Красным - плохо сделано
Синим - пустовато
![го](https://user-images.githubusercontent.com/114770504/193843984-d403d201-02ba-4bba-98dd-e781d0245ba3.png)

Я предлагаю переделать так:
   1. В туалеты поставить нормальный пол
   2. Переделать дормы ксеноархеологии по типу дорм на основном уровне полярки.
   3. В мини медпункт ксеноархеологии поставить IV-drip с нанокровью и таблеточки, заменить пол.
   4. Добавить эммиттер в одну из тестовых комнат.
   5. На склад добавить всяких вещей
   6. Переделать комнату отдыха, добавив в неё пол из дерева и тёмный стол.
   7. Возьмём офис РД с Исхода, не вижу смысла, что-то новое придумывать.
   8. Переделать робототехнику

**Comment by intercepti0n** [comment]
Закрываю иссуй так как карта выведена из ротации и удалена из билда в #11430.
