### ISSUE TITLE
Заменить унылый шкафчик с мешками крови на гига чад анимированный  холодильник

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#9598]
Он красивый и не выбрасывает все свое содержимое на пол при любом удобном ему случае 

Сейчас
![image](https://user-images.githubusercontent.com/76823962/193893723-f964cf91-68f2-4432-b7f6-76b1f44a4f89.png)
Будет
![8HG1KtvEqs](https://user-images.githubusercontent.com/76823962/193893703-1bb7f1ec-eb64-4a4c-937b-06440a799dbe.gif)

Оценили 36 человек

**Comment by DarkHunter7756** [comment]
Находится в билде по пути icons/obj/vending.dmi

**Comment by MemoryDreams** [comment]
А он не работает без света?

**Comment by MemoryDreams** [comment]
А он не работает без света?

**Comment by Tsurupeta** [comment]
Не должен.

**Comment by kreeperHLC** [comment]
Одобряю.
