### ISSUE TITLE
Вырезать вкладки Faction и Citizenship, добавить поле Background в character setup

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#9599]
Вырезать вкладки Faction и Citizenship.
<details>
<summary>Добавить поле Background.</summary>

- Nanotrasen
- Nova Magnitka
- Gaia Magna
- Zeng-Hu Clique
- Zermig VIII
- Independent Arcturia
- Parthenonnus Ark Space Vessel
- Moghes
- Skrell Empire
- Adhomai
- Corporate Sector
- Unset
- Other (с возможностью вписать свою строку)

</details>

<details>
<summary>Обновить содержание поля Home System.</summary>

- Gilgamesh
- Tau Ceti
- Epsilon Ursae Minoris
- Zermig
- Arcturus
- Vega
- Renenet
- Alpha Centauri
- Sirius
- Qerrbalak
- S`randarr
- Uioa-Esa
- Unset
- Other (с возможностью вписать свою строку)

</details>

**Иссуй составлен по просьбе и на основе слов главного по лору Оникса.**

**Comment by PlinHost** [comment]
Одобрено решением сената

**Comment by Epicus7** [comment]
Награда выдана
