### ISSUE TITLE
Исправить ссылку на бекстори в приветственных сообщениях и кнопке на обоих серверах

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#9600]
**Цитата:** _"Исправить ссылку в модт серверов Бекстори на статью [Welcome To The Station](https://wiki.ss13.ru/index.php?title=Welcome_to_the_Station)"_

![image](https://user-images.githubusercontent.com/98965002/193907855-5314e90d-c010-425f-95c7-63d3f82773b8.png)

![image](https://user-images.githubusercontent.com/98965002/193907876-33f4d5a8-8bbf-435b-b1f8-f957597a936b.png)

**Иссуй составлен по просьбе и на основе слов главного по лору Оникса.**

**Comment by PlinHost** [comment]
Не касается билда
