### ISSUE TITLE
Обновить рестрикты ксеносам в соответствии с обновленным лором

### ISSUE THREAD

**Issue by ghost** [ChaoticOnyx/OnyxBay#9601]
Обновить рестрикты ксеносам на всех картах в соответствии с измененным лором и опираясь на таблицы с Вики.

[Таяран](https://wiki.ss13.ru/index.php?title=%D0%A2%D0%B0%D1%8F%D1%80%D0%B0%D0%BD)
[Унати](https://wiki.ss13.ru/index.php?title=Unathi)
[Скрелл](https://wiki.ss13.ru/index.php?title=Skrell)

**Иссуй составлен по просьбе и на основе слов главного по лору Оникса.**

**Comment by PlinHost** [comment]
Одобрено решением сената

**Comment by Epicus7** [comment]
Награда выдана
