### ISSUE TITLE
У скреллов нет синтетических тел

### ISSUE THREAD

**Issue by BugReporterOnyx** [ChaoticOnyx/OnyxBay#9603]
### Описание бага
У скреллов нет возможности выбрать синтетическое тело
### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем расу скреллов
2. Открываем Limbs (Adjust)->Full Body
3. Нажимаем Prothtesis
4. Видим ошибку  - Окно с выбором протезов не открывается

### Ожидаемое поведение
Должно открыться окно со списком производетелей синтетических тел

### Скриншоты
----
### (Опционально) Дополнительная информация
Здесь можете описать любую дополнительную информацию, которая касается бага

### (Опционально) Характеристики
 - OS: Windows
 - Версия клиента 514.1588
 - Версия сервера Server Revision: [975df480e8df5162958967e8e3be3356a74a998a](https://github.com/ChaoticOnyx/OnyxBay/commit/975df480e8df5162958967e8e3be3356a74a998a) - 958967e8e3be3356a74a998a - 2022-09-30
 - ID игры ckf-bQVL

**Comment by ghost** [comment]
У нас нет протезов для скреллов.

**Comment by TobyThorne** [comment]
> У нас нет протезов для скреллов.

на нет и суда нет
