### ISSUE TITLE
БАГ: Особая особь алиума по типу "Ферал" или "Вайл" теряет свои свойства после эволюции и становится обычным алиумом

### ISSUE THREAD

**Issue by Firefroge** [ChaoticOnyx/OnyxBay#9654]
### Описание бага
Если ты грудолом, который вылез из ксеноса - то ты должен быть ОСОБЫМ, но при эволюции - ты становишься обычной версией алиена

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем лявру из таяры/унати/скрелла
2. Эволюционируем
3. Становимся обычным алиеном

### Ожидаемое поведение
Ну эволюционировавший алиен должен быть особым.

**Comment by Firefroge** [comment]
Бот в дискорде поел говна и не хочет нормально принимать мой багрепорт

**Comment by TobyThorne** [comment]
просто фрога лох
Что именно в описании непонятного?
![image](https://user-images.githubusercontent.com/45202681/194962165-111b1b47-2ddc-4115-a390-75668b4ed282.png)
![image](https://user-images.githubusercontent.com/45202681/194962178-e7b7b68b-2847-4614-8899-5e4cac712118.png)
![image](https://user-images.githubusercontent.com/45202681/194962190-46f710e5-1e3e-4da0-873f-9d9790b3d01d.png)
У каждого "расового" грудолома только один из классов баффнутый. Таяры - хантер, унатхи - цент, скреллы - дрон.

**Comment by Firefroge** [comment]
Тоесть то, что они раньше могли быть кем угодно - баг?

**Comment by TobyThorne** [comment]
> Тоесть то, что они раньше могли быть кем угодно - баг?

всм
ферал дронов и вайл хантеров никогда не существовало
а обычного сента/дрона какой-нибудь ферал грудолом всегда может выбрать, если не хочет баффнутого хантера
