### ISSUE TITLE
Революция: вернуть главных революционеров

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#973]
Вернуть разделение революционеров на главных и не очень.

Все революционеры, которые спавнятся в начале - главные. Конвертированные - обычные.

**Comment by Wuattt** [comment]
так а щас разве не так? Раундстартовые революционеры имеют синюю R, законверченые - красную R

**Comment by k4m3rn** [comment]
>You are a Head Revolutionary!

/thread
