### ISSUE TITLE
 Авто-отбытие шаттла прибытия после 1 минуты без новых рабочих и не-наличия внутри него экипажа

### ISSUE THREAD

**Issue by DarkHunter7756** [ChaoticOnyx/OnyxBay#9736]
Решаем логическую проблему спавна гражданских на вечно стоящем шаттле. 

Шаттл появляется на месте исчезновения при прибытии новых членов экипажа через спавнпоинт шаттла

**Comment by Medjic** [comment]
Лучше сделать спавн на уже отлетевшем шаттле, который потом прилетает на станцию.
Если уже другой космонавт отлетит на нём, он просто зависнет в космосе до тех пока не респавнится новый или не нажмёт на консоль. При начале раунда ВСЕ ассистенты будут рождаться на многочисленных местах.

**Comment by DarkHunter7756** [comment]
В моей концепции он просто исчезает. А потом появляется вновь в час великой нужды

**Comment by Medjic** [comment]
А если оттуда не уйдёт человек?

**Comment by DarkHunter7756** [comment]
Тогда новый заспавнится на этом же шаттле...ладно, твой вариант лучше

**Comment by Medjic** [comment]
😸

**Comment by SVEDETEL69** [comment]
Короче как на тг?

**Comment by Medjic** [comment]
Как на ТГ, да.
