### ISSUE TITLE
Революция: вернуть аплинк

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#974]
Вернуть главным революционерам (issue #973) аплинк.

**Убрать оттуда слишком крутые синдикатовские шмотки**, но добавить какие-то свои плюшки и возможность заказывать их оптом для раздачи товарищам.

Например, наборы "собери самострел", самодельная броня, кустарные гранаты и т.д.

**Comment by Cinericius** [comment]
Можно положить один аплинк в книжку из #976

**Comment by kreeperHLC** [comment]
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/14943437/f209703f-5db6-49cb-9781-6a90d5361529)
