### ISSUE TITLE
Революция: лояльные к НТ персонажи не могут быть революционерами

### ISSUE THREAD

**Issue by Epicus7** [ChaoticOnyx/OnyxBay#977]
Если в сетапе персонажа стоит, что он лояльный НТ, то ему нельзя предложить стать революционером.

Для баланса, наверное, стоит немного порезать шансы таких персонажей получить антага случайным распределением (и явно написать об этом в сетапе).

Нужно для баланса после остальных изменений революции. Другие изменения (смотри проект) делают революционеров более сильными - это должно сбалансировать режим.

**Comment by TapKo4eB** [comment]
Ещё один ползунок для аффекта на шанс антагонизации за пределами вкладки ролек, плюс палим антагов раундстартом через крю рекодрс. Нет, спасибо.

**Comment by Doster-d** [comment]
Вы че блять совсем поехавшие?

**Comment by MorJams** [comment]
Кто это одобрил, отдобрите обратно.
1) Лояльность/нелояльность это лишь ролплей характеристика персонажа. То, как человека видит ЦК. Они не могут ошибаться? Человек может сорок лет пахал ради маскировки со стороны НТ.
2) Как выше и написали, палится через Крю Рекордс. Можно, конечно, оправдать эту тупость, но это того не стоит.
3) Нахуя?

**Comment by MorJams** [comment]
Пускай человек сам решает же, нахуя его ограничивать.

**Comment by Epicus7** [comment]
Весь проект Революция принят и одобрен сенатом в декабре месяце.

**Comment by Epicus7** [comment]
Поднял в сенате предложение отменить апрув.

**Comment by kreeperHLC** [comment]
Как же хорошо что Сенат решал всего лишь три года назад. Отмена одобрения и отклонено.
