### ISSUE TITLE
Служебная овчарка (новый моб для управления игроком) 

### ISSUE THREAD

**Issue by Sudar0770** [ChaoticOnyx/OnyxBay#9787]
### Улучшение
Увидев мистера Димпси я преисполнился любовью к братьям нашим меньшим и осознал, что полезных животных под управлением игроков должно быть больше. Начну с овчарки для СБ по кличке Robust.  Не имеет рук, но может пуллить крупные предметы как хуманы и прочие расы. Не понимает человеческий язык, но всё ещё видит эмоуты. 
Имеет способность залезать в сумки и вытаскивать взрывчатку? Наркотики? Колбасу? 
Имеет таргетную абилку ввиде лая на цель которую можно разносторонне использовать (например сигнализировать офицерам об опасности) 
Имеет лип Воксов, но не грабает после(тут спорно, но я называю то, что в теории должна уметь боевая собака) 
Укусы наносят небольшой урон сродни укусам монке. 
Имеет на себе СБ пояс(на самом деле это тактическая собачья разгрузка, но суть остаётся прежней) которым сам Робаст пользоваться не сможет, но всегда будет рад принести тебе лишнюю светошумовую.
Робаст в баланс своей скорости и такла должен иметь хп на 3-4 удара огнетушителем. Это заставит игроков отыгрывать верного пса, а не топ Робаст ера сервера 1337.
Способ лечения: могу предложить два варианта, один казуальный через помазку гелями и бинтами, второй через хирургию как у хуманов, оба варианта хороши по своим причинам, но лично мне больше нравится мазаться бинтиком и выходить из крита. 
Бегать Робаст будет быстро как котолюди.
Все мы понимаем, что собак в охрану берут из-за их невероятного нюха. Как это реализовать я не знаю, но пара идей есть. 
1) понюхав вещь/куклу/кровь пëс выбирает запах из списка тех, кто с этим чем-то контактировал и вносит их в свой пулл памяти и может переключаться между искомыми объектами и при выборе одного из них внутренний пинпоинтер будет работать на цель. Например обнюхав состав СБ в начале раунда Робаст без труда найдет Вардена напившегося в баре, а обнюхав кровь сможет найти труп бедного ГП в техах.  Однако обнюхав не куклу Робаст не будет знать кого именно он учуял если конечно этого кого-то небыло в пулле памяти запахов. Пулл запаха предлагаю не ограничивать, ибо если пёс не может понять кого искать из-за незнания языка, то и им баланса не будет. Всё ещё нужно будет иметь вещь искомого или его кровь чтобы чётко дать псу знать в какую сторону нюхать. 
2) Дать Робасту визуализацию запахов а-ля термалы которые показывают смутный образ кукол и вполне чёткий образ колбасы на кухне (кстати можно объединить с первым пунктом с некоторыми условностями. 
Бипски недолюбливает Робаста и при визуальном контакте будет высказывать своё негодование из ревности, но это не точно

Любимая еда Робаста - сосиски, но он может спокойно кушать любую другую еду для утоления голода. Однако сосиски или колбаса лечат Робаста и воспроизводят над его текстуркой анимацию розовых сердечек.  Если в радиусе экрана где-то появилась колбаса или сосиски, то псу приходит уведомление об этом. Если пёс сильно голоден, то сообщение даст ему понять, что рядом его любимое лакомство и вы ОЧЕНЬ сильно его хотите. 
Хозяином Робаста по умолчанию должен быть Варден? ГСБ? Детектив? Или Робаст не имеет таковых и спаунится вместе с офицерами?  Мне кажется, что кинологом может быть детектив, но тут нужен геймдизайн. 
Робаст имеет два интернета как у боргов: хэлп и харм. На хэлпе по куклам он будет лизаться и тыкаться носом, а на харме кусать. Любимая игрушка Робаста - обувь, на харме он будет швырять её в рандомные стороны с шансом на уничтожение этой самой обуви оставляя от неё лишь тряпку или мусор. 

Робаст не сможет самостоятельно открывать шлюзы для которых нужен доступ или же Робаст будет иметь обычный СБ доступ? Хороший вопрос, присылайте свои варианты ответа. 
Робаст очень верный пёс и не предаст своих офицеров, однако есть способ обратить его на сторону антагонистов и это культ. Если каким-то образом культистам удастся обратить Робаста в культ, то пёс сменит свою текстуру на зловещую, хп увеличатся и пёс получит способность хоть и медленно, но выбивать шлюзы и не укреплённые стены. 

Как повод подзаебаться предлагаю вставить псу распознавание определённых слов подобно кодовым словам у предателей. Так Робаст сможет понимать, что он хороший мальчик и что клоуну нужно откусить задницу. 
Примерный набор команд:
Фас - напасть на цель или агрессора
Фу - отменить прошлую команду или указать псу, что он поступает плохо
Молодец - похвалить пса
Ко мне - подозвать Робаста
Сидеть - приказать псу встать и ожидать другой команды
Гуляй - отпустить пса по своим делам
Защита - приказать Робасту следовать за целью и нападать на тех, кто по мнению пса опасен для охраняемого объекта
Ищи - дать псу понять, что что-то или кто-то потерялось и это нужно найти
Робаст - пёс же знает своё имя и будет на него реагировать. 
У пса будет своя лежанка в Бриге и команда "Место" Призывает пса идти на лежанку (кстати ещё один возможный способ хила пса, лёг на мягкую лежанку и медленно восстанавливает хп) 

Этот иссуй не завершён и находится на стадии допиливания. Автор надеется на отзывы, в том числе и на критику.

**Comment by TimErmolt** [comment]
Зачем настолько сложные механики одного пса, который по сути является массивным баффом для СБ (игрок в оболочке собаки с возможностью найти что угодно и кого угодно на станции, немного понёрфленными термалами, рентгеновским зрением через одежду, таклом, бегающий на спидах и способный приносить офицерикам оружие), в котором она явно не нуждается? А кому-то ещё всё это кодить, отлаживать и потом балансить, когда после обновления сервера что-то непременно будет сломано.

Лучше уж, если хочется робастных зверушек, добавить к ХоСу в кабинет того же пса или паука, который будет его питомцем (ХоСа и капитана в этом плане обделили) и будет драться с входящими в кабинет, кроме СБшников. Ну, можно ещё сделать, чтобы дрался с находящимися в розыске, на случай если будет желание его выгулять с пользой. Естественно, не слишком робастно, на уровне козла какого-нибудь.

**Comment by DarkHunter7756** [comment]
аэээ, может просто создадим профу собаки, знающую галактик коммон (не способную на нем говорить), имеющую условный слот под предмет и спавнящуюся у кабинки ХоСа/Вардена? Пускай у нее будет не так много ХП, но достаточно скорости.

**Comment by TimErmolt** [comment]
Мне не очень нравится идея добавлять ещё один слот для игрока в охрану в целом. Даже если это практически симплмоб-собака, всё равно симплмоб под контролем игрока -- это гораздо больше, чем просто рандомно бродящий по кабинету или бригу. Просто моба -- пожалуйста (хоть и здесь следует знать меру), а вот управляемых игроком не надо.

**Comment by Sudar0770** [comment]
> аэээ, может просто создадим профу собаки, знающую галактик коммон (не способную на нем говорить), имеющую условный слот под предмет и спавнящуюся у кабинки ХоСа/Вардена? Пускай у нее будет не так много ХП, но достаточно скорости.

Я поддерживаю идею, чтобы пëс мог понимать речь, но это сделает из игрока на псе настоящего метагеймера который по первому требованию офицера сразу побежит искать Антонова Антона Ассистента. А так пёс будет небольшим подспорьем ибо офицер для поиска должен будет положить перчатки подозреваемого перед псом и сказать "ищи".
Это обделит Мистера Димпси, ибо тот не может говорить на коммоне и зачастую даже бармен не знает обезъяний.

**Comment by Sudar0770** [comment]
> Зачем настолько сложные механики одного пса, который по сути является массивным баффом для СБ (игрок в оболочке собаки с возможностью найти что угодно и кого угодно на станции, немного понёрфленными термалами, рентгеновским зрением через одежду, таклом, бегающий на спидах и способный приносить офицерикам оружие)

Я предлагаю способности пса с точки зрения логики. Однако я не геймдизайнер и альтернативы тех или иных фич можно рассмотреть и обсудить. Да, пёс перегружен механиками и если честно, то на мой взгляд псу хватит такла и пинпоинтера на пулл памяти запахов. Пёс должен быть не жирным усилением СБ, а небольшим подспорьем со своими минусами и нелепыми РП ситуациями.

**Comment by ArmolitskiyCarpoeb** [comment]
Комиссар рекс
