### ISSUE TITLE
Не пофиксилось спонтанное видение людей и вещей сквозь стены

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#9812]
> Больше не отображаются мобы и предметы, которые вы не должны видеть.
 #9776

Чёт не очень.
![image](https://user-images.githubusercontent.com/60045066/199554347-dc2e26d1-655e-40d3-9ea7-e6d01077f67c.png)

**Comment by TimErmolt** [comment]
Иногда даже НЕСКОЛЬКИХ человек видно сквозь стену. При этом они ходят, разговаривают, иногда стреляют -- а их видно. Мне так билд отряд нюкеров, собирающийся штурмовать отдел, спалил.

**Comment by igorsaux** [comment]
https://github.com/ChaoticOnyx/OnyxBay/issues/8662
