### ISSUE TITLE
Спрайты для некроманта

### ISSUE THREAD

**Issue by Zert0X** [ChaoticOnyx/OnyxBay#9846]
#6619

Тупая бюрократия сената требует отдельный иссуй для спрайтеров.
Нужны:
1. Мясной голем
2. Костяной голем
3. Форма лича, можно посмотреть на Evil Pope.
4. Иконки для абилок
5. Спрайт упыря

**Все мобы - СИМПЛМОБЫ**
Кроме лича, лич должен быть хуманом то есть с отдельными конечностями, хотя тут хз

**Comment by Terydd** [comment]
Чем 
![image](https://user-images.githubusercontent.com/91453615/201599526-b8240f77-89ed-412a-93c8-e6444dae20e0.png)
не подходит под (1.Мясной голем)?

**Comment by ArmolitskiyCarpoeb** [comment]
За рубли насрайчу классных симплмобов

**Comment by Tsurupeta** [comment]
Рублей нет, но вы держитесь

**Comment by ArmolitskiyCarpoeb** [comment]
Ладно, давайте тогда кастомку "пульсач"

**Comment by Medjic** [comment]
Почти дорисовал. Хуй.

**Comment by Tsurupeta** [comment]
Меджи за это получит целых 100 опиксов

**Comment by Medjic** [comment]
![image](https://user-images.githubusercontent.com/75128764/203799123-c3c02dec-159c-41db-a327-92edaf87ea8c.png)

**Comment by Zert0X** [comment]
Одобряю иконочки мне нравится

**Comment by Epicus7** [comment]
Награда выдана
