### ISSUE TITLE
Несоответствие описания мультитула и реальности

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#9861]
В описании мультитула пишется, что он сделан из диэлектрического пластика:
https://github.com/ChaoticOnyx/OnyxBay/blob/da2412f856de918b7a1625b47432710f648f2b5b/code/game/objects/items/devices/multitool.dm#L8
Тем не менее, работая мультитулом с проводами, удар током ты всё равно получаешь в полной мощности, хотя его описание явно говорит, что не должен.

### Решение
Либо убрать слова про диэлектрический материал из описания мультитула, либо сделать так, чтобы при работе им нельзя было быть шандарахнутым, либо снижать мощность получаемого разряда.
Учитывая, что мультитул является первым инструментом для взлома дверей и вендоматов, а напечатать его можно на любом автолате и даже найти в техах или ассистентской, думаю, лучше всё-таки поменять описание.

**Comment by No-Tips** [comment]
Май хонест реакшн ту улучшение:
🤓🤓🤓🤓
