### ISSUE TITLE
Абдуктор умирает изза гланды

### ISSUE THREAD

**Issue by HeAPTEM** [ChaoticOnyx/OnyxBay#9864]
**### Описание бага**
За абдуктора при имплантации гланды производящей плазму в виде газа ослепляет самого абдуктора, а также при снятии наручников когда испытуемого отправляют на станцию обратно когда снимаються наручники они искрятся и поджигают плазму тем самым убивая абдуктора

**### Воспроизведение**
Шаги чтобы воспроизвести баг:
1. Берем гланду плазмы
2. Имплантируем пациенту
3. Закрываем рану
4. Плазма произведена на шатле абдуктора

### Ожидаемое поведение
отсутствует

### Скриншоты
отсутствует

### (Опционально) Дополнительная информация
отсутствует

### (Опционально) Характеристики
 - OS:Windows 10
 - Версия клиента (не нашел) но самая новая
 - Версия сервера Server Revision: 2e02fad116f279105439f03593ba9ea9720bd5d8 - 5439f03593ba9ea9720bd5d8 - 2022-11-02
 - ID игры Game ID: ckY-ccF0

**### Идея как решить (сам добавил)**
Зделать скрипт на активацию гланды только после сканирования и отравки испытуемого на станцию

**Comment by HeAPTEM** [comment]
Может это и улучшение но я не смог решить что выбрать

**Comment by Zert0X** [comment]
Вы как долго держали испытуемого на корабле... Я бы сказал скил исью абдукторов, но гланда вроде и должна активироваться после отправки мб я налажал когда пилил

**Comment by HeAPTEM** [comment]
я максимально быстро вставил имплант и как только закрыл живот сразу плазма пошла

**Comment by Zert0X** [comment]
Абдукторы выпилены #11479
