### ISSUE TITLE
Абдукторский пистолет срёт болью до конца раунда

### ISSUE THREAD

**Issue by TimErmolt** [ChaoticOnyx/OnyxBay#9880]
# Описание бага
Попали в тебя -- до конца раунда ты черепаха. На кукле показывается повреждение поражённой части тела, но физических повреждений нет, как и внутренних. Врачи разводят руками и ничего не могут сделать, кроме как накачать обезболивающим, на котором тебе придётся жить весь раунд. Либо же страдать от урезанной вдвое, а то и больше, скорости ходьбы. Лечится, наверное, только стазисом генокрада или педальным реджувом. Ну или заменой конечности, но это уже совсем смешно.

**Comment by Devyashka** [comment]
Проблема в том, что абдукторский пистолет наносит генетический урон, который многие не замечают в сканере.

**Comment by Nod404** [comment]
генетический урон всему виной
