### ISSUE TITLE
Нерф стингов генокрада

### ISSUE THREAD

**Issue by Ruforce** [ChaoticOnyx/OnyxBay#99]
На данный момент:
1. Дедстинг практически моментально уничтожает ВСЕ органы.
2. Пробивают любую броню.

**Comment by ZerlGray** [comment]
Я вообще во много что не смог.
Но они пробивают броню только тогда, когда ты целишься туда, где нет брони. Что в целом так то логично.

**Comment by ZerlGray** [comment]
И вообще - не нравится - фикси сам :) Сам механ работы стингов я не трогал, так что пошев нахой

**Comment by Cinericius** [comment]
Я щас скажу крамольное, но может вообще выпилить стинги? Ну кроме разве что фальшивых армблейдов, трансформ-стинга (все время забываю, есть ли он у нас) и ДНК-заборника. Крч оставить только стинги с "интересными" эффектами, а банальщину типа ослеплялок-убивалок убрать найух.

**Comment by Cinericius** [comment]
Это побудит игроков играть интереснее и юзать всякие новые абилки типа саморасчленения, а не тупа заплевывать иглами из инвиза.

**Comment by Epicus7** [comment]
Может быть лучше повысить стоимость стингам просто? Ограничить каким-то образом использование еще можно. Например, добавить шанс, что ты сам отравишься, а не выстрелишь стингом.

**Comment by ZerlGray** [comment]
Я уже понерфал дедстинг. Просто в игре нерфа нет. Он в дев ветке.

**Comment by Cinericius** [comment]
Не ну, а нужен ли вообще этот механ стингов? Он, конечно, классический, но мы вполне можем от него отказаться. Причем можно не убирать стинги совсем, а сделать их педальной абилкой. Будет все плохо без них - вернем назад, чо.

**Comment by Ruforce** [comment]
сейчас игра за геносоа представляет из себя увлекательный квест по отжору макак из ксенобиологии в первой половине раунда и "пресс стинг ту вин" во второй.

**Comment by Cinericius** [comment]
Давайте эксперимента ради уберем все стинги (кроме "интересных") на неделю в педальные абилки. Ну то есть тупа их из меню покупки уберем.

**Comment by Epicus7** [comment]
Стинги выпилены: 4c6776ebc43983ec41fba0a0940283d3c77c9352
