### ISSUE TITLE
Получение бесконечных ресурсов и мощной машинерии

### ISSUE THREAD

**Issue by Battleparrot** [ChaoticOnyx/OnyxBay#9934]
### Описание бага
Бесконечные ресурсы и мощная машинерия

### Воспроизведение
Шаги чтобы воспроизвести баг:
Принцип бага прост:  вы разбираете машинерию и собираете обратно, до момента прикручивания отвёрткой, и снова разбираете и собираете (пока не надоест). Значения элементов стакаются, что позволяет забустить пролат до минусовых значений материалов (по сути при печати тебе пролат сам даёт ресурсы). Работает на всю машинерию с компонентной базой: пролат, автолат, фабрикатор, охладитель/нагреватель, ПАКМАНЫ, СМЕСЫ, генератор щитов и т.п

**Comment by Tsurupeta** [comment]
Опять звягин

**Comment by NoneOfYourBsns** [comment]
Если этот баг не исправили, то я бы попросил составителя иссуя присоединиться к обсуждению и объяснить принцип, желательно с визуальной демонстрацией. Я десять раз пересобрал протолат, но каких-то минусовых значений получить не удалось. При быстром анализе кода понять природу данной ошибки мне не удалось.
