### ISSUE TITLE
Нимфы сломаны

### ISSUE THREAD

**Issue by Traysoul** [ChaoticOnyx/OnyxBay#998]
### Описание бага
Нимфы сломаны. Нельзя стать убер-дионой. Нельзя выбросить предмет, который взял. Что можно: ползти за штукатурку(в вентиляцию), спрятаться и прыгнуть к другой нимфе видимо от разделения которого нет. Ну и растения удобрять.

### Воспроизведение
Шаги чтобы воспроизвести баг:
1. Берем нимфу
2. Тестим

Ожидаемое поведение(можете не читать)
я блять взял нимфу блять я удобрял  блять я поливал эти растения нахуй и пришлось мне от сорняков их немножко очистить блять и бросить в мусорку нахуй и потом в комнате ещё сидеть блять и всё это заняло время бля вооот сейчас надо пойти писать иссуй блять такая вот хуйня это всё из-за тестеров блять тестеры типа нихуя не делают во всех смыслах этого слова ебать
![PicsArt_09-28-10 47 07](https://user-images.githubusercontent.com/58553282/70437430-a4c7cf80-1a9c-11ea-96c0-bc07c875e230.jpg)

**Comment by kreeperHLC** [comment]
Для убер Дионы нужно как минимум две нимфы

**Comment by Traysoul** [comment]
Поясни, две нимфы-игрока? И один из них становится дионой?

**Comment by kreeperHLC** [comment]
Можно и вторую нимфу без игрока, просто кликаешь (?) по второй за первую и объединяешься. А там уже голосованием между активными дионами можно стать человекоподобной с управлением нескольких игроков

**Comment by Traysoul** [comment]
Получается, если ты одна нимфа, то ты обречён сосать бибу до конца раунда?

**Comment by kreeperHLC** [comment]
Засоси диону без разума и все нормас будет

**Comment by Epicus7** [comment]
Чо, в итоге что сломано то?

**Comment by Traysoul** [comment]
Ничего не сломано видимо, но теперь очень сложно стать дионой. Просто почитай весь процесс.

**Comment by kreeperHLC** [comment]
Ну тогда закрываем
