### ISSUE TITLE
Нерф самопалов через рандом

### ISSUE THREAD

**Issue by Kostil** [ChaoticOnyx/OnyxBay#9997]
### Улучшение
Все самопалы - крайне хорошее оружие собранное на коленке. По факту без каких либо минусов. 

### Решение
Добавить им простой минус - возможность взорваться в руке при выстреле или сделать осечку с пустым отстрелом и необходимостью "вытаскивать пулю" из ствола отвёрткой. Это не покупной ствол или что-то в этом роде. Хотим надёжность - покупаем или пиздим с арсенала

### Шансы
не сильных 10 процентов хватит, чтобы ассистухи морально понимали - что с этими штуками будет вероятность выстрелить себе в ногу. Не говорю уже о том, чтобы долго использовать их в перестрелке

**Comment by TimErmolt** [comment]
> Все самопалы - крайне хорошее оружие собранное на коленке. По факту без каких либо минусов.

Их главный минус -- однозарядность. Только у кустарного дробовика есть возможность зарядить два патрона, и то не все до этого догадываются. Зипган и арбалет заряжаются только по одному патрону. На перезарядку уходит достаточно времени, чтобы кто угодно мог запушить и ухерачить дубинкой или тазером.

Да и вообще сейчас при сопоставлении СБ и станционной швали (антаги не в счёт) СБ побеждает с хорошим отрывом. У охраны пушки, смертоносные и нет, броня, локальный лазарет в отделе, термал-очки и камеры. У швали только самоделки и барменская двустволка. При ограблении арсенала у тебя всегда есть вероятность получить либо дубинкой в жопу, либо ПМку от вахтёра с педалями, если ты не инженер, ибо единственный способ грабить скрытно -- из космоса через р_стены. Можно заказать через карго, но там могут спалить и по анонсу, и по камерам, и ещё надо уговорить кого-то заказать -- хрен ты это сделаешь, если не найдётся в карго трейтора. Короче говоря, сейчас получить оружие гарантированно без палева можно только самоделками.

А, ну и да, ещё удачи крафтить самопалы, если уборщик (или кто-то ещё) спрятал все мышеловки или носит их с собой и никому не отдаёт.

ТЛ;ДР: Сиё есть нёрф станционной швали; нёрф станционной швали не нужен. ОП солевой СБ-мэйн.

**Comment by Kostil** [comment]
> Их главный минус -- однозарядность. Только у кустарного дробовика есть возможность зарядить два патрона, и то не все до этого догадываются. Зипган и арбалет заряжаются только по одному патрону. На перезарядку уходит достаточно времени, чтобы кто угодно мог запушить и ухерачить дубинкой или тазером.

А у товарища уже торчит шрапнель в заднице, а ассистуха достаёт из широких штанин ещё два припасённых в сумке самострела и продолжает геймплей - выстрелился - убежал, перезарядился.
И да, удачи пушить на 357, что с одного выстрела оторвёт ногу

>При ограблении арсенала у тебя всегда есть вероятность получить либо дубинкой в жопу, либо ПМку от вахтёра с педалями, если ты не инженер

А я не только про безрольковых говорю. Вот только ради награды ты пытаешься создать движ в раунде, а не скрысить пару мышеловок у уборщика

>и ещё надо уговорить кого-то заказать -- хрен ты это сделаешь, если не найдётся в карго трейтор

ой, игра начинается про социалочку или хитрость, а не про пушечки

**Comment by Medjic** [comment]
Poshol na huy, ficha going govno. Do shidaniya.

**Comment by FloweYStyle** [comment]
Извините но билд и так полумертвый стоит и раунды грузит медленнее чем раньше, да и лагает ощутительно больше. Я не думаю, что народу нужно добивать билд бессмысленным нерфом самопала. Как ОПу уже сказали, у самопала прилично минусов, а потому нерфить их потому что "я скозал" - идея сомнительная. У щиткурити есть все пушечки чтобы противодействовать этим так называемым самопалам, есть все бронники чтобы после выстрела не откиснуть от остановки сердца и есть все банки трамадола чтобы при этом ещё и раздать маслин в ответ. Нерфоцирк не нужен, уже видели это говно на пчелках, тгшках и много много где ещё, да и метод нерфа, литералли ввод ОЧЕРЕДНОГО рандома в билд, который и так кишит рандомной боевкой и прочим прочим, что не очень хотелось бы видеть в билде. ОП признайся, что тебя убили с самопала и ты решил открыть из-за этого иссуй, иначе я реально не понимаю, как к такому нерфу можно было придти.
